Repository magento/devdocs, pull requests merged in 2018-09, with the labels that each got.

#2856 removes <span> tag and "mandatory element" on html-tag
  guides/v2.1/frontend-dev-guide/layouts/layout-types.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2852 Fixed small typo in config for enabling apcu extension.
  guides/v2.0/config-guide/prod/prod_perf-optimize.md
  guides/v2.1/config-guide/prod/prod_perf-optimize.md
Labels: 2.0.x, 2.1.x, Editorial

#2862 MFTF 2.3.6 content update: Added line for testCaseId being prepended to title.
  guides/v2.2/magento-functional-testing-framework/2.3/test/annotations.md
Labels: 2.2.x, 2.3.x, Technical

#2858 Fixes incorrect rendering of PHP version tables in system requirements.
  _includes/install/php_2.0.md
  _includes/install/php_2.1.md
  _includes/install/php_2.2.md
  _includes/install/php_2.3.md
  guides/v2.1/install-gde/prereq/php-centos.md
  guides/v2.1/install-gde/prereq/php-ubuntu.md
  guides/v2.2/install-gde/prereq/php-centos.md
  guides/v2.2/install-gde/prereq/php-ubuntu.md
  guides/v2.2/install-gde/system-requirements-tech.md
  guides/v2.3/install-gde/prereq/php-centos-ubuntu.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2853 Link to advanced-setup went to a markdown file instead of a html file…
  guides/v2.2/performance-best-practices/hardware.md
Labels: 2.2.x, 2.3.x, Editorial

#2863 MFTF 2.3.6: Add skipReadiness to MFTF actions
  guides/v2.2/magento-functional-testing-framework/2.3/test/actions.md
Labels: 2.2.x, 2.3.x, Technical

#2864 Update bad links and remove invalid files
  guides/v2.0/contributor-guide/contributing_docs_suggested.md
  guides/v2.0/contributor-guide/templates/basic_template.md
  guides/v2.0/howdoi/bk-how-do-i.md
  guides/v2.0/howdoi/howdoi_contribute.md
  guides/v2.0/howdoi/howdoi_template.md
  guides/v2.1/contributor-guide/contributing_docs_suggested.md
  guides/v2.1/contributor-guide/templates/basic_template.md
  guides/v2.1/howdoi/bk-how-do-i.md
  guides/v2.1/howdoi/howdoi_contribute.md
  guides/v2.1/howdoi/howdoi_template.md
  guides/v2.2/howdoi/bk-how-do-i.md
  guides/v2.2/howdoi/howdoi_contribute.md
  guides/v2.2/howdoi/howdoi_template.md
  guides/v2.3/howdoi/bk-how-do-i.md
  guides/v2.3/howdoi/howdoi_contribute.md
  guides/v2.3/howdoi/howdoi_template.md
  guides/v2.3/rest/operation-status-endpoints.md
  guides/v2.3/rest/operation-status-search.md
Labels: 2.x, Editorial

#2840 MFTF 2.3.6: Add an option to the 'mftf' CLI to remove previously generated suites and tests
  guides/v2.2/magento-functional-testing-framework/2.3/commands/mftf.md
Labels: 2.2.x, 2.3.x, Technical

#2865 Add link to Configure services as web APIs
  guides/v2.1/get-started/authentication/gs-authentication.md
Labels: 2.x, Editorial

#2867 Update 'Whats New on DevDocs'
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2841 Document MSI REST endpoints
  _data/toc/inventory.yml
  _data/toc/msi.yml
  _data/toc/rest-api.yml
  _includes/layout/sidebar.html
  guides/v2.3/rest/modules/inventory/bulk-inventory.md
  guides/v2.3/rest/modules/inventory/link-stocks-sources.md
  guides/v2.3/rest/modules/inventory/manage-source-items.md
  guides/v2.3/rest/modules/inventory/manage-sources.md
  guides/v2.3/rest/modules/inventory/manage-stocks.md
  guides/v2.3/rest/tutorials/msi-order-processing/assign-source-to-stock.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-sources.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-stock.md
Labels: 2.3.x, New doc

#2871 GH2861 - Update directory per dev feedback
  _includes/install/sampledata/sample-data-clone.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2870 Add attribute_options object
  guides/v2.3/graphql/reference/custom-attribute-metadata.md
Labels: 2.3.x, Community, Technical

#2879 Fixed broken link
  guides/v2.2/performance-best-practices/configuration.md
Labels: 2.2.x, 2.3.x, Editorial

#2878 Fixed table output
  _includes/install/web/install-web_3-web-conf.md
Labels: 2.0.x, Editorial

#2874 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2881 Add config types and note about system settings
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-export.md
Labels: 2.2.x, 2.3.x, Community, Major update

#2882 Update for issue 2876
  guides/v2.3/get-started/web-api-functional-testing.md
Labels: 2.3.x, Technical

#2883 replaced deprecated composer flags
  _includes/install/releasenotes/ce_install_20.md
  _includes/install/releasenotes/ce_install_21.md
  _includes/install/releasenotes/ee_install_20.md
  _includes/install/releasenotes/ee_install_21.md
  guides/v2.0/install-gde/install-quick-ref.md
  guides/v2.0/install-gde/prereq/integrator_install_ce.md
  guides/v2.0/install-gde/prereq/integrator_install_ee.md
  guides/v2.0/release-notes/ReleaseNotes2.1_RC1CE.md
  guides/v2.0/release-notes/ReleaseNotes2.1_RC1EE.md
  guides/v2.0/release-notes/ReleaseNotes2.1_RC2CE.md
  guides/v2.0/release-notes/ReleaseNotes2.1_RC2EE.md
  guides/v2.1/install-gde/install-quick-ref.md
  guides/v2.2/install-gde/install-quick-ref.md
  guides/v2.3/install-gde/install-quick-ref.md
Labels: 2.x, Technical

#2810 [MFTF 2.3.6] Added the MAGENTO_CLI_COMMAND_PATH configuration parameter
  guides/v2.2/magento-functional-testing-framework/2.3/configuration.md
Labels: 2.3.x, Technical, internal-dev

#2885 Filter out GraphQL product attributes
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.x, Community, Technical

#2799 Corrected description for SCD_STRATEGY compact
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
Labels: 2.2.x, 2.3.x, Technical

#2892 Ss remove dev box
  guides/v2.0/install-gde/docker/docker-commands.html
  guides/v2.0/install-gde/docker/docker-over.html
  guides/v2.0/install-gde/docker/docker-phpstorm-debug.html
  guides/v2.0/install-gde/docker/docker-phpstorm-parent.html
  guides/v2.0/install-gde/docker/docker-phpstorm-prereq.html
  guides/v2.0/install-gde/docker/docker-phpstorm-project.html
  guides/v2.0/install-gde/docker/docker-phpstorm-test.html
  guides/v2.0/install-gde/docker/docker-ref.html
  guides/v2.0/install-gde/docker/docker-trouble.html
  guides/v2.1/install-gde/docker/docker-commands.html
  guides/v2.1/install-gde/docker/docker-over.html
  guides/v2.1/install-gde/docker/docker-phpstorm-debug.html
  guides/v2.1/install-gde/docker/docker-phpstorm-parent.html
  guides/v2.1/install-gde/docker/docker-phpstorm-prereq.html
  guides/v2.1/install-gde/docker/docker-phpstorm-project.html
  guides/v2.1/install-gde/docker/docker-phpstorm-test.html
  guides/v2.1/install-gde/docker/docker-ref.html
  guides/v2.1/install-gde/docker/docker-trouble.html
  guides/v2.2/install-gde/docker/docker-commands.html
  guides/v2.2/install-gde/docker/docker-over.html
  guides/v2.2/install-gde/docker/docker-phpstorm-debug.html
  guides/v2.2/install-gde/docker/docker-phpstorm-parent.html
  guides/v2.2/install-gde/docker/docker-phpstorm-prereq.html
  guides/v2.2/install-gde/docker/docker-phpstorm-project.html
  guides/v2.2/install-gde/docker/docker-phpstorm-test.html
  guides/v2.2/install-gde/docker/docker-ref.html
  guides/v2.2/install-gde/docker/docker-trouble.html
  guides/v2.3/install-gde/docker/docker-commands.html
  guides/v2.3/install-gde/docker/docker-over.html
  guides/v2.3/install-gde/docker/docker-phpstorm-debug.html
  guides/v2.3/install-gde/docker/docker-phpstorm-parent.html
  guides/v2.3/install-gde/docker/docker-phpstorm-prereq.html
  guides/v2.3/install-gde/docker/docker-phpstorm-project.html
  guides/v2.3/install-gde/docker/docker-phpstorm-test.html
  guides/v2.3/install-gde/docker/docker-ref.html
  guides/v2.3/install-gde/docker/docker-trouble.html
Labels: 2.x

#2869 MAGEDOC-3119: m1.x end of support messaging
  _includes/m1x/eol_message.html
  _layouts/m1x.html
  _layouts/m1x_rest.html
  _layouts/m1x_soap.html
  common/css/stylesheet.css
  guides/m1x/ce18-ee113-home.html
  guides/m1x/ce18-ee113/EE113-benchmark.html
  guides/m1x/ce18-ee113/ce1.8_release-notes.html
  guides/m1x/ce18-ee113/ee1.13_release-notes.html
  guides/m1x/ce18-ee113/using_redis.html
  guides/m1x/ce19-ee114-home.html
  guides/m1x/ce19-ee114/RWD_dev-guide.html
  guides/m1x/ce19-ee114/RWD_responsive_emails.html
  guides/m1x/ce19-ee114/ce1.9_release-notes.html
  guides/m1x/ce19-ee114/ee1.14_release-notes.html
  guides/m1x/ce19-ee114/ios-instrux.html
  guides/m1x/install/installer-privileges_after.html
  guides/m1x/install/installer-privileges_before.html
  guides/m1x/install/installing.html
  guides/m1x/install/installing_install.html
  guides/m1x/install/installing_req-prereq_centos.html
  guides/m1x/install/installing_req-prereq_ubuntu.html
  guides/m1x/install/installing_upgrade_ce18_upgrade-roadmap.html
  guides/m1x/install/installing_upgrade_details.html
  guides/m1x/install/installing_upgrade_from-ee112.html
  guides/m1x/install/installing_upgrade_from-ee11300-or-01.html
  guides/m1x/install/installing_upgrade_landing.html
  guides/m1x/magefordev/mage-for-dev-1.html
  guides/m1x/magefordev/mage-for-dev-2.html
  guides/m1x/magefordev/mage-for-dev-3.html
  guides/m1x/magefordev/mage-for-dev-4.html
  guides/m1x/magefordev/mage-for-dev-5.html
  guides/m1x/magefordev/mage-for-dev-6.html
  guides/m1x/magefordev/mage-for-dev-7.html
  guides/m1x/magefordev/mage-for-dev-8.html
  guides/m1x/other/appsec-900_addhandler.html
  guides/m1x/other/discover-card-validation.html
  guides/m1x/other/ee_connect_patches.html
  guides/m1x/other/ht_extend_magento_rest_api.html
  guides/m1x/other/ht_install-patches.html
  guides/m1x/other/ios-instrux.html
  guides/m1x/other/payflow.html
  guides/m1x/other/php5.4_patch.html
  guides/m1x/other/remote-code-exploit.html
  guides/m1x/other/solr-ee-patches.html
Labels: 1.x, Editorial

#2894 Fix broken code formatting and image in layout-practice.md
  guides/v2.1/frontend-dev-guide/layouts/layout-practice.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2860 corrected extension spelling
  guides/v2.1/ui_comp_guide/components/ui-fileuploader.md
  guides/v2.2/ui_comp_guide/components/ui-fileuploader.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2895 MAGEDOC-3119: Revise support notice title
  _includes/m1x/eol_message.html
Labels: 1.x

#2896 Fixed typo mistakes
  guides/v2.0/ext-best-practices/storefront/storefront-best-practices.md
  guides/v2.2/config-guide/redis/redis-session.md
Labels: 2.0.x, 2.1.x, 2.2.x, Editorial

#2899 Edit di.xml file page
  guides/v2.1/extension-dev-guide/build/di-xml-file.md
  guides/v2.2/extension-dev-guide/build/di-xml-file.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2898 MAGECLOUD-2707: Fixed transposed IP address tables
  guides/v2.1/cloud/env/environments-start.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2905 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2909 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/commerce/2.2.0-develop.html
Labels: 2.3.x, Technical

#2911 Update 'What's New on Devdocs'
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2872 MAGECLOUD-2542 Update Cloud welcome
  _data/main-nav.yml
  _data/toc/cloud-guide.yml
  _includes/layout/navigation.html
  common/images/cloud/CloudBenefits.svg
  common/images/cloud/CloudFastly.png
  common/images/cloud/CloudStack.png
  common/images/cloud/CloudStack.svg
  guides/v2.1/cloud/architecture/cloud-architecture.md
  guides/v2.1/cloud/basic-information/cloud-plans.md
  guides/v2.1/cloud/bk-cloud.md
  guides/v2.1/cloud/live/live-sanity-check.md
  guides/v2.1/cloud/onboarding/onboarding-portal.md
  guides/v2.2/cloud/basic-information/cloud-plans.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.3/cloud/basic-information/cloud-plans.md
Labels: 2.x, Major update

#2893 Document storeConfig endpoint
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/store-config.md
Labels: 2.3.x, Community, New doc

#2912 Publish REST schema for 2.3 beta
  swagger/index.html
  swagger/index_23.html
  swagger/schemas/latest-2.3.schema.json
Labels: 2.3.x, Technical

#2914 Update caps in Cloud nav
  _data/main-nav.yml
Labels: Editorial

#2915 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2919 GH1688 - Add message about developer mode for dev configs
  guides/v2.2/performance-best-practices/configuration.md
Labels: 2.2.x, 2.3.x, Major update

#2922 fix typos
  guides/v2.2/performance-best-practices/software.md
  guides/v2.3/performance-best-practices/software.md
Labels: 2.2.x, 2.3.x, Editorial

#2920 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2928 Add space between and
  _videos/fundamentals/create-a-new-module.md
Labels: Editorial

#2930 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2918 GH2917 - Add note on accepted PRs in code and metadata for template
  _includes/contributor/2-1-end.md
  _includes/contributor/2-2-submission.md
  _includes/contributor/2-3-submission.md
  _includes/contributor/pull-request-table.md
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/contributor-guide/templates/basic_template.md
  guides/v2.1/contributor-guide/templates/tutorial-template-first.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.x, Major update

#2932 udUpdate schema to include MSI
  swagger/schemas/latest-2.3.schema.json
Labels: 2.3.x, Technical

#2908 MAGECLOUD-2681 Explain Docker
  _data/main-nav.yml
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/access-acct/first-time-setup.md
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/reference/docker-config.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-development.md
  guides/v2.2/cloud/reference/docker-config.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/docker/docker-config.md
  guides/v2.3/cloud/docker/docker-development.md
  guides/v2.3/cloud/reference/docker-config.md
Labels: 2.1.x, 2.2.x, 2.3.x, In progress, Major update

#2835 MFTF 2.3.6 updates
  guides/v2.2/magento-functional-testing-framework/2.2/getting-started.md
  guides/v2.2/magento-functional-testing-framework/2.2/suite.md
  guides/v2.3/magento-functional-testing-framework/2.3/commands/codeception.md
  guides/v2.3/magento-functional-testing-framework/2.3/commands/mftf.md
  guides/v2.3/magento-functional-testing-framework/2.3/configuration.md
  guides/v2.3/magento-functional-testing-framework/2.3/data.md
  guides/v2.3/magento-functional-testing-framework/2.3/getting-started.md
  guides/v2.3/magento-functional-testing-framework/2.3/introduction.md
  guides/v2.3/magento-functional-testing-framework/2.3/suite.md
  guides/v2.3/magento-functional-testing-framework/2.3/test/actions.md
  guides/v2.3/magento-functional-testing-framework/2.3/test/annotations.md
  guides/v2.3/magento-functional-testing-framework/2.3/update.md
Labels: 2.2.x, 2.3.x, Technical

#2934 Hg quickfix
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Editorial

#2926 Antonkril patch 3
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
Labels: Technical

#2925 Update index.md
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
Labels: Technical

#2924 Update component status page
  guides/v2.3/release-notes/component-status.md
Labels: 2.3.x

#2936 Ss escapedchar
  _includes/config/setup-cron.md
  _includes/config/setup-cron_2.2_how-to.md
Labels: 2.0.x, Editorial

#2937 Weekly digest
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2927 BIC: Add the StoreResolve deprecation section
  guides/v2.3/release-notes/backward-incompatible-changes/index.md
Labels: 2.3.x, Technical

#2939 MFTF 2.3.6: Add peer review edits
  guides/v2.3/magento-functional-testing-framework/2.3/commands/codeception.md
  guides/v2.3/magento-functional-testing-framework/2.3/commands/mftf.md
  guides/v2.3/magento-functional-testing-framework/2.3/configuration.md
  guides/v2.3/magento-functional-testing-framework/2.3/getting-started.md
  guides/v2.3/magento-functional-testing-framework/2.3/suite.md
Labels: 2.3.x, Editorial

#2938 Removed double occurrences
  guides/v2.1/cloud/project/new-relic.md
  guides/v2.1/migration/migration-overview-how.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2EE.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: Editorial

#2948 Fix code indentation
  _includes/install/allowoverrides24.md
Labels: 2.x, Editorial

#2942 &lt change to < and bash a2enmod rewrite ``` removed
  _includes/install/allowoverrides24.md
Labels: Editorial

#2946 Backward incompatible changes for Magento 2.1.15
  _includes/backward-incompatible-changes/commerce/2.1.14-2.1.15.html
  _includes/backward-incompatible-changes/open-source/2.1.14-2.1.15.html
  guides/v2.1/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.1/release-notes/backward-incompatible-changes/open-source.md
Labels: 2.1.x, Major update

#2951 Fix #1409: Fix examples in the MTF handler docs
  guides/v2.0/mtf/mtf_entities/mtf_handler.md
  guides/v2.1/mtf/mtf_entities/mtf_handler.md
Labels: 2.x, Technical

#2826 Update config-cli-subcommands-index.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-index.md
Labels: 2.2.x, Editorial

#2945 Update routing.md to reflect 2.3 changes
  guides/v2.3/extension-dev-guide/routing.md
Labels: internal-dev

#2949 Cloud key and value pair
  guides/v2.1/cloud/cdn/cloud-vcl-custom-snippets.md
  guides/v2.1/cloud/env/variables-cloud.md
  guides/v2.1/cloud/trouble/robots-sitemap.md
  guides/v2.2/cloud/env/variables-cloud.md
  guides/v2.2/cloud/trouble/robots-sitemap.md
Labels: Editorial

#2955 Fixed link to Contribution Guide
  README.md
Labels: Editorial

#2952 Added information about maintenance mode
  guides/v2.1/config-guide/bootstrap/magento-modes.md
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-maint.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-maint.md
Labels: Technical

#2956 *and* * removed from page
  guides/v2.1/install-gde/prereq/security.md
Labels: 2.1.x, 2.2.x, Editorial

#2960 Update gem dependencies in the lock file
  Gemfile.lock
Labels: Site improvements

#2961 Fix mftf scope in config
  Gemfile.lock
  _config.yml
  guides/v2.2/test/testing.md
  mftf/2.2/introduction.md
  mftf/2.3/introduction.md
Labels: Site improvements

#2963 Update BitBucket integration for Cloud
  guides/v2.1/cloud/integrations/bitbucket-integration.md
Labels: 2.1.x, 2.2.x, Technical

#2944 Added instructions for adding Webhook to Bitbucket
  guides/v2.1/cloud/integrations/bitbucket-integration.md
Labels: Tracking

#2923 Updated Alpha install to Beta install
  _data/toc/release-notes.yml
  guides/v2.1/release-notes/bk-release-notes.md
  guides/v2.2/release-notes/bk-release-notes.md
  guides/v2.3/release-notes/2.3.0-install.md
Labels: 2.3.x, Editorial, In progress

#2968 Removed the hardcoded '-develop' from links
  guides/v2.1/extension-dev-guide/depend-inj.md
  guides/v2.1/extension-dev-guide/prepare/lifecycle.md
  guides/v2.1/javascript-dev-guide/javascript/js_mixins.md
  guides/v2.2/mrg/ce/instant-purchase/index.md
  guides/v2.2/ui_comp_guide/components/ui-fieldset.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/develop/resolvers.md
  guides/v2.3/graphql/index.md
  guides/v2.3/ui_comp_guide/components/image-uploader/index.md
  guides/v2.3/ui_comp_guide/components/wysiwyg/extension-points/index.md
Labels: Editorial

#2969 Update declarative schema command names and options
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
Labels: 2.3.x, Technical

#2970 Fix links in the MFTF guide
  guides/v2.0/magento-devdocs-whatsnew.md
  guides/v2.1/magento-devdocs-whatsnew.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2EE.md
  mftf/2.2/data.md
  mftf/2.2/test/action-groups.md
  mftf/2.2/test/actions.md
  mftf/2.2/update.md
  mftf/2.3/data.md
  mftf/2.3/test/action-groups.md
  mftf/2.3/test/actions.md
  mftf/2.3/update.md
Labels: 2.2.x, 2.3.x, Editorial

#2972 Weekly digest
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2719 update shipment step
  guides/v2.3/rest/tutorials/msi-order-processing/configure-environment.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-cart-add-products.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-invoice.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-order.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-shipment.md
  guides/v2.3/rest/tutorials/msi-order-processing/prepare-for-checkout.md
  guides/v2.3/rest/tutorials/msi-order-processing/run-ssa.md
Labels: 2.3.x, Technical

#2973 add valid payloads and responses
  guides/v2.3/rest/tutorials/msi-order-processing/create-cart-add-products.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-customer.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-invoice.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-order.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-products.md
  guides/v2.3/rest/tutorials/msi-order-processing/prepare-for-checkout.md
  guides/v2.3/rest/tutorials/msi-order-processing/reassign-products-to-another-source.md
Labels: 2.3.x, Editorial

#2975 MAGEDOC-3163: Remove references to Amazon Sales Channel
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  magento-release-information.md
Labels: Editorial

#2979 Fix 'Release notes' link in footer
  _includes/layout/footer-links.html
Labels: 2.x, Editorial

#2978 remove intermediary navigation page
  _data/main-nav.yml
  magento-release-information.md
  rakelib/proofer.rb
Labels: 2.x, Editorial

#2982 Fix formatting in the MTF
  _data/toc/functional-testing-framework-guide.yml
  guides/v2.0/mtf/configuration.md
  guides/v2.0/mtf/create_test/create_new_test.md
  guides/v2.0/mtf/features/isolation.md
  guides/v2.0/mtf/features/parallel_execution.md
  guides/v2.0/mtf/features/reporting.md
  guides/v2.0/mtf/features/test_suite.md
  guides/v2.0/mtf/mtf_changelog.md
  guides/v2.0/mtf/mtf_entities/mtf_block.md
  guides/v2.0/mtf/mtf_entities/mtf_constraint.md
  guides/v2.0/mtf/mtf_entities/mtf_dataset.md
  guides/v2.0/mtf/mtf_entities/mtf_fixture-repo.md
  guides/v2.0/mtf/mtf_entities/mtf_fixture.md
  guides/v2.0/mtf/mtf_entities/mtf_handler.md
  guides/v2.0/mtf/mtf_entities/mtf_page.md
  guides/v2.0/mtf/mtf_entities/mtf_scenariotest.md
  guides/v2.0/mtf/mtf_entities/mtf_testcase.md
  guides/v2.0/mtf/mtf_entities/mtf_typified-element.md
  guides/v2.0/mtf/mtf_installation.md
  guides/v2.0/mtf/mtf_quickstart/mtf_quickstart_config.md
  guides/v2.1/mtf/configuration.md
  guides/v2.1/mtf/create_test/create_new_test.md
  guides/v2.1/mtf/features/parallel_execution.md
  guides/v2.1/mtf/features/webdriver.md
  guides/v2.1/mtf/mtf_changelog.md
  guides/v2.1/mtf/mtf_entities/mtf_block.md
  guides/v2.1/mtf/mtf_entities/mtf_fixture.md
  guides/v2.1/mtf/mtf_entities/mtf_handler.md
  guides/v2.1/mtf/mtf_entities/mtf_scenariotest.md
  guides/v2.1/mtf/mtf_installation.md
  guides/v2.1/mtf/mtf_quickstart/mtf_quickstart_environment.md
  guides/v2.1/mtf/mtf_quickstart/mtf_quickstart_runtest.md
  guides/v2.1/mtf/mtf_update.md
  guides/v2.2/mtf/mtf_changelog.md
  guides/v2.2/mtf/mtf_quickstart/mtf_quickstart_magento.md
  guides/v2.3/mtf/mtf_changelog.md
Labels: 2.0.x, 2.1.x, Editorial

#2985 MAGECLOUD-2547: Fixed file name in Fastly VCL
  guides/v2.1/cloud/cdn/fastly-vcl-whitelist.md
Labels: Editorial

#2987 Remove docker-compose file for obsolete devops project
  docker-compose.yml
Labels: Site improvements

#2976 MQE-1222
  mftf/2.3/test/action-groups.md
Labels: 2.3.x, Technical, internal-dev

#2988 currect typo
  guides/v2.2/install-gde/prereq/install-rabbitmq.md
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
Labels: 2.2.x, 2.3.x, Editorial

#2989 Update continue-to-install.md
  guides/v2.0/install-gde/continue-to-install.md
Labels: Editorial

#2983 Add contributor rewards to Contributor Guide
  .github/CONTRIBUTING.md
  _includes/contributor/labels.md
  _includes/contributor/rewards.md
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#2986 MAGECLOUD-2757 created new note in includes for consistency
  _includes/cloud/note-private-repo.md
  guides/v2.1/cloud/integrations/bitbucket-integration.md
  guides/v2.1/cloud/integrations/cloud-integrations.md
  guides/v2.1/cloud/integrations/github-integration.md
Labels: Editorial

#2991 Fix code formatting on system-requirements-tech.md page
  guides/v2.0/install-gde/system-requirements-tech.md
  guides/v2.1/install-gde/system-requirements-tech.md
Labels: 2.0.x, 2.1.x, Editorial

#2992 Removed redirects as they cause issues with case sensitivity in the gh-pages locally
  guides/m1x/api/soap/enterpriseGiftCard/cartGiftCard/cart_giftcard.add.html
  guides/m1x/api/soap/enterpriseGiftCard/cartGiftCard/cart_giftcard.list.html
  guides/m1x/api/soap/enterpriseGiftCard/cartGiftCard/cart_giftcard.remove.html
  guides/v2.0/cloud/trouble/trouble-error-html-minification.md
Labels: 1.x, 2.0.x, Editorial

#2997 Changed caption for DI example from 'BI' to 'DI'
  guides/v2.1/payments-integrations/base-integration/admin-integration.md
Labels: 2.x, Editorial

#2995 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2998 Update labels for EngCom - Contributor Guide
  _includes/contributor/labels.md
  _includes/contributor/rewards.md
  common/images/fork.png
  common/images/issues.png
  common/images/new_issue.png
  common/images/pr.png
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2999 Update link to wiki page in Contributor Guide
  _includes/contributor/labels.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial
