Repository magento/devdocs, pull requests merged in 2018-05, with the labels that each got.

#1854 Remove link related to itself
  guides/v2.2/install-gde/install/cli/install-cli-install.md
Labels: Editorial

#1857 #1697 - remove symlink from 2.2 back to 2.1, and add requested clarif…
  guides/v2.2/frontend-dev-guide/templates/template-override.md
Labels: 2.2.x, Technical

#1879 Fix link to deploy mode command
  guides/v2.2/config-guide/deployment/pipeline/production-system.md
Labels: Editorial

#1881 Update README.md
  README.md
Labels: Editorial

#1890 Update widget_collapsible.md
  guides/v2.0/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.md
Labels: 2.x, Editorial

#1587 Fix Override static assets part
  guides/v2.0/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.x, Technical

#1850 Update view.xml link to point to exact location
  guides/v2.1/frontend-dev-guide/themes/js-bundling.md
Labels: 2.1.x, Editorial

#1725 Add some necessary configuration to let multi size work properly
  guides/v2.0/config-guide/multi-site/ms_nginx.md
Labels: 2.x, Technical

#1847 Update ui_comp_template_literals.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_template_literals.md
Labels: 2.x, Technical

#1872 Update DML shortcut
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
Labels: 2.3.x, Editorial

#1861 Add defination.xml link to github
  guides/v2.1/ui_comp_guide/bk-ui_comps.md
Labels: 2.x, Editorial

#1903 Add start comment tag to xml DocBlock example.
  guides/v2.1/coding-standards/docblock-standard-general.md
Labels: Editorial

#1913 Fix camel case
  guides/v2.1/extension-dev-guide/attributes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#1929 Fixed missing tag issue and formated code
  guides/m1x/ce19-ee114-home.html
Labels: 1.x, Editorial

#1930 Used variables to show new naming convention of Magento
  _includes/config/config-reference-b2b.md
  _includes/install/sampledata/sample-data-rc1-cli.md
Labels: 2.x, Editorial

#1909 Likemusic bugfix/case sensitive broken links
  guides/m1x/api/rest/introduction.html
  guides/m1x/api/soap-api-index.html
  guides/m1x/api/soap/enterpriseGiftCard/cartGiftCard/cart_giftcard.add.html
  guides/m1x/api/soap/enterpriseGiftCard/cartGiftCard/cart_giftcard.list.html
  guides/m1x/api/soap/enterpriseGiftCard/cartGiftCard/cart_giftcard.remove.html
  guides/v2.0/cloud/trouble/trouble-error-html-minification.md
  guides/v2.0/release-notes/thirdparty-mccloud.md
  guides/v2.0/release-notes/thirdparty_ce.md
  guides/v2.0/release-notes/thirdparty_ee.md
  guides/v2.1/release-notes/thirdparty-mccloud.md
  guides/v2.1/release-notes/thirdparty_ce.md
  guides/v2.1/release-notes/thirdparty_ee.md
  guides/v2.2/cloud/trouble/trouble-error-html-minification.md
  guides/v2.2/release-notes/thirdparty-mccloud.md
  guides/v2.2/release-notes/thirdparty_ce.md
  guides/v2.2/release-notes/thirdparty_ee.md
Labels: Editorial

#1926 Update config-cli-subcommands.md
  guides/v2.1/config-guide/cli/config-cli-subcommands.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#1914 Add Github link and code format
  guides/v2.1/javascript-dev-guide/bk-javascript-dev-guide.md
Labels: Editorial

#1916 Update git link with gallery.js
  guides/v2.1/javascript-dev-guide/javascript/js_practice.md
Labels: 2.x, Editorial

#1915 Added dynamic git link.
  guides/v2.1/javascript-dev-guide/javascript/js_debug.md
Labels: Editorial

#1949 MAGEDOC-2973: Remove symlink to 2.0
  guides/v2.1/migration/extend-the-tool.md
Labels: 2.1.x, Editorial

#1946 Removed extra space from beginning of file
  _includes/backward-incompatible-changes/b2b/1.0.0-develop.html
  _includes/backward-incompatible-changes/commerce/2.1.2-2.1.3.html
  _includes/backward-incompatible-changes/commerce/2.2.0-develop.html
Labels: 2.x, Editorial

#1950 Fix broken link
  guides/v2.3/release-notes/bk-release-notes.md
Labels: 2.3.x, Editorial

#1951 MQE-760: [Documentation] Document test syntax for flattened data
  guides/v2.2/magento-functional-testing-framework/release-2/data.md
  guides/v2.2/magento-functional-testing-framework/release-2/img/section-dia.svg
  guides/v2.2/magento-functional-testing-framework/release-2/metadata.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/actions.md
Labels: 2.2.x, 2.3.x, Major update

#1947 Added code format for command
  _includes/cloud/sens-data-create-config-local.md
  _includes/cloud/ssh-tunnel.md
Labels: Editorial

#1952 GH1945 Revise code formatting, general copyedit per submitted PR
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_depend_types.md
  guides/v2.1/extension-dev-guide/build/component-registration.md
  guides/v2.1/extension-dev-guide/build/create_component.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#1958 MAGEDOC-2979 Remove deprecated [-d|--dry-run]
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
Labels: 2.2.x, 2.3.x, Editorial

#1960 GH1266 Slightly revise version wording to be congruous with example
  guides/v2.1/migration/migration-overview-how.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#1975 GH #1975`<remove>` attribute changes
  guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#1968 Updates to environment variables
  _includes/cloud/merge-configuration.md
  guides/v2.1/cloud/env/variables-build.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#1978 Format XML, PHP and Json code
  guides/v2.2/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-deploy-strategies.md
  guides/v2.2/config-guide/deployment/pipeline/technical-details.md
  guides/v2.2/config-guide/varnish/config-varnish-advanced.md
Labels: 2.x, Editorial

#1989 [fix] typo in advanced reporting / data collection
  guides/v2.2/advanced-reporting/data-collection.md
Labels: Editorial

#1992 [fix] typos in contributor guide
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/contributor-guide/templates/tutorial-template-last.md
  guides/v2.1/contributor-guide/templates/tutorial-template-middle.md
Labels: 2.x, Editorial

#1998 Updated 'Whats New on Devdocs'
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#1853 Update mage-dirs.md
  guides/v2.1/config-guide/bootstrap/mage-dirs.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, Tracking

#1980 Fixed typo mistakes
  guides/v2.2/magento-functional-testing-framework/release-2/introduction.md
Labels: 2.2.x, 2.3.x, Editorial

#2001 Updated formatting
  _includes/comp-man/checklist_2.2.md
  guides/v2.1/comp-mgr/cli/cli-upgrade.md
  guides/v2.2/comp-mgr/cli/cli-upgrade.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2002 [fix] typos in migration section
  guides/v2.0/migration/migration-migrate-follow-up.md
  guides/v2.1/migration/bk-migration-guide.md
  guides/v2.1/migration/extend-the-tool.md
  guides/v2.1/migration/migration-plan.md
  guides/v2.2/migration/migration-migrate-data.md
  guides/v2.2/migration/migration-tool-internal-spec.md
Labels: Editorial

#2000 Migrate PR-1921 to 2.3 docs
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
Labels: 2.3.x, Community, Technical

#2009 GH #1944 Indexer addition
  guides/v2.1/extension-dev-guide/indexing.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#2010 Added missing closing div tag
  _includes/browsers/supported-browsers.md
Labels: 2.x, Editorial

#2011 Update bk-b2b.md
  guides/v2.2/b2b/bk-b2b.md
Labels: 2.2.x, 2.3.x, Editorial

#2016 Adding missing </p> tag that was causing html tags to render in plain…
  guides/v2.1/howdoi/install/mode-switch.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#985 Add information about required rewrite rule for Nginx
  guides/v2.1/release-notes/ReleaseNotes2.1.3CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.3EE.md
Labels: Enhancement

#1590 Update service-to-web-service.md
  guides/v2.0/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: Major update, Waiting for response

#1839 Update lifecycle.md
  guides/v2.1/extension-dev-guide/prepare/lifecycle.md
Labels: Technical

#1841 Update attributes.md
  guides/v2.1/extension-dev-guide/attributes.md
Labels: Technical

#2005 Update xml-instructions.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: Editorial

#1990 [fix] several typos in cloud section
  guides/v2.0/cloud/access-acct/fastly.md
  guides/v2.0/cloud/access-acct/first-time-setup.md
  guides/v2.0/cloud/access-acct/first-time-setup_import-prepare.md
  guides/v2.0/cloud/basic-information/starter-develop-deploy-workflow.md
  guides/v2.0/cloud/bk-cloud.md
  guides/v2.0/cloud/configure/configure-best-practices.md
  guides/v2.0/cloud/configure/fastly-vcl-extend-timeout.md
  guides/v2.0/cloud/configure/setup-cron-jobs.md
  guides/v2.0/cloud/deploy/continuous-deployment.md
  guides/v2.0/cloud/env/environments.md
  guides/v2.0/cloud/howtos/debug.md
  guides/v2.0/cloud/live/go-live-checklist.md
  guides/v2.0/cloud/live/stage-prod-migrate-prereq.md
  guides/v2.0/cloud/live/stage-prod-test.md
  guides/v2.0/cloud/onboarding/onboarding-portal.md
  guides/v2.0/cloud/project/project-integrate-blackfire.md
  guides/v2.0/cloud/project/project-multi-sites.md
  guides/v2.0/cloud/project/project-webint-branch.md
  guides/v2.0/cloud/reference/cli-ref-topic.md
  guides/v2.0/cloud/requirements/cloud-requirements.md
  guides/v2.0/cloud/trouble/pro-env-management.md
  guides/v2.0/cloud/trouble/redis-troubleshooting.md
  guides/v2.0/cloud/trouble/theme-troubleshooting.md
  guides/v2.0/cloud/trouble/trouble-broken-branch.md
  guides/v2.0/cloud/trouble/trouble-error-html-minification.md
  guides/v2.1/cloud/access-acct/fastly.md
  guides/v2.1/cloud/access-acct/first-time-setup.md
  guides/v2.1/cloud/access-acct/first-time-setup_import-prepare.md
  guides/v2.1/cloud/basic-information/starter-develop-deploy-workflow.md
  guides/v2.1/cloud/configure/configure-best-practices.md
  guides/v2.1/cloud/configure/fastly-vcl-extend-timeout.md
  guides/v2.1/cloud/configure/setup-cron-jobs.md
  guides/v2.1/cloud/howtos/debug.md
  guides/v2.1/cloud/live/go-live-checklist.md
  guides/v2.1/cloud/live/paypal-onboarding.md
  guides/v2.1/cloud/live/sens-data-initial.md
  guides/v2.1/cloud/live/sens-data-over.md
  guides/v2.1/cloud/live/stage-prod-migrate-prereq.md
  guides/v2.1/cloud/live/stage-prod-migrate.md
  guides/v2.1/cloud/live/stage-prod-test.md
  guides/v2.1/cloud/onboarding/onboarding-portal.md
  guides/v2.1/cloud/project/project-multi-sites.md
  guides/v2.1/cloud/project/project-webint-branch.md
  guides/v2.1/cloud/requirements/cloud-requirements.md
  guides/v2.1/cloud/trouble/redis-troubleshooting.md
  guides/v2.1/cloud/trouble/theme-troubleshooting.md
  guides/v2.1/cloud/trouble/trouble-error-html-minification.md
  guides/v2.2/cloud/basic-information/starter-develop-deploy-workflow.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/live/paypal-onboarding.md
  guides/v2.2/cloud/live/sens-data-initial.md
  guides/v2.2/cloud/requirements/cloud-requirements.md
Labels: groomed

#2019 Update bk-get-started-api.md
  guides/v2.1/get-started/bk-get-started-api.md
Labels: Editorial

#2021 xdebug note moved to a correct place
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Editorial
