Repository magento/devdocs, pull requests merged in 2018-03, with the labels that each got.

#1741 Update docblock-standard-general.md - fix typo
  guides/v2.0/coding-standards/docblock-standard-general.md
Labels: 2.x, Doc bug

#1743 #1653 Remove old documentations about multi-tenant compiler
  guides/v2.1/config-guide/cli/config-cli-subcommands-compiler.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-compiler.md
Labels: 2.1.x, 2.2.x, Doc update

#1744 Update xss-protection.md
  guides/v2.2/extension-dev-guide/xss-protection.md
Labels: Doc bug

#1745 Added force option for static content deploy
  guides/v2.2/comp-mgr/install-extensions/b2b-installation.md
Labels: Doc update

#1748 Update gulp-sass.md
  guides/v2.0/frontend-dev-guide/css-topics/gulp-sass.md
Labels: 2.x, Doc bug

#1754 Remove minor version
  guides/v2.0/extension-dev-guide/build/build.md
Labels: 2.x, Doc update

#1739 presentation markup used in acceptable example
  guides/v2.0/coding-standards/code-standard-demarcation.md
Labels: 2.x, Doc bug

#1755 Remove https:// from hosts file entry
  guides/v2.0/extension-dev-guide/validate/test-module.md
Labels: 2.x, Doc bug

#1508 Update tech-stack.md
  guides/v2.0/architecture/tech-stack.md
  guides/v2.2/architecture/tech-stack.md
Labels: 2.x, Doc update

#1694 Add Video to keep update Repo
  guides/v2.0/contributor-guide/contributing.md
Labels: 2.x, Doc update

#1770 Update package_module.md
  guides/v2.0/extension-dev-guide/package/package_module.md
Labels: 2.x, Doc bug

#1771 Update package_module.md
  guides/v2.0/extension-dev-guide/package/package_module.md
Labels: 2.x, Doc update

#1775 Fix grammar
  guides/v2.0/extension-dev-guide/build/di-xml-file.md
  guides/v2.2/extension-dev-guide/build/di-xml-file.md
Labels: 2.x, Doc bug

#1787 Fastly
  guides/v2.0/cloud/access-acct/fastly.md
  guides/v2.0/cloud/live/go-live-checklist.md
  guides/v2.1/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.3/cloud/live/go-live-checklist.md
Labels: 2.x, Doc update

#1789 Update Fastly IPs: fix typo
  guides/v2.0/cloud/access-acct/fastly.md
  guides/v2.0/cloud/live/go-live-checklist.md
  guides/v2.1/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.3/cloud/live/go-live-checklist.md
Labels: 2.x, Doc bug

#1646 Fixed wrong spelling
  guides/v2.0/cloud/live/stage-prod-test.md
Labels: 2.x, Doc bug

#1781 Corrected namespace for the Framework examples
  guides/v2.0/architecture/archi_perspectives/framework.md
Labels: 2.x, Doc bug
