Repository magento/devdocs, pull requests merged in 2018-12, with the labels that each got.

#3391 Fixed front matter on go live checklist
  guides/v2.3/cloud/live/go-live-checklist.md
Labels: 2.3.x, Editorial

#3392 Fixed section name in an example
  guides/v2.1/extension-dev-guide/cache/page-caching/private-content.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, internal-dev

#3394 Weekly digest
  whats-new.md
Labels: 2.x, Editorial

#3398 Missing slash with bin/magento path
  _includes/config/es-elasticsearch-magento.md
  guides/v2.0/config-guide/solr/solr-magento.md
  guides/v2.1/config-guide/solr/solr-magento.md
Labels: 2.x, Editorial

#3401 MAGEDOC-3288: Update 2.3.0 upgrade instructions
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Technical

#3400 Update searching-with-repositories.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
Labels: 2.2.x, Editorial

#3397 Update searching-with-repositories.md
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
Labels: 2.2.x, Editorial

#3405 update redirects
  guides/v2.3/performance-best-practices/introduction.md
Labels: 2.3.x, Editorial, internal-dev

#3406 Add link to community resources
  community/resources/resources.md
Labels: 2.x, Major update, internal-dev

#3407 Add absolute URL to sitemap
  robots.txt
Labels: Site improvements, internal-dev

#3272 Updates to Fastly WAF docs
  _data/toc/cloud-guide.yml
  common/images/cloud/cloud-fastly-503-example.png
  common/images/cloud/cloud-fastly-custom-synthetic-pages-edit-html.png
  common/images/cloud/cloud-fastly-custom-synthetic-pages-edit-waf.png
  common/images/cloud/cloud-fastly-customize-503-response.png
  common/images/cloud/cloud-fastly-edit-waf-html.png
  common/images/cloud/cloud-fastly-new-error-page.png
  guides/v2.1/cloud/cdn/cloud-fastly-custom-response.md
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.1/cloud/cdn/configure-fastly.md
  guides/v2.1/cloud/cdn/fastly-waf-service.md
  guides/v2.1/cloud/cdn/trouble-fastly.md
  guides/v2.1/cloud/configure/configuration-overview.md
  guides/v2.2/cloud/cdn/cloud-fastly-custom-response.md
  guides/v2.3/cloud/cdn/cloud-fastly-custom-response.md
  whats-new.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3410 Fixed format issue
  guides/v2.1/install-gde/prereq/optional.md
  guides/v2.3/install-gde/prereq/optional.md
Labels: Editorial

#3411 Update tech-stack.md
  guides/v2.3/architecture/tech-stack.md
Labels: 2.3.x, Editorial, Partner: Webjump, partners-contribution

#3408 Implement autogeneration for third-party licenses topics
  _data/codebase/v2_3/cloud/composer_lock.json
  _data/codebase/v2_3/commerce/composer_lock.json
  _data/codebase/v2_3/open-source/composer_lock.json
  _includes/release-notes/third_party_libs.md
  guides/v2.3/release-notes/thirdparty-mccloud.md
  guides/v2.3/release-notes/thirdparty_ce.md
  guides/v2.3/release-notes/thirdparty_ee.md
Labels: 2.3.x, Editorial

#3347 Updated outdated commands
  _includes/install/file-system-perms-twouser.md
  _includes/install/file-system-perms-twouser_22.md
  guides/v2.0/cloud/before/before-workspace-file-sys-owner.md
  guides/v2.1/cloud/before/before-workspace-file-sys-owner.md
Labels: 2.x, Technical

#3409 Added magento traslation
  guides/v2.0/release-notes/tech_bull_20x_MasterCard.md
  guides/v2.0/release-notes/tech_bull_21-upgrade.md
  guides/v2.1/release-notes/tech_bull_21-upgrade.md
  guides/v2.1/release-notes/tech_bull_216-imageresize.md
Labels: Editorial

#3416 MAGECLOUD-2967 Update Cloud version
  _includes/config/es-elasticsearch-magento.md
  guides/v2.1/cloud/deploy/cloud-deployment-process.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/cloud/project/project-upgrade.md
Labels: 2.3.x, Technical, internal-dev

#3419 Remove DELETE from bulk operations support
  guides/v2.3/rest/asynchronous-web-endpoints.md
  guides/v2.3/rest/bulk-endpoints.md
Labels: 2.3.x, Partner: Comwrap, Technical, partners-contribution

#3365 MFTF 2.3.12: Describe how to use reference to data key in `url` of metadata
  mftf/2.3/metadata.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#3366 MFTF 2.3.12: Add description for the array value element in metadata
  mftf/2.3/metadata.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#3428 Update tech_bull_USPS-patch-Sept2017.md
  guides/v2.1/release-notes/tech_bull_USPS-patch-Sept2017.md
Labels: 2.1.x, Editorial, Partner: Wagento, partners-contribution

#3430 Add backup enable info to devdocs
  _includes/comp-man/backup.md
  guides/v2.1/comp-mgr/trouble/cman/tshoot_backup.md
  guides/v2.1/install-gde/install/cli/install-cli-backup.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3433 Release Note revision for MAGEDOC-3299
  guides/v2.1/release-notes/ReleaseNotes2.1.16CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.16EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3436 Added uses of admin security and magento init params
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-store.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3434 Updated format of code
  guides/v2.2/get-started/create-integration.md
  guides/v2.3/get-started/create-integration.md
Labels: 2.2.x, 2.x, Editorial

#3438 Add a custom last_modified_at plugin
  Gemfile
  Gemfile.lock
  _config.yml
  _plugins/last-modified-at.rb
  mftf/2.2/test/actions.md
Labels: 2.x, Site improvements

#3439 Weekly digest
  whats-new.md
Labels: 2.x, Editorial

#3440 Add MSI module management and user guide link
  _data/toc/software-update-guide.yml
  guides/v2.3/comp-mgr/install-extensions/inventory-management-installation.md
  guides/v2.3/inventory/index.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, New doc, internal-dev

#3442 Exclude 'redirect.html' in the 'last-modified-at' plugin
  _plugins/last-modified-at.rb
Labels: 2.x, Site improvements

#3443 Fixed issue#3399
  _includes/install/sampledata/sample-data-rc1-cli.md
Labels: 2.x, Editorial

#3444 Added new mixin file
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3447 MAGEDOC-3040: RSS enhancements
  feed.xml
Labels: Site improvements

#3429 Update technical-guidelines.md
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.x, Editorial, Partner: Wagento, partners-contribution

#3452 Added missing cache related information
  guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.3.x, Major update

#3453 Updated index management image
  common/images/index_index-modes.png
Labels: 2.x, Editorial

#3459 Fixing Markdown syntax
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Imagination Media, partners-contribution

#3461 Known issue (MC-6030) for 2.3.0 Release Notes
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, Technical

#3458 Fixed checkout layout validation issue
  guides/v2.0/howdoi/checkout/checkout_carrier.md
  guides/v2.1/howdoi/checkout/checkout_carrier.md
Labels: 2.x, Technical

#3208 Replaced two links
  guides/v2.1/frontend-dev-guide/translations/xlate.md
Labels: Editorial

#3462 Canonical URLs to point to the 2.3 version
  Gemfile.lock
  _includes/layout/footer-links.html
  _includes/layout/header-styles.html
  _includes/layout/page-info.html
Labels: Site improvements

#3446 MAGECLOUD-2956: Exception during build phase: Undefined class constant 'PARSE_CONSTANT'
  guides/v2.1/cloud/project/magento-env-yaml.md
Labels: In progress, internal-dev

#3463 Add a pliugin that generates canonical URLs
  Gemfile.lock
  _includes/layout/footer-links.html
  _includes/layout/header-styles.html
  _includes/layout/page-info.html
  _plugins/page-canonical-url.rb
Labels: 2.x, Site improvements

#3460 Fixed instructions for refreshing the cache
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/cdn/cloud-fastly-custom-response.md
  guides/v2.1/cloud/cdn/fastly-waf-service.md
Labels: Editorial

#3464 updated magento command example
  guides/v2.1/config-guide/cli/config-cli-subcommands-depen.md
Labels: 2.x, Editorial, internal-dev

#3222 Update config sample for 2.3 and add additional context
  guides/v2.3/test/integration/integration_test_execution.md
Labels: 2.3.x, Technical

#3467 Optimize plugins to enhance performance
  _plugins/html-check-hook.rb
  _plugins/last-modified-at.rb
  _plugins/page-baseurl-generator.rb
  _plugins/page-canonical-url.rb
Labels: 2.x, Site improvements

#3468 Fix template for packages-dev generator in 3rd party licenses topics
  _includes/release-notes/third_party_libs.md
Labels: 2.3.x, Technical

#3466 Updated CLI docs for compilation process
  guides/v2.0/get-started/create-integration.md
  guides/v2.1/comp-mgr/install-extensions.md
  guides/v2.1/get-started/create-integration.md
  guides/v2.2/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.2/get-started/create-integration.md
  guides/v2.3/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.3/get-started/create-integration.md
Labels: 2.2.x, 2.3.x, Technical

#3456 Added missing parameter and added default value of parameters
  _includes/config/message-queue-consumers.md
  guides/v2.1/config-guide/mq/manage-mysql.md
  guides/v2.2/config-guide/mq/manage-mysql.md
Labels: Major update

#3470 breaking symlinks to help resolve pr-3449
  guides/v2.2/config-guide/config/config-create.md
  guides/v2.3/config-guide/config/config-create.md
Labels: 2.x, Editorial, internal-dev

#3473 Add new install/deploy resources
  community/resources/resources.md
Labels: 2.x, Editorial, Partner: Interactiv4, partners-contribution

#3474 Updated interface link in document
  guides/v2.1/config-guide/config/config-create.md
  guides/v2.2/config-guide/config/config-create.md
  guides/v2.3/config-guide/config/config-create.md
Labels: 2.1.x, Editorial

#3480 Weekly digest
  whats-new.md
Labels: 2.x, Editorial

#3481 Fixed format issue on cronjob command
  _includes/config/setup-cron.md
Labels: 2.x, Editorial

#3478 Disallow sync use of require()
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#3476 Fixed content issue on Configure a custom cron job and cron group
  guides/v2.0/config-guide/cron/custom-cron-tut.md
  guides/v2.1/config-guide/cron/custom-cron-tut.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3415 Update adding-attributes.md
  guides/v2.1/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3485 Fix typos in GraphQL docs
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/develop/exceptions.md
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.x, Editorial

#3486 Clean cache after upgrades
  _videos/fundamentals/add-a-javascript-module.md
  guides/v2.1/comp-mgr/cli/cli-upgrade.md
  guides/v2.1/comp-mgr/install-extensions.md
  guides/v2.1/comp-mgr/module-man/compman-new-purchase.md
  guides/v2.1/comp-mgr/module-man/compman-update.md
  guides/v2.1/comp-mgr/upgrader/ce-ee-upgrade-start.md
  guides/v2.1/comp-mgr/upgrader/upgrade.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.1/config-guide/cron/custom-cron-tut.md
  guides/v2.1/ext-best-practices/extension-coding/example-module-adminpage.md
  guides/v2.1/extension-dev-guide/build/enable-module.md
  guides/v2.1/frontend-dev-guide/themes/admin_theme_apply.md
  guides/v2.1/get-started/create-integration.md
  guides/v2.1/install-gde/install/cli/dev_update-magento.md
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-db-upgr.md
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-enable.md
  guides/v2.1/security/google-recaptcha.md
  guides/v2.1/security/two-factor-authentication.md
  guides/v2.2/comp-mgr/cli/cli-upgrade.md
  guides/v2.2/comp-mgr/extens-man/extensman-new-purchase.md
  guides/v2.2/comp-mgr/extens-man/extensman-update.md
  guides/v2.2/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.2/comp-mgr/upgrader/ce-ee-upgrade-start.md
  guides/v2.2/comp-mgr/upgrader/upgrade.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.2/config-guide/deployment/single-machine.md
  guides/v2.2/get-started/create-integration.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.3/get-started/create-integration.md
Labels: 2.x, Technical, internal-dev

#3418 Create Technical Vision intro page
  _data/toc/coding-standards.yml
  guides/v2.0/coding-standards/technical-vision/index.md
  guides/v2.1/coding-standards/technical-vision/index.md
  guides/v2.2/coding-standards/technical-vision/index.md
  guides/v2.3/coding-standards/technical-vision/index.md
Labels: 2.x, In progress, New doc, internal-dev

#3437 MAGECLOUD-2907: [Cloud Docker] Verify sendmail functionality
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
Labels: In progress, internal-dev

#3488 Set correct pattern of layout file's naming
  guides/v2.1/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: ISM eCompany, Technical, partners-contribution

#3471 Transform Whats New on Devdocs to a template working with data and add a news feed for the topic updates
  _data/whats-new.yml
  i/icons/rss.svg
  whats-new.md
  whatsnew-feed.xml
Labels: 2.x, Site improvements

#3487 GH3207 - translations updates
  _data/toc/frontend-developer-guide.yml
  community/resources/resources.md
  guides/v2.0/frontend-dev-guide/translations/theme_dictionary.md
  guides/v2.0/frontend-dev-guide/translations/translate_practice.md
  guides/v2.0/frontend-dev-guide/translations/xlate.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.1/frontend-dev-guide/translations/theme_dictionary.md
  guides/v2.1/frontend-dev-guide/translations/translate_practice.md
  guides/v2.1/frontend-dev-guide/translations/translate_theory.md
  guides/v2.1/frontend-dev-guide/translations/xlate.md
Labels: 2.x, Community, Major update, internal-dev

#3492 Fix links and dates in Whats New
  _data/whats-new.yml
Labels: 2.x, Editorial

#3489 GH3422 - Updated links and information for testing modules
  community/resources/resources.md
  guides/v2.1/extension-dev-guide/validate/test-module.md
  guides/v2.1/extension-dev-guide/validate/validate.md
  guides/v2.2/extension-dev-guide/validate/test-module.md
  guides/v2.3/extension-dev-guide/validate/test-module.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, internal-dev

#3494 Gelanivishal issue 3164
  guides/v2.1/frontend-dev-guide/themes/theme-structure.md
  guides/v2.2/frontend-dev-guide/themes/theme-structure.md
  guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3479 Update info about getting Fastly credentials
  common/images/cloud/cloud-fastly-credentials-admin-ui.png
  common/images/cloud/cloud-project-web-ui-environment-variables.png
  guides/v2.1/cloud/cdn/configure-fastly.md
  guides/v2.1/cloud/project/projects.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3484 update to new blackfire:setup workflow
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: In progress, Technical

#3431 MFTF 2.3.12 documentation updates
  mftf/2.3/commands/mftf.md
  mftf/2.3/introduction.md
  mftf/2.3/metadata.md
Labels: 2.2.x, 2.3.x, Major update

#3496 MAGECLOUD-2610 add note for support
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: Editorial, internal-dev

#3499 Add info and link for Inventory Management installs
  community/resources/resources.md
  guides/v2.3/comp-mgr/install-extensions/inventory-management-installation.md
Labels: 2.3.x, Community, Editorial, internal-dev

#3500 Fix paths to data in Third-party licenses topics
  _data/codebase/v2_1/commerce/composer_lock.json
  guides/v2.1/release-notes/thirdparty_ee.md
  guides/v2.2/release-notes/thirdparty_ce.md
  guides/v2.2/release-notes/thirdparty_ee.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical
