Repository magento/devdocs, pull requests merged in 2018-07, with the labels that each got.

#2402 GH2116: Revise for Magento Commerce variable
  guides/v2.1/architecture/tech-stack.md
  guides/v2.2/architecture/tech-stack.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
  guides/v2.2/ext-best-practices/tutorials/serialized-to-json-data-upgrade.md
  guides/v2.3/architecture/tech-stack.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2411 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2416 Updated the What's New On DevDocs
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2392 MQE-1073
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/annotations.md
Labels: 2.2.x, 2.3.x, Technical

#2422 GH2419 - Initial draft of CONTRIBUTING.md
  .github/CONTRIBUTING.md
  README.md
  _data/toc/contributor-guide.yml
Labels: 2.x, Enhancement

#2423 Remove contributing guide files
  guides/v2.0/contributor-guide/contributing_docs.md
  guides/v2.1/contributor-guide/contributing_docs.md
  guides/v2.2/contributor-guide/contributing_docs.md
  guides/v2.3/contributor-guide/contributing_docs.md
Labels: 2.x, Editorial, internal-dev

#2313 Added notes in cli doc
  guides/v2.2/comp-mgr/cli/cli-upgrade.md
Labels: 2.2.x

#2425 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2430 Updated create_new_test.md
  guides/v2.1/mtf/create_test/create_new_test.md
Labels: 2.1.x, Editorial

#2428 Removed duplicate div attribute 'class' from serializer.md file
  guides/v2.2/extension-dev-guide/framework/serializer.md
Labels: 2.2.x, Cleanup, Editorial

#2420 Fixed wrong notation for view_preprocessed directory.
  guides/v2.0/frontend-dev-guide/templates/template-walkthrough.md
  guides/v2.0/howdoi/checkout/checkout_form.md
  guides/v2.1/frontend-dev-guide/templates/template-walkthrough.md
  guides/v2.1/frontend-dev-guide/themes/theme-apply.md
  guides/v2.1/howdoi/checkout/checkout_form.md
Labels: 2.x, Editorial

#2410 Update template.md
  guides/v2.1/template.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2436 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2438 Added instruction for add new field in address form
  guides/v2.1/howdoi/checkout/checkout_new_field.md
Labels: 2.x

#2447 Updated the Whats New on Devdocs
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2452 Fixed a spelling mistake
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
Labels: 2.3.x, Editorial

#2390 Update config-cli-subcommands-index.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
Labels: 2.2.x, Editorial

#2450 Fixed #2441 issue
  _data/toc/software-update-guide.yml
  guides/v2.1/comp-mgr/install-extensions.md
  guides/v2.2/comp-mgr/install-extensions.md
Labels: 2.1.x, Editorial

#2454 Rollback change to ADMIN_USERNAME variable
  guides/v2.1/cloud/env/environment-vars_magento.md
  guides/v2.1/cloud/env/variables-intro.md
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
Labels: Cleanup

#2453 Fixed a spelling mistake
  guides/v2.1/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2455 Added Security section
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, Major update

#2465 Update private-content.md
  guides/v2.1/extension-dev-guide/cache/page-caching/private-content.md
Labels: Editorial

#2448 Corrected typo mistakes in pattern-library files.
  guides/v2.0/config-guide/varnish/config-varnish-configure.md
  guides/v2.0/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.1/config-guide/varnish/config-varnish-configure.md
  guides/v2.1/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.1/pattern-library/filters/data-table-filters/filtering.md
  guides/v2.2/config-guide/varnish/config-varnish-configure.md
  swagger/swagger-ui.js
Labels: 2.x, Editorial, Waiting for response

#2393 minor clarification
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
Labels: Waiting for response

#2050 MQE-992: Allow Tests and Action Groups to use inheritance
  _data/toc/magento-functional-testing-framework-guide.yml
  guides/v2.2/magento-functional-testing-framework/release-2/extending.md
  guides/v2.2/magento-functional-testing-framework/release-2/test.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/action-groups.md
  guides/v2.3/magento-functional-testing-framework/release-2/extending.md
Labels: 2.2.x, 2.3.x, New doc, internal-dev

#2476 [fix] small typo in architecture
  guides/v2.1/architecture/archi_perspectives/present_layer.md
Labels: Editorial

#2477 [fix] typo in b2b section
  guides/v2.2/b2b/negotiable-checkout.md
Labels: 2.2.x, 2.3.x, Editorial

#2480 Fix typos in extension dev guide
  guides/v2.0/extension-dev-guide/extension_attributes/adding-attributes.md
  guides/v2.0/extension-dev-guide/indexing-custom.md
  guides/v2.1/extension-dev-guide/extension_attributes/adding-attributes.md
  guides/v2.1/extension-dev-guide/indexing-custom.md
  guides/v2.2/extension-dev-guide/framework/serializer.md
  guides/v2.2/extension-dev-guide/indexer-batch.md
  guides/v2.2/extension-dev-guide/message-queues/bulk-operations.md
  guides/v2.2/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
  guides/v2.3/extension-dev-guide/message-queues/bulk-operations.md
  guides/v2.3/extension-dev-guide/message-queues/config-mq.md
Labels: 2.x, Editorial

#2479 [fix] typo in design styleguide
  guides/v2.0/design-styleguide/number-formats/number-formats.md
  guides/v2.1/design-styleguide/number-formats/number-formats.md
Labels: 2.0.x, 2.1.x, Editorial

#2481 Removed duplicate word
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
Labels: 2.x, Editorial

#2478 [fix] typos in config-guide
  guides/v2.2/config-guide/mq/manage-mysql.md
  guides/v2.2/config-guide/varnish/tshoot-varnish-503.md
  guides/v2.3/config-guide/redis/redis-session.md
Labels: 2.2.x, 2.3.x, Editorial

#2471 MQE-1006: Handling secure/sensitive data in MFTF test
  guides/v2.2/magento-functional-testing-framework/release-2/data.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#2488 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2492 HTLM markdown format
  guides/v2.1/ext-best-practices/admin/admin-best-practices.md
  guides/v2.1/ext-best-practices/admin/placement-and-design.md
  guides/v2.1/ext-best-practices/bk-ext-best-practices.md
Labels: 2.1.x, 2.2.x, Editorial

#2474 Fix code links
  guides/v2.1/frontend-dev-guide/templates/template-sample.md
  guides/v2.1/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/templates/template-sample.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/frontend-dev-guide/templates/template-sample.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Technical, internal-dev

#2495 Revert "MQE-1006: Handling secure/sensitive data in MFTF test"
  guides/v2.2/magento-functional-testing-framework/release-2/data.md
Labels: 2.2.x, 2.3.x, Editorial

#2496 Fix the issue with 'Edit this page on GitHub'
  _config.yml
Labels: 2.x, Enhancement

#2493 Html markdown format
  guides/v2.1/install-gde/prereq/prereq-overview.md
  guides/v2.1/install-gde/system-requirements-tech.md
  guides/v2.2/install-gde/prereq/prereq-overview.md
  guides/v2.2/install-gde/system-requirements-tech.md
Labels: Editorial

#2498 Add MSI and Bulk endpoints
  guides/v2.3/rest/list.md
Labels: 2.3.x, Technical

#2505 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2489 Fixes markdown format.
  guides/v2.1/comp-mgr/trouble/cman/tshoot_backup.md
  guides/v2.1/comp-mgr/upgrader/ce-ee-upgrade-start.md
  guides/v2.1/comp-mgr/upgrader/upgrade-checklist.md
  guides/v2.1/comp-mgr/upgrader/upgrade-main-pg.md
  guides/v2.1/comp-mgr/upgrader/upgrade-readiness.md
  guides/v2.1/comp-mgr/upgrader/upgrade-start.md
  guides/v2.2/comp-mgr/upgrader/ce-ee-upgrade-start.md
  guides/v2.2/comp-mgr/upgrader/upgrade-checklist.md
  guides/v2.2/comp-mgr/upgrader/upgrade-start.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Waiting for response

#2501 Config guide files fix markdown format.
  guides/v2.1/config-guide/bootstrap/mage-dirs.md
  guides/v2.1/config-guide/bootstrap/mage-profiler.md
  guides/v2.1/config-guide/bootstrap/magento-bootstrap.md
  guides/v2.1/config-guide/bootstrap/magento-how-to-set.md
  guides/v2.1/config-guide/bootstrap/magento-modes.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
Labels: 2.1.x, Waiting for response

#2494 [fix] typos in install guide
  guides/v2.0/install-gde/prereq/mysql.md
  guides/v2.0/install-gde/prereq/php-settings.md
  guides/v2.1/install-gde/prereq/mysql.md
  guides/v2.1/install-gde/prereq/php-settings.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/install/post-install-config.md
  guides/v2.3/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/php-settings.md
Labels: 2.0.x, 2.1.x, 2.2.x, 2.3.x, Editorial

#2475 Fixed a spelling mistake
  guides/v2.0/extension-dev-guide/cache/page-caching/public-content.md
  guides/v2.1/extension-dev-guide/cache/page-caching/public-content.md
Labels: 2.x, Editorial

#2507 Hg retract2417
  guides/v2.1/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
Labels: Cleanup

#2508 Fixed typo mistake
  guides/v2.0/extension-dev-guide/cache/page-caching/public-content.md
  guides/v2.1/extension-dev-guide/cache/page-caching/public-content.md
  guides/v2.2/extension-dev-guide/indexer-batch.md
Labels: 2.0.x, 2.1.x, 2.2.x, Editorial

#2432 MQE-1083
  guides/v2.2/magento-functional-testing-framework/release-2/test/actions.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#2514 Update the Whats New on DevDocs
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2053 Mqe 991: MFTF 2.3 update
  guides/v2.2/magento-functional-testing-framework/release-2/merging.md
  guides/v2.2/magento-functional-testing-framework/release-2/test.md
Labels: 2.2.x, 2.3.x, In progress, Technical, internal-dev

#2327 MQE-1045: Document Best Practices for when to use extension vs action groups
  guides/v2.2/magento-functional-testing-framework/release-2/best-practices.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#2353 MQE-1017: Better Error Messaging When Non-Whitespace Characters Are
  guides/v2.2/magento-functional-testing-framework/release-2/commands/mftf.md
  guides/v2.3/magento-functional-testing-framework/release-2/commands/mftf.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#2354 MQE-1068: Require Issue ID for Skipped Test
  guides/v2.2/magento-functional-testing-framework/release-2/commands/codeception.md
  guides/v2.2/magento-functional-testing-framework/release-2/merging.md
  guides/v2.2/magento-functional-testing-framework/release-2/suite.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/annotations.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#2517 MQE-917
  guides/v2.2/magento-functional-testing-framework/release-2/commands/mftf.md
Labels: 2.2.x, 2.3.x, Technical

#2490 MAGECLOUD-1837 update bitbucket integration
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/access-acct/first-time-setup_import-first-steps.md
  guides/v2.1/cloud/configure/configuration-overview.md
  guides/v2.1/cloud/integrations/bitbucket-integration.md
  guides/v2.1/cloud/integrations/cloud-integrations.md
  guides/v2.1/cloud/integrations/github-integration.md
  guides/v2.1/cloud/project/bitbucket-integration.md
  guides/v2.1/cloud/reference/git-integration.md
  guides/v2.1/cloud/requirements/cloud-requirements.md
  guides/v2.1/magento-devdocs-whatsnew.md
  guides/v2.2/cloud/configure/configuration-overview.md
  guides/v2.2/cloud/integrations/bitbucket-integration.md
  guides/v2.2/cloud/integrations/cloud-integrations.md
  guides/v2.2/cloud/integrations/github-integration.md
  guides/v2.2/cloud/project/bitbucket-integration.md
  guides/v2.2/cloud/project/project-integrate-github.md
  guides/v2.2/cloud/requirements/cloud-requirements.md
  guides/v2.3/cloud/integrations/bitbucket-integration.md
  guides/v2.3/cloud/integrations/cloud-integrations.md
  guides/v2.3/cloud/integrations/github-integration.md
  guides/v2.3/cloud/project/bitbucket-integration.md
  guides/v2.3/cloud/project/project-integrate-github.md
Labels: Editorial

#2512 Update bk-frontend-dev-guide.md
  guides/v2.1/frontend-dev-guide/bk-frontend-dev-guide.md
Labels: Editorial

#2522 Removed ADMIN variables ref from deploy var desc
  guides/v2.1/cloud/env/variables-deploy.md
Labels: 2.x, Technical

#2473 Changed the default ADMIN_USERNAME per RAINBOW-420
  guides/v2.1/cloud/before/before-setup-env-2_clone.md
  guides/v2.1/cloud/env/environment-vars_magento.md
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
Labels: 2.x, In progress, Technical

#2523 Fixed markdown syntax
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
Labels: 2.x, Editorial

#2469 Updated component image #2381
  common/images/ui_comp_js_class.png
Labels: 2.2.x, 2.3.x, Editorial, In progress, Tracking

#2529 Wong code solved - install-rabbitmq.md
  guides/v2.1/install-gde/prereq/install-rabbitmq.md
Labels: Editorial

#2528 Update gs-authentication.md
  guides/v2.1/get-started/authentication/gs-authentication.md
Labels: Editorial

#2527 Update cache_for_frontdevs.md
  guides/v2.1/frontend-dev-guide/cache_for_frontdevs.md
Labels: Editorial

#2530 Checkout changes from pangolin-develop
  guides/v2.2/magento-functional-testing-framework/release-2/introduction.md
Labels: 2.2.x, 2.3.x, Technical

#2531 Delete introduction.md
  guides/v2.2/magento-functional-testing-framework/release-2/introduction.md
Labels: 2.2.x, Editorial

#2532 Delete introduction.md
  guides/v2.3/magento-functional-testing-framework/release-2/introduction.md
Labels: 2.2.x, Editorial

#2533 Update component status page
  guides/v2.3/release-notes/component-status.md
Labels: 2.3.x

#2538 MAGEDOC-3047: Remove multi-select section
  guides/v2.2/pattern-library/displaying-data/tile/tile.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#2540 Updated deploy variable description
  guides/v2.2/cloud/env/variables-deploy.md
Labels: 2.2.x, 2.3.x, Technical

#2543 Mftf-Corrections-2.3.0
  guides/v2.2/magento-functional-testing-framework/release-2/commands/codeception.md
  guides/v2.2/magento-functional-testing-framework/release-2/data.md
  guides/v2.2/magento-functional-testing-framework/release-2/getting-started.md
  guides/v2.2/magento-functional-testing-framework/release-2/introduction.md
  guides/v2.2/magento-functional-testing-framework/release-2/metadata.md
  guides/v2.2/magento-functional-testing-framework/release-2/page.md
  guides/v2.2/magento-functional-testing-framework/release-2/section.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/action-groups.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/actions.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/annotations.md
Labels: 2.2.x, 2.3.x, Technical

#2535 Fix MFTF Assertion.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/assertions.md
Labels: 2.2.x, 2.3.x, Technical

#2551 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2549 Html markdown format - optional.md
  guides/v2.1/install-gde/prereq/optional.md
  guides/v2.3/install-gde/prereq/optional.md
Labels: Editorial

#2553 Html markdown format - get-software.md
  guides/v2.1/install-gde/install/get-software.md
Labels: 2.1.x, Editorial

#2554 Update basics_os-version.md
  guides/v2.1/install-gde/basics/basics_os-version.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2396 MAGEDOC-3040: RSS feed
  _config.yml
  _includes/layout/header-styles.html
  feed.xml
Labels: Enhancement, internal-dev

#2502 Prerequisites files code markdown format
  guides/v2.1/install-gde/prereq/apache.md
  guides/v2.1/install-gde/prereq/nginx.md
  guides/v2.1/install-gde/prereq/php-centos.md
  guides/v2.2/install-gde/prereq/php-centos.md
  guides/v2.3/install-gde/prereq/apache.md
  guides/v2.3/install-gde/prereq/nginx.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2556 Add a single page about PWA that link to topics in the PWA docs site
  _includes/layout/navigation.html
  guides/v2.3/pwa/index.md
Labels: internal-dev

#2563 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.2.x, 2.3.x, Technical

#2561 Html markdown format - install-web.md
  guides/v2.1/install-gde/install/web/install-web.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2550 HTML mark down
  guides/v2.1/frontend-dev-guide/templates/template-email.md
  guides/v2.1/frontend-dev-guide/templates/template-overview.md
Labels: Editorial

#2562 Update index.md
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
Labels: 2.3.x, Editorial

#2558 Update errors-and-messages.md
  guides/v2.0/design-styleguide/errors-and-messages/errors-and-messages.md
Labels: Editorial

#2559 Removed double occurrences
  guides/v2.1/cloud/project/magento-env-yaml.md
  guides/v2.1/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: 2.1.x, 2.3.x, 2.x, Editorial

#2560 Update basics_software.md
  guides/v2.1/install-gde/basics/basics_software.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2439 Updated CLI upgrade instructions for 2.3
  _includes/layout/navigation.html
  guides/v2.1/comp-mgr/bk-compman-upgrade-guide.md
  guides/v2.2/comp-mgr/bk-compman-upgrade-guide.md
  guides/v2.2/comp-mgr/prereq/prereq_compman-checklist.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Major update, Tracking

#2565 Fix misspelling of adminhtml
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
Labels: 2.2.x, 2.3.x, Editorial

#2566 Html markdown format - install-web_1-readiness.md
  guides/v2.1/install-gde/install/web/install-web_1-readiness.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2547 Commerce installation additions for 2.3 alpha install
  guides/v2.3/release-notes/2.3.0-alpha-install.md
Labels: 2.3.x, In progress, Major update, internal-dev

#2573 Update basics_docroot.md
  guides/v2.1/install-gde/basics/basics_docroot.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2582 Html markdown format - install-web_2-db.md
  guides/v2.1/install-gde/install/web/install-web_2-db.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2574 Update company-users.md
  guides/v2.2/b2b/company-users.md
Labels: 2.2.x, 2.3.x, Editorial

#2568 Add forgotten comma in afterRender example.
  guides/v2.1/ui_comp_guide/concepts/knockout-bindings.md
  guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2586 Html markdown format - install-web_3-web-conf.md
  guides/v2.1/install-gde/install/web/install-web_3-web-conf.md
Labels: 2.1.x, 2.2.x, 2.x, Editorial

#2571 Improved Magento framework correction class
  guides/v2.1/architecture/archi_perspectives/framework.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2579 Fixed issue #2575
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2587 Update install-quick-ref.md
  guides/v2.1/install-gde/install-quick-ref.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2588 [fix] missing space
  guides/v2.1/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2590 Update mysql_remote.md
  guides/v2.1/install-gde/prereq/mysql_remote.md
Labels: 2.1.x, 2.3.x, 2.x, Editorial

#2593 fix architecture link
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
Labels: Cleanup

#2596 Fix github link to point to correct page
  guides/v2.0/frontend-dev-guide/templates/template-security.md
Labels: 2.0.x, Editorial

#2569 MAGEDOC-3050: Composer install instructions
  _data/toc/installation-guide.yml
  _includes/install/archives-php-issue.md
  _includes/install/composer-overview.html
  _includes/install/composer-overview.md
  _includes/install/file-system-perms-oneuser.md
  _includes/install/file-system-perms-oneuser_22.md
  _includes/install/file-system-perms-twouser.md
  _includes/install/file-system-perms-twouser_22.md
  _includes/install/flow-diagram.md
  _includes/install/prereq.md
  _includes/install/releasenotes/ce_install_20.md
  _includes/install/releasenotes/ce_install_21.md
  _includes/install/releasenotes/ee_install_20.md
  _includes/install/releasenotes/ee_install_21.md
  _includes/php-dev/component-root-2.3.md
  _includes/php-dev/component-root.md
  guides/v2.0/extension-dev-guide/intro/intro-composer.md
  guides/v2.0/install-gde/prereq/dev_install.md
  guides/v2.0/install-gde/prereq/integrator_install.md
  guides/v2.1/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.1/comp-mgr/bk-compman-upgrade-guide.md
  guides/v2.1/config-guide/prod/prod_perf-optimize.md
  guides/v2.1/config-guide/prod/single-machine-deployment.md
  guides/v2.1/extension-dev-guide/build/composer-integration.md
  guides/v2.1/extension-dev-guide/intro/intro-composer.md
  guides/v2.1/install-gde/bk-install-guide.md
  guides/v2.1/install-gde/composer.md
  guides/v2.1/install-gde/install/get-software.md
  guides/v2.1/install-gde/prereq/connect-auth.md
  guides/v2.1/install-gde/prereq/dev_install.md
  guides/v2.1/install-gde/prereq/integrator_install.md
  guides/v2.1/install-gde/prereq/integrator_install_ce.md
  guides/v2.1/install-gde/prereq/integrator_install_composer.md
  guides/v2.1/install-gde/prereq/integrator_install_ee.md
  guides/v2.1/install-gde/prereq/nginx.md
  guides/v2.1/install-gde/trouble/tshoot_composer-fail.md
  guides/v2.2/comp-mgr/bk-compman-upgrade-guide.md
  guides/v2.2/config-guide/deployment/single-machine.md
  guides/v2.2/install-gde/composer.md
  guides/v2.2/install-gde/install/get-software.md
  guides/v2.2/install-gde/prereq/integrator_install.md
  guides/v2.2/install-gde/prereq/integrator_install_ce.md
  guides/v2.2/install-gde/prereq/integrator_install_composer.md
  guides/v2.2/install-gde/prereq/integrator_install_ee.md
  guides/v2.2/performance-best-practices/index.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.3/install-gde/composer.md
  guides/v2.3/install-gde/install/get-software.md
  guides/v2.3/install-gde/prereq/integrator_install.md
  guides/v2.3/install-gde/prereq/integrator_install_ce.md
  guides/v2.3/install-gde/prereq/integrator_install_composer.md
  guides/v2.3/install-gde/prereq/integrator_install_ee.md
  guides/v2.3/install-gde/prereq/nginx.md
Labels: 2.1.x, 2.2.x, 2.3.x, Enhancement, Major update, internal-dev

#2599 Html markdown format - Setup Wizard installation - Step 4 & 5
  guides/v2.1/install-gde/install/web/install-web_4-customize-store.md
  guides/v2.1/install-gde/install/web/install-web_5-create-admin.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2584 [Template html mark down]
  guides/v2.1/frontend-dev-guide/templates/template-override.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2600 Update connect-auth.md
  guides/v2.1/install-gde/prereq/connect-auth.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2598 Update compman-checklist.md
  guides/v2.1/comp-mgr/module-man/compman-checklist.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2591 Adding information about .less files presidence
  guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_approach.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2592 Update security.md
  guides/v2.1/install-gde/prereq/security.md
  guides/v2.3/install-gde/prereq/security.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2601 'Whats New on DevDocs' weekly update
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2577 Update fastly.md
  guides/v2.1/cloud/access-acct/fastly.md
Labels: 2.1.x

#2606 Update zip_install.md
  guides/v2.1/install-gde/prereq/zip_install.md
  guides/v2.2/install-gde/prereq/zip_install.md
  guides/v2.3/install-gde/prereq/zip_install.md
Labels: 2.x, Editorial

#2608 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2613 MFTF: Fixed name format for Section and Action group
  guides/v2.2/magento-functional-testing-framework/release-2/best-practices.md
Labels: 2.2.x, 2.3.x, Editorial

#2580 LFI and RCE protection guidelines
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Major update, Technical

#2612 Update continue-to-install.md
  guides/v2.1/install-gde/continue-to-install.md
Labels: 2.x, Editorial

#2610 HTML to markdown
  guides/v2.1/frontend-dev-guide/responsive-web-design/rwd_css.md
  guides/v2.1/frontend-dev-guide/templates/template-security.md
  guides/v2.1/javascript-dev-guide/widgets/widget_accordion.md
  guides/v2.2/frontend-dev-guide/templates/template-security.md
Labels: 2.1.x, Editorial

#2597 Streamlined Starter workflow
  guides/v2.1/cloud/basic-information/starter-architecture.md
  guides/v2.1/cloud/basic-information/starter-develop-deploy-workflow.md
  guides/v2.2/cloud/basic-information/starter-develop-deploy-workflow.md
Labels: Editorial

#2570 MAGECLOUD-2311 New upgrade section for ece-tools
  _data/toc/cloud-guide.yml
  _includes/cloud/backup-db.md
  _includes/cloud/ece-tools.md
  _includes/cloud/note-ece-tools-package.md
  _includes/cloud/note-upgrade.md
  _includes/cloud/upgrade.md
  guides/v2.1/cloud/project/ece-tools-update.md
  guides/v2.1/cloud/project/ece-tools-upgrade-project.md
  guides/v2.1/cloud/project/project-patch.md
  guides/v2.1/cloud/project/project-upgrade-parent.md
  guides/v2.1/cloud/project/project-upgrade.md
  guides/v2.1/cloud/reference/cloud-composer.md
  guides/v2.1/cloud/reference/docker-config.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes2.1.3.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.1/magento-devdocs-whatsnew.md
  guides/v2.2/cloud/project/ece-tools-update.md
  guides/v2.2/cloud/project/ece-tools-upgrade-project.md
  guides/v2.2/cloud/project/project-patch.md
  guides/v2.2/cloud/project/project-upgrade.md
  guides/v2.2/cloud/reference/cloud-composer.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/project/ece-tools-update.md
  guides/v2.3/cloud/project/ece-tools-upgrade-project.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#2622 Updated formatting per feedback
  guides/v2.1/contributor-guide/contributing_dod.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2603 Convert HTML to markdown for 2.2 and 2.1 on the database caching page
  guides/v2.1/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
Labels: 2.x, Editorial

#2624 Html markdown format - install-cli-subcommands.md
  guides/v2.1/install-gde/install/cli/install-cli-subcommands.md
Labels: 2.x, Editorial

#2617 Update dev_install.md
  guides/v2.1/install-gde/prereq/dev_install.md
Labels: 2.x, Editorial

#2625 Fix xsd paths message queues
  guides/v2.2/extension-dev-guide/message-queues/config-mq.md
  guides/v2.2/extension-dev-guide/message-queues/implement-bulk.md
Labels: 2.2.x, Technical

#2626 Update prepare-install.md
  guides/v2.1/install-gde/install/prepare-install.md
Labels: 2.x, Editorial

#2623 Fix Magento logo under Swagger Rest APIs title
  swagger/css/screen.css
Labels: 2.x, Enhancement

#2564 Update ui-htmlcontent.md
  guides/v2.1/ui_comp_guide/components/ui-htmlcontent.md
  guides/v2.2/ui_comp_guide/components/ui-htmlcontent.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, Waiting for response

#2627 Update install-cli-install.md
  guides/v2.1/install-gde/install/cli/install-cli-install.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
Labels: 2.x, Editorial

#2630 Add 'acceptance' to directory list in testing.md
  guides/v2.2/test/testing.md
Labels: 2.2.x, 2.3.x

#2637 Fixed typo mistake
  guides/v2.0/coding-standards/technical-vision/webapi.md
  guides/v2.0/design-styleguide/capitalization/capitalization.md
  guides/v2.0/frontend-dev-guide/themes/admin_theme_apply.md
Labels: 2.0.x, Editorial

#2602 Fixed a couple of spelling mistakes
  guides/v2.0/frontend-dev-guide/cache_for_frontdevs.md
  guides/v2.2/b2b/company-object.md
Labels: 2.0.x, 2.2.x, Editorial

#2632 Adding content for database maintenance scheduling - performance best practices
  guides/v2.2/performance-best-practices/configuration.md
Labels: 2.2.x, 2.3.x, Major update

#2604 GH2594 - Add porting information to code contributing guide
  common/images/porting-tool-setting.png
  common/images/porting-tool-steps.png
  guides/v2.1/contributor-guide/contributing.md
Labels: 2.x, Major update

#2642 Editorial updates to contribution guide
  .github/CONTRIBUTING.md
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/contributor-guide/contributing_dod.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2644 Added the generated updates for the past week
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2647 quick fix bugs, create var for ece-tools
  _data/var.yml
  guides/v2.1/cloud/project/ece-tools-update.md
  guides/v2.1/cloud/project/ece-tools-upgrade-project.md
Labels: Cleanup

#2614 Fixed incorrect reference to ece-tools db:dump command
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Cleanup

#2648 Upgrade ece parent
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/project/ece-tools-update.md
  guides/v2.1/cloud/project/project-upgrade-parent.md
Labels: Cleanup

#2650 Add information for 2FA on contributor and partner accounts
  .github/CONTRIBUTING.md
  guides/v2.1/contributor-guide/contributing.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#2636 Update install-cli-uninstall.md
  guides/v2.1/install-gde/install/cli/install-cli-uninstall.md
Labels: 2.x, Editorial

#2646 MAGEDOC-3061: Custom cron config options
  guides/v2.1/config-guide/cron/custom-cron-tut.md
Labels: 2.x, Technical, internal-dev

#2641 Convert HTML to markdown on Vagrant configure page
  guides/v2.1/config-guide/varnish/config-varnish.md
  guides/v2.2/config-guide/varnish/config-varnish.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2659 Fixed markdown format for Phase 5
  guides/v2.2/cloud/reference/discover-deploy.md
Labels: Cleanup

#2657 Bring back system-specific settings example list.
  guides/v2.1/config-guide/config/config-php.md
Labels: 2.1.x, Editorial
