Repository magento/devdocs, pull requests merged in 2018-10, with the labels that each got.

#3002 ask_magento twitter account no longer available
  _includes/install/get-help.md
Labels: 2.x, Editorial

#3000 Fix "magneto" typo
  guides/v2.3/release-notes/2.3.0-install.md
Labels: 2.3.x, Editorial

#2801 MD3123 - install instructions for 2FA and recaptcha
  _data/toc/configuration-guide.yml
  guides/v2.1/cloud/configure/configuration-overview.md
  guides/v2.1/security/google-recaptcha.md
  guides/v2.1/security/two-factor-authentication.md
  guides/v2.2/cloud/configure/configuration-overview.md
  guides/v2.2/security/google-recaptcha.md
  guides/v2.2/security/two-factor-authentication.md
Labels: 2.1.x, 2.2.x, New doc

#3005 Added missing word
  guides/v2.1/cloud/setup/first-time-setup-import-prepare.md
Labels: Editorial

#2903 Refactor cli-upgrade.md tutorial
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Editorial

#3006 Update description of route element
  guides/v2.2/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: 2.2.x, 2.3.x

#3007 Fix typo mistake
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, Editorial

#3008 fix redirecting link on the index page
  index.html
  system-requirements.md
Labels: 2.2.x, Editorial

#3011 Fixed redirects to Fastly CDN content
  guides/v2.0/cloud/cdn/trouble-fastly.md
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.1/cloud/cdn/cloud-vcl-custom-snippets.md
  guides/v2.1/cloud/cdn/configure-fastly.md
  guides/v2.1/cloud/cdn/fastly-vcl-badreferer.md
  guides/v2.1/cloud/cdn/fastly-vcl-blacklist.md
  guides/v2.1/cloud/cdn/fastly-vcl-whitelist.md
  guides/v2.1/cloud/cdn/fastly-vcl-wordpress.md
  guides/v2.1/cloud/cdn/trouble-fastly.md
Labels: Editorial

#3012 Editorial fixes for contributing and security items
  .github/CONTRIBUTING.md
  _includes/contributor/rewards.md
  guides/v2.1/security/google-recaptcha.md
  guides/v2.1/security/two-factor-authentication.md
Labels: 2.x, Editorial

#3013 Weekly digest
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#3010 [MFTF 2.3.7] MQE-1117: updated document for dontSeeJsError action after bug fix
  mftf/2.3/test/actions.md
Labels: 2.3.x, Technical, internal-dev

#3009 [MFTF 2.3.7] MQE-1065: updated document for pressKey action for parameterArray syn…
  mftf/2.3/test/actions.md
Labels: 2.3.x, Technical, internal-dev

#3016 Content fixed
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3020 Fix JS bundling documentation
  guides/v2.0/frontend-dev-guide/themes/js-bundling.md
  guides/v2.1/frontend-dev-guide/themes/js-bundling.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3022 Changed example code
  guides/v2.2/config-guide/redis/redis-pg-cache.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3026 clarify version availablility
  guides/v2.2/comp-mgr/install-extensions/b2b-installation.md
Labels: 2.2.x, 2.3.x, Editorial

#3019 Fixed typo
  guides/v2.0/extension-dev-guide/message-queues/message-queues.md
  guides/v2.1/extension-dev-guide/message-queues/message-queues.md
  guides/v2.2/extension-dev-guide/message-queues/message-queues.md
  guides/v2.3/extension-dev-guide/message-queues/message-queues.md
Labels: 2.x, Editorial

#3031 removed archives-php-issue.md for magento 2.3
  guides/v2.3/install-gde/prereq/zip_install.md
Labels: 2.3.x, Editorial

#3035 fix outdated link
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
Labels: Editorial

#3040 MAGEDOC-3184: Added version-specific link to swagger schema
  guides/v2.3/rest/asynchronous-web-endpoints.md
Labels: 2.3.x, Editorial

#2768 Change requirements for strict_types declaration
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.x, Major update

#3042 updated composer.json example
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.3.x

#3014 MFTF 2.3.7: Documentation updates
  mftf/2.2/configuration.md
  mftf/2.2/data.md
  mftf/2.3/configuration.md
  mftf/2.3/data.md
  mftf/2.3/introduction.md
  mftf/2.3/test/action-groups.md
  mftf/2.3/test/actions.md
Labels: 2.3.x, Technical

#3046 Add missing close bracket
  guides/v2.1/install-gde/install/verify.md
Labels: Editorial

#3051 Remove double occurrence
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Editorial

#3053 Fix link on landing page
  .github/CONTRIBUTING.md
  index.html
Labels: 2.x, Editorial

#3055 fix spelling of maintenance in config guide
  guides/v2.1/config-guide/bootstrap/magento-modes.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
Labels: 2.1.x, 2.2.x, Editorial

#2974 Added file location for path
  guides/v2.1/ui_comp_guide/concepts/ui_comp_data_source.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_data_source.md
Labels: 2.1.x, 2.2.x, Editorial

#3056 Fixed a couple of spelling mistakes
  guides/v2.1/ui_comp_guide/components/ui-toolbar.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_linking_concept.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/ui_comp_guide/components/ui-toolbar.md
Labels: 2.1.x, 2.2.x, Editorial

#3057 Generate all navigations from _data/*yml using the same logic
  _data/footer-links.yml
  _data/toc/configuration-guide.yml
  _includes/layout/footer-links.html
  _includes/layout/nav-item.html
  _includes/layout/navigation.html
  _includes/layout/sidebar.html
Labels: Site improvements

#3059 Weekly digest
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#3058 Fix /guides/v2.2/migration/migration-migrate-data.html #3052
  guides/v2.0/migration/migration-migrate-data.md
  guides/v2.1/migration/migration-migrate-data.md
  guides/v2.2/migration/migration-migrate-data.md
Labels: 2.2.x, Waiting for response

#3025 Reordering command arguments to follow one style
  _includes/install/file-system-perms-oneuser_22.md
Labels: 2.0.x, Editorial

#3062 CBE contact information table
  _data/toc/release-notes.yml
  guides/v2.2/release-notes/bk-release-notes.md
  guides/v2.2/release-notes/cbe-support-info.md
Labels: 2.2.x, New doc

#3069 MFTF: Change --lines to --time in the mftf CLI and update the latest release
  mftf/2.3/commands/mftf.md
  mftf/2.3/introduction.md
Labels: 2.3.x, Technical

#3061 MAGEDOC-3187: MFTF - Change the Contribution Guidelines link
  _data/toc/magento-functional-testing-framework-guide-2_3.yml
  _data/toc/magento-functional-testing-framework-guide.yml
  mftf/2.2/contribution-guidelines.md
  mftf/2.3/contribution-guidelines.md
Labels: Editorial

#3076 Added space to better readability
  guides/v2.1/extension-dev-guide/build/optimal-dev-environment.md
Labels: 2.x, Editorial

#3074 Modified email template documentation (#3018)
  guides/v2.1/frontend-dev-guide/templates/template-email.md
Labels: Editorial

#3079 Add a note about order of properties in theme-images.md file.
  guides/v2.0/frontend-dev-guide/themes/theme-images.md
  guides/v2.1/frontend-dev-guide/themes/theme-images.md
Labels: 2.x, Editorial, Technical

#3067 Updated changing file permission commands to run much faster when usi…
  _includes/install/file-system-perms-oneuser.md
  _includes/install/file-system-perms-oneuser_22.md
  _includes/install/file-system-perms-twouser.md
  _includes/install/file-system-perms-twouser_22.md
  _includes/install/file-system-perms-twouser_cmds-only.md
  _includes/install/file-system-perms-twouser_cmds-only_22.md
  _includes/install/sampledata/file-sys-perms-digest.md
  _includes/install/sampledata/sample-data-clone.md
  _includes/install/trouble/rc_perms.md
  guides/m1x/install/installer-privileges_after.html
  guides/m1x/install/installer-privileges_before.html
  guides/m1x/install/installing_install.html
  guides/m1x/install/installing_upgrade_details.html
  guides/m1x/other/ht_extend_magento_rest_api.html
  guides/v2.0/cloud/before/before-setup-env-install.md
  guides/v2.0/config-guide/prod/prod_file-sys-perms.md
  guides/v2.0/install-gde/install/legacy-file-system-perms.md
  guides/v2.0/install-gde/prereq/nginx.md
  guides/v2.1/cloud/before/before-setup-env-install.md
  guides/v2.1/comp-mgr/trouble/cman/upgrade_51431.md
  guides/v2.1/config-guide/prod/prod_file-sys-perms.md
  guides/v2.1/install-gde/composer.md
  guides/v2.1/install-gde/install/legacy-file-system-perms.md
  guides/v2.1/install-gde/prereq/nginx.md
  guides/v2.2/config-guide/prod/prod_file-sys-perms.md
  guides/v2.2/install-gde/prereq/nginx.md
  guides/v2.3/install-gde/prereq/nginx.md
  guides/v2.3/release-notes/2.3.0-install.md
Labels: 2.x, Technical

#3081 Fix mixin link at bottom of js_mixins.md for all versions
  guides/v2.0/howdoi/checkout/checkout_new_step.md
  guides/v2.1/howdoi/checkout/checkout_new_step.md
Labels: 2.x, Editorial

#3073 Added consistency to dev docs
  guides/v2.1/extension-dev-guide/events-and-observers.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3071 Added customer search API request example
  guides/v2.1/get-started/gs-web-api-request.md
Labels: 2.x, Technical

#3085 Fixed top level node schema location url
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Technical

#3088 Theme updates
  Gemfile.lock
  _includes/layout/nav-item.html
  _includes/layout/navigation.html
  _includes/layout/site-nav.html
Labels: Site improvements

#3097 [fix] typo in widget_gallery
  guides/v2.0/javascript-dev-guide/widgets/widget_gallery.md
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery.md
Labels: 2.0.x, 2.1.x, Editorial

#3095 Fix add-a-javascript-module path to frontend
  _videos/fundamentals/add-a-javascript-module.md
Labels: Editorial

#3098 [fix] broken image
  guides/v2.1/pattern-library/getting-user-input/image_uploader/image_uploader.md
Labels: 2.1.x, Editorial

#3093 Update translate_practice.md
  guides/v2.1/frontend-dev-guide/translations/translate_practice.md
Labels: 2.x, Editorial

#3096 [fix] add missing space
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.2.x, Editorial

#3100 #3080 Missing page for Form Component in Magento 2.2 and 2.3 when switching from 2.0
  guides/v2.2/ui_comp_guide/components/ui-form.md
  guides/v2.3/ui_comp_guide/components/ui-form.md
Labels: 2.2.x, 2.x, Site improvements

#3101 Remove obsolete file from Cloud Guide
  guides/v2.1/cloud/before/before-setup-env-overview.md
  guides/v2.1/cloud/setup/first-time-setup.md
  guides/v2.2/cloud/before/before-setup-env-overview.md
  guides/v2.3/cloud/before/before-setup-env-overview.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3102 MAGEDOC 3201 fix
  guides/v2.3/release-notes/2.3.0-quick-start.md
  index.html
Labels: 2.3.x, Editorial

#3104 Fix callout-block markup
  guides/v2.1/config-guide/multi-master/multi-master_manual.md
Labels: 2.x, Editorial

#3103 Fix typo tales > tables
  guides/v2.1/config-guide/multi-master/multi-master.md
Labels: 2.x, Editorial

#3107 Changed ChromePHP to Chrome Logger
  guides/v2.1/config-guide/log/log-magento.md
Labels: 2.x, Editorial, Technical

#3109 Weekly digest
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#3106 Update xsd path to use urn
  guides/v2.2/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: 2.2.x, Technical

#3094 Fix Magento edition name
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, Editorial

#3113 Magento cloud magecloud 2838
  guides/v2.1/cloud/docker/docker-config.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3105 MAGECLOUD-2838: Update documentation for adding PHP 7.2
  guides/v2.1/cloud/docker/docker-config.md
Labels: In progress, internal-dev

#3116 MAGEDOC-3173: Clarify access to Commerce
  availability.md
Labels: 2.3.x, Editorial

#3111 Update index.md
  community/resources/index.md
Labels: Major update

#3120 Add beta banner to 2.3 index page, add availability info to install
  guides/v2.1/install-gde/bk-install-guide.md
  guides/v2.2/install-gde/bk-install-guide.md
  guides/v2.3/index.html
Labels: 2.3.x, Editorial

#3099 [task] introduce new mage2bloburl variable
  _config.yml
  guides/v2.0/cloud/setup/first-time-setup-import-prepare.md
  guides/v2.0/ext-best-practices/tutorials/copy-fieldsets.md
  guides/v2.0/extension-dev-guide/depend-inj.md
  guides/v2.0/extension-dev-guide/prepare/lifecycle.md
  guides/v2.0/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.0/frontend-dev-guide/themes/js-bundling.md
  guides/v2.0/javascript-dev-guide/javascript/js_mixins.md
  guides/v2.0/mtf/mtf_entities/mtf_block.md
  guides/v2.0/release-notes/backward-incompatible-changes/index.md
  guides/v2.1/cloud/setup/first-time-setup-import-prepare.md
  guides/v2.1/ext-best-practices/tutorials/copy-fieldsets.md
  guides/v2.1/extension-dev-guide/depend-inj.md
  guides/v2.1/extension-dev-guide/prepare/lifecycle.md
  guides/v2.1/extension-dev-guide/routing.md
  guides/v2.1/frontend-dev-guide/themes/js-bundling.md
  guides/v2.1/javascript-dev-guide/javascript/js_mixins.md
  guides/v2.1/javascript-dev-guide/javascript/js_overview.md
  guides/v2.1/mtf/mtf_entities/mtf_block.md
  guides/v2.1/ui_comp_guide/components/ui-exportbutton.md
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.2/mrg/ce/instant-purchase/index.md
  guides/v2.2/ui_comp_guide/components/ui-fieldset.md
  guides/v2.3/extension-dev-guide/routing.md
  guides/v2.3/ui_comp_guide/components/wysiwyg/extension-points/index.md
Labels: 2.x, Site improvements, Technical

#3127 Demo PR for SSE team
  guides/v2.1/install-gde/back-intro.md
Labels: Editorial

#3130 Replace Cyrillic letters
  _data/toc/ui-components-guide.yml
  guides/v2.0/coding-standards/code-standard-demarcation.md
  guides/v2.0/contributor-guide/backward-compatible-development/index.md
  guides/v2.0/howdoi/checkout/checkout_payment.md
  guides/v2.0/ui-components/ui-component.md
  guides/v2.1/coding-standards/code-standard-demarcation.md
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
  guides/v2.1/ui_comp_guide/bk-ui_comps.md
  guides/v2.1/ui_comp_guide/components/ui-datecolumn.md
  guides/v2.1/ui_comp_guide/components/ui-exportbutton.md
  guides/v2.1/ui_comp_guide/components/ui-fieldset.md
  guides/v2.1/ui_comp_guide/components/ui-insertform.md
  guides/v2.1/ui_comp_guide/components/ui-modal.md
  guides/v2.1/ui_comp_guide/components/ui-multiselect.md
  guides/v2.1/ui_comp_guide/components/ui-multiselectcolumn.md
  guides/v2.1/ui_comp_guide/components/ui-sizes.md
  guides/v2.1/ui_comp_guide/concepts/knockout-bindings.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.2/config-guide/prod/performance-best-practices.md
  guides/v2.2/frontend-dev-guide/themes/theme-workflow.md
  guides/v2.2/performance-best-practices/advanced-setup.md
  guides/v2.2/ui_comp_guide/bk-ui_comps.md
  guides/v2.2/ui_comp_guide/components/ui-datecolumn.md
  guides/v2.2/ui_comp_guide/components/ui-expandable-column.md
  guides/v2.2/ui_comp_guide/components/ui-exportbutton.md
  guides/v2.2/ui_comp_guide/components/ui-fieldset.md
  guides/v2.2/ui_comp_guide/components/ui-filters.md
  guides/v2.2/ui_comp_guide/components/ui-insertform.md
  guides/v2.2/ui_comp_guide/components/ui-modal.md
  guides/v2.2/ui_comp_guide/components/ui-multiselect.md
  guides/v2.2/ui_comp_guide/components/ui-multiselectcolumn.md
  guides/v2.2/ui_comp_guide/components/ui-sizes.md
  guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.2/ui_comp_guide/howto/new_component_declaration.md
  guides/v2.3/performance-best-practices/advanced-setup.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
Labels: 2.x, Editorial

#3132 Fix broken links in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Editorial

#3135 GH-3134 - Fixed all links for best practices
  community/resources/best-practices.md
Labels: Editorial

#3133 Generated backward incompatible changes (2.2.0 - 2.3)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#3129 Cloud: some small fixes in the go live checklist document.
  guides/v2.2/cloud/live/go-live-checklist.md
Labels: 2.2.x, Editorial

#3138 Fixed Cloud terminal code blocks
  guides/v2.1/cloud/before/before-setup-env-install.md
  guides/v2.1/cloud/env/environments-start.md
  guides/v2.1/cloud/env/smart-wizards.md
  guides/v2.1/cloud/integrations/bitbucket-integration.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/reference/cli-ref-topic.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-upgrade.md
Labels: Editorial

#3140 Deliver PR 3066
  mftf/2.2/introduction.md
  mftf/2.2/test/actions.md
  mftf/2.3/configuration.md
  mftf/2.3/getting-started.md
  mftf/2.3/introduction.md
  mftf/2.3/test/action-groups.md
  mftf/2.3/test/annotations.md
Labels: 2.3.x, Major update

#3139 Add MSI introduction info
  _data/main-nav.yml
  _data/toc/inventory.yml
  _data/toc/rest-api.yml
  guides/v2.3/inventory/architecture.md
  guides/v2.3/inventory/catalog-inventory-replacements.md
  guides/v2.3/inventory/images/inventory-diagram-stock.png
  guides/v2.3/inventory/overview.md
  guides/v2.3/inventory/scalable-inventory-replacements.md
  guides/v2.3/rest/tutorials/msi-order-processing/run-ssa.md
Labels: 2.3.x, Community, New doc

#3144 Fixed links in README
  README.md
Labels: Editorial

#3145 Updated links in system-requirements
  system-requirements.md
Labels: Editorial

#3146 Update contributing_dod.md
  guides/v2.1/contributor-guide/contributing_dod.md
Labels: Editorial

#3148 Fixed NEW_TOPIC issue template
  .github/ISSUE_TEMPLATE/NEW_TOPIC.md
Labels: Editorial

#3149 MAGECLOUD-2874 Double slashes in links
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Editorial

#3142 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#3136 MAGECLOUD-2478: Managed Cloud WAF updates
  _data/toc/cloud-guide.yml
  common/images/cloud/cloud-fastly-waf-403-error.png
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.1/cloud/cdn/cloud-vcl-custom-snippets.md
  guides/v2.1/cloud/cdn/fastly-image-optimization.md
  guides/v2.1/cloud/cdn/fastly-vcl-badreferer.md
  guides/v2.1/cloud/cdn/fastly-vcl-blacklist.md
  guides/v2.1/cloud/cdn/fastly-vcl-whitelist.md
  guides/v2.1/cloud/cdn/fastly-vcl-wordpress.md
  guides/v2.1/cloud/cdn/fastly-waf-service.md
  guides/v2.1/cloud/project/projects.md
  guides/v2.2/cloud/cdn/fastly-waf-service.md
  guides/v2.3/cloud/cdn/fastly-waf-service.md
Labels: Major update

#3154 rename MSI overview file
  _data/main-nav.yml
  guides/v2.3/inventory/index.md
Labels: 2.3.x, Editorial

#3151 Weekly digest
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#3155 Rename TOC link to MSI index.html
  _data/toc/inventory.yml
Labels: 2.x, Editorial

#3159 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#3160 GH-1230: add info about di.xml addition, copyedit
  guides/v2.1/howdoi/checkout/checkout_new_field.md
Labels: 2.1.x, 2.2.x, 2.3.x

#3156 MAGECLOUD-2281: Remove obsolete file
  guides/v2.1/cloud/project/admin-git-push.md
  guides/v2.1/cloud/reference/git-integration.md
  guides/v2.2/cloud/project/admin-git-push.md
  guides/v2.3/cloud/project/admin-git-push.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3166 Properly capitalize PhpStorm
  _data/toc/testing.yml
  guides/m1x/ce19-ee114/RWD_dev-guide.html
  guides/v2.0/cloud/before/before-workspace.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-urn.md
  guides/v2.0/mtf/mtf_introduction.md
  guides/v2.0/test/integration/integration_test_execution.md
  guides/v2.0/test/unit/unit_test_execution.md
  guides/v2.0/test/unit/unit_test_execution_phpstorm.md
  guides/v2.1/cloud/before/before-workspace.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-urn.md
  guides/v2.1/mtf/mtf_introduction.md
  guides/v2.1/test/integration/integration_test_execution.md
  guides/v2.1/test/unit/unit_test_execution.md
  guides/v2.1/test/unit/unit_test_execution_phpstorm.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  mftf/2.2/getting-started.md
  mftf/2.3/getting-started.md
Labels: Editorial

#3170 content fix -fix issue #3167
  guides/v2.1/frontend-dev-guide/themes/product-video.md
Labels: Editorial

#3173 Fix composer package name
  guides/v2.3/release-notes/2.3.0-install.md
Labels: Technical

#3153 Update "Name your component" topic
  guides/v2.3/extension-dev-guide/build/create_component.md
Labels: 2.3.x, Technical, internal-dev

#3163 MAGECLOUD-2577: Add possibility to import DB dump. ElasticSearch and RabbitMQ
  guides/v2.1/cloud/docker/docker-development.md
Labels: Technical, internal-dev

#3174 Update layout-overview.md
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
Labels: 2.2.x, Editorial

#3175 MAGECLOUD-2879: Added ENABLE_GOOGLE_ANALYTICS deploy variable
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3171 Fix array formatting for config settings
  guides/v2.1/cloud/live/sens-data-initial.md
  guides/v2.2/cloud/live/sens-data-initial.md
Labels: Editorial

#3161 Warning about adding Bitbucket integration
  guides/v2.1/cloud/integrations/bitbucket-integration.md
Labels: Editorial

#3177 Update global_extensibility_features.md
  guides/v2.1/architecture/global_extensibility_features.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3183 Add redirect for Inventory front page
  guides/v2.3/inventory/index.md
Labels: 2.3.x, Editorial

#3181 Update contribution guides and community resources
  .github/CONTRIBUTING.md
  common/images/contribute-feedback-link.png
  common/images/contribute-prerequisites.png
  common/images/contribute-write-submit-pr.png
  community/resources/resources.md
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/index.html
  guides/v2.3/index.html
  index.html
Labels: 2.x, Major update

#3184 Add more MSI REST documentation
  _data/toc/rest-api.yml
  guides/v2.3/rest/modules/inventory/bulk-inventory.md
  guides/v2.3/rest/modules/inventory/check-salable-quantity.md
  guides/v2.3/rest/modules/inventory/manage-low-quantity.md
  guides/v2.3/rest/modules/inventory/manage-source-selection.md
Labels: 2.3.x, Community, New doc

#3172 Add importing config file as final step for Cloud transfer
  _includes/cloud/sens-data-create-config-local.md
Labels: Technical

#3192 fix code blocks
  guides/v2.2/cloud/live/sens-data-initial.md
Labels: Editorial

#3158 MAGECLOUD-2395 Add health notifications to integrations
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/env/log-handlers.md
  guides/v2.1/cloud/env/setup-notifications.md
  guides/v2.1/cloud/env/variables-intro.md
  guides/v2.1/cloud/integrations/cloud-integrations.md
  guides/v2.1/cloud/integrations/health-notifications.md
  guides/v2.2/cloud/integrations/health-notifications.md
  guides/v2.3/cloud/integrations/health-notifications.md
Labels: 2.1.x, 2.2.x, 2.3.x, In progress, Major update

#3188 MAGECLOUD-2817 add php const to env yaml
  guides/v2.1/cloud/project/magento-env-yaml.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Technical

#3194 Weekly digest
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x

#3196 Community Resources - Add link Creatuity, update slack info
  community/resources/resources.md
Labels: 2.x, Major update

#3199 [task] propose Magestats.net to Community Resources
  community/resources/resources.md
Labels: Community

#3083 Indent the PHP Code
  guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.md
Labels: 2.x, Editorial

#3084 Fixing text
  guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.md
Labels: 2.x, Editorial

#3169 change container name attribute required value - fix issue #3168
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: Technical

#3023 Updated migration-migrate-delta.md (#2456)
  guides/v2.1/migration/migration-migrate-delta.md
  guides/v2.2/migration/migration-troubleshooting.md
Labels: 2.1.x, 2.2.x, Major update

#3202 Fix typo: _>Module> to _<Module>
  guides/v2.1/frontend-dev-guide/layouts/layout-types.md
Labels: Editorial

#3197 Configure redoc to improve rendering performance
  redoc/2.3/admin-rest-api.html
  redoc/2.3/customer-rest-api.html
  redoc/2.3/guest-rest-api.html
Labels: 2.3.x, internal-dev

#3017 Updated XSD-XML-validation.md with brief notes (#1136)
  guides/v2.0/extension-dev-guide/build/XSD-XML-validation.md
  guides/v2.1/migration/migration-migrate-delta.md
Labels: 2.x, In progress, Technical

#3193 Add Feature availability and Command-line upgrade info to release notes
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/release-notes/2.3.0-install.md
  guides/v2.3/release-notes/2.3.0-quick-start.md
Labels: 2.3.x, Editorial, internal-dev

#3201 Remove unnecessary information
  guides/v2.1/cloud/project/project-multi-sites.md
Labels: internal-dev

#3204 Add note for frontend guide blocks and containers
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, Editorial, internal-dev

#3209 GH-3162: Fix links in list items so they show
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, 2.3.x, Editorial

#3195 Added link from Cloud prerequisites topic to Nginx installation instructions
  guides/v2.1/cloud/before/before-workspace-magento-prereqs.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, internal-dev

#3214 Fixing issue - https://github.com/magento/devdocs/issues/3213
  guides/v2.1/config-guide/varnish/config-varnish.md
Labels: Editorial

#3216 [Cloud Docker] Add new services map
  guides/v2.1/cloud/docker/docker-config.md
Labels: Technical, internal-dev

#3075 Removed sprintf from translation docs
  guides/v2.1/frontend-dev-guide/translations/translate_theory.md
Labels: In progress, Technical

#3220 fix outdated link
  _data/main-nav.yml
Labels: 2.3.x, Editorial, internal-dev
