Repository magento/devdocs, pull requests merged in 2018-08, with the labels that each got.

#2663 Update secy.md
  guides/v2.1/config-guide/secy/secy.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2640 Fix issue #2634 - Add reminder to start mysql service
  _includes/install/mysql_max-allowed-packet-ubuntu.md
  guides/v2.1/install-gde/prereq/mysql.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/mysql.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2667 [fix] small typo
  guides/v2.1/config-guide/prod/config-reference-most.md
Labels: 2.1.x, Editorial

#2516 MFTF 2.3.0 documentation updates
  _data/toc/magento-functional-testing-framework-guide.yml
  guides/v2.2/magento-functional-testing-framework/release-2/best-practices.md
  guides/v2.2/magento-functional-testing-framework/release-2/commands/codeception.md
  guides/v2.2/magento-functional-testing-framework/release-2/commands/mftf.md
  guides/v2.2/magento-functional-testing-framework/release-2/commands/robo.md
  guides/v2.2/magento-functional-testing-framework/release-2/configuration.md
  guides/v2.2/magento-functional-testing-framework/release-2/data.md
  guides/v2.2/magento-functional-testing-framework/release-2/extending.md
  guides/v2.2/magento-functional-testing-framework/release-2/getting-started.md
  guides/v2.2/magento-functional-testing-framework/release-2/introduction.md
  guides/v2.2/magento-functional-testing-framework/release-2/merging.md
  guides/v2.2/magento-functional-testing-framework/release-2/metadata.md
  guides/v2.2/magento-functional-testing-framework/release-2/page.md
  guides/v2.2/magento-functional-testing-framework/release-2/section.md
  guides/v2.2/magento-functional-testing-framework/release-2/suite.md
  guides/v2.2/magento-functional-testing-framework/release-2/test.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/action-groups.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/actions.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/annotations.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/assertions.md
  guides/v2.2/magento-functional-testing-framework/release-2/update.md
  guides/v2.3/magento-functional-testing-framework/release-2/commands/mftf.md
  guides/v2.3/magento-functional-testing-framework/release-2/commands/robo.md
  guides/v2.3/magento-functional-testing-framework/release-2/extending.md
Labels: 2.2.x, 2.3.x, Major update

#2671 Fixed code in the MFTF Update
  guides/v2.2/magento-functional-testing-framework/release-2/update.md
Labels: 2.2.x, 2.3.x, Technical

#2672 Converting HTML to MD
  guides/v2.1/javascript-dev-guide/conventions_js.md
  guides/v2.1/javascript-dev-guide/javascript/custom_js.md
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
  guides/v2.1/javascript-dev-guide/javascript/js_debug.md
  guides/v2.1/javascript-dev-guide/javascript/js_init.md
  guides/v2.1/javascript-dev-guide/javascript/js_overview.md
  guides/v2.1/javascript-dev-guide/javascript/js_practice.md
  guides/v2.1/javascript-dev-guide/javascript/requirejs_concept.md
  guides/v2.1/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.1/javascript-dev-guide/widgets/widget_accordion.md
  guides/v2.1/javascript-dev-guide/widgets/widget_alert.md
  guides/v2.1/javascript-dev-guide/widgets/widget_calendar.md
  guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.1/javascript-dev-guide/widgets/widget_confirm.md
  guides/v2.1/javascript-dev-guide/widgets/widget_dialog.md
  guides/v2.2/javascript-dev-guide/javascript/js_logger.md
Labels: 2.1.x, 2.2.x, Enhancement, internal-dev

#2635 Add version-specific info for Docker config
  guides/v2.1/cloud/reference/docker-config.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2670 Update secy-cron.md
  guides/v2.1/config-guide/secy/secy-cron.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2669 [fix] issue with list rendering before collapsible - see: #2655
  guides/v2.0/ext-best-practices/extension-coding/example-module-adminpage.md
  guides/v2.1/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: 2.0.x, 2.1.x

#2675 Generated backward incompatible changes for Magento B2B
  _includes/backward-incompatible-changes/b2b/1.0.2-1.0.3.html
  _includes/backward-incompatible-changes/b2b/1.0.3-1.0.4.html
  _includes/backward-incompatible-changes/b2b/1.0.4-1.0.5.html
  guides/v2.2/release-notes/backward-incompatible-changes/b2b.md
Labels: 2.2.x, Technical

#2525 Add section with routes alias
  guides/v2.3/extension-dev-guide/webapi/custom-routes.md
Labels: 2.3.x, Community, New doc

#2431 Add Operation Status Search documentation
  guides/v2.3/rest/operation-status-search.md
Labels: 2.3.x, Community, New doc

#2679 MAGEDOC-3095: Fix broken link on 404 page
  404.md
Labels: 2.x, internal-dev

#2680 Fixes in the MFTF Getting started
  _data/toc/magento-functional-testing-framework-guide.yml
  guides/v2.2/magento-functional-testing-framework/release-2/commands/mftf.md
  guides/v2.2/magento-functional-testing-framework/release-2/getting-started.md
  guides/v2.2/magento-functional-testing-framework/release-2/introduction.md
Labels: 2.2.x, 2.3.x, Technical

#2681 Update secy-xframe.md
  guides/v2.1/config-guide/secy/secy-xframe.md
Labels: 2.x, Editorial

#2686 MAGEDOC-2910: Fix typo
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
Labels: 2.2.x, 2.3.x, Editorial, internal-dev

#2689 correct an endpoint route
  guides/v2.2/b2b/credit-manage.md
Labels: 2.2.x, 2.3.x, Technical

#2688 GH-2664 tls redirect
  guides/v2.0/install-gde/system-requirements-tls-parent.md
  guides/v2.0/install-gde/system-requirements_repo-tls1-2.md
  guides/v2.1/install-gde/system-requirements-tls-parent.md
  guides/v2.1/install-gde/system-requirements_repo-tls1-2.md
  guides/v2.2/install-gde/system-requirements-tls-parent.md
  guides/v2.3/install-gde/system-requirements-tls-parent.md
Labels: 2.x, Cleanup

#2687 MAGEDOC-3021: Delete draft topic
  guides/v2.1/install-gde/install/hosted/hosted_start_cron.md
  guides/v2.2/install-gde/install/hosted/hosted_start_cron.md
  guides/v2.3/install-gde/install/hosted/hosted_start_cron.md
Labels: 2.x, Editorial, internal-dev

#2692 Delete orphaned HTML
  guides/v2.0/install-gde/system-requirements-tls-parent.html
  guides/v2.1/install-gde/install/hosted/hosted_start_cron.html
  guides/v2.1/install-gde/system-requirements-tls-parent.html
  guides/v2.2/install-gde/install/hosted/hosted_start_cron.html
  guides/v2.2/install-gde/system-requirements-tls-parent.html
  guides/v2.3/install-gde/install/hosted/hosted_start_cron.html
  guides/v2.3/install-gde/system-requirements-tls-parent.html
Labels: 2.x, internal-dev

#2684 Change Region IPs
  guides/v2.1/cloud/env/environments-start.md
Labels: 2.x, Technical, internal-dev

#2694 Remove rsync topic and redirect to revised CLI topic
  _data/toc/configuration-guide.yml
  guides/v2.2/config-guide/deployment/pipeline/example/cli.md
  guides/v2.2/config-guide/deployment/pipeline/example/rsync.md
  guides/v2.3/config-guide/deployment/pipeline/example/rsync.md
Labels: Cleanup, Editorial, internal-dev

#2674 JS Dev Guide HTML to MD Conversion
  guides/v2.1/javascript-dev-guide/back_to_guide.md
  guides/v2.1/javascript-dev-guide/bk-javascript-dev-guide.md
  guides/v2.1/javascript-dev-guide/conventions_js.md
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery.md
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery_mg.md
  guides/v2.1/javascript-dev-guide/widgets/widget_list.md
  guides/v2.1/javascript-dev-guide/widgets/widget_loader.md
  guides/v2.1/javascript-dev-guide/widgets/widget_menu.md
  guides/v2.1/javascript-dev-guide/widgets/widget_modal.md
  guides/v2.1/javascript-dev-guide/widgets/widget_navigation.md
  guides/v2.1/javascript-dev-guide/widgets/widget_prompt.md
  guides/v2.1/javascript-dev-guide/widgets/widget_quickSearch.md
  guides/v2.1/javascript-dev-guide/widgets/widget_tabs.md
Labels: 2.1.x, internal-dev

#2693 Update framework.md
  guides/v2.1/architecture/archi_perspectives/framework.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2683 Add a prompt to checkout the correct repo branch
  _includes/install/sampledata/sample-data-clone.md
Labels: 2.x, Technical

#2701 Fix path to theme.less
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: 2.x, Editorial

#2661 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/commerce/2.2.0-develop.html
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.2.x, 2.3.x, Technical

#2702 Fixed typo mistakes in ui_comp_guide files
  guides/v2.1/ui_comp_guide/components/ui-actionscolumn.md
  guides/v2.1/ui_comp_guide/components/ui-column.md
  guides/v2.1/ui_comp_guide/components/ui-multiselectcolumn.md
  guides/v2.1/ui_comp_guide/components/ui-onoffcolumn.md
  guides/v2.1/ui_comp_guide/components/ui-thumbnailcolumn.md
  guides/v2.2/ui_comp_guide/components/ui-actionscolumn.md
  guides/v2.2/ui_comp_guide/components/ui-column.md
  guides/v2.2/ui_comp_guide/components/ui-multiselectcolumn.md
  guides/v2.2/ui_comp_guide/components/ui-onoffcolumn.md
  guides/v2.2/ui_comp_guide/components/ui-thumbnailcolumn.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2703 Weekly update of Whats New on DevDocs
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.2.x, 2.3.x, Editorial

#2690 MFTF-Fix Getting Started
  guides/v2.2/magento-functional-testing-framework/release-2/getting-started.md
Labels: 2.2.x, 2.3.x, Technical, Tracking, internal-dev

#2706 Hg bugs
  guides/v2.1/cloud/reference/docker-config.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
Labels: Editorial

#2707 Fixed syntax and version reference error
  guides/v2.1/cloud/reference/docker-config.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
Labels: Editorial

#2658 GH2104 - cli enable disable commands for profiler
  guides/v2.1/config-guide/bootstrap/mage-profiler.md
  guides/v2.2/config-guide/bootstrap/mage-profiler.md
Labels: 2.2.x, 2.3.x, Community, Major update

#2704 MAGEDOC-3101: Fix Introduction
  guides/v2.2/magento-functional-testing-framework/release-2/introduction.md
Labels: 2.2.x, 2.3.x, Technical

#2615 MC-3310: CE changes for TinyMCE4/WYSIWYG events and methods
  guides/v2.3/ui_comp_guide/components/ui-wysiwyg.md
  guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/index.md
Labels: 2.3.x, Major update

#2712 Update Cloud plans page
  _data/var.yml
  guides/v2.1/cloud/basic-information/cloud-plans.md
Labels: Editorial

#2720 Remove hardcoded version from page-baseurl-generator
  _plugins/page-baseurl-generator.rb
Labels: 2.x, Site improvements

#2723 Fix 'page-baseurl-generator'
  _plugins/page-baseurl-generator.rb
Labels: 2.x, Site improvements

#2724 Updated devdocs templates
  guides/v2.1/contributor-guide/templates/basic_template.md
  guides/v2.1/contributor-guide/templates/tutorial-template-first.md
Labels: 2.x, Editorial

#2726 Update navigation in preparation for bulk and asynchronous API topics
  _data/toc/php-developer-guide.yml
  _data/toc/rest-api.yml
  common/images/b2b/payment-on-credit.png
  common/images/b2b/quote-checkout-process.png
  common/images/b2b/quote-statuses.png
  common/images/b2b/quote-workflow.jpg
  guides/v2.2/b2b/company-credit.md
  guides/v2.2/b2b/credit-parent.md
  guides/v2.2/b2b/negotiable-checkout.md
  guides/v2.2/b2b/negotiable-quote.md
  guides/v2.3/b2b/credit-parent.md
  guides/v2.3/b2b/images/payment-on-credit.png
  guides/v2.3/b2b/images/quote-checkout-process.png
  guides/v2.3/b2b/images/quote-statuses.png
  guides/v2.3/b2b/images/quote-workflow.jpg
  guides/v2.3/extension-dev-guide/webapi/custom-routes.md
Labels: 2.x, Editorial

#2727 Put back the Install dependencies note
  guides/v2.1/cloud/reference/docker-config.md
Labels: Editorial

#2733 Add verbal predicate to the sentence
  _includes/config/php-memcache.md
Labels: Editorial

#2734 Updated the Whats New on Devdocs page
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2718 GH2676 - Update PHP version for nginx prereqs
  guides/v2.1/install-gde/prereq/nginx.md
  guides/v2.2/install-gde/prereq/nginx.md
  guides/v2.3/install-gde/prereq/nginx.md
Labels: 2.2.x, 2.3.x, Major update

#2730 Remove wrong and irrelevant information
  guides/v2.1/config-guide/redis/config-redis.md
  guides/v2.2/config-guide/redis/config-redis.md
Labels: Editorial

#2737 Update theme-inherit.md
  guides/v2.1/frontend-dev-guide/themes/theme-inherit.md
Labels: Editorial

#2731 Removing extra space
  guides/v2.1/cloud/project/ece-tools-upgrade-project.md
Labels: Editorial, internal-dev

#2735 Updated plugin req for Fastly IO
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.1/cloud/cdn/fastly-image-optimization.md
  guides/v2.2/cloud/basic-information/cloud-fastly.md
  guides/v2.2/cloud/cdn/cloud-fastly.md
  guides/v2.3/cloud/basic-information/cloud-fastly.md
  guides/v2.3/cloud/cdn/cloud-fastly.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Technical

#2397 Add documentation about BULK API endpoints
  guides/v2.3/rest/bulk-endpoints.md
Labels: 2.3.x, Community, New doc

#2714 MAGECLOUD-2128 Multi-site URLs
  common/images/config_multi-site_base-url-default2.png
  common/images/config_multi-site_base-url.png
  guides/v2.1/cloud/access-acct/first-time-setup_import-prepare.md
  guides/v2.1/cloud/project/project-conf-files_magento-app.md
  guides/v2.1/cloud/project/project-conf-files_routes.md
  guides/v2.1/cloud/project/project-multi-sites.md
  guides/v2.1/config-guide/multi-site/ms_over.md
  guides/v2.1/config-guide/multi-site/ms_websites.md
  guides/v2.2/cloud/project/project-start.md
Labels: 2.1.x, 2.2.x, Editorial, In progress, Technical

#2741 MAGECLOUD-2601 Corrected Elasticsearch release note
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, Technical

#2745 [fix] typo in rest tutorial
  guides/v2.3/rest/tutorials/msi-order-processing/create-cart-add-products.md
  guides/v2.3/rest/tutorials/msi-order-processing/run-ssa.md
Labels: 2.3.x, Editorial

#2739 Building DevDocs in Windows
  README.md
Labels: Site improvements

#2746 converting HTML to md
  guides/v2.1/get-started/authentication/gs-authentication-oauth.md
  guides/v2.1/get-started/authentication/gs-authentication-token.md
  guides/v2.1/get-started/authentication/oauth-errors.md
  guides/v2.1/get-started/create-integration.md
  guides/v2.1/get-started/gs-curl.md
  guides/v2.1/get-started/gs-web-api-request.md
Labels: 2.x, Editorial

#2748 replace pro with essentials
  guides/v2.1/cloud/basic-information/cloud-plans.md
Labels: Editorial

#2747 Replace HTML markup
  guides/v2.2/b2b/company-object.md
  guides/v2.2/b2b/negotiable-manage.md
  guides/v2.2/b2b/negotiable-quote.md
  guides/v2.2/b2b/roles.md
Labels: 2.2.x, 2.3.x, Editorial

#2749 Fix link to contributing.md
  .github/PULL_REQUEST_TEMPLATE.md
  _data/toc/contributor-guide.yml
  _includes/home/contributors.html
  _includes/layout/footer-links.html
  community/resources/index.md
  guides/v2.0/contributor-guide/contributing.md
  guides/v2.0/contributor-guide/quarterly-contributors.md
  guides/v2.0/magento-devdocs-whatsnew.md
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/contributor-guide/quarterly-contributors.md
  guides/v2.1/magento-devdocs-whatsnew.md
  guides/v2.2/magento-functional-testing-framework/contribution-guidelines.md
Labels: 2.x, Editorial

#2751 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/commerce/2.2.0-develop.html
Labels: 2.3.x, Technical

#2744 Merge the develop branch with master
  _includes/install/php_2.2.md
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_and_areas.md
  guides/v2.1/architecture/archi_perspectives/framework.md
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.md
  guides/v2.2/release-notes/ReleaseNotes2.2.1CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
  guides/v2.2/ui_comp_guide/concepts/magento-bindings.md
Labels: Technical

#2740 GH2736 - Add new labels and Magento Contributor Assistant to contributor guide
  guides/v2.0/contributor-guide/contributing.md
  guides/v2.1/contributor-guide/contributing.md
Labels: 2.x, Major update

#2752 Fix: Added the missing symlink
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.md
Labels: 2.2.x, Editorial

#2753 Convert HTML for REST and GraphQL guides
  guides/v2.1/rest/anonymous-api-security.md
  guides/v2.1/rest/bk-rest.md
  guides/v2.1/rest/generate-local.md
  guides/v2.1/rest/performing-searches.md
  guides/v2.1/rest/retrieve-filtered-responses.md
  guides/v2.1/rest/tutorials/index.md
  guides/v2.1/rest/tutorials/orders/order-create-customer.md
  guides/v2.1/rest/tutorials/orders/order-create-quote.md
  guides/v2.1/rest/tutorials/orders/order-prepare-checkout.md
  guides/v2.2/rest/anonymous-api-security.md
  guides/v2.2/rest/generate-local.md
  guides/v2.2/rest/modules/catalog-pricing.md
  guides/v2.2/rest/performing-searches.md
  guides/v2.2/rest/retrieve-filtered-responses.md
  guides/v2.2/rest/tutorials/configurable-product/create-configurable-product.md
  guides/v2.2/rest/tutorials/configurable-product/plan-product.md
  guides/v2.2/rest/tutorials/index.md
  guides/v2.3/graphql/reference/categories.md
  guides/v2.3/graphql/search-pagination.md
  guides/v2.3/rest/performing-searches.md
  guides/v2.3/rest/retrieve-filtered-responses.md
Labels: 2.x, Editorial

#2754 Missing paren
  guides/v2.1/cloud/access-acct/fastly.md
Labels: Editorial

#2755 Update webapi.md
  guides/v2.1/coding-standards/technical-vision/webapi.md
Labels: 2.3.x, internal-dev

#2764 Refactored the Rakefile
  Rakefile
Labels: Site improvements

#2759 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2766 Lk contributing guide formats
  guides/v2.0/contributor-guide/backward-compatible-development/index.md
  guides/v2.0/contributor-guide/contributing.md
  guides/v2.0/contributor-guide/contributing_dod.md
  guides/v2.0/contributor-guide/quarterly-contributors.md
  guides/v2.0/contributor-guide/templates/basic_template.md
  guides/v2.0/contributor-guide/templates/tutorial-template-first.md
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/contributor-guide/contributing_dod.md
  guides/v2.1/contributor-guide/templates/basic_template.md
  guides/v2.1/contributor-guide/templates/tutorial-template-first.md
Labels: 2.0.x, 2.1.x, Editorial

#2628 Add example code to the MFTF Action page
  guides/v2.2/magento-functional-testing-framework/2.3/test/actions.md
Labels: 2.2.x, Major update, Technical, Tracking, internal-dev

#2771 Fixed Typos
  guides/v2.1/config-guide/config/config-create.md
Labels: 2.x, Editorial

#2773 Updated What's New on Devdocs
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2774 Fixed a couple of spelling mistakes
  guides/v2.0/coding-standards/docblock-standard-javascript.md
  guides/v2.1/coding-standards/docblock-standard-javascript.md
  guides/v2.2/extension-dev-guide/message-queues/implement-bulk.md
  guides/v2.3/extension-dev-guide/message-queues/implement-bulk.md
  swagger/lib/marked.js
Labels: 2.x, Editorial

#2779 MFTF fixes: redirects, formatting, mftf run:test CLI
  guides/v2.2/magento-functional-testing-framework/2.2/best-practices.md
  guides/v2.2/magento-functional-testing-framework/2.2/commands/codeception.md
  guides/v2.2/magento-functional-testing-framework/2.2/commands/robo.md
  guides/v2.2/magento-functional-testing-framework/2.2/configuration.md
  guides/v2.2/magento-functional-testing-framework/2.2/data.md
  guides/v2.2/magento-functional-testing-framework/2.2/getting-started.md
  guides/v2.2/magento-functional-testing-framework/2.2/introduction.md
  guides/v2.2/magento-functional-testing-framework/2.2/merging.md
  guides/v2.2/magento-functional-testing-framework/2.2/metadata.md
  guides/v2.2/magento-functional-testing-framework/2.2/page.md
  guides/v2.2/magento-functional-testing-framework/2.2/section.md
  guides/v2.2/magento-functional-testing-framework/2.2/section/locator-functions.md
  guides/v2.2/magento-functional-testing-framework/2.2/section/parameterized-selectors.md
  guides/v2.2/magento-functional-testing-framework/2.2/suite.md
  guides/v2.2/magento-functional-testing-framework/2.2/test.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/action-groups.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/actions.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/annotations.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/assertions.md
  guides/v2.2/magento-functional-testing-framework/2.2/troubleshooting.md
  guides/v2.2/magento-functional-testing-framework/2.2/update.md
  guides/v2.2/magento-functional-testing-framework/2.3/commands/codeception.md
  guides/v2.2/magento-functional-testing-framework/2.3/commands/mftf.md
  guides/v2.2/magento-functional-testing-framework/2.3/configuration.md
  guides/v2.2/magento-functional-testing-framework/2.3/data.md
  guides/v2.2/magento-functional-testing-framework/2.3/extending.md
  guides/v2.2/magento-functional-testing-framework/2.3/getting-started.md
  guides/v2.2/magento-functional-testing-framework/2.3/introduction.md
  guides/v2.2/magento-functional-testing-framework/2.3/merging.md
  guides/v2.2/magento-functional-testing-framework/2.3/metadata.md
  guides/v2.2/magento-functional-testing-framework/2.3/page.md
  guides/v2.2/magento-functional-testing-framework/2.3/section.md
  guides/v2.2/magento-functional-testing-framework/2.3/section/locator-functions.md
  guides/v2.2/magento-functional-testing-framework/2.3/section/parameterized-selectors.md
  guides/v2.2/magento-functional-testing-framework/2.3/suite.md
  guides/v2.2/magento-functional-testing-framework/2.3/test.md
  guides/v2.2/magento-functional-testing-framework/2.3/test/action-groups.md
  guides/v2.2/magento-functional-testing-framework/2.3/test/actions.md
  guides/v2.2/magento-functional-testing-framework/2.3/test/annotations.md
  guides/v2.2/magento-functional-testing-framework/2.3/test/assertions.md
  guides/v2.2/magento-functional-testing-framework/2.3/troubleshooting.md
  guides/v2.2/magento-functional-testing-framework/2.3/update.md
  guides/v2.2/magento-functional-testing-framework/release-1/cest/action-groups.md
Labels: 2.2.x, 2.3.x, Technical

#2781 [BUGFIX] Removed incorrect reference from columns to rows
  guides/v2.1/ui_comp_guide/components/ui-textarea.md
Labels: 2.1.x, Technical

#2778 MAGECLOUD-2540: Added 2-FA and Google reCAPTCHA
  guides/v2.1/cloud/configure/configuration-overview.md
  guides/v2.2/cloud/configure/configuration-overview.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2742 Including 2.3-specific Action information
  guides/v2.3/extension-dev-guide/routing.md
Labels: 2.3.x, Major update, internal-dev

#2782 Update info about local Swagger instance
  guides/v2.1/rest/generate-local.md
Labels: 2.x, Technical

#2783 Update required php extensions
  guides/v2.2/performance-best-practices/software.md
  guides/v2.3/performance-best-practices/software.md
Labels: 2.2.x, 2.3.x, Technical

#2786 Removed Solr reference from v2.2 requirements
  guides/v2.2/cloud/requirements/cloud-requirements.md
Labels: Editorial

#2660 Reverted and converted to kramdown the 'Set up the updater' topic
  _data/toc/installation-guide.yml
  common/images/install_mage2_clone-https.png
  common/images/install_mage2_clone-ssh.png
  guides/v2.1/install-gde/prereq/prereq_updater.md
Labels: 2.1.x, Technical

#2776 Update tutorial documentation
  guides/v2.1/contributor-guide/templates/tutorial-template-first.md
  guides/v2.1/contributor-guide/templates/tutorial-template-last.md
  guides/v2.1/contributor-guide/templates/tutorial-template-middle.md
Labels: 2.x, Editorial

#2775 MAGECLOUD-2581 use env variable to add creds
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/access-acct/first-time-setup_import-prepare.md
  guides/v2.1/cloud/before/before-setup-env-install.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2787 symlink generate-local.md
  guides/v2.2/rest/generate-local.md
Labels: 2.2.x, 2.3.x, Editorial

#2788 migrate PR-1773 to v2.1+
  guides/v2.1/get-started/authentication/gs-authentication-oauth.md
Labels: 2.x, Technical

#1658 Cache description elaborate.
  guides/v2.2/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.2.x

#2785 Fixed heading issue: Updated xml-instructions.md
  guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.x, Editorial

#2790 fix spelling mistakes in contributor-guide
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/contributor-guide/templates/tutorial-template-first.md
  guides/v2.1/contributor-guide/templates/tutorial-template-last.md
  guides/v2.1/contributor-guide/templates/tutorial-template-middle.md
Labels: 2.1.x, Editorial

#2792 JavaScript > Shim section > Fixing Markdown syntax
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.x, Editorial

#2795 Removed recursive link
  guides/v2.2/advanced-reporting/data-collection.md
Labels: 2.2.x, Editorial

#2772 Update config-cli-subcommands-index.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-index.md
Labels: 2.2.x, 2.3.x, Editorial, Waiting for response

#2521 Added information about when a patch is being applied
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
Labels: 2.3.x, Technical

#2806 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2805 Enable the browser auto refresh feature
  _config.yml
Labels: Site improvements

#2803 Updated rake tasks
  Rakefile
  rakelib/converter.rb
  rakelib/jekyll.rb
  rakelib/preview.rake
  rakelib/proofer.rb
  rakelib/rake-helper.rb
  rakelib/test.rake
  rakelib/update.rake
Labels: Site improvements

#2808 Update indentation coding standard
  guides/v2.1/coding-standards/code-standard-javascript.md
Labels: 2.x

#2809 Fixed rake preview:all
  rakelib/preview.rake
Labels: Site improvements

#2815 Fixed variable-name in comment
  _videos/fundamentals/add-new-product-attribute.md
Labels: Technical

#2817 Added install and configure grunt section in v2.2
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.2.x, Editorial

#2818 #2763: Added auto flag missing in data migration devdocs
  guides/v2.1/migration/migration-migrate-data.md
Labels: 2.1.x, Editorial

#2819 Fix code samples to match 4 space standard
  guides/v2.1/coding-standards/code-standard-javascript.md
Labels: 2.x

#2802 Corrected name of staging and prod deploy log
  guides/v2.1/cloud/live/stage-prod-test.md
  guides/v2.1/cloud/project/project-start.md
  guides/v2.1/cloud/trouble/environments-logs.md
  guides/v2.2/cloud/project/project-start.md
  guides/v2.2/cloud/trouble/environments-logs.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2811 MAGECLOUD-1962 update delete instructions
  guides/v2.1/cloud/env/environments-start.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2816 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2822 fix typo and remove stray text
  guides/v2.3/rest/tutorials/msi-order-processing/create-stock.md
Labels: 2.3.x, Editorial

#2797 Restore related topics link
  guides/v2.2/advanced-reporting/data-collection.md
Labels: 2.2.x, Editorial

#2824 Merge the develop branch
  .github/CONTRIBUTING.md
Labels: 2.x

#2825 Removed redundant TOCs
  guides/v2.0/extension-dev-guide/indexing.md
  guides/v2.0/howdoi/php/php_clear-dirs.md
  guides/v2.0/install-gde/trouble/tshoot_sample-data.md
  guides/v2.1/config-guide/elasticsearch/es-config-apache.md
  guides/v2.1/extension-dev-guide/package/package_module.md
  guides/v2.1/frontend-dev-guide/templates/template-email.md
  guides/v2.1/howdoi/php/php_clear-dirs.md
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-deployment.md
  guides/v2.1/install-gde/install/hosted/hosted_start.md
  guides/v2.1/install-gde/trouble/tshoot_sample-data.md
  guides/v2.2/install-gde/trouble/tshoot_sample-data.md
  guides/v2.3/config-guide/elasticsearch/es-config-apache.md
  guides/v2.3/config-guide/elasticsearch/es-config-nginx.md
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
Labels: 2.x, Editorial

#2814 Updated code of ProductCategoryFilter
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
Labels: 2.2.x, Technical

#2820 Update configuration.md
  guides/v2.2/performance-best-practices/configuration.md
Labels: 2.2.x, 2.3.x, Editorial, Waiting for response

#2829 Update the Whats New on DevDocs topic
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2828 MFTF 2.3.6: Test Data now no longer needs to be specific to scope
  guides/v2.2/magento-functional-testing-framework/2.3/data.md
Labels: 2.2.x, 2.3.x, Technical

#2831 MFTF 2.3.5: Editorial updates
  guides/v2.2/magento-functional-testing-framework/2.2/best-practices.md
  guides/v2.2/magento-functional-testing-framework/2.2/commands/codeception.md
  guides/v2.2/magento-functional-testing-framework/2.2/commands/robo.md
  guides/v2.2/magento-functional-testing-framework/2.2/configuration.md
  guides/v2.2/magento-functional-testing-framework/2.2/data.md
  guides/v2.2/magento-functional-testing-framework/2.2/getting-started.md
  guides/v2.2/magento-functional-testing-framework/2.2/introduction.md
  guides/v2.2/magento-functional-testing-framework/2.2/merging.md
  guides/v2.2/magento-functional-testing-framework/2.2/metadata.md
  guides/v2.2/magento-functional-testing-framework/2.2/page.md
  guides/v2.2/magento-functional-testing-framework/2.2/section.md
  guides/v2.2/magento-functional-testing-framework/2.2/section/locator-functions.md
  guides/v2.2/magento-functional-testing-framework/2.2/section/parameterized-selectors.md
  guides/v2.2/magento-functional-testing-framework/2.2/suite.md
  guides/v2.2/magento-functional-testing-framework/2.2/test.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/action-groups.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/actions.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/annotations.md
  guides/v2.2/magento-functional-testing-framework/2.2/test/assertions.md
  guides/v2.2/magento-functional-testing-framework/2.2/troubleshooting.md
  guides/v2.2/magento-functional-testing-framework/2.2/update.md
  guides/v2.2/magento-functional-testing-framework/2.3/getting-started.md
  guides/v2.2/magento-functional-testing-framework/2.3/introduction.md
  guides/v2.2/magento-functional-testing-framework/2.3/update.md
Labels: 2.2.x, 2.3.x, Editorial

#2833 Fixed broken link
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2834 Typo fixes in Extension dev guide
  guides/v2.1/extension-dev-guide/bk-extension-dev-guide.md
  guides/v2.1/extension-dev-guide/intro/developers_roadmap.md
  guides/v2.1/extension-dev-guide/service-contracts/service-contracts.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2804 MAGECLOUD-2625: Added New Relic acct mgmt info
  guides/v2.1/cloud/project/new-relic.md
Labels: 2.1.x, 2.2.x, Major update

#2838 [fix] missing spaces in mtf section
  guides/v2.1/mtf/mtf_entities/mtf_fixture.md
  guides/v2.1/mtf/mtf_entities/mtf_handler.md
  guides/v2.1/mtf/mtf_introduction.md
  guides/v2.1/mtf/mtf_quickstart.md
  guides/v2.1/mtf/mtf_quickstart/mtf_quickstart_environment.md
  guides/v2.1/mtf/mtf_quickstart/mtf_quickstart_runtest.md
  guides/v2.1/mtf/mtf_update.md
Labels: 2.1.x, Editorial

#2830 MAGEDOC-3058: Migration guide infographics
  _data/toc/migration-guide.yml
  common/images/MigrationModes2.png
  common/images/MigrationOverview2.png
  common/images/MigrationSteps2.png
  guides/v2.1/migration/migration-overview-how.md
Labels: 2.x, Editorial, Technical, Tracking

#2844 Fixed typo mistakes.
  guides/m1x/api/rest/introduction.html
  guides/v2.1/ext-best-practices/storefront/storefront-best-practices.md
  guides/v2.1/release-notes/ReleaseNotes2.1.13CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.13EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
Labels: Editorial

#2845 Updated magento-devdocs-whatsnew.md
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: Editorial

#2843 Fixed link target issue.
  guides/v2.1/ext-best-practices/bk-ext-best-practices.md
Labels: Editorial

#2839 Fixed broken directory output
  guides/v2.1/frontend-dev-guide/templates/template-email.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Waiting for response
