Repository magento/devdocs, pull requests merged in 2018-02, with the labels that each got.

#1700 Update observers-bp.md
  guides/v2.0/ext-best-practices/extension-coding/observers-bp.md
Labels: 2.x, Doc update

#1718 Correct a minor typo
  guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.md
Labels: 2.x

#1722 Update magento-modes.md
  guides/v2.0/config-guide/bootstrap/magento-modes.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
Labels: Doc update

#1726 Corrected typo mistake
  guides/v2.0/ext-best-practices/extension-coding/common-programming-bp.md
Labels: Doc bug

#1728 Fix typo: enviornment -> environment
  guides/v2.2/cloud/env/environments.md
Labels: Doc bug

#1731 add informormation about MariaDB to MySQL Page
  guides/v2.2/install-gde/prereq/mysql.md
Labels: 2.2.x, Doc update
