Repository magento/devdocs, pull requests merged in 2018-04, with the labels that each got.

#1790 Fixed broken markup
  guides/v2.0/javascript-dev-guide/widgets/widget_tabs.md
Labels: 2.x, Doc bug

#1765 Notice about change since 2.2 to after plugins with direct link to documentation
  guides/v2.2/ext-best-practices/extension-coding/common-programming-bp.md
Labels: 2.2.x, Doc update

#1795 Fixed broken markup
  guides/v2.1/javascript-dev-guide/widgets/widget_tabs.md
Labels: 2.1.x, Doc bug

#1799 remove dry run from deploy static
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
Labels: 2.2.x, Doc update

#1798 change magento cli to bin/magento and add in bin info for system PATH
  _includes/config/code-backup.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-compiler.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-cron.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-depen.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-layout-xml.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-less-sass.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-spt-util.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-test.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-urn.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-compiler.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-cron.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-depen.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-layout-xml.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-less-sass.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-spt-util.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-test.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-urn.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-compiler.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-export.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-import.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-cron.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-perf-data.md
Labels: 2.x, Doc update

#1793 Update example of requirejs-config.js file
  guides/v2.1/howdoi/checkout/checkout_new_step.md
Labels: 2.x, Doc bug

#1797 Update jasmine.md
  guides/v2.2/test/js/jasmine.md
Labels: 2.x, Doc bug

#1796 Update test_js-unit.md
  guides/v2.1/test/js/test_js-unit.md
Labels: 2.x, Doc bug

#1807 Adding more information about Blackfire configuration, including automated tests
  _data/toc/cloud-guide.yml
  common/images/cloud_blackfire-recommendations.png
  common/images/cloud_blackfire.png
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: 2.x, Doc update

#1809 Fixed typo
  guides/m1x/magefordev/mage-for-dev-1.html
Labels: Doc bug

#1811 Update mage-for-dev-4.html
  guides/m1x/magefordev/mage-for-dev-4.html
Labels: Editorial

#1810 Update mage-for-dev-1.html
  guides/m1x/magefordev/mage-for-dev-1.html
Labels: Editorial

#1813 fixed typo
  guides/v2.2/config-guide/config/disable-module-output.md
Labels: 2.2.x, Editorial

#1818 MAGEDOC-2915: Add symlinks for 2.2 and 2.3
  guides/v2.2/contributor-guide/img/maintainers-sneak-peek.jpg
  guides/v2.3/contributor-guide/img/maintainers-sneak-peek.jpg
Labels: 2.2.x, 2.3.x, Editorial

#1819 MAGEDOC-2915: Fix typo
  guides/v2.1/contributor-guide/devdocs-maintainers.md
Labels: Editorial

#1821 1580: Less compilation
  guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Technical

#1823 1618: Google fonts
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, Technical

#1825 1340: Base URL is case sensitive
  guides/v2.0/install-gde/trouble/tshoot_admin.md
  guides/v2.1/install-gde/trouble/tshoot_admin.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#1827 1569: Feedback on using fonts
  guides/v2.1/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Technical

#1822 Imagine 2018 docathon contributions
  guides/v2.0/install-gde/trouble/tshoot_admin.md
  guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.1/frontend-dev-guide/css-topics/using-fonts.md
  guides/v2.1/frontend-dev-guide/themes/theme-create.md
  guides/v2.1/install-gde/trouble/tshoot_admin.md
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.x, Editorial, Technical
