Repository magento/devdocs, pull requests merged in 2018-06, with the labels that each got.

#2042 [fix] typos in performance
  guides/v2.2/performance-best-practices/configuration.md
  guides/v2.2/performance-best-practices/hardware.md
  guides/v2.2/performance-best-practices/reference-architecture.md
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
  guides/v2.3/performance-best-practices/reference-architecture.md
Labels: Editorial

#1953 #1943 adding in code for hosting multiple websites in one virtual host
  guides/v2.1/config-guide/multi-site/ms_nginx.md
  guides/v2.1/config-guide/multi-site/ms_over.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2047 Removing bread crumbs functionality
  _includes/layout/breadcrumbs.html
  _plugins/breadcrumbs.rb
  _plugins/drops/breadcrumb_item.rb
  _plugins/page-breadcrumbs-generator.rb
Labels: 2.x, Enhancement

#2048 1238: Simplify cloning section and link to GitHub's docs
  common/images/install_mage2_clone-https.png
  common/images/install_mage2_clone-ssh.png
  guides/v2.1/install-gde/prereq/dev_install.md
Labels: Editorial

#2059 [fix] typo in 2.1 mtf section
  guides/v2.1/mtf/create_test/create_new_test.md
Labels: 2.1.x, Editorial

#2060 [fix] typos in marketplace
  guides/v2.1/marketplace/eqp/packages.md
Labels: 2.2.x, Editorial

#2062 [fix] typo in whatsnew
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.1.x, Editorial

#2061 [fix] typos in mftf
  guides/v2.2/magento-functional-testing-framework/contribution-guidelines.md
  guides/v2.2/magento-functional-testing-framework/release-1/cest/actions.md
  guides/v2.2/magento-functional-testing-framework/release-2/metadata.md
  guides/v2.2/magento-functional-testing-framework/release-2/section.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/actions.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/annotations.md
Labels: 2.2.x, Editorial

#2063 [fix] typo in ext-best-practice
  guides/v2.1/ext-best-practices/extension-coding/working-with-arch-bp.md
  guides/v2.1/ext-best-practices/storefront/storefront-best-practices.md
Labels: 2.x, Editorial

#2066 Update js-resources.md
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: Editorial, Partner: Wagento, partners-contribution

#2069 Typo error in documention
  guides/v2.0/pattern-library/getting-user-input/row_pattern/row_pattern.md
Labels: Editorial

#2071 Fixed typo mistake in migration guide.
  guides/v2.0/migration/migration-tool-internal-spec.md
Labels: Editorial

#2067 Update configuration.md
  guides/v2.2/performance-best-practices/configuration.md
Labels: Editorial, Partner: Wagento, partners-contribution

#2056 Update bk-cloud.md
  guides/v2.0/cloud/bk-cloud.md
Labels: Editorial, Partner: Wagento, partners-contribution

#2075 Update errors-and-messages.md
  guides/v2.1/design-styleguide/errors-and-messages/errors-and-messages.md
Labels: Editorial

#2054 Update js-resources.md
  guides/v2.0/javascript-dev-guide/javascript/js-resources.md
Labels: 2.1.x, Editorial, Partner: Wagento, partners-contribution

#2080 Fixed typo error
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.assignProduct.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.assignedProducts.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.create.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.currentStore.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.delete.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.info.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.level.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.move.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.removeProduct.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.tree.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.update.html
  guides/m1x/api/soap/catalog/catalogCategory/catalog_category.updateProduct.html
Labels: Editorial

#2082 Updated Whats New on DevDocs
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2085 1253: Clarify production mode behavior
  guides/v2.1/config-guide/bootstrap/magento-modes.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2087 Updates for GraphQL PR-48
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/categories.md
Labels: 2.3.x, Community, Enhancement

#2086 Added Console as optional extension directory
  _includes/php-dev/component-root-2.3.md
  common/images/pdg-config-file-structure.png
  guides/v2.1/extension-dev-guide/build/module-file-structure.md
  guides/v2.3/extension-dev-guide/build/module-file-structure.md
  guides/v2.3/extension-dev-guide/build/required-configuration-files.md
  guides/v2.3/extension-dev-guide/images/pdg-config-file-structure.png
  guides/v2.3/extension-dev-guide/prepare/prepare_file-str.md
Labels: 2.2.x, 2.3.x, Enhancement, In progress

#2088 Update cluster storage stats in Pro architecture topic
  guides/v2.1/cloud/architecture/pro-architecture.md
Labels: Editorial, Technical

#2094 [fix] typos in payment-gateway/error-code-mapper.md
  guides/v2.2/payments-integrations/payment-gateway/error-code-mapper.md
  guides/v2.3/payments-integrations/payment-gateway/error-code-mapper.md
Labels: 2.2.x, 2.3.x, Editorial

#2091 Removed Community Edition Reference from 2.2
  guides/v2.2/extension-dev-guide/validate/test-module.md
  guides/v2.2/rest/list.md
Labels: Editorial

#2099 [fix] target in community resources
  community/resources/index.md
Labels: Editorial

#2096 Fix typo in cloud (spell Fastly correct)
  guides/v2.0/cloud/access-acct/fastly.md
  guides/v2.0/cloud/trouble/trouble_fastly.md
  guides/v2.1/cloud/access-acct/fastly.md
  guides/v2.1/cloud/trouble/trouble_fastly.md
Labels: Editorial

#2022 MAGEDOC-3015 Update 2.0 symlink paths in v2.2 and v2.3 directories
  guides/v2.2/cloud/access-acct/first-time-deploy.md
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/architecture/pro-architecture-legacy.md
  guides/v2.2/cloud/architecture/pro-architecture.md
  guides/v2.2/cloud/architecture/pro-develop-deploy-workflow.md
  guides/v2.2/cloud/basic-information/cloud-fastly.md
  guides/v2.2/cloud/basic-information/cloud-plans.md
  guides/v2.2/cloud/basic-information/starter-architecture.md
  guides/v2.2/cloud/before/before-setup-env-overview.md
  guides/v2.2/cloud/configure/cloud-vcl-custom-snippets.md
  guides/v2.2/cloud/configure/configure-best-practices.md
  guides/v2.2/cloud/configure/fastly-vcl-badreferer.md
  guides/v2.2/cloud/configure/fastly-vcl-blacklist.md
  guides/v2.2/cloud/configure/fastly-vcl-extend-timeout.md
  guides/v2.2/cloud/configure/fastly-vcl-whitelist.md
  guides/v2.2/cloud/configure/fastly-vcl-wordpress.md
  guides/v2.2/cloud/env/environments-ssh.md
  guides/v2.2/cloud/live/launch-steps.md
  guides/v2.2/cloud/onboarding/onboarding-portal.md
  guides/v2.2/cloud/onboarding/onboarding-tasks.md
  guides/v2.2/cloud/trouble/redis-troubleshooting.md
  guides/v2.2/cloud/trouble/robots-sitemap.md
  guides/v2.2/cloud/trouble/theme-troubleshooting.md
  guides/v2.2/cloud/trouble/trouble-crypt-key-variable.md
  guides/v2.2/cloud/trouble/trouble-google-analytics-deploy.md
  guides/v2.2/config-guide/cache/cache-options.md
  guides/v2.2/config-guide/cache/cache-types.md
  guides/v2.2/config-guide/log/log-intro.md
  guides/v2.2/config-guide/log/log-magento.md
  guides/v2.2/extension-dev-guide/cache/page-caching.md
  guides/v2.2/extension-dev-guide/cache/page-caching/private-content.md
  guides/v2.2/extension-dev-guide/cache/page-caching/public-content.md
  guides/v2.2/extension-dev-guide/cache/partial-caching.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/create-cache-type.md
  guides/v2.2/frontend-dev-guide/cache_for_frontdevs.md
  guides/v2.2/frontend-dev-guide/css-topics/custom-preprocess-parent.md
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
  guides/v2.2/frontend-dev-guide/themes/product-video.md
  guides/v2.2/frontend-dev-guide/themes/theme-install.md
  guides/v2.2/frontend-dev-guide/themes/theme-overview.md
  guides/v2.2/howdoi/checkout/checkout_custom_checkbox.md
  guides/v2.2/howdoi/clean_static_cache.md
  guides/v2.2/install-gde/tutorials/change-docroot-to-pub.md
  guides/v2.3/cloud/architecture/cloud-architecture.md
  guides/v2.3/cloud/architecture/pro-architecture-legacy.md
  guides/v2.3/cloud/architecture/pro-architecture.md
  guides/v2.3/cloud/architecture/pro-develop-deploy-workflow.md
  guides/v2.3/cloud/basic-information/cloud-plans.md
  guides/v2.3/cloud/configure/configure-best-practices.md
  guides/v2.3/cloud/configure/fastly-vcl-badreferer.md
  guides/v2.3/cloud/configure/fastly-vcl-blacklist.md
  guides/v2.3/cloud/configure/fastly-vcl-extend-timeout.md
  guides/v2.3/cloud/configure/fastly-vcl-whitelist.md
  guides/v2.3/cloud/configure/fastly-vcl-wordpress.md
  guides/v2.3/cloud/env/log-handlers.md
  guides/v2.3/cloud/env/variables-post-deploy.md
  guides/v2.3/cloud/trouble/theme-troubleshooting.md
  guides/v2.3/install-gde/tutorials/change-docroot-to-pub.md
Labels: 2.2.x, 2.3.x, Editorial

#2044 Fixed huge number of spelling typo mistakes.
  guides/v2.1/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.1/pattern-library/filters/data-table-filters/filtering.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2098 Update favicon.md
  guides/v2.1/frontend-dev-guide/themes/favicon.md
Labels: Editorial

#2097 Update theme-inherit.md
  guides/v2.1/frontend-dev-guide/themes/theme-inherit.md
Labels: Editorial

#2095 Update admin_theme_apply.md
  guides/v2.1/frontend-dev-guide/themes/admin_theme_apply.md
Labels: Editorial

#2093 Update cache_for_frontdevs.md
  guides/v2.1/frontend-dev-guide/cache_for_frontdevs.md
Labels: Editorial

#2105 Fixed bug in Liquid syntax
  guides/v2.1/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.1/pattern-library/filters/data-table-filters/filtering.md
Labels: 2.1.x, Editorial

#2118 Update order-config-store.md
  guides/v2.1/get-started/order-tutorial/order-config-store.md
Labels: Editorial

#2110 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2101 Update to Pro architecture upscaling description
  guides/v2.1/cloud/architecture/pro-architecture.md
Labels: 2.x, Editorial

#2122 Update webapi.md
  guides/v2.1/coding-standards/technical-vision/webapi.md
Labels: 2.x, Editorial

#2100 Fixed typo error in pattern library
  guides/v2.0/pattern-library/getting-user-input/date_time_selector/date_time_selector.md
  guides/v2.1/pattern-library/getting-user-input/date_time_selector/date_time_selector.md
Labels: 2.x, Editorial

#2012 Added missing closing div tag
  _includes/install/tls-repo.md
  _includes/layout/footer-scripts.html
  _includes/migration/find-version.md
  _includes/performance/development-environment.md
  _includes/php-dev/component-root.md
  _includes/php-dev/component-versioning.md
  _includes/vendor/types-def.md
  _includes/webapi/services21.md
  _includes/webapi/services22.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Waiting for response

#2125 remove outdated file
  guides/v2.2/config-guide/prod/prod_perf-optimize.md
Labels: 2.2.x, Editorial

#2106 Add community section for issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/COMMUNITY_ISSUE_TEMPLATE.md
Labels: Community, Enhancement

#2133 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2111 Fixed target blank issue
  guides/v2.0/extension-dev-guide/build/di-xml-file.md
  guides/v2.1/extension-dev-guide/build/di-xml-file.md
  guides/v2.2/extension-dev-guide/build/di-xml-file.md
Labels: 2.x, Editorial, Waiting for response

#2117 Added link on document
  guides/m1x/system-requirements.md
Labels: Editorial, Waiting for response

#2160 Fix table that isn't rendering properly
  guides/v2.1/get-started/order-tutorial/order-config-store.md
Labels: Editorial

#2161 Added link on text
  guides/v2.0/coding-standards/code-standard-sniffers.md
  guides/v2.1/coding-standards/code-standard-sniffers.md
  guides/v2.2/coding-standards/code-standard-sniffers.md
Labels: 2.x, Editorial

#2127 Fixed format issue in code
  guides/v2.1/coding-standards/code-standard-demarcation.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2164 MAGEDOC-3028: Added links to BI Import API and Order Mgmt
  _includes/layout/navigation.html
Labels: 2.x, Enhancement

#2166 Fix page url generator
  _plugins/page-baseurl-generator.rb
  index.html
Labels: 2.x, Enhancement

#2167 Fixed 2.0 banner
  guides/v2.0/index.html
Labels: 2.x, Editorial

#2168 Removed extra banner in 2.3 index
  _includes/layout/after-site-header.html
  guides/v2.3/index.html
Labels: 2.3.x, Editorial

#2163 Hg blackfire
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: Waiting for response

#2015 Adding troubleshooting guide and fixing CLI usage
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#2182 Fixed broken links containing baseurl variables
  guides/v2.2/performance-best-practices/hardware.md
  guides/v2.2/release-notes/ReleaseNotes2.2.0CE.md
  guides/v2.3/config-guide/deployment/pipeline/build-system.md
  guides/v2.3/ext-best-practices/tutorials/modify-image-library-permissions/index.md
  guides/v2.3/extension-dev-guide/variable-pool/index.md
  guides/v2.3/install-gde/install-quick-ref.md
  guides/v2.3/install-gde/install/get-software.md
  guides/v2.3/install-gde/install/hosted/hosted_get-ftp.md
  guides/v2.3/install-gde/prereq/apache.md
  guides/v2.3/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/mysql_remote.md
  guides/v2.3/install-gde/prereq/nginx.md
  guides/v2.3/install-gde/prereq/optional.md
  guides/v2.3/install-gde/prereq/security.md
  guides/v2.3/install-gde/prereq/zip_install.md
  guides/v2.3/mtf/mtf_installation.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/ui_comp_guide/components/image-uploader/index.md
  guides/v2.3/ui_comp_guide/components/wysiwyg/extension-points/index.md
Labels: 2.x, Editorial

#2177 Update generate-local.md
  guides/v2.2/rest/generate-local.md
Labels: Editorial

#2146 Removed double 'and' from sentence.
  guides/m1x/magefordev/mage-for-dev-7.html
  guides/v2.0/cloud/before/before-workspace.md
  guides/v2.0/cloud/configure/configure-best-practices.md
  guides/v2.0/coding-standards/technical-vision/webapi.md
  guides/v2.0/get-started/authentication/gs-authentication-oauth.md
  guides/v2.0/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.1/cloud/before/before-workspace.md
  guides/v2.1/cloud/configure/configure-best-practices.md
  guides/v2.1/coding-standards/technical-vision/webapi.md
  guides/v2.1/get-started/authentication/gs-authentication-oauth.md
  guides/v2.1/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.2/rest/tutorials/configurable-product/plan-product.md
  guides/v2.2/test/js/jasmine.md
Labels: Editorial

#2140 Removed double 'in' from sentence.
  guides/v2.2/test/js/jasmine.md
Labels: Waiting for response

#2187 URL fix in issue template
  .github/ISSUE_TEMPLATE/COMMUNITY_ISSUE_TEMPLATE.md
Labels: Editorial

#2191 Removed glossary tips from markdown tables
  guides/v2.0/rest/anonymous-api-security.md
  guides/v2.1/rest/anonymous-api-security.md
  guides/v2.2/rest/anonymous-api-security.md
Labels: 2.x, Editorial

#2176 Update generate-local.md
  guides/v2.1/rest/generate-local.md
Labels: Editorial

#2124 MAGECLOUD-2233 Docker configuration topic
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/reference/docker-config.md
  guides/v2.2/cloud/reference/docker-config.md
  guides/v2.3/cloud/reference/docker-config.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#2193 Removed glossarytips from markdown tables
  guides/v2.0/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.0/extension-dev-guide/versioning/dependencies.md
  guides/v2.0/get-started/gs-web-api-response.md
  guides/v2.0/howdoi/howdoi_contribute.md
  guides/v2.0/mtf/mtf_entities/mtf_handler.md
  guides/v2.1/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.1/extension-dev-guide/versioning/dependencies.md
  guides/v2.1/get-started/gs-web-api-response.md
  guides/v2.1/mtf/mtf_entities/mtf_handler.md
  guides/v2.1/payments-integrations/base-integration/payment-option-config.md
  guides/v2.2/extension-dev-guide/message-queues/bulk-operations.md
  guides/v2.3/extension-dev-guide/message-queues/bulk-operations.md
  guides/v2.3/extension-dev-guide/versioning/dependencies.md
Labels: 2.x, Editorial

#2203 Update order-admin-token.md
  guides/v2.1/get-started/order-tutorial/order-admin-token.md
Labels: Editorial

#2192 Replaced 'user name(s)' with 'username(s)'
  _includes/cloud/log-in-db.md
  _includes/config/split-db.md
  _includes/install/sens-data.md
  guides/m1x/ce18-ee113/ce1.8_release-notes.html
  guides/m1x/ce18-ee113/ee1.13_release-notes.html
  guides/v2.0/cloud/before/before-setup-env-2_clone.md
  guides/v2.0/cloud/env/environment-vars_magento.md
  guides/v2.0/cloud/howtos/debug.md
  guides/v2.0/config-guide/multi-master/multi-master_manual.md
  guides/v2.0/install-gde/install-quick-ref.md
  guides/v2.0/install-gde/install/cli/install-cli-install.md
  guides/v2.0/install-gde/install/cli/install-cli-subcommands-deployment.md
  guides/v2.1/cloud/before/before-setup-env-2_clone.md
  guides/v2.1/cloud/env/environment-vars_magento.md
  guides/v2.1/cloud/howtos/debug.md
  guides/v2.1/config-guide/multi-master/multi-master_manual.md
  guides/v2.1/install-gde/install-quick-ref.md
  guides/v2.1/install-gde/install/cli/install-cli-install.md
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-deployment.md
  guides/v2.1/release-notes/ReleaseNotes2.1.8CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.8EE.md
  guides/v2.2/cloud/env/environment-vars_magento.md
  guides/v2.2/extension-dev-guide/configuration/sensitive-and-environment-settings.md
  guides/v2.2/install-gde/install-quick-ref.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-deployment.md
  guides/v2.3/install-gde/install-quick-ref.md
Labels: 2.x, Editorial

#2150 Removed double 'this' from sentence.
  guides/m1x/magefordev/mage-for-dev-6.html
  guides/m1x/magefordev/mage-for-dev-7.html
  guides/v2.0/cloud/configure/setup-cron-jobs.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.0/extension-dev-guide/build/create_component.md
  guides/v2.0/howdoi/checkout/checkout_carrier.md
  guides/v2.0/install-gde/prereq/mysql.md
  guides/v2.0/migration/migration-plan.md
  guides/v2.0/test/integration/integration_test_execution.md
  guides/v2.0/test/unit/writing_testable_code.md
  guides/v2.1/cloud/configure/setup-cron-jobs.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.1/config-guide/multi-site/ms_nginx.md
  guides/v2.1/config-guide/prod/config-reference-var-name.md
  guides/v2.1/extension-dev-guide/build/create_component.md
  guides/v2.1/howdoi/checkout/checkout_carrier.md
  guides/v2.1/install-gde/prereq/mysql.md
  guides/v2.1/marketplace/eqp/files.md
  guides/v2.1/migration/migration-plan.md
  guides/v2.1/payments-integrations/base-integration/formblocktype.md
  guides/v2.1/release-notes/ReleaseNotes2.1.2CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.2EE.md
  guides/v2.1/test/integration/integration_test_execution.md
  guides/v2.1/test/unit/writing_testable_code.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.2/config-guide/deployment/pipeline/production-system.md
  guides/v2.2/config-guide/prod/config-reference-var-name.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.2/magento-functional-testing-framework/release-2/img/data-dia.svg
  guides/v2.2/magento-functional-testing-framework/release-2/suite.md
  guides/v2.2/performance-best-practices/deployment-flow.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
  guides/v2.2/rest/tutorials/configurable-product/plan-product.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/install-gde/prereq/mysql.md
  guides/v2.3/magento-functional-testing-framework/release-2/img/data-dia.svg
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.x, Cleanup

#2152 Fixed link html target value in .md files.
  guides/v2.0/config-guide/prod/prod.md
  guides/v2.0/pattern-library/general/accessibilityguideline/accessibilityGuideline.md
  guides/v2.1/config-guide/elasticsearch/es-overview.md
  guides/v2.1/config-guide/prod/prod.md
  guides/v2.1/pattern-library/general/accessibilityguideline/accessibilityGuideline.md
  guides/v2.2/config-guide/elasticsearch/es-overview.md
Labels: 2.0.x, 2.1.x, 2.2.x, Cleanup

#2210 Updated Whats New On Devdocs
  guides/v2.1/magento-devdocs-whatsnew.md
Labels: 2.x, Editorial

#2211 Lk magedoc2990 how to conversion
  _data/toc/how-do-i.yml
  _includes/layout/navigation.html
  community/resources/support.md
  guides/v2.0/howdoi/checkout/checkout_address.md
  guides/v2.0/howdoi/checkout/checkout_carrier.md
  guides/v2.0/howdoi/checkout/checkout_custom_checkbox.md
  guides/v2.0/howdoi/checkout/checkout_customize.md
  guides/v2.0/howdoi/checkout/checkout_edit_form.md
  guides/v2.0/howdoi/checkout/checkout_form.md
  guides/v2.0/howdoi/checkout/checkout_new_field.md
  guides/v2.0/howdoi/checkout/checkout_new_step.md
  guides/v2.0/howdoi/checkout/checkout_order.md
  guides/v2.0/howdoi/checkout/checkout_overview.md
  guides/v2.0/howdoi/checkout/checkout_payment.md
  guides/v2.0/howdoi/checkout/checkout_zip.md
  guides/v2.1/howdoi/checkout/checkout_address.md
  guides/v2.1/howdoi/checkout/checkout_carrier.md
  guides/v2.1/howdoi/checkout/checkout_custom_checkbox.md
  guides/v2.1/howdoi/checkout/checkout_customize.md
  guides/v2.1/howdoi/checkout/checkout_edit_form.md
  guides/v2.1/howdoi/checkout/checkout_form.md
  guides/v2.1/howdoi/checkout/checkout_new_field.md
  guides/v2.1/howdoi/checkout/checkout_new_step.md
  guides/v2.1/howdoi/checkout/checkout_order.md
  guides/v2.1/howdoi/checkout/checkout_overview.md
  guides/v2.1/howdoi/checkout/checkout_payment.md
  guides/v2.1/howdoi/checkout/checkout_zip.md
  guides/v2.1/howdoi/customize-form-configuration.md
  guides/v2.1/howdoi/customize-modifier-class.md
  guides/v2.1/howdoi/customize_product.md
  guides/v2.2/howdoi/checkout/checkout_shipping_methods.md
  guides/v2.2/howdoi/customize-form-configuration.md
  guides/v2.2/howdoi/customize-modifier-class.md
  guides/v2.2/howdoi/customize_product.md
  guides/v2.3/howdoi/customize-form-configuration.md
  guides/v2.3/howdoi/customize-modifier-class.md
Labels: Editorial

#2212 Replaced 'check box' with `checkbox` throughout the site
  _includes/comp-man/backup.md
  guides/m1x/ce18-ee113/ee1.13_release-notes.html
  guides/m1x/other/ht_extend_magento_rest_api.html
  guides/v2.0/cloud/project/project-integrate-github.md
  guides/v2.0/install-gde/install/hosted/hosted_start_php.md
  guides/v2.0/release-notes/backward-incompatible-changes/index.md
  guides/v2.1/cloud/project/project-integrate-github.md
  guides/v2.1/install-gde/install/hosted/hosted_start_php.md
  guides/v2.1/mtf/mtf_quickstart/mtf_quickstart_magento.md
  guides/v2.1/release-notes/ReleaseNotes2.1.0CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.0EE.md
  guides/v2.1/ui_comp_guide/components/ui-multiselectcolumn.md
  guides/v2.1/ui_comp_guide/components/ui-onoffcolumn.md
  guides/v2.2/mtf/mtf_quickstart/mtf_quickstart_magento.md
  guides/v2.2/ui_comp_guide/components/ui-multiselectcolumn.md
  guides/v2.2/ui_comp_guide/components/ui-onoffcolumn.md
Labels: 2.x, Editorial

#2173 Update xml-instructions.md
  guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup

#2178 Update css_quick_guide_mode.md
  guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup

#2213 Fixed grammatical (article) issue.
  guides/m1x/magefordev/mage-for-dev-5.html
  guides/v2.1/get-started/order-tutorial/order-create-quote.md
Labels: 1.x, 2.1.x, Cleanup

#2234 fixed typo in MAGEDOC-3032
  guides/v2.1/install-gde/install-resources-parent.md
Labels: Editorial

#2218 Update onboarding-tasks.md
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
  guides/v2.2/cloud/project/project-upgrade.md
Labels: 2.1.x, 2.2.x, Cleanup

#2235 Update new-relic.md
  guides/v2.1/cloud/project/new-relic.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup

#2239 Updated the Magento UI Library to fix #526
  common/images/ui_lib1.png
  common/images/ui_lib2.png
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2241 GH #2236 Fix PHP include tables
  _includes/install/php_2.0.md
  _includes/install/php_2.1.md
  _includes/install/php_2.2.md
  _includes/install/php_2.3.md
Labels: 2.x, Cleanup

#2243 PHP-table-fix: Fix order of PHP versions in table
  _includes/install/php_2.1.md
Labels: 2.1.x, Cleanup

#2244 update navigation file
  _includes/layout/navigation.html
  guides/v2.2/rest/tutorials/configurable-product/config-product-intro.md
Labels: 2.2.x, 2.3.x, Editorial

#2242 MAGECLOUD-2150 editing locales
  guides/v2.1/cloud/live/sens-data-over.md
  guides/v2.2/cloud/live/sens-data-over.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2232 Update css_debug.md
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup

#2089 MAGECLOUD-2214 Update Robots and sitemap
  guides/v2.1/cloud/trouble/robots-sitemap.md
  guides/v2.2/cloud/trouble/robots-sitemap.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#2246 Removed unnecessary space and added article.
  guides/v2.2/advanced-reporting/data-collection.md
Labels: 2.2.x, 2.3.x, Cleanup

#2233 Update checkout_new_step.md
  guides/v2.1/howdoi/checkout/checkout_new_step.md
Labels: Technical

#2257 Added information about @api tag tracking to the Backward incompatibl…
  guides/v2.0/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.0/release-notes/backward-incompatible-changes/open-source.md
  guides/v2.1/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.1/release-notes/backward-incompatible-changes/open-source.md
  guides/v2.2/release-notes/backward-incompatible-changes/b2b.md
  guides/v2.2/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.2/release-notes/backward-incompatible-changes/open-source.md
  guides/v2.3/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.3/release-notes/backward-incompatible-changes/open-source.md
Labels: 2.x, Editorial

#2258 bug fix for redirect
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Editorial

#2260 Convert the CSS quick guide overview to markdown
  guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_overview.md
Labels: 2.1.x, Editorial

#2261 Converted HTML to Markdown in 'guides/v2.1/comp-mgr/bk-compman-upgrade-guide.html'
  guides/v2.1/comp-mgr/bk-compman-upgrade-guide.md
Labels: 2.1.x, Editorial

#2256 GH 2240: Revise contributor guide
  guides/v2.0/contributor-guide/contributing_docs.md
  guides/v2.0/contributor-guide/contributing_docs_suggested.md
  guides/v2.0/contributor-guide/templates/basic_template.md
  guides/v2.1/contributor-guide/contributing_docs.md
  guides/v2.1/contributor-guide/contributing_docs_suggested.md
  guides/v2.1/contributor-guide/templates/basic_template.md
Labels: 2.x, Technical

#2262 Fix navigation on configurable tutorial
  guides/v2.2/rest/tutorials/configurable-product/config-product-intro.md
Labels: Editorial

#2273 Update checkout_payment.md
  guides/v2.1/howdoi/checkout/checkout_payment.md
Labels: 2.1.x, Editorial

#2255 Fixed links to MIN_LOGGING_LEVEL variable in Cloud 2002.0.12 release …
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, Editorial

#2221 Fixed typo errors
  _data/toc/ui-library.yml
  guides/v2.0/frontend-dev-guide/translations/translate_theory.md
  guides/v2.0/javascript-dev-guide/javascript/js_init.md
  guides/v2.0/ui-components/ui_components_js.md
  guides/v2.1/frontend-dev-guide/translations/translate_theory.md
  guides/v2.1/javascript-dev-guide/javascript/js_init.md
  guides/v2.1/ui_comp_guide/bk-ui_comps.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_uielement_concept.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.2/ui_comp_guide/bk-ui_comps.md
  guides/v2.2/ui_comp_guide/components/basic-attributes.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_xmlconfig_structure.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup, Waiting for response

#2251 Fixed format issue in cloud document
  guides/v2.2/config-guide/varnish/config-varnish-advanced.md
  guides/v2.2/config-guide/varnish/tshoot-varnish-503.md
Labels: 2.2.x, 2.3.x, Cleanup

#2275 Fix issue #2274 - html escape
  guides/v2.1/frontend-dev-guide/css-topics/using-fonts.md
Labels: Editorial, Technical

#2281 2280: Fixed swagger
  swagger/index_23.html
Labels: 2.3.x, Technical

#2283 Fix paths for ui-components ui-forms
  guides/v2.1/ui_comp_guide/components/ui-form.md
  guides/v2.2/ui_comp_guide/components/ui-form.md
Labels: Technical

#2284 2282: Remove collapsible elements ad fix formatting
  guides/v2.1/frontend-dev-guide/layouts/layout-practice.md
Labels: Editorial

#2278 Fixed typo; added link to robots.txt and sitemap workflow.
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.x, Editorial

#2186 Typo fixes and edits for Cloud docs
  guides/v2.0/cloud/architecture/pro-develop-deploy-workflow.md
  guides/v2.0/cloud/live/live-sanity-check.md
  guides/v2.0/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/architecture/pro-develop-deploy-workflow.md
  guides/v2.1/cloud/live/live-sanity-check.md
  guides/v2.1/cloud/project/admin-git-push.md
  guides/v2.1/cloud/project/bitbucket-integration.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/project/project-multi-sites.md
  guides/v2.1/cloud/project/project-patch.md
  guides/v2.1/cloud/project/project-routes-more-redir.md
  guides/v2.1/cloud/project/project-start.md
  guides/v2.1/cloud/project/project-upgrade.md
  guides/v2.1/config-guide/elasticsearch/es-overview.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-patch.md
  guides/v2.2/cloud/project/project-start.md
  guides/v2.2/cloud/project/project-upgrade.md
  guides/v2.2/config-guide/elasticsearch/es-overview.md
  guides/v2.3/config-guide/elasticsearch/es-overview.md
Labels: 2.1.x, 2.2.x, Editorial

#2285 Removing duplicated sentence from JavaScript developer guide
  guides/v2.1/javascript-dev-guide/javascript/custom_js.md
Labels: Editorial

#2291 Fixed a bunch of broken links
  _data/toc/ui-components-guide.yml
  _includes/install/install-roadmap.md
  guides/v2.0/contributor-guide/contributing_docs.md
  guides/v2.0/howdoi/checkout/checkout_payment.md
  guides/v2.1/contributor-guide/contributing_docs.md
  guides/v2.1/howdoi/checkout/checkout_custom_checkbox.md
  guides/v2.1/howdoi/checkout/checkout_customize.md
  guides/v2.1/howdoi/customize-form-configuration.md
  guides/v2.1/marketplace/eqp/files.md
  guides/v2.1/marketplace/eqp/packages.md
  guides/v2.2/magento-functional-testing-framework/release-2/data.md
  guides/v2.3/config-guide/cli/logging.md
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/release-notes/thirdparty-mccloud.md
  guides/v2.3/release-notes/thirdparty_ce.md
  guides/v2.3/release-notes/thirdparty_ee.md
Labels: Editorial, Technical

#2238 Revise routing topic
  guides/v2.1/extension-dev-guide/routing.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Technical

#2286 Update ui_comp_config_flow_concept.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_config_flow_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_config_flow_concept.md
Labels: Editorial

#2293 Update php-developer-guide.yml
  _data/toc/php-developer-guide.yml
Labels: Editorial

#2254 Fixed the 'hostname' term
  _includes/config/split-deploy/config-mgmt-over1.md
  guides/v2.0/cloud/access-acct/fastly.md
  guides/v2.0/cloud/live/go-live-checklist.md
  guides/v2.1/cloud/access-acct/fastly.md
  guides/v2.1/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.2/config-guide/deployment/pipeline/technical-details.md
  guides/v2.2/extension-dev-guide/configuration/sensitive-and-environment-settings.md
  guides/v2.3/cloud/live/go-live-checklist.md
Labels: 2.x, Editorial

#2219 Generated backward incompatible changes (2.2.0 - 2.3-develop)
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
Labels: 2.3.x, Technical

#2052 MQE-987: Decouple MFTF from Magento
  _data/toc/magento-functional-testing-framework-guide.yml
  guides/v2.2/magento-functional-testing-framework/release-2/commands/codeception.md
  guides/v2.2/magento-functional-testing-framework/release-2/commands/mftf.md
  guides/v2.2/magento-functional-testing-framework/release-2/commands/robo.md
  guides/v2.3/magento-functional-testing-framework/release-2/commands/mftf.md
  guides/v2.3/magento-functional-testing-framework/release-2/commands/robo.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#2304 Update cache_for_frontdevs.md
  guides/v2.1/frontend-dev-guide/cache_for_frontdevs.md
Labels: 2.1.x, Editorial

#2269 Update contributing_docs.md
  guides/v2.1/contributor-guide/contributing_docs.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2270 Update integration_test_execution.md
  guides/v2.1/test/integration/integration_test_execution.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2253 MQE-1064: Relax file and test name requirements
  guides/v2.2/magento-functional-testing-framework/release-2/page.md
  guides/v2.2/magento-functional-testing-framework/release-2/section.md
  guides/v2.2/magento-functional-testing-framework/release-2/test.md
  guides/v2.2/magento-functional-testing-framework/release-2/test/action-groups.md
Labels: 2.2.x, 2.3.x, Technical

#2306 Update navigation for configurable product tutorial
  guides/v2.2/rest/tutorials/configurable-product/config-product-intro.md
  guides/v2.2/rest/tutorials/configurable-product/create-configurable-product.md
  guides/v2.2/rest/tutorials/configurable-product/create-personalization-option.md
  guides/v2.2/rest/tutorials/configurable-product/create-simple-products.md
  guides/v2.2/rest/tutorials/configurable-product/define-config-product-options.md
  guides/v2.2/rest/tutorials/configurable-product/plan-product.md
Labels: 2.2.x, 2.3.x, Editorial

#2123 MAGEDOC-2850: Extension Repo Structure
  _data/toc/php-developer-guide.yml
  guides/v2.3/extension-dev-guide/prepare/ext-repo-structure.md
Labels: 2.3.x, New doc, Tracking

#1491 Update xml-manage.md for meta-tag rendering
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.x, Editorial, Enhancement, Technical, Waiting for response

#2308 Delete obsolete attribute from GraphQL products endpoint
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.x, Technical

#2309 Bd magedoc 2850 ext repo
  guides/v2.3/extension-dev-guide/prepare/ext-repo-structure.md
Labels: 2.3.x, Cleanup

#2310 MAGECLOUD-2289 blackfire route confusion
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: Editorial

#2311 Update theme-best-practice.md
  guides/v2.1/frontend-dev-guide/theme-best-practice.md
Labels: Cleanup

#2268 Update starter-develop-deploy-workflow.md
  guides/v2.0/cloud/basic-information/starter-develop-deploy-workflow.md
  guides/v2.1/cloud/basic-information/starter-develop-deploy-workflow.md
  guides/v2.2/cloud/basic-information/starter-develop-deploy-workflow.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup

#2316 Fixed naming convention issue
  guides/v2.1/config-guide/prod/config-reference-payment.md
  guides/v2.2/config-guide/prod/config-reference-payment.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup

#2314 Update checkout_form.md
  guides/v2.1/howdoi/checkout/checkout_form.md
Labels: 2.1.x, 2.2.x, 2.3.x, Cleanup

#2318 Web server meaning clarified
  guides/v2.1/install-gde/basics/basics_software.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2294 Update RPO time interval for Pro architecture
  guides/v2.1/cloud/architecture/pro-architecture.md
Labels: 2.x, Technical

#2319 Added comment showing syntax for variables
  _data/var.yml
Labels: Enhancement

#2320 GH2290 - Update TOC for 2.3 best practices
  _data/toc/performance-best-practices.yml
Labels: 2.3.x, Editorial

#2325 Fixed typo error on security settings
  guides/v2.0/config-guide/secy/secy-cron.md
  guides/v2.1/config-guide/secy/secy-cron.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2324 Update response-validator.md
  guides/v2.1/payments-integrations/payment-gateway/response-validator.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2266 Update first-time-setup.md
  guides/v2.1/cloud/access-acct/first-time-setup.md
  guides/v2.1/cloud/project/project-webint-branch.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2300 Update bk-compman-upgrade-guide.md
  guides/v2.1/comp-mgr/bk-compman-upgrade-guide.md
  guides/v2.2/comp-mgr/bk-compman-upgrade-guide.md
Labels: 2.x, Editorial

#2323 Update gs-authentication.md
  guides/v2.1/get-started/authentication/gs-authentication.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2331 Update order-config-store.md
  guides/v2.1/get-started/order-tutorial/order-admin-token.md
  guides/v2.1/get-started/order-tutorial/order-config-store.md
  guides/v2.1/get-started/order-tutorial/order-create-customer.md
  guides/v2.1/get-started/order-tutorial/order-create-invoice.md
  guides/v2.1/get-started/order-tutorial/order-create-order.md
  guides/v2.1/get-started/order-tutorial/order-create-shipment.md
  guides/v2.1/get-started/order-tutorial/order-issue-refund.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2334 [FIX] Fix incorrect indexer interface in example
  guides/v2.1/extension-dev-guide/indexing-custom.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2335 Wrong file & don't need cat + pipe
  _videos/fundamentals/create-a-new-module.md
Labels: 2.x, Technical

#2298 Update upgrade-start.md
  guides/v2.1/comp-mgr/upgrader/upgrade-start.md
  guides/v2.2/comp-mgr/upgrader/upgrade-start.md
Labels: 2.x, Editorial

#2351 2248: Clarify which config file we are referring to
  guides/v2.1/migration/migration-migrate-settings.md
Labels: Technical

#2333 Update config-cli-subcommands-static-view.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
Labels: Editorial

#2345 [task] add redis section to document, see: #2337
  guides/v2.1/install-gde/trouble/tshoot_wrong-mysql.md
Labels: Major update

#2356 Add a bullet for nginx troubleshooting
  guides/v2.1/install-gde/trouble/tshoot_no-styles.md
Labels: Technical, internal-dev

#2347 Added link for schema.graphqls
  guides/v2.3/graphql/index.md
Labels: 2.3.x, Editorial

#2366 Update design-patterns.md
  guides/v2.1/extension-dev-guide/service-contracts/design-patterns.md
Labels: Editorial

#2340 Update config-cli-subcommands-static-view.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
Labels: 2.2.x, 2.3.x, Editorial

#1959 lk_80789_reindex-how-to
  guides/v2.2/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
Labels: 2.2.x, Major update

#2374 Correct SSH links for stg/pro
  guides/v2.1/cloud/env/environments-ssh.md
Labels: Technical

#2321 Update advanced-js-bundling.md
  guides/v2.1/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2342 Extra Information related to stores and website.
  guides/v2.1/config-guide/multi-site/ms_over.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#2380 GH #2375 Remove usage of gist for code samples
  guides/m1x/ce19-ee114/RWD_dev-guide.html
  guides/m1x/ce19-ee114/RWD_responsive_emails.html
  guides/m1x/other/ht_extend_magento_rest_api.html
  guides/v2.2/extension-dev-guide/plugins.md
Labels: 1.x

#2339 Update config-cli-subcommands-cache.md
  guides/v2.0/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.x, Editorial

#2385 Generated backward incompatible changes for Magento 2.1
  _includes/backward-incompatible-changes/commerce/2.1.13-2.1.14.html
  _includes/backward-incompatible-changes/open-source/2.1.12-2.1.13.html
  _includes/backward-incompatible-changes/open-source/2.1.13-2.1.14.html
  guides/v2.1/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.1/release-notes/backward-incompatible-changes/open-source.md
Labels: 2.1.x, Major update

#2386 Generated backward incompatible changes for Magento 2.2
  _includes/backward-incompatible-changes/commerce/2.2.4-2.2.5.html
  _includes/backward-incompatible-changes/open-source/2.2.4-2.2.5.html
  guides/v2.2/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.2/release-notes/backward-incompatible-changes/open-source.md
Labels: 2.2.x, Major update
