Repository magento/devdocs, pull requests merged in 2018-11, with the labels that each got.

#3218 Configuration Guide: fix broken links
  _data/toc/configuration-guide.yml
  _includes/config/solr-elastic-selinux.md
  guides/v2.0/config-guide/solr/solr-overview.md
  guides/v2.0/install-gde/install/post-install-config.md
  guides/v2.1/config-guide/bootstrap/magento-modes.md
  guides/v2.1/config-guide/cli/config-cli-subcommands.md
  guides/v2.1/config-guide/elasticsearch/es-config-stopwords.md
  guides/v2.1/config-guide/elasticsearch/es-overview.md
  guides/v2.1/config-guide/memcache/memcache.md
  guides/v2.1/config-guide/prod/prod_deploy.md
  guides/v2.1/config-guide/prod/single-machine-deployment.md
  guides/v2.1/config-guide/solr/solr-overview.md
  guides/v2.1/install-gde/install/post-install-config.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
  guides/v2.2/config-guide/deployment/pipeline/index.md
  guides/v2.2/config-guide/deployment/single-machine.md
  guides/v2.2/config-guide/elasticsearch/es-overview.md
  guides/v2.2/install-gde/install/hosted/post-install-config.md
  guides/v2.2/install-gde/install/post-install-config.md
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
  guides/v2.3/config-guide/elasticsearch/es-overview.md
  guides/v2.3/install-gde/install/post-install-config.md
Labels: Editorial, internal-dev

#3224 Add a label to the Cloud guide
  _data/toc/cloud-guide.yml
Labels: Editorial, internal-dev

#3223 Fixing the broken "Example 2" collspsible element
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3211 MAGEDOC-3227: Fix broken links in Cloud Guide
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.3/security/google-recaptcha.md
  guides/v2.3/security/two-factor-authentication.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, internal-dev

#3225 Bd js bundling fix
  guides/v2.2/frontend-dev-guide/themes/js-bundling.md
Labels: 2.2.x, Editorial

#3226 MAGEDOC-3228: Fix broken links in the Installation Guide
  _includes/install/install-roadmap.md
  _includes/install/ulimit.md
  guides/v2.0/frontend-dev-guide/themes/theme-create.md
  guides/v2.0/install-gde/install/cli/install-cli-uninstall.md
  guides/v2.0/install-gde/prereq/apache.md
  guides/v2.1/config-guide/prod/prod_deploy.md
  guides/v2.1/frontend-dev-guide/themes/theme-create.md
  guides/v2.1/install-gde/install-roadmap_part1.md
  guides/v2.1/install-gde/install-roadmap_trouble.md
  guides/v2.1/install-gde/install/cli/install-cli-install.md
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-deployment.md
  guides/v2.1/install-gde/install/cli/install-cli-uninstall.md
  guides/v2.1/install-gde/install/hosted/hosted_start.md
  guides/v2.1/install-gde/prereq/apache.md
  guides/v2.1/install-gde/prereq/optional.md
  guides/v2.1/install-gde/prereq/prereq_updater.md
  guides/v2.1/install-gde/system-requirements-tech.md
  guides/v2.1/install-gde/trouble/php/tshoot_mod_access_compat.md
  guides/v2.1/install-gde/trouble/php/tshoot_pdo.md
  guides/v2.1/install-gde/trouble/php/tshoot_xdebug.md
  guides/v2.1/install-gde/trouble/tshoot_sample-data.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/install-gde/install-roadmap_cli.md
  guides/v2.2/install-gde/install-roadmap_part1.md
  guides/v2.2/install-gde/install-roadmap_trouble.md
  guides/v2.2/install-gde/install-roadmap_web.md
  guides/v2.2/install-gde/install/cli/dev_downgrade.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
  guides/v2.2/install-gde/install/hosted/post-install-config.md
  guides/v2.2/install-gde/install/post-install-config.md
  guides/v2.3/architecture/tech-stack.md
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/install-gde/install-quick-ref.md
  guides/v2.3/install-gde/prereq/apache.md
  guides/v2.3/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/php-centos-ubuntu.md
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.x, Editorial

#3229 Fixed content issue
  _includes/install/first-steps-cli.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3210 Add a topic describing reporting in the MFTF
  _data/toc/magento-functional-testing-framework-guide-2_3.yml
  mftf/2.3/commands/mftf.md
  mftf/2.3/introduction.md
  mftf/2.3/reporting.md
  mftf/2.3/suite.md
Labels: 2.3.x, New doc, internal-dev

#3228 Update link validation script
  Gemfile
  rakelib/proofer.rb
  rakelib/test.rake
Labels: Site improvements

#3219 Implement the page-baseurl plugin using Jekyll hook
  _plugins/page-baseurl-generator.rb
Labels: Site improvements, internal-dev

#3227 Add notes for resolved Cloud bugs
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Technical, internal-dev

#3232 Clean up devdocs output
  CNAME
  _config.yml
Labels: Site improvements

#3234 Add new resources and edit link
  community/resources/resources.md
Labels: Community, Editorial

#3231 DOCS-3023: Corrected info in PR 3023
  guides/v2.1/migration/migration-migrate-delta.md
  guides/v2.1/migration/migration-tool-internal-spec.md
  guides/v2.2/migration/migration-tool-internal-spec.md
  guides/v2.2/migration/migration-troubleshooting.md
Labels: 2.2.x, 2.3.x, Editorial, Technical, internal-dev

#3237 Update Whats New on Devdocs, move it to the root, enhance links proofer
  guides/v2.0/index.html
  guides/v2.0/magento-devdocs-whatsnew.md
  guides/v2.1/index.html
  guides/v2.2/magento-devdocs-whatsnew.md
  guides/v2.3/index.html
  guides/v2.3/magento-devdocs-whatsnew.md
  index.html
  rakelib/proofer.rb
  whats-new.md
Labels: 2.x, Editorial, Site improvements

#3221 Product add attribute reference
  guides/v2.1/extension-dev-guide/attributes.md
Labels: 2.x, Major update, Technical

#3110 [fix] broken links
  _data/toc/module-reference-guide.yml
  guides/v2.1/pattern-library/bk-pattern.md
  guides/v2.3/mrg/ce/Analytics.md
  guides/v2.3/mrg/ce/CatalogAnalytics.md
  guides/v2.3/mrg/ce/CustomerAnalytics.md
  guides/v2.3/mrg/ce/QuoteAnalytics.md
  guides/v2.3/mrg/ce/ReviewAnalytics.md
  guides/v2.3/mrg/ce/SalesAnalytics.md
  guides/v2.3/mrg/ce/WishlistAnalytics.md
Labels: 2.x, Editorial, Waiting for response

#3236 MD3230 - Reindexer links and comments updated for 2.3.1
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.3/performance-best-practices/configuration.md
  rakelib/proofer.rb
Labels: 2.3.x, Editorial

#3143 Update index.md
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, Waiting for response

#3235 Fixed ticket number on release issue
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, Editorial, internal-dev

#3243 Link checker updates
  rakelib/proofer.rb
Labels: 2.x, Site improvements

#3253 MAGECLOUD-2564: Docker environment improvements
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-deploy.md
Labels: In progress, internal-dev

#3264 Fix links: GraphQL guide
  guides/v2.3/graphql/develop/create-custom-url-resolver.md
  rakelib/proofer.rb
Labels: 2.x, Editorial

#3266 Fix links: Component Manager Guide
  guides/v2.2/comp-mgr/upgrader/upgrade-start.md
  rakelib/proofer.rb
Labels: 2.x, Editorial

#3262 Remove obsolete and overly restrictive rule
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: Technical

#3267 Fix links: Architecture Guide
  guides/v2.1/contributor-guide/contributing_dod.md
  guides/v2.1/extension-dev-guide/versioning/index.md
  rakelib/proofer.rb
Labels: 2.3.x, Editorial

#3268 Fix links: JavaScript Developer Guide
  guides/v2.1/javascript-dev-guide/javascript/js_practice.md
  rakelib/proofer.rb
Labels: 2.x, Editorial

#3271 Hg mc2663 dockece
  _data/main-nav.yml
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/docker/docker-quick-reference.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/docker/docker-quick-reference.md
Labels: internal-dev

#3269 Add note about starting the message queue consumer for bulk/async calls
  guides/v2.3/rest/asynchronous-web-endpoints.md
  guides/v2.3/rest/bulk-endpoints.md
Labels: 2.3.x, Technical

#3274 Improve grammar
  guides/v2.1/frontend-dev-guide/themes/theme-structure.md
Labels: 2.1.x, 2.2.x, Editorial

#3275 Create topic for queue subcommands
  _data/toc/configuration-guide.yml
  _includes/config/message-queue-consumers.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-queue.md
  guides/v2.3/config-guide/mq/manage-mysql.md
Labels: 2.3.x, New doc, internal-dev

#3241 Scrub for Magento Commerce Cloud variable
  _includes/cloud/new-project-from-template.md
  _includes/cloud/patch.md
  guides/v2.1/cloud/basic-information/starter-architecture.md
  guides/v2.1/cloud/before/before-setup-env-2_clone.md
  guides/v2.1/cloud/before/before-setup-env-install.md
  guides/v2.1/cloud/before/before-workspace.md
  guides/v2.1/cloud/composer-packages/patch-notes.md
  guides/v2.1/cloud/configure/setup-cron-jobs.md
  guides/v2.1/cloud/live/live-prot.md
  guides/v2.1/cloud/live/live-sanity-check.md
  guides/v2.1/cloud/live/live.md
  guides/v2.1/cloud/live/paypal-onboarding.md
  guides/v2.1/cloud/onboarding/onboarding-portal.md
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
  guides/v2.1/cloud/project/new-relic.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/project/projects.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.1/cloud/requirements/cloud-requirements.md
  guides/v2.1/cloud/setup/first-time-deploy.md
  guides/v2.1/cloud/setup/first-time-setup-import-first-steps.md
  guides/v2.1/cloud/setup/first-time-setup-import-prepare.md
  guides/v2.1/cloud/trouble/environments-logs.md
  guides/v2.2/cloud/composer-packages/patch-notes.md
  guides/v2.2/cloud/live/paypal-onboarding.md
  guides/v2.2/cloud/reference/cloud-composer.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/requirements/cloud-requirements.md
  guides/v2.2/cloud/trouble/environments-logs.md
Labels: Editorial, internal-dev

#3273 MAGECLOUD-2894 Move global variables
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/env/variables-build.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/env/variables-global.md
  guides/v2.1/cloud/env/variables-intro.md
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/env/working-with-variables.md
  guides/v2.1/cloud/live/sens-data-over.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.1/magento-devdocs-whatsnew.md
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-global.md
  guides/v2.2/cloud/live/sens-data-over.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/env/variables-global.md
Labels: Editorial, internal-dev

#3240 Redoc updates
  _layouts/redoc.html
  redoc/2.3/admin-rest-api.html
  redoc/2.3/admin-schema.json
  redoc/2.3/customer-rest-api.html
  redoc/2.3/customer-schema.json
  redoc/2.3/guest-rest-api.html
  redoc/2.3/guest-schema.json
Labels: Site improvements, internal-dev

#3285 correct path to magento command
  _includes/config/message-queue-consumers.md
Labels: 2.3.x, Editorial, internal-dev

#3278 Add the MFTF Credentials topic
  _data/toc/magento-functional-testing-framework-guide-2_3.yml
  mftf/2.3/credentials.md
  mftf/2.3/data.md
  mftf/2.3/reporting.md
Labels: 2.3.x, New doc, internal-dev

#3288 Weekly digest
  whats-new.md
Labels: 2.x, Editorial

#3290 Fixed links in 'mftf'
  rakelib/proofer.rb
Labels: 2.x, Editorial

#3294 Update MSI REST tutorial
  _data/toc/rest-api.yml
  guides/v2.3/rest/tutorials/index.md
  guides/v2.3/rest/tutorials/msi-order-processing/assign-source-to-stock.md
  guides/v2.3/rest/tutorials/msi-order-processing/bulk-transfer-products.md
  guides/v2.3/rest/tutorials/msi-order-processing/configure-environment.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-cart-add-products.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-customer.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-invoice.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-order.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-products.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-shipment.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-sources.md
  guides/v2.3/rest/tutorials/msi-order-processing/create-stock.md
  guides/v2.3/rest/tutorials/msi-order-processing/index.md
  guides/v2.3/rest/tutorials/msi-order-processing/prepare-for-checkout.md
  guides/v2.3/rest/tutorials/msi-order-processing/reassign-products-to-another-source.md
  guides/v2.3/rest/tutorials/msi-order-processing/run-ssa.md
Labels: 2.3.x, Major update, internal-dev

#3270 Implement link checking as a Jekyll hook
  .gitignore
  Gemfile
  Rakefile
  _config.checks.yml
  _config.stage.yml
  _config.yml
  _plugins/html-check-hook.rb
  guides/v2.1/mrg/ee/MsrpStaging.md
  guides/v2.1/mrg/ee/RmaStaging.md
  guides/v2.1/mrg/ee/SalesRuleStaging.md
  guides/v2.2/mrg/ee/MsrpStaging.md
  guides/v2.2/mrg/ee/RmaStaging.md
  guides/v2.2/mrg/ee/SalesRuleStaging.md
  rakelib/jekyll.rb
  rakelib/proofer.rb
  rakelib/test.rake
Labels: Site improvements

#3299 Rename directory for Inventory tutorial
  _data/toc/rest-api.yml
  guides/v2.3/inventory/index.md
  guides/v2.3/rest/tutorials/index.md
  guides/v2.3/rest/tutorials/inventory/assign-source-to-stock.md
  guides/v2.3/rest/tutorials/inventory/bulk-transfer-products.md
  guides/v2.3/rest/tutorials/inventory/configure-environment.md
  guides/v2.3/rest/tutorials/inventory/create-cart-add-products.md
  guides/v2.3/rest/tutorials/inventory/create-customer.md
  guides/v2.3/rest/tutorials/inventory/create-invoice.md
  guides/v2.3/rest/tutorials/inventory/create-order.md
  guides/v2.3/rest/tutorials/inventory/create-shipment.md
  guides/v2.3/rest/tutorials/inventory/create-sources.md
  guides/v2.3/rest/tutorials/inventory/create-stock.md
  guides/v2.3/rest/tutorials/inventory/index.md
  guides/v2.3/rest/tutorials/inventory/prepare-for-checkout.md
  guides/v2.3/rest/tutorials/inventory/reassign-products-to-another-source.md
  guides/v2.3/rest/tutorials/inventory/run-ssa.md
  whats-new.md
Labels: 2.3.x, Editorial, internal-dev

#3276 Cloud 2002.0.15 release
  _data/main-nav.yml
  _data/toc/cloud-guide.yml
  _includes/cloud/note-ece-tools-package.md
  guides/v2.1/cloud/configure/configure-best-practices.md
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/env/variables-build.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/env/variables-global.md
  guides/v2.1/cloud/env/variables-intro.md
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/env/working-with-variables.md
  guides/v2.1/cloud/live/sens-data-over.md
  guides/v2.1/cloud/project/ece-tools-upgrade-project.md
  guides/v2.1/cloud/project/magento-env-yaml.md
  guides/v2.1/cloud/project/project-conf-files_magento-app.md
  guides/v2.1/cloud/project/project-conf-files_services-mysql.md
  guides/v2.1/cloud/reference/cloud-composer.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/composer-packages/ece-patches.md
  guides/v2.2/cloud/docker/docker-quick-reference.md
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-global.md
  guides/v2.2/cloud/live/sens-data-over.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/reference/cloud-composer.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/docker/docker-quick-reference.md
  guides/v2.3/cloud/env/variables-global.md
  whats-new.md
Labels: 2.1.x, 2.2.x, 2.3.x, In progress, Major update, internal-dev

#3280 MFTF 2.3.11 release updates
  mftf/2.3/commands/mftf.md
  mftf/2.3/introduction.md
Labels: 2.3.x, Major update

#3301 Broken links: Config Guide
  _config.checks.yml
  guides/v2.1/config-guide/cache/cache-types.md
  guides/v2.1/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.1/config-guide/varnish/config-varnish-configure.md
  guides/v2.1/config-guide/varnish/config-varnish-final.md
  guides/v2.1/extension-dev-guide/cache/partial-caching.md
  guides/v2.1/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.1/extension-dev-guide/indexing.md
  guides/v2.1/extension-dev-guide/prepare/prepare.md
  guides/v2.1/install-gde/trouble/tshoot_var-gen-perms.md
  guides/v2.1/test/js/jasmine.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/config-guide/varnish/config-varnish-configure.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/test/js/jasmine.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
Labels: Editorial, internal-dev

#3300 Fix message for developer mode
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
Labels: 2.2.x, Editorial

#3307 Fix links: Extension Best Practices Guide
  _config.checks.yml
  guides/v2.1/ext-best-practices/admin/placement-and-design.md
Labels: 2.x, Editorial

#3309 GraphQL: Add CatalogInventory attributes
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.x, Community, Technical, internal-dev

#3215 Add documentation for creating a Source Selection Algorithm
  _data/toc/inventory.yml
  guides/v2.3/inventory/source-selection-algorithms.md
Labels: 2.3.x, Community, New doc, internal-dev

#3311 Fix links: Extension Developer Guide
  _config.checks.yml
  guides/v2.0/extension-dev-guide/build/create_component.md
  guides/v2.1/coding-standards/docblock-standard-general.md
  guides/v2.1/extension-dev-guide/build/create_component.md
  guides/v2.1/extension-dev-guide/cli-cmds/cli-howto.md
  guides/v2.1/extension-dev-guide/factories.md
  guides/v2.1/extension-dev-guide/proxies.md
  guides/v2.1/extension-dev-guide/service-contracts/service-contracts.md
  guides/v2.1/test/unit/writing_testable_code.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  guides/v2.3/extension-dev-guide/build/create_component.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
Labels: 2.x, Editorial

#3313 Add content for deprecated ScalableInventory entities
  guides/v2.3/inventory/scalable-inventory-replacements.md
Labels: 2.3.x, Major update, internal-dev

#3312 Fix links: UI Components Guide
  _config.checks.yml
  guides/v2.1/mrg/ee/Staging.md
  guides/v2.1/ui_comp_guide/bk-ui_comps.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_template_literals.md
  guides/v2.2/mrg/ee/Staging.md
  guides/v2.2/ui_comp_guide/bk-ui_comps.md
  guides/v2.2/ui_comp_guide/components/ui-insertform.md
  guides/v2.2/ui_comp_guide/components/ui-insertlisting.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_template_literals.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
Labels: 2.x, Editorial, internal-dev

#3314 Fix links: How Do I Guide
  _config.checks.yml
  guides/v2.0/howdoi/checkout/checkout_customize.md
  guides/v2.1/howdoi/checkout/checkout_customize.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_modifier_concept.md
Labels: 2.x, Editorial, internal-dev

#3310 MAGECLOUD-2923 release note for cron bug
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Editorial, internal-dev

#3315 Fix links: REST Guide
  _config.checks.yml
  guides/v2.1/get-started/gs-web-api-request.md
  guides/v2.2/b2b/shared-catalog.md
  guides/v2.3/rest/tutorials/inventory/create-customer.md
Labels: 2.x, Editorial, internal-dev

#3321 Fix links: Remove ignored files
  _config.checks.yml
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.1/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.1/frontend-dev-guide/translations/theme_dictionary.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.2/mrg/ce/instant-purchase/index.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.3/contributor-guide/contributing.md
  guides/v2.3/rest/tutorials/inventory/index.md
  mftf/2.3/data.md
Labels: 2.x, Editorial, internal-dev

#3320 Weekly digest
  whats-new.md
Labels: 2.x, Editorial

#3326 GraphQL: Update query examples
  guides/v2.3/graphql/search-pagination.md
Labels: 2.3.x, Community, Technical, internal-dev

#3329 explains "use_separate_process"
  guides/v2.0/config-guide/cron/custom-cron-ref.md
  guides/v2.1/config-guide/cron/custom-cron-ref.md
Labels: 2.x, Editorial

#3330 Fix #3261 Broken links in release-notes
  _config.checks.yml
  _data/toc/release-notes.yml
  _includes/install/releasenotes/ce_install_21.md
  _includes/install/releasenotes/ee_install_21.md
Labels: Editorial, internal-dev

#3331 Fix #3250 broken links in pattern library
  _config.checks.yml
  guides/v2.1/javascript-dev-guide/widgets/widget_alert.md
  guides/v2.1/pattern-library/containers/slideouts-modals-overlays/slideouts-modals-overalys.md
  guides/v2.1/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.1/ui_comp_guide/components/ui-massactions.md
  guides/v2.2/ui_comp_guide/components/ui-massactions.md
Labels: 2.x, Editorial, internal-dev

#3333 Fix links: Frontend Developer Guide
  _config.checks.yml
  guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.0/frontend-dev-guide/layouts/layout-override.md
  guides/v2.0/frontend-dev-guide/layouts/layout-types.md
  guides/v2.0/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.0/frontend-dev-guide/layouts/xml-manage.md
  guides/v2.0/frontend-dev-guide/responsive-web-design/rwd_practice.md
  guides/v2.0/frontend-dev-guide/templates/template-override.md
  guides/v2.0/frontend-dev-guide/themes/theme-structure.md
  guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.1/frontend-dev-guide/layouts/layout-override.md
  guides/v2.1/frontend-dev-guide/layouts/layout-types.md
  guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.1/frontend-dev-guide/layouts/xml-manage.md
  guides/v2.1/frontend-dev-guide/responsive-web-design/rwd_practice.md
  guides/v2.1/frontend-dev-guide/templates/template-override.md
  guides/v2.1/frontend-dev-guide/themes/theme-structure.md
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
  guides/v2.2/frontend-dev-guide/templates/template-override.md
Labels: 2.x, Editorial, internal-dev

#3335 Fix links: Tech Bulletins
  _config.checks.yml
  magento-techbull.md
Labels: 2.x, Editorial, internal-dev

#3334 add quote endpoint topic
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.x, Community, New doc, internal-dev

#3336 MAGECLOUD-2027 New look for Cloud release notes
  _config.checks.yml
  common/css/devdocs.css
  guides/v2.1/cloud/project/project-upgrade-parent.md
  guides/v2.1/cloud/release-notes/cloud-release-archive.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/composer-packages/ece-patches.md
  guides/v2.2/cloud/release-notes/cloud-release-archive.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/.jekyll-metadata
  guides/v2.3/cloud/release-notes/cloud-release-archive.md
  i/icons/fix.svg
  i/icons/new.svg
  scss/devdocs.scss
  scss/partials/_list-icons.scss
Labels: 2.1.x, 2.2.x, 2.3.x, In progress, Major update, Site improvements, internal-dev

#3343 Fix buttons for contributors
  _config.yml
Labels: 2.x, Site improvements

#3352 Recommend ECMAScript 5.1 instead of 5, and remove abbreviation of ECMAScript for clarity
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, Editorial, internal-dev

#3354 Update language around async code
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, Editorial, internal-dev

#3355 Clarify language around globals
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, Editorial, internal-dev

#3356 Clarify language around redeclaration of JS identifiers
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, Technical, internal-dev

#3348 Fixed technical problem of observer event
  guides/v2.0/config-guide/config/config-create.md
  guides/v2.1/config-guide/config/config-create.md
Labels: 2.x, Technical

#3358 Weekly digest
  whats-new.md
Labels: 2.x, Editorial, internal-dev

#2886 Updated security guidelines
  guides/v2.0/coding-standards/technical-guidelines.md
  guides/v2.1/coding-standards/technical-guidelines.md
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.x, Major update

#3230 MAGEDOC-3112: Add note to relevant pages about 2.1.16 PHP 7.1 support
  guides/v2.1/install-gde/prereq/php-centos.md
  guides/v2.1/install-gde/prereq/php-ubuntu.md
  guides/v2.1/install-gde/system-requirements-tech.md
Labels: 2.1.x, Technical

#3233 MAGEDOC-3207: Add PHP 7.1 support to table
  _includes/install/php_2.1.md
Labels: 2.1.x, Editorial

#3205 Release Notes for Magento Commerce 1.14.4.0 and Magento Open Source 1.9.4.0
  guides/m1x/ce19-ee114/ce1.9_release-notes.html
  guides/m1x/ce19-ee114/ee1.14_release-notes.html
Labels: internal-dev

#3239 2.1.16 release notes
  Gemfile.lock
  _data/toc/release-notes.yml
  _includes/release-notes/engcom-2-1-16-partner.md
  _includes/release-notes/engcom-2-1-16.md
  guides/v2.1/release-notes/ReleaseNotes2.1.16CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.16EE.md
  guides/v2.1/release-notes/bk-release-notes.md
Labels: internal-dev

#3242 Magento Open Source and Commerce 2.2.7 Release Notes
  _data/toc/release-notes.yml
  _includes/release-notes/engcomm-2-2-7-partner.md
  _includes/release-notes/engcomm-2-2-7.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.2/release-notes/bk-release-notes.md
  whats-new.md
Labels: internal-dev

#3362 2.2.7 update: Navigate Magento 2.2 to the MFTF 2.3
  _data/main-nav.yml
Labels: 2.2.x, Editorial

#3360 MAGEDOC-3262: Remove pre-release topics and links to quick start guide
  guides/v2.3/index.html
  guides/v2.3/install-gde/composer.md
  guides/v2.3/release-notes/2.3.0-install.md
  guides/v2.3/release-notes/2.3.0-quick-start.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/bk-release-notes.md
  index.html
Labels: 2.3.x, Editorial

#3367 Change upgrade script link to release branch
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: Editorial

#3346 MAGETWO-94070: Documenation of Enable/disable EAV indexer from Configuration for Magento 2.3
  guides/v2.3/extension-dev-guide/indexer-batch.md
Labels: 2.3.x, Major update, internal-dev

#3370 Update component health index for 2.3.0 release
  guides/v2.3/release-notes/component-status.md
Labels: 2.3.x, Technical

#3364 Add config option to toggle link checking
  _config.yml
  _plugins/html-check-hook.rb
Labels: Technical

#3372 Remove reference to 2.3 Beta
  guides/v2.3/rest/tutorials/inventory/index.md
Labels: 2.3.x, Editorial, internal-dev

#3373 Update notes on GraphQL and MSI per further review
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, Major update

#3375 MAGEDOC-3275: Update Open Source release notes
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, Editorial

#3369 Declarative schema: reference ID changes
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
Labels: 2.3.x, Major update, internal-dev

#3377 MAGEDOC-3277: Fix redirects
  guides/v2.1/ui_comp_guide/bk-ui_comps.md
  guides/v2.2/ui_comp_guide/bk-ui_comps.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3378 Generated documentation for backward incompatible changes between 2.1.15-2.1.16 releases
  _includes/backward-incompatible-changes/commerce/2.1.15-2.1.16.html
  _includes/backward-incompatible-changes/open-source/2.1.15-2.1.16.html
Labels: 2.1.x, Technical, internal-dev

#3379 Generated backward incompatible changes for Magento 2.2.6-2.2.7
  _includes/backward-incompatible-changes/commerce/2.2.6-2.2.7.html
  _includes/backward-incompatible-changes/open-source/2.2.6-2.2.7.html
Labels: 2.2.x, Technical

#3380 Generated backward incompatible changes (2.1.0 - 2.3.0)
  _includes/backward-incompatible-changes/commerce/2.1.0-2.3.0.html
  _includes/backward-incompatible-changes/open-source/2.1.0-2.3.0.html
Labels: 2.1.x, 2.3.x, Technical

#3381 Generated backward incompatible changes (2.2.0 - 2.3.0)
  _includes/backward-incompatible-changes/commerce/2.2.0-2.3.0.html
  _includes/backward-incompatible-changes/open-source/2.2.0-2.3.0.html
Labels: 2.2.x, 2.3.x, Technical

#3385 Update getting-started.md (2.3)
  mftf/2.3/getting-started.md
Labels: 2.3.x, Editorial

#3384 Update getting-started.md (2.2)
  mftf/2.2/getting-started.md
Labels: 2.2.x, Editorial

#3387 MAGEDOC-3276: Updated product availability
  availability.md
Labels: 2.3.x, Editorial

#3386 Update release notes with backward incompatible changes after 2.1.16, 2.2.7, 2.3.0 releases
  _includes/backward-incompatible-changes/commerce/2.1.0-2.3.0.md
  _includes/backward-incompatible-changes/commerce/2.1.15-2.1.16.md
  _includes/backward-incompatible-changes/commerce/2.2.0-2.3.0.md
  _includes/backward-incompatible-changes/commerce/2.2.0-develop.html
  _includes/backward-incompatible-changes/commerce/2.2.6-2.2.7.md
  _includes/backward-incompatible-changes/open-source/2.1.0-2.3.0.md
  _includes/backward-incompatible-changes/open-source/2.1.15-2.1.16.md
  _includes/backward-incompatible-changes/open-source/2.2.0-2.3.0.md
  _includes/backward-incompatible-changes/open-source/2.2.0-develop.html
  _includes/backward-incompatible-changes/open-source/2.2.6-2.2.7.md
  guides/v2.1/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.1/release-notes/backward-incompatible-changes/open-source.md
  guides/v2.2/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.2/release-notes/backward-incompatible-changes/open-source.md
  guides/v2.3/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.3/release-notes/backward-incompatible-changes/open-source.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3389 Update go-live-checklist.md
  guides/v2.3/cloud/live/go-live-checklist.md
Labels: 2.3.x, Editorial

#3390 Fixed compare product path relevant to example
  guides/v2.1/extension-dev-guide/cache/page-caching/private-content.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, internal-dev
