Repository magento/devdocs, pull requests merged in 2019-05, with the labels that each got.

#4364 Updating install instructions for B2B install in Cloud
  guides/v2.2/cloud/configure/setup-b2b.md
Labels: 2.2.x, 2.3.x, Technical

#4390 Removed option type from event list
  guides/v2.1/javascript-dev-guide/widgets/widget_loader.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, small changes

#4389 Corrected magnifier option name
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, small changes

#4388 Added missing details of full screen config options for gallery widget
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, small changes

#4347 Added Composer based theme installation important note
  guides/v2.1/frontend-dev-guide/themes/theme-install.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4393 phtml and php required basic skill To use Frontend development guide
  guides/v2.1/frontend-dev-guide/bk-frontend-dev-guide.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4352 Added technical content regarding Install composer base theme
  guides/v2.1/frontend-dev-guide/themes/theme-install.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#4381 Page Builder migration docs release
  Docfile.yml
  _config.yml
  _data/toc/page-builder.yml
  _includes/layout/after-site-header.html
  rakelib/update.rake
Labels: 2.3.1, New topic, internal-dev

#4400 Updated market place link
  guides/v2.1/extension-dev-guide/build/composer-integration.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4398 Updated command for queue consumers list on extension page
  extensions/b2b/index.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4396 Corrected default value of list widget options
  guides/v2.1/javascript-dev-guide/widgets/widget_list.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4360 Updated corresponding pages due to with Magento Coding Standard release
  _data/toc/coding-standards.yml
  _data/whats-new.yml
  guides/v2.1/coding-standards/bk-coding-standards.md
  guides/v2.1/coding-standards/code-standard-php.md
  guides/v2.1/coding-standards/code-standard-sniffers.md
  guides/v2.1/ext-best-practices/extension-coding/security-performance-data-bp.md
  guides/v2.1/ext-best-practices/extension-coding/working-with-arch-bp.md
  guides/v2.1/extension-dev-guide/validate/test-module.md
  guides/v2.2/coding-standards/code-standard-sniffers.md
  guides/v2.2/extension-dev-guide/validate/test-module.md
  guides/v2.2/test/testing.md
  guides/v2.3/coding-standards/code-standard-sniffers.md
  guides/v2.3/extension-dev-guide/validate/test-module.md
  guides/v2.3/frontend-dev-guide/templates/template-security.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#4405 Update shipping compatibility
  _data/compatibility.yml
Labels: Technical, small changes

#4397 Fixed issue of source code URL
  guides/v2.1/javascript-dev-guide/widgets/widget_confirm.md
  guides/v2.1/javascript-dev-guide/widgets/widget_prompt.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, small changes

#4351 Adding code sample example for the use of collapsible widget
  common/images/widget/collapsible-widget-result-animate.png
  common/images/widget/collapsible-widget-result-initial.png
  guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4094 Removed field from Query which causing error & corrected class name.
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.2, Community

#4401 MAGECLOUD-3491 Docker build options
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: internal-dev

#4406 Adding symlink to 2.3 version.
  guides/v2.1/payments-integrations/payment-gateway/response-validator.md
  guides/v2.3/payments-integrations/payment-gateway/response-validator.md
Labels: 2.3.x, Site improvements

#4407 Symlinking to 2.3
  guides/v2.1/payments-integrations/payment-gateway/response-validator.md
  guides/v2.3/payments-integrations/payment-gateway/response-validator.md
Labels: 2.3.x

#4317 [GraphQl] Fixed response for GraphQl setShippingAddressesOnCart
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.2, Partner: Atwix, Technical, partners-contribution

#4210 Request builder : Adding parameter
  guides/v2.1/payments-integrations/base-integration/payment-option-config.md
  guides/v2.2/payments-integrations/base-integration/payment-action.md
  guides/v2.2/payments-integrations/base-integration/payment-option-config.md
Labels: 2.2.x, 2.3.x, Technical

#4330 Fixed wrong info on Graphql CMS endpoints page
  guides/v2.3/graphql/reference/cms.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution

#4346 Improving the dropdown dialog widget documentation
  common/images/widget/dropdown-dialog-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_dialog.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4333 Adjust layout xml instructions and adding xml examples for all argument types
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4423 magento/devdocs#4410: Broken link
  extensions/install/index.md
Labels: Partner: Atwix, partners-contribution

#4416 Update index.md
  extensions/amazon-sales/index.md
Labels: 2.3.1, Editorial, Event: dmcdindia1

#4415 Update queries.md
  guides/v2.3/graphql/queries.md
Labels: 2.3.x, Editorial, Partner: Wagento, partners-contribution

#4418 Update create-integration.md
  guides/v2.1/get-started/authentication/gs-authentication-oauth.md
  guides/v2.1/get-started/gs-web-api-request.md
  guides/v2.1/javascript-dev-guide/bk-javascript-dev-guide.md
  guides/v2.1/pattern-library/bk-pattern.md
  guides/v2.1/pattern-library/containers/staticContentContainer/contentContainer.md
  guides/v2.3/get-started/create-integration.md
Labels: 2.x, Editorial, Event: dmcdindia1

#4411 Fix cloud variables
  guides/v2.1/cloud/deploy/static-content-deployment.md
  guides/v2.1/cloud/project/new-relic.md
Labels: Editorial, internal-dev

#4162 Fix unclear layer names in Arch guide
  guides/v2.1/architecture/archi_perspectives/present_layer.md
  guides/v2.1/architecture/archi_perspectives/service_layer.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4429 updated pre-release release notes
  extensions/amazon-sales/release-notes/index.md
Labels: Editorial, internal-dev

#4424 Update queries.md
  guides/v2.3/graphql/queries.md
Labels: 2.3.x, Event: dmcdindia1, Partner: Wagento, Technical, partners-contribution

#4414 Remove outdated memcache info
  guides/v2.2/config-guide/memcache/memcache.md
  guides/v2.2/config-guide/memcache/memcache_centos.md
  guides/v2.2/config-guide/memcache/memcache_magento.md
  guides/v2.2/config-guide/memcache/memcache_ubuntu.md
  guides/v2.3/config-guide/memcache/memcache.md
  guides/v2.3/config-guide/memcache/memcache_centos.md
  guides/v2.3/config-guide/memcache/memcache_magento.md
  guides/v2.3/config-guide/memcache/memcache_ubuntu.md
Labels: 2.2.x, 2.3.x, Technical

#4431 update to install info
  extensions/amazon-sales/index.md
Labels: Technical, internal-dev

#4372 Checkout new field
  guides/v2.2/howdoi/checkout/checkout_new_field.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4433 Removing a line that was duplicated via include.
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Technical

#4402 GraphQL caching
  _data/toc/graphql.yml
  guides/v2.3/graphql/caching.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/develop/identity-class.md
  guides/v2.3/graphql/develop/resolvers.md
  guides/v2.3/graphql/send-request.md
Labels: 2.3.2, New topic, internal-dev

#4395 MAGECLOUD-3491: Document validations on docker
  guides/v2.1/cloud/docker/docker-config.md
Labels: internal-dev

#4430 Adding command to CLI command list
  guides/v2.2/config-guide/cli/config-cli-subcommands.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4382 Update config-create.md
  guides/v2.1/config-guide/config/config-create.md
  guides/v2.2/config-guide/config/config-create.md
  guides/v2.3/config-guide/config/config-create.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Vaimo, partners-contribution, small changes

#4409 MAGECLOUD-3054: Implement Database Locks using Zookeeper and flock fo…
  _data/toc/installation-guide.yml
  guides/v2.1/install-gde/install/cli/install-cli-subcommands.md
  guides/v2.2/config-guide/prod/config-reference-envphp.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-deployment.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-lock.md
  guides/v2.3/install-gde/install/cli/install-cli-subcommands-lock.md
Labels: 2.2.x, 2.3.x, New topic, internal-dev

#4437 Improving the writing testable code section
  guides/v2.1/test/unit/writing_testable_code.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4435 fix zero downtime statements
  guides/v2.1/cloud/deploy/reduce-downtime.md
Labels: 2.x, Technical, internal-dev

#4358 Add magnifier widget options sample example using view.xml
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution, small changes

#4434 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#4444 Adding new system specific path as per Backend
  guides/v2.1/config-guide/prod/config-reference-sens.md
  guides/v2.2/config-guide/prod/config-reference-sens.md
  guides/v2.3/config-guide/prod/config-reference-sens.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4447 MAGECLOUD-3345: Add Node.js container
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
Labels: Technical, internal-dev

#4316 [GraphQl] Example of using customizable options on add to cart request
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.2, Partner: Atwix, Technical, partners-contribution

#4184 Add missing attribute into document
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.2, Community, In progress, Partner: Krish TechnoLabs, partners-contribution

#4282 Added technical content about css merging and minification.
  guides/v2.1/frontend-dev-guide/css-topics/css-overview.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4404 MAGECLOUD-3469 indicate add-ons in starter and pro
  guides/v2.1/cloud/architecture/cloud-architecture.md
Labels: 2.x, Technical, internal-dev

#4377 MSI 1.1.2 release notes
  _data/compatibility.yml
  _includes/layout/after-site-header.html
  extensions/inventory-management/index.md
  guides/v2.3/inventory/inventory-cli-reference.md
  guides/v2.3/inventory/release-notes.md
Labels: 1.1.2-msi, Major update, internal-dev

#4448 Cloud 2002.0.18 release
  _data/main-nav.yml
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-database.md
  guides/v2.1/cloud/docker/docker-development-debug.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/env/variables-build.md
  guides/v2.1/cloud/env/variables-cloud.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/docker/docker-database.md
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-cloud.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-global.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/docker/docker-database.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, internal-dev

#4439 Update order-issue-refund.md template
  guides/v2.1/rest/tutorials/orders/order-issue-refund.md
  guides/v2.3/rest/tutorials/orders/order-issue-refund.md
Labels: 2.x, Editorial, Partner: ISM eCompany, partners-contribution

#4457 MSI-2162 Add API reference
  _data/toc/inventory.yml
  _data/whats-new.yml
  guides/v2.3/inventory/catalog-inventory-replacements.md
  guides/v2.3/inventory/index.md
  guides/v2.3/inventory/inventory-api-reference.md
  guides/v2.3/inventory/reservations.md
  guides/v2.3/inventory/scalable-inventory-replacements.md
Labels: 1.1.2-msi, New topic, internal-dev

#4366 Update backward incompatible changes docs for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
Labels: 2.3.2, Technical

#4458 MSI 1.1.2 Beta release content
  _data/compatibility.yml
  _data/toc/configuration-guide.yml
  _data/toc/inventory.yml
  _data/whats-new.yml
  _includes/layout/after-site-header.html
  extensions/inventory-management/index.md
  guides/v2.3/config-guide/cli/config-cli-inventory.md
  guides/v2.3/inventory/catalog-inventory-replacements.md
  guides/v2.3/inventory/images/inventory-diagram-stock.png
  guides/v2.3/inventory/index.md
  guides/v2.3/inventory/inventory-api-reference.md
  guides/v2.3/inventory/inventory-cli-reference.md
  guides/v2.3/inventory/release-notes.md
  guides/v2.3/inventory/reservations.md
  guides/v2.3/inventory/scalable-inventory-replacements.md
  guides/v2.3/rest/modules/inventory/bulk-inventory.md
Labels: 1.1.2-msi, 2.3.x, New topic, internal-dev

#4456 Adding contact specific system paths
  guides/v2.1/config-guide/prod/config-reference-sens.md
  guides/v2.2/config-guide/prod/config-reference-sens.md
  guides/v2.3/config-guide/prod/config-reference-sens.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4453 Added clear information regarding XML block or container value true/false
  guides/v2.1/frontend-dev-guide/theme-best-practice.md
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4465 Update code registration.php file in theme directory
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4464 Update file registration.php code as per Magento2.3
  guides/v2.3/frontend-dev-guide/themes/admin_theme_create.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4449 Update prereqs for Fastly VCL redirect config
  guides/v2.1/cloud/cdn/fastly-vcl-wordpress.md
Labels: 2.x, Technical, internal-dev

#4468 Update docfile to use magento/ page builder repos
  Docfile.yml
Labels: Site improvements

#4469 magento/devdocs#: Replace <your Magento install dir> with <magento_root>
  _includes/comp-man/dependency.md
  _includes/config/locate-session.md
  _includes/install/file-system-perms-oneuser.md
  _includes/install/file-system-perms-oneuser_22.md
  _includes/install/file-system-perms-twouser.md
  _includes/install/file-system-perms-twouser_22.md
  _includes/install/first-steps-cli.md
  _includes/install/new-cli-intro.md
  _includes/install/sampledata/file-sys-perms-digest.md
  _includes/install/sampledata/sample-data-after.md
  _includes/install/sampledata/sample-data-clone.md
  _includes/install/sampledata/sample-data-composer.md
  _includes/install/trouble/rc_cron.md
  _includes/install/trouble/rc_perms.md
  _includes/install/trouble/rc_php-version.md
  _includes/migration/find-version.md
  _includes/vendor/types-def.md
Labels: Partner: Atwix, partners-contribution

#4471 magento/devdocs#: Add or update components
  guides/v2.1/install-gde/install/cli/dev_add-update.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#4392 JS debugging by using DevTools
  common/images/debugging-breakpoints.png
  common/images/debugging-execution-trace.png
  common/images/debugging-sources-pane.png
  guides/v2.1/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_js.md
  guides/v2.2/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_js.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4478 Update inventory/create-cart-add-products.html template
  guides/v2.3/rest/tutorials/inventory/create-cart-add-products.md
Labels: 2.3.x, Editorial, Partner: ISM eCompany, Technical, partners-contribution, small changes

#4473 magento/devdocs#: Remove unused include file
  _includes/migration/find-version.md
Labels: Partner: Atwix, Site improvements, partners-contribution

#4477 Update inventory/create-customer.md template
  guides/v2.3/rest/tutorials/inventory/create-customer.md
Labels: Editorial, Partner: ISM eCompany, partners-contribution, small changes

#4461 Remove duplicate content from Install a theme as composer package section
  guides/v2.1/frontend-dev-guide/themes/theme-install.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4463 Added sentence to click to Save Configuration button
  guides/v2.1/frontend-dev-guide/themes/theme-apply.md
Labels: 2.1.x, 2.3.x, 2.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4475 magento/devdocs#: Set page layout type
  guides/v2.1/frontend-dev-guide/images/wish-list-sharing.png
  guides/v2.1/frontend-dev-guide/layouts/layout-types.md
  guides/v2.2/frontend-dev-guide/images/wish-list-sharing.png
  guides/v2.3/frontend-dev-guide/images/wish-list-sharing.png
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4476 translation guide for email template
  guides/v2.1/frontend-dev-guide/translations/translate_theory.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4472 MAGEDOC-3687: Amazon Sales Channel GA docs
  _data/compatibility.yml
  _includes/layout/after-site-header.html
  extensions/amazon-sales/index.md
  extensions/amazon-sales/release-notes/index.md
  release/index.md
Labels: 2.0.0-asc, Major update

#4328 Adjust technical guidelines event observer example
  guides/v2.1/coding-standards/technical-guidelines.md
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4487 Removed extra tag
  guides/v2.2/ui_comp_guide/components/ui-actionscolumn.md
Labels: 2.2.x, 2.3.x, Editorial

#4498 Improving "Add a new input form to checkout" steps
  guides/v2.1/howdoi/checkout/checkout_form.md
Labels: 2.x, ContributionDay, Major update, Partner: Webjump, partners-contribution

#4499 Fix theme inheritance layout files load order - Issue #2796
  guides/v2.1/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.x, ContributionDay, Major update, Partner: Webjump, partners-contribution

#4500 Adding additional information regarding InstallData and a reference to data patches for 2.3
  guides/v2.1/extension-dev-guide/attributes.md
  guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.x, ContributionDay, Major update

#4497 added missing php tags
  guides/v2.2/extension-dev-guide/plugins.md
Labels: 2.2.x, Community Insider: Cedcommerce, ContributionDay, Editorial, community-insider-contribution

#4490 [2.3.3] Updated lock config and lock env short commands
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
Labels: 2.2.x, 2.3.3, 2.3.x, Community Insider: Cedcommerce, ContributionDay, Technical, community-insider-contribution

#4486 Fix formatting in kramdown and Liquid
  guides/v2.1/config-guide/mq/manage-mysql.md
  guides/v2.1/install-gde/prereq/php-centos.md
  guides/v2.1/install-gde/prereq/php-ubuntu.md
  guides/v2.2/comp-mgr/prereq/prereq_compman-checklist.md
  guides/v2.2/install-gde/prereq/php-centos.md
  guides/v2.2/install-gde/prereq/php-ubuntu.md
  guides/v2.2/install-gde/system-requirements-tech.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, small changes

#4485 Minor fixes to docker
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Editorial, internal-dev

#4483 Added number for Cron section
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.3.2, Editorial

#4509 Update the backward incompatible changes docs for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
Labels: 2.3.x, Technical, small changes

#4504 magento/devdocs#: Develop data and schema patches. Revert module datapatch
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
Labels: 2.3.x, Major update, Partner: Atwix, partners-contribution

#4508 Corrected Fastly CDN availability info on Starter
  guides/v2.1/cloud/cdn/cloud-fastly.md
Labels: 2.2.x, Editorial, internal-dev

#4515 updating magento command for docker based on description in issue #4514
  guides/v2.1/cloud/docker/docker-quick-reference.md
Labels: Editorial, small changes

#4516 Add FORCE_UPDATE_URLS deploy variable doc
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, Technical, internal-dev

#4512 Improvements for Cloud Docker topic
  guides/v2.1/cloud/docker/docker-config.md
Labels: Technical, internal-dev

#4521 Adding the service's node attributes defined in webapi.xsd
  guides/v2.1/extension-dev-guide/service-contracts/service-to-web-service.md
  guides/v2.2/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4454 Fix target="_blank" space & code indentation
  guides/v2.1/extension-dev-guide/cache/page-caching/public-content.md
Labels: 2.1.x, Technical, small changes

#4511 MAGECLOUD-2973 db table prefixes
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: Technical, internal-dev

#4531 Fix format issue in Fastly configuration topic
  guides/v2.1/cloud/cdn/configure-fastly.md
Labels: 2.x, Editorial, internal-dev

#4536 Fix link title
  guides/v2.3/graphql/index.md
Labels: Editorial, small changes

#4540 Update assign-source-to-stock.md template
  guides/v2.3/rest/tutorials/inventory/assign-source-to-stock.md
Labels: 2.3.x, Editorial, Partner: ISM eCompany, partners-contribution

#4539 Prefer exception expectations in body
  guides/v2.3/graphql/functional-testing.md
Labels: 2.3.x, Technical

#4510 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#4501 Functional testing introduction > Syntax fix
  guides/v2.3/graphql/functional-testing.md
Labels: 2.3.x, Editorial, Partner: Imagination Media, partners-contribution, small changes

#4526 magento/devdocs#: CLI. Create or edit an administrator. Examples
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-admin.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-admin.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4530 Defining the zip attributes based on the xsd schema
  guides/v2.1/howdoi/checkout/checkout_zip.md
Labels: 2.1.x, 2.3.x, 2.x, Major update, Partner: Atwix, partners-contribution

#4547 Update attributes.md
  guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.x, Editorial, Partner: Wagento, partners-contribution, small changes

#4546 Uppdate extension-dev-guide/indexer-batch.md
  guides/v2.3/extension-dev-guide/indexer-batch.md
Labels: 2.3.x, Editorial, Partner: ISM eCompany, partners-contribution, small changes

#4517 magento/devdocs#: EAV and extension attributes. Content fix
  guides/v2.1/extension-dev-guide/attributes.md
Labels: 2.1.x, 2.2.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4520 Add description related to server side vs client side compilation
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4527 magento/devdocs#: Locate templates, layouts, and styles
  guides/v2.2/frontend-dev-guide/themes/debug-theme.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4545 [Resolved Tables overflow the content area if cell contains unbreakable text]
  guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.x, Partner: Wagento, Site improvements, partners-contribution

#4502 Draft: Reorg GraphQL quote topic
  _data/toc/graphql.yml
  _includes/graphql/cart-address-input.md
  _includes/graphql/cart-item-input.md
  _includes/graphql/cart-object.md
  _includes/graphql/customizable-option-input.md
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/graphql/reference/quote-add-simple-products.md
  guides/v2.3/graphql/reference/quote-add-virtual-products.md
  guides/v2.3/graphql/reference/quote-apply-coupon.md
  guides/v2.3/graphql/reference/quote-create-cart.md
  guides/v2.3/graphql/reference/quote-payment-method.md
  guides/v2.3/graphql/reference/quote-place-order.md
  guides/v2.3/graphql/reference/quote-remove-coupon.md
  guides/v2.3/graphql/reference/quote-remove-item.md
  guides/v2.3/graphql/reference/quote-set-billing-address.md
  guides/v2.3/graphql/reference/quote-set-guest-email.md
  guides/v2.3/graphql/reference/quote-set-shipping-address.md
  guides/v2.3/graphql/reference/quote-shipping-method.md
  guides/v2.3/graphql/reference/quote-update-cart-items.md
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.2, Community, New topic, internal-dev

#4548 Update index.md
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
Labels: Partner: Wagento, partners-contribution

#4532 Revised the devdocs contribution guide
  .github/CONTRIBUTING.md
Labels: internal-dev

#4535 Added devdocs maintainer guidelines
  .github/MAINTAINER_GUIDELINES.md
  guides/v2.1/contributor-guide/devdocs-maintainers.md
  guides/v2.1/contributor-guide/maintainers.md
Labels: internal-dev

#4541 magento/devdocs#: Routing. Action result object.
  guides/v2.1/extension-dev-guide/routing.md
  guides/v2.3/extension-dev-guide/routing.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4554 GraphQL: Update configurable product attribute names
  guides/v2.3/graphql/reference/configurable-product.md
Labels: 2.3.2, Community, Technical, internal-dev

#4553 GraphQL: enter review comments
  guides/v2.3/graphql/reference/quote-add-simple-products.md
  guides/v2.3/graphql/reference/quote-update-cart-items.md
Labels: 2.3.2, Community, Editorial, internal-dev

#4371 magento/devdocs#: Add custom shipping carrier
  guides/v2.1/howdoi/checkout/checkout-add-custom-carrier.md
  guides/v2.1/howdoi/checkout/checkout_address.md
  guides/v2.1/howdoi/checkout/checkout_carrier.md
  guides/v2.1/howdoi/checkout/checkout_edit_form.md
  guides/v2.1/howdoi/checkout/checkout_form.md
  guides/v2.1/howdoi/checkout/checkout_new_field.md
  guides/v2.1/howdoi/checkout/checkout_overview.md
  guides/v2.1/howdoi/checkout/checkout_zip.md
  guides/v2.1/howdoi/checkout/images/checkout-add-custom-carrier-01.png
  guides/v2.1/howdoi/checkout/images/checkout-add-custom-carrier-02.png
  guides/v2.2/howdoi/checkout/checkout-add-custom-carrier.md
  guides/v2.2/howdoi/checkout/images/checkout-add-custom-carrier-01.png
  guides/v2.2/howdoi/checkout/images/checkout-add-custom-carrier-02.png
  guides/v2.3/howdoi/checkout/checkout-add-custom-carrier.md
  guides/v2.3/howdoi/checkout/images/checkout-add-custom-carrier-01.png
  guides/v2.3/howdoi/checkout/images/checkout-add-custom-carrier-02.png
Labels: 2.1.x, 2.2.x, 2.3.x, New topic, Partner: Atwix, partners-contribution

#4563 Weekly update
  _data/whats-new.yml
Labels: 2.x, Editorial

#4556 GraphQL: Add isEmailAvailable query
  guides/v2.3/graphql/reference/customer.md
Labels: 2.3.2, Community, Major update, internal-dev

#4480 It is easy to Locate styles and css path with grunt tool
  guides/v2.1/frontend-dev-guide/themes/debug-theme.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#4479 Add the technical content regarding grunt exec command.
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4559 Layout overview Introduction content added
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
Labels: 2.3.2, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4558 Added CSS in Media queries condition and generate into magneto style for mobile and desktop
  guides/v2.1/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4566 Fixed link to Page Builder contribution guide.
  _data/toc/page-builder.yml
Labels: 2.3.1, internal-dev

#4567 Correct vendor name
  guides/v2.3/config-guide/elasticsearch/es-downgrade.md
Labels: 2.3.x, Technical, internal-dev

#4565 MAGECLOUD-3569: Improve UX by adding scripts
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-database.md
  guides/v2.1/cloud/docker/docker-development-debug.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
Labels: internal-dev

#4542 MAGECLOUD-3545 add release note for exclude list
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, internal-dev

#4569 Navigation style for mobile and tab style for desktop
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#4503 Add brief detail of Ui component related to frontend and Adminhtml area
  guides/v2.1/ui_comp_guide/bk-ui_comps.md
  guides/v2.2/ui_comp_guide/bk-ui_comps.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4552 Add code examples of adding callbacks on the collapsible widget events
  guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4528 Adding a new topic of how to add a new dynamic rows system config
  common/images/ext-best-practices/dynamic-rows-config-result.png
  guides/v2.1/ext-best-practices/tutorials/dynamic-row-system-config.md
  guides/v2.2/ext-best-practices/tutorials/dynamic-row-system-config.md
  guides/v2.3/ext-best-practices/tutorials/dynamic-row-system-config.md
Labels: 2.1.x, 2.2.x, 2.3.x, New topic, Partner: Atwix, partners-contribution

#4574 MAGECLOUD-2114 fix YAML formatting
  _includes/cloud/pretty-print-services.md
  _includes/cloud/service-config-integration-starter.md
  guides/v2.1/cloud/configure/setup-cron-jobs.md
  guides/v2.1/cloud/env/environment-vars_magento.md
  guides/v2.1/cloud/env/setup-notifications.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/env/variables-global.md
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/project/project-conf-files_magento-app.md
  guides/v2.1/cloud/project/project-conf-files_routes.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/project/project-conf-files_services-mysql.md
  guides/v2.1/cloud/project/project-conf-files_services-rabbit.md
  guides/v2.1/cloud/project/project-conf-files_services-redis.md
  guides/v2.1/cloud/project/project-conf-files_services.md
  guides/v2.1/cloud/project/project-routes-more-cache.md
  guides/v2.1/cloud/project/project-routes-more-redir.md
  guides/v2.1/cloud/project/project-routes-more-ssi.md
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-global.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.x, Editorial, Technical, internal-dev

#4582 Add code examples how to open and close dropdown dialog
  guides/v2.1/javascript-dev-guide/widgets/widget_dialog.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#4588 Add Methods section for loader widget
  guides/v2.1/javascript-dev-guide/widgets/widget_loader.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4581 magento/devdocs#: Extend commands list
  guides/v2.1/config-guide/cli/config-cli-subcommands.md
  guides/v2.2/config-guide/cli/config-cli-subcommands.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4590 Adjust quick search widget documentation
  guides/v2.1/javascript-dev-guide/widgets/widget_quickSearch.md
  guides/v2.2/javascript-dev-guide/widgets/widget_quickSearch.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4600 Update /inventory/create-customer.md
  guides/v2.3/rest/tutorials/inventory/create-customer.md
Labels: 2.3.x, Editorial, Partner: ISM eCompany, partners-contribution

#4602 Add new Page Builder links
  _data/main-nav.yml
  guides/v2.3/page-builder/index.md
  index.html
Labels: 2.3.1, Editorial, Site improvements, internal-dev

#4595 Update Magento Copyright license details content
  guides/v2.1/mtf/features/reporting.md
  guides/v2.2/extension-dev-guide/message-queues/implement-bulk.md
  guides/v2.3/extension-dev-guide/message-queues/implement-bulk.md
Labels: 2.1.x, 2.3.x, 2.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4597 Fix the sample data remove command
  _includes/install/sampledata/sample-data-other-cmds.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4604 magento/devdocs#: Add info about @escapeNotVerified
  guides/v2.2/frontend-dev-guide/templates/template-security.md
  guides/v2.3/frontend-dev-guide/templates/template-security.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#4606 Updated Page Builder index page for devdocs
  guides/v2.3/page-builder/index.md
Labels: 2.3.1, Site improvements, internal-dev

#4576 Added description about default.xml
  guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4609 Removed extra slashes
  guides/v2.1/javascript-dev-guide/javascript/custom_js.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, small changes

#4610 Corrected accepted values
  guides/v2.1/javascript-dev-guide/widgets/widget_navigation.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, small changes

#4607 Update code language package registration.php file
  guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4592 magento/devdocs#: Development. Updates for clear directories.
  guides/v2.1/howdoi/php/php_clear-dirs.md
  guides/v2.2/howdoi/php/php_clear-dirs.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4583 Update configuration file
  guides/v2.1/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4589 Added missing options and updated methods section for menu widget
  guides/v2.1/javascript-dev-guide/widgets/widget_menu.md
  guides/v2.2/javascript-dev-guide/widgets/widget_menu.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4611 Small changes
  _includes/install/sampledata/sample-data-other-cmds.md
  guides/v2.1/javascript-dev-guide/javascript/custom_js.md
  guides/v2.1/javascript-dev-guide/widgets/widget_dialog.md
  guides/v2.1/javascript-dev-guide/widgets/widget_navigation.md
  guides/v2.1/mtf/features/reporting.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.2/extension-dev-guide/message-queues/implement-bulk.md
  guides/v2.2/frontend-dev-guide/templates/template-security.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.3/extension-dev-guide/message-queues/implement-bulk.md
  guides/v2.3/frontend-dev-guide/templates/template-security.md
Labels: internal-dev

#4603 Cloud 2002.0.19 release
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, Technical, internal-dev

#4359 Add technical content as per the codebase repository
  guides/v2.3/graphql/reference/customizable-option-interface.md
Labels: 2.3.2, Community, Partner: Krish TechnoLabs, Technical, partners-contribution
