Repository magento/devdocs, pull requests merged in 2019-02, with the labels that each got.

#3626 Separate by newline console command and text.
  _includes/cloud/enable-ssh.md
Labels: 2.x, Editorial

#3658 Updated docker-magento repo to new url
  community/resources/resources.md
Labels: 2.x, Editorial

#3661 Update config-cli-subcommands-index.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3673 MAGEDOC-3495: Remove Magento Payments
  availability.md
Labels: internal-dev

#3671 Update label based on modules names
  _includes/webapi/services23.md
  guides/v2.2/b2b/integrations.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#3670 Improves GraphQL queries indentation
  guides/v2.3/graphql/search-pagination.md
Labels: 2.3.x, Technical

#3675 Added inventory catalog api
  _includes/webapi/services23.md
  guides/v2.3/rest/list.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3681 Anchor tag removed from use-varnish-cache.md
  guides/v2.2/config-guide/varnish/use-varnish-cache.md
Labels: 2.2.x, 2.3.x, Editorial

#3683 Update label based on modules names
  _includes/webapi/services21.md
  _includes/webapi/services22.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#3688 Adjust GraphQL queries indentation & text markdown
  guides/v2.3/graphql/develop/create-custom-url-resolver.md
  guides/v2.3/graphql/reference/categories.md
  guides/v2.3/graphql/reference/customer.md
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/graphql/reference/quote.md
  guides/v2.3/graphql/reference/store-config.md
  guides/v2.3/graphql/search-pagination.md
Labels: 2.3.x, Community, Technical

#3647 Update magento-bindings.md
  guides/v2.2/ui_comp_guide/concepts/magento-bindings.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_uilayout_concept.md
Labels: 2.2.x, 2.3.x, Editorial

#3689 Update Community slack information and resources
  community/resources/best-practices.md
  community/resources/resources.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.x, Community, Editorial, internal-dev

#3316 Technical Guidelines: domain vs presentation-specific logic
  guides/v2.0/coding-standards/technical-guidelines.md
  guides/v2.1/coding-standards/technical-guidelines.md
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.x, Major update, internal-dev

#3685 module-load-order.md #3649
  guides/v2.1/extension-dev-guide/build/module-load-order.md
Labels: 2.1.x, 2.3.x, 2.x, Community Insider: Cedcommerce, Technical, community-insider-contribution

#3676 MFTF. Getting Started page update
  mftf/2.2/getting-started.md
  mftf/2.3/getting-started.md
Labels: 2.2.x, 2.3.x, Partner: ISM eCompany, Technical, partners-contribution

#3691 Updated What's New on DevDocs
  _data/whats-new.yml
Labels: 2.x, Editorial

#3610 MAGECLOUD-2882: Duplication beetwen SCD_EXCLUDE_THEME and SCD_MATRIX
  guides/v2.1/cloud/env/variables-build.md
  guides/v2.1/cloud/env/variables-deploy.md
Labels: internal-dev

#3693 Update search-pagination.md
  guides/v2.3/graphql/search-pagination.md
Labels: 2.3.x, Community Insider: Cedcommerce, Technical, community-insider-contribution

#3692 MAGECLOUD-3026 resource variable
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3694 MAGEDOC-3502: Elastic search config
  guides/v2.3/config-guide/elasticsearch/es-overview.md
Labels: 2.3.x, Editorial

#3682 Update configurable-product.md
  guides/v2.3/graphql/reference/configurable-product.md
Labels: 2.3.x, Partner: Wagento, Technical, partners-contribution

#3698 Page redirect to same version page
  guides/v2.3/rest/tutorials/orders/order-issue-refund.md
Labels: 2.3.1, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3674 Fix the $ dissapearing from the `bash` code blocks
  common/css/devdocs.css
  scss/devdocs.scss
Labels: Site improvements

#3705 Fix nav (#1568)
  _data/toc/extension-best-practices.yml
Labels: 2.x, Editorial

#3709 MC-6046: Replace 2.0 links with 2.3 links
  guides/v2.3/payments-integrations/payment-gateway/response-validator.md
Labels: 2.3.1, Editorial

#3711 Adding two more Tips and Tricks to MFTF page.
  mftf/2.3/tips-tricks.md
Labels: 2.3.x, Major update

#3714 Fix #3697 legacy architecture note
  _includes/cloud/note-pro-legacy.md
  guides/v2.1/cloud/trouble/pro-env-management.md
Labels: 2.x, Editorial

#3721 GraphQL calculated typo fix
  guides/v2.1/install-gde/install/cli/install-cli-subcommands-admin.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/index.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution

#3629 remove the docker installation section (48f3df90)
  README.md
Labels: Editorial

#3662 MAGEDOC-3489 Cron logging updates
  guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-cron.md
  guides/v2.2/config-guide/cli/logging.md
  guides/v2.3/config-guide/cli/logging.md
Labels: 2.2.x, 2.3.1, Community, Major update, internal-dev

#3723 Update Whats New on Devdocs
  _data/whats-new.yml
Labels: 2.x, Editorial

#3677 Update search-pagination.md
  guides/v2.3/graphql/search-pagination.md
Labels: Partner: Wagento, partners-contribution

#3719 Fixed php syntax highlight issue 2.2 serializer page
  guides/v2.2/extension-dev-guide/framework/serializer.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: ISM eCompany, partners-contribution

#3710 Update public cache content
  guides/v2.1/extension-dev-guide/cache/page-caching/public-content.md
Labels: 2.1.x, 2.3.x, 2.x, Partner: ISM eCompany, Technical, partners-contribution

#3725 Three typos correction (quantity, payment, synchronously)
  guides/v2.2/frontend-dev-guide/themes/js-bundling.md
  guides/v2.3/mrg/ce/InstantPurchase.md
  guides/v2.3/rest/modules/inventory/check-salable-quantity.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution

#3730 Add note about batching changes
  .github/CONTRIBUTING.md
Labels: Editorial

#3728 Cloud release bug notes
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Technical, internal-dev

#3703 Update project-routes-more-redir.md
  guides/v2.1/cloud/project/project-routes-more-redir.md
Labels: 2.x, Editorial, In progress

#3731 Add asynchronous REST schemas
  _data/toc/rest-api.yml
  redoc/2.3/async-admin-rest-api.html
  redoc/2.3/async-admin-schema.json
  redoc/2.3/async-customer-rest-api.html
  redoc/2.3/async-customer-schema.json
  redoc/2.3/async-guest-rest-api.html
  redoc/2.3/async-guest-schema.json
  redoc/2.3/index.md
Labels: 2.3.x, Community, New doc, internal-dev

#3668 Review draft for Distance SSA updates
  _data/toc/configuration-guide.yml
  _includes/config/cli-inventory.md
  _includes/webapi/services23.md
  guides/v2.3/config-guide/cli/config-cli-inventory.md
  guides/v2.3/inventory/source-selection-algorithms.md
  guides/v2.3/rest/list.md
  guides/v2.3/rest/modules/inventory/manage-source-selection.md
  guides/v2.3/rest/tutorials/inventory/assign-source-to-stock.md
  guides/v2.3/rest/tutorials/inventory/create-cart-add-products.md
  guides/v2.3/rest/tutorials/inventory/create-customer.md
  guides/v2.3/rest/tutorials/inventory/create-sources.md
  guides/v2.3/rest/tutorials/inventory/index.md
  guides/v2.3/rest/tutorials/inventory/prepare-for-checkout.md
  guides/v2.3/rest/tutorials/inventory/run-ssa.md
Labels: 2.3.x, Community, Major update, internal-dev

#3569 Inventory Management Release Notes January 2019
  _data/toc/inventory.yml
  _data/toc/release-notes.yml
  _data/var.yml
  _includes/inventory-management/release-notes/intro.md
  _includes/inventory-management/release-notes/v1-1-0.md
  guides/v2.3/inventory/release-notes.md
  guides/v2.3/release-notes/inventory-management.md
Labels: New doc, msi-1.1.0

#3732 Edits to MSI release notes
  _includes/inventory-management/release-notes/intro.md
  guides/v2.3/comp-mgr/install-extensions/inventory-management-installation.md
Labels: internal-dev, msi-1.1.0

#3657 Update config-cli-subcommands-cache.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, Waiting for response, partners-contribution

#3608 Add schema Url for Async import
  guides/v2.3/rest/generate-local.md
Labels: Partner: Comwrap, partners-contribution

#3733 Update db-schema.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3737 Wrong url path in new Inventory Management document
  guides/v2.3/rest/tutorials/inventory/create-cart-add-products.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3736 Update ui-actiondelete.md
  guides/v2.2/ui_comp_guide/components/ui-actiondelete.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3735 MAGEDOC-2761: Fix WEBSITES env var syntax
  guides/v2.1/config-guide/prod/config-reference-var-name.md
  guides/v2.2/config-guide/prod/config-reference-var-name.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3741 Added new nfinset search condition
  guides/v2.2/rest/performing-searches.md
  guides/v2.3/rest/performing-searches.md
Labels: 2.2.x, 2.3.1, Partner: Krish TechnoLabs, Technical, partners-contribution

#3726 Update ui-listing-grid.md
  guides/v2.2/ui_comp_guide/components/ui-listing-grid.md
Labels: 2.2.x, 2.3.x, Partner: Wagento, Technical, partners-contribution

#3727 Update ui-form.md
  guides/v2.2/ui_comp_guide/components/ui-form.md
Labels: 2.2.x, 2.3.x, Partner: Wagento, Technical, partners-contribution

#3752 Fixed path to Restricting access to anonymous web APIs v.2.1
  guides/v2.1/rest/anonymous-api-security.md
  guides/v2.2/rest/anonymous-api-security.md
Labels: 2.x, Editorial, Partner: ISM eCompany, partners-contribution

#3753 Replace github-pages gem with jekyll gems
  Gemfile
  Gemfile.lock
Labels: Site improvements

#3755 Adding Debugging topic to MFTF guide
  _data/toc/magento-functional-testing-framework-guide-2_3.yml
  mftf/2.3/debugging.md
Labels: 2.2.x, 2.3.x, Major update

#3746 MQE-1443: Removing robo commands and updating Codeception paths
  mftf/2.3/commands/codeception.md
  mftf/2.3/extending.md
  mftf/2.3/introduction.md
  mftf/2.3/merging.md
  mftf/2.3/page.md
  mftf/2.3/reporting.md
  mftf/2.3/section.md
  mftf/2.3/section/locator-functions.md
  mftf/2.3/troubleshooting.md
  mftf/2.3/update.md
Labels: 2.3.x, Technical

#3742 Fixed code blocks and indenting cli_cache_subcommands.
  guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.2.x, 2.3.x, Technical

#3744 Update payment-token.md
  guides/v2.3/payments-integrations/vault/payment-token.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3695 MAGEDOC-3450: Page builder config
  Gemfile
  Gemfile.lock
  _config.yml
  mftf/2.2/include/note-2.3-docs.md
  mftf/2.3/include/note-2.2-docs.md
Labels: In progress, Site improvements

#3754 Added parameterized selectors tip to Tips and Tricks
  mftf/2.3/tips-tricks.md
Labels: 2.3.x, Major update

#3739 Update docs for RabbitMQ test configuration
  guides/v2.3/test/integration/integration_test_execution.md
Labels: 2.3.1, Major update, Partner: Something Digital, partners-contribution

#3749 Update gulp-sass.md
  guides/v2.1/frontend-dev-guide/css-topics/gulp-sass.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3759 Added release note for validation of property in composer.json file
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, internal-dev

#3747 Update Redis versions
  _includes/install/php_2.3.md
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.1, Technical

#3760 Correct description of renaming a table
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Technical

#3773 Capitalization correction
  guides/v2.0/cloud/cdn/configure-fastly.md
  guides/v2.0/cloud/live/go-live-checklist.md
  guides/v2.1/cloud/cdn/configure-fastly.md
  guides/v2.1/cloud/live/go-live-checklist.md
  guides/v2.1/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.3/cloud/live/go-live-checklist.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Classy Llama, partners-contribution

#3776 Adjusted "Code cleanup" reward definition
  _includes/contributor/rewards.md
Labels: 2.x, Editorial, internal-dev

#3761 Update ui-form.md
  guides/v2.3/ui_comp_guide/components/ui-form.md
Labels: 2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3775 Updated example of a basic component’s configuration file
  guides/v2.2/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3770 Correct usage of "Recovery Time Objective" term
  guides/v2.0/cloud/architecture/pro-architecture.md
  guides/v2.1/cloud/architecture/pro-architecture.md
Labels: 2.x, Editorial, Partner: Classy Llama, partners-contribution

#3768 Updated argument in example under "Configure DataSource" section
  guides/v2.1/ui_comp_guide/components/ui-listing-grid.md
Labels: 2.1.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3767 Remove unknown anonymous API
  guides/v2.1/rest/anonymous-api-security.md
  guides/v2.2/rest/anonymous-api-security.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3738 Magecloud 2573 admin variables
  guides/v2.1/cloud/before/before-setup-env-2_clone.md
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.1/cloud/env/environment-vars_magento.md
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
  guides/v2.1/cloud/project/project-upgrade.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/project/project-upgrade.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
  guides/v2.3/cloud/project/project-upgrade.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, internal-dev

#3765 Added missing slash in url
  guides/v2.1/rest/retrieve-filtered-responses.md
  guides/v2.2/rest/retrieve-filtered-responses.md
  guides/v2.3/rest/retrieve-filtered-responses.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3780 Update doc contribution guidelines
  .github/CONTRIBUTING.md
Labels: Technical

#3778 Udpate Whats New on DevDocs
  _data/whats-new.yml
Labels: 2.x, Editorial

#3757 Magecloud 2903 update php version validation
  guides/v2.1/cloud/basic-information/starter-architecture.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.1/cloud/requirements/cloud-requirements.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/requirements/cloud-requirements.md
  guides/v2.3/cloud/requirements/cloud-requirements.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3787 Set up multiple websites, stores, and store views in the Admin image issue
  common/images/config_multi-site-add-store-url.png
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3784 Added the X_FRAME_CONFIGURATION global environment variable and relea…
  guides/v2.1/cloud/env/variables-global.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, internal-dev

#3791 Adding testing strategies to Testing Guide.
  guides/v2.2/test/testing.md
Labels: 2.2.x, 2.3.x, Major update

#3758 Create GraphQL Topic for Wish List Endpoint
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/wishlist.md
Labels: 2.3.1, Community, In progress, Technical

#3793 MAGECLOUD-2466 Warm up pages variable updates
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3789 Update Parameters in URLs Example
  guides/v2.1/rest/notes.md
  guides/v2.2/rest/notes.md
Labels: 2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3797 MAGECLOUD-2883 docker notes
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Technical

#3796 MAGECLOUD-2925: Added release item for logging updates
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3785 Remove postman target URL
  guides/v2.1/rest/tutorials/orders/order-intro.md
  guides/v2.2/rest/tutorials/configurable-product/config-product-intro.md
  guides/v2.3/rest/tutorials/index.md
  guides/v2.3/rest/tutorials/orders/order-intro.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3751 Fixed incorrect link path
  guides/v2.1/cloud/cdn/cloud-fastly-custom-response.md
Labels: 2.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3774 Bumped version number for MFTF 2.3.14
  mftf/2.3/introduction.md
Labels: 2.2.x, 2.3.1, Technical

#3792 Add Merge Action Groups section to the MFTF guide
  mftf/2.3/merging.md
  mftf/2.3/test/action-groups.md
Labels: 2.3.x, Major update

#3799 Added missing command to Config guide.
  guides/v2.2/config-guide/config/disable-module-output.md
Labels: 2.2.x, 2.3.x, Technical

#3781 Adding a Versioning topic to MFTF
  _data/toc/magento-functional-testing-framework-guide-2_3.yml
  mftf/2.3/versioning.md
Labels: 2.2.x, 2.3.x, Major update

#3054 Updated custom layout page with block replacement examples (#1910)
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.x, In progress, Technical

#3798 Update data type of latitude,longitude for the Inventory manage sources api
  guides/v2.3/rest/modules/inventory/manage-sources.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3802 Removed incorrect instructions for reinstall via composer #3701
  guides/v2.1/install-gde/install/cli/install-cli-uninstall.md
Labels: 2.2.x, 2.3.x, Technical

#3805 Update configure-fastly.md
  guides/v2.1/cloud/cdn/configure-fastly.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: ISM eCompany, Technical, partners-contribution

#3809 MAGEDOC-3535: Cloud architecture redundancy
  guides/v2.0/cloud/architecture/pro-architecture-legacy.md
  guides/v2.0/cloud/architecture/pro-architecture.md
  guides/v2.1/cloud/architecture/pro-architecture-legacy.md
  guides/v2.1/cloud/architecture/pro-architecture.md
Labels: 2.x, Editorial

#3806 Update configuration.md
  guides/v2.3/performance-best-practices/configuration.md
Labels: Partner: Wagento, partners-contribution

#3815 Added MFTF folder structure.
  guides/v2.2/test/testing.md
Labels: 2.2.x, 2.3.x, Technical

#3808 Fixed javascript code sample
  guides/v2.1/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3813 MAGEDOC-3133: Expand Algolia index coverage
  _config.yml
Labels: Site improvements

#3819 MAGECLOUD-2241 update support note
  guides/v2.1/cloud/project/project-multi-sites.md
Labels: 2.x, Editorial

#3822 fixing broken link to send request
  guides/v2.3/graphql/reference/store-config.md
Labels: 2.3.1, Editorial, internal-dev

#3820 Whats New update
  _data/whats-new.yml
Labels: 2.x, Editorial

#3762 Sales Order API resources updated
  guides/v2.2/mrg/ce/Sales.md
Labels: 2.3.1, Partner: Krish TechnoLabs, Technical, partners-contribution

#3823 Remove glossary tooltip within code block that displayed HTML code.
  guides/v2.0/mtf/mtf_installation.md
Labels: 2.0.x, Editorial

#3824 Added SCD_EXCLUDE_THEMES deprecation info
  guides/v2.1/cloud/env/variables-build.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Editorial

#3804 Update data type Number to Float for the Inventory manage sources api
  guides/v2.3/rest/modules/inventory/check-salable-quantity.md
  guides/v2.3/rest/modules/inventory/manage-low-quantity.md
  guides/v2.3/rest/modules/inventory/manage-source-items.md
  guides/v2.3/rest/modules/inventory/manage-source-selection.md
Labels: 2.3.x, Community, Partner: Krish TechnoLabs, Technical, msi-1.1.0, partners-contribution

#3826 Update the devdocs theme
  Gemfile.lock
Labels: Site improvements

#3825 GraphQL: Describe mutations
  _data/toc/graphql.yml
  guides/v2.3/graphql/mutations.md
Labels: 2.3.1, Community, New doc, internal-dev

#3788 Cloud 2002.0.16
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/architecture/pro-architecture.md
  guides/v2.1/cloud/basic-information/starter-architecture.md
  guides/v2.1/cloud/before/before-setup-env-2_clone.md
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development-debug.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/env/environment-vars_magento.md
  guides/v2.1/cloud/env/variables-build.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/env/variables-global.md
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/onboarding/onboarding-tasks.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/project/project-upgrade.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.1/cloud/requirements/cloud-requirements.md
  guides/v2.2/cloud/docker/docker-development-debug.md
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/project/project-upgrade.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/requirements/cloud-requirements.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
  guides/v2.3/cloud/docker/docker-development-debug.md
  guides/v2.3/cloud/project/project-upgrade.md
  guides/v2.3/cloud/requirements/cloud-requirements.md
Labels: 2.1.x, 2.2.x, 2.3.x, In progress, Major update, internal-dev

#3830 MAGEDOC-3133: Algolia index config
  _config.yml
  _plugins/algolia.rb
Labels: Site improvements

#3833 MAGEDOC-3547: Update product availability page
  availability.md
Labels: 2.3.x, Major update

#3814 Clarified info about domain delegation
  guides/v2.1/cloud/cdn/configure-fastly.md
  guides/v2.1/cloud/cdn/trouble-fastly.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical
