Repository magento/devdocs, pull requests merged in 2019-07, with the labels that each got.

#4889 Update GraphQL examples and fix typo
  guides/v2.3/graphql/queries.md
  guides/v2.3/graphql/tutorials/checkout/checkout-place-order.md
Labels: 2.3.2, Technical, internal-dev

#4857 Remove view_preprocessed with command
  guides/v2.1/frontend-dev-guide/cache_for_frontdevs.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4895 Sync develop with master
  _config.yml
  _data/toc/extension-best-practices.yml
  _data/toc/software-update-guide.yml
  _includes/cloud/note-pro-missing-self-service-options.md
  _includes/cloud/note-route-all-placeholder.md
  _includes/layout/header-scripts.html
  common/images/widget/confirm-widget-result.png
  guides/v2.1/cloud/cdn/configure-fastly.md
  guides/v2.1/cloud/docker/docker-development-testing.md
  guides/v2.1/cloud/project/project-conf-files_routes.md
  guides/v2.1/cloud/project/project-routes-more-cache.md
  guides/v2.1/cloud/project/project-routes-more-redir.md
  guides/v2.1/cloud/project/project-routes-more-ssi.md
  guides/v2.1/config-guide/bootstrap/magento-modes.md
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
  guides/v2.1/extension-dev-guide/attributes.md
  guides/v2.1/frontend-dev-guide/css-topics/css-themes.md
  guides/v2.1/frontend-dev-guide/translations/xlate.md
  guides/v2.2/cloud/docker/docker-development-testing.md
  guides/v2.2/cloud/project/project-conf-files_routes.md
  guides/v2.2/cloud/project/project-routes-more-redir.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
  guides/v2.2/install-gde/prereq/install-rabbitmq.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/comp-mgr/cli/upgrade-with-plugin.md
  guides/v2.3/comp-mgr/cli/upgrade-with-script.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.3/get-started/create-integration.md
  guides/v2.3/graphql/queries.md
  guides/v2.3/graphql/tutorials/checkout/checkout-place-order.md
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  release/index.md
  release/policy/index.md
Labels: internal-dev

#4875 Adding Sales emails system paths
  guides/v2.3/config-guide/prod/config-reference-sens.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4873 GraphQL: Add documentation for Payflow Pro payment method
  _data/toc/graphql.yml
  guides/v2.3/graphql/payment-methods/payflow-link.md
  guides/v2.3/graphql/payment-methods/payflow-pro.md
  guides/v2.3/graphql/reference/paypal-create-payflow-pro-token.md
  guides/v2.3/graphql/reference/paypal-handle-payflow-pro-response.md
Labels: 2.3.2, New topic, internal-dev

#4892 Update cmsPage query
  guides/v2.3/graphql/reference/cms.md
Labels: 2.3.3, Community, Technical, internal-dev

#4884 Add missing word
  guides/v2.2/cloud/reference/discover-deploy.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Classy Llama, partners-contribution, small changes

#4886 magento-coding-standard requires squizlabs/php_codesniffer:~3.3.0
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Editorial

#4887 Remove misleading statement
  guides/v2.3/migration/bk-migration-guide.md
Labels: 2.3.x, Editorial

#4888 If merge js is enabled bundling don't work
  guides/v2.2/frontend-dev-guide/themes/js-bundling.md
Labels: 2.2.x, 2.3.x, Partner: Interactiv4, Technical, partners-contribution

#4876 Adapt HTML markup to Markdown to fix some links
  guides/v2.3/coding-standards/code-standard-demarcation.md
Labels: 2.3.x, Editorial

#4893 Update term description
  guides/v2.3/javascript-dev-guide/bk-javascript-dev-guide.md
  guides/v2.3/javascript-dev-guide/javascript/js_overview.md
Labels: 2.3.x, Editorial

#4630 Product view page available containers
  guides/v2.1/frontend-dev-guide/layouts/product-layouts.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4899 Updated the devdocs gems bunlde
  Gemfile.lock
Labels: Site improvements, internal-dev

#4901 What's New digest
  _data/whats-new.yml
Labels: Editorial

#4902 Update for Google Shopping ads Channel
  _data/compatibility.yml
  extensions/google-shopping-ads/release-notes/index.md
  release/index.md
Labels: 2.0.2 Google Shopping ads Channel, Major update

#4905 Add Payflow Pro graphic
  guides/v2.3/graphql/images/paypal-payflow-pro.svg
  guides/v2.3/graphql/payment-methods/payflow-pro.md
Labels: 2.3.3, Editorial, internal-dev

#4891 Adding an example using the component name
  guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Technical, partners-contribution

#4904 Magento 2.3.2 Release Note update for view model behavior
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.2

#4909 +: removed s from Magento_InventoryReservation(s)Cli
  extensions/inventory-management/index.md
  guides/v2.3/inventory/release-notes.md
Labels: 2.3.x, Partner: Kega, Technical, partners-contribution

#4885 #4762 Provide information about colorPicker Ui Component
  _data/toc/ui-components-guide.yml
  guides/v2.3/ui_comp_guide/components/ui-colorpicker.md
Labels: 2.3.x, New topic, Partner: Space 48, Technical, partners-contribution

#4851 Add Code Sample example for calendar widget
  common/images/widget/calendar-widget-initial.png
  common/images/widget/calendar-widget-open.png
  common/images/widget/calendar-widget-result.png
  guides/v2.2/javascript-dev-guide/widgets/widget_calendar.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4914 Port content updates after doc site maintenance
  guides/v2.2/cloud/project/project-routes-more-cache.md
  guides/v2.2/cloud/project/project-routes-more-ssi.md
  guides/v2.3/cloud/project/project-conf-files_routes.md
  guides/v2.3/cloud/project/project-routes-more-cache.md
  guides/v2.3/cloud/project/project-routes-more-redir.md
  guides/v2.3/cloud/project/project-routes-more-ssi.md
Labels: 2.2.x, 2.3.x, Editorial

#4922 magento/devdocs#: Editorial. ColorPicker component.
  guides/v2.3/ui_comp_guide/components/ui-colorpicker.md
Labels: 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4921 Fixing the shared parameter default value
  guides/v2.2/extension-dev-guide/events-and-observers.md
  guides/v2.3/extension-dev-guide/events-and-observers.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution

#4919 Update php_codesniffer dependency version for 2.3.2
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Technical

#4849 Updates for Google Shopping ads Channel v3.0
  extensions/google-shopping-ads/images/config-api-key.png
  extensions/google-shopping-ads/index.md
  extensions/google-shopping-ads/release-notes/index.md
Labels: 2.0 Google Shopping ads, Major update, internal-dev

#4906 Added warning to Migrate settings about develop mode.
  guides/v2.2/migration/migration-migrate-settings.md
  guides/v2.3/migration/migration-migrate-settings.md
Labels: 2.2.x, 2.3.x, Editorial

#4878 Statement that cache can be enabled|disabled only from command line starting Magento 2.2 is false #4846
  guides/v2.2/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.2.x, 2.3.x, Technical

#4765 Update technical-guidelines.md
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Technical, small changes

#4925 Update docker-development-testing.md
  guides/v2.2/cloud/docker/docker-development-testing.md
Labels: 2.x, Technical, internal-dev

#4930 GraphQL: Create new topic for Authorize.Net
  _data/toc/graphql.yml
  guides/v2.3/graphql/images/authorize-net.svg
  guides/v2.3/graphql/payment-methods/authorize-net.md
  guides/v2.3/graphql/reference/quote-payment-method.md
Labels: 2.3.3, New topic, internal-dev

#4936 Fixed Dependencies Feedback on page: /guides/v2.3/extension-dev-guide/depend-inj.html and v2.2 #4764
  guides/v2.2/extension-dev-guide/depend-inj.md
  guides/v2.3/extension-dev-guide/depend-inj.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#4938 MAGEDOC-3837: Add 2.1 build steps to the README
  README.md
Labels: Site improvements

#4935 magento/devdocs#: Editorial. ColorPicker component. Fix after edit
  guides/v2.3/ui_comp_guide/components/ui-colorpicker.md
Labels: 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4929 magento/devdocs#: Fix location of Data Migration Tool + Editorial fixes
  guides/v2.2/migration/migration-tool-internal-spec.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, partners-contribution, small changes

#4918 Corrected whats new description for PR #4679
  _data/whats-new.yml
Labels: 2.2.x, 2.3.x, small changes

#4933 Adding key "defaults" to examples
  guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Technical, partners-contribution, small changes

#4724 setup_version not needed in magento 2.3
  guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: 2.3.x, Technical

#4931 MAGECLOUD-3897: [Cloud Docker] Clarification to the use of mutagen
  guides/v2.3/cloud/docker/docker-config.md
Labels: internal-dev

#4780 Add documentation for ToggleAdvanced widget
  _data/toc/javascript-developer-guide.yml
  common/images/widget/toggle-widget-initial-result.png
  common/images/widget/toggle-widget-toggled-result.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget_toggle.md
  guides/v2.3/javascript-dev-guide/widgets/widget_toggle.md
Labels: 2.1.x, 2.2.x, 2.3.x, New topic, Partner: Atwix, partners-contribution

#4908 magento/graphql-ce#: Magento CLI. Support short commands name
  _includes/reference/cli-template.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4945 magento/devdocs#: Magento cache overview. Fix bash commands. Additional editorial
  guides/v2.2/frontend-dev-guide/cache_for_frontdevs.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4211 Add SOA section
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.1.x, 2.2.x, 2.3.x, Waiting for response, internal-dev

#4868 Async/Bulk API patch- Add sections about stores
  guides/v2.3/rest/asynchronous-web-endpoints.md
  guides/v2.3/rest/bulk-endpoints.md
Labels: Community, Major update, Partner: Comwrap, partners-contribution

#4946 Update to Release page
  _data/compatibility.yml
  release/index.md
Labels: Technical, small changes

#4568 Add markdown linting
  .mdlrc
  Gemfile
  Gemfile.lock
  Rakefile
  _checks/md-check-hook.rb
  _checks/md_style
  bin/mdl
  rakelib/check.rake
Labels: Site improvements, internal-dev

#4916 Reference for setPaymentMethodAndPlaceOrder Mutation
  _data/toc/graphql.yml
  _includes/graphql/quote-payment-input.md
  guides/v2.3/graphql/reference/quote-set-payment-place-order.md
Labels: 2.3.3, Community, New topic, Partner: Something Digital, partners-contribution

#4951 Removed search type finset for graphql
  guides/v2.3/graphql/queries.md
Labels: 2.3.3, Community, Partner: Krish TechnoLabs, Technical, partners-contribution

#4952 Removed unnecessary spaces
  guides/v2.2/javascript-dev-guide/javascript/js-resources.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#4949 Small Change: Wrong default value and duplicated template
  guides/v2.3/ui_comp_guide/components/ui-colorpicker.md
Labels: 2.3.x, Partner: Space 48, Technical, partners-contribution, small changes

#4529 Extend component types
  _includes/php-dev/composer-types.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution

#4869 MQE-1609: Add more MFTF technical guidelines to devdocs
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Major update

#4958 Fix broken link in `develop`
  guides/v2.3/graphql/reference/quote-payment-method.md
Labels: internal-dev

#4898 Removed unclear/strange sentence from Security, Performance, and Data Handling
  guides/v2.2/ext-best-practices/extension-coding/security-performance-data-bp.md
  guides/v2.3/ext-best-practices/extension-coding/security-performance-data-bp.md
Labels: 2.2.x, 2.3.x, Editorial

#4959 Adding info about new <block> <argument> attribute
  guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.2, Editorial

#4962 Small Change Update mtf_installation.md
  guides/v2.3/mtf/mtf_installation.md
Labels: Editorial, Partner: Space 48, partners-contribution

#4964 fixed broken glossary links
  guides/v2.2/extension-dev-guide/api-concepts.md
  guides/v2.2/extension-dev-guide/service-contracts/design-patterns.md
  guides/v2.2/extension-dev-guide/service-contracts/service-contracts.md
Labels: 2.2.x, 2.3.x, Editorial, internal-dev

#4956 magento/devdocs#: Extend information about "Input component"
  guides/v2.2/ui_comp_guide/components/ui-input.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4493 Add 'GraphQl backward compatibility policy' section to backward compatibility guide
  guides/v2.3/contributor-guide/backward-compatible-development/index.md
Labels: 2.3.x, Major update, Partner: ISM eCompany, partners-contribution

#3982 Tech Guidelines: factories vs `new` keyword
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Major update, internal-dev

#4961 Clarified SemVer per Architect's review
  guides/v2.3/extension-dev-guide/versioning/dependencies.md
  guides/v2.3/extension-dev-guide/versioning/index.md
Labels: 2.3.x, Editorial

#4928 Add Missing documentation for Javascript Dropdown Widget
  _data/toc/javascript-developer-guide.yml
  common/images/widget/dropdown-widget-result.jpg
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget_dropdown.md
  guides/v2.3/javascript-dev-guide/widgets/widget_dropdown.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, partners-contribution

#4968 Removed hardcoded last updated text from top of page
  guides/v2.3/release-notes/component-status.md
Labels: 2.3.x, Editorial, small changes

#4965 MAGEDOC-3934: Added note for cloud libsodium upgrade
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
Labels: 2.3.x, internal-dev

#4967 Fixed #4954 Feedback on page: /community/resources/best-practices.html
  community/resources/best-practices.md
Labels: Editorial, small changes

#4960 GraphQL: Add mutations for adding/removing store credit to a cart
  _data/toc/graphql.yml
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/mutations/apply-store-credit.md
  guides/v2.3/graphql/mutations/remove-store-credit.md
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.3, New topic, internal-dev

#4425 Remove rules duplicating method signature info
  guides/v2.2/coding-standards/docblock-standard-general.md
Labels: 2.1.x, 2.2.x, 2.3.x

#4741 Added additional rules for extendable and non-extendable @api
  guides/v2.2/extension-dev-guide/versioning/codebase-changes.md
Labels: 2.3.x, Technical, internal-dev

#4947 Impr Web API functional testing setup Instructions
  guides/v2.3/get-started/web-api-functional-testing.md
Labels: 2.x, Editorial, Partner: Space 48, partners-contribution

#4781 Adjust code samples for the confirm widget and added information about modalClass option
  guides/v2.2/javascript-dev-guide/widgets/widget_confirm.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4672 To disable/Manage my Account sidebar links
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4629 Common arguments for blocks
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4882 Add article about Stores in Message Queue
  _data/toc/php-developer-guide.yml
  guides/v2.3/extension-dev-guide/message-queues/message-queues-stores.md
Labels: 2.3.2, New topic, Partner: Comwrap, partners-contribution

#4976 Changed note style to warning
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.3.x, Editorial

#4972 magento/devdocs#: Add link to "Add CLI commands" guide
  _includes/reference/cli-template.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-add.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4973 Added language in content deploy command
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4923 Adding an example of routing usage
  common/images/routing-result.png
  guides/v2.2/extension-dev-guide/routing.md
  guides/v2.3/extension-dev-guide/routing.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4953 Added documentation for self-service cron configuration
  guides/v2.2/cloud/configure/setup-cron-jobs.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/trouble/environments-logs.md
Labels: 2.2.x, 2.3.x, Major update, internal-dev

#4966 What's New update
  _data/whats-new.yml
Labels: Editorial

#4979 Reverting markdown to fix the build
  guides/v2.2/extension-dev-guide/versioning/check-version.md
Labels: 2.2.x, 2.3.x, Site improvements

#4980 Fix link to Changelog
  guides/v2.3/migration/bk-migration-guide.md
Labels: Partner: Classy Llama, partners-contribution

#4985 fix broken nav
  _data/toc/php-developer-guide.yml
Labels: 2.3.3, Editorial, internal-dev

#4991 Remove caching from future feature list
  guides/v2.3/graphql/index.md
Labels: 2.3.2, Editorial, small changes

#4990 Clarify the query cache default behavior.
  guides/v2.3/graphql/develop/create-graphqls-file.md
Labels: 2.3.2, Technical, small changes

#4883 [DOCS] Added reference to Extend Config Data for the `Store` GraphQl …
  guides/v2.3/graphql/reference/store-config.md
Labels: 2.3.x, Major update, Partner: Experius, partners-contribution

#4910 Removing the usage of ObjectManager
  guides/v2.2/howdoi/checkout/checkout_new_field.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Technical, partners-contribution

#4859 Applying mobile-specific style
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_mobile.md
Labels: 2.2.x, 2.3.x, Technical, partners-contribution

#4997 Updates swagger-ui version
  _data/toc/rest-api.yml
  swagger/css/screen.css
  swagger/css/theme.css
  swagger/index.html
  swagger/index_22.html
  swagger/index_23.html
  swagger/lib/backbone-min.js
  swagger/lib/handlebars-2.0.0.js
  swagger/lib/highlight.7.3.pack.js
  swagger/lib/jquery-1.8.0.min.js
  swagger/lib/jquery.ba-bbq.min.js
  swagger/lib/jquery.slideto.min.js
  swagger/lib/jquery.wiggle.min.js
  swagger/lib/marked.js
  swagger/lib/swagger-oauth.js
  swagger/lib/underscore-min.js
  swagger/lib/underscore-min.map
  swagger/swagger-ui-bundle.js
  swagger/swagger-ui-bundle.js.map
  swagger/swagger-ui-standalone-preset.js
  swagger/swagger-ui-standalone-preset.js.map
  swagger/swagger-ui.css
  swagger/swagger-ui.css.map
  swagger/swagger-ui.js
  swagger/swagger-ui.js.map
Labels: 2.2.x, Site improvements

#4963 MAGECLOUD-3811 Add section about generic webhooks
  guides/v2.2/cloud/integrations/cloud-integrations.md
Labels: 2.x, Major update, internal-dev

#4996 Adding additional info regarding the debugger keyword
  common/images/debugger.png
  guides/v2.2/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_js.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4999 Layout for renderers cart page items
  guides/v2.2/frontend-dev-guide/layouts/product-layouts.md
Labels: Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#5002 [site] Upgrade RubyGems instead of Bundler
  README.md
Labels: Site improvements, small changes

#4995 Fix code samples
  guides/v2.2/cloud/project/project-conf-files_routes.md
Labels: 2.2.x, 2.3.x, Editorial

#5008 Sync develop with master
  README.md
  _data/toc/rest-api.yml
  common/images/debugger.png
  guides/v2.2/cloud/integrations/cloud-integrations.md
  guides/v2.2/cloud/project/project-conf-files_routes.md
  guides/v2.2/frontend-dev-guide/layouts/product-layouts.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_mobile.md
  guides/v2.2/howdoi/checkout/checkout_new_field.md
  guides/v2.2/test/unit/unit_test_execution_cli.md
  guides/v2.2/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_js.md
  guides/v2.3/graphql/reference/store-config.md
  swagger/css/screen.css
  swagger/css/theme.css
  swagger/index.html
  swagger/index_22.html
  swagger/index_23.html
  swagger/lib/backbone-min.js
  swagger/lib/handlebars-2.0.0.js
  swagger/lib/highlight.7.3.pack.js
  swagger/lib/jquery-1.8.0.min.js
  swagger/lib/jquery.ba-bbq.min.js
  swagger/lib/jquery.slideto.min.js
  swagger/lib/jquery.wiggle.min.js
  swagger/lib/marked.js
  swagger/lib/swagger-oauth.js
  swagger/lib/underscore-min.js
  swagger/lib/underscore-min.map
  swagger/swagger-ui-bundle.js
  swagger/swagger-ui-bundle.js.map
  swagger/swagger-ui-standalone-preset.js
  swagger/swagger-ui-standalone-preset.js.map
  swagger/swagger-ui.css
  swagger/swagger-ui.css.map
  swagger/swagger-ui.js
  swagger/swagger-ui.js.map
Labels: internal-dev

#5003 MAGECLOUD-3932 update bin docker commands
  guides/v2.2/cloud/docker/docker-quick-reference.md
  guides/v2.2/cloud/reference/ece-tools-reference.md
Labels: 2.x, Technical, internal-dev

#5009 Remove duplicated Cookie section in 2.3.0 Release Note
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, Editorial, small changes

#5004 Fix discrepancy regarding plurality within link
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
Labels: 2.2.x, Editorial, small changes

#5006 magento/devdocs#: Manage the 'My Account' dashboard navigation links (Magento v.2.3)
  guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Major update, Partner: Atwix, partners-contribution

#4974 Adding additional info about buttons for alert and confirm widgets
  common/images/widget/alert-widget-result.png
  common/images/widget/confirm-widget-result.png
  guides/v2.2/javascript-dev-guide/widgets/widget_alert.md
  guides/v2.2/javascript-dev-guide/widgets/widget_confirm.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4733 Added info about PasswordStrengthIndicator widget
  _data/toc/javascript-developer-guide.yml
  common/images/widget/password-strength-indicator-widget-result.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget_password_strength_indicator.md
  guides/v2.3/javascript-dev-guide/widgets/widget_password_strength_indicator.md
Labels: 2.1.x, 2.2.x, 2.3.x, New topic, Partner: Atwix, Waiting for response, partners-contribution

#5010 Remove part of JS Framework section from DB Framework section in Magento Open Source 2.3.0 Release Notes
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, Editorial, small changes

#5016 Fixed #5015 Incorrect Example: /guides/v2.3/howdoi/customize-modifier-class.html
  guides/v2.2/howdoi/customize-modifier-class.md
Labels: 2.2.x, 2.3.x, Technical, small changes

#5019 magento/devdocs#: Editorial. PasswordStrengthIndicator widget.
  guides/v2.2/javascript-dev-guide/widgets/widget_password_strength_indicator.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution

#4998 Fixed #4601 Link missing on page: /guides/v2.3/frontend-dev-guide/translations/xlate.html and v2.2
  guides/v2.2/frontend-dev-guide/translations/xlate.md
  guides/v2.3/frontend-dev-guide/translations/xlate.md
Labels: 2.2.x, 2.3.x, Editorial

#5014 Add federated search
  Gemfile.lock
  _includes/home/intro.html
  _includes/layout/header-scripts.html
  _includes/layout/site-nav.html
Labels: Site improvements, internal-dev

#5013 Refactor CLI template
  _data/codebase/v2_1/open-source/bin-magento.yaml
  _data/codebase/v2_2/open-source/bin-magento.yaml
  _data/codebase/v2_3/open-source/bin-magento.yaml
  _includes/reference/cli-template.md
  guides/v2.2/reference/cli/magento.md
  guides/v2.3/reference/cli/magento.md
Labels: Site improvements

#4820 Create a page describing working with async code
  _data/toc/php-developer-guide.yml
  guides/v2.3/extension-dev-guide/async-operations.md
Labels: 2.3.x, Major update, internal-dev

#4943 Reference for checkoutAgreement GraphQl query
  guides/v2.3/graphql/reference/checkout-aggreements.md
Labels: 2.3.x, Community, New topic, Partner: Something Digital, partners-contribution

#5029 Update checkout_new_field.md
  guides/v2.2/howdoi/checkout/checkout_new_field.md
Labels: 2.2.x, 2.3.x, Technical, small changes

#5028 magento/devdocs#: Migrate install/upgrade scripts to declarative schema. Add available types to "setup:db-declaration:generate-patch" command.
  _data/codebase/v2_3/open-source/bin-magento.yml
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#5027 magento/devdocs#: Migrate install/upgrade scripts to declarative schema. Remove deprecated command
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#5017 Fixed #4975 Deployment Production system
  _includes/config/split-deploy/split-deploy-overview.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#4739 Data migration fixes and updates
  guides/v2.2/migration/bk-migration-guide.md
  guides/v2.2/migration/extend-the-tool.md
  guides/v2.2/migration/migration-migrate-after.md
  guides/v2.2/migration/migration-tool-configure.md
  guides/v2.2/migration/migration-tool-internal-spec.md
  guides/v2.3/migration/bk-migration-guide.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, Waiting for response, partners-contribution

#3414 Update guidelines regarding blocks
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, internal-dev

#5031 Adding an important note how to list all the available SOAP Web Services
  guides/v2.2/get-started/soap/soap-web-api-calls.md
Labels: 2.x, Partner: Atwix, Technical, partners-contribution, small changes

#5018 magento/devdocs#: Add examples of hard and soft module dependencies
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4993 Add store credit attributes to customer query
  guides/v2.3/graphql/mutations/apply-store-credit.md
  guides/v2.3/graphql/mutations/remove-store-credit.md
  guides/v2.3/graphql/reference/customer.md
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.3, Major update, internal-dev

#4920 Document catalog configuration added to storeConfig query
  guides/v2.3/graphql/reference/store-config.md
Labels: 2.3.x, Community, Major update, Partner: Something Digital, partners-contribution

#4977 magento/devdocs#: Docs: Add attributes to Customer endpoint
  guides/v2.3/graphql/reference/customer.md
Labels: 2.3.x, Major update, Partner: Atwix, partners-contribution

#4986 magento/devdocs#: Docs: Add documentation for related/upsell/crosssell products (DEVELOP)
  guides/v2.3/graphql/queries.md
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.3, Major update, Partner: Atwix, partners-contribution

#5042 Make <error> and <info> tags visible in callout
  guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#5041 magento/magento2#: Remove duplicated page
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend_types.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#5043 Clarifying the development process
  guides/v2.2/cloud/docker/docker-config.md
Labels: 2.x, Editorial, Partner: Webjump, partners-contribution, small changes

#5023 MAGECLOUD-3182: Initial upload of default Fastly VCL code required
  guides/v2.2/cloud/cdn/configure-fastly.md
Labels: 2.x, Technical, internal-dev

#5035 GraphQL: Add topic about the Payments Advanced payment method
  _data/toc/graphql.yml
  _includes/graphql/payment-methods/payflow-link-attributes.md
  _includes/graphql/payment-methods/payflow-link-workflow.md
  common/images/graphql/paypal-payflow-link.svg
  guides/v2.3/graphql/images/paypal-payflow-link.svg
  guides/v2.3/graphql/payment-methods/payflow-link.md
  guides/v2.3/graphql/payment-methods/payments-advanced.md
Labels: 2.3.3, New topic, internal-dev

#5036 Adding a tip on how to change the project host
  guides/v2.2/cloud/docker/docker-config.md
Labels: 2.x, Editorial, Partner: Webjump, partners-contribution, small changes

#5038 Finalize the style for Markdown linting
  .mdlrc
  _checks/md_style
Labels: Site improvements

#5045 Adjusted bookmarks UI component documentation and added information about missed options
  guides/v2.2/ui_comp_guide/components/ui-bookmarks.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#5044 Add title to Versioning topic
  guides/v2.3/extension-dev-guide/versioning/index.md
Labels: 2.3.x, Site improvements, internal-dev

#5037 Removed redirects to same destination
  guides/v2.2/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.2/cloud/cdn/cloud-fastly-custom-response.md
  guides/v2.2/cloud/cdn/configure-fastly.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/cloud/setup/first-time-deploy.md
  guides/v2.2/comp-mgr/extens-man/extensman-uninst-final.md
  guides/v2.2/contributor-guide/contributors.md
  guides/v2.2/extension-dev-guide/bk-extension-dev-guide.md
  guides/v2.2/extension-dev-guide/cache/page-caching/public-content.md
  guides/v2.2/install-gde/composer.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-admin.md
  guides/v2.2/install-gde/system-requirements.md
  guides/v2.2/javascript-dev-guide/widgets/widget_quickSearch.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.3/cloud/setup/first-time-deploy.md
  guides/v2.3/extension-dev-guide/bk-extension-dev-guide.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: Editorial

#5049 Editorial table should be formatted using markdown
  guides/v2.2/ui_comp_guide/components/ui-draganddrop.md
Labels: 2.x, Editorial, Partner: Space 48, partners-contribution, small changes

#4941 Update code contributions documentation according to closing 2.2-develop branch
  _includes/contributor/2-2-submission.md
  _includes/contributor/2-3-submission.md
  _includes/contributor/pull-request-table.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.2.x, 2.3.x, Technical

#5053 Manage the 'My Account' dashboard navigation links (Magento v.2.2)
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, Partner: Atwix, Technical, partners-contribution

#5059 What's new updates July 15-26
  _data/whats-new.yml
Labels: Editorial, internal-dev

#5025 Removed outdated info about installing Fastly
  guides/v2.2/cloud/cdn/cloud-fastly.md
  guides/v2.2/cloud/cdn/configure-fastly.md
  guides/v2.2/cloud/cdn/trouble-fastly.md
Labels: 2.x, Major update, internal-dev

#5050 Added information about missed options of the UI button and added the Source files section
  guides/v2.2/ui_comp_guide/components/ui-button.md
  guides/v2.2/ui_comp_guide/components/ui-columns.md
  guides/v2.2/ui_comp_guide/components/ui-linkcolumn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#5055 Removed Magento 1 code reference
  guides/v2.3/coding-standards/code-standard-demarcation.md
Labels: 2.3.x, Technical, small changes

#5064 #5005 Update Magento setup rollback command
  guides/v2.2/install-gde/install/cli/install-cli-backup.md
Labels: 2.2.x, 2.3.x, Partner: Space 48, Technical, partners-contribution, small changes

#5065 Fix issue with escaping of JSON in context of html/attribute
  guides/v2.3/frontend-dev-guide/templates/template-security.md
Labels: 2.3.x, Technical, internal-dev, small changes

#5061 Mae cloud fix hotjar feedback
  guides/v2.2/cloud/architecture/cloud-architecture.md
Labels: Editorial, internal-dev

#5069 Decoupling directory endpoints as per Magedoc3974
  _data/toc/graphql.yml
  _includes/graphql/country-output.md
  guides/v2.3/graphql/queries/directory-countries.md
  guides/v2.3/graphql/queries/directory-country.md
  guides/v2.3/graphql/queries/directory-currency.md
  guides/v2.3/graphql/reference/directory.md
Labels: 2.3.3, Site improvements, internal-dev

#5056 KB migration: Create a patch
  guides/v2.2/comp-mgr/patching.md
  guides/v2.3/comp-mgr/patching.md
Labels: 2.2.x, 2.3.x, Major update

#5070 KB migration: Change Blackfire account owner
  guides/v2.2/cloud/project/project-integrate-blackfire.md
Labels: 2.2.x, 2.3.x, Major update, internal-dev

#5072 KB migration: Change New Relic account owner
  guides/v2.2/cloud/project/new-relic.md
Labels: 2.2.x, 2.3.x, internal-dev

#5071 Updated Fastly shield locations
  guides/v2.2/cloud/cdn/configure-fastly.md
Labels: Technical

#4726 Document CSS critical path
  common/images/critical_css_improvements1.png
  common/images/critical_css_improvements2.png
  common/images/critical_css_improvements3.png
  guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.md
  guides/v2.2/frontend-dev-guide/css-topics/css-overview.md
  guides/v2.2/frontend-dev-guide/css-topics/using-fonts.md
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
  guides/v2.3/frontend-dev-guide/css-topics/css-critical-path.md
  guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
  guides/v2.3/frontend-dev-guide/layouts/layout-types.md
Labels: 2.2.x, 2.3.x, New topic

#5039 MAGECLOUD-2739 update services
  _includes/cloud/pretty-print-services.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-conf-files_services-mysql.md
  guides/v2.2/cloud/project/project-conf-files_services-rabbit.md
  guides/v2.2/cloud/project/project-conf-files_services-redis.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.x, Technical, internal-dev

#5079 MQE-1678: Added Action Groups to Technical Guidelines
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Technical

#5047 MC-14863 Update Varnish version number
  guides/v2.2/config-guide/varnish/config-varnish-install.md
  guides/v2.3/graphql/caching.md
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.3, Technical
