Repository magento/devdocs, pull requests merged in 2019-10, with the labels that each got.

#5501 Converted the Change Fastly credentials KB article to DevDocs
  guides/v2.2/cloud/cdn/cloud-fastly.md
  guides/v2.2/cloud/cdn/configure-fastly.md
  guides/v2.2/cloud/live/stage-prod-test.md
  guides/v2.2/cloud/project/projects.md
  guides/v2.3/cloud/project/projects.md
Labels: 2.x, Major update, Progress: approved, internal-dev

#5491 Update view model extension guide
  guides/v2.2/extension-dev-guide/view-models.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical

#5489 Providing additional info on how an observer can be disabled.
  guides/v2.2/extension-dev-guide/events-and-observers.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#5516 Removed definition links from terminal blocks.
  guides/v2.2/install-gde/trouble/php/tshoot_mcrypt.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5524 Fixed MD010 errors in _includes/install
  _includes/install/allowoverrides22.md
  _includes/install/allowoverrides24.md
  _includes/install/auth-tokens-get.md
  _includes/install/composer-clone.md
  _includes/install/file-system-perms-before.md
  _includes/install/file-system-umask-over.md
  _includes/install/flow-diagram.md
  _includes/install/fully-secure.md
  _includes/install/get-software_zip.md
  _includes/install/install-roadmap.md
  _includes/install/patch/get-patch.md
  _includes/install/paypal-tls1-2.md
Labels: Editorial, Progress: approved

#5526 Fixed MD010 errors in _includes/install
  _includes/install/releasenotes/20_release-notes-links.md
  _includes/install/releasenotes/20rc_release-notes-links.md
  _includes/install/releasenotes/21_release-notes-links.md
  _includes/install/releasenotes/ce_install_20.md
  _includes/install/releasenotes/ee_install_20.md
  _includes/install/releasenotes/get-ce-software_zip.md
  _includes/install/releasenotes/get-ee-software_zip.md
Labels: Editorial, Progress: approved

#5527 Fixed remaining MD010 errors in _includes/install
  _includes/install/sampledata/sample-data-other-cmds.md
  _includes/install/sampledata/sample-data-rc1-cli.md
  _includes/install/sampledata/sample-data-rc1-web.md
  _includes/install/sampledata/sample-data_list-of-modules.md
  _includes/install/sens-data.md
  _includes/install/trouble/rc_cron.md
  _includes/install/trouble/rc_php-version.md
  _includes/install/ulimit.md
  _includes/install/web/install-web.md
  _includes/install/web/install-web_1-readiness.md
  _includes/install/web/install-web_2-db.md
  _includes/install/web/install-web_3-web-conf.md
  _includes/install/web/install-web_4-customize-store.md
  _includes/install/web/install-web_5-create-admin.md
  _includes/install/web/install-web_6-install.md
Labels: Editorial, Progress: approved

#5528 Fixed all MD010 errors in _include/config
  _includes/config/cron-overview.md
  _includes/config/es-verify-proxy.md
  _includes/config/es-webserver-overview.md
  _includes/config/multi-site_verify.md
  _includes/config/php-memcache.md
  _includes/config/secure-ws-apache_step1.md
  _includes/config/setup-cron.md
  _includes/config/setup-cron_2.2.md
  _includes/config/setup-cron_2.2_about.md
  _includes/config/setup-cron_2.2_how-to.md
  _includes/config/solr-elastic-selinux.md
  _includes/config/split-db.md
  _includes/config/split-deploy/config-mgmt-over1.md
  _includes/config/split-deploy/example_build-sync.md
  _includes/config/split-deploy/example_update-prod.md
  _includes/config/split-deploy/split-deploy-assumptions.md
Labels: Editorial, Progress: approved

#5530 Fixes all MD010 errors in the Migration Guide
  guides/v2.2/migration/migration-manually.md
  guides/v2.2/migration/migration-tool-install.md
  guides/v2.2/migration/migration-tool-preconditions.md
  guides/v2.2/migration/migration-tool-upgrade.md
Labels: Editorial, Progress: approved

#5529 Fixed all MD010 errors in the Pattern Library Guide
  guides/v2.2/pattern-library/containers/tabs/tabs.md
  guides/v2.2/pattern-library/controls/buttons/buttons.md
  guides/v2.2/pattern-library/displaying-data/datatable/datatable.md
  guides/v2.2/pattern-library/getting-user-input/date_time_selector/date_time_selector.md
  guides/v2.2/pattern-library/graphics/iconography/iconography.md
  guides/v2.2/pattern-library/templates/address-form/address-form.md
Labels: Editorial, Progress: approved

#5532 Fixed all MD010 errors in release notes
  guides/v2.2/release-notes/ReleaseNotes2.2.0CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.0EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
  guides/v2.2/release-notes/ReleaseNotesMagentoShipping2.2.x.md
  guides/v2.2/release-notes/bk-release-notes.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  guides/v2.3/release-notes/bk-release-notes.md
Labels: Editorial, Progress: approved

#5422 magento/devdocs#: How to get RabbitMQ credentials/connection details
  guides/v2.2/cloud/project/project-conf-files_services-rabbit.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: changes requested, Technical, partners-contribution

#5535 Fixed all MD010 errors in the REST Guide
  guides/v2.2/rest/bulk-endpoints.md
  guides/v2.2/rest/tutorials/configurable-product/create-configurable-product.md
  guides/v2.2/rest/tutorials/configurable-product/create-simple-products.md
  guides/v2.2/rest/tutorials/configurable-product/define-config-product-options.md
  guides/v2.2/rest/tutorials/orders/order-create-customer.md
  guides/v2.2/rest/tutorials/orders/order-create-order.md
  guides/v2.2/rest/tutorials/orders/order-prepare-checkout.md
  guides/v2.3/rest/bulk-endpoints.md
  guides/v2.3/rest/modules/inventory/link-stocks-sources.md
  guides/v2.3/rest/modules/inventory/manage-low-quantity.md
  guides/v2.3/rest/modules/inventory/manage-source-items.md
  guides/v2.3/rest/modules/inventory/manage-source-selection.md
  guides/v2.3/rest/modules/inventory/manage-sources.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.md
  guides/v2.3/rest/tutorials/inventory/create-order.md
  guides/v2.3/rest/tutorials/inventory/reassign-products-to-another-source.md
Labels: Editorial, Progress: approved

#5540 Fixed MD010 errors in GraphQL Guide
  guides/v2.3/graphql/develop/resolvers.md
  guides/v2.3/graphql/reference/bundle-product.md
  guides/v2.3/graphql/reference/grouped-product.md
  guides/v2.3/graphql/reference/product-interface-implementations.md
  guides/v2.3/graphql/reference/store-config.md
Labels: Editorial, Progress: approved

#5541 Fixed MD010 errors in non-cloud includes
  _includes/browsers/supported-browsers.md
  _includes/comp-man/backup.md
  _includes/comp-man/checklist.md
  _includes/comp-man/checklist_2.2.md
  _includes/comp-man/readiness-check.md
  _includes/php-dev/component-root-2.3.md
  _includes/php-dev/component-root.md
  _includes/php-dev/component-versioning.md
Labels: Editorial, Progress: approved

#5539 Fixed MD010 errors in UI Components and JS Dev Guides
  guides/v2.2/javascript-dev-guide/javascript/custom_js.md
  guides/v2.2/javascript-dev-guide/javascript/js-resources.md
  guides/v2.2/ui_comp_guide/components/ui-dynamicrows.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_uicollection_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.2/ui_comp_guide/howto/new_component_declaration.md
Labels: Editorial, Progress: approved

#5538 Fixed MD010 errors
  codelinks/attributes.md
  guides/v2.2/b2b/negotiable-checkout.md
  guides/v2.2/comp-mgr/bk-compman-upgrade-guide.md
  guides/v2.2/comp-mgr/trouble/cman/maint-mode.md
  guides/v2.2/config-guide/bootstrap/magento-bootstrap.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-deploy-strategies.md
  guides/v2.2/config-guide/deployment/pipeline/build-system.md
  guides/v2.2/config-guide/deployment/pipeline/technical-details.md
  guides/v2.2/payments-integrations/base-integration/formblocktype.md
  guides/v2.2/payments-integrations/payment-gateway/command-pool.md
  guides/v2.2/performance-best-practices/introduction.md
  guides/v2.2/test/unit/unit_test_execution_cli.md
  guides/v2.2/test/unit/unit_test_execution_phpstorm.md
Labels: Editorial, Progress: approved

#5531 Add warning about prefixes in generated whitelists.
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
Labels: 2.3.x, Editorial, Progress: approved

#5549 Fixed incorrect diagram explanation, added more clarity
  guides/v2.3/inventory/index.md
Labels: 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution, small changes

#5520 Fixed inconsistent bolding of text
  guides/v2.2/frontend-dev-guide/css-topics/css-overview.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, partners-contribution, small changes

#5513 Add ioncube to list of available extensions
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, small changes

#5533 [WIP] Fix config guide topic for performance testing
  _includes/install/first-steps-cli.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-perf-data.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#5471 magento/devdocs#5245: Hard tabs. Folder: guides/cloud
  guides/v2.2/cloud/basic-information/starter-architecture.md
  guides/v2.2/cloud/before/before-setup-env-2_clone.md
  guides/v2.2/cloud/before/before-workspace-file-sys-owner.md
  guides/v2.2/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.2/cloud/cdn/cloud-fastly-custom-response.md
  guides/v2.2/cloud/cdn/configure-fastly.md
  guides/v2.2/cloud/cdn/fastly-image-optimization.md
  guides/v2.2/cloud/cdn/fastly-vcl-badreferer.md
  guides/v2.2/cloud/cdn/fastly-vcl-whitelist.md
  guides/v2.2/cloud/cdn/fastly-vcl-wordpress.md
  guides/v2.2/cloud/cdn/trouble-fastly.md
  guides/v2.2/cloud/configure/import-url-rewrites.md
  guides/v2.2/cloud/env/environments-ssh.md
  guides/v2.2/cloud/env/set-variables.md
  guides/v2.2/cloud/howtos/custom-theme.md
  guides/v2.2/cloud/howtos/debug.md
  guides/v2.2/cloud/howtos/environment-tutorial-env-merge.md
  guides/v2.2/cloud/howtos/how-to.md
  guides/v2.2/cloud/howtos/sample-data.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/live/live-prot.md
  guides/v2.2/cloud/live/live-sanity-check.md
  guides/v2.2/cloud/live/sens-data-initial.md
  guides/v2.2/cloud/live/stage-prod-live.md
  guides/v2.2/cloud/onboarding/onboarding-portal.md
  guides/v2.2/cloud/project/project-webint-basic.md
  guides/v2.2/cloud/project/project-webint-snap.md
  guides/v2.2/cloud/reference/cloud-composer.md
  guides/v2.2/cloud/reference/git-integration.md
  guides/v2.2/cloud/requirements/cloud-requirements.md
  guides/v2.2/cloud/setup/first-time-deploy.md
  guides/v2.2/cloud/setup/first-time-setup-import-first-steps.md
  guides/v2.2/cloud/trouble/restore-configuration-files.md
  guides/v2.2/cloud/trouble/trouble_ce-creds.md
  guides/v2.2/cloud/trouble/trouble_comp-deploy-fail.md
  guides/v2.2/cloud/trouble/troubleshoot-deployment.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.3/cloud/live/go-live-checklist.md
  guides/v2.3/cloud/live/live-sanity-check.md
Labels: Editorial, Partner: Atwix, Progress: changes requested, partners-contribution

#5557 Final fixes for MD010
  guides/v2.2/cloud/project/project-webint-snap.md
  guides/v2.2/cloud/trouble/restore-configuration-files.md
Labels: Editorial, Progress: approved

#5553 Typo and grammar fixes
  community/resources/support.md
Labels: Editorial, Progress: acceptance testing, small changes

#5556 Fixed trailing character
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5555 Removed unnecessary bullet points
  guides/v2.2/javascript-dev-guide/widgets/widget_sticky.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5552 Updated what's new with changes since Sept 20, 2019
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: approved, internal-dev

#5551 Clarified password management explanation
  guides/v2.3/architecture/security_intro.md
Labels: 2.3.x, Editorial, Progress: review, small changes

#5518 Removing troubleshooting topic. mcrypt removed from PHP 7.2.
  _data/toc/installation-guide.yml
  guides/v2.2/install-gde/trouble/php/tshoot_php-main.md
  guides/v2.3/install-gde/trouble/php/tshoot_mcrypt.md
Labels: 2.3.x, Progress: approved, Site improvements

#5563 Markdown linting: Enable rule MD018 (no space after hash on atx headers)
  _checks/styles/style-rules-prod
Labels: Editorial, Progress: approved, internal-dev

#5482 MAGEDOC-3118 Removing extraneous front matter.
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/comp-mgr/extens-man/extensman-new-purchase.md
  guides/v2.2/comp-mgr/extens-man/extensman-readiness-fail.md
  guides/v2.2/comp-mgr/extens-man/extensman-readiness-multi.md
  guides/v2.2/comp-mgr/extens-man/extensman-readiness-success.md
  guides/v2.2/comp-mgr/extens-man/extensman-readiness.md
  guides/v2.2/comp-mgr/extens-man/extensman-uninst-data.md
  guides/v2.2/comp-mgr/extens-man/extensman-update.md
  guides/v2.2/extension-dev-guide/indexing-custom.md
  guides/v2.2/release-notes/ReleaseNotes2.2.1CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.1EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.3CE.md
Labels: 2.2.x, 2.3.x, Progress: approved, Site improvements

#5570 Remove the procedure class and update the theme
  Gemfile.lock
  common/css/devdocs.css
Labels: Progress: approved

#5542 Replaced duplicate v2.3 file with symlink and cleaned services topics
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-conf-files_services-mysql.md
  guides/v2.2/cloud/project/project-conf-files_services-rabbit.md
  guides/v2.2/cloud/project/project-conf-files_services-redis.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.2/cloud/project/project-integrate-blackfire.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.x, Progress: changes requested, Technical, internal-dev

#5575 Small changes
  community/resources/support.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/frontend-dev-guide/css-topics/css-overview.md
  guides/v2.2/javascript-dev-guide/widgets/widget_sticky.md
  guides/v2.3/architecture/security_intro.md
  guides/v2.3/inventory/index.md
Labels: Progress: approved

#5448 Add store name to store config query schema
  guides/v2.3/graphql/queries/store-config.md
Labels: 2.3.4, Community, In progress, Partner: Something Digital, Progress: review, Technical, partners-contribution

#5578 Updated 2.2.10 release notes
  _includes/release-notes/engcomm-2-2-10-issues.md
  _includes/release-notes/engcomm-2-2-10-partner.md
  guides/v2.2/release-notes/release-notes-2-2-10-commerce.md
  guides/v2.2/release-notes/release-notes-2-2-10-open-source.md
Labels: 2.2.10, Progress: approved, Technical, internal-dev

#5577 Fixed list styles (MD004) in the Release Notes
  guides/v2.2/release-notes/ReleaseNotes2.2.0CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.0EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.1CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.1EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.3CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.3EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.5CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.5EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: Editorial

#5579 Fixed list styles (MD004) in the Frontend Dev Guide
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.2/frontend-dev-guide/css-topics/custom_preprocess.md
  guides/v2.2/frontend-dev-guide/layouts/layout-override.md
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
  guides/v2.2/frontend-dev-guide/layouts/layout-types.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_css.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_overview.md
  guides/v2.2/frontend-dev-guide/themes/admin_theme_apply.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-uninstall.md
  guides/v2.2/frontend-dev-guide/themes/theme-workflow.md
  guides/v2.2/frontend-dev-guide/translations/xlate.md
  guides/v2.3/frontend-dev-guide/layouts/layout-types.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/frontend-dev-guide/translations/xlate.md
Labels: Editorial

#5580 Fixed list styles (MD004) in the Migration Guide
  guides/v2.2/migration/migration-migrate-data.md
  guides/v2.2/migration/migration-tool-configure.md
  guides/v2.2/migration/migration-tool-internal-spec.md
Labels: Editorial

#5582 Jf release notes 2 3 3
  _includes/release-notes/engcomm-2-3-3-issues.md
  _includes/release-notes/engcomm-2-3-3-partner.md
  guides/v2.3/release-notes/bk-release-notes.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: 2.3.3, Editorial, Progress: approved, internal-dev

#5587 Fix for broken link to github repo
  guides/v2.2/frontend-dev-guide/themes/theme-images.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5416 magento/devdocs#: Logging into log file. New topic.
  _data/toc/configuration-guide.yml
  _includes/config-guide/custom-logger-handler-examples.md
  guides/v2.2/config-guide/log/custom-logger-handler.md
  guides/v2.3/config-guide/log/custom-logger-handler.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: changes requested, Technical, partners-contribution

#5568 Google Shopping ads Update
  _data/compatibility.yml
  extensions/google-shopping-ads/index.md
  extensions/google-shopping-ads/release-notes/index.md
  release/index.md
Labels: 2.3.3, 3.0.1 GSa, Major update, Progress: changes requested

#5571 Fixed list styles (MD004) in the UI Components Guide
  guides/v2.2/ui_comp_guide/components/ui-columnscontrols.md
  guides/v2.2/ui_comp_guide/components/ui-exportbutton.md
  guides/v2.2/ui_comp_guide/components/ui-form.md
  guides/v2.2/ui_comp_guide/components/ui-massactions.md
  guides/v2.2/ui_comp_guide/components/ui-multiselectcolumn.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
  guides/v2.3/ui_comp_guide/components/ui-form.md
  guides/v2.3/ui_comp_guide/components/ui-secondary-uiselect.md
Labels: Editorial, Progress: approved

#5574 Fixed list styles (MD004) in the Contribution and Configuration Guides
  guides/v2.2/config-guide/config/config-files.md
  guides/v2.2/config-guide/multi-master/multi-master.md
  guides/v2.2/config-guide/multi-site/ms_over.md
  guides/v2.2/config-guide/prod/config-reference-var-name.md
  guides/v2.2/config-guide/secy/secy-cron.md
  guides/v2.2/config-guide/varnish/config-varnish-configure.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.2/contributor-guide/contributing_dod.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.3/config-guide/config/config-files.md
  guides/v2.3/contributor-guide/backward-compatible-development/index.md
  guides/v2.3/contributor-guide/contributing.md
Labels: Editorial, Progress: approved

#5599 Fixed list styles (MD004) in several guides
  guides/v2.2/advanced-reporting/data-collection.md
  guides/v2.2/design-styleguide/iconography/iconography.md
  guides/v2.2/design-styleguide/number-formats/number-formats.md
  guides/v2.2/extension-dev-guide/indexing-custom.md
  guides/v2.2/extension-dev-guide/plugins.md
  guides/v2.2/get-started/create-integration.md
  guides/v2.2/install-gde/trouble/tshoot_no-styles.md
  guides/v2.2/javascript-dev-guide/javascript/js-resources.md
  guides/v2.2/javascript-dev-guide/widgets/widget_gallery.md
  guides/v2.2/pattern-library/general/accessibilityguideline/accessibilityGuideline.md
  guides/v2.2/payments-integrations/signifyd/signifyd.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
  guides/v2.3/get-started/create-integration.md
  guides/v2.3/install-gde/prereq/mysql.md
Labels: Editorial, Progress: approved

#5601 Fixed list styles (MD004) in several more guides
  guides/v2.2/mtf/create_test/create_new_test.md
  guides/v2.2/mtf/features/reporting.md
  guides/v2.2/mtf/mtf_entities/mtf_block.md
  guides/v2.2/mtf/mtf_entities/mtf_constraint.md
  guides/v2.2/mtf/mtf_entities/mtf_dataset.md
  guides/v2.2/mtf/mtf_entities/mtf_fixture-repo.md
  guides/v2.2/mtf/mtf_entities/mtf_page.md
  guides/v2.2/mtf/mtf_entities/mtf_scenariotest.md
  guides/v2.2/performance-best-practices/configuration.md
  guides/v2.2/security/two-factor-authentication.md
  guides/v2.2/test/js/jasmine.md
  guides/v2.3/graphql/functional-testing.md
  guides/v2.3/inventory/inventory-cli-reference.md
  guides/v2.3/mtf/mtf_installation.md
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  guides/v2.3/security/two-factor-authentication.md
Labels: Editorial, Progress: approved

#5586 Restore PR-5392 to develop
  _data/toc/frontend-developer-guide.yml
  guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.md
  guides/v2.2/frontend-dev-guide/css-topics/css-overview.md
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
  guides/v2.3/frontend-dev-guide/css-topics/css-critical-path.md
Labels: 2.2.10, 2.3.3, New topic, Progress: approved, internal-dev

#5602 GraphQL: Update release notes for 2.3.3
  guides/v2.3/graphql/release-notes.md
Labels: Progress: approved

#5536 GraphQL: backport restructuring changes from 2.3.4 and general cleanup
  _data/toc/graphql.yml
  _data/whats-new.yml
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/index.md
  guides/v2.3/graphql/mutations/add-configurable-products.md
  guides/v2.3/graphql/mutations/apply-giftcard.md
  guides/v2.3/graphql/mutations/apply-store-credit.md
  guides/v2.3/graphql/mutations/change-customer-password.md
  guides/v2.3/graphql/mutations/create-empty-cart.md
  guides/v2.3/graphql/mutations/delete-customer-address.md
  guides/v2.3/graphql/mutations/generate-customer-token.md
  guides/v2.3/graphql/mutations/index.md
  guides/v2.3/graphql/mutations/place-order.md
  guides/v2.3/graphql/mutations/redeem-giftcard-balance.md
  guides/v2.3/graphql/mutations/remove-coupon.md
  guides/v2.3/graphql/mutations/remove-giftcard.md
  guides/v2.3/graphql/mutations/remove-item.md
  guides/v2.3/graphql/mutations/remove-store-credit.md
  guides/v2.3/graphql/mutations/set-billing-address.md
  guides/v2.3/graphql/mutations/set-guest-email.md
  guides/v2.3/graphql/mutations/set-payment-method.md
  guides/v2.3/graphql/mutations/set-payment-place-order.md
  guides/v2.3/graphql/mutations/set-shipping-address.md
  guides/v2.3/graphql/mutations/set-shipping-method.md
  guides/v2.3/graphql/mutations/update-cart-items.md
  guides/v2.3/graphql/product/bundle-product.md
  guides/v2.3/graphql/product/grouped-product.md
  guides/v2.3/graphql/product/product-interface-implementations.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries.md
  guides/v2.3/graphql/queries/cart.md
  guides/v2.3/graphql/queries/category.md
  guides/v2.3/graphql/queries/checkout-agreements.md
  guides/v2.3/graphql/queries/cms-blocks.md
  guides/v2.3/graphql/queries/cms-page.md
  guides/v2.3/graphql/queries/custom-attribute-metadata.md
  guides/v2.3/graphql/queries/directory-countries.md
  guides/v2.3/graphql/queries/directory-country.md
  guides/v2.3/graphql/queries/directory-currency.md
  guides/v2.3/graphql/queries/get-payflow-link-token.md
  guides/v2.3/graphql/queries/giftcard-account.md
  guides/v2.3/graphql/queries/index.md
  guides/v2.3/graphql/queries/products.md
  guides/v2.3/graphql/queries/store-config.md
  guides/v2.3/graphql/queries/wishlist.md
  guides/v2.3/graphql/release-notes.md
Labels: 2.3.3, Progress: approved, Site improvements, internal-dev

#5603 Fixed list styles (MD004) in the Cloud Guide
  README.md
  community/resources/best-practices.md
  guides/v2.2/cloud/basic-information/starter-architecture.md
  guides/v2.2/cloud/cdn/trouble-fastly.md
  guides/v2.2/cloud/composer-packages/ece-patches.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/cloud/setup/first-time-setup-import-prepare.md
Labels: Editorial, Progress: review

#5606 Fixed final list style (MD004) errors
  _checks/styles/style-rules-prod
  guides/v2.2/coding-standards/technical-guidelines.md
  guides/v2.2/comp-mgr/prereq/prereq_compman-checklist.md
  guides/v2.2/mrg/intro.md
  guides/v2.3/graphql/functional-testing.md
Labels: Editorial, Progress: approved

#5600 Inventory release notes
  guides/v2.3/inventory/release-notes.md
Labels: Progress: approved

#5583 Fix typo in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Editorial, Progress: review, small changes

#5607 Merge PRs into develop
  _data/toc/graphql.yml
  _data/whats-new.yml
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/index.md
  guides/v2.3/graphql/mutations/add-configurable-products.md
  guides/v2.3/graphql/mutations/apply-giftcard.md
  guides/v2.3/graphql/mutations/apply-store-credit.md
  guides/v2.3/graphql/mutations/change-customer-password.md
  guides/v2.3/graphql/mutations/create-empty-cart.md
  guides/v2.3/graphql/mutations/delete-customer-address.md
  guides/v2.3/graphql/mutations/generate-customer-token.md
  guides/v2.3/graphql/mutations/index.md
  guides/v2.3/graphql/mutations/place-order.md
  guides/v2.3/graphql/mutations/redeem-giftcard-balance.md
  guides/v2.3/graphql/mutations/remove-coupon.md
  guides/v2.3/graphql/mutations/remove-giftcard.md
  guides/v2.3/graphql/mutations/remove-item.md
  guides/v2.3/graphql/mutations/remove-store-credit.md
  guides/v2.3/graphql/mutations/set-billing-address.md
  guides/v2.3/graphql/mutations/set-guest-email.md
  guides/v2.3/graphql/mutations/set-payment-method.md
  guides/v2.3/graphql/mutations/set-payment-place-order.md
  guides/v2.3/graphql/mutations/set-shipping-address.md
  guides/v2.3/graphql/mutations/set-shipping-method.md
  guides/v2.3/graphql/mutations/update-cart-items.md
  guides/v2.3/graphql/product/bundle-product.md
  guides/v2.3/graphql/product/grouped-product.md
  guides/v2.3/graphql/product/product-interface-implementations.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries.md
  guides/v2.3/graphql/queries/cart.md
  guides/v2.3/graphql/queries/category.md
  guides/v2.3/graphql/queries/checkout-agreements.md
  guides/v2.3/graphql/queries/cms-blocks.md
  guides/v2.3/graphql/queries/cms-page.md
  guides/v2.3/graphql/queries/custom-attribute-metadata.md
  guides/v2.3/graphql/queries/directory-countries.md
  guides/v2.3/graphql/queries/directory-country.md
  guides/v2.3/graphql/queries/directory-currency.md
  guides/v2.3/graphql/queries/get-payflow-link-token.md
  guides/v2.3/graphql/queries/giftcard-account.md
  guides/v2.3/graphql/queries/index.md
  guides/v2.3/graphql/queries/products.md
  guides/v2.3/graphql/queries/store-config.md
  guides/v2.3/graphql/queries/wishlist.md
  guides/v2.3/graphql/release-notes.md
  guides/v2.3/inventory/release-notes.md
Labels: 2.3.3, Progress: approved, internal-dev

#5562 GraphQL: Add categoryList query
  _data/toc/graphql.yml
  guides/v2.3/graphql/caching.md
  guides/v2.3/graphql/queries/category-list.md
  guides/v2.3/graphql/queries/category.md
Labels: 2.3.4, New topic, Progress: changes requested, internal-dev

#5598 Add the recommendation for using IP address over a hostname for database config
  _includes/install/web/install-web_2-db.md
Labels: 2.2.x, 2.3.x, Progress: approved, small changes

#5596 Update required TLS version
  guides/v2.2/install-gde/system-requirements-tech.md
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.2.x, 2.3.x, Progress: approved, small changes

#5595 Added note about mcrypt and PHP < 7.2
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Editorial, Progress: approved, small changes

#5591 Fix typo in discover-deploy.md
  guides/v2.2/cloud/reference/discover-deploy.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#5590 Fix typos in storefront_customization.md
  guides/v2.2/architecture/storefront_customization.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#5588 Fix advanced reporting overview typos
  guides/v2.2/advanced-reporting/overview.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#5604 Updated text for upgraded Migration tool
  guides/v2.2/migration/migration-migrate-delta.md
  guides/v2.3/migration/bk-migration-guide.md
Labels: 2.2.x, 2.3.x, Progress: changes requested, Technical

#5523 Adjusting syntax pattern
  guides/v2.2/javascript-dev-guide/javascript/custom_js.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Imagination Media, Progress: approved, partners-contribution

#5594 Add terminal application information for linux desktops
  guides/v2.2/install-gde/basics/basics_login.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5616 Added changelog to Migration Tool TOC
  _data/toc/migration-guide.yml
Labels: 2.2.x, 2.3.x, Progress: approved, Site improvements

#5597 add information about nginx
  guides/v2.2/install-gde/basics/basics_software.md
Labels: 2.2.x, 2.3.x, Progress: approved

#5614 Fix link for U2F Keys
  guides/v2.3/security/two-factor-authentication.md
Labels: 2.3.x, Editorial, Partner: Classy Llama, Progress: approved, partners-contribution

#5618 Fixed list styles (MD004) - Group 1
  guides/v2.2/javascript-dev-guide/javascript/js_init.md
  guides/v2.2/javascript-dev-guide/javascript/js_logger.md
  guides/v2.2/marketplace/eqp/packages.md
  guides/v2.2/mtf/create_test/create_new_test.md
  guides/v2.2/mtf/create_test/new_test.md
  guides/v2.2/mtf/features/isolation.md
  guides/v2.2/mtf/features/test_suite.md
  guides/v2.2/mtf/mtf_entities/mtf_fixture.md
  guides/v2.2/payments-integrations/base-integration/facade-configuration.md
  guides/v2.2/payments-integrations/payment-gateway/payment-gateway-intro.md
  guides/v2.2/rest/tutorials/configurable-product/create-personalization-option.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/create-personalization-option.md
Labels: Editorial, Progress: approved, internal-dev

#5496 [cicd] Add a GitHub action to lint Markdown at PRs
  .github/workflows/main.yml
Labels: Progress: approved, Site improvements

#5617 Removing external links from Community Resources
  community/resources/resources.md
  guides/v2.2/config-guide/deployment/pipeline/index.md
  guides/v2.2/config-guide/deployment/single-machine.md
Labels: Progress: approved, Site improvements

#5619 Merge Q4-integration into develop
  _data/toc/graphql.yml
  _includes/config/consumers.md
  _includes/graphql/cart-object.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-lock.md
  guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
  guides/v2.3/graphql/caching.md
  guides/v2.3/graphql/custom-filters.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/mutations/set-payment-place-order.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries/cart.md
  guides/v2.3/graphql/queries/category-list.md
  guides/v2.3/graphql/queries/category.md
  guides/v2.3/graphql/queries/cms-page.md
  guides/v2.3/graphql/queries/custom-attribute-metadata.md
  guides/v2.3/graphql/queries/index.md
  guides/v2.3/graphql/queries/products-234.md
  guides/v2.3/graphql/queries/products.md
  guides/v2.3/graphql/queries/store-config.md
  guides/v2.3/graphql/queries/url-resolver.md
  guides/v2.3/graphql/tutorials/checkout/checkout-payment-method.md
  guides/v2.3/install-gde/install/cli/install-cli-install.md
  guides/v2.3/install-gde/install/cli/install-cli-subcommands-consumers.md
Labels: Progress: approved, internal-dev

#5566 Fix wrong default values for cron_consumers_runner
  guides/v2.2/config-guide/mq/manage-message-queues.md
  guides/v2.3/config-guide/mq/manage-message-queues.md
Labels: 2.x, Partner: Trezo, Progress: review, Technical, partners-contribution

#5620 Fixed list styles (MD004) - Group 2
  guides/v2.2/coding-standards/docblock-standard-general.md
  guides/v2.2/config-guide/bootstrap/magento-bootstrap.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/config-guide/log/log-magento.md
  guides/v2.2/config-guide/multi-site/ms_nginx.md
  guides/v2.2/frontend-dev-guide/conventions.md
  guides/v2.2/frontend-dev-guide/templates/template-email.md
  guides/v2.2/howdoi/checkout/checkout_new_step.md
  guides/v2.2/install-gde/trouble/php/tshoot_70pct.md
  guides/v2.2/install-gde/trouble/php/tshoot_opcache.md
  guides/v2.3/config-guide/bk-config-guide.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-method.md
  guides/v2.3/install-gde/install-quick-ref.md
Labels: Editorial, Progress: approved, internal-dev

#5622 Updated information related to reward points for Issue Triage activities
  _includes/contributor/rewards.md
Labels: 2.3.x, Progress: changes requested, Technical, internal-dev

#5623 Update data for Packages
  _data/codebase/v2_2/cloud/composer_lock.json
  _data/codebase/v2_2/commerce/composer_lock.json
  _data/codebase/v2_2/open-source/composer_lock.json
  _data/codebase/v2_3/cloud/composer_lock.json
  _data/codebase/v2_3/commerce/composer_lock.json
  _data/codebase/v2_3/open-source/composer_lock.json
Labels: 2.2.10, 2.3.3, Major update, Progress: approved

#5626 Fixed list styles (MD004) - Group 3
  .github/CONTRIBUTING.md
  .github/MAINTAINER_GUIDELINES.md
  _includes/cloud/patch.md
  guides/v2.2/cloud/before/before-workspace.md
  guides/v2.2/cloud/cdn/cloud-vcl-custom-snippets.md
  guides/v2.2/cloud/cdn/trouble-fastly.md
  guides/v2.2/config-guide/bk-config-guide.md
  guides/v2.2/contributor-guide/backward-compatible-development/index.md
  guides/v2.2/install-gde/install-quick-ref.md
  guides/v2.2/install-gde/prereq/nginx.md
  guides/v2.2/mrg/ce/Signifyd.md
  guides/v2.2/mrg/ee/CatalogStaging.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
Labels: Editorial, Progress: approved, internal-dev

#5612 Amazon 3.0.0 Release Notes
  _data/compatibility.yml
  extensions/amazon-sales/release-notes/index.md
  release/index.md
Labels: 3.0.0 Amazon Sales Channel, Major update, Progress: review

#5625 Security-only patch description for release notes (10/8/2019)
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  guides/v2.3/release-notes/bk-release-notes.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: 2.3.x, Progress: changes requested, Technical

#5627 Markdown linting: Fix MD005 errors and enable rule
  .github/CONTRIBUTING.md
  .github/MAINTAINER_GUIDELINES.md
  _checks/styles/style-rules-prod
  _includes/cloud/patch.md
  guides/v2.2/cloud/before/before-workspace.md
  guides/v2.2/cloud/cdn/cloud-vcl-custom-snippets.md
  guides/v2.2/cloud/cdn/trouble-fastly.md
  guides/v2.2/coding-standards/docblock-standard-general.md
  guides/v2.2/config-guide/bk-config-guide.md
  guides/v2.2/config-guide/bootstrap/magento-bootstrap.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/config-guide/log/log-magento.md
  guides/v2.2/config-guide/multi-site/ms_nginx.md
  guides/v2.2/contributor-guide/backward-compatible-development/index.md
  guides/v2.2/frontend-dev-guide/conventions.md
  guides/v2.2/frontend-dev-guide/templates/template-email.md
  guides/v2.2/howdoi/checkout/checkout_new_step.md
  guides/v2.2/install-gde/install-quick-ref.md
  guides/v2.2/install-gde/prereq/nginx.md
  guides/v2.2/install-gde/trouble/php/tshoot_70pct.md
  guides/v2.2/install-gde/trouble/php/tshoot_opcache.md
  guides/v2.2/javascript-dev-guide/javascript/js_init.md
  guides/v2.2/javascript-dev-guide/javascript/js_logger.md
  guides/v2.2/marketplace/eqp/packages.md
  guides/v2.2/mrg/ce/Signifyd.md
  guides/v2.2/mrg/ee/CatalogStaging.md
  guides/v2.2/mtf/create_test/create_new_test.md
  guides/v2.2/mtf/create_test/new_test.md
  guides/v2.2/mtf/features/isolation.md
  guides/v2.2/mtf/features/test_suite.md
  guides/v2.2/mtf/mtf_entities/mtf_fixture.md
  guides/v2.2/payments-integrations/base-integration/facade-configuration.md
  guides/v2.2/payments-integrations/payment-gateway/payment-gateway-intro.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
  guides/v2.2/rest/tutorials/configurable-product/create-personalization-option.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  guides/v2.3/config-guide/bk-config-guide.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-method.md
  guides/v2.3/install-gde/install-quick-ref.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/create-personalization-option.md
Labels: Editorial, Progress: approved, internal-dev

#5424 Adding a new topic related to custom widgets
  _data/toc/extension-best-practices.yml
  common/images/ext-best-practices/custom-widget-options.png
  common/images/ext-best-practices/custom-widget-result.png
  common/images/ext-best-practices/custom-widget.png
  guides/v2.2/ext-best-practices/tutorials/custom-widget.md
  guides/v2.3/ext-best-practices/tutorials/custom-widget.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5433 Adding additional info on how to pass the parameters from a custom Ro…
  guides/v2.2/extension-dev-guide/routing.md
  guides/v2.3/extension-dev-guide/routing.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5576 Consolidate Cloud project upgrade topics
  guides/v2.2/cloud/project/project-upgrade.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
Labels: Progress: review, Site improvements, internal-dev

#5638 Markdown linting: Fix MD006 errors and enable rule
  _checks/styles/style-rules-prod
  guides/v2.2/advanced-reporting/modules.md
  guides/v2.2/ext-best-practices/extension-coding/working-with-arch-bp.md
  guides/v2.2/howdoi/checkout/checkout_overview.md
  guides/v2.2/javascript-dev-guide/conventions_js.md
  guides/v2.2/mrg/ee/CatalogImportExportStaging.md
  guides/v2.2/mtf/create_test/create_new_test.md
  guides/v2.2/mtf/features/modularity.md
  guides/v2.2/mtf/mtf_entities/mtf_typified-element.md
  guides/v2.2/payments-integrations/base-integration/get-payment-info.md
  guides/v2.2/payments-integrations/payment-gateway/error-code-mapper.md
  guides/v2.2/payments-integrations/vault/payment-token.md
  guides/v2.2/rest/generate-local.md
  guides/v2.2/rest/operation-status-search.md
  guides/v2.2/ui_comp_guide/components/ui-treemassactions.md
  guides/v2.3/payments-integrations/payment-gateway/error-code-mapper.md
  guides/v2.3/payments-integrations/vault/payment-token.md
  guides/v2.3/rest/generate-local.md
  guides/v2.3/rest/operation-status-search.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/create-personalization-option.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/define-config-product-options.md
Labels: Editorial, Progress: review, internal-dev

#5637 Adds new topics to MFTF TOC
  _data/toc/mftf.yml
Labels: New topic, Progress: approved

#5584 Replaced v2.3 files with symlink to v2.2 file
  guides/v2.2/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/live/live-sanity-check.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.3/cloud/live/go-live-checklist.md
  guides/v2.3/cloud/live/live-sanity-check.md
Labels: 2.x, Editorial, Progress: review, internal-dev

#5643 Fixed list styles (MD007) - Group 1 of 3
  _includes/contributor/rewards.md
  _includes/php-dev/component-root-2.3.md
  _includes/php-dev/component-root.md
  _includes/vendor/types-def.md
  _videos/fundamentals/add-new-product-attribute.md
  community/resources/multi-repo-docs.md
  extensions/amazon-sales/index.md
  guides/v2.2/architecture/archi_perspectives/domain_layer.md
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/architecture/pro-architecture.md
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-development-debug.md
  guides/v2.2/cloud/docker/docker-development.md
  guides/v2.2/cloud/env/variables-post-deploy.md
  guides/v2.2/cloud/integrations/github-integration.md
  guides/v2.2/cloud/live/paypal-onboarding.md
  guides/v2.2/cloud/live/sens-data-over.md
  guides/v2.2/cloud/release-notes/cloud-release-archive.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/coding-standards/code-standard-jquery-widgets.md
  guides/v2.2/comp-mgr/cli/cli-upgrade.md
  guides/v2.2/comp-mgr/patching.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: Editorial, Progress: approved, internal-dev

#5641 MAGEDOC-4024 New Cloud topic for managing disk space
  _data/toc/cloud-guide.yml
  guides/v2.2/cloud/project/manage-disk-space.md
  guides/v2.3/cloud/project/manage-disk-space.md
Labels: 2.x, New topic, Progress: approved, internal-dev

#5651 Added changelog to Migration TOC
  _data/toc/migration-guide.yml
Labels: Progress: approved, Site improvements

#5648 Fixed formatting
  guides/v2.2/architecture/archi_perspectives/service_layer.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#5615 Small addition to clarify text
  guides/v2.2/migration/migration-migrate-delta.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#5652 Small corrections to Magento 2.3.3 release notes
  _includes/release-notes/engcomm-2-3-3-issues.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: 2.3.3, Editorial, Progress: approved, internal-dev

#5649 fixed MFTF version number
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Progress: approved, Technical

#5644 Fixed list styles (MD007) - Group 2 of 3
  guides/v2.2/config-guide/cache.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
  guides/v2.2/config-guide/multi-master/multi-master_manual.md
  guides/v2.2/config-guide/multi-site/ms_apache.md
  guides/v2.2/design-styleguide/content-formats/content-formats.md
  guides/v2.2/design-styleguide/content-voice-tone/content-voice-tone.md
  guides/v2.2/ext-best-practices/admin/feedback-placement-and-design.md
  guides/v2.2/extension-dev-guide/build/composer-integration.md
  guides/v2.2/extension-dev-guide/object-manager.md
  guides/v2.2/extension-dev-guide/service-contracts/service-to-web-service.md
  guides/v2.2/frontend-dev-guide/cache_for_frontdevs.md
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_js.md
  guides/v2.2/get-started/authentication/gs-authentication-oauth.md
  guides/v2.2/install-gde/basics/basics_docroot.md
  guides/v2.2/install-gde/system-requirements-tech.md
  guides/v2.2/install-gde/trouble/php/tshoot_session.md
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
  guides/v2.3/install-gde/prereq/optional.md
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: Editorial, Progress: approved, internal-dev

#5654 Small changes
  .github/CONTRIBUTING.md
  _includes/install/web/install-web_2-db.md
  _includes/release-notes/engcomm-2-3-3-issues.md
  guides/v2.2/advanced-reporting/overview.md
  guides/v2.2/architecture/archi_perspectives/service_layer.md
  guides/v2.2/architecture/frontend_custom_strategies.md
  guides/v2.2/architecture/storefront_customization.md
  guides/v2.2/cloud/reference/discover-deploy.md
  guides/v2.2/install-gde/basics/basics_software.md
  guides/v2.2/install-gde/system-requirements-tech.md
  guides/v2.2/javascript-dev-guide/javascript/custom_js.md
  guides/v2.2/migration/migration-migrate-delta.md
  guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/install-gde/system-requirements-tech.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  guides/v2.3/security/two-factor-authentication.md
Labels: Progress: approved

#5653 GraphQL: Update Braintree attribute descriptions
  guides/v2.3/graphql/mutations/create-braintree-client-token.md
  guides/v2.3/graphql/mutations/set-payment-place-order.md
  guides/v2.3/graphql/payment-methods/braintree.md
Labels: 2.3.3, Community, Progress: approved, Technical, internal-dev

#5624 Updated What's New with changes since October 1.
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: changes requested, internal-dev

#5659 magento/devdocs#: Cloud. Upgrade to 2.3.3 via composer
  guides/v2.3/cloud/project/project-upgrade.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5517 Removed mcrypt from extension and noted use of sodium
  guides/v2.3/performance-best-practices/software.md
Labels: 2.3.x, Progress: review, Technical

#5481 MAGETWO-63395 Add code sample for dynamic content
  guides/v2.2/javascript-dev-guide/javascript/js_init.md
Labels: 2.2.x, 2.3.x, Major update, Progress: approved

#5660 GraphQL: Update attribute descriptions for 2.3.4
  _includes/graphql/cart-object.md
  _includes/graphql/customer-address-input.md
  _includes/graphql/customer-address-output.md
  _includes/graphql/customer-input.md
  _includes/graphql/customer-output.md
  guides/v2.3/graphql/mutations/create-customer-address.md
  guides/v2.3/graphql/mutations/set-shipping-address.md
  guides/v2.3/graphql/queries/cart.md
  guides/v2.3/graphql/queries/customer-orders.md
Labels: 2.3.4, Community, Progress: approved, Technical, internal-dev

#5503 Add the FolderTree widget documentation
  _data/toc/javascript-developer-guide.yml
  common/images/widget/folder-tree-widget-media-example.png
  common/images/widget/folder-tree-widget.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget-folder-tree.md
  guides/v2.3/javascript-dev-guide/widgets/widget-folder-tree.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: changes requested, partners-contribution

#5635 Update declarative schema info
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: Community Insider: Magecom, Progress: review, community-insider-contribution

#5663 Clarified method for setting CRYPT_KEY
  guides/v2.2/cloud/env/variables-deploy.md
Labels: 2.x, Progress: changes requested, Technical, internal-dev

#5664 GraphQL: Update PayPal output object names
  guides/v2.3/graphql/mutations/create-payflow-pro-token.md
  guides/v2.3/graphql/mutations/create-paypal-express-token.md
Labels: 2.3.4, Community, Progress: approved, Technical, internal-dev

#5667 Magento 2.3.3 release note discussion of Elasticsearch pagination patch
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: Progress: approved

#5665 Fixed ordered list prefix (MD029) - Group 1
  guides/v2.2/rest/tutorials/orders/order-create-customer.md
  guides/v2.2/rest/tutorials/orders/order-create-order.md
  guides/v2.2/test/integration/annotations/magento-app-area.md
  guides/v2.2/test/integration/annotations/magento-cache.md
  guides/v2.2/test/integration/annotations/magento-config-fixture.md
  guides/v2.2/test/integration/annotations/magento-data-fixture.md
  guides/v2.2/test/js/jasmine.md
  guides/v2.2/test/js/test_js-unit.md
  guides/v2.2/test/unit/unit_test_execution_phpstorm.md
  guides/v2.2/ui_comp_guide/bk-ui_comps.md
  guides/v2.2/ui_comp_guide/components/ui-filters.md
  guides/v2.2/ui_comp_guide/components/ui-form.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_config_flow_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_template_literals.md
  guides/v2.2/ui_comp_guide/howto/new_component_declaration.md
  guides/v2.2/ui_comp_guide/howto/price_rendering.md
  guides/v2.2/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_js.md
  guides/v2.3/rest/tutorials/inventory/configure-environment.md
  guides/v2.3/rest/tutorials/inventory/create-customer.md
  guides/v2.3/rest/tutorials/inventory/create-invoice.md
  guides/v2.3/rest/tutorials/inventory/create-order.md
  guides/v2.3/rest/tutorials/inventory/create-shipment.md
  guides/v2.3/rest/tutorials/inventory/run-ssa.md
  guides/v2.3/test/integration/annotations/magento-config-fixture.md
  guides/v2.3/test/integration/annotations/magento-data-fixture.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
  guides/v2.3/ui_comp_guide/components/ui-form.md
  guides/v2.3/ui_comp_guide/components/ui-wysiwyg.md
  guides/v2.3/ui_comp_guide/howto/update-url-type.md
Labels: Editorial, Progress: review

#5666 Fixed ordered list prefix (MD029) - Group 2
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.2/release-notes/backward-incompatible-changes/reference.md
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/backward-incompatible-changes/reference.md
Labels: Editorial, Progress: approved

#5668 Fixed ordered list prefix (MD029) - Group 3
  guides/v2.2/pattern-library/containers/slideouts-modals-overlays/slideouts-modals-overalys.md
  guides/v2.2/pattern-library/controls/Expandable_Sections/expand-collapse.md
  guides/v2.2/pattern-library/controls/button-bar/button-bar.md
  guides/v2.2/pattern-library/displaying-data/tree/tree.md
  guides/v2.2/pattern-library/feedbackToUser/progressIndicator/progressIndicator.md
  guides/v2.2/pattern-library/getting-user-input/image_uploader/image_uploader.md
  guides/v2.2/pattern-library/graphics/iconography/iconography.md
  guides/v2.2/pattern-library/navigation/links/links.md
  guides/v2.2/pattern-library/templates/sign-in-form/sign-in-form.md
  guides/v2.2/payments-integrations/base-integration/integration-intro.md
  guides/v2.2/payments-integrations/signifyd/signifyd.md
  guides/v2.2/payments-integrations/vault/admin-integration.md
  guides/v2.2/payments-integrations/vault/enabler.md
  guides/v2.2/payments-integrations/vault/vault-intro.md
Labels: Editorial, Progress: review

#5670 Fixed ordered list prefix (MD029) - Group 5
  guides/v2.2/install-gde/basics/basics_docroot.md
  guides/v2.2/install-gde/install-quick-ref.md
  guides/v2.2/install-gde/install/cli/dev_add-update.md
  guides/v2.2/install-gde/install/hosted/hosted_start_db.md
  guides/v2.2/install-gde/install/hosted/hosted_start_php.md
  guides/v2.2/install-gde/install/prepare-install.md
  guides/v2.2/install-gde/prereq/install-rabbitmq.md
  guides/v2.2/install-gde/prereq/optional.md
  guides/v2.2/install-gde/trouble/php/tshoot_70pct.md
  guides/v2.2/install-gde/trouble/php/tshoot_opcache.md
  guides/v2.2/install-gde/trouble/php/tshoot_session.md
  guides/v2.2/install-gde/tutorials/change-docroot-to-pub.md
  guides/v2.2/javascript-dev-guide/javascript/custom_js.md
  guides/v2.2/javascript-dev-guide/javascript/js-resources.md
  guides/v2.2/javascript-dev-guide/javascript/js_debug.md
  guides/v2.2/javascript-dev-guide/javascript/js_practice.md
  guides/v2.2/javascript-dev-guide/widgets/widget_accordion.md
  guides/v2.3/install-gde/install-quick-ref.md
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
  guides/v2.3/install-gde/prereq/nginx.md
  guides/v2.3/install-gde/prereq/zip_install.md
  guides/v2.3/install-gde/tutorials/change-docroot-to-pub.md
  guides/v2.3/inventory/reservations.md
Labels: Editorial, Progress: approved

#5669 Fixed ordered list prefix (MD029) - Group 4
  guides/v2.2/marketplace/eqp/auth.md
  guides/v2.2/marketplace/eqp/packages.md
  guides/v2.2/migration/migration-manually.md
  guides/v2.2/migration/migration-migrate-data.md
  guides/v2.2/migration/migration-migrate-settings.md
  guides/v2.2/migration/migration-migrate.md
  guides/v2.2/migration/migration-overview-how.md
  guides/v2.2/migration/migration-plan.md
  guides/v2.2/migration/migration-tool-install.md
  guides/v2.2/migration/migration-tool-internal-spec.md
  guides/v2.2/migration/migration-tool-upgrade.md
  guides/v2.2/migration/migration-tool.md
  guides/v2.2/mrg/ee/Staging.md
  guides/v2.2/mtf/create_test/create_new_test.md
  guides/v2.2/mtf/features/parallel_execution.md
  guides/v2.2/mtf/features/reporting.md
  guides/v2.2/mtf/features/webdriver.md
  guides/v2.2/mtf/mtf_entities/mtf_block.md
  guides/v2.2/mtf/mtf_entities/mtf_page.md
  guides/v2.2/mtf/mtf_installation.md
  guides/v2.2/mtf/mtf_quickstart/mtf_quickstart_magento.md
  guides/v2.3/migration/migration-migrate-settings.md
Labels: Editorial, Progress: review

#5655 Fixed ordering of points
  guides/v2.2/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, partners-contribution, small changes

#5658 magento/devdocs#: Fix label for product-enterprise-edition
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution, small changes

#5661 MAGEDOC-4115 Fixed infobox code
  guides/v2.2/config-guide/cli/logging.md
  guides/v2.3/config-guide/cli/logging.md
Labels: 2.2.x, Editorial, Progress: approved

#5675 Fixed inconsistent code formatting
  guides/v2.2/frontend-dev-guide/tools/using_grunt.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5567 Update identity-class.md
  guides/v2.3/graphql/develop/identity-class.md
Labels: 2.3.x, Progress: approved, Technical

#5519 Added proper space on function. Updated syntax for build.js file.
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: 2.3.x, Progress: approved, Technical, Waiting for response

#5565 Resolved issue #5179
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: acceptance testing, Technical, partners-contribution

#5677 Fixed ordered list prefix (MD029) - Group 6
  guides/v2.2/howdoi/checkout/checkout-add-custom-carrier.md
  guides/v2.2/howdoi/checkout/checkout_address.md
  guides/v2.2/howdoi/checkout/checkout_carrier.md
  guides/v2.2/howdoi/checkout/checkout_custom_checkbox.md
  guides/v2.2/howdoi/checkout/checkout_customize.md
  guides/v2.2/howdoi/checkout/checkout_edit_form.md
  guides/v2.2/howdoi/checkout/checkout_form.md
  guides/v2.2/howdoi/checkout/checkout_new_field.md
  guides/v2.2/howdoi/checkout/checkout_new_step.md
  guides/v2.2/howdoi/checkout/checkout_order.md
  guides/v2.2/howdoi/checkout/checkout_payment.md
  guides/v2.2/howdoi/checkout/checkout_shipping_methods.md
  guides/v2.2/howdoi/customize-form-configuration.md
  guides/v2.2/howdoi/customize-modifier-class.md
  guides/v2.3/howdoi/checkout/checkout-add-custom-carrier.md
Labels: Editorial, Progress: approved

#5678 Fixed ordered list prefix (MD029) - Group 7
  guides/v2.2/get-started/authentication/gs-authentication-oauth.md
  guides/v2.2/get-started/authentication/gs-authentication-token.md
  guides/v2.2/get-started/create-integration.md
  guides/v2.2/get-started/gs-web-api-request.md
  guides/v2.3/get-started/create-integration.md
  guides/v2.3/graphql/functional-testing.md
  guides/v2.3/graphql/payment-methods/authorize-net.md
  guides/v2.3/graphql/payment-methods/braintree-vault.md
  guides/v2.3/graphql/tutorials/checkout/checkout-add-product-to-cart.md
  guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
  guides/v2.3/graphql/tutorials/checkout/checkout-payment-method.md
  guides/v2.3/graphql/tutorials/checkout/checkout-place-order.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-method.md
Labels: Editorial, Progress: approved

#5679 Fixed ordered list prefix (MD029) - Group 8
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_approach.md
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_mode.md
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_mobile.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_practice.md
  guides/v2.2/frontend-dev-guide/templates/template-email.md
  guides/v2.2/frontend-dev-guide/templates/template-walkthrough.md
  guides/v2.2/frontend-dev-guide/themes/admin_theme_apply.md
  guides/v2.2/frontend-dev-guide/themes/admin_theme_create.md
  guides/v2.2/frontend-dev-guide/themes/debug-theme.md
  guides/v2.2/frontend-dev-guide/themes/favicon.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-inherit.md
  guides/v2.2/frontend-dev-guide/themes/theme-install.md
  guides/v2.2/frontend-dev-guide/themes/theme-uninstall.md
  guides/v2.2/frontend-dev-guide/themes/theme-workflow.md
  guides/v2.2/frontend-dev-guide/translations/translate_theory.md
  guides/v2.3/frontend-dev-guide/themes/admin_theme_create.md
Labels: Editorial, Progress: approved

#5680 Fixed ordered list prefix (MD029) - Group 9
  guides/v2.2/ext-best-practices/extension-coding/example-module-adminpage.md
  guides/v2.2/ext-best-practices/tutorials/serialized-to-json-data-upgrade.md
  guides/v2.2/extension-dev-guide/build/di-xml-file.md
  guides/v2.2/extension-dev-guide/build/enable-module.md
  guides/v2.2/extension-dev-guide/build/module-load-order.md
  guides/v2.2/extension-dev-guide/cache/page-caching/private-content.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
  guides/v2.2/extension-dev-guide/configuration/importers.md
  guides/v2.2/extension-dev-guide/package/package_module.md
  guides/v2.2/extension-dev-guide/prepare/dev-summary.md
  guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
  guides/v2.3/extension-dev-guide/indexing.md
  guides/v2.3/extension-dev-guide/message-queues/message-queues.md
  guides/v2.3/extension-dev-guide/package/package_module.md
  guides/v2.3/extension-dev-guide/versioning/dependencies.md
Labels: Editorial, Progress: approved

#5682 Fixed ordered list prefix (MD029) - Group 11
  guides/v2.2/config-guide/multi-site/ms_nginx.md
  guides/v2.2/config-guide/multi-site/ms_websites.md
  guides/v2.2/config-guide/prod/config-reference-var-name.md
  guides/v2.2/config-guide/varnish/config-varnish-advanced.md
  guides/v2.2/config-guide/varnish/config-varnish-configure.md
  guides/v2.2/config-guide/varnish/config-varnish-magento.md
  guides/v2.2/config-guide/varnish/config-varnish.md
  guides/v2.2/config-guide/varnish/tshoot-varnish-503.md
Labels: Editorial, Progress: approved

#5681 Fixed ordered list prefix (MD029) - Group 10
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
  guides/v2.2/config-guide/cli/config-cli-subcommands.md
  guides/v2.2/config-guide/cron/custom-cron-tut.md
  guides/v2.2/config-guide/deployment/pipeline/example/cli.md
  guides/v2.2/config-guide/deployment/pipeline/technical-details.md
  guides/v2.2/config-guide/deployment/single-machine.md
  guides/v2.2/config-guide/memcache/memcache_magento.md
  guides/v2.2/config-guide/memcache/memcache_ubuntu.md
  guides/v2.2/config-guide/multi-master/multi-master_manual.md
  guides/v2.2/config-guide/multi-master/multi-master_masterdb.md
  guides/v2.2/config-guide/multi-site/ms_apache.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.3/config-guide/cli/logging.md
  guides/v2.3/config-guide/elasticsearch/es-config-apache.md
Labels: Progress: review

#5640 Generated backward incompatible changes reference for Magento 2.2.10
  _includes/backward-incompatible-changes/commerce/2.2.9-2.2.10.md
  _includes/backward-incompatible-changes/open-source/2.2.9-2.2.10.md
  guides/v2.2/release-notes/backward-incompatible-changes/reference.md
Labels: 2.2.10, Major update, Progress: approved

#5690 Fix links
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.3/cloud/project/project-upgrade.md
  guides/v2.3/cloud/project/projects.md
  guides/v2.3/graphql/product/grouped-product.md
Labels: Editorial, Progress: approved, internal-dev

#5686 Update backward incompatible changes docs for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.2-2.3.3.md
  _includes/backward-incompatible-changes/open-source/2.3.2-2.3.3.md
  guides/v2.3/release-notes/backward-incompatible-changes/reference.md
Labels: 2.3.3, Major update, Progress: approved

#5687 Fixed ordered list prefix (MD029) - Group 13
  guides/v2.2/coding-standards/docblock-standard-general.md
  guides/v2.2/coding-standards/technical-vision/webapi.md
  guides/v2.2/comp-mgr/marketplace/marketplace.md
  guides/v2.2/comp-mgr/upgrader/upgrade-main-pg.md
  guides/v2.2/contributor-guide/templates/basic_template.md
  guides/v2.2/design-styleguide/content-voice-tone/content-voice-tone.md
  guides/v2.2/design-styleguide/errors-and-messages/errors-and-messages.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/comp-mgr/cli/upgrade-with-plugin.md
  guides/v2.3/comp-mgr/cli/upgrade-with-script.md
  guides/v2.3/contributor-guide/contributing.md
Labels: Progress: approved

#5691 Fixed ordered list prefix (MD029) - Group 16
  .github/ISSUE_TEMPLATE/BUG.md
  _checks/styles/style-rules-prod
  _includes/cloud/backup-db.md
  _includes/cloud/enable-ssh.md
  _includes/cloud/log-in-db.md
  _includes/cloud/new-project-from-template.md
  _includes/cloud/patch.md
  guides/v2.2/cloud/cdn/fastly-vcl-blacklist.md
  guides/v2.2/cloud/configure/configure-best-practices.md
  guides/v2.2/cloud/configure/setup-b2b.md
  guides/v2.2/cloud/howtos/debug.md
  guides/v2.2/cloud/live/launch-steps.md
  guides/v2.2/cloud/live/live.md
  guides/v2.2/cloud/live/paypal-onboarding.md
  guides/v2.2/cloud/live/sens-data-over.md
  guides/v2.2/cloud/onboarding/onboarding-tasks.md
  guides/v2.2/cloud/project/project-webint-branch.md
  guides/v2.2/cloud/setup/first-time-setup-import-prepare.md
  guides/v2.2/cloud/trouble/trouble-crypt-key-variable.md
  guides/v2.2/cloud/trouble/trouble-error-html-minification.md
Labels: Editorial, Progress: approved

#5684 Fixed ordered list prefix (MD029) - Group 12
  guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-cron.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.2/config-guide/cli/logging.md
  guides/v2.2/config-guide/elasticsearch/es-config-stopwords.md
  guides/v2.2/config-guide/elasticsearch/es-overview.md
  guides/v2.2/config-guide/memcache/memcache_centos.md
  guides/v2.2/config-guide/multi-master/multi-master_manual.md
Labels: Editorial, Progress: approved

#5688 Fixed ordered list prefix (MD029) - Group 14
  _videos/fundamentals/add-a-javascript-module.md
  _videos/fundamentals/add-a-new-table-to-database.md
  _videos/fundamentals/add-new-product-attribute.md
  _videos/fundamentals/create-a-new-module.md
  _videos/fundamentals/create-a-new-page.md
  guides/v2.2/advanced-reporting/overview.md
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.md
  guides/v2.3/architecture/archi_perspectives/webapi-vision.md
Labels: Editorial, Progress: approved

#5656 magento/devdocs#: Fix links in How Magento implements indexing
  guides/v2.2/extension-dev-guide/indexing.md
  guides/v2.3/extension-dev-guide/indexing.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#5699 Email template patch information for Magento 2.3.3 release notes
  _includes/release-notes/engcomm-2-3-3-issues.md
  _includes/release-notes/engcomm-2-3-3-partner.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: Progress: approved

#5672 magento/devdocs#: Docs: Create topic for addDownloadableProductsToCart mutation
  _data/toc/graphql.yml
  guides/v2.3/graphql/mutations/add-downloadable-products.md
Labels: 2.3.x, New topic, Partner: Atwix, Progress: review, partners-contribution

#5696 XML code block designation on page is causing issues with display/ren…
  guides/v2.2/cloud/trouble/trouble_ce-creds.md
Labels: Editorial, Progress: acceptance testing, small changes

#5695 Changes array syntax `[]` instead of long `array()`.
  guides/v2.2/extension-dev-guide/test/test_object-mgr.md
Labels: 2.2.x, 2.3.x, Progress: approved, small changes

#5633 magento/devdocs#: Describe changeCustomerPassword mutation errors
  guides/v2.3/graphql/mutations/change-customer-password.md
Labels: 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#5708 Added page-builder-types to gitignore file
  .gitignore
Labels: 2.3.x, Progress: approved, internal-dev

#5716 Update variables-deploy.md
  guides/v2.2/cloud/env/variables-deploy.md
Labels: Editorial, Partner: Rave Digital, partners-contribution, small changes

#5628 magento/devdocs#: Add a custom payment method to checkout. Fix Step 4
  guides/v2.2/howdoi/checkout/checkout_payment.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#5707 magento/devdocs#5249: Markdown linting: Spaces after list markers (MD030). Part 01
  _includes/cache/page-cache-checklists.md
  _includes/cache/page-cache-overview.md
  _includes/cloud/admin-ui-login-step.md
  _includes/cloud/cloud-fastly-manage-vcl-from-admin.md
  _includes/cloud/data-collection.md
  _includes/cloud/enable-ssh.md
  _includes/cloud/patch.md
  _includes/cloud/sens-data-create-config-local.md
  _includes/comp-man/checklist.md
  _includes/comp-man/checklist_2.2.md
  _includes/comp-man/dependency.md
  _includes/comp-man/readiness-check.md
  _includes/config-guide/custom-logger-handler-examples.md
  _includes/config/es-elasticsearch-magento.md
  _includes/config/install-java.md
  _includes/config/install-java8.md
Labels: Partner: Atwix, Progress: changes requested, Special achievement, partners-contribution

#5718 GraphQL: Move CategoryInterface out of category query
  _data/toc/graphql.yml
  guides/v2.3/graphql/product/category-interface.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries/category.md
Labels: 2.3.x, New topic, Progress: approved, internal-dev

#5719 Update auth-tokens-get.md
  _includes/install/auth-tokens-get.md
Labels: Partner: Rave Digital, Progress: changes requested, Technical, partners-contribution, small changes

#5722 Fix syntax for paths to run Actions on
  .github/workflows/main.yml
Labels: Progress: approved

#5720 Refactors MD030 issues
  guides/v2.2/ui_comp_guide/best-practices/semantic_config.md
  guides/v2.2/ui_comp_guide/components/ui-actionscolumn.md
  guides/v2.2/ui_comp_guide/components/ui-bookmarks.md
  guides/v2.2/ui_comp_guide/components/ui-button.md
  guides/v2.2/ui_comp_guide/components/ui-column.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_data_source.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_uilayout_concept.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
  guides/v2.3/ui_comp_guide/components/image-uploader/index.md
  guides/v2.3/ui_comp_guide/components/ui-colorpicker.md
  guides/v2.3/ui_comp_guide/components/wysiwyg/extension-points/index.md
  redoc/2.3/index.md
  release/policy/index.md
  system-requirements.md
Labels: Partner: Zilker Technology, Special achievement, partners-contribution

#5723 magento/devdocs#5249: Markdown linting: Spaces after list markers (MD030). Folder - b2b
  guides/v2.2/b2b/bk-b2b.md
  guides/v2.2/b2b/company-object.md
  guides/v2.2/b2b/company-structures.md
  guides/v2.2/b2b/company-users.md
  guides/v2.2/b2b/company.md
  guides/v2.2/b2b/credit-manage.md
  guides/v2.2/b2b/negotiable-checkout.md
  guides/v2.2/b2b/negotiable-manage.md
  guides/v2.2/b2b/negotiable-order-workflow.md
  guides/v2.2/b2b/negotiable-quote.md
  guides/v2.2/b2b/negotiable-update.md
  guides/v2.2/b2b/roles.md
  guides/v2.2/b2b/shared-cat-company.md
  guides/v2.2/b2b/shared-cat-manage.md
  guides/v2.2/b2b/shared-cat-product-assign.md
  guides/v2.2/b2b/shared-catalog.md
Labels: Partner: Atwix, Progress: approved, Special achievement, partners-contribution

#5724 Markdown linting: Spaces after list markers (MD030)
  extensions/amazon-sales/index.md
  extensions/amazon-sales/release-notes/index.md
  extensions/b2b/index.md
  extensions/index.md
  extensions/install/index.md
  extensions/inventory-management/index.md
  guides/v2.2/advanced-reporting/report-xml.md
  guides/v2.2/architecture/archi_perspectives/ABasics_intro.md
  guides/v2.2/architecture/archi_perspectives/ALayers_intro.md
  guides/v2.2/architecture/archi_perspectives/components/AComponents.md
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_and_areas.md
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_intro.md
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_relationships.md
  guides/v2.2/architecture/archi_perspectives/framework.md
  guides/v2.2/architecture/archi_perspectives/persist_layer.md
  guides/v2.3/architecture/archi_perspectives/persist_layer.md
Labels: Partner: Atwix, Progress: review, Special achievement, partners-contribution

#5727 Markdown linting: Spaces after list markers (MD030)
  guides/v2.2/architecture/archi_perspectives/present_layer.md
  guides/v2.2/architecture/archi_perspectives/service_layer.md
  guides/v2.2/architecture/extensibility.md
  guides/v2.2/architecture/frontend_custom_strategies.md
  guides/v2.2/architecture/gdpr/magento-1x.md
  guides/v2.2/architecture/gdpr/magento-2x.md
  guides/v2.2/architecture/global_extensibility_features.md
  guides/v2.2/architecture/security_intro.md
  guides/v2.2/architecture/tech-stack.md
  guides/v2.3/architecture/archi_perspectives/present_layer.md
  guides/v2.3/architecture/global_extensibility_features.md
  guides/v2.3/architecture/tech-stack.md
Labels: Partner: Atwix, Special achievement, partners-contribution

#5731 magento/devdocs#5249: Markdown linting: Spaces after list markers (MD030). Folder - cloud. Part 04.
  guides/v2.2/cloud/live/stage-prod-migrate.md
  guides/v2.2/cloud/onboarding/onboarding-portal.md
  guides/v2.2/cloud/project/ece-tools-update.md
  guides/v2.2/cloud/project/ece-tools-upgrade-project.md
  guides/v2.2/cloud/project/new-relic.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/project/project-conf-files_routes.md
  guides/v2.2/cloud/project/project-patch.md
  guides/v2.2/cloud/project/project-routes-more-cache.md
  guides/v2.2/cloud/project/project-routes-more-redir.md
  guides/v2.2/cloud/project/project-webint-basic.md
  guides/v2.2/cloud/project/project-webint-snap.md
  guides/v2.2/cloud/project/projects.md
  guides/v2.2/cloud/reference/cli-ref-topic.md
  guides/v2.2/cloud/reference/discover-deploy.md
Labels: Partner: Atwix, Special achievement, partners-contribution
