Repository magento/devdocs, pull requests merged in 2019-08, with the labels that each got.

#5088 magento/devdocs#: Editorial. Update Magento setup rollback command
  guides/v2.2/install-gde/install/cli/install-cli-backup.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, Waiting for response, partners-contribution, small changes

#5021 Adjusting the modifier by including the required componentType attribute
  guides/v2.2/howdoi/customize-modifier-class.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5084 Migrating urlresolver topic to queries subdir as per Magedoc3977
  _data/toc/graphql.yml
  guides/v2.3/graphql/queries/store-config.md
  guides/v2.3/graphql/queries/url-resolver.md
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/graphql/reference/url-resolver.md
Labels: 2.3.3, Progress: approved, Site improvements, internal-dev

#5046 MAGEDOC-3966 PHP version update
  _data/toc/installation-guide.yml
  _includes/install/trouble/rc_php-version.md
  guides/v2.2/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.2/comp-mgr/trouble/cman/out-of-memory.md
  guides/v2.2/config-guide/deployment/pipeline/build-system.md
  guides/v2.2/install-gde/install-quick-ref.md
  guides/v2.2/install-gde/prereq/apache.md
  guides/v2.2/install-gde/prereq/install-rabbitmq.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.2/install-gde/prereq/mysql_remote.md
  guides/v2.2/install-gde/prereq/nginx.md
  guides/v2.2/install-gde/prereq/optional.md
  guides/v2.2/install-gde/prereq/php-centos.md
  guides/v2.2/install-gde/prereq/php-parent.md
  guides/v2.2/install-gde/prereq/php-settings.md
  guides/v2.2/install-gde/prereq/php-ubuntu.md
  guides/v2.2/install-gde/prereq/prereq-overview.md
  guides/v2.2/install-gde/prereq/security.md
  guides/v2.2/install-gde/system-requirements-tech.md
  guides/v2.2/install-gde/trouble/php/tshoot_pdo.md
  guides/v2.2/install-gde/trouble/php/tshoot_php-date.md
  guides/v2.2/install-gde/trouble/php/tshoot_php-set.md
  guides/v2.2/mtf/mtf_installation.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.3/config-guide/deployment/pipeline/build-system.md
  guides/v2.3/install-gde/install-quick-ref.md
  guides/v2.3/install-gde/prereq/apache.md
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
  guides/v2.3/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/mysql_remote.md
  guides/v2.3/install-gde/prereq/nginx.md
  guides/v2.3/install-gde/prereq/optional.md
  guides/v2.3/install-gde/prereq/php-centos-ubuntu.md
  guides/v2.3/install-gde/prereq/php-parent.md
  guides/v2.3/install-gde/prereq/php-settings.md
  guides/v2.3/install-gde/prereq/prereq-overview.md
  guides/v2.3/install-gde/prereq/security.md
  guides/v2.3/install-gde/system-requirements-tech.md
  guides/v2.3/install-gde/trouble/php/tshoot_pdo.md
  guides/v2.3/mtf/mtf_installation.md
Labels: 2.3.3, Progress: review, Technical

#5108 Disable external link checking
  Docfile.yml
  _config.checks.yml
  _data/main-nav.yml
  guides/v2.2/architecture/archi_perspectives/present_layer.md
  guides/v2.3/inventory/architecture.md
  guides/v2.3/pwa/index.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: Progress: approved, internal-dev

#5091 Information about patch PRODSECBUG 2233
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.2.8, 2.2.x, 2.3.0, 2.3.1, 2.3.x, 2.x, Major update, Progress: approved, internal-dev

#5104 KB migration: Enable Elasticsearch on Cloud
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, internal-dev

#5107 Update PayPal URL descriptions
  _includes/graphql/payment-methods/payflow-link-attributes.md
  guides/v2.3/graphql/payment-methods/payflow-link.md
  guides/v2.3/graphql/payment-methods/payments-advanced.md
  guides/v2.3/graphql/reference/paypal-create-payflow-pro-token.md
Labels: 2.3.3, Progress: approved, Technical, internal-dev

#5094 Corrected errors in Fastly set up topic
  guides/v2.2/cloud/cdn/configure-fastly.md
Labels: 2.2.x, Editorial, Progress: approved, internal-dev

#5048 GraphQL: Update ProductImage data type
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.3, Major update, Progress: approved, internal-dev

#5082 Small changes
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/config-guide/config/config-files.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
  guides/v2.2/extension-dev-guide/versioning/index.md
  guides/v2.2/install-gde/install/cli/install-cli-backup.md
  guides/v2.2/ui_comp_guide/components/ui-bookmarks.md
  guides/v2.2/ui_comp_guide/components/ui-draganddrop.md
  guides/v2.3/coding-standards/code-standard-demarcation.md
  guides/v2.3/config-guide/config/config-files.md
  guides/v2.3/extension-dev-guide/build/create_component.md
  guides/v2.3/extension-dev-guide/versioning/index.md
  guides/v2.3/frontend-dev-guide/templates/template-security.md
Labels: 2.2.x, 2.3.x, Progress: review

#5109 KB migration: Set cache TTL for static files
  _data/toc/cloud-guide.yml
  guides/v2.2/cloud/project/set-cache.md
  guides/v2.3/cloud/project/set-cache.md
Labels: 2.2.x, 2.3.x, New topic, Progress: approved, internal-dev

#5100 Migrating Vault endpoint to new directories as per magedoc3978
  _data/toc/graphql.yml
  _includes/graphql/customer-payment-tokens.md
  guides/v2.3/graphql/mutations/delete-payment-token.md
  guides/v2.3/graphql/queries/customer-payment-tokens.md
  guides/v2.3/graphql/reference/vault.md
Labels: 2.3.3, Progress: approved, Site improvements, internal-dev

#5111 KB migration: Profile DB queries on cloud
  _data/toc/cloud-guide.yml
  guides/v2.2/cloud/project/profile-database-queries.md
  guides/v2.3/cloud/project/profile-database-queries.md
Labels: 2.2.x, 2.3.x, New topic, Progress: approved, internal-dev

#5101 Change the PWA studio url in Federated Search
  _includes/layout/header-scripts.html
Labels: Progress: review

#5110 What's new updates July 26 - Aug 2
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: approved, internal-dev

#5116 Correct a typo
  guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#5113 Cloud notes
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: Progress: review, Technical, internal-dev

#5087 Adjusted the ExportButton, Hidden, Modal, OnOffColumn Ui components documentations
  guides/v2.2/ui_comp_guide/components/ui-exportbutton.md
  guides/v2.2/ui_comp_guide/components/ui-hidden.md
  guides/v2.2/ui_comp_guide/components/ui-modal.md
  guides/v2.2/ui_comp_guide/components/ui-onoffcolumn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#4551 Updates to code contribution guide
  _includes/contributor/labels.md
  _includes/contributor/rewards.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.2.x, 2.3.x, Major update, Progress: review, internal-dev

#5062 Update create-integration.md
  guides/v2.3/get-started/create-integration.md
Labels: 2.x, Editorial, Progress: approved, small changes

#5121 MAGEDOC-4009 Updating package version numbers for 2.3.3.
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.3, Progress: approved, Technical

#5106 Adding data file Action Group reference
  _data/mftf.yml
  _includes/mftf/mftf_data.md
Labels: 2.2.x, 2.3.x, Progress: approved, Site improvements

#5054 MAGEDOC-3969 Added note to MTF to use MFTF
  guides/v2.2/mtf/mtf_installation.md
  guides/v2.2/mtf/mtf_introduction.md
  guides/v2.2/mtf/mtf_quickstart.md
  guides/v2.2/mtf/mtf_update.md
  guides/v2.3/mtf/mtf_installation.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: review

#5119 Fix links
  guides/v2.3/graphql/release-notes.md
  release/index.md
Labels: Editorial, Progress: approved

#5097 magento/devdocs#: Register libraries
  guides/v2.2/extension-dev-guide/build/component-registration.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5128 Update to Upcoming releases page.
  release/index.md
Labels: 2.0.0-asc, Progress: approved, small changes

#5095 [site] Enhance the external link checking
  Docfile.yml
  Rakefile
  _config.checks.yml
  _data/toc/rest-api.yml
  _data/whats-new.yml
  _includes/contributor/2-1-end.md
  _includes/layout/after-site-header.html
  _includes/layout/header-styles.html
  _layouts/redirect.html
  community/resources/best-practices.md
  community/resources/resources.md
  extensions/index.md
  guides/v2.2/architecture/archi_perspectives/persist_layer.md
  guides/v2.2/architecture/archi_perspectives/present_layer.md
  guides/v2.2/cloud/trouble/message-queues.md
  guides/v2.2/comp-mgr/patching.md
  guides/v2.2/contributor-guide/backward-compatible-development/index.md
  guides/v2.2/contributor-guide/maintainers.md
  guides/v2.2/frontend-dev-guide/themes/js-bundling.md
  guides/v2.2/frontend-dev-guide/translations/xlate.md
  guides/v2.2/install-gde/install/cli/install-cli-uninstall.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9EE.md
  guides/v2.2/test/testing.md
  guides/v2.3/architecture/archi_perspectives/persist_layer.md
  guides/v2.3/architecture/archi_perspectives/present_layer.md
  guides/v2.3/architecture/archi_perspectives/webapi-vision.md
  guides/v2.3/contributor-guide/backward-compatible-development/index.md
  guides/v2.3/extension-dev-guide/depend-inj.md
  guides/v2.3/frontend-dev-guide/translations/xlate.md
  guides/v2.3/install-gde/system-requirements-tech.md
  guides/v2.3/inventory/release-notes.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  release/index.md
  release/policy/index.md
  swagger/schemas/2.1.2.schema.json
  swagger/schemas/2.2.0.schema.json
  swagger/schemas/2.2.1.schema.json
  swagger/schemas/2.2.2.schema.json
  swagger/schemas/2.2.9.schema.json
  swagger/schemas/latest-2.0.schema.json
  swagger/schemas/latest-2.1.schema.json
  swagger/schemas/latest-2.2.schema.json
  swagger/schemas/latest-2.3.schema.json
  swagger/schemas/latest_develop.json
  swagger/schemas/original-2.1.schema.json
  system-requirements.md
Labels: Editorial, Progress: approved, Site improvements

#5114 GraphQL: genericize Payflow Pro docs
  _includes/graphql/payment-methods/payflow-pro-attributes.md
  _includes/graphql/payment-methods/payflow-pro-workflow.md
  common/images/graphql/paypal-payflow-pro.svg
  guides/v2.3/graphql/images/paypal-payflow-pro.svg
  guides/v2.3/graphql/payment-methods/payflow-pro.md
Labels: 2.3.3, Editorial, Progress: approved, internal-dev

#5007 Adding a useful topic of how a custom Import Entity can be defined.
  _data/toc/extension-best-practices.yml
  common/images/ext-best-practices/import-entity.png
  guides/v2.2/ext-best-practices/tutorials/custom-import-entity.md
  guides/v2.3/ext-best-practices/tutorials/custom-import-entity.md
Labels: New topic, Partner: Atwix, Progress: changes requested, partners-contribution

#5132 magento/devdocs#: Data Migration Tool. Updates Content.
  guides/v2.2/migration/migration-migrate-data.md
  guides/v2.2/migration/migration-troubleshooting.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#5130 Update to supported PHP version
  guides/v2.2/install-gde/prereq/php-settings.md
Labels: 2.2.x, Progress: approved, Technical

#5099 Create topic for PayPal Express Checkout payment method
  _data/toc/graphql.yml
  _includes/graphql/payment-methods/paypal-express-checkout-attributes.md
  _includes/graphql/payment-methods/paypal-express-checkout-workflow.md
  common/images/graphql/paypal-express-checkout.svg
  guides/v2.3/graphql/mutations/create-paypal-express-token.md
  guides/v2.3/graphql/payment-methods/paypal-express-checkout.md
  guides/v2.3/graphql/reference/paypal.md
  guides/v2.3/graphql/reference/quote-payment-method.md
Labels: 2.3.3, New topic, Progress: approved, internal-dev

#5011 Technical documentation about integration with CardinalCommerce
  _data/toc/payments-integrations.yml
  common/images/payments-integrations/cardinal_commerce.svg
  guides/v2.2/payments-integrations/cardinal/cardinal.md
  guides/v2.3/payments-integrations/cardinal/cardinal.md
Labels: 2.2.x, 2.3.x, New topic, Progress: approved, internal-dev

#5122 Updated architectural diagram to newest version
  common/images/archi_diagram_desired-state.png
  guides/v2.3/architecture/archi_perspectives/arch_diagrams.md
Labels: 2.2.x, 2.3.x, Progress: changes requested, Technical

#5140 Moved note about `crontab -l` command error
  guides/v2.2/cloud/configure/setup-cron-jobs.md
Labels: 2.2.x, Partner: Atwix, Progress: approved

#5142 Add info about service install or update on Pro
  guides/v2.2/cloud/project/project-conf-files_services-mysql.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#5137 MAGECLOUD-3957 default admin locale
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: Progress: review, Technical, internal-dev

#5148 Update elastic php client composer package name
  guides/v2.2/config-guide/elasticsearch/es-downgrade.md
Labels: 2.2.x, Progress: approved, Technical

#5126 Fix missing a reference to the official m2 translations project in gi…
  guides/v2.2/frontend-dev-guide/translations/xlate.md
  guides/v2.3/frontend-dev-guide/translations/xlate.md
Labels: Partner: Space 48, Progress: approved, partners-contribution

#5120 Fix formatting of sample in setup-cron-jobs.md
  guides/v2.2/cloud/configure/setup-cron-jobs.md
Labels: Progress: changes requested

#5060 Add custom modal type
  common/images/widget/modal-widget-result-custom.png
  guides/v2.2/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.2.x, 2.3.x, Partner: Wagento, Progress: approved, Technical, partners-contribution

#5151 Small changes
  guides/v2.2/cloud/configure/setup-cron-jobs.md
  guides/v2.2/cloud/project/project-conf-files_services-mysql.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.2/config-guide/elasticsearch/es-downgrade.md
  guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.md
  guides/v2.2/frontend-dev-guide/translations/xlate.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/frontend-dev-guide/translations/xlate.md
  guides/v2.3/get-started/create-integration.md
  guides/v2.3/graphql/release-notes.md
  release/index.md
Labels: 2.2.x, 2.3.x, Progress: approved

#5144 [site] Review project implementation and tools
  Rakefile
  _checks/html-check-hook.rb
  _config.yml
  _plugins/glossary-tooltip.rb
  _plugins/liquid-tags/collapsible.rb
  _plugins/liquid-tags/remote_markdown.rb
  _plugins/page-params/github-path.rb
  _plugins/page-params/last-modified-at.rb
  _plugins/page-params/page-baseurl-generator.rb
  _plugins/page-params/page-canonical-url.rb
  _plugins/page-params/page-versionless.rb
  _plugins/page-params/page-versions.rb
  bin/whatsup_github
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.md
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_intro.md
  guides/v2.2/architecture/extensibility.md
  guides/v2.2/architecture/frontend_custom_strategies.md
  guides/v2.2/config-guide/secy/secy.md
  guides/v2.2/javascript-dev-guide/widgets/widget_list.md
  guides/v2.2/javascript-dev-guide/widgets/widget_redirectUrl.md
  guides/v2.3/architecture/security_intro.md
  guides/v2.3/graphql/tutorials/checkout/index.md
  lib/converter.rb
  lib/doc_config.rb
  lib/double_slash_check.rb
  lib/link_checker.rb
Labels: Progress: approved, Site improvements

#5139 GraphQL: Add PayPal Website Payments Pro payment method docs
  _data/toc/graphql.yml
  _includes/graphql/payment-methods/hosted-pro-attributes.md
  _includes/graphql/payment-methods/hosted-pro-workflow.md
  common/images/graphql/paypal-hosted-pro.svg
  guides/v2.3/graphql/payment-methods/hosted-pro.md
  guides/v2.3/graphql/queries/get-hosted-pro-url.md
Labels: 2.3.3, New topic, Progress: approved, internal-dev

#5152 MAGECLOUD-4052 lock provider variable
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: Progress: review, internal-dev

#5127 Add group and subgroup
  guides/v2.2/extension-dev-guide/versioning/check-version.md
Labels: 2.x, Editorial, Progress: approved, small changes

#5158 GraphQL: Add payflow_express and misc payment methods
  _data/toc/graphql.yml
  _includes/graphql/payment-methods/payflow-link-workflow.md
  guides/v2.3/graphql/payment-methods/authorize-net.md
  guides/v2.3/graphql/payment-methods/hosted-pro.md
  guides/v2.3/graphql/payment-methods/payflow-express.md
  guides/v2.3/graphql/payment-methods/payflow-link.md
  guides/v2.3/graphql/payment-methods/payflow-pro.md
  guides/v2.3/graphql/payment-methods/payments-advanced.md
  guides/v2.3/graphql/payment-methods/paypal-express-checkout.md
Labels: 2.3.3, New topic, Progress: approved, internal-dev

#4912 Update docs for magento/graphql-ce#757
  guides/v2.3/graphql/payment-methods/payflow-link.md
  guides/v2.3/graphql/payment-methods/payflow-pro.md
Labels: 2.3.3, Community, In progress, Partner: Something Digital, Progress: review, Technical, partners-contribution

#5156 URL fixed for "Install by cloning repositories" link
  _includes/install/sampledata/sample-data-composer.md
Labels: 2.2.x, 2.3.x, Progress: approved, small changes

#5163 Fix typo
  guides/v2.3/architecture/archi_perspectives/persist_layer.md
Labels: Progress: approved

#5164 magento/devdocs#: Data Migration Tool. Delta migration command update.
  guides/v2.2/migration/migration-migrate-delta.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#5063 Align RabbitMQ installation guide
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
Labels: 2.3.x, Major update, Partner: Comwrap, Progress: changes requested, partners-contribution

#5159 magento/devdocs#: URN highlighter. Keep DTDs up to date.
  guides/v2.2/config-guide/cli/config-cli-subcommands-urn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#5150 add callback to fs.appendFile method call
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: 2.3.x, Progress: approved, Technical

#5168 Update GraphQL docs
  guides/v2.3/graphql/send-request.md
Labels: 2.3.x, Technical, internal-dev, small changes

#5102 Update statement about declaring exceptions
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical

#5146 [site][cicd] Add the Markdown style testing to 'rake test:cicd'
  .mdlrc
  Rakefile
  _checks/html_check_hook.rb
  _checks/md_check_hook.rb
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  lib/link_checker.rb
  rakelib/check.rake
  rakelib/multirepo.rake
  rakelib/test.rake
  rakelib/update.rake
Labels: Progress: review, Site improvements

#5171 Add information about PopupWindow widget
  _data/toc/javascript-developer-guide.yml
  common/images/widget/popupWindow-widget-result.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget-popup-window.md
  guides/v2.3/javascript-dev-guide/widgets/widget-popup-window.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: approved, partners-contribution

#5131 Add redirect for link to devdocs used in magento codebase
  guides/v2.3/release-notes/bk-release-notes.md
Labels: 2.3.x, Editorial, Progress: approved, small changes

#5169 MAGECLOUD-4018: Adjust Service Version Validation for 2.2.10/2.3.3 Support
  guides/v2.2/cloud/project/project-conf-files_services.md
Labels: Progress: review, Technical, internal-dev

#5160 What's new updates Aug 2 - 9
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: review, internal-dev

#5154 Update MFTF TOC for new topics.
  _data/toc/mftf.yml
Labels: Editorial, Progress: approved

#5157 MAGECLOUD-4056: [Cloud Docker] Static files not available if these are created on build stage
  guides/v2.2/cloud/docker/docker-config.md
Labels: Progress: changes requested, Technical, internal-dev

#5175 magento/devdocs#: Remove unused "Indexing" page.
  guides/v2.2/extension-dev-guide/indexing-parent.md
  guides/v2.3/extension-dev-guide/indexing-parent.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, partners-contribution, small changes

#5161 Adding additional information on how to include 3rd-party JS libraries
  common/images/js/slick-slider-result.png
  guides/v2.2/javascript-dev-guide/javascript/js-resources.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5170 #5133- Fixed authentication directions + markdown fixes.
  guides/v2.2/install-gde/composer.md
  guides/v2.3/install-gde/composer.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5174 magento/devdocs#: Set up cron jobs. Structure of `crons` section in `.magento.app.yaml`
  guides/v2.2/cloud/configure/setup-cron-jobs.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution

#5135 Add information about the TrimInput widget
  _data/toc/javascript-developer-guide.yml
  common/images/widget/trimInput-widget-result.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget-trim-input.md
  guides/v2.3/javascript-dev-guide/widgets/widget-trim-input.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Technical, partners-contribution

#5173 Small changes
  _data/toc/mftf.yml
  _data/whats-new.yml
  _includes/install/sampledata/sample-data-composer.md
  guides/v2.2/coding-standards/technical-guidelines.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-urn.md
  guides/v2.2/extension-dev-guide/indexing-parent.md
  guides/v2.2/migration/migration-migrate-delta.md
  guides/v2.3/architecture/archi_perspectives/persist_layer.md
  guides/v2.3/extension-dev-guide/indexing-parent.md
  guides/v2.3/graphql/send-request.md
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
  guides/v2.3/release-notes/bk-release-notes.md
Labels: 2.2.x, 2.3.x, Progress: approved

#5181 Contributor guide squash commits
  guides/v2.2/contributor-guide/contributing.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5178 [site] Fix invalid HTML and enable HTML checking
  _config.checks.yml
  _includes/note.html
  guides/v2.2/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.2/cloud/howtos/install-components.md
  guides/v2.2/cloud/live/stage-prod-migrate.md
  guides/v2.2/coding-standards/technical-guidelines.md
  guides/v2.2/config-guide/cache/cache-options.md
  guides/v2.2/config-guide/multi-master/multi-master_manual.md
  guides/v2.2/config-guide/prod/prod_file-sys-perms.md
  guides/v2.2/config-guide/varnish/config-varnish.md
  guides/v2.2/config-guide/varnish/use-varnish-cache.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/frontend-dev-guide/layouts/layout-extend.md
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
  guides/v2.2/install-gde/bk-install-guide.md
  guides/v2.2/install-gde/install/prepare-install.md
  guides/v2.2/install-gde/prereq/apache.md
  guides/v2.2/install-gde/prereq/zip_install.md
  guides/v2.2/javascript-dev-guide/widgets/widget_gallery.md
  guides/v2.2/mrg/ee/Staging.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.3/install-gde/prereq/apache.md
  guides/v2.3/install-gde/prereq/zip_install.md
Labels: Editorial, Progress: review, Site improvements

#5182 Updating the quick-search widget documentation
  common/images/widget/quick-search-result.png
  guides/v2.2/javascript-dev-guide/widgets/widget_quickSearch.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5167 magento/devdocs#: Data Migration Tool. Data migration command. Preparation for delta step.
  guides/v2.2/migration/migration-migrate-data.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: review, Technical, partners-contribution

#5176 Adjusted the PasswordStrengthIndicator widget documentation
  guides/v2.2/javascript-dev-guide/widgets/widget_password_strength_indicator.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5186 Add 2.2.9 entries to release notes TOC
  _data/toc/release-notes.yml
Labels: 2.2.9, Progress: approved, Site improvements, internal-dev

#5183 Adding information about downloading a Sample File for a new Import Entity
  common/images/ext-best-practices/import-entity.png
  guides/v2.2/ext-best-practices/tutorials/custom-import-entity.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#5123 MAGECLOUD-3520 update screenshot, php lines, markdown
  common/images/config_multi-site-store.png
  guides/v2.2/cloud/project/project-multi-sites.md
  guides/v2.2/cloud/project/project-start.md
  guides/v2.2/config-guide/multi-site/ms_websites.md
Labels: 2.x, Major update, Progress: review, internal-dev

#5180 magento/devdocs#: Cloud. Set up cron jobs. CRONTAB and Magento Cloud CRONs
  guides/v2.2/cloud/configure/setup-cron-jobs.md
Labels: 2.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5129 Converting the Change Increment ID KB to devdocs
  _data/toc/configuration-guide.yml
  guides/v2.2/config-guide/multi-site/change-increment-id.md
  guides/v2.3/config-guide/multi-site/change-increment-id.md
Labels: 2.2.x, 2.3.x, New topic, Progress: approved

#5177 Add data file and template for MFTF Action Groups reference
  _data/codebase/mftf/action-groups.yml
  _data/toc/mftf.yml
  _includes/mftf/actiongroup_data.md
  common/css/devdocs.css
Labels: Progress: changes requested, Technical

#5193 GraphQL: small doc updates from Engcomm PRs
  guides/v2.3/graphql/reference/bundle-product.md
  guides/v2.3/graphql/reference/categories.md
  guides/v2.3/graphql/reference/downloadable-product.md
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.3, Community, Progress: approved, Technical, internal-dev

#5199 MAGEDOC-3673/MC-3673
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 2.x, Progress: approved

#4950 magento/devdocs#: Add info about setPaymentMethodAndPlaceOrder to GraphQL checkout tutorial
  guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
  guides/v2.3/graphql/tutorials/checkout/checkout-payment-method.md
  guides/v2.3/graphql/tutorials/checkout/checkout-quote-email.md
Labels: 2.3.3, Community, Major update, Partner: Atwix, Progress: approved, partners-contribution

#5000 magento/devdocs#: Fixes to GraphQl Checkout Tutorial.
  guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-method.md
Labels: 2.3.3, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5155 Converting the Grouped Products KB to Devdocs
  _data/toc/rest-api.yml
  guides/v2.2/rest/images/new-grouped-product.png
  guides/v2.2/rest/tutorials/grouped-product/create-and-manage-grouped-products.md
  guides/v2.2/rest/tutorials/index.md
  guides/v2.3/rest/images/new-grouped-product.png
  guides/v2.3/rest/tutorials/grouped-product/create-and-manage-grouped-products.md
  guides/v2.3/rest/tutorials/index.md
Labels: 2.3.x, New topic, Progress: changes requested, internal-dev

#4915 BraintreeGraphQl Workflow
  guides/v2.3/graphql/mutations/braintree-create-client-token.md
  guides/v2.3/graphql/payment-methods/braintree-vault.md
  guides/v2.3/graphql/payment-methods/braintree.md
Labels: 2.3.3, Community, In progress, New topic, Partner: Something Digital, Progress: review, partners-contribution

#5197 GraphQL: Migrate reference topics created in 2.3.3
  _data/toc/graphql.yml
  _data/whats-new.yml
  _includes/graphql/payment-methods/payflow-link-workflow.md
  _includes/graphql/payment-methods/payflow-pro-workflow.md
  guides/v2.3/graphql/mutations/create-payflow-pro-token.md
  guides/v2.3/graphql/mutations/handle-payflow-pro-response.md
  guides/v2.3/graphql/mutations/redeem-giftcard-balance.md
  guides/v2.3/graphql/mutations/remove-giftcard.md
  guides/v2.3/graphql/queries/checkout-agreements.md
  guides/v2.3/graphql/queries/custom-attribute-metadata.md
  guides/v2.3/graphql/queries/get-payflow-link-token.md
Labels: 2.3.3, Progress: approved, Site improvements, internal-dev

#5219 Debug logging options should match sentence context
  guides/v2.2/config-guide/cli/logging.md
  guides/v2.3/config-guide/cli/logging.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, internal-dev

#5223 Link to new marketing PDF from release info page
  release/index.md
  release/policy/index.md
Labels: Progress: approved, internal-dev

#5134 Update debug.md
  guides/v2.2/cloud/howtos/debug.md
Labels: Progress: changes requested

#5212 Updated What's New for documentation updates since Aug 9, 2019
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: review, internal-dev

#5213 GraphQL: update description of deprecated directive
  guides/v2.3/graphql/develop/create-graphqls-file.md
Labels: 2.3.4, Progress: approved, Technical, internal-dev

#5198 MAGECLOUD-3874: Remove support if build_options.ini and fail build if it's present
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/project/magento-env-yaml.md
Labels: Progress: review, Technical, internal-dev

#5196 MAGECLOUD-3871: Write cloud.log in debug level to file
  guides/v2.2/cloud/env/variables-global.md
Labels: 2.x, Progress: review, Technical, internal-dev

#5232 GraphQL: Add Braintree infographics
  _data/toc/graphql.yml
  common/images/graphql/braintree-vault.svg
  common/images/graphql/braintree.svg
  guides/v2.3/graphql/payment-methods/braintree-vault.md
  guides/v2.3/graphql/payment-methods/braintree.md
Labels: 2.3.3, Editorial, Progress: approved, internal-dev

#5125 Removed legacy Cloud infrastructure info
  _data/toc/cloud-guide.yml
  _data/whats-new.yml
  _includes/cloud/hooks.md
  _includes/cloud/note-pro-legacy.md
  _includes/cloud/note-pro-using-yaml-support.md
  _includes/cloud/note-pro-using-yaml.md
  _includes/cloud/wings-management.md
  common/images/cloud/cloud-pro-project-access.png
  common/images/cloud/cloud-starter-project-access.png
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/architecture/pro-architecture-legacy.md
  guides/v2.2/cloud/architecture/pro-architecture.md
  guides/v2.2/cloud/architecture/pro-develop-deploy-workflow.md
  guides/v2.2/cloud/configure/setup-cron-jobs.md
  guides/v2.2/cloud/env/environments.md
  guides/v2.2/cloud/integrations/bitbucket-integration.md
  guides/v2.2/cloud/live/stage-prod-migrate-prereq.md
  guides/v2.2/cloud/live/stage-prod-migrate.md
  guides/v2.2/cloud/project/magento-env-yaml.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/project/project-conf-files_services-redis.md
  guides/v2.2/cloud/project/project-integrate-blackfire.md
  guides/v2.2/cloud/project/project-multi-sites.md
  guides/v2.2/cloud/project/project-upgrade.md
  guides/v2.2/cloud/project/project-webint-basic.md
  guides/v2.2/cloud/project/project-webint-branch.md
  guides/v2.2/cloud/project/projects.md
  guides/v2.2/cloud/project/user-admin.md
  guides/v2.2/cloud/reference/cli-ref-topic.md
  guides/v2.2/cloud/reference/discover-deploy.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/setup/first-time-setup-import-prepare.md
  guides/v2.2/cloud/trouble/pro-env-management.md
  guides/v2.2/cloud/trouble/site-availability.md
  guides/v2.2/cloud/trouble/trouble.md
  guides/v2.3/cloud/architecture/pro-architecture-legacy.md
  guides/v2.3/cloud/project/projects.md
  guides/v2.3/cloud/project/user-admin.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/trouble/pro-env-management.md
Labels: 2.x, Major update, Progress: changes requested, internal-dev

#5236 Added Q3 Commerce releases to release info page
  release/index.md
Labels: Progress: approved, internal-dev

#5254 Add GTM tag in order to verify site in GSC
  _includes/layout/site-nav.html
Labels: Progress: approved

#5258 Add GSC meta tag
  _includes/layout/header-styles.html
Labels: Progress: approved

#5239 Updated instructions for reviewing cron configuration
  guides/v2.2/cloud/configure/setup-cron-jobs.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#5209 Update section about exceptions
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Major update, Progress: approved, internal-dev

#5217 Fixing the developer mode sentence
  guides/v2.2/config-guide/bootstrap/magento-modes.md
Labels: 2.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5215 Updating the checking cron module section
  guides/v2.2/config-guide/cron/custom-cron-tut.md
Labels: 2.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#5226 Fix typo in credentials section
  guides/v2.2/get-started/authentication/gs-authentication-token.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#5227 Remove email example from username credentials
  guides/v2.2/get-started/authentication/gs-authentication-token.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, small changes

#5224 magento/devdocs#: Cloud. Elastic search.
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5202 magento/devdocs#4649: Topic clarification/correction request
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
Labels: 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution, small changes

#5263 magento/devdocs#: Fix release notice info about STATIC_CONTENT_THREADS and change info on the appropriate pages
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/trouble/redis-troubleshooting.md
  guides/v2.2/cloud/trouble/site-availability.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5264 Small changes
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
  guides/v2.2/config-guide/cron/custom-cron-tut.md
  guides/v2.2/get-started/authentication/gs-authentication-token.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
Labels: Progress: review, internal-dev

#5255 Added Note for 404 error regarding /robots.txt files
  guides/v2.2/cloud/trouble/robots-sitemap.md
Labels: 2.3.x, Editorial, Progress: review, internal-dev

#5267 Update Magento 2.3.0 Open Source release notes
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.3.x, Community Insider: Cream, Progress: review, Technical, community-insider-contribution

#5257 Updated option desc for queue:consumers:start
  _includes/config/message-queue-consumers.md
Labels: 2.2.10, 2.3.3, Progress: review, Technical, internal-dev

#5266 GH-4757: Copyedit /front-end-dev-guide/theme-best-practice.md page
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
Labels: 2.x, Editorial, Progress: review

#5291 Removed config.env info
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-development-debug.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
  test.txt
Labels: 2.x, Technical, internal-dev

#5189 Q3 pre-release Composer install instructions
  guides/v2.3/cloud/project/project-upgrade.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/install-gde/composer.md
Labels: 2.3.x, Major update, Progress: changes requested, internal-dev

#5296 Removed example of customizing the Admin URI during install
  guides/v2.2/install-gde/composer.md
  guides/v2.3/install-gde/composer.md
Labels: 2.2.x, 2.3.x, Progress: acceptance testing, Technical

#5297 Fixed broken link for Emogrifier README link
  guides/v2.2/frontend-dev-guide/templates/template-email.md
Labels: 2.3.x, Editorial, Progress: approved, small changes

#5295 updating output of this command bin/magento queue:consumers:list
  _includes/config/message-queue-consumers.md
Labels: 2.x, Editorial, Progress: acceptance testing, small changes

#5292 Remove unsupported PHP versions from examples
  guides/v2.2/extension-dev-guide/package/package_module.md
Labels: 2.2.x, 2.3.x, Progress: acceptance testing, Technical, small changes

#5205 magento/devdocs#3220: Prioritizing Plugins section of Plugins (Interceptors) is not clear
  guides/v2.2/extension-dev-guide/plugins.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5231 Converting the refunds and credits KB to devdocs
  _data/toc/rest-api.yml
  guides/v2.2/rest/modules/sales/refunds.md
  guides/v2.3/rest/modules/sales/refunds.md
Labels: 2.2.x, 2.3.x, New topic, Progress: approved, internal-dev

#5301 Small changes
  _includes/config/message-queue-consumers.md
  guides/v2.2/extension-dev-guide/package/package_module.md
  guides/v2.2/extension-dev-guide/plugins.md
  guides/v2.2/frontend-dev-guide/templates/template-email.md
  guides/v2.3/extension-dev-guide/package/package_module.md
Labels: Progress: review, internal-dev

#5284 GraphQL: Migrate Quote endpoint topics
  _data/toc/graphql.yml
  _data/whats-new.yml
  _includes/graphql/cart-object.md
  _includes/graphql/payment-methods/hosted-pro-workflow.md
  _includes/graphql/payment-methods/payflow-link-workflow.md
  _includes/graphql/payment-methods/payflow-pro-workflow.md
  _includes/graphql/payment-methods/paypal-express-checkout-workflow.md
  guides/v2.3/graphql/mutations/add-configurable-products.md
  guides/v2.3/graphql/mutations/add-simple-products.md
  guides/v2.3/graphql/mutations/add-virtual-products.md
  guides/v2.3/graphql/mutations/apply-coupon.md
  guides/v2.3/graphql/mutations/apply-giftcard.md
  guides/v2.3/graphql/mutations/apply-store-credit.md
  guides/v2.3/graphql/mutations/create-empty-cart.md
  guides/v2.3/graphql/mutations/create-paypal-express-token.md
  guides/v2.3/graphql/mutations/handle-payflow-pro-response.md
  guides/v2.3/graphql/mutations/place-order.md
  guides/v2.3/graphql/mutations/remove-coupon.md
  guides/v2.3/graphql/mutations/remove-giftcard.md
  guides/v2.3/graphql/mutations/remove-item.md
  guides/v2.3/graphql/mutations/remove-store-credit.md
  guides/v2.3/graphql/mutations/set-billing-address.md
  guides/v2.3/graphql/mutations/set-guest-email.md
  guides/v2.3/graphql/mutations/set-payment-method.md
  guides/v2.3/graphql/mutations/set-payment-place-order.md
  guides/v2.3/graphql/mutations/set-shipping-address.md
  guides/v2.3/graphql/mutations/set-shipping-method.md
  guides/v2.3/graphql/mutations/update-cart-items.md
  guides/v2.3/graphql/payment-methods/authorize-net.md
  guides/v2.3/graphql/payment-methods/braintree-vault.md
  guides/v2.3/graphql/payment-methods/braintree.md
  guides/v2.3/graphql/payment-methods/payflow-express.md
  guides/v2.3/graphql/payment-methods/payflow-link.md
  guides/v2.3/graphql/payment-methods/payflow-pro.md
  guides/v2.3/graphql/payment-methods/paypal-express-checkout.md
  guides/v2.3/graphql/product/gift-card-product.md
  guides/v2.3/graphql/queries/cart.md
  guides/v2.3/graphql/queries/get-hosted-pro-url.md
  guides/v2.3/graphql/queries/get-payflow-link-token.md
  guides/v2.3/graphql/queries/giftcard-account.md
  guides/v2.3/graphql/release-notes.md
  guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
Labels: 2.3.3, Progress: approved, Site improvements, internal-dev

#5303 Regenerate the magento CLI reference
  _data/codebase/v2_2/open-source/bin-magento.yml
  _data/codebase/v2_3/open-source/bin-magento.yml
Labels: Progress: approved, Technical, internal-dev
