Repository magento/devdocs, pull requests merged in 2019-06, with the labels that each got.

#4664 Corrected the default value of buttons option
  guides/v2.1/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4663 Corrected the value of "template" attribute
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4668 MAGECLOUD-3720: Corrected email config info
  guides/v2.1/cloud/project/project-webint-basic.md
Labels: 2.x, Editorial, internal-dev

#4428 Document new PoisonPill interface
  _data/toc/php-developer-guide.yml
  guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/extension-dev-guide/message-queues/refresh-config.md
Labels: 2.3.2, New topic, internal-dev

#4587 Update ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
Labels: Editorial, Partner: ISM eCompany, partners-contribution

#4671 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#4643 Config files updates (m.2.3)
  guides/v2.3/config-guide/config/config-files.md
Labels: 2.3.x, Major update, Partner: Atwix, Technical, partners-contribution

#4641 Add PayPal GraphQL support
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/paypal.md
  guides/v2.3/graphql/reference/quote-payment-method.md
Labels: 2.3.3, New topic, internal-dev

#4666 Improved explanation & context of setCurrentPage method.
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
Labels: 2.3.x, Technical

#4688 Partner Release Notes 2.3.2 and 2.2.9
  _includes/release-notes/engcomm-2-2-9-partner.md
  _includes/release-notes/engcomm-2-3-2-partner.md
Labels: 2.3.2, internal-dev

#4691 Add support of multirepo search
  Gemfile.lock
  _config.yml
  _includes/layout/header-scripts.html
  _includes/layout/version-switcher.html
  _plugins/collapsible-content.rb
  _plugins/page-versionless.rb
  _plugins/page-versions.rb
Labels: Site improvements

#4697 fix page title issue
  guides/v2.1/javascript-dev-guide/widgets/widget_accordion.md
Labels: 2.1.x, 2.3.x, 2.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4689 magento/devdocs#: Remove direct links to repository
  guides/v2.1/frontend-dev-guide/layouts/layout-types.md
  guides/v2.1/test/integration/annotations/magento-db-isolation.md
  guides/v2.2/frontend-dev-guide/themes/js-bundling.md
  guides/v2.2/test/integration/annotations/magento-db-isolation.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/functional-testing.md
  guides/v2.3/inventory/inventory-api-reference.md
  guides/v2.3/test/integration/annotations/magento-db-isolation.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4692 Fix TOC entry for new Poison Pill topic
  _data/toc/php-developer-guide.yml
Labels: internal-dev

#4670 MAGEDOC-3783 Add "Patching Magento" topic to devdocs.
  _data/toc/software-update-guide.yml
  guides/v2.1/comp-mgr/patching.md
  guides/v2.2/comp-mgr/patching.md
  guides/v2.3/comp-mgr/patching.md
Labels: 2.1.x, 2.2.x, 2.3.x, New topic

#4599 Block vs container details
  guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4703 Ken google 1.1.2 rel notes
  extensions/google-shopping-ads/release-notes/index.md
Labels: 1.1.2-gsa, Major update

#4699 Add content to ObjectManager topic
  guides/v2.1/extension-dev-guide/object-manager.md
Labels: 2.1.x, 2.2.x, 2.3.x, internal-dev

#4698 Updated notes for recaptcha in 2.3.2, 2.2.9, 2.1.18
  guides/v2.1/security/google-recaptcha.md
  guides/v2.3/inventory/release-notes.md
  guides/v2.3/security/google-recaptcha.md
Labels: 2.1.x, 2.2.x, 2.3.2, Technical, internal-dev

#4706 update release page for google patch 1.1.2
  _data/compatibility.yml
  release/index.md
Labels: Major update

#4707 magento/devdocs#: Add information about Magento_Persistent module for Magento 2.1 and 2.2 versions
  guides/v2.1/mrg/ce/Persistent.md
  guides/v2.2/mrg/ce/Persistent.md
Labels: 2.1.x, 2.2.x, New topic, Partner: Atwix, Technical, partners-contribution

#4685 magento/devdocs#: Config files updates (m.2.1)
  guides/v2.1/config-guide/config/config-files.md
Labels: 2.1.x, Partner: Atwix, Technical, partners-contribution

#4718 Sync develop with master
  Gemfile.lock
  _config.yml
  _data/compatibility.yml
  _data/toc/software-update-guide.yml
  _data/whats-new.yml
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
  _includes/layout/header-scripts.html
  _includes/layout/version-switcher.html
  _plugins/collapsible-content.rb
  _plugins/page-versionless.rb
  _plugins/page-versions.rb
  extensions/amazon-sales/index.md
  extensions/google-shopping-ads/release-notes/index.md
  guides/v2.1/cloud/project/project-webint-basic.md
  guides/v2.1/comp-mgr/patching.md
  guides/v2.1/config-guide/mq/rabbitmq-overview.md
  guides/v2.1/config-guide/prod/config-reference-most.md
  guides/v2.1/extension-dev-guide/object-manager.md
  guides/v2.1/frontend-dev-guide/layouts/layout-types.md
  guides/v2.1/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.1/howdoi/checkout/images/checkout-add-custom-carrier-01.png
  guides/v2.1/howdoi/checkout/images/checkout-add-custom-carrier-02.png
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
  guides/v2.1/javascript-dev-guide/widgets/widget_accordion.md
  guides/v2.1/javascript-dev-guide/widgets/widget_modal.md
  guides/v2.1/mrg/ce/Persistent.md
  guides/v2.1/test/integration/annotations/magento-db-isolation.md
  guides/v2.2/comp-mgr/patching.md
  guides/v2.2/config-guide/mq/rabbitmq-overview.md
  guides/v2.2/config-guide/prod/config-reference-most.md
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/themes/js-bundling.md
  guides/v2.2/mrg/ce/Persistent.md
  guides/v2.2/test/integration/annotations/magento-db-isolation.md
  guides/v2.3/comp-mgr/patching.md
  guides/v2.3/config-guide/config/config-files.md
  guides/v2.3/config-guide/mq/rabbitmq-overview.md
  guides/v2.3/config-guide/redis/redis-pg-cache.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
  guides/v2.3/graphql/functional-testing.md
  guides/v2.3/inventory/inventory-api-reference.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/backward-incompatible-changes/reference.md
  guides/v2.3/test/integration/annotations/magento-db-isolation.md
  release/index.md
Labels: internal-dev

#4714 Remove double empty lines for widgets documentations and add the missed active option link for tabs widget
  guides/v2.1/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.1/javascript-dev-guide/widgets/widget_alert.md
  guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.1/javascript-dev-guide/widgets/widget_confirm.md
  guides/v2.1/javascript-dev-guide/widgets/widget_dialog.md
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery.md
  guides/v2.1/javascript-dev-guide/widgets/widget_loader.md
  guides/v2.1/javascript-dev-guide/widgets/widget_modal.md
  guides/v2.1/javascript-dev-guide/widgets/widget_navigation.md
  guides/v2.1/javascript-dev-guide/widgets/widget_quickSearch.md
  guides/v2.1/javascript-dev-guide/widgets/widget_tabs.md
  guides/v2.2/javascript-dev-guide/widgets/widget_quickSearch.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4710 Typo in description for "privateInfoKeys" option
  guides/v2.2/payments-integrations/base-integration/payment-option-config.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#4708 magento/devdocs#: Add link to Symfony console component
  guides/v2.1/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4700 Add __('<your_string>') method in Button Example
  guides/v2.1/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.1.x, 2.2.x, 2.3.x, Community, Technical, small changes

#4701 magento/devdocs#: Add information about cookies restriction
  guides/v2.1/cloud/project/project-routes-more-cache.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4684 Config files updates 2.2
  guides/v2.2/config-guide/config/config-files.md
Labels: 2.2.x, Partner: Atwix, Technical, partners-contribution

#4705 MAGECLOUD-3739 elasticsuite plugin note
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.x, Technical

#4709 magento/devdocs#: Monolog log functions
  guides/v2.1/config-guide/log/log-magento.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4722 Added v2.3.2 release notes
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.2, New topic

#4721 Added release notes for version 2.2.9
  _data/toc/release-notes.yml
  _includes/release-notes/engcomm-2-2-9-issues.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9EE.md
  guides/v2.2/release-notes/bk-release-notes.md
Labels: 2.2.x, New topic

#4727 Update MFTF branch from develop to master.
  Docfile.yml
Labels: Site improvements

#4646 Database translation description
  guides/v2.1/frontend-dev-guide/translations/theme_dictionary.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4725 Update GraphQL release notes for 2.3.2
  guides/v2.3/graphql/release-notes.md
Labels: 2.3.2, Community, Major update, internal-dev

#4686 Fixing initial spellcheck errors
  _data/whats-new.yml
  _includes/config/config-reference_sensitive.md
  guides/v2.1/cloud/cdn/fastly-waf-service.md
  guides/v2.1/config-guide/prod/config-reference-sens.md
  guides/v2.1/ext-best-practices/extension-coding/coding-faq.md
  guides/v2.1/marketplace/eqp/packages.md
  guides/v2.1/pattern-library/controls/Expandable_Sections/expand-collapse.md
  guides/v2.1/pattern-library/getting-user-input/form_elements/form_elements.md
  guides/v2.1/payments-integrations/vault/payment-token.md
  guides/v2.1/release-notes/ReleaseNotes2.1.13CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.13EE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.14EE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.15CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.16EE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.8CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.8EE.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/config-guide/deployment/index.md
  guides/v2.2/config-guide/memcache/memcache.md
  guides/v2.2/config-guide/prod/config-reference-sens.md
  guides/v2.2/mrg/b2b/Company.md
  guides/v2.2/payments-integrations/vault/payment-token.md
  guides/v2.2/release-notes/ReleaseNotes2.2.0CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.0EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.3/config-guide/prod/config-reference-sens.md
  guides/v2.3/graphql/functional-testing.md
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/inventory/release-notes.md
  guides/v2.3/mrg/b2b/Company.md
  guides/v2.3/mrg/b2b/RequisitionList.md
  guides/v2.3/mrg/ce/InstantPurchase.md
  guides/v2.3/mrg/ce/WebapiAsync.md
  guides/v2.3/mrg/ee/ScalableCheckout.md
  guides/v2.3/mrg/ee/ScalableInventory.md
  guides/v2.3/mrg/ee/ScalableOms.md
  guides/v2.3/mrg/ee/Staging.md
  guides/v2.3/mrg/ee/VisualMerchandiser.md
  guides/v2.3/mtf/mtf_installation.md
  guides/v2.3/payments-integrations/vault/payment-token.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/rest/modules/inventory/manage-source-selection.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#4734 Minor grammar issue
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
Labels: 2.3.x, Editorial

#4730 Update price_rendering.md
  guides/v2.2/ui_comp_guide/howto/price_rendering.md
Labels: 2.2.x, 2.3.x, Partner: MageSpecialist, Technical, partners-contribution

#4737 Added toc and release note page updates for 2.3.2
  _data/toc/release-notes.yml
  guides/v2.3/release-notes/bk-release-notes.md
Labels: 2.3.2, Editorial

#4720 MAGECLOUD-3258 warm cache with multiple pages
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, Technical, internal-dev

#4738 corrected link syntax
  extensions/amazon-sales/index.md
Labels: Editorial, internal-dev

#4740 Fix compatibility table
  _data/compatibility.yml
Labels: internal-dev

#4680 Update backward incompatible changes docs for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
Labels: 2.3.x, Technical

#4749 MAGECLOUD-3258: warm cache with multiple pages
  guides/v2.1/cloud/env/variables-post-deploy.md
Labels: internal-dev

#4752 Added 'rake check' to Rakefile
  Rakefile
  rakelib/check.rake
Labels: Site improvements

#4744 Replaced TABS for space for correct indentation.
  guides/v2.1/javascript-dev-guide/javascript/js_init.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, small changes

#4751 Weekly digest
  _data/whats-new.yml
Labels: Editorial

#4695 Change Database Interface section link and sample code
  guides/v2.3/extension-dev-guide/prepare/lifecycle.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4694 Module wise translate same element
  guides/v2.1/frontend-dev-guide/translations/theme_dictionary.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4754 Remove obsolete image reference
  guides/v2.1/cloud/cdn/fastly-vcl-whitelist.md
Labels: 2.x, small changes

#4683 Added info about mview
  guides/v2.2/extension-dev-guide/indexing.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4591 Add warning about the list widget is deprecated since version 2.2.0
  guides/v2.2/javascript-dev-guide/widgets/widget_list.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, partners-contribution

#4747 Additional info about module's output disabling
  guides/v2.2/config-guide/config/disable-module-output.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4756 Update MFTF repo from develop to master.
  _config.yml
Labels: Site improvements

#4746 Update backward incompatible changes docs for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
Labels: 2.3.x, Technical

#4735 Adding the data provider annotation to Unit Tests
  _data/toc/testing.yml
  guides/v2.1/test/unit/annotations/data-provider.md
  guides/v2.2/test/unit/annotations/data-provider.md
  guides/v2.3/test/unit/annotations/data-provider.md
Labels: 2.1.x, 2.2.x, 2.3.x, New topic, Partner: Atwix, partners-contribution

#4693 Add bin/magento reference topics
  _data/codebase/v2_1/open-source/bin-magento.yaml
  _data/codebase/v2_2/open-source/bin-magento.yaml
  _data/codebase/v2_3/open-source/bin-magento.yaml
  _data/main-nav.yml
  _includes/reference/cli-template.md
  guides/v2.1/reference/cli/magento.md
  guides/v2.2/reference/cli/magento.md
  guides/v2.3/reference/cli/magento.md
Labels: 2.x, New topic

#4761 Update backward incompatible changes docs for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
Labels: 2.3.x, Technical

#4760 Add GraphQL vault documentation
  _data/toc/graphql.yml
  _includes/graphql/customer-payment-tokens.md
  guides/v2.3/graphql/reference/vault.md
Labels: 2.3.2, Community, New topic, internal-dev

#4768 Fix description of theme.xml contents
  guides/v2.1/frontend-dev-guide/themes/theme-structure.md
  guides/v2.2/frontend-dev-guide/themes/theme-structure.md
  guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#4769 Weekly digest and 'rake whatsnew'
  .gitignore
  Gemfile
  Gemfile.lock
  Rakefile
  _data/whats-new.yml
Labels: Editorial, Site improvements

#4772 Fixed up formatting errors in 'Applying patches' topic.
  guides/v2.3/comp-mgr/patching.md
Labels: 2.3.x, Editorial

#4399 Update checkout_new_step.md
  guides/v2.1/howdoi/checkout/checkout_new_step.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4774 MAGEDOC-3878: Fixed code blocks and other line indentations
  guides/v2.3/install-gde/prereq/php-centos-ubuntu.md
Labels: 2.3.x, Editorial, internal-dev

#4770 MD3834 - 2.1 EOL banner
  _includes/layout/after-site-header.html
Labels: 2.1.x, Site improvements, internal-dev

#4771 Add documentation for RedirectUrl widget
  _data/toc/javascript-developer-guide.yml
  common/images/widget/redirectUrl-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.1/javascript-dev-guide/widgets/widget_redirectUrl.md
  guides/v2.2/javascript-dev-guide/widgets/widget_redirectUrl.md
  guides/v2.3/javascript-dev-guide/widgets/widget_redirectUrl.md
Labels: Partner: Atwix, partners-contribution

#4731 Add code samples for alert widget and add information about modalClass option
  common/images/widget/alert-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_alert.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4773 Release notes 2 1 18
  .gitignore
  .vscode/settings.json
  Gemfile
  Gemfile.lock
  Rakefile
  _data/codebase/v2_1/open-source/bin-magento.yaml
  _data/codebase/v2_2/open-source/bin-magento.yaml
  _data/codebase/v2_3/open-source/bin-magento.yaml
  _data/main-nav.yml
  _data/toc/javascript-developer-guide.yml
  _data/toc/release-notes.yml
  _data/toc/testing.yml
  _data/whats-new.yml
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
  _includes/reference/cli-template.md
  common/images/widget/redirectUrl-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.1/javascript-dev-guide/widgets/widget_redirectUrl.md
  guides/v2.1/reference/cli/magento.md
  guides/v2.1/release-notes/ReleaseNotes2.1.18CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.18EE.md
  guides/v2.1/release-notes/bk-release-notes.md
  guides/v2.1/test/unit/annotations/data-provider.md
  guides/v2.2/javascript-dev-guide/widgets/widget_redirectUrl.md
  guides/v2.2/reference/cli/magento.md
  guides/v2.2/test/unit/annotations/data-provider.md
  guides/v2.3/install-gde/prereq/php-centos-ubuntu.md
  guides/v2.3/javascript-dev-guide/widgets/widget_redirectUrl.md
  guides/v2.3/reference/cli/magento.md
  guides/v2.3/test/unit/annotations/data-provider.md
Labels: 2.1.18, Major update

#4782 Described missed prompt widget options and added code samples of prompt widget initialization
  common/images/widget/prompt-widget-result.png
  guides/v2.2/javascript-dev-guide/widgets/widget_prompt.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4743 Fixes some issues in the release notes for Magento 2.3.2
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.2, Editorial

#4690 New GraphQL topics for the GiftCard object
  _data/toc/graphql.yml
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/reference/quote-apply-giftcard.md
  guides/v2.3/graphql/reference/quote-giftcard-account.md
  guides/v2.3/graphql/reference/quote-remove-giftcard.md
  guides/v2.3/graphql/reference/quote.md
  guides/v2.3/graphql/reference/redeem-giftcard-balance.md
Labels: 2.3.2, New topic, internal-dev

#4787 MAGECLOUD-3813 ece-tools reference
  _data/toc/cloud-guide.yml
  _includes/cloud/note-ece-tools-release-info.md
  guides/v2.1/cloud/bk-cloud.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/env/variables-cloud.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/reference/ece-tools-reference.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-cloud.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/reference/ece-tools-reference.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/reference/ece-tools-reference.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, New topic, internal-dev

#4777 Update docs about composer-packaged themes to include naming convention
  guides/v2.1/extension-dev-guide/package/package_module.md
  guides/v2.1/frontend-dev-guide/themes/theme-structure.md
  guides/v2.2/frontend-dev-guide/themes/theme-structure.md
  guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, small changes

#4790 Add content related to loader widget
  guides/v2.1/javascript-dev-guide/widgets/widget_loader.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4797 Add __('<your_string>') method in Confirm Widget Examples
  guides/v2.1/javascript-dev-guide/widgets/widget_confirm.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4799 Small changes
  guides/v2.1/extension-dev-guide/package/package_module.md
  guides/v2.1/frontend-dev-guide/themes/theme-structure.md
  guides/v2.1/howdoi/checkout/checkout_new_step.md
  guides/v2.1/javascript-dev-guide/widgets/widget_alert.md
  guides/v2.1/javascript-dev-guide/widgets/widget_confirm.md
  guides/v2.1/javascript-dev-guide/widgets/widget_loader.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/frontend-dev-guide/themes/theme-structure.md
  guides/v2.3/comp-mgr/patching.md
  guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: internal-dev

#4674 customize Magento admin logo
  guides/v2.1/frontend-dev-guide/themes/admin_theme_create.md
  guides/v2.3/frontend-dev-guide/themes/admin_theme_create.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4786 Separate indexing configuration into `_config.index.yml`
  _config.index.yml
  _config.yml
Labels: Site improvements

#4794 Add ece-tools contributor credit to Cloud release notes
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: Editorial, internal-dev

#4796 added known issues
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.2, Editorial

#4791 MAGECLOUD-3357: [Cloud Docker] Changes in .magento.app.yaml should affect php modules
  guides/v2.1/cloud/docker/docker-development-debug.md
Labels: internal-dev

#4802 Added Code Sample for Confirmation widget
  common/images/widget/confirm-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_confirm.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#4814 Weekly digest
  _data/whats-new.yml
Labels: Editorial

#4819 Update Magento Inventory 1.1.2 for GA
  _data/compatibility.yml
  _data/toc/release-notes.yml
  extensions/inventory-management/index.md
  guides/v2.3/inventory/images/inventory-diagram-stock.png
  guides/v2.3/inventory/index.md
  guides/v2.3/inventory/inventory-api-reference.md
  guides/v2.3/inventory/release-notes.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 1.1.2-msi, Technical, internal-dev

#4821 Add links
  guides/v2.3/graphql/reference/wishlist.md
  guides/v2.3/graphql/release-notes.md
Labels: 2.3.2, Editorial, internal-dev

#4822 Sync develop with master
  _config.index.yml
  _config.yml
  _data/whats-new.yml
  common/images/widget/alert-widget-result.png
  common/images/widget/confirm-widget-result.png
  common/images/widget/prompt-widget-result.png
  guides/v2.1/extension-dev-guide/package/package_module.md
  guides/v2.1/frontend-dev-guide/themes/admin_theme_create.md
  guides/v2.1/frontend-dev-guide/themes/theme-structure.md
  guides/v2.1/howdoi/checkout/checkout_new_step.md
  guides/v2.1/javascript-dev-guide/widgets/widget_alert.md
  guides/v2.1/javascript-dev-guide/widgets/widget_confirm.md
  guides/v2.1/javascript-dev-guide/widgets/widget_loader.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/frontend-dev-guide/themes/theme-structure.md
  guides/v2.2/javascript-dev-guide/widgets/widget_prompt.md
  guides/v2.3/comp-mgr/patching.md
  guides/v2.3/frontend-dev-guide/themes/admin_theme_create.md
  guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: internal-dev

#4823 Fix GraphQL Vault link
  guides/v2.3/graphql/release-notes.md
Labels: Editorial, internal-dev

#4824 MAGEDOC-3906: Update release info page for Q2 release
  _data/compatibility.yml
  release/index.md
Labels: 2.3.x, Major update

#4827 Remove system-specific file
  .gitignore
  .vscode/settings.json
Labels: internal-dev

#4817 Added TTFB_TESTED_PAGES
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/live/stage-prod-test.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/env/variables-post-deploy.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, Major update

#4676 Update codebase-changes.md
  guides/v2.1/extension-dev-guide/versioning/codebase-changes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, internal-dev

#4830 Added note for developer mode
  guides/v2.1/config-guide/bootstrap/magento-modes.md
  guides/v2.2/config-guide/bootstrap/magento-modes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4331 magento/devdocs#: Resolvers. Add a tip about input/output types
  guides/v2.3/graphql/develop/resolvers.md
Labels: 2.3.1, Partner: Atwix, Technical, partners-contribution

#4808 Adding the missing menu item for the DynamicRows topic
  _data/toc/extension-best-practices.yml
  guides/v2.3/graphql/develop/resolvers.md
Labels: Partner: Atwix, partners-contribution, small changes

#4832 fix formatting in GraphQL release notes
  guides/v2.3/graphql/release-notes.md
Labels: 2.3.2, Editorial, internal-dev

#4831 Merge Q3-develop with develop
  _data/toc/graphql.yml
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/reference/paypal.md
  guides/v2.3/graphql/reference/quote-apply-giftcard.md
  guides/v2.3/graphql/reference/quote-giftcard-account.md
  guides/v2.3/graphql/reference/quote-payment-method.md
  guides/v2.3/graphql/reference/quote-remove-giftcard.md
  guides/v2.3/graphql/reference/quote.md
  guides/v2.3/graphql/reference/redeem-giftcard-balance.md
Labels: internal-dev

#4271 Graphql checkout tutorial
  _data/toc/graphql.yml
  guides/v2.3/graphql/tutorials/checkout/checkout-add-product-to-cart.md
  guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
  guides/v2.3/graphql/tutorials/checkout/checkout-customer.md
  guides/v2.3/graphql/tutorials/checkout/checkout-payment-method.md
  guides/v2.3/graphql/tutorials/checkout/checkout-place-order.md
  guides/v2.3/graphql/tutorials/checkout/checkout-quote-email.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-method.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shopping-cart.md
  guides/v2.3/graphql/tutorials/checkout/index.md
Labels: 2.3.2, Community, New topic, Partner: Atwix, partners-contribution

#4637 [2.3.3 - 2.2.10] Update contributors guide due to Travis CI disable
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.2.10, 2.3.3, Editorial

#4828 MAGECLOUD-3684 functional testing in Docker
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/docker/docker-development-testing.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/docker/docker-development-testing.md
  guides/v2.3/cloud/docker/docker-development-testing.md
Labels: 2.x, New topic, internal-dev

#4837 Generated backward incompatible changes docs for the latest patch release of Magento 2.1
  _includes/backward-incompatible-changes/commerce/2.1.17-2.1.18.html
  _includes/backward-incompatible-changes/open-source/2.1.17-2.1.18.md
Labels: 2.1.18

#4836 Generated backward incompatible changes docs for Magento 2.2
  _includes/backward-incompatible-changes/commerce/2.2.8-2.2.9.md
  _includes/backward-incompatible-changes/open-source/2.2.8-2.2.9.md
Labels: 2.2.9

#4833 Generated docs for backward incompatible changes in 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3.2.md
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3.2.md
Labels: 2.3.2

#4835 Added missing Highlights information to 2.3.2 Open Source release notes
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.2

#4845 Update theme-best-practice.md
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#4842 fixing code issue
  guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.md
  guides/v2.3/get-started/create-integration.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4834 GitHub issue #4505: Fix table formatting and link issues
  guides/v2.1/extension-dev-guide/attributes.md
Labels: 2.2.x, Editorial, small changes

#4848 link tag can be use to insert CSS file
  guides/v2.1/frontend-dev-guide/css-topics/css-themes.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#4841 Fix PR owner
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.x, Editorial

#4847 Update configure-fastly.md
  guides/v2.1/cloud/cdn/configure-fastly.md
Labels: 2.x, Editorial, Partner: ISM eCompany, partners-contribution

#4809 Adding a new point related to the extension's performance
  guides/v2.1/ext-best-practices/extension-coding/security-performance-data-bp.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4677 MQE-1482: Add MFTF Tests technical guidelines to "Technical Guidelines" topic on DevDocs
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.3.x, Major update, internal-dev

#4853 Release Note update for June 26 Hot Fix for Magento 2.3.2 and 2.3.1
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.x

#4855 Release note update for Magento 2.3.2 and 2.3.1 June 26 hot fix
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.x

#4856 Changed OVE to OVER ( it was confusing )
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: 2.3.x, Editorial, small changes

#4838 Adding data for bin/magento reference and composer dependencies
  _data/codebase/v2_1/cloud/composer_lock.json
  _data/codebase/v2_1/commerce/composer_lock.json
  _data/codebase/v2_1/open-source/bin-magento.yml
  _data/codebase/v2_1/open-source/composer_lock.json
  _data/codebase/v2_2/cloud/composer_lock.json
  _data/codebase/v2_2/commerce/composer_lock.json
  _data/codebase/v2_2/open-source/bin-magento.yml
  _data/codebase/v2_2/open-source/composer_lock.json
  _data/codebase/v2_3/cloud/composer_lock.json
  _data/codebase/v2_3/commerce/composer_lock.json
  _data/codebase/v2_3/open-source/bin-magento.yml
  _data/codebase/v2_3/open-source/composer_lock.json
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#4805 Recommend including gender as a translation variable
  guides/v2.1/frontend-dev-guide/translations/xlate.md
Labels: 2.3.x, Editorial, Partner: Mediotype, partners-contribution

#4854 Backward incompatible changes reference for 2.3.2, 2.2.9, 2.1.18
  _includes/backward-incompatible-changes/commerce/2.1.17-2.1.18.md
  _includes/backward-incompatible-changes/commerce/2.2.8-2.2.9.md
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3.2.md
  _includes/backward-incompatible-changes/open-source/2.1.17-2.1.18.md
  _includes/backward-incompatible-changes/open-source/2.2.8-2.2.9.md
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3.2.md
  guides/v2.1/release-notes/backward-incompatible-changes/reference.md
  guides/v2.2/release-notes/backward-incompatible-changes/reference.md
  guides/v2.3/release-notes/backward-incompatible-changes/reference.md
Labels: 2.1.17, 2.2.9, 2.3.2, Major update

#4778 Update architecture guide
  _data/toc/architecture-guide.yml
  _data/toc/configuration-guide.yml
  common/images/archi_diagrams_current.png
  guides/v2.1/architecture/archi_perspectives/arch_diagrams.md
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_and_areas.md
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_depend.md
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_intro.md
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_relationships.md
  guides/v2.1/architecture/archi_perspectives/domain_layer.md
  guides/v2.1/architecture/archi_perspectives/framework.md
  guides/v2.1/architecture/archi_perspectives/persist_layer.md
  guides/v2.1/architecture/archi_perspectives/present_layer.md
  guides/v2.1/architecture/archi_perspectives/service_layer.md
  guides/v2.1/architecture/archi_perspectives/tech-vision.md
  guides/v2.1/architecture/bk-architecture.md
  guides/v2.1/architecture/extensibility.md
  guides/v2.1/architecture/frontend_custom_strategies.md
  guides/v2.1/architecture/gdpr/magento-1x.md
  guides/v2.1/architecture/gdpr/magento-2x.md
  guides/v2.1/architecture/global_extensibility_features.md
  guides/v2.1/architecture/security_intro.md
  guides/v2.1/config-guide/secy/secy.md
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
  guides/v2.1/extension-dev-guide/versioning/check-version.md
  guides/v2.1/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.2/architecture/archi_perspectives/tech-vision.md
  guides/v2.2/architecture/frontend_custom_strategies.md
  guides/v2.2/coding-standards/technical-guidelines.md
  guides/v2.3/architecture/archi_perspectives/components/modules/mod_conventions.md
  guides/v2.3/architecture/archi_perspectives/components/modules/mod_depend_types.md
  guides/v2.3/architecture/archi_perspectives/tech-vision.md
  guides/v2.3/architecture/archi_perspectives/webapi-vision.md
  guides/v2.3/architecture/tech-stack.md
  guides/v2.3/extension-dev-guide/versioning/dependencies.md
  guides/v2.3/extension-dev-guide/versioning/index.md
Labels: 2.1.x, 2.2.x, 2.3.x, Site improvements

#4729 SemVer is not used
  release/policy/index.md
Labels: Editorial

#4862 Update the Module Reference Guide after 2.3.2 release
  _data/toc/module-reference-guide-2_3.yml
  guides/v2.3/mrg/b2b/CheckoutAddressSearchNegotiableQuote.md
  guides/v2.3/mrg/b2b/Company.md
  guides/v2.3/mrg/b2b/RequisitionList.md
  guides/v2.3/mrg/ce/GraphQlCache.md
  guides/v2.3/mrg/ce/InstantPurchase.md
  guides/v2.3/mrg/ce/Paypal.md
  guides/v2.3/mrg/ce/PaypalCaptcha.md
  guides/v2.3/mrg/ce/SampleData.md
  guides/v2.3/mrg/ce/Signifyd.md
  guides/v2.3/mrg/ce/VaultGraphQl.md
  guides/v2.3/mrg/ce/WebapiAsync.md
  guides/v2.3/mrg/ee/BundleStaging.md
  guides/v2.3/mrg/ee/CatalogImportExportStaging.md
  guides/v2.3/mrg/ee/CatalogInventoryStaging.md
  guides/v2.3/mrg/ee/CatalogRuleStaging.md
  guides/v2.3/mrg/ee/CatalogStaging.md
  guides/v2.3/mrg/ee/CatalogUrlRewriteStaging.md
  guides/v2.3/mrg/ee/CheckoutAddressSearch.md
  guides/v2.3/mrg/ee/CheckoutAddressSearchGiftRegistry.md
  guides/v2.3/mrg/ee/CheckoutStaging.md
  guides/v2.3/mrg/ee/CmsStaging.md
  guides/v2.3/mrg/ee/ConfigurableProductStaging.md
  guides/v2.3/mrg/ee/DownloadableStaging.md
  guides/v2.3/mrg/ee/ElasticsearchCatalogPermissions.md
  guides/v2.3/mrg/ee/GiftCardStaging.md
  guides/v2.3/mrg/ee/GiftMessageStaging.md
  guides/v2.3/mrg/ee/GiftWrappingStaging.md
  guides/v2.3/mrg/ee/GoogleOptimizerStaging.md
  guides/v2.3/mrg/ee/GroupedProductStaging.md
  guides/v2.3/mrg/ee/LayeredNavigationStaging.md
  guides/v2.3/mrg/ee/MsrpStaging.md
  guides/v2.3/mrg/ee/PaymentStaging.md
  guides/v2.3/mrg/ee/ProductVideoStaging.md
  guides/v2.3/mrg/ee/ReviewStaging.md
  guides/v2.3/mrg/ee/RewardStaging.md
  guides/v2.3/mrg/ee/RmaStaging.md
  guides/v2.3/mrg/ee/SalesRuleStaging.md
  guides/v2.3/mrg/ee/ScalableCheckout.md
  guides/v2.3/mrg/ee/ScalableInventory.md
  guides/v2.3/mrg/ee/ScalableOms.md
  guides/v2.3/mrg/ee/SearchStaging.md
  guides/v2.3/mrg/ee/Staging.md
  guides/v2.3/mrg/ee/VisualMerchandiser.md
  guides/v2.3/mrg/ee/WeeeStaging.md
Labels: 2.3.2, Major update, internal-dev

#4807 Adding the depends annotation to Integration Tests
  _data/toc/testing.yml
  guides/v2.1/test/integration/annotations/depends.md
  guides/v2.2/test/integration/annotations/depends.md
  guides/v2.3/test/integration/annotations/depends.md
Labels: 2.1.x, 2.2.x, 2.3.x, New topic, Partner: Atwix, partners-contribution

#4839 Cloud 2002.0.20 release
  _data/toc/cloud-guide.yml
  _includes/cloud/note-ece-tools-release-info.md
  guides/v2.1/cloud/bk-cloud.md
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-database.md
  guides/v2.1/cloud/docker/docker-development-debug.md
  guides/v2.1/cloud/docker/docker-development-testing.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/env/variables-cloud.md
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.1/cloud/env/variables-post-deploy.md
  guides/v2.1/cloud/live/stage-prod-test.md
  guides/v2.1/cloud/project/ece-tools-upgrade-project.md
  guides/v2.1/cloud/project/project-conf-files_magento-app.md
  guides/v2.1/cloud/reference/ece-tools-reference.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/docker/docker-development-testing.md
  guides/v2.2/cloud/env/variables-cloud.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-post-deploy.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/reference/ece-tools-reference.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/docker/docker-development-testing.md
  guides/v2.3/cloud/reference/ece-tools-reference.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, internal-dev

#4861 Add documentation for Payflow Link payment processor
  _data/toc/graphql.yml
  guides/v2.3/graphql/images/paypal-payflow-link.svg
  guides/v2.3/graphql/payment-methods/payflow-link.md
  guides/v2.3/graphql/reference/paypal-get-payflow-link-token.md
  guides/v2.3/graphql/reference/quote-payment-method.md
Labels: 2.3.3, New topic, internal-dev

#4863 Update PR template (2.1 EOL)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: internal-dev

#4864 Summer release digest
  _data/whats-new.yml
Labels: Editorial

#4865 Release note partner contribution tables added (2.3.2 and 2.2.9)
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
Labels: small changes

#4850 Updated Release Notes for Google Shopping ads Channel extension for version 2.0.1
  _data/compatibility.yml
  extensions/google-shopping-ads/release-notes/index.md
  release/index.md
Labels: 2.0 Google Shopping ads, Major update, internal-dev

#4826 Clarify module dependency rule wording
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, small changes

#4867 Add Marketplace link to Upcoming releases page.
  release/index.md
Labels: Site improvements, internal-dev, small changes

#4795 Add routes.yaml {all} option for route templates.
  _includes/cloud/note-pro-missing-self-service-options.md
  _includes/cloud/note-route-all-placeholder.md
  guides/v2.1/cloud/project/project-conf-files_routes.md
  guides/v2.1/cloud/project/project-routes-more-cache.md
  guides/v2.1/cloud/project/project-routes-more-redir.md
  guides/v2.1/cloud/project/project-routes-more-ssi.md
  guides/v2.2/cloud/project/project-conf-files_routes.md
  guides/v2.2/cloud/project/project-routes-more-redir.md
Labels: 2.1.x, 2.2.x, Major update, internal-dev

#4866 Fixed #4622 /guides/v2.3/install-gde/prereq/install-rabbitmq.html and v2.2
  guides/v2.2/install-gde/prereq/install-rabbitmq.md
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
Labels: 2.2.x, 2.3.x, Editorial

#4871 Add tag manager instead of Google Analytics
  _config.yml
  _includes/layout/header-scripts.html
Labels: Site improvements

#4679 Update the CLI upgrading topics
  _data/toc/software-update-guide.yml
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/comp-mgr/cli/upgrade-with-plugin.md
  guides/v2.3/comp-mgr/cli/upgrade-with-script.md
Labels: 2.3.x, New topic, internal-dev

#4874 MAGECLOUD-3860 clarify functional testing for ece-tools
  guides/v2.1/cloud/docker/docker-development-testing.md
  guides/v2.2/cloud/docker/docker-development-testing.md
Labels: 2.x, Technical, internal-dev
