Repository magento/devdocs, pull requests merged in 2019-12, with the labels that each got.

#6090 Sample fastly block by coutry code and user agent
  src/guides/v2.2/cloud/cdn/fastly-vcl-blacklist.md
Labels: 2.x, Progress: review, Technical

#6084 Clarify global scoped config options
  src/guides/v2.3/test/integration/annotations/magento-config-fixture.md
Labels: 2.3.x, Partner: JH, Progress: approved, Technical, partners-contribution

#6088 Fix syntax
  src/guides/v2.3/javascript-dev-guide/javascript/custom_js.md
Labels: 2.3.x, Editorial, Partner: Imagination Media, Progress: approved, partners-contribution

#6055 magento/devdocs#: Cloud. Add notice about “wizard:ideal-state”
  src/guides/v2.2/cloud/deploy/smart-wizards.md
  src/guides/v2.2/cloud/reference/ece-tools-reference.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: acceptance testing, partners-contribution

#6097 Updated instructions for using custom VCL code for blocking
  src/_data/toc/cloud-guide.yml
  src/_data/whats-new.yml
  src/guides/v2.2/cloud/cdn/fastly-vcl-blacklist.md
  src/guides/v2.2/cloud/cdn/fastly-vcl-blocking.md
  src/guides/v2.3/cloud/cdn/fastly-vcl-blacklist.md
  src/guides/v2.3/cloud/cdn/fastly-vcl-blocking.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6094 Web API allows to create Customer for admin and for guest user.
  src/guides/v2.2/rest/tutorials/orders/order-create-customer.md
Labels: Progress: approved

#6098 [site] Fix rake update tasks
  rakelib/check.rake
  rakelib/multirepo.rake
  rakelib/update.rake
Labels: Progress: approved, Site improvements

#6102 Clarify process to allocate disk space on Cloud envs
  src/guides/v2.2/cloud/project/manage-disk-space.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6087 Update operation-status-endpoints.md to add bulk/{bulkUuid}/operation-status/{status} description
  src/guides/v2.3/rest/operation-status-endpoints.md
Labels: Partner: Comwrap, Progress: changes requested, Technical, partners-contribution

#6092 Cache clean after modifying configuration file
  src/guides/v2.2/ext-best-practices/tutorials/dynamic-row-system-config.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical

#6106 Fix XML alignment
  src/guides/v2.2/extension-dev-guide/view-models.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Imagination Media, Progress: approved, partners-contribution

#6104 Updated What's New with changes since November 20
  src/_data/whats-new.yml
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6099 Resolve Code example issue
  src/guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#6113 Improved the JS Mixins documentation
  src/guides/v2.2/javascript-dev-guide/javascript/js_mixins.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6108 Minor maintenance of Inventory guides
  src/_includes/layout/after-site-header.html
  src/extensions/inventory-management/index.md
Labels: Progress: review

#6070 MAGECLOUD-3057 remove Xdebug hack
  src/guides/v2.2/cloud/howtos/debug.md
Labels: Progress: changes requested, Technical

#6117 Code compile and cache clean after copying fieldsets
  src/guides/v2.2/ext-best-practices/tutorials/copy-fieldsets.md
Labels: 2.2.x, 2.3.x, Partner: Ziffity, Progress: approved, Technical

#6121 Update fastly-vcl-blocking.md
  src/guides/v2.2/cloud/cdn/fastly-vcl-blocking.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6114 Update DynamicRows UI component documentation
  src/common/images/ui_comps/dynamicrows-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-dynamicrows.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6128 Adding a note related to CSV profiler
  src/guides/v2.2/config-guide/bootstrap/mage-profiler.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6126 empty lines removed
  src/guides/v2.2/frontend-dev-guide/templates/template-email.md
Labels: 2.2.x, 2.3.x, Editorial

#6122 Fixed command syntax
  src/guides/v2.2/cloud/project/project-conf-files_magento-app.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6129 Fixing the git config url after moving the content to /src folder
  _config.yml
Labels: Partner: Atwix, Site improvements, partners-contribution

#6130 Add IP addresses for Security Scanner tool
  src/guides/v2.2/cloud/live/live.md
Labels: 2.2.x, 2.3.x, Progress: review, Technical, internal-dev

#6133 Corrected the Docker compose override file name
  src/guides/v2.2/cloud/docker/docker-quick-reference.md
Labels: Progress: approved

#6109 Added missing link.
  src/guides/v2.2/pattern-library/getting-user-input/form_elements/form_elements.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#6137 Update config-cli-subcommands-cache.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Progress: review, Technical, partners-contribution, small changes

#6086 Order creation API endpoints updated for guest users
  src/guides/v2.2/rest/tutorials/orders/order-add-items.md
  src/guides/v2.2/rest/tutorials/orders/order-create-order.md
  src/guides/v2.2/rest/tutorials/orders/order-create-quote.md
  src/guides/v2.2/rest/tutorials/orders/order-prepare-checkout.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Ziffity, Progress: approved, Technical

#6139 Update ui_comp_linking_concept.md
  src/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
Labels: Partner: Webjump, Progress: approved, partners-contribution

#6136 Update Email UI component documentation
  src/common/images/ui_comps/ui-email-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-email.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6134 Add example for configuring the Paging UI component
  src/common/images/ui_comps/ui-paging-configured-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-paging.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6096 Update "Manage company users" to describe current features
  src/guides/v2.2/b2b/company-users.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, internal-dev, small changes

#6110 Cleanup of Admin Errors and Message Writing topic.
  src/guides/v2.2/design-styleguide/errors-and-messages/errors-and-messages.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: review

#6131 Update the documentation for Radioset UI component
  src/common/images/ui_comps/ui-radioset-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-radioset.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6127 Update OnOffColumn UI component documentation
  src/common/images/ui_comps/ui-onoffcolumn-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-onoffcolumn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6115 Add the documentation for DynamicRowsDragAndDrop UI component
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/dynamicrows-dnd-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-dynamicrows-dnd.md
  src/guides/v2.3/ui_comp_guide/components/ui-dynamicrows-dnd.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6135 MC-29345: ENGCOM: Update documentation (devdocs) according to 2.4
  src/_includes/contributor/2-4-submission.md
  src/_includes/contributor/labels.md
  src/_includes/contributor/pull-request-table.md
  src/guides/v2.2/contributor-guide/contributing.md
  src/guides/v2.3/contributor-guide/contributing.md
Labels: 2.2.x, 2.3.x, Progress: review, Technical

#6118 Adding additional options to modal widget.
  src/guides/v2.2/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6132 Updated module-file-structure.md
  src/guides/v2.3/extension-dev-guide/build/module-file-structure.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution

#6112 Added info about new docker:build option, --sync-engine=native
  src/guides/v2.2/cloud/docker/docker-config.md
  src/guides/v2.2/cloud/docker/docker-mode-developer.md
  src/guides/v2.2/cloud/docker/docker-quick-reference.md
  src/guides/v2.2/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6140 Small changes
  _config.yml
  src/common/images/ui_comps/ui-columns-list-result.png
  src/common/images/ui_comps/ui-email-result.png
  src/common/images/ui_comps/ui-onoffcolumn-result.png
  src/common/images/ui_comps/ui-paging-configured-result.png
  src/common/images/ui_comps/ui-radioset-result.png
  src/guides/v2.2/b2b/company-users.md
  src/guides/v2.2/cloud/project/project-conf-files_magento-app.md
  src/guides/v2.2/config-guide/bootstrap/mage-profiler.md
  src/guides/v2.2/design-styleguide/errors-and-messages/errors-and-messages.md
  src/guides/v2.2/frontend-dev-guide/templates/template-email.md
  src/guides/v2.2/javascript-dev-guide/widgets/widget_modal.md
  src/guides/v2.2/pattern-library/getting-user-input/form_elements/form_elements.md
  src/guides/v2.2/ui_comp_guide/components/ui-email.md
  src/guides/v2.2/ui_comp_guide/components/ui-onoffcolumn.md
  src/guides/v2.2/ui_comp_guide/components/ui-paging.md
  src/guides/v2.2/ui_comp_guide/components/ui-radioset.md
  src/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
  src/guides/v2.3/extension-dev-guide/build/module-file-structure.md
Labels: Progress: approved

#6120 Re-enable the module after modify the module load sequence
  src/guides/v2.2/ext-best-practices/tutorials/custom-widget.md
Labels: 2.2.x, 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6154 Adding output styling for CLI
  src/guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution

#6152 #6151 - Fix Schema location in queue.xml example for message queue co…
  src/guides/v2.3/extension-dev-guide/message-queues/config-mq.md
Labels: 2.3.x, Progress: approved, Technical, small changes

#6150 compile and cache clean after changing logging configuration
  src/guides/v2.2/config-guide/log/log-db.md
Labels: 2.2.x, 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6143 Stop indexing MTF docs
  src/robots.txt
Labels: Site improvements, internal-dev

#6149 code compile and cache clean after configure a custom cron
  src/guides/v2.2/config-guide/cron/custom-cron-tut.md
Labels: 2.2.x, 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6156 Add Marketpace User Guide to the site search
  Gemfile.lock
  src/_includes/layout/header-scripts.html
Labels: Progress: approved, Site improvements

#6148 Added colorPicker binding
  src/guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution, small changes

#6147 Added template binding examples
  src/guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution, small changes

#6162 Update rwd-breakpoints.md
  src/guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#6146 Added ko scope virtual element example
  src/guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#6161 Fixed internal links
  src/guides/v2.2/config-guide/varnish/config-varnish.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: 2.x, Editorial, internal-dev, small changes

#6144 Fix formatting in the Sales module description and add 'rake convert'
  Rakefile
  bin/kramdown
  src/guides/v2.2/mrg/ce/Sales.md
Labels: 2.2.x, Editorial, Progress: approved, Site improvements

#6174 Sync 2.3.4-develop
  Gemfile.lock
  Rakefile
  _config.yml
  bin/kramdown
  src/_includes/layout/header-scripts.html
  src/common/images/ui_comps/ui-columns-list-result.png
  src/common/images/ui_comps/ui-email-result.png
  src/common/images/ui_comps/ui-onoffcolumn-result.png
  src/common/images/ui_comps/ui-paging-configured-result.png
  src/common/images/ui_comps/ui-radioset-result.png
  src/guides/v2.2/b2b/company-users.md
  src/guides/v2.2/cloud/project/project-conf-files_magento-app.md
  src/guides/v2.2/config-guide/bootstrap/mage-profiler.md
  src/guides/v2.2/design-styleguide/errors-and-messages/errors-and-messages.md
  src/guides/v2.2/ext-best-practices/tutorials/custom-widget.md
  src/guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.2/frontend-dev-guide/templates/template-email.md
  src/guides/v2.2/javascript-dev-guide/widgets/widget_modal.md
  src/guides/v2.2/mrg/ce/Sales.md
  src/guides/v2.2/pattern-library/getting-user-input/form_elements/form_elements.md
  src/guides/v2.2/ui_comp_guide/components/ui-email.md
  src/guides/v2.2/ui_comp_guide/components/ui-onoffcolumn.md
  src/guides/v2.2/ui_comp_guide/components/ui-paging.md
  src/guides/v2.2/ui_comp_guide/components/ui-radioset.md
  src/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
  src/guides/v2.3/extension-dev-guide/build/module-file-structure.md
  src/robots.txt
Labels: Progress: approved

#6175 Sync 2.3.5-develop
  Gemfile.lock
  Rakefile
  _config.yml
  bin/kramdown
  src/_includes/layout/header-scripts.html
  src/common/images/ui_comps/ui-columns-list-result.png
  src/common/images/ui_comps/ui-email-result.png
  src/common/images/ui_comps/ui-onoffcolumn-result.png
  src/common/images/ui_comps/ui-paging-configured-result.png
  src/common/images/ui_comps/ui-radioset-result.png
  src/guides/v2.2/b2b/company-users.md
  src/guides/v2.2/cloud/project/project-conf-files_magento-app.md
  src/guides/v2.2/config-guide/bootstrap/mage-profiler.md
  src/guides/v2.2/design-styleguide/errors-and-messages/errors-and-messages.md
  src/guides/v2.2/ext-best-practices/tutorials/custom-widget.md
  src/guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.2/frontend-dev-guide/templates/template-email.md
  src/guides/v2.2/javascript-dev-guide/widgets/widget_modal.md
  src/guides/v2.2/mrg/ce/Sales.md
  src/guides/v2.2/pattern-library/getting-user-input/form_elements/form_elements.md
  src/guides/v2.2/ui_comp_guide/components/ui-email.md
  src/guides/v2.2/ui_comp_guide/components/ui-onoffcolumn.md
  src/guides/v2.2/ui_comp_guide/components/ui-paging.md
  src/guides/v2.2/ui_comp_guide/components/ui-radioset.md
  src/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
  src/guides/v2.3/extension-dev-guide/build/module-file-structure.md
  src/robots.txt
Labels: Progress: approved

#6189 Removing duplicate mailto in email request link
  src/release/index.md
Labels: Editorial, small changes

#6187 magento/devdocs#: Fix visual bug on the “Create an integration” page
  src/guides/v2.2/get-started/create-integration.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6186 magento/devdocs#4651: /guides/v2.3/config-guide/cron/custom-cron-tut.html
  src/guides/v2.2/config-guide/cron/custom-cron-tut.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6181 magento/devdocs#5926: Install Guide: PHP settings topic has formatting issues
  src/guides/v2.2/install-gde/prereq/php-settings.md
Labels: 2.2.x, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6123 GraphQL: Describe staging features
  src/_data/toc/graphql.yml
  src/_data/whats-new.yml
  src/common/images/graphql/graphql-authorization.png
  src/guides/v2.3/graphql/authorization-tokens.md
  src/guides/v2.3/graphql/get-customer-authorization-token.md
  src/guides/v2.3/graphql/images/graphql-authorization.png
  src/guides/v2.3/graphql/mutations/redeem-giftcard-balance.md
  src/guides/v2.3/graphql/queries/index.md
  src/guides/v2.3/graphql/queries/wishlist.md
  src/guides/v2.3/graphql/send-request.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-add-product-to-cart.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-customer.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-payment-method.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-place-order.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-method.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shopping-cart.md
  src/guides/v2.3/graphql/tutorials/checkout/index.md
Labels: 2.3.5, Major update, Progress: approved, internal-dev

#6107 Add topic for new email template directives
  src/guides/v2.2/frontend-dev-guide/templates/template-email.md
  src/guides/v2.3/frontend-dev-guide/templates/template-email-migration.md
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
Labels: 2.3.4, New topic, Progress: approved

#6190 Fix versionless cloud links
  src/_data/toc/release-notes.yml
  src/guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  src/guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  src/release/index.md
Labels: Progress: approved

#6183 Update the documentation for the LinkColumn UI component
  src/common/images/ui_comps/ui-linkcolumn-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-linkcolumn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6185 Update Filters UI component documentation
  src/common/images/ui_comps/ui-filters-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-filters.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6176 Update documentation for the Checkbox UI component
  src/guides/v2.2/ui_comp_guide/components/ui-checkbox.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6182 Update documentation for the FiltersChips UI component
  src/common/images/ui_comps/ui-filterschips-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-filterschips.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6159 Update the documentation for the Hidden UI component
  src/common/images/ui_comps/ui-hidden-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-hidden.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical

#6172 Update documentation for the File UI component
  src/common/images/ui_comps/ui-file-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-file.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6173 Added info about manually disabling and enabling cron jobs
  src/guides/v2.2/cloud/configure/setup-cron-jobs.md
Labels: 2.x, Progress: changes requested, internal-dev

#6167 Information added for all the nodes in env.php
  src/guides/v2.2/config-guide/prod/config-reference-envphp.md
Labels: 2.3.x, Major update, Partner: Ziffity, Progress: review, partners-contribution

#6192 Performance best practices add apcu info
  src/guides/v2.2/performance-best-practices/deployment-flow.md
  src/guides/v2.2/performance-best-practices/software.md
  src/guides/v2.3/performance-best-practices/software.md
Labels: 2.x, Progress: approved, Technical

#6177 Update documentation for the SelectColumn UI component
  src/common/images/ui_comps/ui-selectcolumn-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-selectcolumn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6163 Update rwd-breakpoints.md
  src/guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#6188 Update documentation for the Sizes UI component
  src/common/images/ui_comps/ui-sizes-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-sizes.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6201 Small changes
  src/common/images/ui_comps/ui-file-result.png
  src/common/images/ui_comps/ui-fileuploader-result.png
  src/common/images/ui_comps/ui-filterschips-result.png
  src/common/images/ui_comps/ui-hidden-result.png
  src/common/images/ui_comps/ui-selectcolumn-result.png
  src/common/images/ui_comps/ui-sizes-result.png
  src/guides/v2.2/config-guide/cron/custom-cron-tut.md
  src/guides/v2.2/config-guide/log/log-db.md
  src/guides/v2.2/config-guide/varnish/config-varnish.md
  src/guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
  src/guides/v2.2/get-started/create-integration.md
  src/guides/v2.2/install-gde/prereq/php-settings.md
  src/guides/v2.2/ui_comp_guide/components/ui-file.md
  src/guides/v2.2/ui_comp_guide/components/ui-fileuploader.md
  src/guides/v2.2/ui_comp_guide/components/ui-filterschips.md
  src/guides/v2.2/ui_comp_guide/components/ui-hidden.md
  src/guides/v2.2/ui_comp_guide/components/ui-selectcolumn.md
  src/guides/v2.2/ui_comp_guide/components/ui-sizes.md
  src/guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
  src/guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  src/release/index.md
Labels: Progress: approved

#6178 Update MultiselectColumn column UI component documentation
  src/common/images/ui_comps/ui-multiselectcolumn-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-multiselectcolumn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#6209 Indexer reset command added with examples
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Ziffity, Progress: approved, partners-contribution

#6204 Small typo in code example
  src/guides/v2.2/extension-dev-guide/proxies.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#6196 Fixing typo in apc codeblock
  src/guides/v2.2/performance-best-practices/software.md
  src/guides/v2.3/performance-best-practices/software.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, small changes

#6180 magento/devdocs#: Fix incorrect markdown in UI Text component.
  src/guides/v2.2/ui_comp_guide/components/ui-text.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6205 magento/devdocs#6101: Feedback on Create and manage users topic
  src/cloud/project/user-admin.md
Labels: 2.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6208 Update Input UI component documentation
  src/common/images/ui_comps/ui-input-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-input.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6210 Update Expandable UI component documentation
  src/common/images/ui_comps/ui-expandable-expanded-result.png
  src/common/images/ui_comps/ui-expandable-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-expandable-column.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6203 MAGECLOUD-4738: [DOCS] Document All Backward-incompatible Changes in ECE-Tools 2002.1.0
  src/cloud/release-notes/backward-incompatible-changes.md
Labels: Progress: review

#6213 magento/devdocs#: Add applyCouponToCart mutation API errors
  src/guides/v2.3/graphql/mutations/apply-coupon.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6207 Update documentation for the Text UI component
  src/common/images/ui_comps/ui-text-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-text.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6219 Sentence Correction.
  src/guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#6211 Update InsertListing UI component documentation
  src/common/images/ui_comps/ui-insertlisting-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-insertlisting.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6217 Added cli command for static content signing to enable/disable
  src/guides/v2.2/config-guide/cache/static-content-signing.md
Labels: 2.2.x, 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution, small changes

#6199 Add full urn path to example XML files on copy fieldsets tutorial page
  src/guides/v2.2/ext-best-practices/tutorials/copy-fieldsets.md
Labels: Progress: approved

#6142 Fix plugins prioritization order information
  src/guides/v2.2/extension-dev-guide/plugins.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Webjump, Progress: review, partners-contribution

#6236 MIssing semicolon added.
  src/guides/v2.3/coding-standards/code-standard-demarcation.md
Labels: 2.3.x, Editorial, Progress: approved, small changes

#6222 Update docker-config.md
  src/cloud/docker/docker-config.md
Labels: Editorial, Partner: Rave Digital, Progress: approved, partners-contribution, small changes

#6235 Improving the Ui Form Component documentation
  src/guides/v2.2/ui_comp_guide/components/ui-form.md
  src/guides/v2.3/ui_comp_guide/components/ui-form.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6231 Period(".") added and Extra colon removed
  src/guides/v2.2/coding-standards/code-standard-less.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#6232 Remove duplicated </a> tag.
  src/guides/v2.3/coding-standards/code-standard-demarcation.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6237 Word "Differences" changed to "Relationship"
  src/guides/v2.2/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6239 Italic style removed from the word "is"
  src/guides/v2.2/frontend-dev-guide/themes/js-bundling.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6229 Added information to block class attribute
  src/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#6220 magento/devdocs#: Add removeCouponFromCart mutation API errors
  src/guides/v2.3/graphql/mutations/remove-coupon.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6234 Update the documentation for the urlInput UI component
  src/common/images/ui_comps/ui-urlinput-category-link-result.png
  src/common/images/ui_comps/ui-urlinput-default-link-result.png
  src/common/images/ui_comps/ui-urlinput-product-link-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-urlinput.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6158 Update documentation for the Textarea UI component
  src/common/images/ui_comps/ui-textarea-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-textarea.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical

#6166 Updated link to proper format
  src/guides/v2.2/frontend-dev-guide/css-topics/css-themes.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#6218 Update InsertForm UI component documentation
  src/common/images/ui_comps/ui-insertform-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-insertform.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6238 Introduced a space between "Translate" and "Inline"
  src/guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Ziffity, partners-contribution, small changes

#6242 Small changes
  src/cloud/docker/docker-config.md
  src/common/images/ui_comps/ui-expandable-expanded-result.png
  src/common/images/ui_comps/ui-expandable-result.png
  src/common/images/ui_comps/ui-input-result.png
  src/common/images/ui_comps/ui-insertform-result.png
  src/common/images/ui_comps/ui-insertlisting-result.png
  src/common/images/ui_comps/ui-text-result.png
  src/common/images/ui_comps/ui-textarea-result.png
  src/common/images/ui_comps/ui-urlinput-category-link-result.png
  src/common/images/ui_comps/ui-urlinput-default-link-result.png
  src/common/images/ui_comps/ui-urlinput-product-link-result.png
  src/guides/v2.2/coding-standards/code-standard-less.md
  src/guides/v2.2/config-guide/cache/static-content-signing.md
  src/guides/v2.2/ext-best-practices/tutorials/copy-fieldsets.md
  src/guides/v2.2/extension-dev-guide/proxies.md
  src/guides/v2.2/frontend-dev-guide/css-topics/css-themes.md
  src/guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
  src/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.2/frontend-dev-guide/themes/js-bundling.md
  src/guides/v2.2/frontend-dev-guide/themes/theme-inherit.md
  src/guides/v2.2/performance-best-practices/software.md
  src/guides/v2.2/ui_comp_guide/components/ui-expandable-column.md
  src/guides/v2.2/ui_comp_guide/components/ui-form.md
  src/guides/v2.2/ui_comp_guide/components/ui-input.md
  src/guides/v2.2/ui_comp_guide/components/ui-insertform.md
  src/guides/v2.2/ui_comp_guide/components/ui-insertlisting.md
  src/guides/v2.2/ui_comp_guide/components/ui-text.md
  src/guides/v2.2/ui_comp_guide/components/ui-textarea.md
  src/guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
  src/guides/v2.3/coding-standards/code-standard-demarcation.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/graphql/mutations/apply-coupon.md
  src/guides/v2.3/graphql/mutations/remove-coupon.md
  src/guides/v2.3/performance-best-practices/software.md
  src/guides/v2.3/ui_comp_guide/components/ui-form.md
  src/guides/v2.3/ui_comp_guide/components/ui-urlinput.md
Labels: Progress: approved, internal-dev

#6216 Added a warning about vcl snippet format
  src/cloud/cdn/cloud-vcl-custom-snippets.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6247 Remove version references for NGINX and Debian
  src/cloud/architecture/pro-architecture.md
  src/cloud/basic-information/starter-architecture.md
  src/cloud/requirements/cloud-requirements.md
Labels: Progress: approved, Technical, internal-dev

#6259 Improvement on "Overview of Magento's Icon CSS"
  src/guides/v2.2/frontend-dev-guide/css-topics/using-fonts.md
Labels: Partner: Ziffity, Progress: approved, Technical, partners-contribution, small changes

#6268 Update the documentation for the Checkboxset UI component
  src/common/images/ui_comps/ui-checkboxset-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-checkboxset.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6266 Add examples for the Checkbox UI component
  src/common/images/ui_comps/ui-checkbox-result.png
  src/common/images/ui_comps/ui-radio-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-checkbox.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6265 Improve the example of declaring the command name
  src/guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution, small changes

#6264 Add the example of how InsertListing component integrates with the Modal component
  src/common/images/ui_comps/ui-insertlisting-modal-result.png
  src/common/images/ui_comps/ui-insertlisting-open-button-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-insertlisting.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6263 Add the example of how InsertForm component integrates with the Modal component
  src/common/images/ui_comps/ui-insertform-modal-result.png
  src/common/images/ui_comps/ui-insertform-open-button-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-insertform.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Progress: review, Technical, partners-contribution, small changes

#6269 Update documentation for wysiwyg ui component
  src/common/images/ui_comps/ui-wysiwyg-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-wysiwyg.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6252 Period(".") added.
  src/guides/v2.2/contributor-guide/contributing.md
  src/guides/v2.2/frontend-dev-guide/css-topics/css-overview.md
  src/guides/v2.2/frontend-dev-guide/css-topics/css-themes.md
  src/guides/v2.2/frontend-dev-guide/tools/using_grunt.md
  src/guides/v2.2/frontend-dev-guide/translations/translate_practice.md
  src/guides/v2.2/frontend-dev-guide/translations/xlate.md
  src/guides/v2.3/frontend-dev-guide/translations/xlate.md
Labels: Editorial, Partner: Ziffity, Progress: changes requested, partners-contribution, small changes

#6241 Providing the way how a page type can be created for a new route
  src/common/images/routing-page-type-result.png
  src/guides/v2.2/extension-dev-guide/routing.md
  src/guides/v2.3/extension-dev-guide/routing.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution, small changes

#6271 Update xss-protection.md
  src/guides/v2.2/extension-dev-guide/xss-protection.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, small changes

#6244 Add support for DELETE async calls
  src/guides/v2.3/rest/asynchronous-web-endpoints.md
  src/guides/v2.3/rest/bulk-endpoints.md
Labels: 2.3.x, Partner: Comwrap, Progress: approved, Technical, partners-contribution, small changes

#6270 Removed invalid escape method - escapeHtmlAttribute
  src/guides/v2.2/extension-dev-guide/xss-protection.md
Labels: 2.2.x, 2.3.x, Partner: Ziffity, Technical, partners-contribution, small changes

#6267 CLI commands added for custom indexer
  src/guides/v2.2/extension-dev-guide/indexing-custom.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6274 Update supported browsers
  src/_includes/browsers/supported-browsers.md
Labels: 2.2.x, 2.3.x, Editorial, internal-dev, small changes

#6233 Add the documentation for the CheckboxToggleNotice UI component
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/checkbox-toggle-notice-1-result.png
  src/common/images/ui_comps/checkbox-toggle-notice-2-result.png
  src/guides/v2.2/ui_comp_guide/components/ui-checkbox-toggle-notice.md
  src/guides/v2.3/ui_comp_guide/components/ui-checkbox-toggle-notice.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: approved, partners-contribution

#6226 New Page: Form Validation
  src/_data/toc/frontend-developer-guide.yml
  src/guides/v2.2/frontend-dev-guide/validations/form-validation.md
  src/guides/v2.3/frontend-dev-guide/validations/form-validation.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Zilker Technology, Progress: approved, partners-contribution

#6215 Updates for ece-tools 2002.1.0 backwards incompatible changes
  src/_data/toc/cloud-guide.yml
  src/cloud/configure/setup-cron-jobs.md
  src/cloud/deploy/static-content-deployment.md
  src/cloud/docker/docker-development-testing.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/env/variables-post-deploy.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-conf-files_services.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Progress: review, Technical, internal-dev

#6273 Small changes
  src/_includes/browsers/supported-browsers.md
  src/common/images/routing-page-type-result.png
  src/common/images/ui_comps/ui-checkbox-result.png
  src/common/images/ui_comps/ui-checkboxset-result.png
  src/common/images/ui_comps/ui-insertform-modal-result.png
  src/common/images/ui_comps/ui-insertform-open-button-result.png
  src/common/images/ui_comps/ui-insertlisting-modal-result.png
  src/common/images/ui_comps/ui-insertlisting-open-button-result.png
  src/common/images/ui_comps/ui-radio-result.png
  src/common/images/ui_comps/ui-wysiwyg-result.png
  src/guides/v2.2/contributor-guide/contributing.md
  src/guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.2/extension-dev-guide/indexing-custom.md
  src/guides/v2.2/extension-dev-guide/routing.md
  src/guides/v2.2/extension-dev-guide/xss-protection.md
  src/guides/v2.2/frontend-dev-guide/css-topics/css-overview.md
  src/guides/v2.2/frontend-dev-guide/css-topics/css-themes.md
  src/guides/v2.2/frontend-dev-guide/css-topics/using-fonts.md
  src/guides/v2.2/frontend-dev-guide/tools/using_grunt.md
  src/guides/v2.2/frontend-dev-guide/translations/translate_practice.md
  src/guides/v2.2/frontend-dev-guide/translations/xlate.md
  src/guides/v2.2/ui_comp_guide/components/ui-checkbox.md
  src/guides/v2.2/ui_comp_guide/components/ui-checkboxset.md
  src/guides/v2.2/ui_comp_guide/components/ui-insertform.md
  src/guides/v2.2/ui_comp_guide/components/ui-insertlisting.md
  src/guides/v2.3/extension-dev-guide/routing.md
  src/guides/v2.3/frontend-dev-guide/translations/xlate.md
  src/guides/v2.3/rest/asynchronous-web-endpoints.md
  src/guides/v2.3/rest/bulk-endpoints.md
  src/guides/v2.3/ui_comp_guide/components/ui-wysiwyg.md
Labels: Progress: approved, internal-dev

#6246 Added additional step in add custom field document
  src/guides/v2.2/howdoi/checkout/checkout_custom_checkbox.md
Labels: 2.2.x, 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution, small changes

#6225 Added example for layout block
  src/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution, small changes

#6191 Add a section for industry regulation compliance
  src/_data/main-nav.yml
  src/_data/toc/compliance.yml
  src/compliance/industry-compliance.md
  src/compliance/privacy/backend-data-access-points.svg
  src/compliance/privacy/backend-data-entry-points.svg
  src/compliance/privacy/ccpa.md
  src/compliance/privacy/frontend-data-access-points.svg
  src/compliance/privacy/frontend-data-entry-points.svg
  src/compliance/privacy/gdpr.md
  src/compliance/privacy/pi-data-reference-m1.md
  src/compliance/privacy/pi-data-reference-m2.md
  src/guides/v2.2/architecture/gdpr/magento-2x.md
  src/guides/v2.3/architecture/gdpr/backend-data-access-points.svg
  src/guides/v2.3/architecture/gdpr/backend-data-entry-points.svg
  src/guides/v2.3/architecture/gdpr/frontend-data-access-points.svg
  src/guides/v2.3/architecture/gdpr/frontend-data-entry-points.svg
  src/guides/v2.3/architecture/gdpr/magento-1x.md
  src/guides/v2.3/architecture/gdpr/magento-2x.md
Labels: New topic, Progress: review, internal-dev

#6251 Updated Docker database container with info about setting CRYPT_KEY o…
  src/cloud/docker/docker-database.md
  src/cloud/env/variables-deploy.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/setup/first-time-setup-import-import.md
  src/guides/v2.2/release-notes/ReleaseNotes2.2.2EE.md
Labels: Progress: review

#6281 Apply small changes
  src/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.2/howdoi/checkout/checkout_custom_checkbox.md
Labels: Progress: approved, internal-dev

#6284 Removed symlink info from README
  .github/CONTRIBUTING.md
Labels: Progress: approved, internal-dev

#6286 Magento file system owner doesn't need sudo previlage.
  src/_includes/install/file-system-perms-twouser_22.md
Labels: Editorial, Progress: approved, small changes

#6240 Improvement - Getting a CMS Block in phtml
  src/guides/v2.2/frontend-dev-guide/templates/template-override.md
Labels: 2.2.x, Partner: Ziffity, Progress: changes requested, Technical, partners-contribution, small changes

#6275 Providing some useful information on how to provide classes to blocks…
  src/common/images/block-class-result.png
  src/common/images/container-classes-result.png
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution, small changes

#6289 Update the documentation for the Column UI component
  src/guides/v2.3/ui_comp_guide/components/ui-column.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6287 Update documentation for the Button UI component
  src/common/images/ui_comps/ui-form-buttons-example.png
  src/guides/v2.3/ui_comp_guide/components/ui-button.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6290 Update documentation for the HtmlContent UI component
  src/common/images/ui_comps/ui-htmlcontent-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-htmlcontent.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6292 Improving the RequireJS documentation with another available config
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6276 Added cache types in cache clean command
  src/guides/v2.2/frontend-dev-guide/themes/debug-theme.md
Labels: 2.2.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6278 Added layout block example
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution, small changes

#6288 Adding additional step in checkout customization
  src/guides/v2.2/howdoi/checkout/checkout_shipping_methods.md
Labels: 2.2.x, Partner: Ziffity, Progress: changes requested, Technical, partners-contribution, small changes

#6227 Added example and made content consistent in View Model page
  src/guides/v2.2/extension-dev-guide/view-models.md
  src/guides/v2.3/extension-dev-guide/view-models.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution, small changes

#6249 Fixed subtopics of "Import existing code into a project"
  src/cloud/setup/first-time-setup-import-import.md
  src/cloud/setup/first-time-setup-import-prepare.md
  src/common/images/cloud_cloud-git-214.png
  src/common/images/cloud_cloud-git-233.png
  src/common/images/cloud_cloud-git_raw.png
Labels: 2.x, Partner: Atwix, Progress: review, Technical, partners-contribution, small changes

#6295 Small changes
  src/_includes/install/file-system-perms-twouser_22.md
  src/cloud/setup/first-time-setup-import-import.md
  src/cloud/setup/first-time-setup-import-prepare.md
  src/common/images/block-class-result.png
  src/common/images/cloud_cloud-git-214.png
  src/common/images/cloud_cloud-git-233.png
  src/common/images/cloud_cloud-git_raw.png
  src/common/images/container-classes-result.png
  src/common/images/ui_comps/ui-form-buttons-example.png
  src/common/images/ui_comps/ui-htmlcontent-result.png
  src/guides/v2.2/extension-dev-guide/view-models.md
  src/guides/v2.2/frontend-dev-guide/templates/template-override.md
  src/guides/v2.2/frontend-dev-guide/themes/debug-theme.md
  src/guides/v2.2/howdoi/checkout/checkout_shipping_methods.md
  src/guides/v2.3/extension-dev-guide/view-models.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
  src/guides/v2.3/ui_comp_guide/components/ui-button.md
  src/guides/v2.3/ui_comp_guide/components/ui-column.md
  src/guides/v2.3/ui_comp_guide/components/ui-htmlcontent.md
Labels: Progress: approved, internal-dev

#6298 Fixed file redirects to work with versionless Cloud Guide
  src/cloud/architecture/cloud-architecture.md
  src/cloud/architecture/pro-architecture.md
  src/cloud/architecture/pro-develop-deploy-workflow.md
  src/cloud/before/before-setup-env-2_clone.md
  src/cloud/before/before-setup-env-install.md
  src/cloud/before/before-workspace-magento-prereqs.md
  src/cloud/before/before-workspace-ssh.md
  src/cloud/cdn/cloud-fastly-custom-response.md
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/cdn/fastly-vcl-badreferer.md
  src/cloud/cdn/fastly-vcl-blocking.md
  src/cloud/cdn/fastly-vcl-whitelist.md
  src/cloud/cdn/fastly-vcl-wordpress.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/deploy/smart-wizards.md
  src/cloud/docker/docker-config.md
  src/cloud/env/environments-start.md
  src/cloud/env/environments.md
  src/cloud/env/variables-deploy.md
  src/cloud/howtos/install-components.md
  src/cloud/live/stage-prod-live.md
  src/cloud/onboarding/onboarding-tasks.md
  src/cloud/project/ece-tools-update.md
  src/cloud/project/log-locations.md
  src/cloud/project/project-webint-branch.md
  src/cloud/reference/cloud-composer.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/git-integration.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/setup/first-time-deploy.md
  src/cloud/setup/first-time-setup.md
  src/cloud/trouble/troubleshoot-deployment.md
Labels: 2.x, Editorial, Progress: review, internal-dev
