Repository magento/devdocs, pull requests merged in 2019-09, with the labels that each got.

#5314 Fixed some incorrect path for theme directory
  guides/v2.2/frontend-dev-guide/css-topics/gulp-sass.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical

#5312 Update rwd-breakpoints.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Webjump, Progress: approved, partners-contribution

#5308 magento/devdocs#4792: Clarify command-line update prereq steps
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#5191 Wrong arguments for Stopwords directory
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
Labels: 2.3.x, Progress: approved, Technical

#5307 Adding an additional common layout customization
  common/images/cms-block-reference.png
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
  guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#5306 magento/devdocs#5235: Invalid example in CSS in responsive design topic
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5272 Update the Async API page
  guides/v2.3/extension-dev-guide/async-operations.md
Labels: Progress: approved

#5315 Update first-time-setup-import-import.md
  guides/v2.2/cloud/setup/first-time-setup-import-import.md
Labels: 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution, small changes

#5309 Fix minor typo in Dependency Injection documentation
  guides/v2.2/extension-dev-guide/build/di-xml-file.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5302 magento/devdocs#: Configure migration. Editorial
  guides/v2.2/migration/migration-tool-configure.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5318 Fixing layout example typo
  guides/v2.2/extension-dev-guide/routing.md
  guides/v2.3/extension-dev-guide/routing.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#5324 Sync develop with master
  _data/codebase/v2_2/open-source/bin-magento.yml
  _data/codebase/v2_3/open-source/bin-magento.yml
  _data/toc/rest-api.yml
  _data/whats-new.yml
  _includes/config/message-queue-consumers.md
  common/images/cloud/cloud-pro-project-access.png
  common/images/cloud/cloud-starter-project-access.png
  common/images/cms-block-reference.png
  guides/v2.2/cloud/configure/setup-cron-jobs.md
  guides/v2.2/cloud/setup/first-time-setup-import-import.md
  guides/v2.2/ext-best-practices/extension-coding/security-performance-data-bp.md
  guides/v2.2/extension-dev-guide/package/package_module.md
  guides/v2.2/extension-dev-guide/plugins.md
  guides/v2.2/frontend-dev-guide/css-topics/gulp-sass.md
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_css.md
  guides/v2.2/frontend-dev-guide/templates/template-email.md
  guides/v2.2/install-gde/composer.md
  guides/v2.2/rest/modules/sales/refunds.md
  guides/v2.2/test/js/jasmine.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
  guides/v2.3/ext-best-practices/extension-coding/security-performance-data-bp.md
  guides/v2.3/extension-dev-guide/async-operations.md
  guides/v2.3/extension-dev-guide/package/package_module.md
  guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
  guides/v2.3/install-gde/composer.md
  guides/v2.3/rest/modules/sales/refunds.md
Labels: Progress: approved, internal-dev

#5279 Cloud 2002.0.21
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-development-debug.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/docker/docker-config.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, Major update, Progress: review, internal-dev

#5289 MC-19250: The stuck deployment on the Cloud because of consumers
  _includes/config/consumers.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-lock.md
  guides/v2.3/install-gde/install/cli/install-cli-install.md
  guides/v2.3/install-gde/install/cli/install-cli-subcommands-consumers.md
Labels: 2.3.x, Progress: approved, Technical, internal-dev

#5329 update version constraint Magento Cloud
  guides/v2.3/cloud/project/project-upgrade.md
Labels: 2.3.x, Partner: Space 48, Progress: approved, Technical, partners-contribution, small changes

#5204 Indexing overview. Add EE indexers
  guides/v2.2/extension-dev-guide/indexing.md
  guides/v2.3/extension-dev-guide/indexing.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#5327 Providing a way of how data can be validated before importing it.
  common/images/ext-best-practices/import-validation.png
  guides/v2.2/ext-best-practices/tutorials/custom-import-entity.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: review, Technical, partners-contribution

#5325 Removed duplicate explanation for "You must not hard-code inline Java…
  guides/v2.2/coding-standards/code-standard-demarcation.md
  guides/v2.3/coding-standards/code-standard-demarcation.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5326 Providing an example of button ui component
  common/images/ui_comps/listing_button.png
  guides/v2.2/ui_comp_guide/components/ui-button.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution

#5322 magento/devdocs#1547: Migrating queue.xml to seperate queue_consumer.xml, queue_publisher.xml and queue_topology.xml not working
  guides/v2.3/config-guide/config/config-files.md
  guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/extension-dev-guide/message-queues/message-queues.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#5096 Updated javascript codebase changes version increase scenarios
  guides/v2.2/extension-dev-guide/versioning/codebase-changes.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, small changes

#5299 Added escapeCss function
  guides/v2.3/frontend-dev-guide/templates/template-security.md
Labels: 2.3.x, Major update, Progress: review, internal-dev

#5332 Add more information about the output attribute for containers
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, 2.3.x, Major update, Progress: approved

#5333 Update variables-deploy.md
  guides/v2.2/cloud/env/variables-deploy.md
Labels: Editorial, Progress: approved, internal-dev

#5334 Moved environment variable changes to correct section
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: Progress: review, internal-dev, small changes

#5340 Sync develop with master
  common/images/ext-best-practices/import-validation.png
  common/images/ui_comps/listing_button.png
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-development-debug.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/coding-standards/code-standard-demarcation.md
  guides/v2.2/ext-best-practices/tutorials/custom-import-entity.md
  guides/v2.2/extension-dev-guide/indexing.md
  guides/v2.2/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/ui_comp_guide/components/ui-button.md
  guides/v2.3/cloud/docker/docker-config.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
  guides/v2.3/coding-standards/code-standard-demarcation.md
  guides/v2.3/config-guide/config/config-files.md
  guides/v2.3/extension-dev-guide/indexing.md
  guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/extension-dev-guide/message-queues/message-queues.md
  guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.3/frontend-dev-guide/templates/template-security.md
Labels: Progress: approved, internal-dev

#5338 Remove unnecessary visible backticks
  guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Space 48, Progress: approved, partners-contribution, small changes

#5336 Factory entity is removed from 'codegen-over-why' section
  guides/v2.2/extension-dev-guide/code-generation.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, small changes

#5341 Updated type parameter description
  guides/v2.2/cloud/project/project-conf-files_services.md
Labels: Progress: approved

#5342 Small changes
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/extension-dev-guide/build/di-xml-file.md
  guides/v2.2/extension-dev-guide/code-generation.md
  guides/v2.2/extension-dev-guide/routing.md
  guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.md
  guides/v2.3/cloud/project/project-upgrade.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
  guides/v2.3/extension-dev-guide/routing.md
Labels: Progress: review

#5343 Fix the outdated "Compile LESS using Grunt" documentation
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/tools/using_grunt.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5347 fix external mutagen link
  guides/v2.2/cloud/docker/docker-config.md
Labels: Editorial, Progress: approved, internal-dev

#5355 Adjusted the widget documentations
  guides/v2.2/javascript-dev-guide/widgets/widget-multiselect.md
  guides/v2.2/javascript-dev-guide/widgets/widget-popup-window.md
  guides/v2.2/javascript-dev-guide/widgets/widget-trim-input.md
  guides/v2.2/javascript-dev-guide/widgets/widget_accordion.md
  guides/v2.2/javascript-dev-guide/widgets/widget_alert.md
  guides/v2.2/javascript-dev-guide/widgets/widget_calendar.md
  guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.2/javascript-dev-guide/widgets/widget_confirm.md
  guides/v2.2/javascript-dev-guide/widgets/widget_dialog.md
  guides/v2.2/javascript-dev-guide/widgets/widget_dropdown.md
  guides/v2.2/javascript-dev-guide/widgets/widget_gallery.md
  guides/v2.2/javascript-dev-guide/widgets/widget_gallery_mg.md
  guides/v2.2/javascript-dev-guide/widgets/widget_list.md
  guides/v2.2/javascript-dev-guide/widgets/widget_loader.md
  guides/v2.2/javascript-dev-guide/widgets/widget_menu.md
  guides/v2.2/javascript-dev-guide/widgets/widget_modal.md
  guides/v2.2/javascript-dev-guide/widgets/widget_navigation.md
  guides/v2.2/javascript-dev-guide/widgets/widget_password_strength_indicator.md
  guides/v2.2/javascript-dev-guide/widgets/widget_prompt.md
  guides/v2.2/javascript-dev-guide/widgets/widget_quickSearch.md
  guides/v2.2/javascript-dev-guide/widgets/widget_redirectUrl.md
  guides/v2.2/javascript-dev-guide/widgets/widget_tabs.md
  guides/v2.2/javascript-dev-guide/widgets/widget_toggle.md
  guides/v2.3/javascript-dev-guide/widgets/widget_calendar.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: review, partners-contribution

#5363 Enrich Calendar Widget Code example section
  guides/v2.2/javascript-dev-guide/widgets/widget_calendar.md
  guides/v2.3/javascript-dev-guide/widgets/widget_calendar.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5337 information added for how to reinstall triggers
  guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.3/install-gde/prereq/mysql.md
Labels: 2.3.x, Progress: review, Technical

#5364 magento/devdocs#5361: 404 external links
  _data/toc/page-builder.yml
  guides/v2.2/architecture/frontend_custom_strategies.md
  guides/v2.2/javascript-dev-guide/widgets/widget-row-builder.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
Labels: Partner: Atwix, Progress: approved, Technical, partners-contribution

#5365 GraphQL: Alphabetize queries and mutations
  _data/toc/graphql.yml
  guides/v2.3/graphql/mutations/create-braintree-client-token.md
  guides/v2.3/graphql/payment-methods/braintree.md
  guides/v2.3/graphql/queries/cms-blocks.md
  guides/v2.3/graphql/queries/cms-page.md
Labels: 2.3.3, Editorial, Progress: approved, internal-dev

#5388 Edits to 2.3.3 Commerce release notes
  _data/toc/release-notes.yml
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: 2.3.3, Editorial, internal-dev

#5373 Remove 2.1 comment from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Site improvements

#5391 Fix external link
  guides/v2.2/release-notes/ReleaseNotes2.2.4CE.md
Labels: Editorial, small changes

#5374 Remove obsolete redis troubleshooting topic
  _data/toc/cloud-guide.yml
  guides/v2.2/cloud/project/project-conf-files_services-redis.md
  guides/v2.2/cloud/trouble/redis-troubleshooting.md
  guides/v2.2/cloud/trouble/site-availability.md
  guides/v2.3/cloud/trouble/redis-troubleshooting.md
Labels: internal-dev

#5393 2.3.3 release notes
  _data/toc/release-notes.yml
  guides/v2.3/release-notes/bk-release-notes.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: 2.3.3, internal-dev

#5387 [DOCS] Added missing type decelerations for the db_schema.xml
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: Partner: Experius, partners-contribution

#5394 Remove first batch of obsolete troubleshooting topics
  _data/toc/cloud-guide.yml
  _data/toc/software-update-guide.yml
  guides/v2.2/cloud/project/project-conf-files_services-redis.md
  guides/v2.2/cloud/trouble/redis-troubleshooting.md
  guides/v2.2/cloud/trouble/site-availability.md
  guides/v2.2/comp-mgr/trouble/cman/ce-ee-upgrade.md
  guides/v2.2/comp-mgr/trouble/cman/doc.md
  guides/v2.2/comp-mgr/trouble/cman/gitignore.md
  guides/v2.2/comp-mgr/trouble/cman/upgrade_51431.md
  guides/v2.2/comp-mgr/trouble/tshoot.md
  guides/v2.2/comp-mgr/upgrader/ce-ee-upgrade-start.md
  guides/v2.3/cloud/trouble/redis-troubleshooting.md
  guides/v2.3/comp-mgr/trouble/cman/ce-ee-upgrade.md
  guides/v2.3/comp-mgr/trouble/cman/doc.md
  guides/v2.3/comp-mgr/trouble/cman/gitignore.md
  guides/v2.3/comp-mgr/trouble/cman/upgrade_51431.md
Labels: Site improvements

#5351 MAGEDOC-4021 KB conversion Log Locations to Cloud guide
  _data/toc/cloud-guide.yml
  guides/v2.2/cloud/cdn/trouble-fastly.md
  guides/v2.2/cloud/configure/setup-cron-jobs.md
  guides/v2.2/cloud/live/live-sanity-check.md
  guides/v2.2/cloud/live/stage-prod-test.md
  guides/v2.2/cloud/project/log-locations.md
  guides/v2.2/cloud/project/project-start.md
  guides/v2.2/cloud/project/project-upgrade.md
  guides/v2.2/cloud/project/project-webint-basic.md
  guides/v2.2/cloud/reference/discover-deploy.md
  guides/v2.2/cloud/trouble/environments-logs.md
  guides/v2.2/cloud/trouble/site-availability.md
  guides/v2.3/cloud/live/live-sanity-check.md
  guides/v2.3/cloud/project/log-locations.md
  guides/v2.3/cloud/project/project-upgrade.md
  guides/v2.3/cloud/trouble/environments-logs.md
Labels: 2.x, New topic, Progress: review, internal-dev

#5395 Cloud dev doc review
  guides/v2.2/cloud/cdn/configure-fastly.md
  guides/v2.2/cloud/env/environments-start.md
  guides/v2.2/cloud/project/project-conf-files_routes.md
  guides/v2.2/cloud/project/project-webint-basic.md
  guides/v2.2/cloud/project/project-webint-snap.md
  guides/v2.3/cloud/project/projects.md
Labels: 2.2.x, 2.3.x, Technical

#5398 Fix typo in command example
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-maint.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Webjump, partners-contribution, small changes

#5396 Fix mistake
  guides/v2.2/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#5397 Fix event dispatch example
  guides/v2.2/extension-dev-guide/events-and-observers.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Technical, partners-contribution

#5402 Fixed path to log files
  guides/v2.2/cloud/project/log-locations.md
Labels: 2.x, Editorial, internal-dev

#5401 Updated diagram to latest version.
  guides/v2.2/architecture/archi_perspectives/arch_diagrams.md
  guides/v2.3/architecture/archi_perspectives/arch_diagrams.md
Labels: 2.2.x, 2.3.x, Editorial, Technical

#5222 GraphQL: Add layered navigation documentation
  _data/toc/graphql.yml
  _data/whats-new.yml
  guides/v2.3/graphql/custom-filters.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/index.md
  guides/v2.3/graphql/mutations/index.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries.md
  guides/v2.3/graphql/queries/custom-attribute-metadata.md
  guides/v2.3/graphql/queries/index.md
  guides/v2.3/graphql/queries/products-234.md
  guides/v2.3/graphql/queries/products.md
  guides/v2.3/graphql/release-notes.md
Labels: 2.3.4, Major update, Progress: review, internal-dev

#5404 Added link to web configuration for multisite
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
Labels: 2.x, Technical, internal-dev

#5360 Added MediaUploader widget documentation
  _data/toc/javascript-developer-guide.yml
  common/images/widget/media-uploader-widget-result.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget-media-uploader.md
  guides/v2.3/javascript-dev-guide/widgets/widget-media-uploader.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: changes requested, partners-contribution

#5376 Improving the ColorPicker UiComponent documentation
  common/images/ui_comps/color_picker_result.png
  guides/v2.3/ui_comp_guide/components/ui-colorpicker.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution

#5386 Improving the Modal UiComponent documentation
  common/images/ui_comps/notification_modal_result.png
  common/images/ui_comps/slide_modal_result.png
  guides/v2.2/ui_comp_guide/components/ui-modal.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#5405 remove information that vcl export is optional
  guides/v2.2/config-guide/varnish/config-varnish-magento.md
Labels: 2.2.x, 2.3.x, Technical, small changes

#5407 Added version banner to layout.
  _includes/layout/page-header.html
  common/css/devdocs.css
Labels: Site improvements

#5406 Updates to routes.yaml code samples
  _includes/cloud/note-route-all-placeholder.md
  guides/v2.2/cloud/project/project-conf-files_routes.md
  guides/v2.2/cloud/project/project-routes-more-cache.md
Labels: 2.x, Technical, internal-dev

#5413 Deprecate setPaymentAndPlaceOrder mutation
  guides/v2.3/graphql/mutations/set-payment-place-order.md
  guides/v2.3/graphql/tutorials/checkout/checkout-payment-method.md
Labels: 2.3.4, Community, Major update

#5409 fixed repository name and more
  guides/v2.2/cloud/integrations/bitbucket-integration.md
  guides/v2.2/cloud/integrations/cloud-integrations.md
Labels: Editorial, internal-dev, small changes

#5358 Added the documentation for Sortable widget
  _data/toc/javascript-developer-guide.yml
  common/images/widget/sortable-widget-initial-result.png
  common/images/widget/sortable-widget-sorted-result.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget-sortable.md
  guides/v2.3/javascript-dev-guide/widgets/widget-sortable.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: review, partners-contribution

#5357 magento/devdocs#: DevDocs contributors guide. Add info about symbolic links.
  .github/CONTRIBUTING.md
Labels: Major update, Partner: Atwix, Progress: changes requested, partners-contribution

#5418 Fix link title for Install Elasticsearch 6.x
  guides/v2.3/config-guide/elasticsearch/es-overview.md
Labels: 2.3.x, Editorial

#5411 Typo changes
  guides/v2.2/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#5330 magento/devdocs#: Cloud. Add VCL for the sitemap.xml and robots.txt files
  guides/v2.2/cloud/trouble/robots-sitemap.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#5417 MAGECLOUD-4242: Refactor ece-tools functional tests
  guides/v2.2/cloud/docker/docker-development-testing.md
Labels: 2.x, Technical, internal-dev

#5420 Version banner fix
  _includes/layout/page-header.html
Labels: Site improvements

#5354 Update Multiselect Widget Documentation
  guides/v2.2/javascript-dev-guide/widgets/widget-multiselect.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: changes requested, partners-contribution

#5423 Fixing the Markdown syntax in checkout_new_field
  guides/v2.2/howdoi/checkout/checkout_new_field.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Imagination Media, partners-contribution

#5392 Hide "CSS Critical Path" mentioned in documentation pages as it is not port of stable Magento version yet (nor 2.2 or 2.3)
  _data/whats-new.yml
  guides/v2.2/frontend-dev-guide/css-topics/css-critical-path.md
  guides/v2.2/frontend-dev-guide/css-topics/css-overview.md
  guides/v2.2/frontend-dev-guide/theme-best-practice.md
  guides/v2.3/frontend-dev-guide/css-topics/css-critical-path.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, partners-contribution

#5426 GraphQL: Add url_suffix attribute
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries/category.md
  guides/v2.3/graphql/queries/cms-page.md
  guides/v2.3/graphql/queries/url-resolver.md
Labels: 2.3.4, Technical, internal-dev

#5428 Fix code block style (MD040)
  README.md
  _videos/fundamentals/add-a-new-table-to-database.md
  guides/v2.2/advanced-reporting/report-xml.md
  guides/v2.2/b2b/company-structures.md
  guides/v2.2/b2b/company-users.md
  guides/v2.2/b2b/credit-manage.md
  guides/v2.2/b2b/integrations.md
  guides/v2.2/b2b/negotiable-order-workflow.md
  guides/v2.2/b2b/negotiable-update.md
  guides/v2.2/b2b/roles.md
  guides/v2.2/b2b/shared-cat-company.md
  guides/v2.2/b2b/shared-cat-manage.md
  guides/v2.2/b2b/shared-cat-product-assign.md
  guides/v2.2/cloud/project/ece-tools-upgrade-project.md
  guides/v2.2/cloud/project/sendgrid.md
  guides/v2.2/coding-standards/code-standard-less.md
  guides/v2.2/config-guide/bootstrap/magento-how-to-set.md
  guides/v2.2/config-guide/cache/static-content-signing.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-depen.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-index.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-layout-xml.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-perf-data.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-spt-util.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-test.md
  guides/v2.2/config-guide/elasticsearch/es-config-apache.md
  guides/v2.3/config-guide/cli/config-cli-subcommands-perf-data.md
Labels: Site improvements

#5430 Fixed code block style (MD040) in the Contributor Guide
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.2/contributor-guide/templates/basic_template.md
  guides/v2.2/contributor-guide/templates/tutorial-template-first.md
  guides/v2.2/contributor-guide/templates/tutorial-template-last.md
  guides/v2.2/contributor-guide/templates/tutorial-template-middle.md
  guides/v2.3/contributor-guide/contributing.md
Labels: Site improvements

#5431 Fixed code block style (MD040) in the Frontend and JS Developer Guides
  guides/v2.2/frontend-dev-guide/layouts/layout-practice.md
  guides/v2.2/frontend-dev-guide/templates/template-email.md
  guides/v2.2/frontend-dev-guide/templates/template-override.md
  guides/v2.2/javascript-dev-guide/widgets/widget_loader.md
Labels: Site improvements

#5410 magento/devdocs#: Develop issue 1740. Additional changes
  _includes/config/setup-cron_2.2_how-to.md
  _includes/config/setup-cron_2.3_how-to.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#5435 Fixed code block style (MD040) in the Migration Guide
  guides/v2.2/migration/migration-tool-install.md
  guides/v2.2/migration/migration-tool-internal-spec.md
  guides/v2.2/migration/migration-tool-upgrade.md
Labels: Site improvements

#5436 Fixed code block style (MD040) in the UI components Guide
  guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
  guides/v2.2/ui_comp_guide/concepts/magento-bindings.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_data_source.md
  guides/v2.3/ui_comp_guide/components/ui-urlinput.md
  guides/v2.3/ui_comp_guide/howto/update-url-type.md
Labels: Site improvements

#5437 Fixed code block style (MD040) in the Inventory guide
  guides/v2.2/get-started/authentication/gs-authentication-token.md
  guides/v2.3/inventory/reservations.md
Labels: Site improvements

#5434 Fixed code block style (MD040) in the Extension Developer Guide
  guides/v2.2/ext-best-practices/extension-coding/example-module-adminpage.md
  guides/v2.2/extension-dev-guide/build/module-file-structure.md
  guides/v2.2/extension-dev-guide/cache/page-caching/public-content.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-naming-guidelines.md
  guides/v2.2/extension-dev-guide/code-generation.md
  guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.md
  guides/v2.2/extension-dev-guide/framework/serializer.md
  guides/v2.2/extension-dev-guide/message-queues/implement-bulk.md
  guides/v2.2/extension-dev-guide/routing.md
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
  guides/v2.2/extension-dev-guide/validate/test-module.md
  guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
  guides/v2.3/extension-dev-guide/build/module-file-structure.md
  guides/v2.3/extension-dev-guide/message-queues/implement-bulk.md
  guides/v2.3/extension-dev-guide/routing.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
  guides/v2.3/extension-dev-guide/validate/test-module.md
Labels: Site improvements

#5432 Fixed code block style (MD040) in the Marketplace EQP API Guide
  guides/v2.2/marketplace/eqp/auth.md
  guides/v2.2/marketplace/eqp/files.md
  guides/v2.2/marketplace/eqp/packages.md
  guides/v2.2/marketplace/eqp/reports.md
  guides/v2.2/marketplace/eqp/users.md
Labels: Site improvements

#5429 Fixed code block style (MD040) in the Software Update Guide
  _includes/comp-man/checklist.md
  guides/v2.2/comp-mgr/extens-man/extensman-uninst-data.md
  guides/v2.2/comp-mgr/trouble/cman/maint-mode.md
  guides/v2.2/comp-mgr/trouble/cman/out-of-memory.md
  guides/v2.2/comp-mgr/trouble/cman/update-fail.md
  guides/v2.2/comp-mgr/trouble/cman/were-sorry.md
  guides/v2.2/comp-mgr/upgrader/ce-ee-upgrade-start.md
  guides/v2.2/comp-mgr/upgrader/upgrade.md
Labels: Site improvements

#5425 GraphQL: Add fields and example showing cart rule discounts
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/queries/cart.md
  guides/v2.3/graphql/queries/products.md
Labels: 2.3.4, Major update, internal-dev

#5438 GraphQL: Add introspection query examples
  guides/v2.3/graphql/index.md
  guides/v2.3/graphql/queries.md
Labels: 2.3.x, Major update, internal-dev

#5442 Add missing curly brace in the nginx configuration
  guides/v2.2/comp-mgr/trouble/cman/maint-mode.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, small changes

#5445 Improving the layout common customization with block ifconfig argument
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
  guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5455 Add an open source license
  LICENSE.txt
Labels: Progress: approved, internal-dev

#5453 magento/devdocs#: Cloud. `magento-cloud db:dump` command
  _includes/cloud/backup-db.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5458 Fixed MD040 errors in _includes/config/
  _includes/config/install-java.md
  _includes/config/install-java8.md
  _includes/config/redis-verify.md
  _includes/config/secure-ws-apache_step1.md
  _includes/config/secure-ws-apache_step2.md
  _includes/config/setup-cron.md
  _includes/config/setup-cron_2.2.md
  _includes/config/setup-cron_2.2_how-to.md
  _includes/config/split-db.md
  _includes/config/split-deploy/example_build-sync.md
  _includes/config/split-deploy/example_update-prod.md
Labels: Progress: review, Site improvements

#5457 Fix Cloud procedures for Docker and integrations
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-database.md
  guides/v2.2/cloud/docker/docker-development-debug.md
  guides/v2.2/cloud/docker/docker-development.md
  guides/v2.2/cloud/integrations/bitbucket-integration.md
  guides/v2.2/cloud/integrations/cloud-integrations.md
  guides/v2.2/cloud/integrations/github-integration.md
  guides/v2.2/cloud/integrations/health-notifications.md
Labels: Editorial, Progress: approved, internal-dev

#5467 Update bundle
  Gemfile.lock
Labels: Site improvements

#5461 Mc 18725
  guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
Labels: 2.3.4, Major update, Progress: approved

#5464 Release notes for 2.2.10
  _data/toc/release-notes.yml
  guides/v2.2/release-notes/bk-release-notes.md
  guides/v2.2/release-notes/release-notes-2-2-10-commerce.md
  guides/v2.2/release-notes/release-notes-2-2-10-open-source.md
Labels: 2.2.10, Progress: approved

#5452 Added the RemainingCharacters widget documentation
  _data/toc/javascript-developer-guide.yml
  common/images/widget/remaining-characters-widget-with-exceeded-text-length.png
  common/images/widget/remaining-characters-widget-with-not-exceeded-text-length.png
  guides/v2.2/javascript-dev-guide/widgets/jquery-widgets-about.md
  guides/v2.2/javascript-dev-guide/widgets/widget-remaining-characters.md
  guides/v2.3/javascript-dev-guide/widgets/widget-remaining-characters.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5444 Fix procedures in Cloud includes and references
  _includes/cloud/backup-db.md
  _includes/cloud/composer-name.md
  _includes/cloud/enable-ssh.md
  _includes/cloud/sens-data-create-config-local.md
  guides/v2.2/cloud/before/before-setup-env-2_clone.md
  guides/v2.2/cloud/before/before-setup-env-install.md
  guides/v2.2/cloud/before/before-workspace-cloud-account.md
  guides/v2.2/cloud/before/before-workspace-file-sys-owner.md
  guides/v2.2/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.2/cloud/before/before-workspace-ssh.md
  guides/v2.2/cloud/before/before-workspace.md
  guides/v2.2/cloud/configure/import-url-rewrites.md
  guides/v2.2/cloud/configure/setup-cron-jobs.md
  guides/v2.2/cloud/deploy/static-content-deployment.md
  guides/v2.2/cloud/reference/cli-ref-topic.md
  guides/v2.2/cloud/reference/ece-tools-reference.md
  guides/v2.2/cloud/setup/first-time-setup-import-first-steps.md
  guides/v2.2/cloud/trouble/robots-sitemap.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
Labels: Editorial, Progress: changes requested, internal-dev

#5465 Updated what's new with changes since Sept 7, 2019
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: review, internal-dev

#5414 Add note about baler module to bundling topic
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: 2.3.0, Progress: approved

#5475 Fixed MD040 errors in Install Guide
  guides/v2.2/install-gde/basics/basics_magento-installed.md
  guides/v2.2/install-gde/basics/basics_os-version.md
  guides/v2.2/install-gde/install/cli/dev_downgrade.md
  guides/v2.2/install-gde/install/cli/dev_reinstall.md
  guides/v2.2/install-gde/install/cli/install-cli-adminurl.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-db-status.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-db.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-deployment.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-enable.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-maint.md
  guides/v2.2/install-gde/install/cli/install-cli-subcommands-store.md
  guides/v2.2/install-gde/install/cli/install-cli-theme-uninstall.md
  guides/v2.2/install-gde/install/cli/install-cli-uninstall-langpk.md
  guides/v2.2/install-gde/install/cli/install-cli-uninstall-mods.md
  guides/v2.2/install-gde/install/legacy-file-system-perms.md
  guides/v2.2/install-gde/prereq/apache.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.2/install-gde/prereq/mysql_remote.md
  guides/v2.2/install-gde/prereq/nginx.md
  guides/v2.2/install-gde/prereq/optional.md
  guides/v2.2/install-gde/prereq/php-centos.md
  guides/v2.2/install-gde/prereq/php-settings.md
  guides/v2.2/install-gde/prereq/php-ubuntu.md
  guides/v2.2/install-gde/prereq/prereq-overview.md
  guides/v2.2/install-gde/prereq/security.md
  guides/v2.2/install-gde/trouble/git/tshoot_clone.md
  guides/v2.2/install-gde/trouble/git/tshoot_git-pull-origin.md
  guides/v2.2/install-gde/trouble/php/tshoot_70pct.md
  guides/v2.2/install-gde/trouble/php/tshoot_mcrypt.md
  guides/v2.2/install-gde/trouble/php/tshoot_mod_access_compat.md
  guides/v2.2/install-gde/trouble/php/tshoot_nginx-port.md
  guides/v2.2/install-gde/trouble/php/tshoot_opcache.md
  guides/v2.2/install-gde/trouble/php/tshoot_pdo.md
  guides/v2.2/install-gde/trouble/php/tshoot_php-date.md
  guides/v2.2/install-gde/trouble/php/tshoot_php-set.md
  guides/v2.2/install-gde/trouble/php/tshoot_phpini.md
  guides/v2.2/install-gde/trouble/php/tshoot_session.md
  guides/v2.2/install-gde/trouble/php/tshoot_xdebug.md
  guides/v2.2/install-gde/trouble/tshoot_access-browser.md
  guides/v2.2/install-gde/trouble/tshoot_bundlesampledata.md
  guides/v2.2/install-gde/trouble/tshoot_composer-fail.md
  guides/v2.2/install-gde/trouble/tshoot_exceptions.md
  guides/v2.2/install-gde/trouble/tshoot_install_depend.md
  guides/v2.2/install-gde/trouble/tshoot_mysql_table-open-cache.md
  guides/v2.2/install-gde/trouble/tshoot_sample-data.md
  guides/v2.2/install-gde/trouble/tshoot_segfault.md
  guides/v2.3/install-gde/install-quick-ref.md
  guides/v2.3/install-gde/prereq/apache.md
  guides/v2.3/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/mysql_remote.md
  guides/v2.3/install-gde/prereq/nginx.md
  guides/v2.3/install-gde/prereq/optional.md
  guides/v2.3/install-gde/prereq/php-settings.md
  guides/v2.3/install-gde/prereq/security.md
  guides/v2.3/install-gde/prereq/zip_install.md
  guides/v2.3/install-gde/trouble/php/tshoot_pdo.md
Labels: Progress: approved, Site improvements

#5477 Code Cleanup
  guides/v2.2/rest/tutorials/orders/order-create-customer.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution, small changes

#5484 MAGEDOC-4099: Added more info about pre-release packages
  _includes/install/pre-release.md
  guides/v2.2/release-notes/release-notes-2-2-10-commerce.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
  guides/v2.3/install-gde/composer.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
Labels: Progress: approved, internal-dev

#5449 Added preferred usage of JS declarative notation
  guides/v2.2/javascript-dev-guide/javascript/js_init.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: changes requested, Technical, partners-contribution

#5469 magento/devdocs#5245: Hard tabs. Folder: guides/architecture
  guides/v2.2/architecture/tech-stack.md
  guides/v2.3/architecture/tech-stack.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5470 magento/devdocs#5245: Hard tabs. Folder: guides/b2b
  guides/v2.2/b2b/company-object.md
  guides/v2.2/b2b/company-structures.md
  guides/v2.2/b2b/company-users.md
  guides/v2.2/b2b/negotiable-checkout.md
  guides/v2.2/b2b/negotiable-manage.md
  guides/v2.2/b2b/negotiable-order-workflow.md
  guides/v2.2/b2b/shared-cat-product-assign.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, partners-contribution, small changes

#5486 magento/devdocs#5245: Hard tabs. Folder: guides/coding-standars
  guides/v2.2/coding-standards/code-standard-demarcation.md
  guides/v2.2/coding-standards/docblock-standard-javascript.md
  guides/v2.3/coding-standards/code-standard-demarcation.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#5487 magento/devdocs#5245: Hard tabs. Folder: guides/сomp-mgr
  guides/v2.2/comp-mgr/bk-compman-upgrade-guide.md
  guides/v2.2/comp-mgr/cli/cli-upgrade.md
  guides/v2.2/comp-mgr/extens-man/extensman-backup.md
  guides/v2.2/comp-mgr/extens-man/extensman-checklist.md
  guides/v2.2/comp-mgr/extens-man/extensman-main-pg.md
  guides/v2.2/comp-mgr/extens-man/extensman-readiness-fail.md
  guides/v2.2/comp-mgr/extens-man/extensman-readiness-multi.md
  guides/v2.2/comp-mgr/extens-man/extensman-readiness.md
  guides/v2.2/comp-mgr/extens-man/extensman-uninst-data.md
  guides/v2.2/comp-mgr/marketplace/marketplace.md
  guides/v2.2/comp-mgr/module-man/compman-start.md
  guides/v2.2/comp-mgr/prereq/prereq_compman-checklist.md
  guides/v2.2/comp-mgr/prereq/prereq_compman.md
  guides/v2.2/comp-mgr/trouble/cman/cron.md
  guides/v2.2/comp-mgr/trouble/cman/maint-mode.md
  guides/v2.2/comp-mgr/trouble/cman/out-of-memory.md
  guides/v2.2/comp-mgr/trouble/cman/tshoot_backup.md
  guides/v2.2/comp-mgr/trouble/cman/were-sorry.md
  guides/v2.2/comp-mgr/trouble/tshoot.md
  guides/v2.2/comp-mgr/updater/update-updater.md
  guides/v2.2/comp-mgr/upgrader/ce-ee-upgrade-start.md
  guides/v2.2/comp-mgr/upgrader/upgrade-checklist.md
  guides/v2.2/comp-mgr/upgrader/upgrade-main-pg.md
  guides/v2.2/comp-mgr/upgrader/upgrade-start.md
  guides/v2.2/comp-mgr/upgrader/upgrade.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#5450 Added critical purpose and usage of routeId in routes.xml
  guides/v2.2/extension-dev-guide/routing.md
  guides/v2.3/extension-dev-guide/routing.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#5421 Removed 'How to' text from TOC labels
  _data/toc/page-builder.yml
Labels: Editorial, internal-dev

#5451 magento/devdocs#: Declarative schema and Develop data and schema patches. Execution priority.
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5320 [site] Update Markdown linting tasks
  _checks/md_check_hook.rb
  rakelib/check.rake
  rakelib/test.rake
Labels: Progress: acceptance testing, Site improvements

#5498 Fixed MD040 errors in cloud topics
  guides/v2.2/cloud/before/before-workspace-file-sys-owner.md
  guides/v2.2/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.2/cloud/cdn/cloud-vcl-custom-snippets.md
  guides/v2.2/cloud/cdn/fastly-vcl-whitelist.md
  guides/v2.2/cloud/cdn/trouble-fastly.md
  guides/v2.2/cloud/env/environments-ssh.md
  guides/v2.2/cloud/howtos/custom-theme.md
  guides/v2.2/cloud/howtos/debug.md
  guides/v2.2/cloud/howtos/environment-tutorial-env-merge.md
  guides/v2.2/cloud/live/live-sanity-check.md
  guides/v2.2/cloud/live/sens-data-initial.md
  guides/v2.2/cloud/setup/first-time-deploy.md
  guides/v2.2/cloud/trouble/robots-sitemap.md
  guides/v2.2/cloud/trouble/trouble_ce-creds.md
  guides/v2.2/cloud/trouble/trouble_comp-deploy-fail.md
  guides/v2.2/cloud/trouble/troubleshoot-deployment.md
  guides/v2.3/cloud/before/before-workspace-magento-prereqs.md
  guides/v2.3/cloud/live/live-sanity-check.md
  guides/v2.3/cloud/setup/first-time-deploy.md
Labels: Editorial, Progress: approved

#5507 magento/devdocs#5245: Hard tabs. Folder: guides/frontend-dev-guide
  guides/v2.2/frontend-dev-guide/bk-frontend-dev-guide.md
  guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_overview.md
  guides/v2.2/frontend-dev-guide/css-topics/custom_preprocess.md
  guides/v2.2/frontend-dev-guide/css-topics/gulp-sass.md
  guides/v2.2/frontend-dev-guide/css-topics/theme-ui-lib.md
  guides/v2.2/frontend-dev-guide/layouts/layout-extend.md
  guides/v2.2/frontend-dev-guide/layouts/layout-override.md
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_js.md
  guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_overview.md
  guides/v2.2/frontend-dev-guide/themes/theme-apply.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-images.md
  guides/v2.2/frontend-dev-guide/themes/theme-structure.md
  guides/v2.2/frontend-dev-guide/translations/theme_dictionary.md
  guides/v2.2/frontend-dev-guide/translations/xlate.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/frontend-dev-guide/translations/xlate.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#5505 magento/devdocs#5245: Hard tabs. Folder: guides/design-styleguide
  guides/v2.2/design-styleguide/iconography/iconography.md
  guides/v2.2/design-styleguide/pagegrid/pagegrid.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#5509 magento/devdocs#5245: Hard tabs. Folder: guides/howdoi
  guides/v2.2/howdoi/checkout/checkout_new_step.md
  guides/v2.2/howdoi/checkout/checkout_zip.md
  guides/v2.2/howdoi/customize-form-configuration.md
  guides/v2.2/howdoi/php/php_clear-dirs.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#5495 Fixed MD040 errors in REST and GraphQL topics
  guides/v2.2/performance-best-practices/software.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/rest/asynchronous-web-endpoints.md
  guides/v2.2/rest/bulk-endpoints.md
  guides/v2.2/rest/modules/catalog-pricing.md
  guides/v2.2/rest/modules/catalog.md
  guides/v2.2/rest/operation-status-endpoints.md
  guides/v2.2/rest/operation-status-search.md
  guides/v2.2/rest/performing-searches.md
  guides/v2.2/rest/tutorials/configurable-product/create-personalization-option.md
  guides/v2.3/graphql/develop/debugging.md
  guides/v2.3/graphql/reference/cms.md
  guides/v2.3/graphql/reference/customer.md
  guides/v2.3/graphql/reference/wishlist.md
  guides/v2.3/rest/asynchronous-web-endpoints.md
  guides/v2.3/rest/bulk-endpoints.md
  guides/v2.3/rest/modules/inventory/bulk-inventory.md
  guides/v2.3/rest/modules/inventory/check-salable-quantity.md
  guides/v2.3/rest/modules/inventory/link-stocks-sources.md
  guides/v2.3/rest/modules/inventory/manage-low-quantity.md
  guides/v2.3/rest/modules/inventory/manage-source-items.md
  guides/v2.3/rest/modules/inventory/manage-source-selection.md
  guides/v2.3/rest/modules/inventory/manage-sources.md
  guides/v2.3/rest/modules/inventory/manage-stocks.md
  guides/v2.3/rest/operation-status-endpoints.md
  guides/v2.3/rest/operation-status-search.md
Labels: Editorial, Progress: changes requested

#5497 Fixed MD040 errors in cloud includes
  _includes/cloud/cli-get-started.md
  _includes/cloud/composer-name.md
  _includes/cloud/enable-ssh.md
  _includes/cloud/patch.md
  _includes/cloud/ssh-tunnel.md
Labels: Editorial, Progress: approved

#5510 Small changes
  _includes/cloud/backup-db.md
  guides/v2.2/cloud/cdn/fastly-vcl-wordpress.md
  guides/v2.2/comp-mgr/trouble/cman/maint-mode.md
  guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.2/rest/tutorials/orders/order-create-customer.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: Progress: approved

#5508 magento/devdocs#5245: Hard tabs. Folder: guides/get-started
  guides/v2.2/get-started/bk-get-started-api.md
  guides/v2.2/get-started/web-api-functional-testing.md
  guides/v2.3/get-started/web-api-functional-testing.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#5514 Enable rule MD040
  _checks/styles/style-rules-prod
Labels: Progress: approved, Site improvements

#5331 Markdown linting: Enable rule MD023 - Headers must start at the beginning of the line
  _checks/styles/style-rules-prod
  guides/v2.2/config-guide/multi-site/ms_websites.md
Labels: Progress: approved, Site improvements

#5500 Remove duplicate Cloud files from 2.3
  guides/v2.2/cloud/project/projects.md
  guides/v2.2/cloud/requirements/cloud-requirements.md
  guides/v2.3/cloud/project/projects.md
  guides/v2.3/cloud/requirements/cloud-requirements.md
  guides/v2.3/cloud/setup/first-time-deploy.md
Labels: Editorial, Progress: approved, internal-dev

#5493 Updated WAF feature descriptions and provisioning process to match cu…
  _data/toc/cloud-guide.yml
  _data/whats-new.yml
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/cdn/cloud-fastly-custom-response.md
  guides/v2.2/cloud/cdn/cloud-fastly.md
  guides/v2.2/cloud/cdn/fastly-waf-service.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#5506 magento/devdocs#5245: Hard tabs. Folder: guides/extension-dev-guide
  guides/v2.2/extension-dev-guide/attributes.md
  guides/v2.2/extension-dev-guide/bk-extension-dev-guide.md
  guides/v2.2/extension-dev-guide/build/build.md
  guides/v2.2/extension-dev-guide/build/composer-integration.md
  guides/v2.2/extension-dev-guide/build/di-xml-file.md
  guides/v2.2/extension-dev-guide/build/module-file-structure.md
  guides/v2.2/extension-dev-guide/build/module-load-order.md
  guides/v2.2/extension-dev-guide/build/required-configuration-files.md
  guides/v2.2/extension-dev-guide/cache/partial-caching.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/create-cache-type.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-add.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
  guides/v2.2/extension-dev-guide/cli-cmds/cli-naming-guidelines.md
  guides/v2.2/extension-dev-guide/code-generation.md
  guides/v2.2/extension-dev-guide/configuration/sensitive-and-environment-settings.md
  guides/v2.2/extension-dev-guide/depend-inj.md
  guides/v2.2/extension-dev-guide/indexer-batch.md
  guides/v2.2/extension-dev-guide/indexing-custom.md
  guides/v2.2/extension-dev-guide/indexing.md
  guides/v2.2/extension-dev-guide/intro/developers_roadmap.md
  guides/v2.2/extension-dev-guide/intro/intro-composer-gloss.md
  guides/v2.2/extension-dev-guide/intro/intro-composer.md
  guides/v2.2/extension-dev-guide/message-queues/bulk-operations.md
  guides/v2.2/extension-dev-guide/message-queues/queue-migration.md
  guides/v2.2/extension-dev-guide/package/package.md
  guides/v2.2/extension-dev-guide/prepare/dev-summary.md
  guides/v2.2/extension-dev-guide/prepare/lifecycle.md
  guides/v2.2/extension-dev-guide/prepare/prepare.md
  guides/v2.2/extension-dev-guide/validate/test-module.md
  guides/v2.3/extension-dev-guide/attributes.md
  guides/v2.3/extension-dev-guide/bk-extension-dev-guide.md
  guides/v2.3/extension-dev-guide/build/module-file-structure.md
  guides/v2.3/extension-dev-guide/build/required-configuration-files.md
  guides/v2.3/extension-dev-guide/depend-inj.md
  guides/v2.3/extension-dev-guide/indexer-batch.md
  guides/v2.3/extension-dev-guide/indexing.md
  guides/v2.3/extension-dev-guide/message-queues/bulk-operations.md
  guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/extension-dev-guide/message-queues/queue-migration.md
  guides/v2.3/extension-dev-guide/validate/test-module.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: review, partners-contribution

#5512 GraphQL: Update pricing schema changes
  _data/toc/graphql.yml
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries/cart.md
  guides/v2.3/graphql/queries/category.md
  guides/v2.3/graphql/queries/products.md
Labels: 2.3.4, Major update, Progress: review, internal-dev

#5492 Remove obsolete troubleshooting topics
  _data/toc/installation-guide.yml
  guides/v2.2/install-gde/install/cli/install-cli-backup.md
  guides/v2.2/install-gde/prereq/dev_install.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.2/install-gde/prereq/optional.md
  guides/v2.2/install-gde/trouble/php/tshoot_phpini.md
  guides/v2.2/install-gde/trouble/tshoot_composer-install.md
  guides/v2.2/install-gde/trouble/tshoot_mysql_table-open-cache.md
  guides/v2.2/install-gde/trouble/tshoot_segfault.md
  guides/v2.3/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/optional.md
  guides/v2.3/install-gde/trouble/php/tshoot_phpini.md
  guides/v2.3/install-gde/trouble/tshoot_composer-install.md
  guides/v2.3/install-gde/trouble/tshoot_mysql_table-open-cache.md
  guides/v2.3/install-gde/trouble/tshoot_segfault.md
Labels: Progress: acceptance testing, Site improvements
