Repository magento/devdocs, pull requests merged in 2019-03, with the labels that each got.

#3842 Add multirepo support
  .gitignore
  Rakefile
  rakelib/lib/converter.rb
  rakelib/lib/double-slash-check.rb
  rakelib/lib/link-checker.rb
  rakelib/multirepo.rake
  scripts/docs-from-code.sh
Labels: Site improvements

#3841 Add MBI navigation and config
  Rakefile
  _config.yml
  _data/main-nav.yml
  _data/toc/mbi.yml
  rakelib/multirepo.rake
Labels: Site improvements

#3847 Update ui_comp_data_source.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_data_source.md
Labels: 2.2.x, 2.3.x, Technical

#3849 Alphabetize GraphQL attributes
  guides/v2.3/graphql/reference/bundle-product.md
  guides/v2.3/graphql/reference/categories.md
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/graphql/reference/custom-attribute-metadata.md
  guides/v2.3/graphql/reference/customizable-option-interface.md
  guides/v2.3/graphql/reference/downloadable-product.md
  guides/v2.3/graphql/reference/gift-card-product.md
  guides/v2.3/graphql/reference/grouped-product.md
  guides/v2.3/graphql/reference/url-resolver.md
Labels: 2.3.1, Community, Editorial, internal-dev

#3846 Update create-admin-token.md
  guides/v2.2/rest/tutorials/prerequisite-tasks/create-admin-token.md
Labels: 2.2.x, 2.3.x, Partner: ISM eCompany, partners-contribution

#3845 Updated indexing.md
  guides/v2.1/extension-dev-guide/indexing.md
Labels: Partner: ISM eCompany, partners-contribution

#3623 Fix Fastly service configuration custom VCL examples for WordPress redirects and blocking referrer spam
  _data/toc/cloud-guide.yml
  _includes/cloud/admin-ui-login-step.md
  _includes/cloud/cloud-fastly-manage-vcl-from-admin.md
  common/images/cloud/cloud-fastly-create-referrer-block-snippet.png
  common/images/cloud/cloud-fastly-create-vcl-snippet.png
  common/images/cloud/cloud-fastly-edge-dictionary-add-items.png
  common/images/cloud/cloud-fastly-edge-dictionary-configure.png
  common/images/cloud/cloud-fastly-edit-snippets.png
  common/images/cloud/cloud-fastly-manage-snippets.png
  common/images/cloud/cloud-fastly-referrer-blocklist-dictionary.png
  guides/v2.1/cloud/cdn/cloud-fastly.md
  guides/v2.1/cloud/cdn/cloud-vcl-custom-snippets.md
  guides/v2.1/cloud/cdn/configure-fastly.md
  guides/v2.1/cloud/cdn/fastly-vcl-badreferer.md
  guides/v2.1/cloud/cdn/fastly-vcl-whitelist.md
  guides/v2.1/cloud/cdn/fastly-vcl-wordpress.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3843 MAGECLOUD-3193 github integration
  common/images/cloud_github-acct-settings.png
  common/images/cloud_github-acct-webhook.png
  common/images/cloud_github-acct-webhook2.png
  guides/v2.0/cloud/project/project-integrate-github.md
  guides/v2.1/cloud/integrations/bitbucket-integration.md
  guides/v2.1/cloud/integrations/github-integration.md
Labels: 2.x, Technical, internal-dev

#3851 GraphQL: add the option_id parameter for customizable options
  guides/v2.3/graphql/reference/customizable-option-interface.md
Labels: 2.3.1, Community, Major update, internal-dev

#3818 Updating customer endpoint topic with mutations
  guides/v2.3/graphql/reference/customer.md
Labels: 2.3.1, Community, In progress, Technical

#3848 Ignore the page-builder directory
  .gitignore
Labels: Site improvements

#3852 Make last-modified-at plugin to work correct in subrepos
  _plugins/last-modified-at.rb
Labels: Site improvements

#3854 Updating ProductInterface endpoint with new data types
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.1, Community, Technical

#3855 Add sales endpoint
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/sales.md
Labels: 2.3.1, Community, New doc, internal-dev

#3652 GraphQL request and response correction
  guides/v2.3/graphql/reference/url-resolver.md
Labels: 2.3.x, Technical, partners-contribution

#3838 Updating Quote Endpoint with Query and Mutations
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.1, Community, Major update

#3704 Module version dependencies.
  guides/v2.0/extension-dev-guide/versioning/dependencies.md
  guides/v2.1/extension-dev-guide/versioning/dependencies.md
  guides/v2.3/extension-dev-guide/versioning/dependencies.md
Labels: 2.x, Partner: ISM eCompany, Technical, partners-contribution

#3859 URL Rewrite updates
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/graphql/reference/url-resolver.md
Labels: 2.3.1, Community, Major update, internal-dev

#3850 Update porting content
  guides/v2.1/contributor-guide/contributing.md
  guides/v2.2/contributor-guide/contributing.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.x, Major update, Partner: Krish TechnoLabs, partners-contribution

#3853 MAGEDOC-3553: Make 'Edit this page on GitHub' work in docs from subrepos
  _config.yml
  _includes/layout/page-info.html
  _plugins/github-path.rb
Labels: Site improvements

#3863 Fix incorrect composer command for MFTF.
  mftf/2.3/getting-started.md
Labels: 2.3.x, Technical

#3864 Updated sys reqs and unsupported OS.
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Major update

#3866 Update What's New on DevDocs
  _data/whats-new.yml
Labels: 2.x, Editorial

#3862 Update bk-install-guide.md
  guides/v2.2/install-gde/bk-install-guide.md
Labels: 2.2.x, 2.3.x, Editorial

#3865 Update data type for the Company Credits API
  guides/v2.2/b2b/credit-manage.md
Labels: Partner: Krish TechnoLabs, Technical, partners-contribution

#3800 Updated function name and argument of configuration fixture annotation example
  guides/v2.2/test/integration/annotations/magento-config-fixture.md
  guides/v2.3/test/integration/annotations/magento-config-fixture.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#3844 Update gs-authentication-token.md
  guides/v2.1/get-started/authentication/gs-authentication-token.md
Labels: Partner: ISM eCompany, partners-contribution

#3872 Fixed incorrect path to Admin Token Lifetime (hours) option
  guides/v2.1/rest/tutorials/orders/order-admin-token.md
Labels: 2.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3801 Added null/optional parameter in constructor as per Backward Compatibility Policy
  guides/v2.3/ui_comp_guide/components/ui-wysiwyg.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#3867 Adding mutation and query to configurable and downloadable product endpoints
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/graphql/reference/downloadable-product.md
Labels: 2.3.1, Community, Major update

#3875 Add rake tasks to update multi repository structure
  _checks/html-check-hook.rb
  rakelib/converter.rb
  rakelib/double-slash-check.rb
  rakelib/link-checker.rb
  rakelib/update.rake
Labels: Site improvements

#3856 Community edition also need the bcmath extension
  guides/v2.3/install-gde/prereq/php-centos-ubuntu.md
Labels: 2.3.x, Technical

#3858 fix #3857 Fix collapsible savestate default value
  guides/v2.1/javascript-dev-guide/widgets/widget_collapsible.md
Labels: 2.1.x, Partner: Vaimo, Technical, partners-contribution

#3882 Update schemas for 2.3.1
  redoc/2.3/admin-schema.json
  redoc/2.3/async-admin-schema.json
  redoc/2.3/async-customer-schema.json
  redoc/2.3/async-guest-schema.json
  redoc/2.3/customer-schema.json
  redoc/2.3/guest-schema.json
Labels: 2.3.1, Technical, internal-dev

#3883 Use build number instead of branch name on staging
  rakelib/lib/link-checker.rb
Labels: Site improvements

#3889 Update technical-details.md
  guides/v2.2/config-guide/deployment/pipeline/technical-details.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: ISM eCompany, partners-contribution

#3873 Correct max page size for elasticsearch engine
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
Labels: 2.3.1, Partner: Krish TechnoLabs, Technical, partners-contribution

#3877 Update db-schema.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Partner: Wagento, Technical, Waiting for response, partners-contribution

#3834 Fix incorrect pre tag & indentation in documentation
  guides/v2.1/cloud/setup/first-time-setup-import-first-steps.md
Labels: Editorial

#3829 Content update for "Code Contributions" page
  _includes/contributor/labels.md
  _includes/contributor/rewards.md
  guides/v2.3/contributor-guide/contributing.md
Labels: 2.2.x, 2.3.x, Editorial

#3892 Adding Page Builder TOC
  _data/main-nav.yml
  _data/toc/page-builder.yml
  _data/toc/release-notes.yml
  _includes/layout/after-site-header.html
Labels: 2.3.x, internal-dev

#3897 Add page-builder docs to rake init
  rakelib/multirepo.rake
Labels: Site improvements

#3891 Fix graphql query/mutation indentation
  guides/v2.3/graphql/reference/bundle-product.md
  guides/v2.3/graphql/reference/categories.md
  guides/v2.3/graphql/reference/cms.md
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/graphql/reference/custom-attribute-metadata.md
  guides/v2.3/graphql/reference/customer.md
  guides/v2.3/graphql/reference/customizable-option-interface.md
  guides/v2.3/graphql/reference/downloadable-product.md
  guides/v2.3/graphql/reference/gift-card-product.md
  guides/v2.3/graphql/reference/grouped-product.md
  guides/v2.3/graphql/reference/product-interface-implementations.md
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/graphql/reference/quote.md
  guides/v2.3/graphql/reference/sales.md
  guides/v2.3/graphql/reference/store-config.md
  guides/v2.3/graphql/reference/url-resolver.md
  guides/v2.3/graphql/reference/wishlist.md
Labels: 2.3.1, Editorial

#3899 Add a rake update task for page-builder docs
  rakelib/update.rake
Labels: Site improvements

#3894 Remove note as 2.3 is officially released
  guides/v2.3/graphql/index.md
Labels: 2.3.x, Editorial

#3907 Fixing broken links
  guides/v2.1/frontend-dev-guide/translations/translate_theory.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3909 Generated news update from PRs for the recent week
  _data/whats-new.yml
Labels: Editorial

#3828 Added format of parameter.
  guides/v2.2/b2b/company-users.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3911 Document Directory endpoint
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/directory.md
Labels: 2.3.1, Community, Major update

#3888 Added remaining soap services
  _includes/webapi/services22.md
  _includes/webapi/services23.md
Labels: 2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3903 Fix list command call in cli guidelines
  guides/v2.0/extension-dev-guide/cli-cmds/cli-naming-guidelines.md
  guides/v2.1/extension-dev-guide/cli-cmds/cli-naming-guidelines.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Mediotype, Technical, partners-contribution

#3915 Update install-roadmap_cli.html
  guides/v2.2/install-gde/install-roadmap_cli.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: ISM eCompany, partners-contribution

#3912 Add notes about mutations not being supported in 2.3.1
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.1, internal-dev

#3920 Fix Page Builder TOC to reflect recent changes
  _data/toc/page-builder.yml
Labels: Editorial

#3918 Add missing type
  guides/v2.3/rest/modules/inventory/check-salable-quantity.md
Labels: 2.3.x, Community, Technical

#3902 Added headers for the customer resource api
  guides/v2.2/b2b/negotiable-order-workflow.md
  guides/v2.2/b2b/negotiable-update.md
Labels: 2.2.x, Community, Partner: Krish TechnoLabs, Technical, partners-contribution

#3884 Added missing parameters and default value column
  guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.md
Labels: 2.2.x, Community, Technical

#3921 Update guides/v2.3/install-gde/prereq/prereq-overview.html
  guides/v2.3/install-gde/prereq/prereq-overview.md
Labels: Partner: ISM eCompany, partners-contribution

#3904 Fix broken js highlighter rendering
  guides/v2.1/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
Labels: Editorial, Partner: Mediotype, partners-contribution

#3916 Add ES 5.2 as supported Cloud service
  guides/v2.2/cloud/project/project-conf-files_services.md
Labels: 2.2.x, 2.3.x, Technical

#3919 Add links to graphql-ce repo for mutations
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/graphql/reference/quote.md
Labels: 2.3.1, internal-dev

#3926 Fixing top-level nav title to match guide name. #3886
  _data/main-nav.yml
Labels: 2.2.x, 2.3.x, Editorial

#3890 Adding support for Elasticsearch 6.
  _data/toc/configuration-guide.yml
  _includes/config/es-elasticsearch-magento.md
  _includes/install/php_2.2.md
  _includes/install/php_2.3.md
  common/images/elastic_choose-in-admin-es6.png
  common/images/elastic_choose-in-admin.png
  guides/v2.1/config-guide/elasticsearch/es-downgrade.md
  guides/v2.1/install-gde/system-requirements-tech.md
  guides/v2.2/config-guide/elasticsearch/es-downgrade.md
  guides/v2.2/config-guide/elasticsearch/es-overview.md
  guides/v2.2/install-gde/system-requirements-tech.md
  guides/v2.2/performance-best-practices/software.md
  guides/v2.3/config-guide/elasticsearch/es-downgrade.md
  guides/v2.3/config-guide/elasticsearch/es-overview.md
  guides/v2.3/install-gde/prereq/php-centos-ubuntu.md
  guides/v2.3/install-gde/prereq/prereq-overview.md
  guides/v2.3/install-gde/system-requirements-tech.md
  guides/v2.3/performance-best-practices/software.md
Labels: 2.2.x, 2.3.x, Major update

#3876 update of backward compatibility policy
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
  guides/v2.1/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.1/extension-dev-guide/versioning/dependencies.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3933 MAGEDOC-3583: RTM topics and tasks
  _data/toc/page-builder.yml
Labels: 2.3.x, Editorial, internal-dev

#3893 MAGECLOUD-3082 update architecture grid
  guides/v2.1/cloud/architecture/cloud-architecture.md
Labels: 2.x, Technical

#3871 Update technical-guidelines.md
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.2.x, 2.3.x, Major update

#3934 Fix wrong path and update path of indexing
  guides/v2.0/extension-dev-guide/indexing.md
  guides/v2.1/release-notes/ReleaseNotes2.1.8CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.8EE.md
  guides/v2.2/performance-best-practices/configuration.md
  guides/v2.3/performance-best-practices/configuration.md
Labels: 2.1.x, 2.2.x, 2.3.x

#3699 Update info about the Fastly response headers that should be checked for CDN troubleshooting
  guides/v2.1/cloud/cdn/trouble-fastly.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3932 Message queue topic described as API.
  guides/v2.1/contributor-guide/backward-compatible-development/index.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3939 Grammar doctoring
  README.md
Labels: 2.3.x, Editorial

#3937 Fix WysiwygDefaultConfig class name
  guides/v2.3/ui_comp_guide/components/wysiwyg/extension-points/index.md
Labels: 2.3.x, Editorial

#3931 Fixed DocBlock comment and correct class name
  guides/v2.3/extension-dev-guide/variable-pool/index.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3951 Update JsTestDriver info for 2.2 and remove for 2.3
  _data/toc/testing.yml
  guides/v2.1/mtf/mtf_introduction.md
  guides/v2.1/test/js/test_js-unit.md
  guides/v2.2/test/testing.md
  guides/v2.3/test/js/test_js-unit.md
Labels: 2.2.x, 2.3.x, Technical

#3950 Added missing argument in function
  guides/v2.2/extension-dev-guide/message-queues/bulk-operations.md
  guides/v2.3/extension-dev-guide/message-queues/bulk-operations.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3896 Update Customer attributes
  guides/v2.3/graphql/reference/customer.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#3929 Added missing attribute of customizable option interface
  guides/v2.3/graphql/reference/customizable-option-interface.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3917 Update ReleaseNotes2.1.16CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.16CE.md
Labels: Partner: ISM eCompany, partners-contribution

#3952 Updates based on feedback
  guides/v2.1/cloud/cdn/trouble-fastly.md
Labels: 2.1.x, 2.2.x, 2.3.x, internal-dev

#3957 Document multiple arguments for trans directive
  guides/v2.1/frontend-dev-guide/templates/template-email.md
Labels: Partner: Mediotype, partners-contribution

#3914 Extension dev enable module path correction
  guides/v2.1/extension-dev-guide/build/enable-module.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3961 MD-3608 reCAPTCHA install command update
  guides/v2.1/security/google-recaptcha.md
Labels: 2.1.x, 2.2.x, Technical, internal-dev

#3963 Release notes 2 2 8
  _data/toc/release-notes.yml
  _includes/release-notes/engcomm-2-2-8-issues.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.2/release-notes/bk-release-notes.md
Labels: 2.3.1, Major update

#3964 Release notes 2 3 1
  _data/toc/release-notes.yml
  _includes/release-notes/engcomm-2-3-1-issues.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/bk-release-notes.md
Labels: 2.2.8, Major update

#3953 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#3946 Update authentication/gs-authentication-token.md
  guides/v2.1/get-started/authentication/gs-authentication-token.md
Labels: Partner: ISM eCompany, partners-contribution

#3974 Added api of unapply customer balance
  guides/v2.2/rest/list.md
Labels: 2.2.8, Partner: Krish TechnoLabs, Technical, partners-contribution

#3969 Update extension-dev-guide/indexing-custom.md
  guides/v2.1/extension-dev-guide/indexing-custom.md
Labels: Partner: ISM eCompany, partners-contribution

#3959 Fixed broken link to PHP docs.
  guides/v2.1/test/integration/integration_test_execution.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3960 Update index.md
  guides/v2.3/ui_comp_guide/components/wysiwyg/extension-points/index.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3947 Update static-content-signing.md
  guides/v2.2/config-guide/cache/static-content-signing.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: ISM eCompany, partners-contribution

#3943 Updated the visibility of a property as per codebase
  guides/v2.1/extension-dev-guide/factories.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3938 Add link of command class example
  guides/v2.1/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3949 Update composer.md
  guides/v2.1/install-gde/composer.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3965 2.3.1 MSI Inventory Management release notes update
  _data/toc/release-notes.yml
  _includes/inventory-management/release-notes/intro.md
  _includes/inventory-management/release-notes/v1-1-0.md
  guides/v2.3/inventory/release-notes.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/inventory-management.md
Labels: 2.3.1, Technical, msi-1.1.0

#3981 Release notes 2 1 17
  _data/toc/release-notes.yml
  guides/v2.1/release-notes/ReleaseNotes2.1.17CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.17EE.md
  guides/v2.1/release-notes/bk-release-notes.md
Labels: 2.1.17, Major update

#3985 MAGECLOUD-3317 remove reference to Smile
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.2.x, Technical, internal-dev

#3984 Fixing "Mangento" typo in cloud guide
  guides/v2.0/cloud/before/before-workspace-cloud-account.md
  guides/v2.1/cloud/before/before-workspace-cloud-account.md
Labels: 2.x, Editorial, Partner: Atwix, partners-contribution

#3986 MAGEDOC-3628: Removed empty topic
  guides/v2.1/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_overview.md
  guides/v2.2/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_overview.md
  guides/v2.3/ui_comp_guide/troubleshoot/ui_comp_troubleshoot_overview.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3941 Add a plugin to generate page.versions
  _includes/layout/version-switcher.html
  _plugins/page-versions.rb
Labels: Site improvements

#3970 Update rake tasks automating work with subrepositories
  rakelib/multirepo.rake
  rakelib/update.rake
Labels: Site improvements

#3696 Performance Load Testing dev doc page
  guides/v2.3/cloud/live/testing-store.md
Labels: Major update, internal-dev

#3987 Added missing argument in function and updated code as per codebase
  guides/v2.1/mtf/mtf_entities/mtf_testcase.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3972 Update wrong configuration path
  guides/v2.1/ext-best-practices/storefront/storefront-best-practices.md
  guides/v2.1/get-started/bk-get-started-api.md
  guides/v2.2/config-guide/varnish/config-varnish-advanced.md
  guides/v2.2/performance-best-practices/configuration.md
  guides/v2.3/performance-best-practices/configuration.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3971 Update the Magento third party licenses topic
  magento-third-party.md
Labels: 2.2.x, 2.3.x, Editorial, In progress, groomed

#3901 Update project-conf-files_services-rabbit.md
  guides/v2.1/cloud/project/project-conf-files_services-rabbit.md
Labels: 2.2.x, Technical

#3989 Add Partner lists to release notes
  _includes/release-notes/engcomm-2-2-8-partner.md
  _includes/release-notes/engcomm-2-3-1-partner.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 2.3.1, Technical, internal-dev

#3954 grunt command for specified theme
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
Labels: Partner: Krish TechnoLabs, Technical, partners-contribution

#3996 Update orders/order-create-customer.md
  guides/v2.1/cloud/project/project-conf-files_services-rabbit.md
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.1/rest/tutorials/orders/order-create-customer.md
Labels: Partner: ISM eCompany, partners-contribution, small changes

#3991 Update configuration path
  guides/v2.1/get-started/bk-get-started-api.md
  guides/v2.1/release-notes/ReleaseNotes2.1.11CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.11EE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.13CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.13EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, partners-contribution, small changes

#3995 Update flow-diagram.md
  _includes/install/flow-diagram.md
Labels: 2.x, Editorial, Partner: ISM eCompany, partners-contribution

#3990 Update js-resources.md
  _includes/install/flow-diagram.md
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.1.x, small changes

#3973 Add 2.3.1 GraphQL release notes
  _data/toc/graphql.yml
  guides/v2.3/graphql/reference/product-interface-implementations.md
  guides/v2.3/graphql/release-notes.md
Labels: 2.3.1, New topic, internal-dev

#3993 Changed kramdown wording
  .github/CONTRIBUTING.md
  community/resources/multi-repo-docs.md
Labels: Editorial, Partner: Atwix, partners-contribution

#3997 Extension Dev Guide > Fixing highlights for PHP
  .github/CONTRIBUTING.md
  community/resources/multi-repo-docs.md
  guides/v2.2/extension-dev-guide/plugins.md
Labels: 2.3.2, Partner: Imagination Media, partners-contribution, small changes

#3998 Fixed link formatting
  guides/v2.1/cloud/cdn/fastly-vcl-wordpress.md
Labels: 2.1.x, 2.2.x, 2.3.x, internal-dev, small changes

#3523 Add Request Processors pool documentation for WebApi
  guides/v2.3/extension-dev-guide/webapi/request-processor-pool.md
Labels: 2.3.1, Community, New doc, Partner: Comwrap, partners-contribution

#4002 Backpoint PR-3523 to 2.2
  _data/toc/php-developer-guide.yml
  guides/v2.2/extension-dev-guide/webapi/request-processor-pool.md
Labels: 2.2.x, Community, New doc, internal-dev

#4004 backport item to 2.0 Technical Guidelines
  guides/v2.0/coding-standards/technical-guidelines.md
Labels: 2.0.x, Technical, internal-dev

#4000 magento/devdocs#: Fix for ResolverInterface return type
  guides/v2.3/graphql/develop/resolvers.md
Labels: 2.3.x, Editorial, Partner: Atwix, partners-contribution

#3597 Added missing store part in url
  guides/v2.1/extension-dev-guide/attributes.md
  guides/v2.1/get-started/authentication/gs-authentication-token.md
  guides/v2.1/rest/notes.md
  guides/v2.1/rest/performing-searches.md
  guides/v2.1/rest/retrieve-filtered-responses.md
  guides/v2.1/rest/tutorials/orders/order-add-items.md
  guides/v2.1/rest/tutorials/orders/order-admin-token.md
  guides/v2.1/rest/tutorials/orders/order-create-customer.md
  guides/v2.1/rest/tutorials/orders/order-create-invoice.md
  guides/v2.1/rest/tutorials/orders/order-create-order.md
  guides/v2.1/rest/tutorials/orders/order-create-quote.md
  guides/v2.1/rest/tutorials/orders/order-create-shipment.md
  guides/v2.1/rest/tutorials/orders/order-issue-refund.md
  guides/v2.1/rest/tutorials/orders/order-prepare-checkout.md
  guides/v2.2/b2b/company-object.md
  guides/v2.2/b2b/company-structures.md
  guides/v2.2/b2b/company-users.md
  guides/v2.2/b2b/credit-manage.md
  guides/v2.2/b2b/negotiable-checkout.md
  guides/v2.2/b2b/negotiable-manage.md
  guides/v2.2/b2b/negotiable-order-workflow.md
  guides/v2.2/b2b/negotiable-update.md
  guides/v2.2/b2b/roles.md
  guides/v2.2/b2b/shared-cat-company.md
  guides/v2.2/b2b/shared-cat-manage.md
  guides/v2.2/b2b/shared-cat-product-assign.md
  guides/v2.2/rest/asynchronous-web-endpoints.md
  guides/v2.2/rest/modules/catalog-pricing.md
  guides/v2.2/rest/notes.md
  guides/v2.2/rest/operation-status-search.md
  guides/v2.2/rest/performing-searches.md
  guides/v2.2/rest/retrieve-filtered-responses.md
  guides/v2.2/rest/tutorials/configurable-product/plan-product.md
  guides/v2.2/rest/tutorials/prerequisite-tasks/create-admin-token.md
  guides/v2.3/rest/asynchronous-web-endpoints.md
  guides/v2.3/rest/modules/inventory/bulk-inventory.md
  guides/v2.3/rest/modules/inventory/check-salable-quantity.md
  guides/v2.3/rest/modules/inventory/link-stocks-sources.md
  guides/v2.3/rest/modules/inventory/manage-low-quantity.md
  guides/v2.3/rest/modules/inventory/manage-source-items.md
  guides/v2.3/rest/modules/inventory/manage-source-selection.md
  guides/v2.3/rest/modules/inventory/manage-sources.md
  guides/v2.3/rest/modules/inventory/manage-stocks.md
  guides/v2.3/rest/operation-status-search.md
  guides/v2.3/rest/performing-searches.md
  guides/v2.3/rest/retrieve-filtered-responses.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/plan-product.md
  guides/v2.3/rest/tutorials/inventory/assign-source-to-stock.md
  guides/v2.3/rest/tutorials/inventory/bulk-transfer-products.md
  guides/v2.3/rest/tutorials/inventory/create-cart-add-products.md
  guides/v2.3/rest/tutorials/inventory/create-customer.md
  guides/v2.3/rest/tutorials/inventory/create-invoice.md
  guides/v2.3/rest/tutorials/inventory/create-order.md
  guides/v2.3/rest/tutorials/inventory/create-shipment.md
  guides/v2.3/rest/tutorials/inventory/create-sources.md
  guides/v2.3/rest/tutorials/inventory/create-stock.md
  guides/v2.3/rest/tutorials/inventory/prepare-for-checkout.md
  guides/v2.3/rest/tutorials/inventory/reassign-products-to-another-source.md
  guides/v2.3/rest/tutorials/inventory/run-ssa.md
  guides/v2.3/rest/tutorials/orders/order-issue-refund.md
Labels: 1.x, 2.x, Partner: Krish TechnoLabs, Special achievement, Technical, partners-contribution

#4020 Formatting the configuration to match to the configurations' styling
  guides/v2.1/install-gde/install/cli/install-cli-install.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution

#4023 Fixed Datatype of "identifiers" field
  guides/v2.3/graphql/reference/cms.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4014 Update new_component_declaration.md
  guides/v2.2/ui_comp_guide/howto/new_component_declaration.md
Labels: 2.3.x, 2.x, Editorial

#4016 Removed extra dependency and correct class name in function argument
  guides/v2.1/extension-dev-guide/depend-inj.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, partners-contribution

#4015 magento/devdocs#: Replace ``` php with ``` json for the JSON data
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/index.md
Labels: 2.3.x, Editorial, Partner: Atwix, partners-contribution

#4018 Safari browser Discontinuing (Microsoft Windows OS) from 2012
  _includes/browsers/supported-browsers.md
Labels: 2.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4025 Added LESS word, Developer also familiar with LESS
  guides/v2.1/frontend-dev-guide/bk-frontend-dev-guide.md
Labels: 2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3935 Update tshoot_access-browser.html
  guides/v2.3/install-gde/trouble/tshoot_access-browser.md
Labels: Partner: ISM eCompany, partners-contribution

#4005 MAGECLOUD-3234 Reducing downtime
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/deploy/optimize-cloud-deployment.md
  guides/v2.1/cloud/deploy/reduce-downtime.md
  guides/v2.1/cloud/deploy/static-content-deployment.md
  guides/v2.2/cloud/deploy/reduce-downtime.md
  guides/v2.3/cloud/deploy/reduce-downtime.md
Labels: 2.2.x, New doc, internal-dev

#4029 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#4031 Update description of topic_names
  guides/v2.3/rest/operation-status-endpoints.md
Labels: 2.3.1, Editorial, internal-dev

#4036 Fix for GiftCardProduct documentation
  _data/toc/cloud-guide.yml
  _data/whats-new.yml
  guides/v2.1/cloud/deploy/optimize-cloud-deployment.md
  guides/v2.1/cloud/deploy/reduce-downtime.md
  guides/v2.1/cloud/deploy/static-content-deployment.md
  guides/v2.2/cloud/deploy/reduce-downtime.md
  guides/v2.3/cloud/deploy/reduce-downtime.md
  guides/v2.3/graphql/reference/gift-card-product.md
  guides/v2.3/install-gde/trouble/tshoot_access-browser.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4034 MAGEDOC-3637: Update PageBuiler TOC and remove beta banner
  _data/toc/page-builder.yml
  _includes/layout/after-site-header.html
Labels: 2.3.1, Site improvements, Tracking, internal-dev

#4006 Fixing Grammatical Mistakes
  guides/v2.1/comp-mgr/trouble/cman/out-of-memory.md
  guides/v2.1/frontend-dev-guide/bk-frontend-dev-guide.md
  guides/v2.3/ui_comp_guide/bk-ui_comps.md
Labels: 2.3.x, Editorial, Waiting for response

#4003 Updating third-party license links
  _data/footer-links.yml
  guides/v2.3/release-notes/thirdparty_ce.md
  magento-third-party.md
Labels: 2.x, internal-dev

#3925 MERGE IN 2.3.2: Fixed table structure with removing space and removed deprecated attribute.
  guides/v2.3/graphql/reference/url-resolver.md
Labels: 2.3.2, Community, Partner: Krish TechnoLabs, Technical, partners-contribution

#4048 Updated currency and removed deprecated attributes from DirectoryGraphQl
  guides/v2.3/graphql/reference/directory.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#4007 magento/devdocs#: Exception handling
  guides/v2.3/graphql/develop/exceptions.md
Labels: 2.3.x, Community, Partner: Atwix, Technical, partners-contribution

#4011 Added sensitive configuration of braintree phone
  guides/v2.2/config-guide/prod/config-reference-sens.md
  guides/v2.3/config-guide/prod/config-reference-sens.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#3983 Added missing argument in virtualType
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4035 MAGECLOUD-3237: Update Elasticsearch support info
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/project/project-conf-files_services-elastic.md
  guides/v2.1/cloud/project/project-conf-files_services.md
  guides/v2.2/cloud/project/project-conf-files_services-elastic.md
  guides/v2.2/cloud/project/project-conf-files_services.md
  guides/v2.3/cloud/project/project-conf-files_services-elastic.md
Labels: 2.1.x, 2.2.x, 2.3.x, internal-dev

#4001 Update create-graphqls-file.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
Labels: 2.3.x, Community, Editorial, Partner: Atwix, partners-contribution

#4049 Hot Fix March 26 2019
  guides/v2.1/release-notes/ReleaseNotes2.1.16CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.16EE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.17CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.17EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 2.1.17, 2.2.8, 2.3.0, 2.3.1, Major update

#4051 fix code gates that were incorrectly applied in 2.3.1
  guides/v2.2/performance-best-practices/software.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/reference/directory.md
  guides/v2.3/graphql/reference/downloadable-product.md
  guides/v2.3/graphql/reference/sales.md
  guides/v2.3/graphql/reference/store-config.md
  guides/v2.3/graphql/reference/url-resolver.md
  guides/v2.3/install-gde/prereq/prereq-overview.md
Labels: 2.3.x, Editorial, internal-dev

#4044 Add info about backward incompatible changes in 2.1.17 release
  _includes/backward-incompatible-changes/commerce/2.1.16-2.1.17.md
  _includes/backward-incompatible-changes/open-source/2.1.16-2.1.17.md
  guides/v2.1/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.1/release-notes/backward-incompatible-changes/open-source.md
Labels: 2.1.17, Technical

#4045 Add info about backward incompatible changes in 2.2.8 release
  _includes/backward-incompatible-changes/commerce/2.2.7-2.2.8.md
  _includes/backward-incompatible-changes/open-source/2.2.7-2.2.8.md
  guides/v2.2/release-notes/backward-incompatible-changes/commerce.md
  guides/v2.2/release-notes/backward-incompatible-changes/open-source.md
Labels: 2.2.8, Major update

#4057 UI library Components "tabs and accordions" are already in sections
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: Editorial, Partner: Krish TechnoLabs, partners-contribution

#4053 Punctuation fix
  guides/v2.1/architecture/archi_perspectives/persist_layer.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Vaimo, partners-contribution

#4055 2.3 release note spell correction
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 2.3.1, Editorial
