Repository magento/devdocs, pull requests merged in 2019-01, with the labels that each got.

#3504 Update lifecycle.md
  guides/v2.1/extension-dev-guide/prepare/lifecycle.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3510 Comwrap api synonyms
  _data/toc/php-developer-guide.yml
  guides/v2.2/extension-dev-guide/webapi/custom-routes.md
Labels: 2.2.x, Community, Editorial, Partner: Comwrap, partners-contribution

#3509 Remove custom routes implementation from 2.2 devdocs
  guides/v2.1/extension-dev-guide/prepare/lifecycle.md
Labels: Partner: Comwrap, partners-contribution

#3505 Fixed file path in example 2
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: ISM eCompany, Technical, partners-contribution

#3506 Update adding-attributes.md
  guides/v2.1/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3490 MAGECLOUD-2823: SCD_COMPRESSION_LEVEL - Wrong Default Value in Sample…
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-deploy.md
Labels: In progress, internal-dev

#3513 Add endpoint for swagger API
  guides/v2.3/rest/generate-local.md
Labels: 2.3.1, Partner: Comwrap, partners-contribution

#3517 Typo fix (minor)
  guides/v2.1/extension-dev-guide/proxies.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3512 3511 composer auth
  _includes/install/auth-json.md
  _includes/install/composer-clone.md
  _includes/install/prereq.md
  guides/v2.0/install-gde/prereq/dev_install.md
  guides/v2.1/install-gde/prereq/dev_install.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3519 Added redirect for old ece-tools update topic
  guides/v2.1/cloud/project/ece-tools-update.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3525 Enable more checks with link checker
  Rakefile
  _config.checks.yml
  _config.yml
  _data/whats-new.yml
  _plugins/html-check-hook.rb
  guides/v2.0/template.md
  guides/v2.1/cloud/cdn/trouble-fastly.md
  guides/v2.1/template.md
  guides/v2.2/template.md
  guides/v2.3/modules/bluefoot-cms/iconography.md
  guides/v2.3/template.md
  rakelib/converter.rb
  rakelib/jekyll.rb
  rakelib/link-checker.rb
  rakelib/preview.rake
  rakelib/proofer.rb
  rakelib/rake-helper.rb
  rakelib/test.rake
  rakelib/update.rake
Labels: 2.x, Editorial, Site improvements

#3527 Update php_clear-dirs.md
  guides/v2.2/howdoi/php/php_clear-dirs.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Wagento, partners-contribution

#3529 Fix #2756 update command
  guides/v2.1/config-guide/prod/prod_file-sys-perms.md
  guides/v2.2/config-guide/prod/prod_file-sys-perms.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3530 Remove gulpfile and clean the NPM dependencies
  _config.yml
  common/css/devdocs.css
  common/js/devdocs.min.js
  gulpfile.js
  js/_includes/survey.js
  js/devdocs.js
  package-lock.json
  package.json
  scss/_variables.scss
  scss/devdocs.scss
  scss/partials/_contributors.scss
  scss/partials/_home.scss
  scss/partials/_list-icons.scss
Labels: Site improvements, internal-dev

#3533 Update theme to be from master branch
  Gemfile
  Gemfile.lock
Labels: 2.x, Site improvements

#3538 Update db-schema.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Partner: Wagento, Technical, partners-contribution

#3537 Update data-patches.md
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
Labels: 2.3.x, Partner: Wagento, Technical, partners-contribution

#3495 MAGEDOC-3312: Added note to screenshot action in MFTF docs
  mftf/2.3/test/actions.md
Labels: 2.2.x, 2.3.x, Technical

#3542 MAGECLOUD-3039 clarify Blackfire support for pro and starter
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, internal-dev

#3526 MAGECLOUD-3046: [Cloud Docker] Remove deprecated CLI container
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
Labels: internal-dev

#3547 removed sentence from RN about PB evaluation enrollment
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
Labels: 2.3.x, Editorial, internal-dev

#3546 Typo corrected translati9on -> translation
  guides/v2.1/config-guide/cli/config-cli-subcommands-i18n.md
Labels: 2.1.x, 2.2.x, Community Insider: Cedcommerce, Editorial, community-insider-contribution

#3541 Update cli-upgrade.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Partner: Space 48, Technical, partners-contribution

#3536 Resolve symlinks for the page.last-modified-at parameter
  _plugins/last-modified-at.rb
  rakelib/test.rake
Labels: 2.x, Site improvements

#3549 Typo correction in technical guidelines
  guides/v2.1/coding-standards/technical-vision/index.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#3551 Remove extension_attributes variable
  guides/v2.2/rest/operation-status-endpoints.md
  guides/v2.3/rest/operation-status-endpoints.md
Labels: 2.2.x, Partner: Comwrap, Technical, partners-contribution

#3550 Fix typo preventing <h3> in Markdown
  _includes/install/auth-json.md
Labels: 2.x, Editorial

#2665 Annotations in the Integration Testing Framework
  _data/toc/testing.yml
  guides/v2.1/test/integration/annotations/magento-app-area.md
  guides/v2.1/test/integration/annotations/magento-app-isolation.md
  guides/v2.1/test/integration/annotations/magento-cache.md
  guides/v2.1/test/integration/annotations/magento-components-dir.md
  guides/v2.1/test/integration/annotations/magento-config-fixture.md
  guides/v2.1/test/integration/annotations/magento-data-fixture.md
  guides/v2.1/test/integration/annotations/magento-db-isolation.md
  guides/v2.2/test/integration/annotations/magento-app-area.md
  guides/v2.2/test/integration/annotations/magento-app-isolation.md
  guides/v2.2/test/integration/annotations/magento-cache.md
  guides/v2.2/test/integration/annotations/magento-components-dir.md
  guides/v2.2/test/integration/annotations/magento-config-fixture.md
  guides/v2.2/test/integration/annotations/magento-data-fixture.md
  guides/v2.2/test/integration/annotations/magento-db-isolation.md
  guides/v2.3/test/integration/annotations/magento-app-area.md
  guides/v2.3/test/integration/annotations/magento-app-isolation.md
  guides/v2.3/test/integration/annotations/magento-cache.md
  guides/v2.3/test/integration/annotations/magento-components-dir.md
  guides/v2.3/test/integration/annotations/magento-config-fixture.md
  guides/v2.3/test/integration/annotations/magento-data-fixture.md
  guides/v2.3/test/integration/annotations/magento-db-isolation.md
Labels: 2.1.x, In progress, New doc, internal-dev

#3544 Fixed path of PatchVersionInterface
  guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
  guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3539 Update bulk-endpoints.md
  guides/v2.3/rest/bulk-endpoints.md
Labels: 2.3.x, Partner: Wagento, Technical, partners-contribution

#3552 MAGEDOC-3399: Product availability update
  availability.md
Labels: Major update

#3545 Db magedoc 3514 redis
  guides/v2.1/config-guide/redis/config-redis.md
  guides/v2.1/config-guide/redis/redis-pg-cache.md
  guides/v2.1/config-guide/redis/redis-session.md
  guides/v2.2/config-guide/redis/config-redis.md
  guides/v2.2/config-guide/redis/redis-pg-cache.md
  guides/v2.2/config-guide/redis/redis-session.md
  guides/v2.3/config-guide/redis/redis-session.md
Labels: 2.2.x, 2.3.x, Technical

#3556 Add user_type parameter
  guides/v2.3/rest/operation-status-endpoints.md
Labels: 2.3.x, Partner: Comwrap, Technical, partners-contribution

#3567 Updating the broken link > UI Components Config
  guides/v2.2/ui_comp_guide/concepts/ui_comp_modifier_concept.md
Labels: Editorial, Partner: Imagination Media, partners-contribution

#3568 Fixed TOC. Set to installation-guide.
  guides/v2.1/install-gde/install/sample-data-before-clone.md
  guides/v2.1/install-gde/install/sample-data-before-composer.md
  guides/v2.1/install-gde/install/sample-data-other-cmds.md
  guides/v2.1/install-gde/install/sample-data.md
Labels: 2.x, Technical

#3561 Fix installation command accidentally changing ownership throughout root filesystem
  guides/v2.1/install-gde/composer.md
  guides/v2.1/install-gde/prereq/nginx.md
  guides/v2.2/install-gde/prereq/nginx.md
  guides/v2.3/install-gde/composer.md
  guides/v2.3/install-gde/prereq/nginx.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3570 MAGECLOUD-2067 clarify branching
  guides/v2.1/cloud/before/before-setup-env-2_clone.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
Labels: Technical, internal-dev

#3562 Link checker: Check for double forward slashes
  Rakefile
  _data/whats-new.yml
  _plugins/html-check-hook.rb
  guides/v2.0/extension-dev-guide/code-generation.md
  guides/v2.0/frontend-dev-guide/responsive-web-design/rwd_css.md
  guides/v2.0/frontend-dev-guide/responsive-web-design/rwd_js.md
  guides/v2.0/frontend-dev-guide/themes/theme-create.md
  guides/v2.1/config-guide/config/config-php.md
  guides/v2.1/extension-dev-guide/code-generation.md
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
  guides/v2.1/frontend-dev-guide/responsive-web-design/rwd_css.md
  guides/v2.1/frontend-dev-guide/themes/theme-create.md
  guides/v2.1/javascript-dev-guide/javascript/js_debug.md
  guides/v2.1/payments-integrations/vault/payment-token.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_linking_concept.md
  guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/extension-dev-guide/code-generation.md
  guides/v2.2/extension-dev-guide/searching-with-repositories.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/payments-integrations/vault/payment-token.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  mftf/2.3/getting-started.md
  rakelib/converter.rb
  rakelib/double-slash-check.rb
Labels: Site improvements

#3563 Removed unnecessary comma (,) from the page
  guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.md
Labels: 2.1.x, Community Insider: Cedcommerce, Editorial, community-insider-contribution

#3576 Updated html for ui- wysiwyg page
  guides/v2.1/ui_comp_guide/components/ui-wysiwyg.md
  guides/v2.2/ui_comp_guide/components/ui-wysiwyg.md
  guides/v2.3/ui_comp_guide/components/ui-wysiwyg.md
Labels: 2.1.x, 2.2.x, 2.3.x, Community Insider: Cedcommerce, Editorial, community-insider-contribution

#3572 Added additional directories
  guides/v2.1/extension-dev-guide/build/module-file-structure.md
  guides/v2.3/extension-dev-guide/build/module-file-structure.md
Labels: 2.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3575 Updated text about setting docroot to pub.
  guides/v2.3/install-gde/tutorials/change-docroot-to-pub.md
Labels: 2.3.x, Technical

#3577 2FA and reCAPTCHA update for 2.3
  _data/toc/configuration-guide.yml
  guides/v2.3/security/google-recaptcha.md
  guides/v2.3/security/two-factor-authentication.md
Labels: 2.3.x, Major update

#3578 MAGECLOUD-1581 change base template
  guides/v2.2/cloud/project/project-start.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#3583 Update upgrade information for MSI
  guides/v2.3/comp-mgr/install-extensions/inventory-management-installation.md
Labels: 2.3.x, Community, Technical, internal-dev

#3579 Resolve spelling mistakes
  guides/v2.3/graphql/develop/resolvers.md
Labels: Community Insider: Cedcommerce, community-insider-contribution

#3584 Added section on structuring action groups.
  mftf/2.3/test/action-groups.md
Labels: 2.3.x, Major update

#3587 Clarified the diff between public and private code.
  guides/v2.1/extension-dev-guide/versioning/codebase-changes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3589 Improved Content
  guides/v2.3/inventory/index.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
Labels: 2.3.x, Community Insider: Cedcommerce, Editorial, community-insider-contribution

#3581 Small url alignment
  guides/v2.2/rest/tutorials/configurable-product/create-personalization-option.md
Labels: 2.2.x, 2.3.x, Partner: Comwrap, Technical, partners-contribution

#3553 Update mtf_scenariotest.md
  guides/v2.1/mtf/mtf_entities/mtf_scenariotest.md
  guides/v2.2/mtf/mtf_entities/mtf_scenariotest.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3596 Adding section on php max-input-vars
  guides/v2.1/install-gde/trouble/php/tshoot_php-set.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#3585 Added configuration update command in command summary
  guides/v2.2/config-guide/cli/config-cli-subcommands.md
Labels: 2.2.x, Community Insider: Cedcommerce, Editorial, community-insider-contribution

#3599 Default value for area-code
  _includes/config/message-queue-consumers.md
Labels: 2.x, Partner: Wagento, Technical, partners-contribution

#3600 Update checkout_new_step.md
  guides/v2.1/howdoi/checkout/checkout_new_step.md
Labels: 2.x, Editorial

#3602 Consolidate Caching sections to address #1612
  guides/v2.1/extension-dev-guide/cache/page-caching/public-content.md
Labels: 2.1.x, 2.2.x, 2.3.x

#3604 Weekly digest
  _data/whats-new.yml
  whats-new.md
Labels: Editorial

#3609 added translate attribute to labels
  guides/v2.1/howdoi/checkout/checkout_form.md
Labels: 2.1.x, 2.3.x, 2.x, Technical

#3603 Update Magento Release Info with link to Cloud release notes
  guides/v2.3/release-notes/bk-release-notes.md
Labels: 2.3.x, Technical

#3611 Corrected name of staging and prod deploy log
  guides/v2.1/cloud/project/project-start.md
  guides/v2.2/cloud/project/project-start.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3616 fixed syntax highlighting
  guides/v2.2/config-guide/cli/config-cli-subcommands-cron.md
Labels: 2.2.x, 2.3.x, Editorial

#3618 Disable link checking hook for 'jekyll serve'
  Rakefile
  _checks/html-check-hook.rb
  rakelib/preview.rake
Labels: Site improvements

#3595 Remove obsolete release notes
  _includes/cloud/note-ece-tools-release-info.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/release-notes/bk-release-notes.md
  guides/v2.3/cloud/release-notes/CloudReleaseNotes.md
  guides/v2.3/release-notes/bk-release-notes.md
Labels: 2.x, Editorial, Major update

#3607 Added remaining Inventory Sales Api
  guides/v2.3/rest/list.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3615 Update migration-migrate-delta.md
  guides/v2.1/migration/migration-migrate-delta.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Wagento, Technical, partners-contribution

#3620 Add example of allow all urls to load page in iframe
  guides/v2.0/config-guide/secy/secy-xframe.md
  guides/v2.1/config-guide/secy/secy-xframe.md
Labels: 2.x, Partner: Comwrap, Technical, partners-contribution

#3617 fix inconsistency between configuration code and documentation
  guides/v2.2/config-guide/config/disable-module-output.md
Labels: 2.2.x, 2.3.x, Editorial

#3627 Correct delete Inventory Low Quantity Notification Api
  guides/v2.3/rest/list.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3630 Added MSI soap API's list
  _includes/webapi/services23.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#3632 Fix MFTF assertions.md
  mftf/2.2/test/assertions.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#3636 Removed incorrect reference from columns to rows
  guides/v2.2/ui_comp_guide/components/ui-textarea.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3613 Update mtf_installation.md
  guides/v2.3/mtf/mtf_installation.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#3605 Default Value corrections for start message queue consumers
  _includes/config/message-queue-consumers.md
Labels: 2.3.x, Partner: Wagento, Technical, partners-contribution

#3633 Updating Actions reference for MFTF 2.3.13
  mftf/2.3/include/note-2.2-docs.md
  mftf/2.3/introduction.md
  mftf/2.3/test/actions.md
Labels: 2.3.x, Major update

#3635 Adding tips and tricks page to MFTF.
  _data/toc/magento-functional-testing-framework-guide-2_3.yml
  mftf/2.3/tips-tricks.md
Labels: 2.3.1, New doc

#3637 Remove obsolete file
  swagger/index2.html
Labels: 2.x, Site improvements

#3645 Fixed action names.
  mftf/2.3/test/actions.md
Labels: 2.3.x, Technical

#3644 Fix the bin/magento path
  _includes/performance/development-environment.md
Labels: 2.x, Editorial, Partner: Imagination Media, partners-contribution

#3642 Fixed SOAP error
  guides/v2.1/get-started/soap/soap-web-api-calls.md
Labels: 2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3641 Update SOAP bulk api service name
  _includes/webapi/services23.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3638 Em magento bulkapi
  _data/toc/rest-api.yml
  guides/v2.2/rest/images/add-your-name.png
  guides/v2.3/rest/tutorials/bulk-configurable-product/config-product-intro.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/create-personalization-option.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/define-config-product-options.md
  guides/v2.3/rest/tutorials/bulk-configurable-product/plan-product.md
  guides/v2.3/rest/tutorials/index.md
Labels: 2.3.x, Community, New doc, Partner: Comwrap, partners-contribution

#3643 Update Bulk route, add "async/bulk"
  guides/v2.2/rest/bulk-endpoints.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3640 Request body correction for create customer using API
  guides/v2.1/get-started/gs-web-api-request.md
Labels: 2.x, Partner: Wagento, Technical, partners-contribution

#3646 Wrong api name in details page
  guides/v2.3/rest/modules/inventory/manage-low-quantity.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3655 Wrong API example added in doc
  guides/v2.2/rest/bulk-endpoints.md
  guides/v2.3/rest/bulk-endpoints.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3651 Fixed remaining SOAP error
  guides/v2.0/get-started/soap/soap-web-api-calls.md
Labels: 2.0.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3660 Quick fix for release notes
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: Editorial

#3586 magento-cloud ssh changed, so our instructions needed updating
  guides/v2.1/cloud/project/project-integrate-blackfire.md
Labels: 2.x, Technical

#3593 Update readme
  README.md
Labels: Site improvements, internal-dev

#3659 Update xsd path to use urn
  guides/v2.1/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: 2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3557 Fixed path to integraton
  guides/v2.0/get-started/create-integration.md
  guides/v2.1/get-started/create-integration.md
  guides/v2.2/get-started/create-integration.md
  guides/v2.3/get-started/create-integration.md
Labels: 2.x, Partner: ISM eCompany, Technical, partners-contribution

#3601 Change description of running consumer
  guides/v2.2/rest/asynchronous-web-endpoints.md
  guides/v2.3/rest/asynchronous-web-endpoints.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Comwrap, partners-contribution

#3656 Added remaining api
  _includes/webapi/services23.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3654 Added Reset Password API in anonymous list
  guides/v2.1/rest/anonymous-api-security.md
  guides/v2.2/rest/anonymous-api-security.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3669 Clarifies a sentence around the umask file.
  _includes/install/file-system-umask.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial
