Repository magento/devdocs, pull requests merged in 2019-04, with the labels that each got.

#4111 add link to GraphQL release notes
  _data/toc/release-notes.yml
Labels: 2.3.x, Editorial, internal-dev

#4028 Update webapi.xml reference
  guides/v2.2/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: 2.3.2, Technical, internal-dev

#4052 How to Get Customer Authorization Token
  _data/toc/graphql.yml
  guides/v2.3/graphql/develop/get-customer-authorization-token.md
  guides/v2.3/graphql/images/graphql-authorization.png
Labels: 2.3.1, New topic, Partner: Atwix, partners-contribution

#4104 Fix the instructions to update the /update folder
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Partner: Imagination Media, Technical, partners-contribution

#4122 2.0 EOL banner
  _includes/layout/after-site-header.html
Labels: Site improvements

#4127 MAGEDOC-2588: Table does not summarize all commands
  guides/v2.1/config-guide/cli/config-cli-subcommands.md
  guides/v2.2/config-guide/cli/config-cli-subcommands.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#4126 Fixing PRs after merge
  _data/toc/graphql.yml
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.3/graphql/get-customer-authorization-token.md
Labels: 2.1.x, 2.3.1, Editorial, internal-dev

#4134 Removed extra double quote
  guides/v2.3/graphql/reference/gift-card-product.md
Labels: 2.3.x, Editorial

#4131 added missing opening php tag
  _videos/fundamentals/add-a-javascript-module.md
  _videos/fundamentals/add-a-new-table-to-database.md
  _videos/fundamentals/add-new-product-attribute.md
Labels: 2.1.x, 2.2.x, 2.3.x, Community Insider: Cedcommerce, Technical, community-insider-contribution

#4133 Changed content type to json for query result
  guides/v2.3/graphql/reference/categories.md
  guides/v2.3/graphql/reference/cms.md
  guides/v2.3/graphql/reference/configurable-product.md
  guides/v2.3/graphql/reference/custom-attribute-metadata.md
  guides/v2.3/graphql/reference/customer.md
  guides/v2.3/graphql/reference/quote.md
  guides/v2.3/graphql/reference/wishlist.md
Labels: 2.3.x, Technical

#4117 Tabs and accordions widget set with CSS for Breakpoints
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: 2.1.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4079 grunt command for specified theme in 2.2 and 2.3
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4120 Apply theme code in theme.js to running grunt for theme development
  guides/v2.2/frontend-dev-guide/tools/using_grunt.md
Labels: 2.2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#3967 Remove deprecated always_populate_raw_post_data error
  guides/v2.2/install-gde/trouble/php/tshoot_php-set.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4140 Move up 2.3.1 in availability table
  availability.md
Labels: Editorial

#4139 Revisions to GraphQL Request Headers
  _data/toc/graphql.yml
  guides/v2.3/graphql/send-request.md
Labels: 2.3.1, Technical, internal-dev

#4012 Update default max messages in manage-mysql.md
  guides/v2.2/config-guide/mq/manage-message-queues.md
  guides/v2.3/config-guide/mq/manage-message-queues.md
Labels: 2.2.x, Editorial

#4124 Fixed typos with http host match
  guides/v2.1/cloud/project/project-multi-sites.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4141 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#4103 PRODSECBUG-2347 Release Note Update
  guides/v2.1/release-notes/ReleaseNotes2.1.17CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.17EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 2.x, Major update, internal-dev

#4013 [GraphQL] Add information about debugging
  _data/toc/graphql.yml
  guides/v2.3/graphql/develop/debugging.md
Labels: 2.3.x, New topic, Partner: Atwix, partners-contribution

#4144 Add missing argument into document
  guides/v2.3/extension-dev-guide/variable-pool/index.md
Labels: 2.3.x, Technical

#4155 magento/graphql-ce# Change article's author
  guides/v2.3/graphql/get-customer-authorization-token.md
Labels: 2.3.x, Editorial, Partner: Atwix, partners-contribution

#4161 Fix path to m1x images in layouts
  _layouts/m1x.html
  _layouts/m1x_rest.html
  _layouts/m1x_soap.html
Labels: 1.x, Editorial

#4159 Fixed wrong customers save api route
  guides/v2.1/get-started/authentication/gs-authentication.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4136 Update module-load-order.md
  guides/v2.1/extension-dev-guide/build/module-load-order.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4146 Fixed JavaScript message formatting
  guides/v2.1/coding-standards/code-standard-javascript.md
  guides/v2.3/graphql/develop/resolvers.md
Labels: 2.x, Editorial

#4128 Fix PHP version number for Magento 2.2.
  _includes/install/php_2.2.md
  guides/v2.2/performance-best-practices/software.md
Labels: 2.2.x, Technical

#4163 Enable nested directories when adding a subrepository
  scripts/docs-from-code.sh
Labels: Site improvements

#4165 Fixed format issue
  guides/v2.2/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.3/comp-mgr/install-extensions/b2b-installation.md
Labels: 2.2.x, 2.3.x, Editorial

#4091 CSS source maps solve this issue. and override variables from lib css to custom theme
  common/images/fdg/lib-map.png
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.1.x, 2.2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4175 added opening php tag
  guides/v2.1/extension-dev-guide/attributes.md
  guides/v2.1/extension-dev-guide/plugins.md
Labels: Community Insider: Cedcommerce, Editorial, community-insider-contribution

#4058 Add Customize dropdown link style
  guides/v2.1/frontend-dev-guide/layouts/layout-practice.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4098 MAGEDOC-3556: Product release info
  _data/compatibility.yml
  _includes/compatibility.html
  availability.md
  release/index.md
Labels: 2.3.x, New topic, internal-dev

#4130 Mae magecloud 2822 scd max execution time
  guides/v2.2/cloud/env/variables-build.md
  guides/v2.2/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-global.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#4157 MAGECLOUD-3054: Implement Database Locks using Zookeeper and flock for Reliable HA Support
  guides/v2.2/cloud/env/variables-cloud.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.2.x, 2.3.x, Technical, internal-dev

#4084 Update for March 29, 2019 hot fix
  guides/v2.1/release-notes/ReleaseNotes2.1.17CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.17EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 2.1.17, 2.2.8, 2.3.1, internal-dev

#4174 Small changes
  _includes/install/php_2.2.md
  guides/v2.1/coding-standards/code-standard-javascript.md
  guides/v2.1/extension-dev-guide/attributes.md
  guides/v2.1/extension-dev-guide/build/module-load-order.md
  guides/v2.1/extension-dev-guide/plugins.md
  guides/v2.1/get-started/authentication/gs-authentication.md
  guides/v2.2/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.2/performance-best-practices/software.md
  guides/v2.3/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.3/graphql/develop/resolvers.md
Labels: 2.1.x, 2.2.x, 2.3.x

#4101 Known Issue MAGETWO-98947
  guides/v2.1/release-notes/ReleaseNotes2.1.17CE.md
  guides/v2.1/release-notes/ReleaseNotes2.1.17EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: internal-dev

#4186 Fix routes.yaml file using tabs vs spaces
  guides/v2.1/cloud/project/project-multi-sites.md
Labels: Editorial

#4191 Version change in installation file
  guides/v2.3/comp-mgr/install-extensions/inventory-management-installation.md
Labels: 2.3.x, Technical

#4178 remove 1page layout from the code as per the latest version magento2.3 …
  guides/v2.1/howdoi/checkout/checkout_customize.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4196 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#3992 Fixing the documentation on how to correctly copy the fieldsets with custom attributes
  guides/v2.1/ext-best-practices/tutorials/copy-fieldsets.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, partners-contribution

#4129 Add warning regarding GTID consistency
  guides/v2.1/install-gde/prereq/mysql.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/mysql.md
Labels: 2.1.x, 2.2.x, 2.3.x, Community, Technical

#4195 Zero downtime clarification
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/deploy/optimize-cloud-deployment.md
  guides/v2.1/cloud/deploy/reduce-downtime.md
Labels: Editorial

#4203 Fix Warning Formatting
  guides/v2.1/install-gde/prereq/mysql.md
  guides/v2.2/install-gde/prereq/mysql.md
  guides/v2.3/install-gde/prereq/mysql.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, internal-dev, small changes

#4209 Release info update (Google Shopping Ads Channel)
  release/index.md
Labels: Editorial

#4207 Make code in user readable format
  guides/v2.1/config-guide/bootstrap/magento-bootstrap.md
Labels: 2.3.x, Editorial

#4206 Formatted CLI commands
  guides/v2.2/cloud/basic-information/starter-develop-deploy-workflow.md
Labels: 2.3.x, Technical

#4208 GraphQL sentence improvement
  guides/v2.3/graphql/index.md
Labels: 2.3.x, Editorial

#3524 Technical guidelines: Clarify what to do when service contracts already exist in a module not suffixed with "Api"
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.x, Major update, internal-dev

#4082 magento/devdocs#: GraphQL functional testing. Add info about fixtures
  guides/v2.3/graphql/functional-testing.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution

#4215 4201: Update link to availability table
  _data/whats-new.yml
  guides/v2.1/install-gde/bk-install-guide.md
  guides/v2.2/install-gde/bk-install-guide.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
Labels: Editorial

#4185 Update cli-upgrade.md
  guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.x, Editorial

#4219 Update Magento version in gateway command description
  guides/v2.2/payments-integrations/payment-gateway/gateway-command.md
Labels: 2.2.x, 2.3.x, Editorial, small changes

#4218 Added missing full-screen options in gallery widget example
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery.md
Labels: 2.2.x, 2.3.x, Technical, small changes

#4212 Update the technical content as per the codebase repository
  guides/v2.1/howdoi/checkout/checkout_payment.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4189 Remove extra spaces in file names
  guides/v2.1/ui_comp_guide/concepts/ui_comp_config_flow_concept.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_config_flow_concept.md
Labels: 2.1.x, 2.2.x, Community, Editorial, small changes

#4179 It happen when we removed the active theme from Magento
  guides/v2.1/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.1.x, 2.2.x, 2.3.x, Community, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4160 Updated code of the test method as per codebase
  guides/v2.1/mtf/mtf_entities/mtf_testcase.md
  guides/v2.2/mtf/mtf_entities/mtf_testcase.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, partners-contribution, small changes

#4123 Correct typo from FASTLY_EDIT_VERSION_ to FASTLY_EDIT_VERSION
  guides/v2.1/cloud/cdn/cloud-vcl-custom-snippets.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, small changes

#4114 Deleting the directory in the file system while on Styles debugging in server-side compilation mode
  guides/v2.1/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4216 Generated backward incompatible changes for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
Labels: 2.3.x, Major update

#4222 Update content based on magento codebase repository
  guides/v2.1/howdoi/checkout/checkout_address.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4197 Add folder structure to Integration testing page.
  guides/v2.1/test/integration/integration_test_execution.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update

#4223 Added comments and bolded label names in PR_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Site improvements

#4026 Adding a code sample of how the menu widget can be initialized and used.
  guides/v2.1/javascript-dev-guide/widgets/images/menu-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_menu.md
  guides/v2.2/javascript-dev-guide/widgets/images/menu-widget-result.png
  guides/v2.3/javascript-dev-guide/widgets/images/menu-widget-result.png
Labels: Major update, Partner: Atwix, partners-contribution

#4148 magento/devdocs#: Expected exceptions
  guides/v2.3/graphql/functional-testing.md
Labels: Major update, Partner: Atwix, Technical, partners-contribution

#4227 Update backward incompatible changes topics (2.0)
  release-notes/backward-incompatible-changes/index.md
  release-notes/backward-incompatible-changes/open-source.md
  release-notes/backward-incompatible-changes/reference.md
Labels: 2.0.x, Editorial

#4220 Remove file-based redirect
  release/index.md
Labels: Site improvements

#4225 MAGECLOUD-3150 Cron changes for Cloud Docker
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, internal-dev

#4205 MAGECLOUD-3409 update web property
  guides/v2.1/cloud/project/project-conf-files_magento-app.md
  guides/v2.2/cloud/project/project-conf-files_magento-app.md
Labels: 2.1.x, 2.2.x, Technical, internal-dev

#4017 Adding additional info regarding the --backend-frontname on Magento installation
  guides/v2.1/install-gde/composer.md
  guides/v2.1/install-gde/install/cli/install-cli-install.md
  guides/v2.2/install-gde/install/cli/install-cli-install.md
  guides/v2.3/install-gde/composer.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4236 Change up PR template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Site improvements

#4238 Remove duplicated "No changes" in BICs reference topics
  _includes/backward-incompatible-changes/commerce/2.0.0-2.0.1.html
  _includes/backward-incompatible-changes/commerce/2.0.1-2.0.2.html
  _includes/backward-incompatible-changes/commerce/2.0.10-2.0.11.html
  _includes/backward-incompatible-changes/commerce/2.0.12-2.0.13.html
  _includes/backward-incompatible-changes/commerce/2.0.13-2.0.14.html
  _includes/backward-incompatible-changes/commerce/2.0.14-2.0.15.html
  _includes/backward-incompatible-changes/commerce/2.0.15-2.0.16.html
  _includes/backward-incompatible-changes/commerce/2.0.17-2.0.18.html
  _includes/backward-incompatible-changes/commerce/2.0.2-2.0.3.html
  _includes/backward-incompatible-changes/commerce/2.0.3-2.0.4.html
  _includes/backward-incompatible-changes/commerce/2.0.4-2.0.5.html
  _includes/backward-incompatible-changes/commerce/2.0.5-2.0.6.html
  _includes/backward-incompatible-changes/commerce/2.0.6-2.0.7.html
  _includes/backward-incompatible-changes/commerce/2.0.7-2.0.8.html
  _includes/backward-incompatible-changes/commerce/2.0.8-2.0.9.html
  _includes/backward-incompatible-changes/commerce/2.0.9-2.0.10.html
  _includes/backward-incompatible-changes/commerce/2.1.0-2.1.1.html
  _includes/backward-incompatible-changes/commerce/2.1.1-2.1.2.html
  _includes/backward-incompatible-changes/commerce/2.1.11-2.1.12.html
  _includes/backward-incompatible-changes/commerce/2.1.12-2.1.13.html
  _includes/backward-incompatible-changes/commerce/2.1.13-2.1.14.html
  _includes/backward-incompatible-changes/commerce/2.1.14-2.1.15.html
  _includes/backward-incompatible-changes/commerce/2.1.15-2.1.16.md
  _includes/backward-incompatible-changes/commerce/2.1.16-2.1.17.md
  _includes/backward-incompatible-changes/commerce/2.1.3-2.1.4.html
  _includes/backward-incompatible-changes/commerce/2.1.4-2.1.5.html
  _includes/backward-incompatible-changes/commerce/2.1.5-2.1.6.html
  _includes/backward-incompatible-changes/commerce/2.1.6-2.1.7.html
  _includes/backward-incompatible-changes/commerce/2.1.8-2.1.9.html
  _includes/backward-incompatible-changes/commerce/2.1.9-2.1.10.html
  _includes/backward-incompatible-changes/commerce/2.2.1-2.2.2.html
  _includes/backward-incompatible-changes/commerce/2.2.4-2.2.5.html
  _includes/backward-incompatible-changes/commerce/2.2.5-2.2.6.html
  _includes/backward-incompatible-changes/open-source/2.0.15-2.0.16.html
  _includes/backward-incompatible-changes/open-source/2.0.16-2.0.17.html
  _includes/backward-incompatible-changes/open-source/2.0.17-2.0.18.html
  _includes/backward-incompatible-changes/open-source/2.1.11-2.1.12.html
  _includes/backward-incompatible-changes/open-source/2.1.12-2.1.13.html
  _includes/backward-incompatible-changes/open-source/2.1.13-2.1.14.html
  _includes/backward-incompatible-changes/open-source/2.1.14-2.1.15.html
  _includes/backward-incompatible-changes/open-source/2.1.9-2.1.10.html
  _includes/backward-incompatible-changes/open-source/2.2.4-2.2.5.html
  _includes/backward-incompatible-changes/open-source/2.2.5-2.2.6.html
Labels: 2.x, Editorial

#4241 Update the code as per the code repository
  guides/v2.1/extension-dev-guide/prepare/lifecycle.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4230 Added details of mode option for magnifier
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical, small changes

#4217 Formatted XML code
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
Labels: 2.3.1, Editorial, small changes

#4229 Update the content based on codebase repository
  guides/v2.1/howdoi/checkout/checkout_customize.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4242 Adding a code sample of how the tabs widget can be initialized and used.
  guides/v2.1/javascript-dev-guide/widgets/images/tabs-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_tabs.md
  guides/v2.2/javascript-dev-guide/widgets/images/tabs-widget-result.png
  guides/v2.3/javascript-dev-guide/widgets/images/tabs-widget-result.png
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4019 magento/devdocs#: ProductInterface updates
  guides/v2.1/javascript-dev-guide/widgets/images/tabs-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_tabs.md
  guides/v2.2/javascript-dev-guide/widgets/images/tabs-widget-result.png
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/javascript-dev-guide/widgets/images/tabs-widget-result.png
Labels: Editorial, Partner: Atwix, partners-contribution

#4235 Adding argument in Gateway Vault Authorization command
  guides/v2.2/payments-integrations/vault/vault-di.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4248 Adding data bind class to fieldset in Vault enabling controls
  guides/v2.1/payments-integrations/vault/enabler.md
Labels: 2.2.x, 2.3.x, Technical, partners-contribution, small changes

#4214 MAGEDOC-3672: Magento extensions
  _config.yml
  _data/main-nav.yml
  _data/toc/extensions.yml
  _data/toc/inventory.yml
  _data/toc/software-update-guide.yml
  _data/whats-new.yml
  _includes/layout/after-site-header.html
  extensions/b2b/index.md
  extensions/google-shopping-ads/images/apikey.png
  extensions/google-shopping-ads/images/config-api-key.png
  extensions/google-shopping-ads/images/config-api-portal.png
  extensions/google-shopping-ads/images/update.png
  extensions/google-shopping-ads/index.md
  extensions/google-shopping-ads/release-notes/index.md
  extensions/index.md
  extensions/install/index.md
  extensions/inventory-management/index.md
  guides/v2.1/comp-mgr/install-extensions.md
  guides/v2.2/b2b/bk-b2b.md
  guides/v2.2/b2b/negotiable-order-workflow.md
  guides/v2.2/cloud/configure/setup-b2b.md
  guides/v2.2/comp-mgr/install-extensions.md
  guides/v2.3/comp-mgr/install-extensions.md
  guides/v2.3/comp-mgr/install-extensions/b2b-installation.md
  guides/v2.3/inventory/index.md
  guides/v2.3/inventory/release-notes.md
Labels: 2.x, New topic, internal-dev

#4221 magento/devdocs#: Compile less into css
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#3812 Initial pass at fixing non-symlink redirects
  guides/v2.1/cloud/release-notes/CloudReleaseNotes101.4.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes101.6.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes101.7.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes101.8.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes101.9.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes2.1.2.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes2.1.3.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes2.1.4.md
  guides/v2.1/cloud/release-notes/CloudReleaseNotes2.1.5.md
  guides/v2.1/comp-mgr/module-man/compman-start.md
  guides/v2.1/contributor-guide/contributing_docs_suggested.md
  guides/v2.1/contributor-guide/maintainers.md
  guides/v2.1/extension-dev-guide/cache/partial-caching/create-cache-type.md
  guides/v2.1/extension-dev-guide/package/package_mktpl.md
  guides/v2.1/extension-dev-guide/prepare/dev-summary.md
  guides/v2.1/extension-dev-guide/prepare/prepare_file-str.md
  guides/v2.1/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.1/extension-dev-guide/versioning/index.md
  guides/v2.1/rest/tutorials/orders/order-add-items.md
  guides/v2.1/rest/tutorials/orders/order-prepare-checkout.md
  guides/v2.1/test/integration/integration_test_execution.md
  guides/v2.2/rest/modules/catalog-pricing.md
  guides/v2.3/extension-dev-guide/versioning/dependencies.md
  guides/v2.3/extension-dev-guide/versioning/index.md
  guides/v2.3/install-gde/composer.md
  guides/v2.3/rest/performing-searches.md
  guides/v2.3/rest/retrieve-filtered-responses.md
Labels: 2.1.x, 2.2.x, 2.3.x, Site improvements

#4257 Fix module name (case)
  extensions/inventory-management/index.md
Labels: 2.3.x, Editorial

#4253 Update technical content based on code base repository
  guides/v2.1/howdoi/checkout/checkout_edit_form.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4231 Using grunt for magento tasks
  guides/v2.2/frontend-dev-guide/tools/using_grunt.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#4246 MAGEDOC-3691: Release page update
  _config.yml
  _data/compatibility.yml
  _data/toc/release.yml
  _data/whats-new.yml
  _includes/compatibility.html
  guides/v2.1/install-gde/bk-install-guide.md
  guides/v2.2/install-gde/bk-install-guide.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  release/index.md
  release/policy/index.md
Labels: Editorial

#4249 Adding folder structure to 2.3 topic
  guides/v2.3/test/integration/integration_test_execution.md
Labels: 2.3.x

#4263 Add missing parameter into document as per the codebase repository
  guides/v2.1/payments-integrations/payment-gateway/request-builder.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4264 Small changes
  extensions/inventory-management/index.md
  guides/v2.1/extension-dev-guide/prepare/lifecycle.md
  guides/v2.1/howdoi/checkout/checkout_customize.md
  guides/v2.1/howdoi/checkout/checkout_edit_form.md
  guides/v2.1/javascript-dev-guide/javascript/js-resources.md
  guides/v2.1/javascript-dev-guide/widgets/widget_gallery_mg.md
  guides/v2.1/payments-integrations/payment-gateway/request-builder.md
  guides/v2.1/payments-integrations/vault/enabler.md
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.2/frontend-dev-guide/tools/using_grunt.md
  guides/v2.3/graphql/reference/products.md
Labels: 2.1.x, 2.2.x, 2.3.x

#4265 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#4152 magento/graphql-ce# New topic - Check the Magento version
  _data/toc/php-developer-guide.yml
  guides/v2.1/extension-dev-guide/images/version.png
  guides/v2.1/extension-dev-guide/versioning/check-version.md
  guides/v2.2/extension-dev-guide/images/version.png
  guides/v2.2/extension-dev-guide/versioning/check-version.md
  guides/v2.3/extension-dev-guide/images/version.png
  guides/v2.3/extension-dev-guide/versioning/check-version.md
Labels: 2.x, New topic, Partner: Atwix, partners-contribution

#4268 Formatted JSON code
  guides/v2.1/cloud/trouble/troubleshoot-deployment.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, small changes

#4213 Compile LESS using Grunt: add missing links, minor refactoring
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.2.x, Editorial, Partner: Atwix, partners-contribution, small changes

#4168 While working on the client-side compilation mode files are compiled every page load and provide slow response times
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4180 Layout XML is merging order.
  guides/v2.1/frontend-dev-guide/layouts/layout-overview.md
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4267 Replace symlinks with real files in 2.0
  pattern-library/bk-pattern.md
  pattern-library/containers/slideouts-modals-overlays/slideouts-modals-overalys.md
  pattern-library/containers/staticContentContainer/contentContainer.md
  pattern-library/containers/tabs/tabs.md
  pattern-library/controls/button-bar/button-bar.md
  pattern-library/controls/buttons/buttons.md
  pattern-library/displaying-data/datatable/datatable.md
  pattern-library/displaying-data/tile/tile.md
  pattern-library/displaying-data/tree/tree.md
  pattern-library/feedbackToUser/progressIndicator/progressIndicator.md
  pattern-library/filters/data-table-filters/filtering.md
  pattern-library/general/accessibilityguideline/accessibilityGuideline.md
  pattern-library/getting-user-input/date_time_selector/date_time_selector.md
  pattern-library/getting-user-input/form_elements/form_elements.md
  pattern-library/getting-user-input/image_uploader/image_uploader.md
  pattern-library/getting-user-input/row_pattern/row_pattern.md
  pattern-library/getting-user-input/select_from_list/select_from_list.md
  pattern-library/getting-user-input/use_default_config/use_default_config.md
  pattern-library/navigation/links/links.md
  pattern-library/navigation/wizard/wizard.md
  pattern-library/templates/address-form/address-form.md
  pattern-library/templates/sign-in-form/sign-in-form.md
Labels: 2.0.x, Editorial

#4151 logo supported image files and use of SVG logo
  guides/v2.1/frontend-dev-guide/themes/theme-apply.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4272 MAGECLOUD-2172 release note for redis cache fix
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: internal-dev

#4135 Custom Magento icon css and use in our theme
  guides/v2.1/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4273 Replace 2.0 symlinks
  guides/v2.1/coding-standards/technical-vision/index.md
  guides/v2.2/config-guide/cache.md
  guides/v2.2/migration/migration-migrate-follow-up.md
Labels: 2.x, Editorial

#4269 Adding a code sample of how the modal widget can be initialized
  common/images/widget/modal-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.1.x, 2.3.x, 2.x, Major update, Partner: Atwix, partners-contribution

#4286 Spelling Correction
  guides/v2.3/architecture/tech-stack.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4287 magento/devdocs#: Add a custom breakpoint. Add information about @media-target
  guides/v2.1/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4275 Add missing parameter into technical document
  guides/v2.2/payments-integrations/payment-gateway/request-builder.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4270 MAGECLOUD-2890 add varnish container and TLS container
  guides/v2.1/cloud/docker/docker-config.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/docker/docker-quick-reference.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: In progress, internal-dev

#4250 Adding parameters to Brainetree Vault request builder
  guides/v2.1/payments-integrations/vault/admin-integration.md
  guides/v2.2/payments-integrations/vault/admin-integration.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4281 Update Customer address input attribute
  guides/v2.3/graphql/reference/customer.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#4293 Removed MC-5465 from 2-3-1 release notes
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: 2.3.1, 2.3.x, internal-dev

#4291 GitHub Issue #3298: Required verbiage
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_relationships.md
  guides/v2.1/extension-dev-guide/intro/developers_roadmap.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#4288 Add missing argument parameter as per the codebase repository
  guides/v2.1/payments-integrations/base-integration/payment-action.md
  guides/v2.2/payments-integrations/base-integration/payment-action.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4277 Add the last modified date to the page info section
  _includes/layout/footer-scripts.html
  _includes/layout/page-info.html
  _plugins/last-modified-at.rb
  common/css/devdocs.css
  common/js/last-modified-at.js
  i/icons/time.svg
  scss/devdocs.scss
Labels: Site improvements

#4156 Added a section about breaking changes that require approval
  guides/v2.1/contributor-guide/contributing_dod.md
Labels: 2.1.x, 2.2.x, 2.3.x, Technical

#4262 Fixes some PHP highlights that I broke yesterday.
  guides/v2.1/coding-standards/technical-guidelines.md
  guides/v2.1/config-guide/bootstrap/magento-bootstrap.md
  guides/v2.2/coding-standards/technical-guidelines.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial

#4292 Small changes
  _includes/layout/footer-scripts.html
  common/js/survey.js
  extensions/google-shopping-ads/images/apikey.png
  extensions/google-shopping-ads/images/config-api-key.png
  extensions/google-shopping-ads/images/config-api-portal.png
  extensions/google-shopping-ads/images/update.png
  guides/v2.1/architecture/archi_perspectives/components/modules/mod_relationships.md
  guides/v2.1/cloud/trouble/troubleshoot-deployment.md
  guides/v2.1/extension-dev-guide/intro/developers_roadmap.md
  guides/v2.1/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.1/frontend-dev-guide/layouts/layout-overview.md
  guides/v2.1/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
  guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.md
  guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
  guides/v2.2/frontend-dev-guide/layouts/layout-overview.md
  guides/v2.3/architecture/tech-stack.md
Labels: 2.1.x, 2.2.x, 2.3.x

#4232 Generated backward incompatible changes for 2.3
  _includes/backward-incompatible-changes/commerce/2.3.1-2.3-develop.html
Labels: 2.3.2, Technical

#4289 Updating the configure the magento application topic
  guides/v2.1/install-gde/install/post-install-config.md
  guides/v2.2/install-gde/install/post-install-config.md
  guides/v2.3/install-gde/install/post-install-config.md
Labels: 2.1.x, 2.2.x, 2.3.x, internal-dev

#4306 Define the Vendor directory name instead of magento
  guides/v2.1/frontend-dev-guide/conventions.md
  guides/v2.1/javascript-dev-guide/conventions_js.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution, small changes

#4309 UI Library Mixin Update
  guides/v2.1/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4305 Update Advance Reporting XML configuration
  guides/v2.2/advanced-reporting/data-collection.md
Labels: 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4298 Fix broken link for ModSecurity rules
  guides/v2.1/cloud/cdn/fastly-waf-service.md
Labels: Editorial, internal-dev, small changes

#4297 Update link as current Devdoc Magento version
  guides/v2.1/javascript-dev-guide/javascript/js_init.md
Labels: 2.1.x, 2.2.x, 2.3.x, Editorial, Partner: Krish TechnoLabs, partners-contribution

#4290 MAGECLOUD-3054: Implement Database Locks using Zookeeper and flock for Reliable HA Support
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.2.x, 2.3.x, Editorial, internal-dev

#4256 Implement Docfile
  .gitignore
  Docfile.yml
  Rakefile
  rakelib/lib/doc-config.rb
  rakelib/multirepo.rake
Labels: Site improvements

#4312 MAGECLOUD-2899: Redis Slave Nodes Have no Health Checks / Are not Stable
  guides/v2.1/cloud/env/variables-deploy.md
  guides/v2.2/cloud/env/variables-deploy.md
Labels: internal-dev

#4310 Remove uneccessary parameter from technical document as per the codeb…
  guides/v2.3/graphql/reference/configurable-product.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4164 Added missing fields related to customer information
  guides/v2.1/architecture/archi_perspectives/framework.md
  guides/v2.1/architecture/gdpr/magento-2x.md
Labels: 2.3.x, Editorial

#4311 Add Website attributes parameter as per the codebase repository
  guides/v2.3/graphql/reference/products.md
  guides/v2.3/graphql/reference/store-config.md
Labels: Partner: Krish TechnoLabs, partners-contribution

#4314 Weekly digest
  _data/whats-new.yml
Labels: 2.x, Editorial

#4078 Replace deprecated attribute name
  guides/v2.3/graphql/reference/url-resolver.md
Labels: 2.3.2, Community, Partner: Krish TechnoLabs, Technical, partners-contribution

#4147 Removed unused and wrong type
  guides/v2.3/graphql/reference/configurable-product.md
Labels: 2.3.2, In progress, Partner: Krish TechnoLabs, Technical, partners-contribution

#4066 magento/devdocs#: Store endpoint
  guides/v2.3/graphql/reference/store-config.md
Labels: 2.3.1, Partner: Atwix, Technical, Waiting for response, partners-contribution

#4324 Add required parameter in shipping carrier validation rule
  guides/v2.1/howdoi/checkout/checkout_carrier.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution, small changes

#4304 Adding a code sample of how the accordion widget can be used
  common/images/widget/accordion-widget-result.png
  guides/v2.1/javascript-dev-guide/widgets/widget_accordion.md
Labels: 2.1.x, 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#4334 magento/devdocs#: Add a sequence for overrides in responsive design
  guides/v2.1/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Atwix, Technical, partners-contribution

#4332 Add External source css description
  guides/v2.1/frontend-dev-guide/css-topics/css-themes.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4321 MAGECLOUD-2664 connect to database
  _data/main-nav.yml
  _data/toc/cloud-guide.yml
  guides/v2.1/cloud/docker/docker-database.md
  guides/v2.1/cloud/docker/docker-development.md
  guides/v2.1/cloud/release-notes/cloud-tools.md
  guides/v2.2/cloud/docker/docker-database.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/docker/docker-database.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, Major update, internal-dev

#4132 To wrap div or block using container
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4299 Remove excess whitespace from source code
  _includes/layout/main-nav-item.html
  _includes/layout/nav-item.html
  _includes/layout/navigation.html
  _includes/layout/sidebar.html
Labels: Site improvements

#4320 Add CategoryTree object paramter table as per the codebase repository
  guides/v2.3/graphql/reference/categories.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4340 Add Inventory Management GraphQL attributes
  guides/v2.3/graphql/reference/products.md
Labels: 2.3.2, Community, Technical, internal-dev

#4283 Added technical content regarding Customizing style in theme keep in mind both compilation mode
  guides/v2.1/frontend-dev-guide/css-topics/css-overview.md
Labels: 2.1.x, 2.2.x, 2.3.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#4237 MAGECLOUD-3205: Provide ElasticsSuite auto-configuration in ECE-Tools
  guides/v2.2/cloud/env/variables-deploy.md
Labels: internal-dev

#4303 Generated backward incompatible changes for 2.3
  _includes/backward-incompatible-changes/open-source/2.3.1-2.3-develop.html
Labels: 2.3.2, Technical

#4295 Added note about using ">=2.3.1 <2.3.2" syntax for composer
  guides/v2.3/cloud/project/project-upgrade.md
Labels: 2.3.x, Editorial

#4339 Add ProductImage object as per the code base repository
  guides/v2.3/graphql/reference/products.md
Labels: Partner: Krish TechnoLabs, partners-contribution
