Repository magento/devdocs, pull requests merged in 2019-11, with the labels that each got.

#5907 Filtering.md
  _data/toc/marketplace-api.yml
  marketplace/eqp/v1/filtering.md
Labels: 2.3.x, New topic, Progress: approved

#5908 Packages.md
  marketplace/eqp/v1/packages.md
Labels: 2.3.x, Technical, internal-dev

#5904 Fixed theme inheritance terminology
  guides/v2.2/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5906 Fixed improper rendering of info callout
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5872 Technical guidelines: added guidelines about IDs
  guides/v2.2/coding-standards/technical-guidelines.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
Labels: 2.3.x, Major update, Progress: review, internal-dev

#5909 Users.md
  marketplace/eqp/v1/users.md
Labels: Progress: review

#5912 Added missing space
  guides/v2.2/install-gde/install/cli/dev_options.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, partners-contribution, small changes

#5910 Increment RabbitMQ version support for 2.3.4
  guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.4, Progress: approved, Technical

#5899 GraphQL: Add customerCart query
  _data/toc/graphql.yml
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/queries/customer-cart.md
Labels: 2.3.4, New topic, Progress: approved, internal-dev

#5905 Added layout override examples
  guides/v2.2/frontend-dev-guide/layouts/layout-override.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5914 Magento 2.2.8 Open Source Release Notes broken link fix
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
Labels: 2.2.8, Progress: approved, small changes

#5913 Small changes
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/cdn/cloud-fastly.md
  guides/v2.2/cloud/cdn/fastly-waf-service.md
  guides/v2.2/comp-mgr/cli/cli-upgrade.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/config-guide/prod/config-reference-gitignore.md
  guides/v2.2/extension-dev-guide/events-and-observers.md
  guides/v2.2/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.2/extension-dev-guide/view-models.md
  guides/v2.2/frontend-dev-guide/layouts/layout-types.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/themes/debug-theme.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-inherit.md
  guides/v2.2/install-gde/install/cli/dev_options.md
  guides/v2.2/marketplace/eqp/packages.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
  guides/v2.3/config-guide/prod/config-reference-gitignore.md
  guides/v2.3/extension-dev-guide/attributes.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
  guides/v2.3/frontend-dev-guide/layouts/layout-types.md
  guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/graphql/mutations/set-payment-place-order.md
Labels: 2.2.x, 2.3.x, Progress: changes requested

#5915 Update users.md
  marketplace/eqp/v1/filtering.md
  marketplace/eqp/v1/users.md
Labels: Progress: approved

#5882 magento/devdocs#: Add setGuestEmailOnCart mutation API errors
  guides/v2.3/graphql/mutations/set-guest-email.md
Labels: 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution

#5918 EQP updates
  _data/main-nav.yml
  _data/toc/marketplace-api.yml
  _data/whats-new.yml
  guides/v2.2/marketplace/eqp/auth.md
  guides/v2.2/marketplace/eqp/files.md
  guides/v2.3/marketplace/eqp/api.md
  guides/v2.3/marketplace/eqp/auth.md
  guides/v2.3/marketplace/eqp/files.md
  guides/v2.3/marketplace/eqp/packages.md
  guides/v2.3/marketplace/eqp/reports.md
  guides/v2.3/marketplace/eqp/users.md
  marketplace/eqp/v1/api.md
  marketplace/eqp/v1/auth.md
  marketplace/eqp/v1/files.md
  marketplace/eqp/v1/filtering.md
  marketplace/eqp/v1/packages.md
  marketplace/eqp/v1/reports.md
  marketplace/eqp/v1/users.md
Labels: New topic, Progress: changes requested, internal-dev

#5900 GraphQL: Add mergeCarts mutation
  _data/toc/graphql.yml
  _includes/graphql/cart-object.md
  guides/v2.3/graphql/mutations/merge-carts.md
  guides/v2.3/graphql/queries/customer-cart.md
Labels: 2.3.4, New topic, Progress: approved, internal-dev

#5920 Fixed cms query input
  guides/v2.3/graphql/queries/cms-page.md
Labels: 2.3.x, Community Insider: Cedcommerce, Progress: review, Technical, community-insider-contribution

#5921 Sync develop with master
  _data/toc/configuration-guide.yml
  _data/toc/javascript-developer-guide.yml
  _data/toc/mftf.yml
  _includes/release-notes/engcomm-2-3-3-issues.md
  common/images/archi_hash_upgrade_algorithm.png
  common/images/archi_hash_upgrade_strategy.png
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/cdn/cloud-fastly.md
  guides/v2.2/cloud/cdn/fastly-waf-service.md
  guides/v2.2/cloud/env/environments-start.md
  guides/v2.2/coding-standards/technical-guidelines.md
  guides/v2.2/comp-mgr/cli/cli-upgrade.md
  guides/v2.2/config-guide/cli/config-cli-subcommands-mode.md
  guides/v2.2/config-guide/prod/config-reference-gitignore.md
  guides/v2.2/config-guide/secy/hashing.md
  guides/v2.2/config-guide/secy/secy.md
  guides/v2.2/contributor-guide/contributing_dod.md
  guides/v2.2/extension-dev-guide/events-and-observers.md
  guides/v2.2/extension-dev-guide/versioning/codebase-changes.md
  guides/v2.2/extension-dev-guide/view-models.md
  guides/v2.2/frontend-dev-guide/layouts/layout-override.md
  guides/v2.2/frontend-dev-guide/layouts/layout-types.md
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.2/frontend-dev-guide/themes/debug-theme.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/frontend-dev-guide/themes/theme-inherit.md
  guides/v2.2/frontend-dev-guide/translations/theme_dictionary.md
  guides/v2.2/howdoi/checkout/checkout_order.md
  guides/v2.2/install-gde/install/cli/dev_options.md
  guides/v2.2/javascript-dev-guide/javascript/requirejs.md
  guides/v2.2/marketplace/eqp/packages.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.2/ui_comp_guide/concepts/magento-bindings.md
  guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.md
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
  guides/v2.3/config-guide/prod/config-reference-gitignore.md
  guides/v2.3/config-guide/secy/hashing.md
  guides/v2.3/extension-dev-guide/attributes.md
  guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  guides/v2.3/extension-dev-guide/declarative-schema/index.md
  guides/v2.3/frontend-dev-guide/layouts/layout-types.md
  guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/graphql/develop/create-graphqls-file.md
  guides/v2.3/graphql/mutations/set-guest-email.md
  guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: Progress: approved, internal-dev

#5897 Added translation methods in UI component templates
  guides/v2.2/frontend-dev-guide/translations/translate_theory.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: review, Technical, partners-contribution, small changes

#5871 Update adding-attributes.md
  guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: 2.2.x, 2.3.x, Progress: review, Technical

#5903 Fixed symbolic link creation command
  .github/CONTRIBUTING.md
Labels: Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#5881 magento/devdocs#: Add createEmptyCart mutation API errors
  guides/v2.3/graphql/mutations/create-empty-cart.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5923 Replace jquery/ui usages with individual jQuery UI components
  guides/v2.3/javascript-dev-guide/javascript/custom_js.md
  guides/v2.3/javascript-dev-guide/javascript/js_practice.md
Labels: 2.3.x, Progress: review, Technical, internal-dev

#5922 Updated what's new
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: review, internal-dev

#5877 Added guidance for fixing session start
  guides/v2.2/cloud/docker/docker-config.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#5901 magento/devdocs#: Fix link on the “Magento payment provider gateway” page
  guides/v2.2/payments-integrations/payment-gateway/payment-gateway-intro.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, partners-contribution

#5930 Add attributes to ProductFilterInput
  guides/v2.3/graphql/queries/products.md
Labels: 2.3.x, Technical, internal-dev

#5831 Update the UI Date component documentation
  common/images/ui_comps/ui-date-expanded-result.png
  common/images/ui_comps/ui-date-result.png
  guides/v2.2/ui_comp_guide/components/ui-date.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, partners-contribution

#5935 Add attribution for RequireJS topic
  guides/v2.2/javascript-dev-guide/javascript/requirejs.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved, small changes

#5936 GraphQL: add to list of deprecated filter attributes
  guides/v2.3/graphql/queries/products.md
Labels: 2.3.4, Progress: approved, Technical, internal-dev

#5931 GraphQL: Change cart_id to id in customerCart query
  guides/v2.3/graphql/queries/customer-cart.md
Labels: 2.3.4, Progress: approved, Technical, internal-dev

#5932 Add new custom layout update guide
  guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, 2.3.x, Major update, Progress: approved, internal-dev

#5938 Changed subheadings hierarchy level
  guides/v2.2/javascript-dev-guide/javascript/requirejs.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5937 Update the documentation for ActionDelete UI component documentation
  common/images/ui_comps/action-delete-result.png
  guides/v2.2/ui_comp_guide/components/ui-actiondelete.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5940 Update ActionsColumns UI component documentation
  common/images/ui_comps/actions-column-result.png
  guides/v2.2/ui_comp_guide/components/ui-actionscolumn.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5944 Update ColumnsControls UI component documentation
  common/images/ui_comps/columns-controls-result.png
  guides/v2.2/ui_comp_guide/components/ui-columnscontrols.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5865 Added instructions for Fastly Edge Modules: Reroute to other CMS backend
  _data/toc/cloud-guide.yml
  guides/v2.2/cloud/cdn/fastly-vcl-wordpress.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#5947 Issue #1049 [graphql documentation] addBundleProductsToCart mutation
  _data/toc/graphql.yml
  guides/v2.3/graphql/mutations/add-bundle-products.md
Labels: 2.3.4, Community, New topic, Partner: Atwix, Progress: review, partners-contribution

#5867 Updated manage message queues instructions
  guides/v2.2/config-guide/mq/manage-message-queues.md
  guides/v2.2/install-gde/prereq/install-rabbitmq.md
  guides/v2.2/rest/bulk-endpoints.md
  guides/v2.2/rest/tutorials/configurable-product/config-product-intro.md
  guides/v2.3/config-guide/mq/manage-message-queues.md
  guides/v2.3/install-gde/prereq/install-rabbitmq.md
  guides/v2.3/rest/bulk-endpoints.md
Labels: 2.2.x, 2.3.x, Partner: Trezo, Progress: review, Technical, partners-contribution

#5948 Fixed grammar
  guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5941 Update Bookmarks UI component documentation
  common/images/ui_comps/bookmarks-result.png
  guides/v2.2/ui_comp_guide/components/ui-bookmarks.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5946 Update Search UI component documentation
  common/images/ui_comps/ui-search-result.png
  guides/v2.2/ui_comp_guide/components/ui-search.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5952 GraphQL: Deprecate wishlist query
  _includes/graphql/customer-output.md
  guides/v2.3/graphql/queries/customer.md
  guides/v2.3/graphql/queries/wishlist.md
Labels: 2.3.4, Community, Major update, Progress: approved, internal-dev

#5949 GraphQL: Deprecate ShippingCartAddress.cart_items in favor of cart_items_v2
  guides/v2.3/graphql/mutations/set-shipping-address.md
  guides/v2.3/graphql/queries/cart.md
Labels: 2.3.4, Community, Progress: approved, Technical, internal-dev

#5955 GraphQL: Deprecate use_for_shipping attribute
  guides/v2.3/graphql/mutations/set-billing-address.md
  guides/v2.3/graphql/mutations/set-shipping-address.md
  guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
Labels: 2.3.4, Community, Progress: approved, Technical, internal-dev

#5942 magento/devdocs#: Add addSimpleProductsToCart mutation API errors
  guides/v2.3/graphql/mutations/add-simple-products.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#5939 magento/devdocs#: Add addConfigurableProductsToCart mutation API errors
  guides/v2.3/graphql/mutations/add-configurable-products.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#5886 magento/devdocs#: Add revokeCustomerToken mutation API errors
  guides/v2.3/graphql/mutations/revoke-customer-token.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#5902 Reorganized templates topic
  _data/toc/frontend-developer-guide.yml
  guides/v2.2/frontend-dev-guide/templates/template-email.md
  guides/v2.2/frontend-dev-guide/templates/template-sample.md
  guides/v2.3/frontend-dev-guide/templates/template-sample.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Site improvements, partners-contribution

#5856 Adding alternative magic method to retrieve arguments
  guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Progress: review, Technical, partners-contribution

#5953 Enhance Commerce release info
  _data/compatibility.yml
  release/index.md
  release/policy/index.md
Labels: Progress: approved, internal-dev

#5943 magento/devdocs#: Add addVirtualProductsToCart mutation API errors
  guides/v2.3/graphql/mutations/add-virtual-products.md
Labels: 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution, small changes

#5934 Added new section for 2.3 parity
  guides/v2.2/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.2.x, Major update, Progress: approved

#5957 Markdown linting: Enable rule MD032 (lists should be surrounded by blank lines)
  _checks/styles/style-rules-prod
  _includes/config/setup-cron_2.2_about.md
  _includes/config/setup-cron_2.2_how-to.md
  _includes/config/setup-cron_2.3_how-to.md
  guides/v2.2/cloud/cdn/trouble-fastly.md
  guides/v2.2/cloud/composer-packages/ece-patches.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.1.md
  guides/v2.2/cloud/release-notes/CloudReleaseNotes2.2.md
  guides/v2.2/mrg/ce/Signifyd.md
  guides/v2.2/pattern-library/general/accessibilityguideline/accessibilityGuideline.md
  guides/v2.2/release-notes/ReleaseNotes2.2.0CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.0EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.1CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.1EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.2EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.3CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.3EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.4EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.5CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.5EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.6EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.7EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8CE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.8EE.md
  guides/v2.2/release-notes/ReleaseNotes2.2.9CE.md
  guides/v2.2/release-notes/release-notes-2-2-10-commerce.md
  guides/v2.2/release-notes/release-notes-2-2-10-open-source.md
  guides/v2.3/graphql/develop/identity-class.md
  guides/v2.3/graphql/functional-testing.md
  guides/v2.3/graphql/payment-methods/authorize-net.md
  guides/v2.3/graphql/product/product-interface-implementations.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: Editorial, Progress: approved

#5958 Fix endpoint domain names
  marketplace/eqp/v1/api.md
  marketplace/eqp/v1/auth.md
  marketplace/eqp/v1/files.md
  marketplace/eqp/v1/filtering.md
  marketplace/eqp/v1/packages.md
  marketplace/eqp/v1/users.md
Labels: Editorial, internal-dev

#5959 Small changes
  guides/v2.2/frontend-dev-guide/translations/translate_theory.md
  guides/v2.2/javascript-dev-guide/javascript/requirejs.md
  guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.2/payments-integrations/payment-gateway/payment-gateway-intro.md
  guides/v2.3/graphql/mutations/add-configurable-products.md
  guides/v2.3/graphql/mutations/add-simple-products.md
  guides/v2.3/graphql/mutations/revoke-customer-token.md
  guides/v2.3/graphql/queries/products.md
  marketplace/eqp/v1/api.md
  marketplace/eqp/v1/auth.md
  marketplace/eqp/v1/files.md
  marketplace/eqp/v1/filtering.md
  marketplace/eqp/v1/packages.md
  marketplace/eqp/v1/users.md
Labels: Progress: approved

#5960 Update MFTF Action Groups data file.
  _data/actiongroups.yml
Labels: Progress: approved, Site improvements, internal-dev

#5968 Fix the mdl version to 0.7.0 in the GH workflow
  .github/workflows/main.yml
Labels: Progress: approved

#5961 magento/devdocs#: Add createCustomer mutation API errors
  guides/v2.3/graphql/mutations/create-customer.md
Labels: 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution

#5966 Update migration-troubleshooting.md
  guides/v2.2/migration/migration-troubleshooting.md
Labels: Progress: approved

#5969 Amazon 301
  _data/compatibility.yml
  extensions/amazon-sales/release-notes/index.md
  release/index.md
Labels: 3.0.1-asc, Major update, Progress: approved

#5964 Add information about Magento consumers
  guides/v2.2/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/extension-dev-guide/message-queues/config-mq.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Comwrap, Progress: review, partners-contribution

#5962 magento/devdocs#: Add createCustomerAddress mutation API errors
  guides/v2.3/graphql/mutations/create-customer-address.md
Labels: 2.3.x, Partner: Atwix, Progress: changes requested, Technical, partners-contribution

#5977 MAGECLOUD-4655 Update config file extension for Blackfire
  guides/v2.2/cloud/project/project-integrate-blackfire.md
Labels: 2.x, Progress: approved, Technical, small changes

#5975 [site] Add mdl to the bundle, update rake tasks
  Gemfile
  Gemfile.lock
  bin/mdl
  rakelib/build.rake
  rakelib/check.rake
  rakelib/test.rake
Labels: Progress: approved, Site improvements

#5978 Fix small grammatical issue
  guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5981 Sync develop with master
  Gemfile
  Gemfile.lock
  _data/compatibility.yml
  bin/mdl
  extensions/amazon-sales/release-notes/index.md
  guides/v2.2/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  guides/v2.3/graphql/mutations/create-customer-address.md
  rakelib/build.rake
  rakelib/check.rake
  rakelib/test.rake
  release/index.md
Labels: Progress: approved

#5950 Add info about new resolver interfaces
  guides/v2.3/graphql/develop/resolvers.md
Labels: 2.3.4, Major update, Progress: changes requested, internal-dev

#5979 Fixed incorrect link syntax
  guides/v2.2/howdoi/checkout/checkout_customize.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#5976 Fixed incorrect module dependency examples
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Technical, partners-contribution

#5974 Add documentation about caching user defined EAV attributes in 2.3.4
  guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
  guides/v2.3/config-guide/prod/config-reference-most.md
  guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.4, Progress: review, Technical, internal-dev

#5985 [site] Fix bug in rake build:stage
  rakelib/build.rake
Labels: Progress: approved, Site improvements

#5984 Product availability updates
  release/index.md
Labels: Progress: approved, internal-dev

#5989 Adding the widget available options
  guides/v2.2/ext-best-practices/tutorials/custom-widget.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5991 magento/devdocs#: Add updateCustomerAddress mutation API errors
  guides/v2.3/graphql/mutations/update-customer-address.md
Labels: 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution, small changes

#5988 magento/devdocs#: Add deleteCustomerAddress mutation API errors
  guides/v2.3/graphql/mutations/delete-customer-address.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#5986 Improving the Range UiComponent
  common/images/ui_comps/date-range-result.png
  common/images/ui_comps/text-range-result.png
  guides/v2.2/ui_comp_guide/components/ui-range.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5993 Cloud docker updates
  _data/toc/cloud-guide.yml
  common/images/cloud/docker-topology.png
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-containers.md
  guides/v2.2/cloud/docker/docker-development.md
  guides/v2.2/cloud/docker/docker-extend.md
  guides/v2.2/cloud/docker/docker-mode-developer.md
  guides/v2.2/cloud/docker/docker-mode-production.md
  guides/v2.2/cloud/docker/docker-php.md
  guides/v2.2/cloud/docker/docker-services.md
  guides/v2.3/cloud/docker/docker-services.md
Labels: Progress: review, Technical

#5983 Add site switcher to the header
  Gemfile.lock
  _includes/layout/site-nav.html
Labels: Progress: approved, Site improvements

#5995 Removed workflows file
  .github/workflows/main.yml
Labels: Progress: approved, internal-dev

#5987 Improving the Checkbox UiComponent documentation
  common/images/ui_comps/checkbox-component-result.png
  guides/v2.2/ui_comp_guide/components/ui-checkbox.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#5994 Add contributor metadata info
  guides/v2.2/contributor-guide/templates/basic_template.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: changes requested, small changes

#5992 magento/devdocs#: Extends information about creating a dynamic row system config.
  common/images/ext-best-practices/dynamic-rows-config-result.png
  guides/v2.2/ext-best-practices/tutorials/dynamic-row-system-config.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#5997 Cloud 2002.0.22
  _data/toc/cloud-guide.yml
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
Labels: 2.x, Progress: changes requested, internal-dev

#6003 Update lifecycle.md
  guides/v2.3/extension-dev-guide/prepare/lifecycle.md
Labels: Partner: Webjump, Progress: approved, partners-contribution

#6002 Update create-cache-type.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/create-cache-type.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Technical, partners-contribution

#6000 Fix identation of XML code
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Webjump, partners-contribution

#5990 Update theme-create.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: changes requested, small changes

#6006 Typo fix
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
Labels: 2.2.x, Editorial, Progress: approved

#6001 Adding new example
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
Labels: 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution

#6007 Small changes
  guides/v2.2/cloud/project/project-integrate-blackfire.md
  guides/v2.2/contributor-guide/templates/basic_template.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/create-cache-type.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/howdoi/checkout/checkout_customize.md
  guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.3/extension-dev-guide/prepare/lifecycle.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/graphql/mutations/delete-customer-address.md
  guides/v2.3/graphql/mutations/update-customer-address.md
Labels: Progress: approved

#6008 [site] Add 'rake index' and 'rake multirepo:reinit'
  Rakefile
  rakelib/multirepo.rake
  scripts/docs-from-code.sh
Labels: Progress: approved, Site improvements

#6009 Remove typos in command
  guides/v2.2/cloud/project/user-admin.md
Labels: 2.2.x, 2.3.x, Editorial, Progress: approved

#5998 Updated reCAPTCHA with PHP config note
  guides/v2.3/security/google-recaptcha.md
Labels: 2.3.x, Progress: approved, Technical

#6004 Added note for ece-tools patch process fix
  guides/v2.2/cloud/release-notes/cloud-tools.md
Labels: 2.x, Progress: review, Technical, internal-dev

#6019 Sync develop with master
  .github/workflows/main.yml
  Gemfile.lock
  Rakefile
  _data/toc/cloud-guide.yml
  _includes/layout/site-nav.html
  common/images/ext-best-practices/dynamic-rows-config-result.png
  common/images/ui_comps/checkbox-component-result.png
  common/images/ui_comps/date-range-result.png
  common/images/ui_comps/text-range-result.png
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_depend.md
  guides/v2.2/cloud/project/project-integrate-blackfire.md
  guides/v2.2/cloud/project/user-admin.md
  guides/v2.2/cloud/release-notes/cloud-tools.md
  guides/v2.2/contributor-guide/templates/basic_template.md
  guides/v2.2/ext-best-practices/tutorials/custom-widget.md
  guides/v2.2/ext-best-practices/tutorials/dynamic-row-system-config.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/create-cache-type.md
  guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  guides/v2.2/frontend-dev-guide/themes/theme-create.md
  guides/v2.2/howdoi/checkout/checkout_customize.md
  guides/v2.2/javascript-dev-guide/widgets/widget_collapsible.md
  guides/v2.2/ui_comp_guide/components/ui-checkbox.md
  guides/v2.2/ui_comp_guide/components/ui-range.md
  guides/v2.3/cloud/release-notes/cloud-tools.md
  guides/v2.3/extension-dev-guide/prepare/lifecycle.md
  guides/v2.3/extension-dev-guide/searching-with-repositories.md
  guides/v2.3/frontend-dev-guide/themes/theme-create.md
  guides/v2.3/graphql/mutations/delete-customer-address.md
  guides/v2.3/graphql/mutations/update-customer-address.md
  guides/v2.3/security/google-recaptcha.md
  rakelib/build.rake
  rakelib/multirepo.rake
  release/index.md
  scripts/docs-from-code.sh
Labels: Progress: approved, internal-dev

#5917 Feature/elasticsearch stopwords
  guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
Labels: 2.3.x, Major update, Partner: Webjump, Progress: changes requested, partners-contribution

#6018 Fixing the LESS snippet syntax
  guides/v2.2/javascript-dev-guide/javascript/js-resources.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Imagination Media, Progress: approved, partners-contribution, small changes

#6015 Fixed incorrect syntax for custom KO checked binding
  guides/v2.2/ui_comp_guide/concepts/magento-bindings.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#6016 Added missing example for i18n Magento binding syntax
  guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#6014 Added JS script name resolution examples
  guides/v2.2/javascript-dev-guide/javascript/js_debug.md
Labels: 2.2.x, 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#5965 Updated repo path Actiongroups data file
  _data/actiongroups.yml
  _data/codebase/mftf/action-groups.yml
Labels: Progress: changes requested, Site improvements

#6021 Option added for secure DB connection
  guides/v2.3/install-gde/install/cli/install-cli-install.md
Labels: 2.3.4, Community, Progress: approved, Technical

#6005 Fix merge example for RESOURCE_CONFIGURATION variable
  guides/v2.2/cloud/env/variables-deploy.md
Labels: Progress: approved

#6027 Release Notes for Google 3.0.2
  _data/compatibility.yml
  extensions/google-shopping-ads/release-notes/index.md
  release/index.md
Labels: 3.0.2 Google Shopping ads, Major update, Progress: approved

#6013 Masonry component doc added
  _data/toc/ui-components-guide.yml
  common/images/ui_comps/masonry-grid-result.png
  guides/v2.3/ui_comp_guide/components/ui-masonry.md
Labels: 2.3.4, Community, New topic, Progress: changes requested

#5929 Using the /search endpoint
  _data/toc/rest-api.yml
  guides/v2.2/rest/search-endpoint.md
  guides/v2.3/rest/search-endpoint.md
Labels: 2.2.x, 2.3.x, New topic, Partner: Comwrap, Progress: approved, partners-contribution

#6026 Fixes magento/devdocs#6025
  guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: 2.3.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#5971 magento/devdocs#: Cloud. Set ADMIN_URL via magneto-cloud command-line tool
  guides/v2.2/cloud/env/environment-vars_magento.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#6029 GraphQL: Clean-up around deprecated attributes
  guides/v2.3/graphql/mutations/add-configurable-products.md
  guides/v2.3/graphql/mutations/place-order.md
  guides/v2.3/graphql/product/downloadable-product.md
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries/cart.md
Labels: 2.3.4, Editorial, Progress: approved, internal-dev

#6039 Update Paging UI component documentation
  common/images/ui_comps/ui-paging-result.png
  guides/v2.2/ui_comp_guide/components/ui-paging.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6038 Update DragAndDrop UI component documentation
  common/images/ui_comps/ui-draganddrop-columns-result.png
  guides/v2.2/ui_comp_guide/components/ui-draganddrop.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6037 Update date column UI component documentation
  common/images/ui_comps/ui-date-column-result.png
  guides/v2.2/ui_comp_guide/components/ui-datecolumn.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6036 Update ui columns documentation
  common/images/ui_comps/ui-columns-list-result.png
  common/images/ui_comps/ui-columns-result.png
  guides/v2.2/ui_comp_guide/components/ui-columns.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6034 Update UI column component documentation
  common/images/ui_comps/ui-column-result.png
  guides/v2.2/ui_comp_guide/components/ui-column.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6033 Adding question mark when nullable value is declared
  guides/v2.2/contributor-guide/backward-compatible-development/index.md
  guides/v2.3/contributor-guide/backward-compatible-development/index.md
Labels: 2.2.x, 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution, small changes

#6030 Updated What's New with changes since November 4
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6040 magento/devdocs#5632: Incorrect link to JSCS site.
  guides/v2.2/coding-standards/code-standard-javascript.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6041 Merge UI component PRs
  common/images/ui_comps/ui-column-result.png
  common/images/ui_comps/ui-columns-list-result.png
  common/images/ui_comps/ui-columns-result.png
  common/images/ui_comps/ui-date-column-result.png
  common/images/ui_comps/ui-draganddrop-columns-result.png
  common/images/ui_comps/ui-paging-result.png
  guides/v2.2/ui_comp_guide/components/ui-column.md
  guides/v2.2/ui_comp_guide/components/ui-columns.md
  guides/v2.2/ui_comp_guide/components/ui-datecolumn.md
  guides/v2.2/ui_comp_guide/components/ui-draganddrop.md
  guides/v2.2/ui_comp_guide/components/ui-paging.md
Labels: Progress: review

#6047 Remove Google 302 reference from Whats New page
  _data/whats-new.yml
Labels: 2.x, Editorial, Progress: review, internal-dev

#6046 Revert Google 3.0.2 release notes
  _data/compatibility.yml
  extensions/google-shopping-ads/release-notes/index.md
  release/index.md
Labels: 3.0.2 Google Shopping ads, Progress: approved

#6048 GraphQL: Deprecate ProductInterfaces attributes
  guides/v2.3/graphql/product/product-interface.md
  guides/v2.3/graphql/queries/products.md
Labels: 2.3.4, Progress: approved, Technical, internal-dev

#6050 Optimized Index Management screen capture
  common/images/index_index-modes.png
Labels: Progress: approved

#6043 Updated Architecture topic for Starter plan
  guides/v2.2/cloud/architecture/cloud-architecture.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6051 magento/devdocs#: Add customerDownloadableProducts query API errors
  guides/v2.3/graphql/queries/customer-downloadable-products.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6049 magento/devdocs#: Add customerOrders query API errors
  guides/v2.3/graphql/queries/customer-orders.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6042 magento/devdocs#5218: Need info about structures in Adding a custom indexer
  guides/v2.2/extension-dev-guide/indexing-custom.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#6045 Updating Fieldset UiComponent documentation
  common/images/ui_comps/fieldset-component-result.png
  guides/v2.2/ui_comp_guide/components/ui-fieldset.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#6032 [site] Update 'rake build:prod'
  rakelib/build.rake
Labels: Progress: approved, Site improvements

#6031 GraphQL caching with Fastly
  guides/v2.2/cloud/cdn/configure-fastly.md
  guides/v2.3/graphql/caching.md
Labels: 2.3.x, Major update, Progress: review, internal-dev

#6052 GraphQL: small changes
  guides/v2.3/graphql/mutations/add-configurable-products.md
  guides/v2.3/graphql/mutations/add-simple-products.md
Labels: 2.3.x, Editorial, Progress: approved, internal-dev

#6058 Removing Cloud BI Import API From TOC
  _data/toc/mbi.yml
Labels: Progress: approved, internal-dev

#6054 Editorial fix
  guides/v2.2/cloud/cdn/configure-fastly.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6053 Updated view-models.md
  guides/v2.2/extension-dev-guide/view-models.md
Labels: 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution

#6059 Small changes
  guides/v2.2/architecture/archi_perspectives/service_layer.md
  guides/v2.2/coding-standards/code-standard-javascript.md
  guides/v2.2/contributor-guide/backward-compatible-development/index.md
  guides/v2.2/extension-dev-guide/view-models.md
  guides/v2.2/javascript-dev-guide/javascript/js-resources.md
  guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
  guides/v2.2/ui_comp_guide/concepts/magento-bindings.md
  guides/v2.3/contributor-guide/backward-compatible-development/index.md
  guides/v2.3/graphql/queries/customer-downloadable-products.md
  guides/v2.3/graphql/queries/customer-orders.md
Labels: Progress: approved

#6062 Add MBI to search and update site switcher
  Gemfile.lock
  _includes/layout/header-scripts.html
Labels: Progress: approved, Site improvements

#6063 KB migration: Restore an environment
  _data/toc/cloud-guide.yml
  common/images/copy-git-clone.png
  common/images/select-commit-hash.png
  guides/v2.2/cloud/env/restore-environment.md
  guides/v2.2/cloud/project/project-webint-snap.md
  guides/v2.3/cloud/env/restore-environment.md
Labels: New topic, Progress: approved

#6061 Converting the Display Magento error report number KB to devdocs
  guides/v2.2/cloud/cdn/cloud-fastly-custom-response.md
Labels: 2.x, New topic, Progress: changes requested, internal-dev

#6064 Fixed incorrect terminology and added references
  guides/v2.2/architecture/archi_perspectives/components/modules/mod_and_areas.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, Progress: review, partners-contribution

#6065 Set warning for STATIC_CONTENT_SYMLINK variable
  guides/v2.2/cloud/env/variables-deploy.md
Labels: 2.x, Partner: Comwrap, Progress: approved, Technical, partners-contribution

#6066 ElasticSearch: Nigix proxy config correction
  guides/v2.3/config-guide/elasticsearch/es-config-nginx.md
Labels: 2.3.x, Partner: Ziffity, Technical, partners-contribution

#6069 Updating CLI documentation
  guides/v2.2/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.2.x, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6068 Add supported service versions of RabbitMQ
  guides/v2.2/cloud/project/project-conf-files_services-rabbit.md
Labels: Editorial, Partner: Something Digital, Progress: review, partners-contribution, small changes

#6073 Remove remote_markdown completely
  _data/toc/module-reference-guide.yml
  _plugins/liquid-tags/remote_markdown.rb
  guides/v2.2/advanced-reporting/modules.md
  guides/v2.2/mrg/ce/Analytics.md
  guides/v2.2/mrg/ce/CatalogAnalytics.md
  guides/v2.2/mrg/ce/CustomerAnalytics.md
  guides/v2.2/mrg/ce/QuoteAnalytics.md
  guides/v2.2/mrg/ce/ReviewAnalytics.md
  guides/v2.2/mrg/ce/Sales.md
  guides/v2.2/mrg/ce/SalesAnalytics.md
  guides/v2.2/mrg/ce/WishlistAnalytics.md
  guides/v2.2/mtf/configuration.md
  guides/v2.2/mtf/mtf_entities/mtf_constraint.md
  guides/v2.2/mtf/mtf_entities/mtf_dataset.md
  guides/v2.2/mtf/mtf_entities/mtf_handler.md
  guides/v2.2/mtf/mtf_entities/mtf_scenariotest.md
  guides/v2.2/test/integration/annotations/magento-data-fixture.md
  guides/v2.3/test/integration/annotations/magento-data-fixture.md
Labels: Progress: approved, Site improvements

#6035 Added information on custom docker configurations
  guides/v2.2/cloud/docker/docker-config.md
  guides/v2.2/cloud/docker/docker-quick-reference.md
Labels: Partner: Zilker Technology, Progress: review, Technical, partners-contribution

#6074 Add example for local RabbitMQ Management UI
  guides/v2.2/cloud/project/project-conf-files_services-rabbit.md
Labels: Partner: Something Digital, Progress: approved, partners-contribution

#6072 Resolve code quotation error.
  guides/v2.2/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.x, Partner: Krish TechnoLabs, Technical, partners-contribution

#6075 Add docs for new Adobe-generated alert policies for New Relic
  _data/toc/cloud-guide.yml
  common/images/cloud/cloud-new-relic-notification-channels.png
  common/images/cloud/cloud-newrelic-alert-policies.png
  common/images/cloud/cloud-newrelic-dashboard-basic.png
  common/images/cloud/cloud-project-details-new-relic.png
  guides/v2.2/cloud/architecture/cloud-architecture.md
  guides/v2.2/cloud/live/go-live-checklist.md
  guides/v2.2/cloud/project/monitor-performance.md
  guides/v2.2/cloud/project/new-relic.md
  guides/v2.3/cloud/project/monitor-performance.md
Labels: 2.x, Major update, Progress: review

#6028 Image preview component added
  _data/toc/ui-components-guide.yml
  common/images/ui_comps/image-preview-result.png
  guides/v2.3/ui_comp_guide/components/ui-image-preview.md
Labels: Progress: review

#6078 Updates and corrections to Adobe-generated alert policy info
  guides/v2.2/cloud/integrations/health-notifications.md
  guides/v2.2/cloud/project/manage-disk-space.md
  guides/v2.2/cloud/project/new-relic.md
Labels: 2.x, Progress: review, Technical, internal-dev
