Repository magento/devdocs, pull requests merged in 2020-12, with the labels that each got.

#8294 Update simple-product.md
  src/guides/v2.3/graphql/interfaces/simple-product.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8298 GraphQL: Replace list of company role permissions with a structural view
  src/_includes/b2b/company/company-acl.md
  src/guides/v2.4/graphql/mutations/create-company-role.md
  src/guides/v2.4/graphql/mutations/update-company-role.md
Labels: 2.4.2, Internal Dev, Progress: approved, Technical

#8288 Update directory-currency.md
  src/guides/v2.3/graphql/queries/directory-currency.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8295 GraphQL: Add list of supported cards to Payflow Pro
  src/_includes/graphql/payment-methods/payflow-pro-attributes.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Technical

#8287 Link to Fastly DNS config info for apex domains
  src/cloud/cdn/configure-fastly.md
Labels: 2.x, Progress: approved

#8268 Removed basics. Clean up and some grammar.
  src/guides/v2.3/install-gde/prereq/install-rabbitmq.md
  src/guides/v2.3/install-gde/prereq/merch_install.md
  src/guides/v2.3/install-gde/prereq/optional.md
  src/guides/v2.3/install-gde/trouble/tshoot_access-browser.md
  src/guides/v2.4/install-gde/prereq/es-config-apache.md
Labels: 2.3.x, 2.4.x, Progress: review, Site Improvements

#8315 Update get-hosted-pro-url.md
  src/guides/v2.3/graphql/queries/get-hosted-pro-url.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8276 Update ui_comp_uiregistry.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiregistry.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8307 Update available-stores.md
  src/guides/v2.4/graphql/queries/available-stores.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8296 Fix wrong cli command
  src/guides/v2.3/test/static/static_test_execution.md
Labels: Partner: EY, Progress: approved, Small Changes, partners-contribution

#8306 PAY-226: Info architecture for Magento Payments
  _config.yml
  src/_data/main-nav.yml
  src/_data/toc/magento-payments.yml
  src/magento-payments/architecture.md
  src/magento-payments/configure-payments.md
  src/magento-payments/installing-payments.md
  src/magento-payments/managing-info.md
  src/magento-payments/payments.md
  src/magento-payments/security.md
Labels: Progress: approved, Site Improvements

#8309 updated the extension b2b installation command and added info
  src/extensions/b2b/index.md
Labels: Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8321 Update product-review-ratings-metadata.md
  src/guides/v2.4/graphql/queries/product-review-ratings-metadata.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8274 PHP code update for two-level cache in v2.3 devdocs
  src/guides/v2.3/config-guide/cache/two-level-cache.md
Labels: 2.3.x, Partner: EY, Progress: approved, Small Changes, Technical, partners-contribution

#8290 Updated the command in sample-data-rc1-cli-24.md file
  src/_includes/install/sampledata/file-sys-perms-digest-24.md
  src/_includes/install/sampledata/sample-data-rc1-cli-24.md
Labels: 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8326 Update plugins.md
  src/guides/v2.3/extension-dev-guide/plugins.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8279 Updated sample data clone commands
  src/_includes/install/sampledata/sample-data-clone-24.md
  src/guides/v2.4/install-gde/install/cli/install-cli-sample-data-clone.md
  src/guides/v2.4/install-gde/install/sample-data-after-clone.md
  src/guides/v2.4/install-gde/install/sample-data-before-clone.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8300 Update directory-currency.md
  src/guides/v2.3/graphql/queries/directory-currency.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8336 [DOCS] MCLOUD-7322: Removing elasticsearch plugins from services.yaml
  src/cloud/project/services-elastic.md
Labels: 2.4.x, Progress: approved, Technical, Tracking

#8302 Update directory-countries.md
  src/guides/v2.3/graphql/queries/directory-countries.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8308 Update pickup-locations.md
  src/guides/v2.4/graphql/queries/pickup-locations.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8310 Update url-resolver.md
  src/guides/v2.3/graphql/queries/url-resolver.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8320 Update get-payflow-link-token.md
  src/guides/v2.3/graphql/queries/get-payflow-link-token.md
Labels: Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8319 Update customer-payment-tokens.md
  src/guides/v2.3/graphql/queries/customer-payment-tokens.md
Labels: Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8318 Update custom-attribute-metadata.md
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8301 Update directory-country.md
  src/guides/v2.3/graphql/queries/directory-country.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8337 Small changes
  src/_includes/install/sampledata/file-sys-perms-digest-24.md
  src/_includes/install/sampledata/sample-data-clone-24.md
  src/_includes/install/sampledata/sample-data-rc1-cli-24.md
  src/guides/v2.3/config-guide/cache/two-level-cache.md
  src/guides/v2.3/extension-dev-guide/plugins.md
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
  src/guides/v2.3/graphql/queries/customer-payment-tokens.md
  src/guides/v2.3/graphql/queries/directory-countries.md
  src/guides/v2.3/graphql/queries/directory-country.md
  src/guides/v2.3/graphql/queries/directory-currency.md
  src/guides/v2.3/graphql/queries/get-hosted-pro-url.md
  src/guides/v2.3/graphql/queries/get-payflow-link-token.md
  src/guides/v2.3/graphql/queries/url-resolver.md
  src/guides/v2.3/test/static/static_test_execution.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiregistry.md
  src/guides/v2.4/graphql/queries/available-stores.md
  src/guides/v2.4/graphql/queries/pickup-locations.md
  src/guides/v2.4/graphql/queries/product-review-ratings-metadata.md
  src/guides/v2.4/install-gde/install/cli/install-cli-sample-data-clone.md
  src/guides/v2.4/install-gde/install/sample-data-after-clone.md
  src/guides/v2.4/install-gde/install/sample-data-before-clone.md
Labels: Maintenance, Progress: approved

#8303 GraphQL coverage for shopper assistance
  src/_data/toc/graphql.yml
  src/_includes/graphql/customer-output-24.md
  src/guides/v2.4/graphql/authorization-tokens.md
  src/guides/v2.4/graphql/mutations/create-customer-v2.md
  src/guides/v2.4/graphql/mutations/generate-customer-token-as-admin.md
  src/guides/v2.4/graphql/mutations/update-customer-v2.md
Labels: 2.4.2, New Topic, Partner: EY, Progress: approved, partners-contribution

#8305 GraphQL: Add company credit coverage
  src/_includes/graphql/company.md
  src/guides/v2.4/graphql/queries/company.md
Labels: 2.4.2, Community, Internal Dev, Progress: approved, Technical

#8322 Update products.md
  src/guides/v2.4/graphql/queries/products.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8247 Issue-3393- Documentation for multistore setups
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-maint.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8349 MC-39142: [Documentation] Update documentation for DMT timezone settings
  src/guides/v2.3/migration/migration-migrate-follow-up.md
Labels: Internal Dev, Progress: approved, Technical

#8345 Update braintree-vault.md
  src/guides/v2.3/graphql/payment-methods/braintree-vault.md
Labels: Editorial, Partner: EY, Progress: approved, partners-contribution

#8346 Update payflow-pro.md
  src/guides/v2.3/graphql/payment-methods/payflow-pro.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8344 Add reference to the order item options for the OrderItemInterface attributes page and dynamic link in Invoice attribute page.
  src/_includes/graphql/invoice-item-interface.md
  src/_includes/graphql/order-item-interface.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8355 Update add-products-to-cart.md
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8353 Customer query improvements
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/product-review.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/queries/customer.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8352 Cart query Object improvement
  src/_includes/graphql/cart-object-24.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/cart.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8313 Update category-list.md
  src/guides/v2.3/graphql/queries/category-list.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8356 Fixed the argument name
  src/guides/v2.3/extension-dev-guide/view-models.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8357 Enable MD linter in SuperLinter's workflow
  .github/ISSUE_TEMPLATE/NEW_FEATURE.md
  .github/workflows/linter.yml
  _checks/html_check_hook.rb
  src/cloud/cdn/configure-fastly.md
  src/cloud/live/site-launch-checklist.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
  src/guides/v2.3/install-gde/system-requirements.md
  src/guides/v2.4/extension-dev-guide/versioning/mftf-tests-codebase-changes.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
  src/marketplace/sellers/installation-and-varnish-tests.md
Labels: Maintenance, Progress: approved

#8351 Moving Customize Magento Admin Design to DevDocs
  src/_data/toc/how-do-i.yml
  src/common/images/design_conf2.png
  src/guides/v2.3/howdoi/admin/customize_admin.md
  src/guides/v2.4/howdoi/admin/customize_admin.md
Labels: 2.3.x, 2.4.x, New Topic, Partner: Vaimo, Progress: approved, partners-contribution

#8342 product-interface-dynamic-links-mapping
  src/guides/v2.3/graphql/interfaces/bundle-product.md
  src/guides/v2.3/graphql/interfaces/configurable-product.md
  src/guides/v2.3/graphql/interfaces/downloadable-product.md
  src/guides/v2.3/graphql/interfaces/gift-card-product.md
  src/guides/v2.3/graphql/interfaces/grouped-product.md
  src/guides/v2.3/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.3/graphql/interfaces/product-interface.md
  src/guides/v2.3/graphql/interfaces/virtual-product.md
  src/guides/v2.4/graphql/interfaces/bundle-product.md
  src/guides/v2.4/graphql/interfaces/configurable-product.md
  src/guides/v2.4/graphql/interfaces/downloadable-product.md
  src/guides/v2.4/graphql/interfaces/gift-card-product.md
  src/guides/v2.4/graphql/interfaces/grouped-product.md
  src/guides/v2.4/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/interfaces/simple-product.md
  src/guides/v2.4/graphql/interfaces/virtual-product.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8311 Added an explanation on how to pass data to the script via data-mage-init and to access them in the script.
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8350 Product Recommendations release notes for 3.2.0
  src/_data/mde.yml
  src/recommendations/install-configure.md
  src/recommendations/release-notes.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8365 Fix 2.4.2 beta release date
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: approved

#8358 Added yotpo release notes
  src/_data/toc/extensions.yml
  src/_data/vbe.yml
  src/extensions/vendor/yotpo/release-notes.md
Labels: 2.4.2, Internal Dev, New Topic, Progress: approved

#8151 Add Braintree VBE and update UG links
  src/_data/vbe.yml
  src/extensions/vendor/vendor.md
Labels: Internal Dev, Maintenance, Progress: approved, hacktoberfest-accepted

#8366 Add Braintree entry to VBE compatibility matrix for 2.4.1
  src/_data/vbe.yml
Labels: 2.4.1, Internal Dev, Maintenance, Progress: approved

#8363 Updating prex to 3.2.2
  src/_data/mde.yml
  src/recommendations/release-notes.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8375 MQP Release 1.0.13
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update

#8202 Added documentation for copy, move and delete requisition list items mutations
  src/_data/toc/graphql.yml
  src/_includes/graphql/requisition-list.md
  src/guides/v2.4/graphql/mutations/copy-items-between-requisition-lists.md
  src/guides/v2.4/graphql/mutations/delete-requisition-list-items.md
  src/guides/v2.4/graphql/mutations/move-items-between-requisition-lists.md
Labels: 2.4.2, New Topic, Partner: Zilker Technology, Progress: approved, partners-contribution

#8368 Update web-api-functional-testing.md
  src/guides/v2.3/get-started/web-api-functional-testing.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8362 Wishlist error message
  src/guides/v2.4/graphql/mutations/add-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/remove-products-from-wishlist.md
  src/guides/v2.4/graphql/mutations/update-products-in-wishlist.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8328 Update customizable-option-interface.md
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
Labels: Partner: EY, Progress: approved, Technical, partners-contribution

#8361 Add Error message on the product type
  src/guides/v2.3/graphql/mutations/add-bundle-products.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/mutations/add-downloadable-products.md
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/mutations/add-downloadable-products.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8377 Merge small-changes branch into master
  src/_includes/graphql/cart-object-24.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/invoice-item-interface.md
  src/_includes/graphql/order-item-interface.md
  src/_includes/graphql/product-review.md
  src/guides/v2.3/extension-dev-guide/view-models.md
  src/guides/v2.3/graphql/mutations/add-bundle-products.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/mutations/add-downloadable-products.md
  src/guides/v2.3/graphql/payment-methods/braintree-vault.md
  src/guides/v2.3/graphql/payment-methods/payflow-pro.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/category-list.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/mutations/add-downloadable-products.md
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/customer.md
Labels: Maintenance, Progress: approved

#8382 Updated Serializer implementations
  src/guides/v2.3/extension-dev-guide/framework/serializer.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8367 Example added on how to overwrite a knockoutjs html file
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8383 Added the asynchronous way of retrieving ui components from the registry
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiregistry.md
Labels: 2.3.x, 2.4.2, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8384 Added new page for URL library
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/framework/url-library.md
  src/guides/v2.4/extension-dev-guide/framework/url-library.md
Labels: New Topic, Partner: EY, Progress: approved, partners-contribution

#8374 Adding link to catalog sync dashboard
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-catalog-sync.md
Labels: 2.3.x, Editorial, Internal Dev, Progress: approved

#8079 Update BIC reference
  src/_includes/backward-incompatible-changes/commerce/2.4.1-2.4.2-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.4.1-2.4.2-develop.html
Labels: Automation, Internal Dev, Progress: on hold, hacktoberfest-accepted

#8390 added a missing code-fence
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8391 Updated the Linux kernel info on the software page
  src/guides/v2.3/performance-best-practices/software.md
  src/guides/v2.4/performance-best-practices/software.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8280 GraphQL: Add staging attribute
  src/guides/v2.4/graphql/interfaces/category-interface.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
Labels: 2.4.2, Internal Dev, Progress: approved, Technical

#8254 MC38472 remote storage
  src/_data/toc/configuration-guide.yml
  src/common/images/config-remote-storage-nginx-image-resize.png
  src/common/images/config-remote-storage-schema.png
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-caching.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-image-resize.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage.md
  src/guides/v2.4/install-gde/install/cli/install-cli-install.md
Labels: 2.4.2, Internal Dev, New Topic, Progress: approved

#8348 Fix 404s on External Links
  src/cloud/cdn/fastly-vcl-badreferer.md
  src/guides/v2.3/coding-standards/docblock-standard-general.md
  src/guides/v2.3/config-guide/secy/secy-xframe.md
  src/guides/v2.3/config-guide/varnish/config-varnish-advanced.md
  src/guides/v2.3/config-guide/varnish/config-varnish-install.md
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.4/test/integration/annotations.md
Labels: 2.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8354 8341 requisition list mutations
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/add-products-to-requisition-list.md
  src/guides/v2.4/graphql/mutations/add-requisition-list-items-to-cart.md
  src/guides/v2.4/graphql/mutations/clear-customer-cart.md
  src/guides/v2.4/graphql/mutations/update-requisition-list-items.md
Labels: 2.4.2, New Topic, Partner: EY, Progress: approved, partners-contribution

#8388 Magento 2 4 2 Beta Release Notes
  src/_data/toc/release-notes.yml
  src/_includes/release-notes/engcomm-2-4-2-issues.md
  src/_includes/release-notes/engcomm-2-4-2-partner.md
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/guides/v2.4/release-notes/bk-release-notes.md
  src/guides/v2.4/release-notes/commerce-2-4-2.md
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8393 Update whastnew template and rake task
  Rakefile
  src/whats-new.md
Labels: Progress: approved, Site Improvements

#8385 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#8397 Added PB user guide links
  src/guides/v2.4/release-notes/commerce-2-4-2.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#8381 issue-8376-made the requested changes
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/create-requisition-list.md
  src/guides/v2.4/graphql/mutations/delete-requisition-list-items.md
  src/guides/v2.4/graphql/mutations/delete-requisition-list.md
  src/guides/v2.4/graphql/mutations/update-requisition-list.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8403 [AWS S3] MC-38901: Add release notes
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#8327 added a note indicating that the deletion of snippets has to be done using the api
  src/cloud/cdn/cloud-vcl-custom-snippets.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8406 Magento 2.4.2 Beta Release Notes minor change
  src/guides/v2.4/release-notes/commerce-2-4-2.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#7998 [maintenance] Add plugins for debugging
  _plugins/debug/site_post_render.rb
  _plugins/debug/site_pre_render.rb
Labels: Maintenance, Progress: approved

#8405 Update the linting workflow on GitHub
  .github/workflows/linter.yml
  .github/workflows/main.yml
Labels: Maintenance, Progress: approved

#8387 Update README link to docker
  README.md
Labels: Internal Dev, Progress: approved, Small Changes

#8386 Use "jekyll/jekyll:3.8.6" so it is locked, rather than "latest"
  docker-compose.yaml
Labels: Progress: approved, Small Changes, Technical

#8410 Magento 2.4.2 Beta release Note update (removal of known issue description for MC-39522)
  src/guides/v2.4/release-notes/commerce-2-4-2.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved, Progress: on hold

#8409 Disable OpenAPI linter
  .github/workflows/linter.yml
Labels: Maintenance, Progress: approved

#8364 Improve info about managing SSH keys in Cloud Guide
  src/_includes/cloud/enable-ssh.md
  src/cloud/project/user-admin.md
Labels: Progress: approved, Technical

#8398 GraphQL: Add configurable_product_options_selection attribute and exa…
  src/guides/v2.4/graphql/interfaces/configurable-product.md
Labels: 2.4.2, Internal Dev, Progress: approved, Technical

#8408 GraphQL: Requisition list updates
  src/_data/toc/graphql.yml
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/requisition-list.md
  src/guides/v2.4/graphql/interfaces/requisition-list-item-interface.md
  src/guides/v2.4/graphql/queries/customer.md
Labels: 2.4.2, Internal Dev, Progress: approved, Technical

#8399 shipment-email-notify
  src/guides/v2.3/rest/tutorials/orders/order-create-shipment.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: changes requested, partners-contribution

#8400 Update performing-searches.md
  src/guides/v2.3/rest/performing-searches.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8379 Added an additional method regarding adding a SSH key
  src/_includes/cloud/enable-ssh.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8415 MC-40003: [Documentation] Invalid directive for 'X-Frame-Options' header
  src/guides/v2.3/config-guide/secy/secy-xframe.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#8412 Update compatibility matrix and availability tables for 2.4.2
  src/_data/mde.yml
  src/_data/vbe.yml
  src/release/availability.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8283 Add __('<your_string>') method in Prompt widget
  src/guides/v2.3/javascript-dev-guide/widgets/widget_prompt.md
Labels: Progress: approved

#8418 Merge small-changes branch into master
  README.md
  docker-compose.yaml
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
  src/guides/v2.3/performance-best-practices/software.md
  src/guides/v2.3/rest/tutorials/orders/order-create-shipment.md
  src/guides/v2.4/performance-best-practices/software.md
Labels: 2.3.x, 2.4.x, Maintenance, Progress: approved

#8401 Update catalog.md
  src/guides/v2.3/rest/modules/catalog.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8413 giftcard errors coverage
  src/guides/v2.3/graphql/mutations/remove-giftcard.md
  src/guides/v2.4/graphql/mutations/remove-giftcard.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8422 Add instructions for reverting from a split database to a single database
  src/_data/toc/configuration-guide.yml
  src/guides/v2.3/config-guide/revert-split-database.md
  src/guides/v2.4/config-guide/revert-split-database.md
Labels: 2.3.x, 2.4.x, Internal Dev, New Topic, Progress: approved

#8423 Sync 2.4.2-develop
  .github/workflows/linter.yml
  .github/workflows/main.yml
  README.md
  Rakefile
  _plugins/debug/site_post_render.rb
  _plugins/debug/site_pre_render.rb
  docker-compose.yaml
  src/_data/toc/php-developer-guide.yml
  src/_data/whats-new.yml
  src/_includes/cloud/enable-ssh.md
  src/_includes/graphql/cart-object-24.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/invoice-item-interface.md
  src/_includes/graphql/order-item-interface.md
  src/_includes/graphql/product-review.md
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/cdn/fastly-vcl-badreferer.md
  src/cloud/project/user-admin.md
  src/guides/v2.3/coding-standards/docblock-standard-general.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-catalog-sync.md
  src/guides/v2.3/config-guide/secy/secy-xframe.md
  src/guides/v2.3/config-guide/varnish/config-varnish-advanced.md
  src/guides/v2.3/config-guide/varnish/config-varnish-install.md
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.3/extension-dev-guide/framework/serializer.md
  src/guides/v2.3/extension-dev-guide/framework/url-library.md
  src/guides/v2.3/extension-dev-guide/view-models.md
  src/guides/v2.3/graphql/mutations/add-bundle-products.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/mutations/add-downloadable-products.md
  src/guides/v2.3/graphql/payment-methods/braintree-vault.md
  src/guides/v2.3/graphql/payment-methods/payflow-pro.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/category-list.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_prompt.md
  src/guides/v2.3/performance-best-practices/software.md
  src/guides/v2.3/rest/modules/catalog.md
  src/guides/v2.3/rest/performing-searches.md
  src/guides/v2.3/rest/tutorials/orders/order-create-shipment.md
  src/guides/v2.4/extension-dev-guide/framework/url-library.md
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/mutations/add-downloadable-products.md
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/performance-best-practices/software.md
  src/guides/v2.4/test/integration/annotations.md
  src/whats-new.md
Labels: 2.4.2, Maintenance, Progress: approved

#8425 Sync 2.4.2-develop (2nd try)
  src/_data/toc/configuration-guide.yml
  src/guides/v2.3/config-guide/revert-split-database.md
  src/guides/v2.4/config-guide/revert-split-database.md
Labels: 2.4.2, Maintenance, Progress: approved

#8424 Add deprecation notice for the split database feature
  src/_includes/layout/page-header.html
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8421 added coverage for shipping address
  src/guides/v2.4/graphql/mutations/set-shipping-address.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8420 added update customer coverage
  src/guides/v2.4/graphql/mutations/update-customer.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8404 Cloud Docker release notes 1.2.1
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved, Tracking

#8429 Cloud Docker release 1.2.1
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Progress: approved

#8427 Update messaging about the deprecation of the split database feature
  src/guides/v2.3/config-guide/revert-split-database.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#8426 Magento 2.4.2 Beta Release Note minor update December 21
  src/guides/v2.4/release-notes/commerce-2-4-2.md
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.2, Internal Dev, Progress: review

#8369 GraphQL: StoreConfig attribute updates
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/queries/available-stores.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.2, Internal Dev, Progress: approved, Technical

#8435 FAdded missing release note item from contributor.
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.4.x, Internal Dev, Progress: approved

#8273 GraphQL: Deprecate id attributes in favor of uids
  src/_data/toc/graphql.yml
  src/_includes/graphql/cart-item-input-24.md
  src/_includes/graphql/cart-object-24.md
  src/_includes/graphql/category-filter-input.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customizable-option-input-24.md
  src/_includes/graphql/downloadable-items-links.md
  src/_includes/graphql/entered-option-input.md
  src/_includes/graphql/gift-wrapping.md
  src/_includes/graphql/grouped-product-sample-24.md
  src/_includes/graphql/item-selected-bundle-option.md
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/interfaces/bundle-product.md
  src/guides/v2.4/graphql/interfaces/cart-item-interface.md
  src/guides/v2.4/graphql/interfaces/category-interface.md
  src/guides/v2.4/graphql/interfaces/configurable-product.md
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.4/graphql/interfaces/downloadable-product.md
  src/guides/v2.4/graphql/interfaces/gift-card-product.md
  src/guides/v2.4/graphql/interfaces/grouped-product.md
  src/guides/v2.4/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/interfaces/simple-product.md
  src/guides/v2.4/graphql/interfaces/virtual-product.md
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/mutations/add-downloadable-products.md
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
  src/guides/v2.4/graphql/mutations/add-simple-products.md
  src/guides/v2.4/graphql/mutations/add-virtual-products.md
  src/guides/v2.4/graphql/mutations/remove-item.md
  src/guides/v2.4/graphql/mutations/reorder-items.md
  src/guides/v2.4/graphql/mutations/set-gift-options.md
  src/guides/v2.4/graphql/mutations/update-cart-items.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/categories.md
  src/guides/v2.4/graphql/queries/category-list.md
  src/guides/v2.4/graphql/queries/customer-cart.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/graphql/queries/products.md
  src/guides/v2.4/graphql/queries/url-resolver.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8434 added errors coverage for billing address mutation
  src/guides/v2.4/graphql/mutations/set-gift-options.md
Labels: Partner: EY, Progress: ready for review, partners-contribution

#8221 GraphQL: Document WishlistItemInterface
  src/_data/toc/graphql.yml
  src/_includes/graphql/wishlist-item-interface.md
  src/_includes/graphql/wishlist.md
  src/guides/v2.4/graphql/interfaces/wishlist-item-interface.md
  src/guides/v2.4/graphql/mutations/add-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/copy-products-between-wishlists.md
  src/guides/v2.4/graphql/mutations/copy-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/create-wishlist.md
  src/guides/v2.4/graphql/mutations/delete-wishlist.md
  src/guides/v2.4/graphql/mutations/move-products-between-wishlists.md
  src/guides/v2.4/graphql/mutations/move-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/remove-products-from-wishlist.md
  src/guides/v2.4/graphql/mutations/update-products-in-wishlist.md
  src/guides/v2.4/graphql/mutations/update-wishlist.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/release-notes/commerce-2-4-2.md
Labels: 2.4.x, Internal Dev, New Topic, Progress: approved

#8402 Update proxies.md
  src/guides/v2.3/extension-dev-guide/proxies.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8428 GraphQL: Merge requisition lists docs into 2.4.2-develop
  src/_data/toc/graphql.yml
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/requisition-list.md
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/interfaces/requisition-list-item-interface.md
  src/guides/v2.4/graphql/mutations/add-products-to-requisition-list.md
  src/guides/v2.4/graphql/mutations/add-requisition-list-items-to-cart.md
  src/guides/v2.4/graphql/mutations/clear-customer-cart.md
  src/guides/v2.4/graphql/mutations/copy-items-between-requisition-lists.md
  src/guides/v2.4/graphql/mutations/create-requisition-list.md
  src/guides/v2.4/graphql/mutations/delete-requisition-list-items.md
  src/guides/v2.4/graphql/mutations/delete-requisition-list.md
  src/guides/v2.4/graphql/mutations/move-items-between-requisition-lists.md
  src/guides/v2.4/graphql/mutations/update-requisition-list-items.md
  src/guides/v2.4/graphql/mutations/update-requisition-list.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/release-notes/commerce-2-4-2.md
Labels: 2.4.2, Community, Internal Dev, New Topic, Progress: approved

#8258 GraphQL: Add RMA mutations
  src/_data/toc/graphql.yml
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/return.md
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/mutations/add-return-comment.md
  src/guides/v2.4/graphql/mutations/add-return-tracking.md
  src/guides/v2.4/graphql/mutations/remove-return-tracking.md
  src/guides/v2.4/graphql/mutations/request-return.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/release-notes/commerce-2-4-2.md
Labels: 2.4.2, Internal Dev, New Topic, Progress: approved

#8442 Merge small-changes PRs into master
  src/guides/v2.3/graphql/mutations/remove-giftcard.md
  src/guides/v2.4/graphql/mutations/remove-giftcard.md
  src/guides/v2.4/graphql/mutations/set-gift-options.md
  src/guides/v2.4/graphql/mutations/set-shipping-address.md
  src/guides/v2.4/graphql/mutations/update-customer.md
Labels: Progress: approved

#8414 add purchase order changes
  src/guides/v2.3/b2b/bk-b2b.md
  src/guides/v2.4/b2b/bk-b2b.md
  src/guides/v2.4/b2b/integrations.md
Labels: 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution
