Repository magento/devdocs, pull requests merged in 2020-06, with the labels that each got.

#7308 Update ruby and gems
  .ruby-version
  Gemfile.lock
Labels: Maintenance, Progress: approved

#7324 Remove lines breaking whastnew generation
  src/_data/whats-new.yml
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7327 Updates to error reference for ece-tools deployment
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/note-error-message-reference-ece-tools.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/log-locations.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/error-codes.md
  src/cloud/trouble/trouble.md
Labels: 2.x, Internal Dev, Major Update, Progress: review

#7328 Revert ruby to 2.6.5
  .ruby-version
Labels: Maintenance, Progress: approved

#7310 Update configure-fastly.md
  src/cloud/cdn/configure-fastly.md
Labels: 2.x, Progress: approved, Technical

#7309 Adjust syntax
  src/guides/v2.3/extension-dev-guide/package/package_module.md
Labels: 2.3.x, Editorial, Partner: Le Site, Progress: approved, Small Changes, partners-contribution

#7335 Added configuration instructions for Blackfire.io in Cloud Docker
  src/_data/toc/cloud-guide.yml
  src/cloud/docker/docker-config-blackfire-io.md
Labels: 2.x, Internal Dev, New Topic, Progress: approved

#7288 Update redis preload documentation
  src/guides/v2.3/config-guide/redis/redis-pg-cache.md
Labels: 2.3.x, Progress: approved, Technical

#7315 Spelling error
  src/guides/v2.3/comp-mgr/patching.md
Labels: 2.3.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7321 Add info about Xdebug container for Cloud Docker and update configuration instructions
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/howtos/debug.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7338 Magento 2.4.0 Release Note minor fixes -- 0602
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Progress: approved, Small Changes

#7337 add CACHE_ENABLE_FAILED and CRYPT_KEY_IS_ABSENT error messages
  src/_data/cloud-error-messages.yml
  src/cloud/reference/error-codes.md
Labels: Internal Dev, Progress: approved

#7300 Updating step for BitBucket integration
  src/cloud/integrations/bitbucket-integration.md
Labels: 2.x, Partner: Rave Digital, Progress: approved, Technical, partners-contribution

#7342 Backward incompatible page 2.4 fix typo
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: Editorial, Progress: approved

#7344 Magento 2.3.x release note update for Extension Manager known issue
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.x, Major Update, Progress: approved

#7343 Remove Extension Manager docs
  src/_data/toc/extensions.yml
  src/_data/toc/software-update-guide.yml
  src/_includes/layout/page-header.html
  src/common/images/cman_uninstall-data.png
  src/common/images/cman_update-fail.png
  src/common/images/extens_mgr_login.png
  src/common/images/extens_mgr_select.png
  src/common/images/extens_mgr_updates.png
  src/common/images/extensman_choose-to-install.png
  src/common/images/extensman_columns-only.png
  src/common/images/extensman_delete.png
  src/common/images/extensman_icon_question.png
  src/common/images/extensman_new-purchases-step3install.png
  src/common/images/extensman_new-purchases_finish.png
  src/common/images/extensman_new-updates.png
  src/common/images/extensman_read-upd-multi-fail.png
  src/common/images/extensman_read-upd-multi-success.png
  src/common/images/extensman_ready-to-install-pg.png
  src/common/images/extensman_ready-to-install.png
  src/common/images/extensman_review-purchases.png
  src/common/images/extensman_uninst2.png
  src/common/images/extensman_uninstall.png
  src/common/images/extensman_update-all.png
  src/common/images/extensman_update-selected.png
  src/common/images/extensman_update-step.png
  src/common/images/extensman_update-success.png
  src/common/images/extensman_update_readiness.png
  src/extensions/install/index.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-backup.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-checklist.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-main-pg.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-new-purchase.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-readiness-fail.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-readiness-multi.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-readiness-success.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-readiness.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-uninst-data.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-uninst-final.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-update.md
  src/guides/v2.3/comp-mgr/extens-man/step3-parent.md
  src/guides/v2.3/comp-mgr/prereq/prereq_compman.md
  src/guides/v2.3/extension-dev-guide/intro/intro-composer-gloss.md
  src/guides/v2.3/extension-dev-guide/prepare/lifecycle.md
  src/guides/v2.3/extension-dev-guide/validate/test-module.md
  src/guides/v2.3/frontend-dev-guide/translations/xlate.md
Labels: 2.3.x, Internal Dev, Major Update, Progress: approved

#7350 Fix RSS feed
  src/feed.xml
  src/whatsnew-feed.xml
Labels: Maintenance, Progress: approved

#7351 Update the beta banner to warn of source code links
  src/_includes/layout/page-header.html
Labels: Progress: approved, Site Improvements

#7347 update action on LESS change
  src/guides/v2.3/howdoi/php/php_clear-dirs.md
Labels: 2.3.x, Editorial, Progress: approved

#7348 Fixed Incorrect query in gift card product example
  src/guides/v2.3/graphql/product/gift-card-product.md
Labels: 2.3.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#7355 Revise topmost callout of Best practices for extension devs topic
  src/guides/v2.3/ext-best-practices/bk-ext-best-practices.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7345 MCLOUD-2361: OOTB Docker Initialization
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
Labels: Internal Dev, Progress: changes requested

#7322 MCLOUD-3734: Wizard CLI command for split Db 'wizard:split-db-state'
  src/cloud/deploy/smart-wizards.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7340 magento/devdocs#: Add updateCartItems query API errors
  src/guides/v2.3/graphql/mutations/update-cart-items.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7352 Added a redirect for page linked from admin UI
  src/guides/v2.4/release-notes/bk-release-notes.md
Labels: Maintenance, Progress: approved

#7353 Updating testing recommendations topic
  src/recommendations/test.md
Labels: 2.3.5, Internal Dev, Progress: approved

#7357 Update checkout_customize.md
  src/guides/v2.3/howdoi/checkout/checkout_customize.md
Labels: 2.x, Editorial

#7359 Imropve performance by getting rid of loadIcons script
  Gemfile.lock
  src/_includes/layout/site-nav.html
  src/_includes/layout/version-switcher.html
  src/common/css/devdocs.css
Labels: Progress: approved

#7341 magento/devdocs#: Add setShippingAddressesOnCart query API errors
  src/guides/v2.3/graphql/mutations/set-shipping-address.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7360 fix: missing space in sentence
  src/guides/v2.3/extension-dev-guide/security/content-security-policies.md
Labels: 2.3.x, Editorial, Progress: approved

#7318 Remove multi-tenant notice
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-compiler.md
Labels: 2.3.4, 2.3.x, Editorial, Partner: Something Digital, Progress: approved, partners-contribution

#7314 magento/devdocs#: Disabling plugins. Add an example about a particular case.
  src/guides/v2.3/extension-dev-guide/plugins.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7362 magento/devdocs#: Add setPaymentMethodAndPlaceOrder mutation API errors
  src/guides/v2.3/graphql/mutations/set-payment-place-order.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7358 MC-23384 Update email template rule
  src/guides/v2.4/frontend-dev-guide/templates/template-email-migration.md
Labels: 2.4.x, Editorial, Progress: approved

#7372 MCLOUD-6137: Mention error log file
  src/cloud/project/log-locations.md
  src/cloud/reference/error-codes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7370 MC-34170 Add Note about PHP 7.4.2 bug
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.x, Editorial, Progress: approved

#7330 Update L2 cache
  src/guides/v2.4/config-guide/cache/two-level-cache.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7384 Removed pre-release date for 2.3.5-p2
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: approved

#7385 Decouple MBI from Advanced Reports (DevDocs side)
  src/guides/v2.3/advanced-reporting/data-collection.md
  src/guides/v2.3/advanced-reporting/modules.md
  src/guides/v2.3/advanced-reporting/overview.md
Labels: 2.3.x, Editorial, Progress: approved

#7378 magento/devdocs#7375: GraphQL: Add support for Inventory In-Store Pickup.
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/set-shipping-address.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/pickup-locations.md
Labels: 2.4.x, New Topic, Partner: Vaimo, Progress: approved, partners-contribution

#7371 update m2-ece-scd-dump to ece-tools config:dump
  src/cloud/architecture/starter-develop-deploy-workflow.md
  src/cloud/live/sens-data-initial.md
  src/cloud/project/project-upgrade.md
  src/cloud/reference/discover-deploy.md
Labels: 2.x, Progress: approved, Small Changes, Technical

#7393 Add caveat for webapi admin session authentication bug
  src/guides/v2.3/get-started/authentication/gs-authentication-session.md
Labels: Progress: approved, Technology Partner: dotdigital, tech-partners-contribution

#7383 magento/devdocs#7376: REST: Inventory In-Store Pickup endpoints.
  src/_data/toc/inventory.yml
  src/_data/toc/rest-api.yml
  src/guides/v2.4/rest/modules/inventory/in-store-pickup.md
  src/guides/v2.4/rest/modules/inventory/manage-sources.md
Labels: 2.4.0, Community, New Topic, Partner: Vaimo, Progress: approved, partners-contribution

#7394 Clarify support for Elasticsearch in Magento 2.4.0
  src/_data/toc/configuration-guide.yml
  src/_includes/layout/page-header.html
  src/guides/v2.4/comp-mgr/prereq/prereq-elasticsearch.md
  src/guides/v2.4/config-guide/elasticsearch/es-downgrade.md
  src/guides/v2.4/config-guide/elasticsearch/es-overview.md
  src/guides/v2.4/install-gde/prereq/elasticsearch.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7396 ece-tools list sample response added
  src/cloud/reference/ece-tools-reference.md
Labels: 2.x, Partner: Ziffity, Progress: approved, Small Changes, Technical, partners-contribution

#7397 Change Docfile to point to new page-builder docs repo
  Docfile.yml
Labels: 2.3.x, Internal Dev, Progress: approved, Site Improvements

#7392 2FA Updates (redux)
  src/guides/v2.3/security/two-factor-authentication.md
  src/guides/v2.4/security/two-factor-authentication.md
Labels: 2.3.x, 2.4.0, Internal Dev, Major Update, Progress: approved

#7406 Add whatsnew update for changes since June 9
  src/_data/whats-new.yml
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7401 Added instruction to obtain module name
  src/extensions/install/index.md
Labels: 2.3.x, Progress: approved

#7402 Updated inter server communication section
  src/guides/v2.3/install-gde/prereq/security.md
Labels: 2.3.x, Editorial, Progress: approved

#7415 Removed references to Signifyd
  src/_data/toc/payments-integrations.yml
  src/guides/v2.4/config-guide/prod/config-reference-most.md
  src/guides/v2.4/payments-integrations/signifyd/signifyd.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7414 Remove deprecated payment methods
  src/_includes/webapi/services24.md
  src/guides/v2.4/config-guide/prod/config-reference-payment.md
  src/guides/v2.4/config-guide/prod/config-reference-sens.md
  src/guides/v2.4/howdoi/checkout/checkout_payment.md
  src/guides/v2.4/rest/list.md
  src/guides/v2.4/rest/rest_endpoints.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7417 Announce removal of the Braintree module in the 2.4 Payment Integrations Guide
  src/_includes/layout/page-header.html
  src/guides/v2.3/payments-integrations/base-integration/admin-integration.md
  src/guides/v2.3/payments-integrations/base-integration/facade-configuration.md
  src/guides/v2.3/payments-integrations/base-integration/formblocktype.md
  src/guides/v2.3/payments-integrations/base-integration/get-payment-info.md
  src/guides/v2.3/payments-integrations/base-integration/integration-intro.md
  src/guides/v2.3/payments-integrations/cardinal/cardinal.md
  src/guides/v2.3/payments-integrations/payment-gateway/command-pool.md
  src/guides/v2.3/payments-integrations/payment-gateway/error-code-mapper.md
  src/guides/v2.3/payments-integrations/payment-gateway/gateway-command.md
  src/guides/v2.3/payments-integrations/payment-gateway/request-builder.md
  src/guides/v2.3/payments-integrations/payment-gateway/response-handler.md
  src/guides/v2.3/payments-integrations/vault/customer-stored-payments.md
  src/guides/v2.3/payments-integrations/vault/enabler.md
  src/guides/v2.4/howdoi/checkout/checkout_payment.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7412 Add release notes for Cloud Components 1.0.4
  src/cloud/release-notes/mcc-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7418 Fix version support table
  src/cloud/project/project-conf-files_services.md
Labels: 2.x, Internal Dev, Progress: approved, Small Changes

#7413 2.4 manish develop
  src/cloud/project/user-admin.md
Labels: 2.x, Editorial, Progress: approved, Small Changes

#7419 Remove Internet Explorer 11 from the list of supported browsers
  src/_includes/browsers/supported-browsers-24.md
  src/guides/v2.4/frontend-dev-guide/bk-frontend-dev-guide.md
  src/guides/v2.4/install-gde/system-requirements_browsers.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7421 2.4 manish develop
  src/cloud/project/user-admin.md
Labels: 2.4.x, Editorial, Progress: approved

#7331 Update for redis configuration
  src/guides/v2.4/config-guide/redis/redis-pg-cache.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7410 magento/devdocs#7404: Feedback on page: /guides/v2.4/ui_comp_guide/components/ui-wysiwyg.html
  src/guides/v2.3/ui_comp_guide/components/ui-wysiwyg.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7423 Update extension compatibility for 2.4.0
  src/_data/mde.yml
  src/_data/vbe.yml
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7427 Update Redis configuration page
  src/guides/v2.4/config-guide/redis/redis-pg-cache.md
Labels: 2.4.x, Progress: approved, Technical

#7424 magento/devdocs#7366: GraphQL: Document password change mutations. Mutation: requestPasswordResetEmail.
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/images/reset-password-email.png
  src/guides/v2.4/graphql/mutations/request-password-reset-email.md
Labels: 2.4.1, Community, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#7398 Since the sockets php extension becomes required from 2.4.0 onwards, …
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: Progress: approved

#7411 Added release notes for Cloud Patches 1.0.5
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7307 Admin grid tutorial
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/admin-grid.md
  src/guides/v2.4/extension-dev-guide/admin-grid.md
Labels: 2.3.x, New Topic, Progress: approved

#7426 magento/devdocs#7366: GraphQL: Document password change mutations. Mutation: resetPassword.
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/request-password-reset-email.md
  src/guides/v2.4/graphql/mutations/reset-password.md
Labels: 2.4.1, Community, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#7429 Plugins - Fix link to $next
  src/guides/v2.3/extension-dev-guide/plugins.md
Labels: 2.3.x, Editorial, Progress: approved

#7434 Add Edge to supported browsers page
  src/_includes/browsers/supported-browsers-24.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7430 Point REST API reference links to hosted docs
  src/common/images/schema-switcher.png
  src/redoc/2.3/index.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#7405 Magento 2.4.0 Beta Release Note update 0603
  src/_includes/release-notes/engcomm-2-4-0-issues.md
  src/_includes/release-notes/engcomm-2-4-0-partner.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7431 magento/devdocs#7364: Update the storeConfig query to include the new attributes
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.3.x, Community, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#7438 Redirect from old Redoc topics to new hosted docs
  src/redoc/2.3/admin-rest-api.html
  src/redoc/2.3/customer-rest-api.html
  src/redoc/2.3/guest-rest-api.html
Labels: 2.3.x, Internal Dev, Maintenance, Progress: approved

#7425 Added PrivateLink service documentation:
  src/_data/toc/cloud-guide.yml
  src/cloud/bk-cloud.md
  src/cloud/project/privatelink-service.md
  src/common/images/cloud/CloudBenefits.svg
  src/common/images/cloud/cloud-privatelink-architecture-diagram.png
Labels: 2.x, Internal Dev, New Topic, Progress: review

#7439 GraphQL: Break links for files using cart-object.md file
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/mutations/add-downloadable-products.md
  src/guides/v2.4/graphql/mutations/add-simple-products.md
  src/guides/v2.4/graphql/mutations/add-virtual-products.md
  src/guides/v2.4/graphql/mutations/apply-coupon.md
  src/guides/v2.4/graphql/mutations/apply-giftcard.md
  src/guides/v2.4/graphql/mutations/apply-store-credit.md
  src/guides/v2.4/graphql/mutations/handle-payflow-pro-response.md
  src/guides/v2.4/graphql/mutations/merge-carts.md
  src/guides/v2.4/graphql/mutations/remove-coupon.md
  src/guides/v2.4/graphql/mutations/remove-giftcard.md
  src/guides/v2.4/graphql/mutations/remove-item.md
  src/guides/v2.4/graphql/mutations/remove-store-credit.md
  src/guides/v2.4/graphql/mutations/set-guest-email.md
  src/guides/v2.4/graphql/mutations/set-shipping-method.md
  src/guides/v2.4/graphql/mutations/update-cart-items.md
  src/guides/v2.4/graphql/queries/customer-cart.md
Labels: 2.4.1, Community, Internal Dev, Maintenance, Progress: approved

#7440 Update REST table of contents
  src/_data/toc/rest-api.yml
Labels: 2.3.x, Internal Dev, Maintenance, Progress: approved

#7436 GraphQL: Add support for order details in My Orders
  src/_includes/graphql/customer-address-output.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customer-output-24.md
  src/guides/v2.4/graphql/mutations/change-customer-password.md
  src/guides/v2.4/graphql/mutations/create-customer.md
  src/guides/v2.4/graphql/mutations/update-customer.md
  src/guides/v2.4/graphql/queries/customer-orders.md
  src/guides/v2.4/graphql/queries/customer.md
Labels: 2.4.1, Internal Dev, Major Update, Progress: approved

#7449 magento/devdocs#7363: Update the storeConfig query to include new fields
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7445 Remove old data from the What's New page
  src/whats-new.md
Labels: Internal Dev, Maintenance, Progress: approved

#7451 Fix note format
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved, Small Changes

#7450 #7437 Update memory recommendation for PHP
  src/guides/v2.3/performance-best-practices/software.md
Labels: 2.3.x, Progress: approved, Technical

#7447 Cloud packages release June 2020
  src/_data/codebase/cloud/cloud-error-messages.yml
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_data/whats-new.yml
  src/_includes/cloud/backup-db.md
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/_includes/cloud/note-error-message-reference-ece-tools.md
  src/cloud/configure/import-url-rewrites.md
  src/cloud/deploy/static-content-deployment.md
  src/cloud/docker/docker-config-blackfire-io.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-development-testing.md
  src/cloud/docker/docker-development.md
  src/cloud/docker/docker-manage-cron-jobs.md
  src/cloud/docker/docker-manage-database.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-split-db.md
  src/cloud/docker/docker-test-app-mftf.md
  src/cloud/docker/docker-test-magecloud-pkg-code.md
  src/cloud/env/restore-environment.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/env/variables-post-deploy.md
  src/cloud/howtos/debug.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/log-locations.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-conf-files_services.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade.md
  src/cloud/project/project-webint-snap.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/reference/error-codes.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
  src/cloud/trouble/trouble.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7453 Upgrade gems and ruby
  .ruby-version
  Gemfile.lock
Labels: Internal Dev, Maintenance, Progress: approved

#7457 Revert jekyll to 4.1.0
  Gemfile.lock
Labels: Internal Dev, Maintenance, Progress: approved

#7455 Adding information about how to separately install PB with recs
  src/recommendations/install-configure.md
Labels: 2.3.x, Internal Dev, Progress: approved

#7462 Magento-cloud-components: Release 1.0.5
  src/cloud/release-notes/mcc-release-notes.md
Labels: Internal Dev, Progress: approved

#7460 Cloud Release note corrections and yaml format fix
  src/cloud/docker/docker-test-magecloud-pkg-code.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7464 Updates to PrivateLink topic in Cloud Guide
  src/_data/var.yml
  src/cloud/project/privatelink-service.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7461 Magento 2 4 0 Beta Release Note update -- 6/26
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Progress: approved, Small Changes

#7458 added link to graphql web api tests
  src/guides/v2.3/get-started/web-api-functional-testing.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#7471 Wrong path to setShippingAddressesOnCart mutation
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
Labels: 2.3.x, Editorial, Progress: approved

#7473 GraphQL caching: fix header name
  src/guides/v2.3/graphql/caching.md
  src/guides/v2.4/graphql/caching.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved
