Repository magento/devdocs, pull requests merged in 2020-11, with the labels that each got.

#8127 Deleted M1 references from a bunch of places in Marketplace docs
  src/marketplace/sellers/technical-reference.md
  src/marketplace/sellers/technical-review-guidelines.md
Labels: Internal Dev, Progress: approved, Technical, hacktoberfest-accepted

#8160 Layout overview small typo fix
  src/guides/v2.3/frontend-dev-guide/layouts/layout-overview.md
Labels: 2.4.x, Editorial, Progress: approved

#8167 Clarified code sample in UI Registry topic
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiregistry.md
Labels: 2.3.x, 2.4.x, Progress: approved, Small Changes, Technical

#8157 Changed Hardcoded text for Magento Commerce Cloud to Variable
  src/_includes/cloud/error-codes.md
  src/cloud/integrations/gitlab-integration.md
  src/cloud/project/services-mysql.md
  src/cloud/project/user-admin.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/requirements/cloud-requirements.md
  src/community/resources/best-practices.md
  src/guides/v2.3/comp-mgr/patching/mqp.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#8169 Sync 2.4.2-develop
  .github/MAINTAINER_GUIDELINES.md
  src/_data/toc/cloud-guide.yml
  src/_data/toc/marketplace-sellers.yml
  src/cloud/architecture/pro-architecture.md
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/docker/docker-extend.md
  src/cloud/env/environments-start.md
  src/cloud/live/live.md
  src/cloud/project/magento-app-php-ini.md
  src/cloud/project/project-webint-basic.md
  src/cloud/project/sendgrid.md
  src/cloud/project/services-mysql.md
  src/contributor-guide/contributing.md
  src/guides/v2.3/ext-best-practices/tutorials/copy-fieldsets.md
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.3/performance-best-practices/advanced-setup.md
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/performance-best-practices/advanced-setup.md
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
  src/guides/v2.4/security/two-factor-authentication.md
  src/marketplace/sellers/code-sniffer.md
  src/marketplace/sellers/code-validation.md
  src/marketplace/sellers/copy-paste-detector.md
  src/marketplace/sellers/extension-create.md
  src/marketplace/sellers/installation-and-varnish-tests.md
  src/marketplace/sellers/malware-scan.md
  src/marketplace/sellers/packaging-v1x-extensions.md
  src/marketplace/sellers/semantic-version-check.md
  src/marketplace/sellers/submit-for-technical-review.md
  src/marketplace/sellers/technical-reference.md
  src/marketplace/sellers/technical-review-guidelines.md
  src/quality-patches/release-notes.md
  src/recommendations/verify.md
Labels: 2.4.2, Maintenance, Progress: approved

#8152 Update error-codes information with current info
  src/_includes/cloud/error-codes.md
Labels: Internal Dev, Progress: approved, hacktoberfest-accepted

#8154 Issue 7976 widget
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: Progress: approved

#8158 Added Information About Cloud Being Only Production Mode
  src/guides/v2.3/performance-best-practices/configuration.md
  src/guides/v2.4/performance-best-practices/configuration.md
Labels: 2.x, Partner: Vaimo, Progress: on hold, Technical, partners-contribution

#8168 Fix broken link in Cloud Docker documentation
  src/cloud/docker/docker-mode-developer.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#8174 Adding implementation topic for recommendations
  src/_data/toc/product-recommendations.yml
  src/recommendations/implementation.md
  src/recommendations/product-recs.md
Labels: 2.3.x, Internal Dev, Progress: approved

#8121 Fix the topic `mergeCarts` mutation according to PR magento2#30633
  src/guides/v2.4/graphql/mutations/merge-carts.md
Labels: 2.4.2, Community, Event: MageCONF CD 2020, Partner: Atwix, Progress: approved, Technical, hacktoberfest-accepted, partners-contribution

#8125 Adding content about the catalog sync CLI
  src/_data/toc/configuration-guide.yml
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-catalog-sync.md
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-catalog-sync.md
Labels: 2.4.x, Internal Dev, Progress: approved, hacktoberfest-accepted

#8099 Updated Extension guides links to 2.4 release line
  src/marketplace/sellers/extension-create.md
Labels: Editorial, Internal Dev, Progress: approved, hacktoberfest-accepted

#8147 mc38473 remote storage
  src/_data/toc/configuration-guide.yml
  src/common/images/config-remote-storage-schema.png
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage.md
  src/guides/v2.4/install-gde/install/cli/install-cli-install.md
Labels: Internal Dev, Progress: review, hacktoberfest-accepted

#8176 Updating releases notes and image
  src/_data/mde.yml
  src/recommendations/images/filter-tp2.png
  src/recommendations/release-notes.md
Labels: 2.4.x, Internal Dev, Progress: approved

#8161 ECE-Tools 2002.1.3 docs and release notes
  src/_data/var.yml
  src/_includes/cloud/error-codes.md
  src/cloud/env/variables-build.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: review

#8183 MQE-2354: [MFTF SVC] Change "<test> ref change" from MAJOR to a MINOR
  src/guides/v2.4/extension-dev-guide/versioning/mftf-tests-codebase-changes.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8175 Reorganize sys reqs page
  Docfile.yml
  src/_data/toc/installation-guide.yml
  src/_data/whats-new.yml
  src/_includes/install/flow-diagram-24.md
  src/_includes/install/flow-diagram.md
  src/_includes/install/tls-repo_24.md
  src/guides/v2.3/architecture/extensibility.md
  src/guides/v2.3/architecture/tech-stack.md
  src/guides/v2.3/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.3/install-gde/prereq/nginx.md
  src/guides/v2.3/install-gde/prereq/prereq-overview.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.3/install-gde/system-requirements.md
  src/guides/v2.3/install-gde/system-requirements_browsers.md
  src/guides/v2.3/install-gde/system-requirements_repo-tls1-2.md
  src/guides/v2.3/install-gde/system-requirements_tls1-2.md
  src/guides/v2.3/install-gde/trouble/tshoot_access-browser.md
  src/guides/v2.3/migration/migration-plan.md
  src/guides/v2.3/performance-best-practices/software.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
  src/guides/v2.4/architecture/tech-stack.md
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/prereq/nginx.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/install-gde/system-requirements.md
  src/guides/v2.4/install-gde/system-requirements_browsers.md
  src/guides/v2.4/install-gde/system-requirements_repo-tls1-2.md
  src/guides/v2.4/install-gde/system-requirements_tls1-2.md
  src/guides/v2.4/performance-best-practices/software.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
  src/system-requirements.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: approved

#8181 Update What's New for October 14 - November 3
  src/_data/whats-new.yml
Labels: Editorial, Internal Dev, Progress: approved

#8191 Magento 2.3.6 and 2.4.1 Release Note minor update
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
Labels: 2.3.6, 2.4.1, Internal Dev, Progress: approved

#8186 Port changes in two-level-cache article from 2.4
  src/guides/v2.3/config-guide/cache/two-level-cache.md
Labels: 2.3.x, Editorial, Progress: approved

#8184 pass "entity_type_code" instead of "entity_type_id"
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8098 Updated another way of string translation in js
  src/guides/v2.3/frontend-dev-guide/translations/translate_theory.md
Labels: Partner: Ziffity, Progress: approved, Technical, hacktoberfest-accepted, partners-contribution

#8195 Small changes
  src/cloud/project/project-upgrade.md
  src/cloud/trouble/trouble-error-html-minification.md
  src/guides/v2.3/config-guide/cache/two-level-cache.md
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-overview.md
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiregistry.md
  src/guides/v2.4/extension-dev-guide/versioning/mftf-tests-codebase-changes.md
Labels: Internal Dev, Progress: approved

#8172 Gift registry queries
  src/_data/toc/graphql.yml
  src/_includes/graphql/gift-registry-dynamic-interface.md
  src/_includes/graphql/gift-registry.md
  src/guides/v2.4/graphql/queries/gift-registry-types.md
  src/guides/v2.4/graphql/queries/gift-registry.md
Labels: 2.4.2, New Topic, Partner: Zilker Technology, Progress: approved, partners-contribution

#8197 Update Docker command help
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/cloud/docker/docker-quick-reference.md
Labels: 2.x, Internal Dev, Progress: review

#8198 Updates for Cloud Docker 1.2.0 release
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Internal Dev, Progress: review

#8187 Clarify that the default value for the max_allowed_packets setting applies to cloud and on-premises projects
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/prereq/mysql.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Technical

#8097 ISSUE-7986: The topics for the "Company Role" mutations and "isCompanyRoleNameAvailable" query have been created
  src/_data/toc/graphql.yml
  src/_includes/b2b/company/company-acl.md
  src/_includes/graphql/company-role.md
  src/guides/v2.4/graphql/mutations/create-company-role.md
  src/guides/v2.4/graphql/mutations/delete-company-role.md
  src/guides/v2.4/graphql/mutations/update-company-role.md
  src/guides/v2.4/graphql/queries/is-company-role-name-available.md
Labels: 2.4.2, Community, New Topic, Partner: Atwix, Progress: approved, Special achievement, hacktoberfest-accepted, partners-contribution

#8180 Added warning about arguments merge and replace
  src/guides/v2.3/extension-dev-guide/build/di-xml-file.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#8192 fixed incorrect line in di.xml section
  src/guides/v2.3/inventory/source-selection-algorithms.md
Labels: 2.4.2, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#8182 The missed achievement has been added to the contributing page.
  src/_includes/contributor/rewards.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#8200 Update release-notes.md - corrected version number
  src/recommendations/release-notes.md
Labels: Editorial, Partner: Balance Internet, Progress: approved, partners-contribution

#8196 Installation Guide reorganization
  src/_data/main-nav.yml
  src/_data/toc/installation-guide.yml
  src/index.html
Labels: Editorial, Internal Dev, Progress: approved

#8199 Cloud Docker 1.2.0 Release
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-test-app-mftf.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8203 Cloud packages november release
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/_includes/cloud/error-codes.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-test-app-mftf.md
  src/cloud/env/variables-build.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.4.x, Major Update, Progress: approved

#8205 Sync 2.4.2-develop
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/_includes/cloud/error-codes.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-test-app-mftf.md
  src/cloud/env/variables-build.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.4.2, Maintenance, Progress: approved

#8136 Update javascript guide section
  src/guides/v2.3/javascript-dev-guide/javascript/custom_js.md
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_debug.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_mixins.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_practice.md
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical, hacktoberfest-accepted

#8185 Add warning about using psr php extension
  src/_includes/install/php-versions-2.4.md
Labels: 2.4.x, Editorial, Progress: approved

#7702 In-Store Pickup GraphQl intersection products assignments filter.
  src/guides/v2.4/graphql/queries/pickup-locations.md
Labels: 2.4.2, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8209 Adding link to API keys
  src/recommendations/implementation.md
Labels: 2.3.4, Internal Dev, Progress: approved

#8212 Fix note format
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/prereq/mysql.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#8105 Update install-cli-subcommands-admin.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-admin.md
Labels: Editorial, Partner: Pinpoint, Progress: approved, Small Changes, hacktoberfest-accepted, partners-contribution

#8179 Added Purchase Order to comany resource table
  src/_includes/webapi/b2b_roles.md
  src/guides/v2.3/b2b/roles.md
  src/guides/v2.4/b2b/roles.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved

#8207 deleted basics_software.md file and removed the reference for 'What i…
  src/guides/v2.3/install-gde/basics/basics_software.md
  src/guides/v2.3/install-gde/prereq/apache.md
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.3/install-gde/prereq/nginx.md
  src/guides/v2.4/install-gde/basics/basics_software.md
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/prereq/nginx.md
Labels: 2.3.x, 2.4.x, Partner: Zilker Technology, Progress: approved, Site Improvements, partners-contribution

#8210 Update system requirements for 2.4.2
  src/guides/v2.3/config-guide/varnish/config-varnish-final.md
  src/guides/v2.3/config-guide/varnish/config-varnish.md
  src/guides/v2.4/comp-mgr/prereq/prereq-elasticsearch.md
  src/guides/v2.4/comp-mgr/prereq/prereq_compman-checklist.md
  src/guides/v2.4/comp-mgr/prereq/prereq_compman.md
  src/guides/v2.4/config-guide/varnish/config-varnish-advanced.md
  src/guides/v2.4/config-guide/varnish/config-varnish-configure.md
  src/guides/v2.4/install-gde/prereq/elasticsearch.md
  src/guides/v2.4/install-gde/system-requirements.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#8213 Clarification for description for attribute 'template' in 'Layout instructions'
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#8190 [AWS S3] Improvements
  src/_data/toc/configuration-guide.yml
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-migration.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage.md
Labels: Internal Dev, Progress: approved

#8219 Removes references to the archive installer
  src/_includes/install/file-system-perms-oneuser.md
  src/_includes/install/file-system-perms-oneuser_24.md
  src/_includes/install/file-system-perms-twouser.md
  src/_includes/install/file-system-perms-twouser_24.md
  src/_includes/install/flow-diagram-24.md
  src/_includes/install/flow-diagram.md
  src/_includes/php-dev/component-root-2.3.md
  src/_includes/php-dev/component-root.md
  src/common/images/install-diagram-24.svg
  src/guides/v2.3/comp-mgr/bk-compman-upgrade-guide.md
  src/guides/v2.3/config-guide/deployment/single-machine.md
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  src/guides/v2.3/install-gde/bk-install-guide.md
  src/guides/v2.3/install-gde/composer.md
  src/guides/v2.3/install-gde/prereq/nginx.md
  src/guides/v2.3/install-gde/prereq/zip_install.md
  src/guides/v2.3/performance-best-practices/introduction.md
  src/guides/v2.4/comp-mgr/bk-compman-upgrade-guide.md
  src/guides/v2.4/config-guide/deployment/single-machine.md
  src/guides/v2.4/install-gde/bk-install-guide.md
  src/guides/v2.4/install-gde/composer.md
  src/guides/v2.4/install-gde/prereq/nginx.md
  src/guides/v2.4/install-gde/prereq/zip_install.md
Labels: Progress: approved

#8220 MQP Release 1.0.9
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#8170 Issue 7993 documentation for gift registry mutations
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/create-gift-registry.md
  src/guides/v2.4/graphql/mutations/share-gift-registry.md
Labels: 2.4.2, New Topic, Partner: Zilker Technology, Progress: approved, partners-contribution

#8226 Update REST API links
  src/_data/toc/rest-api.yml
  src/redoc/2.3/index.md
Labels: 2.3.6, 2.4.1, Editorial, Internal Dev, Maintenance, Progress: approved

#8216 Updated Cloud Docker container info and clean up markdown
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Internal Dev, Progress: review, Technical

#8227 MQP Release 1.0.10
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#8225 Patch widget_gallery configuration typo
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8228 Fix array attribute
  src/guides/v2.3/graphql/develop/extend-existing-schema.md
Labels: 2.4.x, Editorial, Partner: Gene, Progress: approved, Small Changes, Technical, partners-contribution

#8230 Added REMOTE_STORAGE deploy variable to Cloud Guide
  src/_data/var.yml
  src/cloud/env/variables-deploy.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Internal Dev, Progress: review, Technical

#8217 changed to the right file name
  src/guides/v2.3/frontend-dev-guide/tools/using_grunt.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#8233 Update What's New for Nov 16
  src/_data/whats-new.yml
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved

#8162 Added Note Type & Custom Type definitions
  src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
  src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
Labels: 2.3.x, 2.4.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8235 Adding content about handling cookie restrictions
  src/_data/toc/product-recommendations.yml
  src/recommendations/setting-cookie.md
Labels: 2.4.x, Internal Dev, Progress: approved

#8238 Fix linting in install-guide-refresh integration branch
  src/_includes/install/file-system-perms-oneuser.md
  src/_includes/install/file-system-perms-twouser.md
  src/_includes/install/file-system-perms-twouser_24.md
Labels: Editorial, Internal Dev, Progress: approved

#8242 Fix broken links in the install-guide-refresh integration branch
  src/_includes/install/file-system-perms-twouser.md
  src/_includes/install/file-system-perms-twouser_24.md
Labels: Editorial, Internal Dev, Progress: approved

#8245 Remove space before opening braces in style less code standards
  src/guides/v2.3/coding-standards/code-standard-less.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8231 Issue-6011- Example changed to suit the generated factory's pattern
  src/guides/v2.3/extension-dev-guide/factories.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8206 Issue-7448-added the usage of ModifierPoolDataProvider class
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_data_source.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#8248 MCLOUD-7258: Add missing field to DevDocs for build:custom:compose
  src/cloud/docker/docker-quick-reference.md
Labels: Progress: approved

#8250 MCLOUD-7258: Add missing field to DevDocs for build:custom:compose (#…
  src/cloud/docker/docker-quick-reference.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8252 Add release notes for MQP 1.0.11 release
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#8249 Updates for the ece-tools 2002.1.4 release
  src/_data/var.yml
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8257 Fix downgrade example
  src/cloud/project/services.md
Labels: 2.x, Progress: approved, Technical

#8255 added more information regarding the CSS inheritance
  src/guides/v2.3/frontend-dev-guide/css-guide/css_quick_guide_approach.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8253 Install Guide copy edit and cleanup
  src/_data/toc/installation-guide.yml
  src/_includes/install/composer-overview_24.md
  src/_includes/install/flow-diagram-24.md
  src/guides/v2.4/install-gde/install-flow-diagram.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8223 Issue-7059-Clarifications about filterProcessor when searching with repositories
  src/guides/v2.3/extension-dev-guide/searching-with-repositories.md
  src/guides/v2.4/extension-dev-guide/searching-with-repositories.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Zilker Technology, Progress: approved, Small Changes, partners-contribution

#8046 Reworked GraphQL tutorial
  src/guides/v2.3/graphql/index.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-add-product-to-cart.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-customer.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-payment-method.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-place-order.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-quote-email.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shopping-cart.md
  src/guides/v2.3/graphql/tutorials/checkout/index.md
  src/guides/v2.4/graphql/tutorials/checkout/checkout-shipping-method.md
Labels: 2.3.x, 2.4.x, Major Update, Progress: approved, hacktoberfest-accepted

#8246 7786-Changed the code for afterSave function in adding-attributes.md file
  src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8194 Issue 8189 - L2 caching example change
  src/guides/v2.4/config-guide/cache/two-level-cache.md
Labels: 2.4.x, Partner: Zilker Technology, Progress: changes requested, Technical, partners-contribution

#8193 issue-6383-added disclaimer for the given scenario
  src/guides/v2.3/extension-dev-guide/indexing.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#8266 Clarify summary of .magento.app.yaml file
  src/cloud/reference/discover-deploy.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#8259 Updated composer package versions for 2.4
  src/_includes/install/sampledata/sample-data-rc1-cli-24.md
  src/guides/v2.4/comp-mgr/cli/cli-rc1-samp.md
Labels: 2.4.x, Internal Dev, Progress: approved, Technical

#8271 MQP Release 1.0.12
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#8244 Add BIC description caused by GraphQL compare list coverage
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: Progress: approved

#8218 Issue-2916- Provide more info about file/classes in code snippets to adding-attributes.html
  src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#8278 Update cms-page.md
  src/guides/v2.3/graphql/queries/cms-page.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8282 Fix link
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Something Digital, Progress: approved, partners-contribution

#8232 Added more details to define Graphql schema for better understanding
  src/guides/v2.3/graphql/develop/create-graphqls-file.md
  src/guides/v2.4/graphql/develop/create-graphqls-file.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8263 Clarify note about configuring Fastly with production settings
  src/cloud/cdn/configure-fastly.md
Labels: 2.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8236 MCLOUD-6073: Review "Update the metapackage" devdocs which is confusing merchants and support agents
  src/cloud/project/ece-tools-upgrade-project.md
Labels: Progress: approved, Technical

#8285 Change beta release date for Q1 2021
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: approved

#8286 Clarify instructions for upgrading Magento deployed on Cloud
  src/cloud/project/ece-tools-upgrade-project.md
Labels: 2.x, Progress: approved, Technical
