Repository magento/devdocs, pull requests merged in 2020-10, with the labels that each got.

#7957 What's New updates Sept 15 - Sept 30
  src/_data/whats-new.yml
Labels: 2.x, Editorial

#7956 Magento release calendar updates and introduction to new version support policy
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: approved

#7972 Fix typo in MDVA-28661 version constraint MQP release-notes.md
  src/quality-patches/release-notes.md
Labels: Editorial, Internal Dev, Progress: approved

#7928 DEL: doc section related to enable_lazy_loading_for_images_without_borders
  src/guides/v2.4/frontend-dev-guide/themes/theme-images.md
Labels: 2.4.2, Editorial, Progress: approved

#7962 Magento 2.4.1 and 2.3.6 Pre-release Release Notes
  src/_data/toc/release-notes.yml
  src/_includes/release-notes/engcomm-2-4-1-partner.md
  src/guides/v2.3/release-notes/b2b-release-notes.md
  src/guides/v2.3/release-notes/bk-release-notes.md
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
Labels: 2.4.1, Internal Dev, Progress: approved

#7971 Clean up Configure routes topic in Cloud Guide
  src/cloud/project/project-routes-more-redir.md
  src/cloud/project/routes.md
Labels: 2.x, Editorial, Progress: approved

#7952 Update shielding information per CSM feedback
  src/cloud/cdn/configure-fastly-customize-cache.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7934 MQE-2298: Move and update test BIC document to DevDocs
  src/guides/v2.4/extension-dev-guide/versioning/mftf-tests-codebase-changes.md
Labels: Progress: approved

#7978 Added new TOC entry for new topic
  src/_data/toc/php-developer-guide.yml
Labels: 2.4.x, Progress: approved, Site Improvements

#7944 Updated CRON options for 2.4
  src/_includes/config/setup-cron_2.4_how-to.md
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#7982 Editorial update to clarify Origin Cloaking description
  src/cloud/cdn/cloud-fastly.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7974 Fixed unused script
  src/_includes/layout/footer-scripts.html
Labels: Progress: approved, Site Improvements

#7977 Update XML syntax to change block's template
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.4.x, Progress: approved, Technical

#7983 Performance best practices > Improve the syntax
  src/guides/v2.3/performance-best-practices/advanced-setup.md
  src/guides/v2.4/performance-best-practices/advanced-setup.md
Labels: 2.3.x, 2.4.x, Partner: Le Site, Progress: approved, Technical, partners-contribution

#7995 MCLOUD-6394: Help with running MFTF test generation commands
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-test-app-mftf.md
Labels: Internal Dev, Progress: approved

#7973 Updating compatibility and events tables
  src/_data/mde.yml
  src/recommendations/events.md
Labels: 2.4.x, Internal Dev, Progress: approved

#7929 [Doc] Adding new PHP extensions #155
  src/cloud/docker/docker-extend.md
Labels: Internal Dev, Progress: approved, Technical

#7981 Fix wrong file name > nginx.conf.sample
  src/guides/v2.3/config-guide/secy/secy-cron.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Le Site, Progress: approved, Small Changes, partners-contribution

#7997 Add Visual Studio Code on catalog generation
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-urn.md
Labels: 2.4.x, Editorial, Progress: approved

#7999 Update using-fonts.md
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#8004 Correct media-queries for tablet
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8006 Removed duplicated 'describes'
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shopping-cart.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#7980 ES recommendedation > Removing inconsistencies
  src/guides/v2.4/install-gde/prereq/elasticsearch.md
Labels: 2.4.x, Major Update, Partner: Le Site, Progress: approved, partners-contribution

#7968 Add storageConfig entry to data provider of admin grid doc
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8002 Release info for ASC 4.3.0
  src/_data/mde.yml
  src/extensions/amazon-sales/release-notes/index.md
Labels: Channels, Progress: approved

#8011 Fix super linter
  .github/workflows/linter.yml
Labels: Maintenance, Progress: approved

#8010 Document the `consumers_wait_for_messages` setting in the `env.php` file
  src/guides/v2.3/config-guide/mq/manage-message-queues.md
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: approved

#8001 GraphQL: Update availableStores query
  src/guides/v2.4/graphql/queries/available-stores.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8009 Update Compatibility table
  src/_data/mde.yml
Labels: 2.4.1, Progress: approved

#7969 Add note related render use magento bindings
  src/guides/v2.3/ui_comp_guide/concepts/magento-bindings.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8007 MCLOUD-6939: Errors occur running magento commands in composer cloud docker installation
  src/cloud/env/variables-build.md
Labels: 2.x, Internal Dev, Progress: review

#8014 Add deprecation notice for magento/url-rewrite-import-export module f…
  src/cloud/configure/import-url-rewrites.md
Labels: 2.x, Event: Distributed CD India 2020, Internal Dev, Progress: approved, Technical

#8008 Improve Apply Patch page
  src/_data/toc/software-update-guide.yml
  src/cloud/project/project-patch.md
  src/guides/v2.3/comp-mgr/patching.md
  src/guides/v2.3/comp-mgr/patching/command-line.md
  src/guides/v2.3/comp-mgr/patching/composer.md
  src/guides/v2.3/comp-mgr/patching/mqp.md
  src/guides/v2.4/comp-mgr/patching/command-line.md
  src/guides/v2.4/comp-mgr/patching/composer.md
  src/guides/v2.4/comp-mgr/patching/mqp.md
  src/quality-patches/release-notes.md
Labels: Progress: approved

#8015 Improve Apply Patch page
  src/_data/toc/software-update-guide.yml
  src/cloud/project/project-patch.md
  src/guides/v2.3/comp-mgr/patching.md
  src/guides/v2.3/comp-mgr/patching/command-line.md
  src/guides/v2.3/comp-mgr/patching/composer.md
  src/guides/v2.3/comp-mgr/patching/mqp.md
  src/guides/v2.4/comp-mgr/patching/command-line.md
  src/guides/v2.4/comp-mgr/patching/composer.md
  src/guides/v2.4/comp-mgr/patching/mqp.md
  src/quality-patches/release-notes.md
Labels: 2.x, Editorial, Progress: approved

#8016 magento/devdocs#: Get Redis version on Cloud environments
  src/cloud/project/services-redis.md
Labels: 2.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#8017 Update What's New
  src/_data/whats-new.yml
Labels: 2.x, Editorial, Progress: approved

#8024 Update cloud-architecture.md
  src/cloud/architecture/cloud-architecture.md
Labels: 2.x, Progress: approved, Technical

#8025 Added link how to use MQP on Magento Commerce Cloud
  src/guides/v2.3/comp-mgr/patching/mqp.md
Labels: 2.x, Editorial, Progress: approved

#7951 Added Static and SemVer tests docs
  src/_data/main-nav.yml
  src/_data/toc/testing.yml
  src/guides/v2.3/test/static/static_test_execution.md
  src/guides/v2.3/test/svc/semver_test_execution.md
  src/guides/v2.4/test/static/static_test_execution.md
  src/guides/v2.4/test/svc/semver_test_execution.md
Labels: 2.3.x, 2.4.x, Internal Dev, New Topic, Progress: approved

#8029 Added link to custom cron reference
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.md
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8018 Improve 'rake whatsnew'
  Rakefile
  src/_data/whats-new.yml
Labels: Maintenance, Progress: approved

#8035 Sync 2.4.1-develop
  .github/workflows/linter.yml
  Rakefile
  src/_data/main-nav.yml
  src/_data/mde.yml
  src/_data/toc/software-update-guide.yml
  src/_data/toc/testing.yml
  src/_data/whats-new.yml
  src/cloud/architecture/cloud-architecture.md
  src/cloud/configure/import-url-rewrites.md
  src/cloud/project/project-patch.md
  src/cloud/project/services-redis.md
  src/extensions/amazon-sales/release-notes/index.md
  src/guides/v2.3/comp-mgr/patching.md
  src/guides/v2.3/comp-mgr/patching/command-line.md
  src/guides/v2.3/comp-mgr/patching/composer.md
  src/guides/v2.3/comp-mgr/patching/mqp.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.md
  src/guides/v2.3/config-guide/mq/manage-message-queues.md
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
  src/guides/v2.3/config-guide/secy/secy-cron.md
  src/guides/v2.3/extension-dev-guide/admin-grid.md
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shopping-cart.md
  src/guides/v2.3/performance-best-practices/advanced-setup.md
  src/guides/v2.3/test/static/static_test_execution.md
  src/guides/v2.3/test/svc/semver_test_execution.md
  src/guides/v2.3/ui_comp_guide/concepts/magento-bindings.md
  src/guides/v2.4/comp-mgr/patching/command-line.md
  src/guides/v2.4/comp-mgr/patching/composer.md
  src/guides/v2.4/comp-mgr/patching/mqp.md
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.md
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-urn.md
  src/guides/v2.4/install-gde/prereq/elasticsearch.md
  src/guides/v2.4/performance-best-practices/advanced-setup.md
  src/guides/v2.4/test/static/static_test_execution.md
  src/guides/v2.4/test/svc/semver_test_execution.md
  src/quality-patches/release-notes.md
  src/recommendations/events.md
Labels: 2.4.1, Maintenance, Progress: approved

#7896 Fix env.php code sample for message queue configuration
  src/guides/v2.3/extension-dev-guide/message-queues/message-queues.md
Labels: 2.3.6, Progress: approved, Technical

#8020 Added example for date column and filter to admin grid guide
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8030 Added validation rules to the system.xml reference
  src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
  src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
Labels: 2.x, Progress: approved, Technical, hacktoberfest-accepted

#7949 GraphQL: Add coverage for create/updateCompany mutations
  src/_data/toc/graphql.yml
  src/_includes/graphql/company.md
  src/_includes/graphql/customer-output-24.md
  src/guides/v2.4/graphql/mutations/create-company.md
  src/guides/v2.4/graphql/mutations/update-company.md
Labels: 2.4.2, Community, Internal Dev, New Topic, Progress: approved

#7984 GraphQL: Add basic B2B company queries
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/queries/check-company-admin-email.md
  src/guides/v2.4/graphql/queries/check-company-email.md
  src/guides/v2.4/graphql/queries/check-company-user-email.md
  src/guides/v2.4/graphql/queries/company.md
Labels: 2.4.2, Community, Internal Dev, New Topic, Progress: approved

#8039 [Cloud] Added link about offloading redirects to Fastly to routes.yaml
  src/cloud/project/project-routes-more-redir.md
Labels: 2.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8000 Update theme-structure.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: Editorial, Partner: Krish TechnoLabs, Progress: approved, Small Changes, partners-contribution

#8026 update using-font for 2.4.2. New parameter font-type for custom fonts
  src/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.md
Labels: Progress: approved

#8032 Fix link format
  src/guides/v2.3/config-guide/prod/config-reference-var-name.md
Labels: 2.x, Editorial, Progress: approved, Small Changes

#8005 Added information about deployer 2.0
  src/contributor-guide/contributing.md
Labels: Progress: review

#8040 MCLOUD-7072: Add CLI command for generating .magento.env.yaml
  src/cloud/project/magento-env-yaml.md
  src/cloud/reference/ece-tools-reference.md
Labels: Major Update, Progress: approved

#8043 Added information about deployer 2.0
  src/contributor-guide/contributing.md
Labels: 2.x, Progress: approved, Technical

#8045 MQP Release 1.0.7
  src/quality-patches/release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8037 Added Cloud Patches 1.0.7 release notes
  src/_data/var.yml
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8047 Update GraphQL release notes
  src/guides/v2.4/graphql/release-notes.md
Labels: 2.4.1, Progress: approved

#8036 Magento 2.4.1 and 2.3.6 Release Notes
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
Labels: Progress: approved

#8048 Cloud Patches release notes v1.0.8
  src/_data/var.yml
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8044 Add note about snapshot best practice
  src/cloud/architecture/pro-architecture.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8055 Updated bin-magento.json data after 2.4.1 release
  src/_data/codebase/v2_4/commerce/bin-magento.json
  src/_data/codebase/v2_4/open-source/bin-magento.json
Labels: 2.4.1, Major Update, Progress: approved

#8056 Update availability page for Q4 2020 release
  src/release/availability.md
Labels: Internal Dev, Maintenance, Progress: review

#8054 Update BIC reference
  src/_includes/backward-incompatible-changes/commerce/2.3.5-2.3.6.md
  src/_includes/backward-incompatible-changes/commerce/2.4.0-2.4.1-develop.html
  src/_includes/backward-incompatible-changes/commerce/2.4.0-2.4.1.md
  src/_includes/backward-incompatible-changes/open-source/2.3.5-2.3.6.html
  src/_includes/backward-incompatible-changes/open-source/2.3.5-2.3.6.md
  src/_includes/backward-incompatible-changes/open-source/2.4.0-2.4.1.html
  src/_includes/backward-incompatible-changes/open-source/2.4.0-2.4.1.md
  src/guides/v2.3/release-notes/backward-incompatible-changes/reference.md
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: 2.3.6, 2.4.1, Automation, Internal Dev, Major Update, Progress: approved

#8031 Added Cloud Configuration Hierarchy
  src/cloud/live/sens-data-over.md
Labels: 2.x, Major Update, Partner: Vaimo, Progress: approved, partners-contribution

#8059 Update elasticsearch.md
  src/guides/v2.4/install-gde/prereq/elasticsearch.md
Labels: 2.4.x, Editorial, Progress: approved

#8062 Magento 2.4.1 Release Notes update
  src/guides/v2.4/release-notes/commerce-2-4-1.md
Labels: 2.4.x, Editorial, Progress: approved

#8065 Update composer dependencies
  src/_data/codebase/v2_3/cloud/composer_lock.json
  src/_data/codebase/v2_3/commerce/composer_lock.json
  src/_data/codebase/v2_3/open-source/composer_lock.json
  src/_data/codebase/v2_4/cloud/composer_lock.json
  src/_data/codebase/v2_4/commerce/composer_lock.json
  src/_data/codebase/v2_4/open-source/composer_lock.json
  src/guides/v2.3/release-notes/packages-cloud.md
Labels: 2.3.6, 2.4.1, Major Update, Progress: approved

#8067 Update bin/magento reference (2.3.6)
  src/_data/codebase/v2_3/commerce/bin-magento.json
  src/_data/codebase/v2_3/open-source/bin-magento.json
Labels: 2.3.6, Major Update, Progress: approved

#8070 change varnish and apache version to supported version
  src/guides/v2.4/config-guide/varnish/config-varnish-advanced.md
  src/guides/v2.4/config-guide/varnish/config-varnish-configure.md
  src/guides/v2.4/config-guide/varnish/config-varnish-install.md
Labels: 2.4.x, Editorial, Progress: on hold

#8028 ISSUE-7987: The GraphQL topic "Company team mutations" has been created
  src/_data/toc/graphql.yml
  src/_includes/graphql/company-team.md
  src/guides/v2.4/graphql/mutations/create-company-team.md
  src/guides/v2.4/graphql/mutations/delete-company-team.md
  src/guides/v2.4/graphql/mutations/update-company-structure.md
  src/guides/v2.4/graphql/mutations/update-company-team.md
Labels: New Topic, Partner: Atwix, Progress: approved, partners-contribution

#8060 Fix DB connection step in MySQLset up topic
  src/cloud/project/services-mysql.md
Labels: 2.x, Editorial, Progress: approved, Small Changes

#8061 Update install-cli-install.md
  src/guides/v2.4/install-gde/install/cli/install-cli-install.md
Labels: Editorial, Progress: approved, Small Changes

#8064 Adds information about securing the Swagger endpoint
  src/guides/v2.3/rest/generate-local.md
  src/guides/v2.4/rest/generate-local.md
Labels: 2.3.x, 2.4.x, Major Update, Progress: approved

#8071 Fix incorrect link
  src/cloud/project/magento-app-php-ini.md
Labels: Editorial, Progress: approved, Small Changes

#8023 update inventory-cli-reference.md incorrect info
  src/guides/v2.3/inventory/inventory-cli-reference.md
Labels: 2.x, Event: Distributed CD India 2020, Partner: Cedcommerce, Progress: approved, Technical, partners-contribution

#8034 Updated Integration test docs with missing annotations
  src/guides/v2.4/test/integration/annotations.md
Labels: 2.4.x, Editorial, Progress: approved

#8072 Clarify unique Fastly credentials per environment
  src/cloud/cdn/configure-fastly.md
Labels: 2.x, Editorial, Progress: approved

#8074 Added missing docblock in example
  src/guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.4, 2.4.x, Editorial, Progress: approved

#8076 fix missing link
  src/guides/v2.3/config-guide/deployment/pipeline/technical-details.md
Labels: Editorial, Progress: approved, Small Changes

#8078 Added requirement about minimum version of ece-tools for MQP
  src/cloud/project/project-patch.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#8080 Moved the else logic before if condition
  src/guides/v2.4/extension-dev-guide/searching-with-repositories.md
Labels: 2.4.x, Progress: approved, Small Changes, Technical

#8081 Fix a typo of bin/magento command line setup:config:set argument/option
  src/guides/v2.3/config-guide/redis/redis-session.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8083 Correct spelling on What's new page
  src/_data/whats-new.yml
Labels: Editorial, Progress: approved, Small Changes

#8082 Fix typo (similiar -> similar)
  src/_data/codebase/v2_4/mrg/b2b/RequisitionList.yml
Labels: 2.4.x, Editorial, Progress: approved

#8084 Update index.md
  src/guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/index.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8075 Add link to KB article for css and js optimization
  src/guides/v2.4/performance-best-practices/configuration.md
Labels: 2.x, Progress: approved, Technical

#8089 Index Status Updated
  src/guides/v2.3/extension-dev-guide/indexing.md
Labels: 2.3.x, 2.4.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8053 Session garbage collection configuration
  src/_includes/config/locate-session.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8090 Magento 2.3.6 and 2.4.1 release note update (GH-30513)
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
Labels: 2.3.6, 2.4.1, Internal Dev, Progress: approved

#8077 Added links and resources for Magento Cloud Docker support
  src/cloud/docker/docker-development.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8094 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Editorial, Progress: approved

#8087 Correct number of Integration environments
  src/cloud/architecture/cloud-architecture.md
  src/cloud/live/stage-prod-live.md
Labels: Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8073 add small block about redis configuration
  src/guides/v2.3/config-guide/redis/config-redis.md
Labels: Major Update, Progress: approved

#8096 Fix code sample
  src/cloud/cdn/fastly-vcl-allowlist.md
Labels: 2.x, Progress: approved, Small Changes, Technical

#8102 Break symlink
  src/guides/v2.4/graphql/mutations/generate-customer-token.md
Labels: Internal Dev, Maintenance, Progress: review

#8100 Removed Magento 1 reference from Create an Extension page; made Packaging an Extension a link to packaging guide
  src/marketplace/sellers/extension-create.md
Labels: Editorial, Progress: approved

#8103 Small changes
  src/_data/codebase/v2_4/mrg/b2b/RequisitionList.yml
  src/_data/whats-new.yml
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/project/project-patch.md
  src/guides/v2.3/config-guide/deployment/pipeline/technical-details.md
  src/guides/v2.3/config-guide/redis/redis-session.md
  src/guides/v2.3/extension-dev-guide/attributes.md
  src/guides/v2.3/extension-dev-guide/indexing.md
  src/guides/v2.3/extension-dev-guide/price-adjustments.md
  src/guides/v2.3/payments-integrations/payment-gateway/command-pool.md
  src/guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/index.md
  src/guides/v2.4/extension-dev-guide/searching-with-repositories.md
  src/guides/v2.4/graphql/mutations/generate-customer-token.md
  src/guides/v2.4/performance-best-practices/configuration.md
  src/guides/v2.4/security/security-txt.md
  src/marketplace/sellers/extension-create.md
Labels: Progress: approved

#8093 added create, rename, delete requisition lists
  src/_data/toc/graphql.yml
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/mutations/create-requisition-list.md
  src/guides/v2.4/graphql/mutations/delete-requisition-list.md
  src/guides/v2.4/graphql/mutations/rename-requisition-list.md
Labels: 2.4.2, Community, New Topic, Partner: Zilker Technology, Progress: approved, partners-contribution

#8101 Updating release notes for 3.0.8
  src/_data/mde.yml
  src/recommendations/release-notes.md
Labels: 2.4.x, Internal Dev, Progress: approved

#8068 Cloud: update key value list for web locations
  src/cloud/project/magento-app-properties.md
Labels: 2.x, Progress: approved, Technical

#8111 Magento Commerce 2.4.1 B2B release note minor update
  src/guides/v2.4/release-notes/b2b-release-notes.md
Labels: 2.4.1, Internal Dev, Progress: approved

#8113 Add Adobe logo
  Gemfile.lock
  _config.yml
  src/_includes/layout/site-nav.html
Labels: Progress: approved, Site Improvements

#8104 ISSUE-7985: The topics for the "Company User" mutations have been cre…
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/create-company-user.md
  src/guides/v2.4/graphql/mutations/delete-company-user.md
  src/guides/v2.4/graphql/mutations/update-company-user.md
Labels: 2.4.2, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#8118 Remove extra bracket
  src/cloud/docker/docker-development.md
Labels: 2.x, Editorial, Event: MageCONF CD 2020, Progress: review, Small Changes

#8120 ISSUE-8117: Company-related query names and attributes have been fixed
  src/_data/toc/graphql.yml
  src/_includes/graphql/company.md
  src/guides/v2.4/graphql/queries/check-company-admin-email.md
  src/guides/v2.4/graphql/queries/check-company-email.md
  src/guides/v2.4/graphql/queries/check-company-user-email.md
  src/guides/v2.4/graphql/queries/is-company-admin-email-available.md
  src/guides/v2.4/graphql/queries/is-company-email-available.md
  src/guides/v2.4/graphql/queries/is-company-user-email-available.md
Labels: 2.4.2, Community, Event: MageCONF CD 2020, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#8115 Added information about using Managed Alerts on Starter projects
  src/cloud/docker/docker-development.md
  src/cloud/project/new-relic.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8123 Fix the topics for `categories` and `categoryList` queries according to PR magento2#30630
  src/_includes/graphql/category-filter-input.md
  src/guides/v2.4/graphql/queries/categories.md
  src/guides/v2.4/graphql/queries/category-list.md
Labels: 2.4.2, Event: MageCONF CD 2020, Partner: Atwix, Progress: approved, Technical, partners-contribution

#8130 Sync 2.4.2-develop
  .github/CONTRIBUTING.md
  Gemfile.lock
  _config.yml
  src/_data/codebase/v2_4/mrg/b2b/RequisitionList.yml
  src/_data/mde.yml
  src/_data/whats-new.yml
  src/_includes/layout/site-nav.html
  src/cloud/architecture/cloud-architecture.md
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/docker/docker-development.md
  src/cloud/live/stage-prod-live.md
  src/cloud/project/magento-app-properties.md
  src/cloud/project/new-relic.md
  src/cloud/project/project-patch.md
  src/guides/v2.3/config-guide/deployment/pipeline/technical-details.md
  src/guides/v2.3/config-guide/redis/config-redis.md
  src/guides/v2.3/config-guide/redis/redis-session.md
  src/guides/v2.3/extension-dev-guide/attributes.md
  src/guides/v2.3/extension-dev-guide/indexing.md
  src/guides/v2.3/extension-dev-guide/price-adjustments.md
  src/guides/v2.3/payments-integrations/payment-gateway/command-pool.md
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.3/ui_comp_guide/components/wysiwyg/add-custom-editor/index.md
  src/guides/v2.4/extension-dev-guide/searching-with-repositories.md
  src/guides/v2.4/graphql/mutations/generate-customer-token.md
  src/guides/v2.4/performance-best-practices/configuration.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
  src/guides/v2.4/security/security-txt.md
  src/marketplace/sellers/extension-create.md
  src/recommendations/release-notes.md
Labels: 2.4.2, Maintenance, Progress: approved

#8063 [AWS S3] MC-38473: Create overview and configuration topic
  src/_data/toc/configuration-guide.yml
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage.md
Labels: Internal Dev, Progress: review

#8128 Recs event collection clarifications
  src/recommendations/verify.md
Labels: Editorial, Progress: approved, Small Changes

#8132 Update MAINTAINER_GUIDELINES.md
  .github/MAINTAINER_GUIDELINES.md
Labels: Editorial, Internal Dev, Progress: approved

#8109 Correct commands for splitting databases
  src/guides/v2.3/performance-best-practices/advanced-setup.md
  src/guides/v2.4/performance-best-practices/advanced-setup.md
Labels: 2.x, Partner: Blue Acorn iCi, Progress: approved, Technical, Technology Partner: Vertex, partners-contribution, tech-partners-contribution

#8112 Magento EQP Documentation update.
  src/_data/toc/marketplace-sellers.yml
  src/marketplace/sellers/code-sniffer.md
  src/marketplace/sellers/code-validation.md
  src/marketplace/sellers/copy-paste-detector.md
  src/marketplace/sellers/extension-create.md
  src/marketplace/sellers/installation-and-varnish-tests.md
  src/marketplace/sellers/malware-scan.md
  src/marketplace/sellers/packaging-v1x-extensions.md
  src/marketplace/sellers/semantic-version-check.md
  src/marketplace/sellers/submit-for-technical-review.md
  src/marketplace/sellers/technical-review-guidelines.md
Labels: Internal Dev, Major Update, Progress: approved

#8095 Update contributing.md
  src/contributor-guide/contributing.md
Labels: 2.x, Partner: Test team, Progress: approved, Technical, partners-contribution

#8133 Magento EQP Documentation update. (#8112)
  src/_data/toc/marketplace-sellers.yml
  src/marketplace/sellers/code-sniffer.md
  src/marketplace/sellers/code-validation.md
  src/marketplace/sellers/copy-paste-detector.md
  src/marketplace/sellers/extension-create.md
  src/marketplace/sellers/installation-and-varnish-tests.md
  src/marketplace/sellers/malware-scan.md
  src/marketplace/sellers/packaging-v1x-extensions.md
  src/marketplace/sellers/semantic-version-check.md
  src/marketplace/sellers/submit-for-technical-review.md
  src/marketplace/sellers/technical-review-guidelines.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8131 Fixed TOC entry for "Custom VCL for allowing requests" topic
  src/_data/toc/cloud-guide.yml
  src/cloud/architecture/pro-architecture.md
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/env/environments-start.md
  src/cloud/live/live.md
  src/cloud/project/project-webint-basic.md
  src/cloud/project/sendgrid.md
Labels: 2.x, Editorial, Progress: approved, Small Changes

#8135 Fix spelling error
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
Labels: Editorial, Progress: approved, Small Changes

#8134 [CLOUD] Updated the missing close tag of shell
  src/cloud/trouble/trouble-error-html-minification.md
Labels: Editorial, Partner: Ziffity, Progress: approved, Small Changes, partners-contribution

#8141 [CLOUD] Removed extra trailing comma from composer.json snippet
  src/cloud/project/project-upgrade.md
Labels: Editorial, Progress: approved

#8143 Remove extra slash
  src/cloud/project/magento-app-php-ini.md
Labels: 2.x, Editorial, Progress: approved

#8142 Specify supported version of Composer (latest 1.x)
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Technical

#8137 Updated MySQL to show setting is deprecated
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/prereq/mysql.md
Labels: 2.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8140 MQP Release 1.0.8
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#8150 Magento 2.3.6 and 2.4.1 release note update
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
Labels: 2.3.4, 2.3.6, Internal Dev, Major Update, Progress: approved

#8144 Update maria db versions on services-mysql.md
  src/cloud/project/services-mysql.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8145 Update Magento Cloud Docker instructions for adding custom PHP extensions
  src/cloud/docker/docker-extend.md
Labels: 2.x, Internal Dev, Progress: approved, Technical, hacktoberfest-accepted

#8153 remove XHR instructions
  src/recommendations/verify.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#8122 magento/devdocs#: Update "Copying fieldsets" documentation
  src/guides/v2.3/ext-best-practices/tutorials/copy-fieldsets.md
Labels: Event: MageCONF CD 2020, Partner: Atwix, Progress: approved, Technical, hacktoberfest-accepted, partners-contribution
