Repository magento/devdocs, pull requests merged in 2020-01, with the labels that each got.

#6184 magento/devdocs#5924: Add clarification to required files in About component file structure page
  src/_includes/php-dev/component-required-files.md
  src/_includes/php-dev/component-root-2.3.md
  src/_includes/php-dev/component-root.md
  src/guides/v2.2/extension-dev-guide/prepare/prepare_file-str.md
  src/guides/v2.3/extension-dev-guide/prepare/prepare_file-str.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#6303 magento/devdocs#: Add link to “Applying patches > Custom patches” from “Apply custom patches”
  src/cloud/project/project-patch.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6307 Fix code example adding validation to form
  src/guides/v2.3/javascript-dev-guide/widgets/widget_password_strength_indicator.md
Labels: 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution, small changes

#6301 Add missing command in cache clean
  src/guides/v2.3/frontend-dev-guide/cache_for_frontdevs.md
Labels: Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6314 Update css-preprocess.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, Progress: acceptance testing, partners-contribution, small changes

#6306 Fix the inheritance of alert widget
  src/guides/v2.3/javascript-dev-guide/widgets/widget_alert.md
Labels: 2.3.x, Partner: Webjump, Progress: acceptance testing, Technical, partners-contribution, small changes

#6318 Fix typo
  src/cloud/project/project-upgrade.md
Labels: Editorial, Partner: ISM eCompany, Progress: approved, partners-contribution, small changes

#6302 Custom layout update with XML and admin
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution, small changes

#6308 customize magento luma or Blank theme fonts
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Progress: changes requested, Technical, partners-contribution, small changes

#6319 Fix typo
  src/cloud/cdn/configure-fastly.md
Labels: Editorial, Partner: ISM eCompany, Progress: approved, partners-contribution, small changes

#6315 Need to modify config.php before running docker:build
  src/cloud/docker/docker-config.md
Labels: Editorial, Partner: Wagento, Progress: approved, partners-contribution, small changes

#6304 Added needed spacing.
  src/guides/v2.3/extension-dev-guide/code-generation.md
Labels: Progress: approved, small changes

#6313 requirejs-config.js path corrected
  src/guides/v2.3/javascript-dev-guide/javascript/js_debug.md
Labels: 2.3.x, Community Insider: Cedcommerce, Progress: approved, community-insider-contribution, small changes

#6195 Udpate MFTF data files
  src/_data/codebase/mftf/action-groups.yml
  src/_data/codebase/mftf/functional-tests.yml
  src/_includes/mftf/functional_data.md
  src/_includes/mftf/mftf_data.md
Labels: Progress: approved, Site improvements, Technical

#6320 Small changes
  src/cloud/cdn/configure-fastly.md
  src/cloud/docker/docker-config.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade.md
  src/guides/v2.3/frontend-dev-guide/cache_for_frontdevs.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.md
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_alert.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_password_strength_indicator.md
Labels: Progress: approved, internal-dev

#6323 Updated versioning message for 2.2.
  src/_includes/layout/page-header.html
Labels: Progress: approved, Site improvements

#6291 Update css quick guide approach
  src/guides/v2.3/frontend-dev-guide/css-guide/css_quick_guide_approach.md
Labels: 2.3.x, Major update, Partner: Ziffity, Progress: changes requested, partners-contribution

#6327 Extra Spacing removed from Template-specific non-inline styles's example block
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6300 corrected the grunt file path for Magento2.3.x
  src/guides/v2.3/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.3.x, Progress: approved, Technical, Waiting for response

#6328 Converted markdown to html
  src/_includes/layout/page-header.html
Labels: Progress: approved

#6330 Small changes
  src/_includes/layout/page-header.html
  src/common/images/cloud_cloud-git-233.png
  src/common/images/cloud_cloud-git_raw.png
  src/guides/v2.3/extension-dev-guide/code-generation.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css_debug.md
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_debug.md
Labels: Progress: approved

#6331 Remove references to unsupported versions of Magento from the Contribution Guide
  src/guides/v2.3/contributor-guide/backward-compatible-development/index.md
Labels: 2.3.x, Editorial, Progress: approved

#6334 magento/devdocs#: Layout instructions. Editorial. Remove a redundant colon char
  src/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.2.x, 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6324 magento/devdocs#6322: Clarify Magento version support for magento/url-rewrite-import-export
  src/cloud/configure/import-url-rewrites.md
Labels: 2.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6283 Cloud Suite release note updates for Cloud components package
  src/_data/toc/cloud-guide.yml
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, New topic, Progress: review, internal-dev

#6335 Removed Empty Lines from the Example Block
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#6169 Updating toc and nav files for mbi api
  src/_data/main-nav.yml
  src/_data/toc/mbi.yml
Labels: 2.3.x, Progress: approved, internal-dev

#6341 Release notes (2.3.4)
  src/_data/toc/release-notes.yml
  src/_includes/release-notes/engcomm-2-3-4-issues.md
  src/_includes/release-notes/engcomm-2-3-4-partner.md
  src/guides/v2.3/release-notes/bk-release-notes.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.x, Progress: approved, internal-dev

#6340 Fix 2.2 and 2.3 links and redirects
  src/_includes/install/flow-diagram.md
  src/_includes/install/trouble/rc_php-version.md
  src/guides/v2.2/coding-standards/technical-vision/webapi.md
  src/guides/v2.2/comp-mgr/updater/update-updater.md
  src/guides/v2.2/config-guide/deployment/pipeline/example/cli.md
  src/guides/v2.2/config-guide/prod/config-reference-var-name.md
  src/guides/v2.2/config-guide/secy/hashing.md
  src/guides/v2.2/contributor-guide/contributors.md
  src/guides/v2.2/extension-dev-guide/cache/partial-caching/database-caching.md
  src/guides/v2.2/extension-dev-guide/xss-protection.md
  src/guides/v2.2/pattern-library/getting-user-input/form_elements/form_elements.md
  src/guides/v2.2/release-notes/release-notes-2-2-10-commerce.md
  src/guides/v2.2/release-notes/release-notes-2-2-10-open-source.md
  src/guides/v2.3/advanced-reporting/overview.md
  src/guides/v2.3/comp-mgr/updater/update-updater.md
  src/guides/v2.3/config-guide/deployment/pipeline/example/cli.md
  src/guides/v2.3/contributor-guide/contributors.md
  src/guides/v2.3/extension-dev-guide/cache/partial-caching.md
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/database-caching.md
  src/guides/v2.3/extension-dev-guide/package/package_mktpl.md
  src/guides/v2.3/extension-dev-guide/xss-protection.md
  src/guides/v2.3/install-gde/install/cli/install-cli-backup.md
  src/guides/v2.3/install-gde/prereq/dev_install.md
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
  src/guides/v2.3/pattern-library/containers/slideouts-modals-overlays/slideouts-modals-overalys.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/whats-new.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical, Tracking, internal-dev

#6338 MAGECLOUD-4953-Update Cloud Guide with link to magento-cloud CLI command reference
  src/cloud/reference/cli-ref-topic.md
Labels: Progress: approved, internal-dev

#6346 revert 2.3.4 GraphQL changes from master
  src/_data/toc/graphql.yml
  src/_includes/graphql/cart-object.md
  src/_includes/graphql/create-customer.md
  src/_includes/graphql/customer-address-input.md
  src/_includes/graphql/customer-address-output.md
  src/_includes/graphql/customer-input.md
  src/_includes/graphql/customer-output.md
  src/guides/v2.3/graphql/caching.md
  src/guides/v2.3/graphql/develop/create-graphqls-file.md
  src/guides/v2.3/graphql/develop/resolvers.md
  src/guides/v2.3/graphql/mutations/create-customer-address.md
  src/guides/v2.3/graphql/mutations/create-payflow-pro-token.md
  src/guides/v2.3/graphql/mutations/create-paypal-express-token.md
  src/guides/v2.3/graphql/mutations/place-order.md
  src/guides/v2.3/graphql/mutations/set-billing-address.md
  src/guides/v2.3/graphql/mutations/set-payment-place-order.md
  src/guides/v2.3/graphql/mutations/set-shipping-address.md
  src/guides/v2.3/graphql/product/category-interface.md
  src/guides/v2.3/graphql/product/product-interface.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.3/graphql/queries/customer-orders.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.3/graphql/queries/products.md
  src/guides/v2.3/graphql/queries/store-config.md
Labels: 2.3.x, Progress: approved, internal-dev

#6348 Magento 2. 3. 4 Release Notes Beta
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.x, Editorial, Progress: approved, internal-dev

#6119 MAGECLOUD-3378 scaled architecture
  src/_data/toc/cloud-guide.yml
  src/cloud/architecture/scaled-architecture.md
  src/cloud/project/log-locations.md
  src/common/images/cloud/scaling-core.png
  src/common/images/cloud/scaling-web.png
Labels: 2.x, New topic, Progress: approved, internal-dev

#6224 Added additional info for each nodes in config.php
  src/guides/v2.3/config-guide/prod/config-reference-configphp.md
Labels: Major update, Partner: Ziffity, Progress: approved, partners-contribution

#6350 MC-29776 Adding PHPStan info
  src/guides/v2.3/test/testing.md
Labels: 2.3.3, Major update, Progress: approved

#6349 Revert changes made in 6346
  src/_data/toc/graphql.yml
  src/_includes/graphql/cart-object.md
  src/_includes/graphql/create-customer.md
  src/_includes/graphql/customer-address-input.md
  src/_includes/graphql/customer-address-output.md
  src/_includes/graphql/customer-input.md
  src/_includes/graphql/customer-output.md
  src/guides/v2.3/graphql/caching.md
  src/guides/v2.3/graphql/develop/create-graphqls-file.md
  src/guides/v2.3/graphql/develop/resolvers.md
  src/guides/v2.3/graphql/mutations/create-customer-address.md
  src/guides/v2.3/graphql/mutations/create-payflow-pro-token.md
  src/guides/v2.3/graphql/mutations/create-paypal-express-token.md
  src/guides/v2.3/graphql/mutations/place-order.md
  src/guides/v2.3/graphql/mutations/set-billing-address.md
  src/guides/v2.3/graphql/mutations/set-payment-place-order.md
  src/guides/v2.3/graphql/mutations/set-shipping-address.md
  src/guides/v2.3/graphql/product/category-interface.md
  src/guides/v2.3/graphql/product/product-interface.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.3/graphql/queries/customer-orders.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.3/graphql/queries/products.md
  src/guides/v2.3/graphql/queries/store-config.md
Labels: 2.3.4, Progress: approved, Technical, internal-dev

#6352 Mae fix queue consumers command name
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-maint.md
Labels: 2.3.x, Editorial, Progress: approved, internal-dev

#6357 magento/devdocs#: Logging in to a Magento server. Editorial. Remove a redundant colon char.
  src/guides/v2.3/install-gde/basics/basics_login.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6326 Fix links
  src/guides/v2.3/architecture/archi_perspectives/components/modules/mod_and_areas.md
Labels: 2.3.x, Partner: ISM eCompany, Progress: approved, partners-contribution, small changes

#6297 Clarify flag in robots.txt
  common/images/cloud_project-robots-indexing-by-search-engine.png
  src/cloud/trouble/robots-sitemap.md
Labels: Partner: Webjump, Progress: approved, Technical, partners-contribution, small changes

#6354 Update REST schemas for 2.3.4
  src/redoc/2.3/admin-schema.json
  src/redoc/2.3/async-admin-schema.json
  src/redoc/2.3/async-customer-schema.json
  src/redoc/2.3/async-guest-schema.json
  src/redoc/2.3/customer-schema.json
  src/redoc/2.3/guest-schema.json
Labels: 2.3.4, Major update, Progress: approved, internal-dev

#6336 Made changes suits for 2.3 in template hints
  src/common/images/fdg_debug_theme_23.png
  src/guides/v2.3/frontend-dev-guide/themes/debug-theme.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6362 Added missing bin in cli commands
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-naming-guidelines.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6355 Update the documentation for the Range UI component
  src/guides/v2.3/ui_comp_guide/components/ui-range.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#6351 magento/devdocs#6337: Editorial. Replace mdash HTML special char.
  src/_includes/install/file-system-perms-before.md
  src/_includes/install/file-system-perms-before_22.md
  src/_includes/install/file-system-umask-over.md
  src/_includes/install/install-roadmap.md
  src/cloud/before/before-workspace-ssh.md
  src/cloud/live/live-prot.md
  src/guides/v2.3/coding-standards/code-standard-jquery-widgets.md
  src/guides/v2.3/comp-mgr/extens-man/extensman-main-pg.md
  src/guides/v2.3/config-guide/cache.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-perf-data.md
  src/guides/v2.3/config-guide/config/config-files.md
  src/guides/v2.3/config-guide/config/config-php.md
  src/guides/v2.3/config-guide/cron/custom-cron-ref.md
  src/guides/v2.3/config-guide/deployment/index.md
  src/guides/v2.3/config-guide/log/log-magento.md
  src/guides/v2.3/config-guide/varnish/use-varnish-cache-how.md
  src/guides/v2.3/extension-dev-guide/build/module-load-order.md
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/database-caching.md
  src/guides/v2.3/extension-dev-guide/intro/intro-composer-gloss.md
  src/guides/v2.3/extension-dev-guide/proxies.md
  src/guides/v2.3/install-gde/basics/basics_os-version.md
  src/guides/v2.3/install-gde/bk-install-guide.md
  src/guides/v2.3/install-gde/continue-to-verify.md
  src/guides/v2.3/install-gde/install-roadmap_cli.md
  src/guides/v2.3/install-gde/install-roadmap_part1.md
  src/guides/v2.3/install-gde/install-roadmap_trouble.md
  src/guides/v2.3/install-gde/install-roadmap_web.md
  src/guides/v2.3/install-gde/install/post-install-config.md
  src/guides/v2.3/install-gde/prereq/apache.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md
  src/guides/v2.3/payments-integrations/payment-gateway/error-code-mapper.md
  src/marketplace/eqp/v1/users.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6365 Updated ece-tools 2002.1.0 release notes
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/ece-release-notes.md
Labels: Progress: review, internal-dev

#6339 Cache clean and DI compile commands added
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6342 Update on Reference a container section
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, partners-contribution

#6358 Adding additional info related to layout body attributes
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6353 Cloud pro account level for scaled architecture
  src/cloud/architecture/pro-architecture.md
  src/cloud/architecture/scaled-architecture.md
Labels: Progress: approved, Technical, internal-dev

#6361 Strengthening the deprecation warning via MC-30263
  src/guides/v2.3/mtf/mtf_introduction.md
Labels: 2.3.2, Editorial

#6344 Update the install extension link
  src/guides/v2.3/comp-mgr/marketplace/marketplace.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-install.md
Labels: 2.3.x, Editorial, Partner: Mediotype, Progress: approved, partners-contribution

#6366 Updated Cloud Guide to add latest info for RabbitMQ version support
  src/cloud/project/project-conf-files_services.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6371 MAGECLOUD-4738: Document All Backward-incompatible Changes in ECE-Tools 2002.1.0
  src/cloud/release-notes/backward-incompatible-changes.md
Labels: Progress: approved, internal-dev

#6370 magento/devdocs#6356: UI Element code block is not rendering correctly
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uielement_concept.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6374 Update go-live-checklist.md
  src/cloud/live/go-live-checklist.md
Labels: Editorial, Progress: approved, small changes

#6372 Added an example to "Set body attributes" section
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6367 Remove New Relic and Blackfire section
  src/cloud/project/new-relic.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6375 Small changes
  src/cloud/configure/import-url-rewrites.md
  src/cloud/live/go-live-checklist.md
  src/cloud/reference/cli-ref-topic.md
  src/cloud/trouble/robots-sitemap.md
  src/common/images/cloud/cloud_project-robots-indexing-by-search-engine.png
  src/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/architecture/archi_perspectives/components/modules/mod_and_areas.md
  src/guides/v2.3/comp-mgr/marketplace/marketplace.md
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-naming-guidelines.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-install.md
  src/guides/v2.3/install-gde/basics/basics_login.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-maint.md
  src/guides/v2.3/mtf/mtf_introduction.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uielement_concept.md
Labels: Progress: approved

#6369 MAGECLOUD-4736: Document Changes to Magento-Cloud-Patches
  src/_data/toc/cloud-guide.yml
  src/cloud/project/project-patch.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Major update, Progress: approved, internal-dev

#6376 Fix link syntax
  src/cloud/cdn/configure-fastly.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6378 MAGECLOUD-4738: Document All Backward-incompatible Changes in ECE-Tools 2002.1.0
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Major update, Progress: review, internal-dev

#6382 Update adding-attributes.md
  src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: Editorial, Progress: approved, small changes

#6385 Magento 2 3 4 Release Notes -- prerelease
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: Progress: approved

#6363 Updates and Revisions to the Cloud Docker Documentation
  src/_data/toc/cloud-guide.yml
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development.md
  src/cloud/docker/docker-syncing-data.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Major update, Partner: Zilker Technology, Progress: approved, partners-contribution

#6312 Inventory (msi) blob url variable added and all urls updated
  src/guides/v2.3/inventory/inventory-api-reference.md
Labels: 2.3.x, Community Insider: Cedcommerce, Progress: approved, community-insider-contribution

#6389 Fix invalid command to install, improve formatting
  src/extensions/b2b/index.md
Labels: 2.3.x, Editorial, Partner: Space 48, Progress: approved, partners-contribution

#6391 Docker release: Elasticsearch health check
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Progress: review, Technical, internal-dev

#6392 Docker update RabbitMQ v3.8 support
  src/cloud/docker/docker-containers.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Progress: review, Technical, internal-dev

#6390 Fix remaining redirect conflicts
  src/cloud/cdn/configure-fastly.md
  src/guides/v2.2/architecture/frontend_custom_strategies.md
  src/guides/v2.2/install-gde/system-requirements.md
  src/guides/v2.3/architecture/frontend_custom_strategies.md
  src/guides/v2.3/install-gde/system-requirements.md
Labels: Progress: approved, Site improvements

#6379 GraphQL: Add grouped product example
  src/guides/v2.3/graphql/mutations/add-simple-products.md
Labels: 2.3.4, Community, Progress: approved, Technical, internal-dev

#6401 MAGECLOUD-4040: Added docs for using MFTF in Cloud Docker environment
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-database.md
  src/cloud/docker/docker-development-testing.md
  src/cloud/docker/docker-mftf.md
  src/cloud/live/stage-prod-test.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Major update, Progress: review, internal-dev

#6407 Added module status command in manage installed modules guide
  src/guides/v2.3/config-guide/config/config-php.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#6402 Issue #6325 Change command which has to be used to configure a lock
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-lock.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6397 Update placement-and-design.md minor typo issue
  src/guides/v2.3/ext-best-practices/admin/placement-and-design.md
Labels: 2.3.x, Editorial, Progress: approved

#6410 Update Cloud Documentation for MBI
  src/cloud/architecture/cloud-architecture.md
Labels: 2.3.x, Progress: approved, internal-dev

#6386 Fixing external 404s.
  src/_includes/contributor/labels.md
  src/cloud/docker/docker-config.md
  src/cloud/live/go-live-checklist.md
  src/cloud/live/stage-prod-test.md
  src/guides/v2.3/coding-standards/docblock-standard-general.md
  src/guides/v2.3/config-guide/varnish/config-varnish-configure.md
  src/guides/v2.3/contributor-guide/templates/basic_template.md
  src/guides/v2.3/design-styleguide/iconography/iconography.md
  src/guides/v2.3/extension-dev-guide/plugins.md
  src/guides/v2.3/frontend-dev-guide/templates/template-email-migration.md
  src/guides/v2.3/inventory/inventory-api-reference.md
  src/guides/v2.3/inventory/source-selection-algorithms.md
  src/guides/v2.3/mtf/mtf_quickstart/mtf_quickstart_environment.md
  src/guides/v2.3/mtf/troubleshooting.md
  src/guides/v2.3/pattern-library/graphics/iconography/iconography.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  src/guides/v2.3/ui_comp_guide/components/ui-linkcolumn.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uilayout_concept.md
Labels: Editorial, Progress: approved

#6405 Added MariaDB BIC warning
  src/cloud/project/project-conf-files_services-mysql.md
Labels: 2.3.x, Editorial, Progress: approved

#6415 Fixes class name in CLI command code sample
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.3.x, Progress: approved, Technical

#6404 Clarify how theme inheritance works
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.3.x, Editorial, Progress: approved

#6223 Added additional php doc blocks with examples
  src/guides/v2.3/coding-standards/docblock-standard-general.md
Labels: 2.2.x, 2.3.x, Major update, Partner: Ziffity, Progress: approved, partners-contribution

#6416 Small changes
  src/cloud/cdn/configure-fastly.md
  src/cloud/project/project-conf-files_services-mysql.md
  src/guides/v2.3/config-guide/config/config-php.md
  src/guides/v2.3/ext-best-practices/admin/placement-and-design.md
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
  src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-lock.md
Labels: Progress: approved

#6395 magento/devdocs#: Extend “Customize the 503 error page” topic name
  src/_data/toc/cloud-guide.yml
  src/cloud/cdn/cloud-fastly-custom-response.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6380 remove double quote to make code perfect usable
  src/guides/v2.3/ui_comp_guide/concepts/knockout-bindings.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#6387 Added wrappers for notices
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Editorial, Partner: ISM eCompany, Progress: approved, partners-contribution

#6424 Update on include an external CSS code
  src/guides/v2.3/frontend-dev-guide/css-topics/css-themes.md
Labels: 2.3.x, Editorial, Progress: approved

#6423 Added a point for Theme development best practices
  src/guides/v2.3/frontend-dev-guide/theme-best-practice.md
Labels: Progress: approved

#6425 Update project-conf-files_services-mysql.md
  src/cloud/project/project-conf-files_services-mysql.md
Labels: 2.x, Progress: approved, Technical

#6421 magento/devdocs#: Add deletePaymentToken mutation API errors
  src/guides/v2.3/graphql/mutations/delete-payment-token.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6417 Message Queues: various text edits
  src/guides/v2.3/extension-dev-guide/message-queues/bulk-operations.md
  src/guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  src/guides/v2.3/extension-dev-guide/message-queues/implement-bulk.md
Labels: Progress: approved, Technology Partner: dotdigital, small changes, tech-partners-contribution

#6426 Add info about Magento Cloud Docker mount configuration
  src/cloud/docker/docker-containers.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Progress: review, internal-dev

#6432 Update code reference to view_model
  src/guides/v2.3/extension-dev-guide/view-models.md
Labels: 2.3.x, Progress: approved, Technical

#6435 TLS and Varnish updates
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Progress: approved, internal-dev

#6431 Updates to Magento Cloud Docker CLI commands
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Major update, Progress: approved, internal-dev

#6438 Magento Release Notes 2 3 4 penultimate review copy
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: Progress: approved

#6428 magento/devdocs#: Restore missed PR about CRON options
  src/_includes/config/setup-cron_2.3_how-to.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6408 Added Specify Docker Build Sources section to Extending Docker Page
  src/cloud/docker/docker-extend.md
Labels: 2.x, Major update, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#6347 adding information the find information about sendgrid
  src/cloud/project/sendgrid.md
Labels: Editorial, Partner: Webjump, Progress: approved, partners-contribution, small changes

#6433 Improving the custom cron documentation
  src/guides/v2.3/config-guide/cron/custom-cron-tut.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6427 Magento 2.2.11 Release Notes
  src/_data/toc/release-notes.yml
  src/guides/v2.2/release-notes/bk-release-notes.md
  src/guides/v2.2/release-notes/release-notes-2-2-11-commerce.md
  src/guides/v2.2/release-notes/release-notes-2-2-11-open-source.md
Labels: 2.2.x, Progress: approved, internal-dev

#6442 config-varnish-magento.md Minor changes.
  src/guides/v2.3/config-guide/varnish/config-varnish-magento.md
Labels: 2.3.x, Editorial, Progress: review, small changes

#6441 Update docker-config.md
  src/cloud/docker/docker-config.md
Labels: Editorial, Partner: Rave Digital, Progress: approved, partners-contribution, small changes

#6445 Added release items for PHP-FPM container
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6444 config-varnish-advanced.md Minor Change
  src/guides/v2.3/config-guide/varnish/config-varnish-advanced.md
Labels: 2.3.x, Editorial, Progress: approved

#6399 magento/devdocs#: Add createBraintreeClientToken mutation API error
  src/guides/v2.3/graphql/mutations/create-braintree-client-token.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6446 Fix tables in inventory-api-reference.md
  src/guides/v2.3/inventory/inventory-api-reference.md
Labels: 2.3.x, Editorial, Progress: approved

#6418 Add VBE installation instructions and info about independent releases
  src/_data/toc/extensions.yml
  src/extensions/vendor/amazon-pay/install.md
  src/extensions/vendor/dotdigital/install.md
  src/extensions/vendor/klarna/install.md
  src/extensions/vendor/vendor.md
  src/extensions/vendor/vertex/install.md
  src/extensions/vendor/yotpo/install.md
Labels: Progress: approved, internal-dev

#6451 Providing a list of allowed tags that can be used as HtmlTag on containers
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6450 Removed duplicated known issue section in release notes v2.3.3
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
Labels: Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6447 magento/devdocs#: Add generateCustomerToken mutation API errors
  src/guides/v2.3/graphql/mutations/generate-customer-token.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution, small changes

#6429 Add global "Commerce-only" designation to Page Builder content
  _config.yml
Labels: Progress: approved, Site improvements, internal-dev, small changes

#6449 Providing a new section with all the available UiComponents that can be used in Listing Component
  src/guides/v2.3/ui_comp_guide/components/ui-listing-grid.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6419 Fixed broken link
  src/guides/v2.3/design-styleguide/iconography/iconography.md
Labels: Editorial, Progress: approved

#6455 Small changes
  _config.yml
  src/cloud/docker/docker-config.md
  src/cloud/project/project-conf-files_services-mysql.md
  src/cloud/project/sendgrid.md
  src/guides/v2.3/config-guide/varnish/config-varnish-advanced.md
  src/guides/v2.3/config-guide/varnish/config-varnish-magento.md
  src/guides/v2.3/design-styleguide/iconography/iconography.md
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  src/guides/v2.3/extension-dev-guide/message-queues/bulk-operations.md
  src/guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  src/guides/v2.3/extension-dev-guide/message-queues/implement-bulk.md
  src/guides/v2.3/extension-dev-guide/view-models.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-themes.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/frontend-dev-guide/theme-best-practice.md
  src/guides/v2.3/graphql/mutations/create-braintree-client-token.md
  src/guides/v2.3/graphql/mutations/delete-payment-token.md
  src/guides/v2.3/graphql/mutations/generate-customer-token.md
  src/guides/v2.3/inventory/inventory-api-reference.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  src/guides/v2.3/ui_comp_guide/concepts/knockout-bindings.md
Labels: Progress: approved

#6456 Magento 2.3.4 Release Notes
  src/guides/v2.3/release-notes/bk-release-notes.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: Progress: approved, internal-dev

#6409 Update GraphQL release notes for 2.3.4
  src/guides/v2.3/graphql/release-notes.md
Labels: Progress: approved

#6457 Change PHP-FPM to FPM which is the container name in command line and…
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Technical, internal-dev

#6468 GraphQL: Custom sort attributes
  src/guides/v2.3/graphql/queries/products.md
Labels: 2.3.4, Progress: approved, Technical, internal-dev

#6469 Add details about PHP 7.1 support
  src/_includes/install/php-versions-template.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.4, Progress: approved, Technical

#6470 Applied changes from code review
  src/_includes/config/setup-cron_2.3_how-to.md
  src/guides/v2.2/release-notes/release-notes-2-2-11-commerce.md
  src/guides/v2.2/release-notes/release-notes-2-2-11-open-source.md
Labels: Editorial, Progress: approved, internal-dev

#6471 Fixed a formatting issue in 2.2.11 release notes
  src/guides/v2.2/release-notes/release-notes-2-2-11-commerce.md
Labels: 2.2.x, Editorial, Progress: approved, internal-dev

#6466 Q1 2020 Commerce & Open Source release (2.3.4, 2.3.3-p1, and 2.2.11)
  src/_data/toc/graphql.yml
  src/_data/toc/release-notes.yml
  src/_includes/config/setup-cron_2.3_how-to.md
  src/_includes/graphql/cart-object.md
  src/_includes/graphql/create-customer.md
  src/_includes/graphql/customer-address-input.md
  src/_includes/graphql/customer-address-output.md
  src/_includes/graphql/customer-input.md
  src/_includes/graphql/customer-output.md
  src/_includes/install/php-versions-template.md
  src/_includes/release-notes/engcomm-2-3-4-issues.md
  src/_includes/release-notes/engcomm-2-3-4-partner.md
  src/guides/v2.2/release-notes/bk-release-notes.md
  src/guides/v2.2/release-notes/release-notes-2-2-11-commerce.md
  src/guides/v2.2/release-notes/release-notes-2-2-11-open-source.md
  src/guides/v2.3/graphql/caching.md
  src/guides/v2.3/graphql/develop/create-graphqls-file.md
  src/guides/v2.3/graphql/develop/resolvers.md
  src/guides/v2.3/graphql/mutations/add-simple-products.md
  src/guides/v2.3/graphql/mutations/create-customer-address.md
  src/guides/v2.3/graphql/mutations/create-payflow-pro-token.md
  src/guides/v2.3/graphql/mutations/create-paypal-express-token.md
  src/guides/v2.3/graphql/mutations/place-order.md
  src/guides/v2.3/graphql/mutations/set-billing-address.md
  src/guides/v2.3/graphql/mutations/set-payment-place-order.md
  src/guides/v2.3/graphql/mutations/set-shipping-address.md
  src/guides/v2.3/graphql/product/category-interface.md
  src/guides/v2.3/graphql/product/product-interface.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.3/graphql/queries/customer-orders.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.3/graphql/queries/products.md
  src/guides/v2.3/graphql/queries/store-config.md
  src/guides/v2.3/graphql/release-notes.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.3/release-notes/bk-release-notes.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
  src/redoc/2.3/admin-schema.json
  src/redoc/2.3/async-admin-schema.json
  src/redoc/2.3/async-customer-schema.json
  src/redoc/2.3/async-guest-schema.json
  src/redoc/2.3/customer-schema.json
  src/redoc/2.3/guest-schema.json
Labels: 2.2.x, 2.3.x, Major update, Progress: approved, internal-dev

#6461 magento/devdocs#: GraphQl. API functional tests. Add info about tests location
  src/guides/v2.3/graphql/functional-testing.md
Labels: 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution, small changes

#6473 magento/devdocs#: Editorial. GraphQl. Fix mutation query.
  src/guides/v2.3/graphql/mutations/remove-item.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6472 magento/devdocs#: Add removeItemFromCart mutation API errors
  src/guides/v2.3/graphql/mutations/remove-item.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6460 magento/devdocs#: Add placeOrder mutation API errors
  src/guides/v2.3/graphql/mutations/place-order.md
Labels: 2.3.x, Partner: Atwix, Progress: review, Technical, partners-contribution

#6396 Add the example of using the childDefaults property of uiCollection UI component
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uicollection_concept.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#6463 GH issue 6436 Clarify some points for scaled architecture
  src/cloud/architecture/scaled-architecture.md
Labels: Editorial, Progress: approved, internal-dev, small changes

#6476 magento/devdocs#: Layout instructions. Editorial. Remove a redundant …
  src/guides/v2.3/mtf/features/reporting.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6454 Added additional step in custom widget topic
  src/guides/v2.3/ext-best-practices/tutorials/custom-widget.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6393 magento/devdocs#: Best Practices. Observer. Extend a list of observer areas.
  src/guides/v2.3/ext-best-practices/extension-coding/observers-bp.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6459 Update an example to Include CSS section
  src/guides/v2.3/frontend-dev-guide/css-topics/css-themes.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6485 GraphQL: Provide roadmap information
  src/guides/v2.3/graphql/index.md
  src/guides/v2.3/graphql/release-notes.md
Labels: 2.3.4, Major update, Progress: approved, internal-dev

#6486 Update composer.lock for 2.3.4
  src/_data/codebase/v2_3/cloud/composer_lock.json
  src/_data/codebase/v2_3/commerce/composer_lock.json
  src/_data/codebase/v2_3/open-source/composer_lock.json
Labels: 2.3.4, Progress: approved, Site improvements

#6488 Update customAttributeMetadata query example
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
Labels: 2.3.x, Progress: review, Technical, internal-dev

#6484 Update backward incompatible changes docs after the 2.3.4 release
  src/_includes/backward-incompatible-changes/commerce/2.3.3-2.3.4.md
  src/_includes/backward-incompatible-changes/open-source/2.3.3-2.3.4.md
  src/guides/v2.3/release-notes/backward-incompatible-changes/reference.md
Labels: 2.3.4, Major update, Progress: approved, internal-dev

#6483 Updating backward incompatible changes after the Magento 2.2.11 release
  src/_includes/backward-incompatible-changes/commerce/2.2.10-2.2.11.md
  src/_includes/backward-incompatible-changes/open-source/2.2.10-2.2.11.md
  src/guides/v2.2/release-notes/backward-incompatible-changes/reference.md
Labels: 2.2.11, Major update, Progress: approved, internal-dev

#6420 MAGECLOUD-4996: Document backwards incompatible changes related to Cloud Docker with ECE-Tools 2002.1.0
  src/cloud/release-notes/backward-incompatible-changes.md
Labels: 2.x, Major update, Progress: approved, internal-dev

#6490 Updated composer_lock data after 2.3.4 release
  src/_data/codebase/v2_2/cloud/composer_lock.json
  src/_data/codebase/v2_2/commerce/composer_lock.json
  src/_data/codebase/v2_2/open-source/composer_lock.json
  src/_data/codebase/v2_3/cloud/composer_lock.json
  src/_data/codebase/v2_3/commerce/composer_lock.json
  src/_data/codebase/v2_3/open-source/composer_lock.json
Labels: 2.2.11, 2.3.4, Progress: approved, Technical, internal-dev

#6493 Fixes for Docker 1.0.0 topics
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Editorial, Progress: review, internal-dev

#6491 Update Magento CLI reference data after 2.3.4 release
  src/_data/codebase/v2_3/commerce/bin-magento.json
  src/_data/codebase/v2_3/open-source/bin-magento.json
Labels: 2.3.4, Major update, Progress: approved, internal-dev

#6474 Updated What's New on January 27, 2020
  src/_data/whats-new.yml
  src/guides/v2.2/release-notes/ReleaseNotes2.2.2EE.md
Labels: 2.x, Editorial, Progress: review, internal-dev

#6492 Updated Page Builder build branch from 1.1-develop to develop
  Docfile.yml
Labels: 2.3.4, Progress: approved

#6481 Added instructions for running composer using docker
  src/cloud/docker/docker-config.md
Labels: 2.x, Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#6437 Added `consumers-wait-for-messages` option
  src/_includes/config/message-queue-consumers.md
Labels: 2.3.4, Progress: approved, Technical, internal-dev

#6505 MAGECLOUD-4672: Connection to DB doesn't work
  src/cloud/docker/docker-manage-database.md
Labels: Progress: approved

#6506 Update the Magento CLI reference data (2.2.11)
  src/_data/codebase/v2_2/commerce/bin-magento.json
  src/_data/codebase/v2_2/commerce/bin-magento.yml
  src/_data/codebase/v2_2/open-source/bin-magento.json
  src/_data/codebase/v2_2/open-source/bin-magento.yml
Labels: 2.2.11, Major update, Progress: approved, internal-dev

#6503 Update private-content.md
  src/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
Labels: 2.3.4, Progress: approved, Technical

#6508 MAGECLOUD-4080: Update default example in magento-vars.php
  src/cloud/project/project-multi-sites.md
Labels: 2.x, Progress: approved, internal-dev

#6495 Updated What's New for the 2.3.4 release
  src/_data/whats-new.yml
Labels: 2.3.4, Editorial, Progress: approved, internal-dev
