Repository magento/devdocs, pull requests merged in 2020-05, with the labels that each got.

#7111 Specific layout information for product id and SKU
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#7140 Correct info about headless deployment and Fastly use
  src/cloud/cdn/cloud-fastly.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7144 Update the magento-cloud reference data (1.32.2)
  src/_data/codebase/cloud/magento-cloud.json
  src/_data/codebase/cloud/magento-cloud.yml
Labels: 2.x, Automation, Major Update, Progress: approved

#7124 magento/devdocs#: Add sendEmailToFriend mutation API errors
  src/guides/v2.3/graphql/mutations/send-email-to-friend.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7148 magento/devdocs#7051: Add note about recommendation to put site in main mode and disable cron
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#7146 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.0, Automation, Progress: approved, Technical

#7135 magento/devdocs#: Cloud. Upgrade Magento to 2.3.5
  src/cloud/project/project-upgrade.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7143 Adding major version bump steps
  src/recommendations/install-configure.md
Labels: 2.3.x, Editorial, Progress: approved

#7075 Add Documentation about severity and priority of Issues/PRs
  src/guides/v2.3/contributor-guide/contributing.md
Labels: Progress: approved

#7125 Added description for system attribute option
  src/guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.x, Progress: approved, Technical

#7152 Update create-cache-type.md
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
Labels: 2.3.x, Editorial, Progress: approved

#7138 Added ui tab example
  src/common/images/ui_comps/ui-tab-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-tab.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7128 Instruction not feasible
  src/guides/v2.3/config-guide/cron/custom-cron-tut.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#7149 SELinux + Magento 2.3.5 also needs generated
  src/guides/v2.3/install-gde/prereq/security.md
Labels: Progress: approved, Technical

#7096 command arguments added for migration command syntax
  src/guides/v2.3/migration/migration-migrate-delta.md
  src/guides/v2.3/migration/migration-migrate-settings.md
  src/guides/v2.3/migration/migration-migrate.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7154 Added known issue for Amazon Pay in Magento 2.3.5
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.5, Internal Dev, Major Update, Progress: approved

#7160 Fix incorrect docker-compose command
  src/cloud/docker/docker-containers.md
Labels: Internal Dev, Progress: approved, Small Changes

#7145 Add MySQL warning to Software Update Guide topics
  src/_data/toc/software-update-guide.yml
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/comp-mgr/prereq/prereq-elasticsearch.md
  src/guides/v2.4/comp-mgr/prereq/prereq_compman.md
  src/guides/v2.4/comp-mgr/trouble/current-search-engine.md
  src/guides/v2.4/comp-mgr/trouble/tshoot.md
Labels: 2.4.0, Internal Dev, New Topic, Progress: approved

#7150 GraphQL: Updated the undateCustomerAddress syntax
  src/guides/v2.3/graphql/mutations/update-customer-address.md
Labels: 2.3.x, Editorial, Progress: approved

#7155 Whatsnew for May 4th
  src/_data/whats-new.yml
Labels: 2.3.x, Editorial, Progress: approved

#7139 Use of view models section updated
  src/guides/v2.3/extension-dev-guide/view-models.md
Labels: 2.3.x, Major Update, Partner: Ziffity, Progress: approved, partners-contribution

#7161 Add example usage
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Editorial, Progress: approved

#7165 Spectrum redesign
  Gemfile.lock
  src/_data/toc/b2b-developer-guide.yml
  src/_data/toc/graphql.yml
  src/_data/toc/how-do-i.yml
  src/_data/toc/rest-api.yml
  src/_includes/home/contributors.html
  src/_includes/home/intro.html
  src/_includes/layout/breadcrumbs.html
  src/_includes/layout/footer-scripts.html
  src/_includes/layout/main-nav-item.html
  src/_includes/layout/nav-item.html
  src/_includes/layout/navigation.html
  src/_includes/layout/page-header.html
  src/_includes/layout/page-info.html
  src/_includes/layout/searchform.html
  src/_includes/layout/sidebar.html
  src/_includes/layout/site-nav.html
  src/_includes/layout/version-switcher.html
  src/_layouts/tutorial.html
  src/assets/i/home-bg.jpg
  src/common/css/devdocs.css
  src/common/js/last-modified-at.js
  src/guides/v2.3/rest/tutorials/inventory/configure-environment.md
  src/guides/v2.3/rest/tutorials/inventory/create-stock.md
  src/i/icons/api.svg
  src/i/icons/backend.svg
  src/i/icons/clock.svg
  src/i/icons/community.svg
  src/i/icons/ee-only.svg
  src/i/icons/external.svg
  src/i/icons/fix.svg
  src/i/icons/frontend.svg
  src/i/icons/install.svg
  src/i/icons/new.svg
  src/i/icons/release.svg
  src/i/icons/rss.svg
  src/i/icons/time.svg
  src/i/icons/tutorial.svg
  src/i/loader.svg
  src/index.html
  src/whats-new.md
Labels: Progress: approved

#7159 Add instructions for using a custom VCL snippet to bypass Fastly
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/cloud-fastly-prereqs-custom-vcl.md
  src/cloud/cdn/fastly-vcl-badreferer.md
  src/cloud/cdn/fastly-vcl-blocking.md
  src/cloud/cdn/fastly-vcl-bypass-to-origin.md
  src/cloud/cdn/fastly-vcl-whitelist.md
  src/cloud/cdn/fastly-vcl-wordpress.md
  src/cloud/cdn/trouble-fastly.md
  src/common/images/cloud/cloud-fastly-create-bypass-snippet.png
Labels: Internal Dev, New Topic, Progress: approved

#7167 Bump the theme to fix mobile issue on some devices
  Gemfile.lock
Labels: Progress: approved

#7163 Fix incorrect indent tree show less file in doc
  src/guides/v2.3/frontend-dev-guide/css-guide/css_quick_guide_approach.md
Labels: 2.3.x, Editorial, Progress: approved, Small Changes

#7166 Update infrastructure (rake, bundle)
  Rakefile
  bin/htmlproofer
  rakelib/check.rake
  rakelib/test.rake
Labels: Maintenance, Progress: approved

#7141 Add newly introduced field(EE only) in config guide - Synchronize with Catalog
  src/guides/v2.3/config-guide/prod/config-reference-most.md
Labels: Progress: approved

#7172 Fix emdashes in table
  src/cloud/project/project-conf-files_services.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes, Technical

#7153 Update project-conf-files_services.md
  src/cloud/project/project-conf-files_services.md
Labels: Internal Dev, Progress: approved, Technical

#7184 Add contributors and maintainers link to home page
  src/index.html
Labels: Internal Dev, Progress: approved, Small Changes

#7177 Update composer.json link URL
  src/guides/v2.3/extension-dev-guide/build/module-load-order.md
Labels: Progress: approved, partners-contribution

#7179 Added Most common used Breakpoints
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_mobile.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Progress: approved, Technical, partners-contribution

#7178 Update rwd_overview.md
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_overview.md
Labels: Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#7185 Fix incorrect command description in Magento Cloud CLI Quick reference
  src/cloud/reference/cli-ref-topic.md
Labels: Partner: Wagento, Progress: approved, Small Changes, Technical, partners-contribution

#7157 Updated command to get environment related to issue #7156
  src/cloud/reference/cli-ref-topic.md
Labels: Partner: Wagento, Progress: approved, Technical, partners-contribution

#7193 Release notes and compatibility updates for ASC 4.1.0
  src/_data/mde.yml
  src/extensions/amazon-sales/release-notes/index.md
  src/release/index.md
Labels: Channels, Major Update, Progress: approved

#7187 magento/devdocs#7182: Fix links on page
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#7173 Updated the customer query intro by adding Wishlist as part of customer response
  src/guides/v2.3/graphql/queries/customer.md
Labels: 2.3.x, Editorial, Progress: approved

#7200 Added fields related to bulk operations config guide per as 2.3.5 Commerce Edition.
  src/guides/v2.3/config-guide/prod/config-reference-most.md
Labels: 2.3.4, Editorial, Progress: approved, Small Changes

#7197 Fix format on version support table
  src/cloud/project/project-conf-files_services.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7202 magento/devdocs#: Editorial. Fix RWD CSS file names
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#7181 CommandAbstract should be AbstractCommand
  src/guides/v2.3/extension-dev-guide/depend-inj.md
Labels: 2.3.x, Editorial, Progress: approved, partners-contribution

#7180 when we used Breakpoint 'screen__xl' also added in 'style-l.css'
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Progress: approved, Technical, partners-contribution

#7186 Correct .magento.app.yaml description for "name" property
  src/cloud/project/project-conf-files_magento-app.md
Labels: 2.x, Internal Dev, Progress: approved, Small Changes, Technical

#7199 Update Cloud Guide to reflect Azure IaaS support
  src/cloud/architecture/pro-architecture.md
  src/cloud/bk-cloud.md
  src/cloud/cdn/configure-fastly.md
  src/common/images/cloud/CloudStack.png
  src/common/images/cloud/CloudStack.svg
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7196 MCLOUD-5956: Cloud rewrite import notice
  src/cloud/configure/import-url-rewrites.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7194 Add docs for REDIS_BACKEND deploy variable
  src/cloud/env/variables-deploy.md
Labels: 2.x, Internal Dev, Progress: changes requested, Technical

#7195 Added Cloud Patches 1.0.4 release notes
  src/cloud/project/project-patch.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7198 Clarify doc points per project
  src/_includes/contributor/rewards.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#7201 Updated the config reference by adding fields for 2.3 Open Source Edition
  src/guides/v2.3/config-guide/prod/config-reference-most.md
Labels: 2.3.x, Progress: approved, Technical

#7205 Removed Component Health Index from 2.4
  src/_data/toc/release-notes.yml
  src/guides/v2.4/release-notes/component-status.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved, Tracking

#7151 Adding errors section for addBundleProductsToCart mutation
  src/guides/v2.3/graphql/mutations/add-bundle-products.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7171 Correct Manage disk space section
  src/cloud/project/manage-disk-space.md
Labels: Internal Dev, Progress: review, Technical

#7209 Remove unneeded image file
  src/common/images/cloud/CloudStack.png
Labels: Automation, Internal Dev, Progress: approved

#7210 MC-34147: Prepare Composer update plugin docs for GA
  src/guides/v2.3/comp-mgr/cli/upgrade-with-plugin.md
  src/guides/v2.4/comp-mgr/cli/upgrade-with-plugin.md
Labels: 2.3.x, 2.4.0, Internal Dev, Progress: approved, Technical, Tracking

#7213 Add deprecation notice about the Web Setup Wizard
  src/_includes/install/composer-overview.md
  src/_includes/install/file-system-perms-before.md
  src/_includes/install/file-system-perms-before_22.md
  src/_includes/install/flow-diagram.md
  src/_includes/install/get-software_zip.md
  src/_includes/install/tls-repo.md
  src/_includes/install/web/deprecated.md
  src/_includes/layout/page-header.html
  src/cloud/before/before-setup-env-install.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-install.md
  src/guides/v2.3/install-gde/bk-install-guide.md
  src/guides/v2.3/install-gde/composer.md
  src/guides/v2.3/install-gde/continue-to-install.md
  src/guides/v2.3/install-gde/install-quick-ref.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-db-upgr.md
  src/guides/v2.3/install-gde/install/web/install-web-sample-data-clone.md
  src/guides/v2.3/install-gde/install/web/install-web-sample-data-composer.md
  src/guides/v2.3/install-gde/trouble/tshoot_install_depend.md
  src/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.md
  src/guides/v2.3/performance-best-practices/hardware.md
Labels: 2.3.x, Internal Dev, Major Update, Progress: approved, Tracking

#7208 Update terminology to match Cloud UI interfaces
  src/_data/toc/cloud-guide.yml
  src/_data/whats-new.yml
  src/cloud/architecture/pro-develop-deploy-workflow.md
  src/cloud/basic-information/starter-architecture.md
  src/cloud/basic-information/starter-develop-deploy-workflow.md
  src/cloud/before/before-workspace.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/docker/docker-development.md
  src/cloud/env/environments-start.md
  src/cloud/live/launch-steps.md
  src/cloud/live/live.md
  src/cloud/live/site-launch-checklist.md
  src/cloud/live/stage-prod-live.md
  src/cloud/onboarding/onboarding-portal.md
  src/cloud/project/project-upgrade.md
  src/cloud/project/projects.md
  src/cloud/reference/discover-deploy.md
  src/cloud/requirements/cloud-requirements.md
  src/cloud/setup/first-time-setup.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7147 MCLOUD-3180 update the Configuration management topic
  src/cloud/cdn/trouble-fastly.md
  src/cloud/live/sens-data-initial.md
  src/cloud/live/sens-data-over.md
  src/cloud/reference/discover-deploy.md
  src/cloud/release-notes/cloud-release-archive.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7216 Update Cloud manage disk space
  src/cloud/project/manage-disk-space.md
Labels: Internal Dev, Progress: approved, Technical

#7220 Update supported versions of Varnish
  src/guides/v2.3/config-guide/varnish/config-varnish.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#7222 Update supported versions of Varnish on 2.4
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7218 Whatsnew update for week of May 11
  Rakefile
  src/_data/whats-new.yml
Labels: Progress: approved

#7217 Update create_component.md
  src/guides/v2.3/extension-dev-guide/build/create_component.md
Labels: Partner: Basecom, Progress: approved, partners-contribution

#7226 small fix Yaml formatting
  src/cloud/configure/setup-cron-jobs.md
Labels: 2.3.x, Editorial, Partner: Wagento, Progress: approved, Small Changes, partners-contribution

#7207 GraphQL: Deprecate attribute_id
  src/guides/v2.4/graphql/product/configurable-product.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7206 Clarify scope of Component Status page
  src/guides/v2.3/release-notes/component-status.md
Labels: 2.3.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7191 Fixed noNamespaceSchemaLocation declarations for csp_whitelist.xsd
  src/guides/v2.3/extension-dev-guide/security/content-security-policies.md
Labels: 2.3.x, Progress: approved, Technical

#7225 Fix incorrect "Include CSS" example
  src/guides/v2.3/frontend-dev-guide/css-topics/css-themes.md
Labels: Progress: approved, Technical

#7233 Cache clean cmd added in bundling js guide
  src/guides/v2.3/frontend-dev-guide/themes/js-bundling.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7215 composer install --no-dev > skip installing packages listed in requir…
  src/guides/v2.3/performance-best-practices/deployment-flow.md
Labels: Progress: approved

#7234 Small changes
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-conf-files_services.md
  src/guides/v2.3/config-guide/prod/config-reference-most.md
  src/guides/v2.3/extension-dev-guide/depend-inj.md
  src/guides/v2.3/extension-dev-guide/security/content-security-policies.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-themes.md
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.md
  src/guides/v2.3/frontend-dev-guide/themes/js-bundling.md
  src/guides/v2.3/release-notes/component-status.md
Labels: 2.3.5, Editorial, Progress: approved, Site Improvements

#7190 Adding new version of existing service - Magento Cloud Docker
  src/cloud/docker/docker-extend.md
Labels: Internal Dev, Partner: Zilker Technology, Progress: approved, Waiting for Response, partners-contribution

#7232 Revisions to upgrade instructions for 2.4.0
  src/_data/toc/software-update-guide.yml
  src/guides/v2.3/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/comp-mgr/cli/upgrade-with-script.md
Labels: 2.3.x, 2.4.0, Internal Dev, Major Update, Progress: approved

#7235 MC-34181 Update PHPUnit version numbers for 2.4
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/migration/migration-tool-internal-spec.md
  src/guides/v2.4/test/integration/annotations.md
  src/guides/v2.4/test/integration/integration_test_execution.md
  src/guides/v2.4/test/unit/unit_test_execution_cli.md
Labels: 2.4.0, 2.4.x, Progress: approved, Technical

#7227 Fix incorrect path doc ui library
  src/guides/v2.3/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: 2.3.x, Progress: approved, Technical

#7237 GraphQL: Break symlinks for regionid
  src/_includes/graphql/customer-address-input-24.md
  src/_includes/graphql/customer-address-output-24.md
  src/_includes/graphql/customer-input-24.md
  src/_includes/graphql/customer-output-24.md
  src/guides/v2.4/graphql/mutations/create-customer-address.md
  src/guides/v2.4/graphql/mutations/create-customer.md
  src/guides/v2.4/graphql/mutations/update-customer-address.md
  src/guides/v2.4/graphql/mutations/update-customer.md
  src/guides/v2.4/graphql/queries/customer.md
Labels: 2.4.x, Internal Dev, Maintenance, Progress: approved

#7238 Updated Cloud Guide to reflect migration to Dedicated staging environments for all Cloud projects
  src/cloud/architecture/pro-architecture.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/log-locations.md
  src/cloud/project/project-conf-files_services-elastic.md
  src/cloud/project/project-start.md
  src/cloud/project/projects.md
  src/cloud/reference/discover-deploy.md
  src/common/images/cloud/cloud_pro-branch-architecture-wings.png
  src/common/images/cloud/cloud_pro-branch-architecture.png
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7211 Corrected instructions for adding Cloud user access
  src/cloud/onboarding/onboarding-portal.md
  src/cloud/onboarding/onboarding-tasks.md
  src/cloud/project/user-admin.md
  src/common/images/cloud/cloud-login-infrastructure-access.png
  src/common/images/cloud/cloud_account_project.png
  src/common/images/cloud/cloud_project-access.png
  src/common/images/cloud/cloud_project-add-env-user.png
  src/common/images/cloud/cloud_project-add-super-user.png
  src/common/images/cloud/cloud_project-conf-env.png
  src/common/images/cloud/cloud_project-config.png
  src/common/images/cloud/cloud_project-env.png
  src/common/images/cloud/cloud_project-onboarding-ui.png
  src/common/images/cloud/cloud_status.png
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7228 Update Cloud project-conf-files_services-elastic.md
  src/cloud/project/project-conf-files_services-elastic.md
Labels: 2.x, Partner: Le Site, Progress: approved, Technical, partners-contribution

#7249 Add section header for linking to Pro architecture
  src/cloud/architecture/pro-architecture.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7247 GraphQL: Update description of total_count
  src/guides/v2.4/graphql/develop/create-graphqls-file.md
  src/guides/v2.4/graphql/product/category-interface.md
  src/guides/v2.4/graphql/queries/products.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#7241 Fixed link formatting
  src/guides/v2.3/frontend-dev-guide/themes/theme-images.md
Labels: 2.3.x, Editorial, Progress: approved

#7239 GraphQL: Reinstate the region_id attribute in 2.4
  src/_includes/graphql/customer-address-input-24.md
  src/_includes/graphql/customer-address-output-24.md
  src/_includes/graphql/customer-input-24.md
  src/guides/v2.4/graphql/queries/cart.md
Labels: 2.4.x, Internal Dev, Progress: approved, Technical

#7252 Remove unnecessary dots
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.3.x, Editorial, Progress: approved

#7258 GH-7243: Update contributing.md with MerchDocs info
  src/_data/toc/contributor-guide.yml
  src/_includes/contributor/rewards.md
Labels: 2.3.x, Community, Editorial, Progress: approved

#7221 Adding content about how to customize recommendations using Page Builder
  src/recommendations/customize.md
Labels: 2.3.4, Editorial, Progress: approved

#7259 Magento 2.3.5 Release Note May 20 hotfix update
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.5, Progress: approved

#7256 magento/devdocs#: Add updateCustomer mutation API errors
  src/guides/v2.3/graphql/mutations/update-customer.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7254 Removed bcmath Magento Commerce notice
  src/guides/v2.3/install-gde/prereq/php-settings.md
Labels: 2.3.x, Editorial, Progress: approved

#7262 2fa updates
  src/guides/v2.3/security/two-factor-authentication.md
Labels: 2.4.0, Major Update, Progress: approved

#7265 New userguide index and link
  Gemfile.lock
  src/_includes/layout/header-scripts.html
  src/common/css/devdocs.css
Labels: Progress: approved

#7263 Make Cloud region reference generic in Cloud stack diagram
  src/common/images/cloud/cloud_stack-diagram.png
Labels: 2.x, Internal Dev, Progress: approved, Small Changes, Technical

#7253 Fixes list numbering in "Uninstall modules" page
  src/guides/v2.3/install-gde/install/cli/install-cli-uninstall-mods.md
Labels: 2.3.x, Progress: approved

#7224 Added field information of module InventoryDistanceBasedSourceSelection
  src/guides/v2.3/config-guide/prod/config-reference-most.md
  src/guides/v2.3/config-guide/prod/config-reference-sens.md
Labels: 2.3.5, Progress: approved, Small Changes, Technical

#7268 Fix an incorrcet filename
  src/guides/v2.3/howdoi/checkout/checkout_zip.md
Labels: 2.3.x, Progress: approved

#7264 Update whatsnew
  src/_data/whats-new.yml
Labels: 2.3.x, Internal Dev, Progress: approved

#7176 Magento 2.4.0 requires minimum stable MySQL 5.7.x version
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7267 Update cloud-architecture.md
  src/cloud/architecture/cloud-architecture.md
Labels: 2.x, Editorial, Progress: approved

#7269 G arvind magecloud 155
  src/cloud/docker/docker-extend.md
Labels: Partner: Zilker Technology, Progress: approved, Technical, partners-contribution

#7223 Fixed formatting issue
  src/guides/v2.3/test/unit/writing_testable_code.md
Labels: 2.3.x, Editorial, Progress: approved

#7275 Fix custom logo example
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.3.x, Partner: Aligent Consulting, Progress: approved, Technical, partners-contribution

#7158 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.0, Automation, Progress: approved

#7284 Magento 2.3.5 Release note update -- new link to KB article
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.5, Editorial, Progress: approved

#7286 Update the install diagram
  src/_includes/install/flow-diagram-24.md
  src/common/images/install-diagram-24.png
  src/common/images/install-diagram-24.svg
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7285 Improve Vertex for 2.4.0's changes
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Partner: Mediotype, Progress: approved, Technology Partner: Vertex, partners-contribution, tech-partners-contribution

#7270 Missing underscores in Shipping example
  src/guides/v2.3/config-guide/prod/config-reference-var-name.md
Labels: 2.3.x, Editorial, Progress: approved

#7236 Introduce image lazy loading mechanism
  src/guides/v2.4/frontend-dev-guide/themes/theme-images.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7273 Update config-cli-subcommands-cache.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
Labels: 2.3.x, Editorial, Progress: approved

#7290 Update description of Pro develop and deploy workflow
  src/cloud/architecture/pro-develop-deploy-workflow.md
Labels: 2.3.x, Editorial, Progress: approved, Small Changes

#7282 Add Elasticsearch container config option to Magento Cloud Docker
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7283 MC-32488 MySQL 8 update
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.0, Major Update, Progress: approved

#7255 MC-34097 Update supported PHP version
  src/_data/codebase/v2_4/commerce/composer_lock.json
  src/_data/codebase/v2_4/open-source/composer_lock.json
  src/_includes/install/php-versions-template.md
  src/_includes/install/trouble/rc_php-version.md
  src/guides/v2.3/config-guide/secy/hashing.md
  src/guides/v2.3/install-gde/prereq/apache.md
  src/guides/v2.3/install-gde/prereq/merch_install.md
  src/guides/v2.3/install-gde/prereq/nginx.md
  src/guides/v2.3/install-gde/prereq/php-settings.md
  src/guides/v2.3/install-gde/trouble/tshoot_access-browser.md
  src/guides/v2.4/config-guide/secy/hashing.md
  src/guides/v2.4/install-gde/prereq/php-settings.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/performance-best-practices/software.md
Labels: 2.4.0, Major Update, Progress: approved

#7296 Update whatsnew
  src/_data/whats-new.yml
Labels: 2.3.x, Internal Dev, Progress: approved

#7281 Fix inconsistent recommendations for SKIP_SCD text #7271
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
Labels: 2.x, Progress: approved, Technical

#7295 Backward incompatible changes for 2.4.0 beta
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7294 Add example for using --no-varnish option
  src/cloud/docker/docker-containers-service.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7299 Cleanup obsolete metadata in troubleshooting topics
  src/cloud/trouble/trouble-crypt-key-variable.md
  src/cloud/trouble/trouble-error-html-minification.md
  src/cloud/trouble/trouble-google-analytics-deploy.md
  src/cloud/trouble/trouble_ce-creds.md
  src/cloud/trouble/trouble_proj-startover.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7231 Remove not neccessary anymore queue.xml
  src/guides/v2.3/config-guide/config/config-files.md
  src/guides/v2.3/extension-dev-guide/message-queues/config-mq.md
Labels: 2.3.x, Partner: Comwrap, Progress: approved, partners-contribution

#7279 Add Example command how to run api-functional test
  src/guides/v2.3/get-started/web-api-functional-testing.md
Labels: 2.3.x, Partner: Comwrap, Progress: approved, Technical, partners-contribution

#7303 Add warning about PHP 7.3 to 2.4.0
  src/guides/v2.4/install-gde/prereq/php-settings.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.0, Editorial, Progress: approved

#7302 Add a 2.4.0 beta banner message to 2.4 docs
  src/_includes/layout/page-header.html
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7293 Create CSP docs for 2.4
  src/guides/v2.4/extension-dev-guide/security/content-security-policies.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7305 Remove unused symlink
  src/packages-open-source.md
Labels: Maintenance, Progress: approved

#7292 Add sample dependency injection for modifiers
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.md
Labels: 2.3.x, Partner: Pinpoint, Progress: approved, Technical, partners-contribution

#7304 Adding Product Recommendations to compatibility page
  src/_data/mde.yml
Labels: 2.3.5, Progress: approved

#7301 Magento 2 4 0 Beta Release Notes
  src/_data/toc/release-notes.yml
  src/guides/v2.4/release-notes/bk-release-notes.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7306 Updating whatsnew for 2.4.0-develop
  src/_data/whats-new.yml
Labels: 2.4.0, Progress: approved

#7311 Fix Composer syntax for installing upgrade plugin
  src/guides/v2.3/comp-mgr/cli/upgrade-with-plugin.md
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7313 Sync 2.4.0-develop
  src/_data/mde.yml
  src/_data/whats-new.yml
  src/cloud/architecture/pro-develop-deploy-workflow.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/trouble/trouble-crypt-key-variable.md
  src/cloud/trouble/trouble-error-html-minification.md
  src/cloud/trouble/trouble-google-analytics-deploy.md
  src/cloud/trouble/trouble_ce-creds.md
  src/cloud/trouble/trouble_proj-startover.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cache.md
  src/guides/v2.3/config-guide/config/config-files.md
  src/guides/v2.3/config-guide/prod/config-reference-var-name.md
  src/guides/v2.3/extension-dev-guide/message-queues/config-mq.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/get-started/web-api-functional-testing.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
  src/guides/v2.3/test/unit/writing_testable_code.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  src/packages-open-source.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7316 Add more BIC details about Elasticsearch and MySQL
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7317 Add more BIC detail about PHP and PHPUnit
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7319 Add a banner about Elasticsearch requirements in Install and Upgrade guides
  src/_includes/layout/page-header.html
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7320 fix broken link
  src/guides/v2.4/config-guide/elasticsearch/es-overview.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved
