Repository magento/devdocs, pull requests merged in 2020-07, with the labels that each got.

#7478 magento/devdocs#7363: Add “gift_message” to CustomerOrders query
  src/guides/v2.4/graphql/queries/customer-orders.md
Labels: 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7485 Added anchor links
  src/_data/toc/rest-api.yml
  src/common/images/schema-switcher.png
  src/redoc/2.3/index.md
Labels: 2.3.x, Internal Dev, Maintenance, Progress: approved

#7441 GraphQL: Add gift message attributes to Cart
  src/_includes/graphql/cart-object-24.md
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/mutations/add-downloadable-products.md
  src/guides/v2.4/graphql/mutations/add-simple-products.md
  src/guides/v2.4/graphql/mutations/add-virtual-products.md
  src/guides/v2.4/graphql/mutations/apply-coupon.md
  src/guides/v2.4/graphql/mutations/apply-giftcard.md
  src/guides/v2.4/graphql/mutations/apply-store-credit.md
  src/guides/v2.4/graphql/mutations/handle-payflow-pro-response.md
  src/guides/v2.4/graphql/mutations/merge-carts.md
  src/guides/v2.4/graphql/mutations/remove-coupon.md
  src/guides/v2.4/graphql/mutations/remove-giftcard.md
  src/guides/v2.4/graphql/mutations/remove-item.md
  src/guides/v2.4/graphql/mutations/remove-store-credit.md
  src/guides/v2.4/graphql/mutations/reorder-items.md
  src/guides/v2.4/graphql/mutations/set-billing-address.md
  src/guides/v2.4/graphql/mutations/set-guest-email.md
  src/guides/v2.4/graphql/mutations/set-payment-method.md
  src/guides/v2.4/graphql/mutations/set-shipping-address.md
  src/guides/v2.4/graphql/mutations/set-shipping-method.md
  src/guides/v2.4/graphql/mutations/update-cart-items.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/customer-cart.md
Labels: 2.4.1, Community, Internal Dev, Progress: approved, Technical

#7432 Dead links on the Code Contributions page, updated all 404 pages with correct pages.
  src/guides/v2.3/contributor-guide/contributing.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#7452 Remove Magento 1 content from the project (end of support)
  Docfile.yml
  _config.index.yml
  _config.yml
  rakelib/update.rake
  src/_data/whats-new.yml
  src/_layouts/m1x.html
  src/_layouts/m1x_rest.html
  src/_layouts/m1x_soap.html
Labels: 1.x, Internal Dev, Major Update, Progress: approved

#7465 Upgrade whatsup_github gem
  Gemfile.lock
  rakelib/update.rake
Labels: Maintenance, Progress: approved

#7482 Added backticks to parameter name
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-store.md
Labels: 2.3.x, Progress: approved

#7483 Alter the default value of `--consumers-wait-for-messages`
  src/_includes/config/message-queue-consumers.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#7484 Update message-queue-consumers.md
  src/_includes/config/message-queue-consumers.md
Labels: 2.3.x, 2.4.x, Partner: Bounteous, Progress: approved, Technical, partners-contribution

#7422 magento/devdocs#7366: GraphQl. subscribeEmailToNewsletter. Mutation for subscribe feature.
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/subscribe-email-to-newsletter.md
Labels: 2.4.1, Community, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#7468 Fix typo hightest
  src/guides/v2.3/frontend-dev-guide/translations/theme_dictionary.md
Labels: Editorial, Partner: creativestyle, Progress: approved, partners-contribution

#7472 Customer Custom Attribute scope added
  src/guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.x, Progress: approved, Technical

#7469 Declaring custom UI component updated
  src/guides/v2.3/ui_comp_guide/howto/new_component_declaration.md
Labels: 2.3.x, Progress: approved, Technical

#7477 Update layout-create.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
Labels: 2.3.x, Progress: approved

#7466 Change override to extend for etc/view.xml
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.3.x, Editorial, Partner: creativestyle, Progress: approved, partners-contribution

#7487 Cloud patch topic code block format
  src/cloud/project/project-patch.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#7492 Corrected format of memory value for PHP.
  src/guides/v2.3/performance-best-practices/software.md
Labels: Editorial, Progress: approved, Small Changes

#7489 Adding heading to Page Builder install section
  src/recommendations/install-configure.md
Labels: 2.3.x, Editorial, Progress: approved

#7467 Remove docs about responsive.js
  src/guides/v2.4/extension-dev-guide/build/module-file-structure.md
  src/guides/v2.4/frontend-dev-guide/responsive-web-design/rwd_js.md
Labels: 2.4.1, Partner: creativestyle, Progress: approved, partners-contribution

#7495 Remove link to Baler config instructions
  src/cloud/env/variables-build.md
Labels: 2.x, Internal Dev, Technical

#7493 Generated backward incompatible changes docs for 2.4.0-develop
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4.0-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4.0-develop.html
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: Automation, Internal Dev, Progress: approved

#7490 What's New changes since June 13
  src/_data/whats-new.yml
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7494 Removed detailed description of configuring Baler on Cloud
  src/cloud/deploy/static-content-deployment.md
  src/cloud/env/variables-build.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7502 Remove redundant page parameters
  src/guides/v2.3/extension-dev-guide/routing.md
  src/guides/v2.4/extension-dev-guide/routing.md
Labels: Progress: approved, Small Changes

#7505 Add 2021 release dates to release info page
  src/release/index.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7507 Fix typo in release calendar
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: approved

#7506 Removed irrelevant info about encryption keys
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-spt-util.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#7499 Adding release notes for product recommendations
  src/_data/toc/product-recommendations.yml
  src/_data/toc/release-notes.yml
  src/recommendations/release-notes.md
Labels: 2.3.x, Internal Dev, Progress: approved

#7509 Small changes
  src/_includes/config/message-queue-consumers.md
  src/cloud/project/project-patch.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-spt-util.md
  src/guides/v2.3/extension-dev-guide/attributes.md
  src/guides/v2.3/extension-dev-guide/routing.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
  src/guides/v2.3/frontend-dev-guide/translations/theme_dictionary.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-store.md
  src/guides/v2.3/performance-best-practices/software.md
  src/guides/v2.3/ui_comp_guide/howto/new_component_declaration.md
  src/guides/v2.4/extension-dev-guide/routing.md
Labels: Progress: approved, Site Improvements

#7508 magento/devdocs#7474: [MASTER] Feedback on page: /guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.html
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, partners-contribution

#7501 Remove unneccessary approach add custom font
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
Labels: Progress: approved, Technical

#7498 Add use cases for web API authentication methods
  src/guides/v2.3/config-guide/config/config-files.md
  src/guides/v2.3/get-started/authentication/gs-authentication-oauth.md
  src/guides/v2.3/get-started/authentication/gs-authentication.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: review

#7511 Update add-simple-products.md
  src/guides/v2.3/graphql/mutations/add-simple-products.md
Labels: Progress: approved, Technical

#7510 Update to Whatsnew since July 6
  src/_data/whats-new.yml
Labels: Editorial, Internal Dev, Progress: approved

#7515 Update message-queues.md
  src/guides/v2.3/extension-dev-guide/message-queues/message-queues.md
Labels: Partner: Comwrap, Progress: approved, Technical, partners-contribution

#7516 Update bulk-operations.md
  src/guides/v2.3/extension-dev-guide/message-queues/bulk-operations.md
Labels: 2.3.x, Partner: Comwrap, Progress: approved, Technical, partners-contribution

#7520 Fix 2020 Q4 pre-release date
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: approved

#7517 Publish Magento Cloud 2FA for SSH beta documentation
  src/_data/toc/cloud-guide.yml
  src/cloud/env/environments-start.md
  src/cloud/live/sens-data-initial.md
  src/cloud/live/sens-data-over.md
  src/cloud/project/project-enable-mfa-project.md
  src/cloud/project/project-webint-basic.md
  src/cloud/project/projects.md
  src/cloud/project/user-admin.md
  src/common/images/cloud-2fa-settings-tfa-recovery-codes.png
  src/common/images/cloud/Cloud_Projects.png
  src/common/images/cloud/cloud-2fa-settings-tfa-app-example.png
  src/common/images/cloud/cloud-2fa-settings-tfa-browser-trust.png
  src/common/images/cloud/cloud-2fa-settings-tfa-manage.png
  src/common/images/cloud/cloud-2fa-settings-tfa-recovery-codes.png
  src/common/images/cloud/cloud-account-settings-manage-2fa-config.png
  src/common/images/cloud/cloud-account-settings-tab.png
  src/common/images/cloud/cloud_account_settings-api-token-app-name.png
  src/common/images/cloud/cloud_account_settings-api-token-created.png
  src/common/images/cloud/cloud_account_settings-create-api-token.png
  src/common/images/cloud/cloud_account_settings-tfa-setup-app-options.png
  src/common/images/cloud/cloud_account_settings-tfa-setup-app.png
  src/common/images/cloud/cloud_account_settings-tfa-setup-steps.png
  src/common/images/cloud_account_settings-enable-tfa.png
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7519 Change redis log level to 4
  src/guides/v2.3/config-guide/redis/redis-session.md
Labels: 2.3.x, Progress: approved, Technical

#7512 Added deprecation notice for Elasticsearch 6
  src/_includes/config/es-elasticsearch-magento.md
  src/_includes/config/es-version-23.md
  src/guides/v2.3/config-guide/elasticsearch/es-downgrade.md
  src/guides/v2.3/config-guide/elasticsearch/es-overview.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.6, Internal Dev, Progress: approved, Technical

#7521 Fixed directory to match module structure
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: 2.3.x, Progress: approved, Technical

#7525 Added 2.4.0-p1 to the 2020 Q4 release schedule
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: approved

#7527 closing tag
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: 2.4.x, Editorial

#7522 update javascript in magento rwd
  src/guides/v2.4/frontend-dev-guide/responsive-web-design/rwd_js.md
Labels: 2.4.x, Progress: approved, Technical

#7523 add content best practice less modular
  src/guides/v2.3/frontend-dev-guide/theme-best-practice.md
Labels: 2.3.x, Progress: approved, Technical

#7532 Update - Simple product add to cart mutation
  src/guides/v2.3/graphql/mutations/add-simple-products.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#7529 Update 2.4 system requirements
  src/guides/v2.4/install-gde/prereq/php-settings.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7530 Updates for Cloud MFA and 2FA content
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/beta-release-content-warning.md
  src/_includes/cloud/cloud-secure-api-token.md
  src/cloud/project/project-enable-mfa-enforcement.md
  src/cloud/project/project-webint-basic.md
  src/cloud/project/user-admin.md
  src/common/images/cloud-2fa-settings-tfa-recovery-codes.png
  src/common/images/cloud/cloud_account_settings-api-token-app-name.png
  src/common/images/cloud_account_settings-enable-tfa.png
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7533 Added link to 2.4.0 REST API reference
  src/_data/toc/rest-api.yml
  src/guides/v2.4/rest/bk-rest.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7536 Break symlinks before replacing instances of the term `shipping method`
  src/_data/toc/graphql.yml
  src/guides/v2.4/config-guide/multi-site/ms_over.md
  src/guides/v2.4/graphql/index.md
  src/guides/v2.4/graphql/mutations/set-shipping-method.md
  src/guides/v2.4/graphql/tutorials/checkout/checkout-shipping-method.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7531 GraphQL: Add OrderAddress data type to Sales schema
  src/_includes/graphql/customer-orders-output.md
Labels: 2.4.1, Internal Dev, Progress: approved, Technical

#7539 Change shipping methods to delivery methods in select cases
  src/guides/v2.4/config-guide/multi-site/ms_over.md
  src/guides/v2.4/config-guide/prod/config-reference-most.md
  src/guides/v2.4/config-guide/prod/config-reference-sens.md
  src/guides/v2.4/graphql/mutations/set-shipping-method.md
  src/guides/v2.4/graphql/tutorials/checkout/checkout-shipping-method.md
  src/guides/v2.4/rest/tutorials/orders/order-config-store.md
Labels: 2.4.0, Community, Editorial, Internal Dev, Progress: approved

#7528 Update BIC reference
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4.0-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4.0-develop.html
Labels: Automation, Progress: approved

#7541 Annotation with correct number of params
  src/guides/v2.4/extension-dev-guide/routing.md
Labels: Progress: approved

#7545 Update Inventory REST tutorial to be ready for In-Store Pickup
  src/_includes/webapi/tutorials/configure-shipping-methods-24.md
  src/guides/v2.3/rest/tutorials/inventory/configure-environment.md
  src/guides/v2.4/rest/tutorials/inventory/assign-source-to-stock.md
  src/guides/v2.4/rest/tutorials/inventory/bulk-transfer-products.md
  src/guides/v2.4/rest/tutorials/inventory/configure-environment.md
  src/guides/v2.4/rest/tutorials/inventory/create-cart-add-products.md
  src/guides/v2.4/rest/tutorials/inventory/create-customer.md
  src/guides/v2.4/rest/tutorials/inventory/create-order.md
  src/guides/v2.4/rest/tutorials/inventory/create-shipment.md
  src/guides/v2.4/rest/tutorials/inventory/create-sources.md
  src/guides/v2.4/rest/tutorials/inventory/prepare-for-checkout.md
  src/guides/v2.4/rest/tutorials/inventory/reassign-products-to-another-source.md
  src/guides/v2.4/rest/tutorials/inventory/run-ssa.md
Labels: 2.4.0, Community, Internal Dev, Major Update, Progress: approved

#7554 Inventory 1.2.0 release notes.
  src/guides/v2.3/inventory/release-notes.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7546 Adding git steps to MFA Enforcement page
  src/cloud/project/project-enable-mfa-enforcement.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7553 Updating release notes for v3.0.3
  src/recommendations/release-notes.md
Labels: 2.3.x, Internal Dev, Progress: approved

#7534 Add note about bundle products to Inventory REST topic
  src/guides/v2.4/rest/modules/inventory/manage-source-items.md
Labels: 2.4.0, Community, Progress: approved, Technical

#7547 callout-tip was added on the code snippet
  src/guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.x, Editorial, Progress: approved

#7550 scalability -> salability
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: 2.4.0, Progress: approved

#7549 fix link formatting in Magento 2.4 backward incompatible changes
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: 2.4.0, Editorial, Progress: approved

#7537 Update 2.3 system requirements
  src/guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#7526 MQE-2142: Magento 2.4.0 MFTF BiC list
  src/_data/codebase/v2_4/mftf/b2b/bic/v1_1_0-1_2_0-develop.yml
  src/_data/codebase/v2_4/mftf/ce/bic/v2_3_0-2_4_0-develop.yml
  src/_data/codebase/v2_4/mftf/ee/bic/v2_3_0-2_4_0-develop.yml
  src/_data/toc/mftf.yml
  src/guides/v2.4/reference/mftf/backward-incompatible-changes.md
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: Internal Dev, Progress: approved

#7563 GraphQL release notes
  src/guides/v2.4/graphql/release-notes.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7555 Create symlink for MSI release notes
  src/_data/mde.yml
  src/guides/v2.3/inventory/release-notes.md
  src/guides/v2.4/inventory/release-notes.md
Labels: Internal Dev, Maintenance, Progress: approved

#7558 Adding additional 2FA on SSH troubleshooting and sample automation script
  src/cloud/project/project-enable-mfa-enforcement.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7569 Remove list of REST endpoints and services
  src/_data/toc/rest-api.yml
  src/_data/whats-new.yml
  src/guides/v2.3/b2b/integrations.md
  src/guides/v2.3/get-started/gs-web-api-request.md
  src/guides/v2.3/rest/generate-local.md
  src/guides/v2.3/rest/list.md
  src/guides/v2.3/rest/rest_endpoints.md
  src/guides/v2.4/rest/list.md
  src/guides/v2.4/rest/rest_endpoints.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Technical

#7574 Break symlinks in files that mention the admin token endpoint
  src/guides/v2.4/get-started/authentication/gs-authentication.md
  src/guides/v2.4/graphql/authorization-tokens.md
  src/guides/v2.4/graphql/queries/index.md
  src/guides/v2.4/rest/generate-local.md
  src/guides/v2.4/rest/tutorials/orders/order-admin-token.md
  src/guides/v2.4/rest/tutorials/prerequisite-tasks/create-admin-token.md
Labels: 2.4.0, Community, Internal Dev, Maintenance, Progress: approved

#7571 MCLOUD-6485: Add validator for braintree variable existence
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-upgrade.md
Labels: Internal Dev, Progress: approved

#7572 Update Magento Cloud CLI reference
  src/_data/codebase/cloud/magento-cloud.json
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7575 Magento 2.4.0 Release Notes -- Beta update
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7576 Update endpoints for creating an admin token
  src/guides/v2.3/graphql/authorization-tokens.md
  src/guides/v2.3/graphql/queries/index.md
  src/guides/v2.4/get-started/authentication/gs-authentication-token.md
  src/guides/v2.4/graphql/authorization-tokens.md
  src/guides/v2.4/graphql/queries/index.md
  src/guides/v2.4/rest/generate-local.md
  src/guides/v2.4/rest/tutorials/orders/order-admin-token.md
  src/guides/v2.4/rest/tutorials/prerequisite-tasks/create-admin-token.md
Labels: 2.4.0, Community, Internal Dev, Major Update, Progress: approved

#7577 Delete obsolete REST files/schemas
  src/redoc/2.3/admin-rest-api.html
  src/redoc/2.3/admin-schema.json
  src/redoc/2.3/customer-rest-api.html
  src/redoc/2.3/customer-schema.json
  src/redoc/2.3/guest-rest-api.html
  src/redoc/2.3/guest-schema.json
Labels: 2.3.x, Internal Dev, Maintenance, Progress: approved

#7573 MCLOUD-6221: Add specific error code in some steps
  src/cloud/reference/error-codes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7565 ASC Release Notes 4.2.0
  src/_data/mde.yml
  src/extensions/amazon-sales/release-notes/index.md
Labels: 2.4.x, Channels, Progress: approved

#7556 Security txt
  src/_data/toc/configuration-guide.yml
  src/guides/v2.4/security/security-txt.md
Labels: 2.4.0, Major Update, Progress: approved

#7581 MCLOUD-6530: Fix an issue with empty error code in the StepException
  src/_includes/cloud/error-codes.md
Labels: Internal Dev, Progress: approved

#7566 Adding B2B release notes
  src/_data/toc/release-notes.yml
  src/guides/v2.4/release-notes/b2b-release-notes.md
Labels: 2.4.0, New Topic, Progress: approved

#7561 Callout what's new
  .gitignore
  src/assets/i/flag.svg
  src/common/css/devdocs.css
  src/index.html
Labels: 2.x, Internal Dev, Progress: approved, Site Improvements

#7579 Adding MFA troubleshooting section
  src/cloud/before/before-workspace-ssh.md
Labels: Internal Dev, Major Update, Progress: approved

#7538 Update privatelink-service.md
  src/cloud/project/privatelink-service.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7552 Extend message queue consumers configuration with new attributes
  src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
Labels: Internal Dev, Progress: approved

#7570 Update composer.json
  src/guides/v2.4/extension-dev-guide/build/composer-integration.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#7584 Cloud Guide MFA and TFA updates
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/enable-ssh.md
  src/cloud/before/before-workspace-ssh.md
  src/cloud/cdn/cloud-fastly.md
  src/cloud/cdn/fastly-vcl-whitelist.md
  src/cloud/cdn/fastly-waf-service.md
  src/cloud/project/project-enable-mfa-enforcement.md
  src/cloud/project/user-admin.md
  src/common/images/cloud/cloud-account-settings-tab.png
  src/common/images/cloud/cloud_account_settings-tfa-setup-app.png
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7583 Simplify inventory REST tutorial
  src/guides/v2.4/rest/tutorials/inventory/assign-source-to-stock.md
  src/guides/v2.4/rest/tutorials/inventory/bulk-transfer-products.md
  src/guides/v2.4/rest/tutorials/inventory/configure-environment.md
  src/guides/v2.4/rest/tutorials/inventory/create-cart-add-products.md
  src/guides/v2.4/rest/tutorials/inventory/create-customer.md
  src/guides/v2.4/rest/tutorials/inventory/create-invoice.md
  src/guides/v2.4/rest/tutorials/inventory/create-order.md
  src/guides/v2.4/rest/tutorials/inventory/create-shipment.md
  src/guides/v2.4/rest/tutorials/inventory/create-sources.md
  src/guides/v2.4/rest/tutorials/inventory/create-stock.md
  src/guides/v2.4/rest/tutorials/inventory/index.md
  src/guides/v2.4/rest/tutorials/inventory/prepare-for-checkout.md
  src/guides/v2.4/rest/tutorials/inventory/reassign-products-to-another-source.md
  src/guides/v2.4/rest/tutorials/inventory/run-ssa.md
Labels: Progress: approved

#7578 Updates for ece-tools error reference
  src/_data/codebase/cloud/cloud-error-messages.yml
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/error-codes.md
  src/cloud/project/log-locations.md
  src/cloud/reference/ece-tools-error-reference.md
  src/cloud/reference/error-codes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7598 Link to MySQL system requirements
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/prereq/mysql.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7596 Add known issue for Inventory 1.2.0 (inventory_cleanup_reservations)
  src/guides/v2.3/inventory/release-notes.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7600 Describe the otp parameter for Google Authenticator 2FA
  src/guides/v2.4/get-started/authentication/gs-authentication-token.md
  src/guides/v2.4/rest/tutorials/orders/order-admin-token.md
  src/guides/v2.4/rest/tutorials/orders/order-intro.md
  src/guides/v2.4/rest/tutorials/prerequisite-tasks/create-admin-token.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7602 Standardize release terminology
  src/_data/toc/release.yml
  src/_data/whats-new.yml
  src/guides/v2.3/comp-mgr/patching.md
  src/guides/v2.3/install-gde/bk-install-guide.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.4/install-gde/bk-install-guide.md
  src/release/availability.md
  src/release/index.md
  src/release/policy/index.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7603 Update database configuration commands for MySQL 8
  src/guides/v2.4/install-gde/prereq/mysql.md
Labels: 2.4.x, Progress: approved, Technical

#7599 Added Magento Cloud Components 1.0.6 release notes
  src/cloud/release-notes/mcc-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7597 Remove 2.4.0 beta banner for GA
  src/_includes/layout/page-header.html
  src/release/availability.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7585 Magento 2.4.0 Release Notes GA
  src/_includes/layout/page-header.html
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
  src/release/availability.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7604 Doc updates for log aggregration and New Relic Logs UI
  src/_data/toc/cloud-guide.yml
  src/cloud/architecture/scaled-architecture.md
  src/cloud/cdn/cloud-fastly.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/log-locations.md
  src/cloud/project/new-relic.md
  src/cloud/project/project-webint-basic.md
  src/cloud/reference/discover-deploy.md
  src/cloud/trouble/trouble.md
  src/common/images/cloud/cloud-new-relic-cdn-logs-dashboard.png
  src/common/images/cloud/cloud-new-relic-fastly-log-attribute-filter.png
  src/common/images/cloud/cloud-new-relic-logs-has-client_ip-fastly.png
  src/common/images/cloud/cloud-new-relic-one-logs-access.png
  src/common/images/cloud/cloud-newrelic-dashboard-basic.png
  src/common/images/cloud/cloud_new-relic-log-query-has-ident.png
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7606 Adding support for 2.4.0
  src/recommendations/release-notes.md
Labels: 2.4.x, Internal Dev, Progress: approved

#7608 Updated composer_lock data after 2.4.0 release
  src/_data/codebase/v2_4/cloud/composer_lock.json
  src/_data/codebase/v2_4/commerce/composer_lock.json
  src/_data/codebase/v2_4/open-source/composer_lock.json
Labels: 2.4.0, Automation, Major Update, Progress: approved

#7609 Add link to new Inventory docs in release notes
  src/guides/v2.3/inventory/release-notes.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7612 Add reference documentation for `bin/magento` commands
  src/_data/codebase/v2_4/commerce/bin-magento.json
  src/_data/codebase/v2_4/open-source/bin-magento.json
  src/guides/v2.4/reference/cli/magento-commerce.md
  src/guides/v2.4/reference/cli/magento.md
Labels: 2.4.0, Automation, Internal Dev, Major Update, Progress: approved

#7591 Versionless Contribution Guide
  .github/CONTRIBUTING.md
  .github/MAINTAINER_GUIDELINES.md
  _config.yml
  src/_data/main-nav.yml
  src/_data/toc/contributor-guide.yml
  src/_data/whats-new.yml
  src/_includes/reference/cli-template.md
  src/contributor-guide/backward-compatible-development/index.md
  src/contributor-guide/contributing.md
  src/contributor-guide/contributing_docs_suggested.md
  src/contributor-guide/contributing_dod.md
  src/contributor-guide/contributors.md
  src/contributor-guide/img/maintainers-sneak-peek.jpg
  src/contributor-guide/maintainers.md
  src/contributor-guide/templates/basic_template.md
  src/contributor-guide/templates/tutorial-template-first.md
  src/contributor-guide/templates/tutorial-template-last.md
  src/contributor-guide/templates/tutorial-template-middle.md
  src/guides/v2.3/coding-standards/docblock-standard-general.md
  src/guides/v2.3/ext-best-practices/extension-coding/working-with-arch-bp.md
  src/guides/v2.3/extension-dev-guide/api-concepts.md
  src/guides/v2.3/extension-dev-guide/service-contracts/service-contracts.md
  src/guides/v2.3/extension-dev-guide/validate/validate.md
  src/guides/v2.3/extension-dev-guide/versioning/index.md
  src/guides/v2.3/extension-dev-guide/view-models.md
  src/guides/v2.3/index.html
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.3/test/testing.md
  src/guides/v2.4/contributor-guide/backward-compatible-development/index.md
  src/guides/v2.4/contributor-guide/contributing.md
  src/guides/v2.4/contributor-guide/contributing_docs_suggested.md
  src/guides/v2.4/contributor-guide/contributing_dod.md
  src/guides/v2.4/contributor-guide/contributors.md
  src/guides/v2.4/contributor-guide/img/maintainers-sneak-peek.jpg
  src/guides/v2.4/contributor-guide/maintainers.md
  src/guides/v2.4/contributor-guide/templates/basic_template.md
  src/guides/v2.4/contributor-guide/templates/tutorial-template-first.md
  src/guides/v2.4/contributor-guide/templates/tutorial-template-last.md
  src/guides/v2.4/contributor-guide/templates/tutorial-template-middle.md
  src/index.html
Labels: Internal Dev, Progress: approved, Site Improvements

#7613 Magento 2.4.0 Release Note Highlights Update
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7614 Updates for New Relic Logs documentation
  src/cloud/architecture/scaled-architecture.md
  src/cloud/project/log-locations.md
  src/cloud/project/new-relic.md
  src/common/images/cloud/cloud-newrelic-dashboard-logs-access.png
Labels: 2.x, Internal Dev, Progress: on hold, Small Changes

#7586 Cloud Guide fixes
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/cdn/fastly-vcl-allowlist.md
Labels: 2.x, Internal Dev, Progress: review, Small Changes

#7567 Update supported ES versions for Magento 2.4
  src/cloud/project/project-conf-files_services.md
Labels: Internal Dev, Progress: approved, Small Changes

#7590 Correct font display values
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#7548 Update mage-profiler.md
  src/guides/v2.3/config-guide/bootstrap/mage-profiler.md
Labels: 2.3.x, Editorial, Progress: approved

#7615 Update security-txt.md
  src/guides/v2.4/security/security-txt.md
Labels: 2.x, Partner: Corra, Progress: review, Small Changes, partners-contribution

#7623 Magento 2.4.0 Backward Incompatibility Highlights Update for MFTF
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7618 Small changes
  src/cloud/architecture/scaled-architecture.md
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/project/log-locations.md
  src/cloud/project/new-relic.md
  src/cloud/project/project-conf-files_services.md
  src/common/images/cloud/cloud-newrelic-dashboard-logs-access.png
  src/guides/v2.3/config-guide/bootstrap/mage-profiler.md
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
  src/guides/v2.4/security/security-txt.md
Labels: 2.x, Internal Dev, Progress: approved, Small Changes

#7620 MCLOUD-5624: Unable to enable sending email in the docker
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-extend.md
  src/cloud/project/log-locations.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Internal Dev, Progress: review

#7601 Update whats new
  src/_data/whats-new.yml
Labels: Progress: approved

#7626 updating support table for prex
  src/_data/mde.yml
Labels: 2.4.0, Internal Dev, Progress: approved

#7607 Update BIC reference
  src/_data/codebase/v2_4/mftf/b2b/bic/v1_1_0-1_2_0.yml
  src/_data/codebase/v2_4/mftf/ce/bic/v2_3_0-2_4_0.yml
  src/_data/codebase/v2_4/mftf/ee/bic/v2_3_0-2_4_0.yml
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4.0-develop.html
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4.0.md
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4.0-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4.0.md
  src/guides/v2.4/reference/mftf/backward-incompatible-changes.md
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: Automation, Major Update, Progress: approved

#7628 Remove blank line from metadata
  src/guides/v2.4/security/security-txt.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7616 Fix "SVC failure due to adding strict types" section of release notes
  src/guides/v2.4/release-notes/backward-incompatible-changes/index.md
Labels: 2.4.x, Progress: approved

#7630 Magento 2.4.0 Release Note minor edit
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7622 Updated links to Redocly
  src/_data/toc/rest-api.yml
  src/guides/v2.4/rest/bk-rest.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#7611 DOC-202: Revise MSI modules to be disabled list
  src/extensions/inventory-management/index.md
Labels: 2.4.x, Major Update, Progress: approved

#7635 Remove duplicates in BIC reference
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4.0.md
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4.0.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7634 Fix encoding issue on the Security.txt page
  src/guides/v2.4/security/security-txt.md
Labels: 2.4.x, Internal Dev, Maintenance, Progress: approved

#7637 Add MFTF reference documentation for tests and action groups in 2.4.0
  src/_data/codebase/v2_4/mftf/ce/action-groups.yml
  src/_data/codebase/v2_4/mftf/ce/functional-tests.yml
  src/guides/v2.4/reference/mftf/action-groups.md
  src/guides/v2.4/reference/mftf/functional-tests.md
Labels: 2.4.0, Automation, Internal Dev, Major Update, Progress: approved

#7638 Magento 2 4 0 Release Note update -- new hotfixes
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7644 Added missing release note for B2B
  src/guides/v2.4/release-notes/b2b-release-notes.md
Labels: 2.4.0, Editorial, Progress: approved

#7632 theme /i18n location inaccurate
  src/guides/v2.4/frontend-dev-guide/translations/xlate.md
Labels: 2.4.x, Editorial, Progress: approved, Small Changes

#7645 adding new field as on 2.4
  src/guides/v2.4/config-guide/prod/config-reference-most.md
Labels: 2.4.x, Progress: approved

#7594 Update content for section layout customise
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Progress: approved, Technical

#7619 Note that security releases are not always -p1
  src/release/index.md
Labels: Partner: Blue Acorn iCi, Progress: approved, Small Changes, Technical, Technology Partner: Vertex, partners-contribution, tech-partners-contribution

#7648 Add known issue to release notes
  src/extensions/amazon-sales/release-notes/index.md
Labels: 2.4.0, Channels, Progress: approved

#7652 Added missing part about action controllers decomposition
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7649 Update ES versions in cloud services
  src/cloud/project/project-conf-files_services.md
Labels: 2.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7646 MCLOUD-5511: Add Multi-website Support into Cloud Docker
  src/_data/toc/cloud-guide.yml
  src/cloud/docker/docker-multi-website.md
  src/cloud/project/project-multi-sites.md
Labels: Internal Dev, Progress: approved

#7627 Add guideline to prevent manual changes to codebase content
  .github/CONTRIBUTING.md
Labels: Internal Dev, Progress: review, Site Improvements
