Repository magento/devdocs, pull requests merged in 2020-09, with the labels that each got.

#7792 Adding beta content for visual similarity rec type
  src/recommendations/install-configure.md
  src/recommendations/release-notes.md
Labels: 2.4.x, Internal Dev

#7791 Update whatsnew for Aug 31
  src/_data/whats-new.yml
Labels: Internal Dev, Site Improvements

#7794 Update Marketplace EQP API's auth.md
  src/marketplace/eqp/v1/auth.md
Labels: Internal Dev

#7796 2FA updated diagram
  src/guides/v2.4/security/two-factor-authentication.md
Labels: 2.4.x, Internal Dev, Progress: approved, Small Changes

#7797 GraphQL: Move files to an interfaces directory
  src/_data/toc/graphql.yml
  src/_data/whats-new.yml
  src/guides/v2.3/graphql/interfaces/bundle-product.md
  src/guides/v2.3/graphql/interfaces/category-interface.md
  src/guides/v2.3/graphql/interfaces/configurable-product.md
  src/guides/v2.3/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.3/graphql/interfaces/downloadable-product.md
  src/guides/v2.3/graphql/interfaces/gift-card-product.md
  src/guides/v2.3/graphql/interfaces/grouped-product.md
  src/guides/v2.3/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.3/graphql/interfaces/product-interface.md
  src/guides/v2.3/graphql/mutations/add-bundle-products.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/product/product-interface-implementations.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/category-list.md
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.3/graphql/queries/products.md
  src/guides/v2.3/graphql/queries/wishlist.md
  src/guides/v2.3/graphql/release-notes.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-add-product-to-cart.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
  src/guides/v2.4/graphql/interfaces/bundle-product.md
  src/guides/v2.4/graphql/interfaces/category-interface.md
  src/guides/v2.4/graphql/interfaces/configurable-product.md
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.4/graphql/interfaces/downloadable-product.md
  src/guides/v2.4/graphql/interfaces/gift-card-product.md
  src/guides/v2.4/graphql/interfaces/grouped-product.md
  src/guides/v2.4/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/product/bundle-product.md
  src/guides/v2.4/graphql/product/customizable-option-interface.md
  src/guides/v2.4/graphql/product/downloadable-product.md
  src/guides/v2.4/graphql/product/gift-card-product.md
  src/guides/v2.4/graphql/product/grouped-product.md
  src/guides/v2.4/graphql/product/product-interface-implementations.md
  src/guides/v2.4/graphql/product/product-interface.md
  src/guides/v2.4/graphql/queries/categories.md
  src/guides/v2.4/graphql/queries/category-list.md
  src/guides/v2.4/graphql/queries/category.md
  src/guides/v2.4/graphql/release-notes.md
Labels: 2.3.x, 2.4.x, Internal Dev, Maintenance, Progress: approved

#7803 Added the contributor name and contributor link
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#7798 GraphQL: Move files to an interfaces directory part 2
  src/_data/toc/graphql.yml
  src/_data/whats-new.yml
  src/_includes/graphql/wishlist.md
  src/guides/v2.3/graphql/interfaces/bundle-product.md
  src/guides/v2.3/graphql/interfaces/category-interface.md
  src/guides/v2.3/graphql/interfaces/configurable-product.md
  src/guides/v2.3/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.3/graphql/interfaces/downloadable-product.md
  src/guides/v2.3/graphql/interfaces/gift-card-product.md
  src/guides/v2.3/graphql/interfaces/grouped-product.md
  src/guides/v2.3/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.3/graphql/interfaces/product-interface.md
  src/guides/v2.3/graphql/mutations/add-bundle-products.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/product/product-interface-implementations.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/category-list.md
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.3/graphql/queries/products.md
  src/guides/v2.3/graphql/queries/wishlist.md
  src/guides/v2.3/graphql/release-notes.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-add-product-to-cart.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
  src/guides/v2.4/graphql/interfaces/bundle-product.md
  src/guides/v2.4/graphql/interfaces/category-interface.md
  src/guides/v2.4/graphql/interfaces/configurable-product.md
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.4/graphql/interfaces/downloadable-product.md
  src/guides/v2.4/graphql/interfaces/gift-card-product.md
  src/guides/v2.4/graphql/interfaces/grouped-product.md
  src/guides/v2.4/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/product/product-interface-implementations.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/categories.md
  src/guides/v2.4/graphql/queries/category-list.md
  src/guides/v2.4/graphql/queries/category.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/graphql/queries/products.md
  src/guides/v2.4/graphql/release-notes.md
Labels: 2.4.1, Internal Dev, Maintenance, Progress: approved

#7808 Add workaround for MariaDB 10.4 performance issue
  src/_includes/install/maria-db.md
  src/cloud/project/project-conf-files_services-mysql.md
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/performance-best-practices/configuration.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved

#7789 Updates for new Managed Alerts for Magento Commerce alert policy
  src/_data/whats-new.yml
  src/cloud/architecture/cloud-architecture.md
  src/cloud/integrations/health-notifications.md
  src/cloud/live/site-launch-checklist.md
  src/cloud/project/manage-disk-space.md
  src/cloud/project/new-relic.md
  src/common/images/cloud/cloud-new-relic-add-alerts-to-notification-channel.png
  src/common/images/cloud/cloud-new-relic-add-notification-channel.png
  src/common/images/cloud/cloud-new-relic-create-notification-channel.png
  src/common/images/cloud/cloud-new-relic-select-account.png
  src/common/images/cloud/cloud-newrelic-magento-alert-conditions.png
  src/common/images/cloud/cloud-newrelic-managed-alerts-for-magento.png
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7809 Removing MFTF references
  src/_data/codebase/v2_3/mftf/action-groups.yml
  src/_data/codebase/v2_3/mftf/functional-tests.yml
  src/_data/codebase/v2_4/mftf/b2b/action-groups.yml
  src/_data/codebase/v2_4/mftf/b2b/bic/v1_1_0-1_2_0.yml
  src/_data/codebase/v2_4/mftf/b2b/functional-tests.yml
  src/_data/codebase/v2_4/mftf/ce/action-groups.yml
  src/_data/codebase/v2_4/mftf/ce/bic/v2_3_0-2_4_0.yml
  src/_data/codebase/v2_4/mftf/ce/functional-tests.yml
  src/_data/codebase/v2_4/mftf/ee/action-groups.yml
  src/_data/codebase/v2_4/mftf/ee/bic/v2_3_0-2_4_0.yml
  src/_data/codebase/v2_4/mftf/ee/functional-tests.yml
  src/_data/toc/mftf-v2.yml
  src/_data/toc/mftf.yml
  src/_data/whats-new.yml
  src/guides/v2.3/reference/mftf/action-groups.md
  src/guides/v2.3/reference/mftf/functional-tests.md
  src/guides/v2.4/reference/mftf/action-groups.md
  src/guides/v2.4/reference/mftf/functional-tests.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved

#7811 Updated 2fa diagram syntax
  src/guides/v2.4/security/two-factor-authentication.md
Labels: 2.4.0, Internal Dev, Progress: approved, Small Changes, Technical

#7795 Bypass fastly cleanup for Origin Cloaking
  src/_data/toc/cloud-guide.yml
  src/cloud/cdn/fastly-vcl-bypass-to-origin.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7810 MCLOUD-6430: Xdebug not working on Magento Cloud Docker 1.1
  src/cloud/docker/docker-development-debug.md
Labels: Internal Dev, Progress: approved, Technical

#7807 Updated 2fa diagram
  src/guides/v2.4/security/two-factor-authentication.md
Labels: 2.4.0, Internal Dev, Progress: approved, Small Changes

#7707 Update on Integrating modules
  src/guides/v2.3/get-started/create-integration.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#7815 Revert "GraphQL: Add section about CORS"
  src/guides/v2.4/graphql/send-request.md
Labels: 2.4.1, Progress: approved

#7814 New Relic Alerts: Warning req'd notification channel config
  src/cloud/project/new-relic.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7817 Fix Cloud services list alignment to correct broken list
  src/cloud/project/project-conf-files_services.md
Labels: Editorial, Progress: approved

#7800 Update using-fonts.md
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, Small Changes, partners-contribution

#7813 Refactor Cloud Application Page to smaller pages with Menu Entries
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_data/whats-new.yml
  src/_includes/cloud/error-codes.md
  src/_includes/cloud/note-route-all-placeholder.md
  src/_includes/cloud/service-config-integration-starter.md
  src/_includes/cloud/tip-change-installed-service-version.md
  src/cloud/architecture/pro-architecture.md
  src/cloud/architecture/starter-architecture.md
  src/cloud/before/before-setup-env-install.md
  src/cloud/configure/configuration-overview.md
  src/cloud/configure/import-url-rewrites.md
  src/cloud/configure/setup-cron-jobs.md
  src/cloud/deploy/cloud-deployment-process.md
  src/cloud/deploy/reduce-downtime.md
  src/cloud/deploy/scenario-based-deployment.md
  src/cloud/deploy/static-content-deployment.md
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-manage-cron-jobs.md
  src/cloud/env/environments-ssh.md
  src/cloud/env/environments.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/env/variables-post-deploy.md
  src/cloud/live/live-prot.md
  src/cloud/live/live-sanity-check.md
  src/cloud/live/sens-data-over.md
  src/cloud/project/log-locations.md
  src/cloud/project/magento-app-php-application.md
  src/cloud/project/magento-app-php-ini.md
  src/cloud/project/magento-app-properties.md
  src/cloud/project/magento-app-variables.md
  src/cloud/project/magento-app-workers.md
  src/cloud/project/magento-app.md
  src/cloud/project/manage-disk-space.md
  src/cloud/project/project-routes-more-redir.md
  src/cloud/project/project-upgrade.md
  src/cloud/project/project-webint-basic.md
  src/cloud/project/projects.md
  src/cloud/project/routes.md
  src/cloud/project/services-elastic.md
  src/cloud/project/services-mysql.md
  src/cloud/project/services-rabbit.md
  src/cloud/project/services-redis.md
  src/cloud/project/services.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/requirements/cloud-requirements.md
  src/cloud/setup/first-time-setup-import-prepare.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: Major Update, Partner: Vaimo, Progress: review, partners-contribution

#7823 Finalize the Cloud updates related to Application topic
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_data/whats-new.yml
  src/_includes/cloud/error-codes.md
  src/_includes/cloud/note-route-all-placeholder.md
  src/_includes/cloud/service-config-integration-starter.md
  src/_includes/cloud/tip-change-installed-service-version.md
  src/cloud/architecture/pro-architecture.md
  src/cloud/architecture/starter-architecture.md
  src/cloud/before/before-setup-env-install.md
  src/cloud/configure/configuration-overview.md
  src/cloud/configure/import-url-rewrites.md
  src/cloud/configure/setup-cron-jobs.md
  src/cloud/deploy/cloud-deployment-process.md
  src/cloud/deploy/reduce-downtime.md
  src/cloud/deploy/scenario-based-deployment.md
  src/cloud/deploy/static-content-deployment.md
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-manage-cron-jobs.md
  src/cloud/env/environments-ssh.md
  src/cloud/env/environments.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/env/variables-post-deploy.md
  src/cloud/live/live-prot.md
  src/cloud/live/live-sanity-check.md
  src/cloud/live/sens-data-over.md
  src/cloud/project/log-locations.md
  src/cloud/project/magento-app-php-application.md
  src/cloud/project/magento-app-php-ini.md
  src/cloud/project/magento-app-properties.md
  src/cloud/project/magento-app-variables.md
  src/cloud/project/magento-app-workers.md
  src/cloud/project/magento-app.md
  src/cloud/project/manage-disk-space.md
  src/cloud/project/project-routes-more-redir.md
  src/cloud/project/project-upgrade.md
  src/cloud/project/project-webint-basic.md
  src/cloud/project/projects.md
  src/cloud/project/routes.md
  src/cloud/project/services-elastic.md
  src/cloud/project/services-mysql.md
  src/cloud/project/services-rabbit.md
  src/cloud/project/services-redis.md
  src/cloud/project/services.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/requirements/cloud-requirements.md
  src/cloud/setup/first-time-setup-import-prepare.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: Editorial, Progress: approved

#7819 Updates for bypass fastly cache
  src/cloud/cdn/fastly-vcl-bypass-to-origin.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/live/stage-prod-test.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7822 Updates for Let's Encrypt SSL/TLS certs
  src/cloud/cdn/configure-fastly.md
  src/cloud/live/live.md
  src/cloud/live/site-launch-checklist.md
  src/cloud/requirements/cloud-requirements.md
Labels: Progress: approved

#7799 Update set-shipping-address.md
  src/guides/v2.3/graphql/mutations/set-shipping-address.md
  src/guides/v2.4/graphql/mutations/set-shipping-address.md
Labels: 2.3.x, 2.4.x, Progress: dev in progress, Technical

#7841 Facilitate rake update tasks
  Rakefile
  rakelib/multirepo.rake
  rakelib/update.rake
Labels: Internal Dev, Maintenance, Progress: approved

#7826 Removed "A branch name of Sprint2 and sprint2 are just fine." #7825
  src/cloud/reference/git-integration.md
Labels: 2.x, Progress: approved, Small Changes

#7842 Upgrade mdl, enable MD046
  .github/workflows/main.yml
  Gemfile
  Gemfile.lock
  _checks/styles/style-rules-prod
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-import.md
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
  src/guides/v2.3/ext-best-practices/tutorials/serialized-to-json-data-upgrade.md
  src/guides/v2.3/extension-dev-guide/configuration/sensitive-and-environment-settings.md
  src/guides/v2.3/extension-dev-guide/package/package_module.md
  src/guides/v2.3/get-started/authentication/gs-authentication-oauth.md
  src/guides/v2.3/install-gde/prereq/security.md
  src/guides/v2.3/pattern-library/displaying-data/datatable/datatable.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
Labels: Editorial, Internal Dev, Maintenance, Progress: approved

#7830 Guidance about auto-generated webhook on Bitbucket
  src/cloud/integrations/bitbucket-integration.md
Labels: 2.x, Partner: Vaimo, Progress: review, Technical, partners-contribution

#7831 Added risk assessment to contributing page
  src/contributor-guide/contributing.md
Labels: Major Update, Progress: approved, Site Improvements

#7839 Update mysql.md - remove line referring non existent admin feature
  src/guides/v2.4/install-gde/prereq/mysql.md
Labels: 2.4.x, Editorial, Progress: approved, Small Changes

#7835 Add clear generated/metadata command
  src/guides/v2.3/comp-mgr/cli/upgrade-with-script.md
Labels: 2.3.x, Progress: approved, Small Changes, Technical

#7828 Update DevPortal Sandbox images
  src/marketplace/eqp/v1/images/sandbox-access-key-empty.png
  src/marketplace/eqp/v1/images/sandbox-access-key-list.png
  src/marketplace/eqp/v1/images/sandbox-not-eligible.png
Labels: Internal Dev, Progress: approved, Small Changes

#7840 Cloud Docker and Cloud Components release note updates
  src/_data/var.yml
  src/cloud/live/live.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Internal Dev, Progress: on hold, Technical

#7846 Magento 2.4.1 Beta Release Notes
  src/_data/toc/release-notes.yml
  src/_includes/release-notes/engcomm-2-4-1-issues.md
  src/_includes/release-notes/engcomm-2-4-1-partner.md
  src/guides/v2.4/release-notes/bk-release-notes.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
Labels: 2.4.1, Internal Dev, Major Update, Progress: approved

#7736 Update BIC reference
  src/_includes/backward-incompatible-changes/commerce/2.4.0-2.4.1-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.4.0-2.4.1-develop.html
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: 2.4.1, Automation, Internal Dev, Progress: approved

#7845 Small changes
  src/guides/v2.3/comp-mgr/cli/upgrade-with-script.md
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/marketplace/eqp/v1/images/sandbox-access-key-empty.png
  src/marketplace/eqp/v1/images/sandbox-access-key-list.png
  src/marketplace/eqp/v1/images/sandbox-not-eligible.png
Labels: 2.3.x, 2.4.0, Internal Dev, Progress: approved, Small Changes

#7856 Remove statements
  src/guides/v2.3/security/google-recaptcha.md
  src/guides/v2.3/security/two-factor-authentication.md
  src/guides/v2.4/security/security-txt.md
  src/guides/v2.4/security/two-factor-authentication.md
Labels: 2.3.x, 2.4.0, Editorial, Internal Dev, Progress: approved

#7851 Updating compatibility table for Recommendations
  src/_data/mde.yml
Labels: 2.4.x, Internal Dev, Progress: approved

#7850 MQP Release 1.0.4
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#7806 Added "Virtual product data types" topic to graphql
  src/_data/toc/graphql.yml
  src/guides/v2.3/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.3/graphql/interfaces/product-interface.md
  src/guides/v2.3/graphql/interfaces/virtual-product.md
  src/guides/v2.4/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/interfaces/virtual-product.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#7805 Added "Simple product data types" topic to graphql
  src/_data/toc/graphql.yml
  src/guides/v2.3/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.3/graphql/interfaces/product-interface.md
  src/guides/v2.3/graphql/interfaces/simple-product.md
  src/guides/v2.4/graphql/interfaces/product-interface-implementations.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
  src/guides/v2.4/graphql/interfaces/simple-product.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#7843 Doctor jekyll reports conflicts
  src/cloud/cdn/fastly-vcl-bypass-to-origin.md
  src/cloud/docker/docker-manage-cron-jobs.md
  src/guides/v2.3/graphql/authorization-tokens.md
  src/guides/v2.3/graphql/develop/create-graphqls-file.md
  src/guides/v2.3/graphql/get-customer-authorization-token.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shopping-cart.md
  src/guides/v2.4/graphql/authorization-tokens.md
  src/guides/v2.4/graphql/develop/create-graphqls-file.md
  src/guides/v2.4/graphql/get-customer-authorization-token.md
  src/guides/v2.4/install-gde/continue-to-verify.md
  src/guides/v2.4/install-gde/install-roadmap_web.md
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/install-gde/prereq/php-settings.md
Labels: 2.x, Partner: Vaimo, Progress: approved, Site Improvements, Technical, partners-contribution

#7861 GraphQL: CustomizableFileOption/Value aren't supported
  src/guides/v2.3/graphql/interfaces/customizable-option-interface.md
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Technical

#7860 MCLOUD-6898: Add option to customize port for MailHog
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-quick-reference.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7868 app:config:dump - Update list of available config types
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-export.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#7832 GraphQL: Move *ItemInterface docs to their own topics
  src/_data/toc/graphql.yml
  src/_includes/graphql/credit-memo-item-interface.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/downloadable-items-links.md
  src/_includes/graphql/gift-card-item.md
  src/_includes/graphql/invoice-item-interface.md
  src/_includes/graphql/item-selected-bundle-option.md
  src/_includes/graphql/order-item-interface.md
  src/_includes/graphql/shipment-item-interface.md
  src/guides/v2.4/graphql/interfaces/credit-memo-item-interface.md
  src/guides/v2.4/graphql/interfaces/invoice-item-interface.md
  src/guides/v2.4/graphql/interfaces/order-item-interface.md
  src/guides/v2.4/graphql/interfaces/shipment-item-interface.md
Labels: 2.4.1, Internal Dev, Progress: approved, Technical

#7827 Clarify EAV Attribute Options
  src/guides/v2.3/extension-dev-guide/attributes.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#7867 Checkout form improvements
  src/guides/v2.3/howdoi/checkout/checkout_form.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7857 Note about different service versions on Cloud
  src/_includes/cloud/note-cloud-services-compatibility.md
  src/cloud/project/services-elastic.md
  src/cloud/project/services.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7871 Update What's New for Sept 14
  src/_data/whats-new.yml
Labels: Editorial, Progress: approved

#7873 GraphQL: Add/update customer query examples
  src/guides/v2.4/graphql/queries/customer.md
Labels: 2.4.1, Internal Dev, Progress: approved, Technical

#7863 Document 'disable_introspection' for GraphQL
  src/guides/v2.3/graphql/queries/index.md
  src/guides/v2.4/graphql/queries/index.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: approved

#7875 Pipeline deployment definition is unclear
  src/_includes/config/split-deploy/split-deploy-overview.md
Labels: Partner: Vaimo, Progress: approved, partners-contribution

#7872 Adding link to release notes from install
  src/recommendations/install-configure.md
Labels: 2.4.x, Progress: approved

#7869 Move Fastly custom cache configuration to new topic:
  src/_data/toc/cloud-guide.yml
  src/cloud/cdn/cloud-fastly.md
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/cdn/configure-fastly-customize-cache.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/cdn/fastly-image-optimization.md
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/live/site-launch-checklist.md
  src/common/images/cloud/cloud-fastly-starter-activate-domain.png
  src/common/images/cloud/cloud_fastly-maint-allowlist.png
Labels: 2.x, Major Update, Progress: changes requested

#7876 Remove abandoned Baler module
  src/guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: Partner: Something Digital, Progress: approved, partners-contribution

#7874 Updated information about Cloud Metapackage
  src/cloud/project/project-webint-snap.md
  src/cloud/reference/cloud-composer.md
Labels: 2.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#7882 Update linter
  .github/workflows/linter.yml
Labels: Maintenance, Progress: approved

#7884 Fixed broken HREF - Security Intro Page
  src/guides/v2.3/architecture/security_intro.md
Labels: Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#7880 Updated Fastly set up instructions for Platform TLS
  src/cloud/cdn/cloud-fastly.md
  src/cloud/cdn/configure-fastly-customize-cache.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/live/live.md
  src/cloud/live/site-launch-checklist.md
  src/cloud/live/stage-prod-migrate-prereq.md
  src/cloud/requirements/cloud-requirements.md
Labels: 2.x, Major Update, Progress: changes requested

#7859 Add additional clarifications.
  src/marketplace/sellers/product-descriptions.md
Labels: 2.x, Progress: approved, Small Changes, Technical

#7885 Update Fastly set up instructions and SSL/TLS certificate information
  src/_data/toc/cloud-guide.yml
  src/cloud/cdn/cloud-fastly.md
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/cdn/configure-fastly-customize-cache.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/cdn/fastly-image-optimization.md
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/live/live.md
  src/cloud/live/site-launch-checklist.md
  src/cloud/live/stage-prod-migrate-prereq.md
  src/cloud/requirements/cloud-requirements.md
  src/common/images/cloud/cloud-fastly-starter-activate-domain.png
  src/common/images/cloud/cloud_fastly-maint-allowlist.png
Labels: 2.x, Major Update, Progress: approved

#7853 GraphQL: availableStores query
  src/_data/toc/graphql.yml
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/queries/available-stores.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.1, Community, Internal Dev, New Topic, Progress: approved

#7887 Updated Install Options
  src/guides/v2.3/install-gde/continue-to-install.md
  src/guides/v2.4/install-gde/bk-install-guide.md
  src/guides/v2.4/install-gde/continue-to-install.md
Labels: 2.3.4, 2.3.x, Editorial, Partner: Vaimo, Progress: approved, Small Changes, partners-contribution

#7889 Added info about Grunt Failure
  src/guides/v2.3/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.3.4, 2.3.x, Editorial, Partner: Vaimo, Progress: approved, Small Changes, partners-contribution

#7890 Create New Item To Make Instructions Clearer
  src/guides/v2.3/config-guide/prod/prod_file-sys-perms.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Vaimo, Progress: approved, Small Changes, partners-contribution

#7894 Removed orphaned page - nothing ever linked to this
  src/guides/v2.3/javascript-dev-guide/back_to_guide.md
  src/guides/v2.4/javascript-dev-guide/back_to_guide.md
Labels: 2.3.x, 2.4.x, Partner: Vaimo, Progress: approved, partners-contribution

#7900 Small changes
  src/common/images/cloud/cloud-fastly-starter-activate-domain.png
  src/common/images/cloud/cloud_fastly-maint-allowlist.png
  src/guides/v2.3/config-guide/prod/prod_file-sys-perms.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css_debug.md
  src/guides/v2.3/install-gde/continue-to-install.md
  src/guides/v2.3/javascript-dev-guide/back_to_guide.md
  src/guides/v2.4/install-gde/bk-install-guide.md
  src/guides/v2.4/install-gde/continue-to-install.md
  src/guides/v2.4/javascript-dev-guide/back_to_guide.md
Labels: Internal Dev, Maintenance, Progress: approved

#7893 Removed triple dots to stop appearing in Apache configuration block
  src/guides/v2.3/install-gde/prereq/apache.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Vaimo, Progress: approved, Small Changes, partners-contribution

#7848 Update prereq-overview.md
  src/guides/v2.3/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
Labels: Progress: approved

#7901 Update ui-columnscontrols.md
  src/guides/v2.3/ui_comp_guide/components/ui-columnscontrols.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Accenture, Progress: approved, Small Changes, partners-contribution

#7906 CAPTCHA and WebAPIs
  src/_data/toc/graphql.yml
  src/_data/toc/rest-api.yml
  src/guides/v2.3/get-started/gs-web-api-request.md
  src/guides/v2.3/graphql/protected-mutations.md
  src/guides/v2.3/graphql/send-request.md
  src/guides/v2.3/rest/protected-endpoints.md
  src/guides/v2.4/graphql/protected-mutations.md
  src/guides/v2.4/rest/protected-endpoints.md
Labels: 2.3.6, 2.4.1, Internal Dev, New Topic, Progress: approved

#7898 MCLOUD-2789: [Cloud Docker] Add custom ES plugins
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7905 Added clarification about beta access for Q4 2020 release
  src/release/index.md
Labels: Editorial, Progress: approved

#7899 Added info about Fastly Admin UI Not Being Available (Cloud)
  src/cloud/cdn/configure-fastly.md
Labels: 2.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#7870 Update Verify Zend Framework composer dependencies section for Cloud Update Magento Version doc
  src/cloud/project/project-upgrade.md
Labels: 2.x, Progress: approved, Technical

#7904 Added new topic about Magento's software lifecycle policy
  src/_data/toc/release.yml
  src/release/lifecycle-policy.md
Labels: New Topic, Progress: approved

#7907 MCLOUD-6896: Add possibility to pass ECE-Tools environment variables
  src/cloud/docker/docker-config.md
Labels: 2.x, Progress: approved, Technical

#7909 MCLOUD-6896: Add possibility to pass ECE-Tools environment variables …
  src/cloud/docker/docker-config.md
Labels: 2.x, Progress: approved, Technical

#7913 MQP Release 1.0.5
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#7915 Fix broken link
  src/cloud/howtos/debug.md
Labels: 2.x, Editorial, Progress: approved, Small Changes

#7917 Remove Magento-Doc-Feedback email address
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  src/guides/v2.3/bk-get-started-magento.md
Labels: Internal Dev, Maintenance, Progress: approved

#7916 Move clean up instructions earlier in the upgrade procedure
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
Labels: 2.4.1, Editorial, Internal Dev, Progress: approved

#7903 Added Sequence Load information for TinyMCE extension
  src/guides/v2.3/ui_comp_guide/components/wysiwyg/configure-tinymce-editor.md
Labels: 2.3.x, 2.4.x, Partner: Vaimo, Progress: approved, Small Changes, Technical, partners-contribution

#7919 Editorial/elastic variable
  src/cloud/project/services-elastic.md
Labels: Editorial, Partner: Vaimo, Progress: approved, Small Changes, partners-contribution

#7911 Fix missing "\" in new implementation example
  src/guides/v2.4/config-guide/redis/redis-pg-cache.md
Labels: 2.4.x, Editorial, Progress: approved, Small Changes

#7865 Improve docs and add more information related with blocks
  src/guides/v2.3/frontend-dev-guide/layouts/layout-practice.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#7918 Added Dynamic Row Default Example
  src/guides/v2.3/ext-best-practices/tutorials/dynamic-row-system-config.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: Vaimo, Progress: approved, partners-contribution

#7912 MCLOUD-6977: Update documentation about routes
  src/cloud/project/routes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7926 Fix typo in extension dev guide
  src/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#7925 Inventory release notes
  src/guides/v2.3/inventory/release-notes.md
Labels: 2.4.1, Internal Dev, Major Update, Progress: approved

#7888 GraphQL: Mutations for managing wish lists (EE)
  src/_data/toc/graphql.yml
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/mutations/copy-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/create-wishlist.md
  src/guides/v2.4/graphql/mutations/delete-wishlist.md
  src/guides/v2.4/graphql/mutations/move-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/update-wishlist.md
Labels: 2.4.2, Community, Internal Dev, New Topic, Progress: approved

#7931 Fixed broken URL links on REST API Overview menu
  src/_data/toc/rest-api.yml
Labels: 2.4.x, Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#7921 Editorial/maintenance enable info
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-maint.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#7908 Remove AMQP Store warning
  src/_data/toc/rest-api.yml
  src/guides/v2.3/extension-dev-guide/message-queues/message-queues-stores.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-maint.md
Labels: 2.3.x, 2.4.x, Partner: Comwrap, Progress: approved, Small Changes, Technical, partners-contribution

#7932 Added a link to KB articles about patches, fixed B2B versions
  src/quality-patches/release-notes.md
Labels: Editorial, Internal Dev, Progress: approved

#7883 Remove Secondary Component Information
  src/guides/v2.3/ui_comp_guide/howto/new_component_declaration.md
Labels: 2.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#7927 MCLOUD-6977: Update documentation about routes (#7912)
  src/cloud/project/routes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7891 Klarna payment method overview and GraphQL mutation
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/images/klarna-payments-cart-updates.drawio
  src/guides/v2.4/graphql/images/klarna-payments-cart-updates.svg
  src/guides/v2.4/graphql/images/klarna-payments.drawio
  src/guides/v2.4/graphql/images/klarna-payments.svg
  src/guides/v2.4/graphql/mutations/create-klarna-payments-session.md
  src/guides/v2.4/graphql/payment-methods/klarna.md
Labels: 2.4.1, New Topic, Progress: approved

#7924 [WIP] Added Slave Database Connection Information
  src/cloud/project/services-mysql.md
Labels: 2.3.x, 2.4.x, Partner: Vaimo, Progress: approved, partners-contribution

#7886 Add import command description (Contributors assistant)
  src/contributor-guide/contributing.md
Labels: Major Update, Progress: approved

#7902 Fix return for extractAdjustment
  src/guides/v2.3/extension-dev-guide/price-adjustments.md
Labels: 2.2.x, 2.3.x, Progress: approved, Technical

#7937 Small changes
  src/cloud/howtos/debug.md
  src/cloud/project/services-elastic.md
  src/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
  src/guides/v2.3/extension-dev-guide/message-queues/message-queues-stores.md
  src/guides/v2.3/extension-dev-guide/price-adjustments.md
  src/guides/v2.3/install-gde/prereq/prereq-overview.md
  src/guides/v2.3/ui_comp_guide/components/ui-columnscontrols.md
  src/guides/v2.3/ui_comp_guide/components/wysiwyg/configure-tinymce-editor.md
  src/guides/v2.4/config-guide/redis/redis-pg-cache.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
Labels: Progress: approved

#7941 (maintenance) Add init to build:stage
  rakelib/build.rake
Labels: Maintenance, Progress: approved

#7942 remove redundant variable
  src/guides/v2.3/extension-dev-guide/price-adjustments.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#7943 Improving the create a new page layout topic
  src/common/images/fdg/custom_layout_footer_bottom.png
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
Labels: 2.3.4, 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7950 Update GraphQL index page
  src/guides/v2.4/graphql/index.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7945 Update project-routes-more-redir.md
  rakelib/build.rake
  src/cloud/howtos/debug.md
  src/cloud/project/project-routes-more-redir.md
  src/cloud/project/services-elastic.md
  src/cloud/project/services-mysql.md
  src/common/images/fdg/custom_layout_footer_bottom.png
  src/contributor-guide/contributing.md
  src/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
  src/guides/v2.3/extension-dev-guide/message-queues/message-queues-stores.md
  src/guides/v2.3/extension-dev-guide/price-adjustments.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
  src/guides/v2.3/install-gde/prereq/prereq-overview.md
  src/guides/v2.3/ui_comp_guide/components/ui-columnscontrols.md
  src/guides/v2.3/ui_comp_guide/components/wysiwyg/configure-tinymce-editor.md
  src/guides/v2.4/config-guide/redis/redis-pg-cache.md
  src/guides/v2.4/graphql/index.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
Labels: Editorial, Progress: approved

#7939 Add info about optimized realpath_cache_settings
  src/cloud/project/magento-app-php-application.md
  src/cloud/project/magento-app-php-ini.md
  src/guides/v2.3/config-guide/multi-site/ms_nginx.md
  src/guides/v2.4/install-gde/prereq/php-settings.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/performance-best-practices/software.md
Labels: 2.x, Progress: approved, Technical

#7954 Add missing leading dot for `.well-known`
  src/cloud/project/magento-app-php-application.md
  src/cloud/project/magento-app-php-ini.md
  src/common/images/fdg/custom_layout_footer_bottom.png
  src/guides/v2.3/config-guide/multi-site/ms_nginx.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
  src/guides/v2.4/graphql/index.md
  src/guides/v2.4/install-gde/prereq/php-settings.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/performance-best-practices/software.md
  src/guides/v2.4/security/security-txt.md
Labels: Progress: approved

#7849 Update compatibility table and adding B2B for 2.4.1
  src/_data/mde.yml
Labels: 2.4.1, Internal Dev, Progress: approved, Site Improvements

#7922 Add Information About Content Staging
  src/guides/v2.3/extension-dev-guide/staging.md
Labels: Partner: Vaimo, Progress: approved, Technical, partners-contribution

#7964 Add a warning about the `REDIS_USE_SLAVE_CONNECTION` deploy variable
  src/cloud/env/variables-deploy.md
Labels: Progress: approved, Technical

#7965 adding link to list of events
  src/recommendations/verify.md
Labels: 2.4.x, Internal Dev, Progress: review

#7953 Update php extensions template to include ext-sockets
  src/_includes/install/php-extensions-template.md
  src/guides/v2.4/install-gde/prereq/php-settings.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7966 MQP Release 1.0.6
  src/quality-patches/release-notes.md
Labels: Major Update, Progress: approved
