Repository magento/devdocs, pull requests merged in 2020-08, with the labels that each got.

#7621 short array updated in code examples
  src/guides/v2.3/coding-standards/code-standard-demarcation.md
  src/guides/v2.3/config-guide/mq/manage-message-queues.md
  src/guides/v2.3/extension-dev-guide/test/test_object-mgr.md
  src/guides/v2.3/get-started/soap/soap-web-api-calls.md
Labels: 2.3.x, Editorial, Partner: Born Group, Progress: approved, partners-contribution

#7633 Extend documentation about onlySpawnWhenMessageAvailable consumer setting
  src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
Labels: 2.4.x, Internal Dev, Progress: approved

#7659 Add Security.txt feature attribution to community member
  src/guides/v2.4/security/security-txt.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7660 Revisions to new change version topic
  src/cloud/project/project-conf-files_services.md
Labels: 2.x, Internal Dev, Progress: review, Technical

#7663 Magento 2.4.0 Release Note update -- added links to newly available KB articles
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7664 Removed duplicate note
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
Labels: 2.4.0, Editorial, Progress: approved

#7647 GraphQL: Update customer object output for shipping
  src/_includes/graphql/customer-orders-output.md
Labels: 2.4.1, Internal Dev, Progress: approved, Technical

#7653 Extend reference docs for MFTF tests and action groups: Commerce and B2B
  src/_data/codebase/v2_4/mftf/b2b/action-groups.yml
  src/_data/codebase/v2_4/mftf/b2b/functional-tests.yml
  src/_data/codebase/v2_4/mftf/ee/action-groups.yml
  src/_data/codebase/v2_4/mftf/ee/functional-tests.yml
  src/_data/toc/mftf-v2.yml
  src/_data/toc/mftf.yml
  src/_includes/mftf/action-groups-template.md
  src/_includes/mftf/functional-tests-template.md
  src/_includes/mtf/block_attributes.md
  src/_includes/mtf/page-generator.md
  src/guides/v2.4/reference/mftf/action-groups.md
  src/guides/v2.4/reference/mftf/backward-incompatible-changes.md
  src/guides/v2.4/reference/mftf/functional-tests.md
Labels: 2.4.0, Automation, Internal Dev, Major Update, Progress: approved

#7657 MCLOUD-6215: Add examples in devdocs how to downgrade service versions
  src/cloud/project/project-conf-files_services.md
Labels: Internal Dev, Progress: approved, Waiting for Response

#7631 Assign page.guide_version via configuration scopes
  _config.yml
  _plugins/page-params/page-baseurl-generator.rb
Labels: Internal Dev, Progress: approved, Site Improvements

#7670 Enable Xdebug. Console command quick fix
  src/cloud/docker/docker-development-debug.md
Labels: Internal Dev, Progress: approved

#7658 Consolidate info about security releases on the policy page
  src/release/index.md
  src/release/policy/index.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#7665 Removed duplicate note; suggested to remove entire section
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.x, Editorial, Progress: approved, Small Changes

#7667 Fix a link in the Configuration Guide
  src/guides/v2.3/config-guide/config/config-create.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7666 Update contribution guidelines
  .github/CONTRIBUTING.md
Labels: Internal Dev, Maintenance, Progress: approved, Small Changes

#7671 B2B-709 Added known issue to B2B Release notes
  src/guides/v2.4/release-notes/b2b-release-notes.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7643 magento/devdocs#: Cloud. Skip patches.
  src/cloud/project/project-patch.md
Labels: 2.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7624 Added note about increasing value for SCD_MAX_EXECUTION_TIME
  src/_includes/cloud/note-increase-scd-max-execution-time-variable.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
Labels: 2.x, Internal Dev, Progress: approved

#7675 Magento 2 4 0 Release Note hotfix update 0803
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7593 Update custom js content
  src/guides/v2.3/javascript-dev-guide/javascript/custom_js.md
Labels: 2.4.0, Editorial, Progress: approved

#7672 Updating theme to use the latest Adobe analytics script
  Gemfile.lock
  src/_includes/layout/header-scripts.html
Labels: Internal Dev, Progress: approved, Site Improvements

#7679 Update video-tips.md
  src/marketplace/sellers/video-tips.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#7678 Remove obsolete topics and refresh config
  _config.yml
  src/_data/toc/contributor-guide.yml
  src/contributor-guide/contributing_docs_suggested.md
  src/guides/v2.3/bk-get-started-magento.md
  src/guides/v2.3/extension-dev-guide/Contribute_edg.md
  src/guides/v2.4/extension-dev-guide/Contribute_edg.md
Labels: Editorial, Maintenance, Progress: approved

#7677 Release notes for 3.0.5
  src/recommendations/release-notes.md
Labels: 2.4.x, Internal Dev, Progress: approved

#7661 Updated ES software compatibility matrix
  src/_includes/cloud/cloud-elasticsearch-client-compatibility.md
Labels: 2.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7669 Cloud packages August release
  src/_data/codebase/cloud/cloud-error-messages.yml
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_data/whats-new.yml
  src/_includes/cloud/error-codes.md
  src/_includes/cloud/note-error-message-reference-ece-tools.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-extend.md
  src/cloud/env/variables-build.md
  src/cloud/project/log-locations.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade.md
  src/cloud/reference/ece-tools-error-reference.md
  src/cloud/reference/error-codes.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
  src/cloud/trouble/trouble.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7681 Added link to KB troubleshooting article
  src/cloud/project/new-relic.md
Labels: 2.x, Internal Dev, Progress: approved, Small Changes, Technical

#7683 fix(xdebug, docker): fixes a typo in xdebug yaml
  src/cloud/docker/docker-development-debug.md
Labels: 2.x, Editorial, Progress: approved, Small Changes

#7685 Small changes
  .github/CONTRIBUTING.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/project/new-relic.md
  src/cloud/project/project-patch.md
  src/guides/v2.3/config-guide/config/config-create.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/get-started/create-integration.md
  src/guides/v2.3/javascript-dev-guide/bk-javascript-dev-guide.md
  src/guides/v2.3/javascript-dev-guide/javascript/custom_js.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_overview.md
  src/guides/v2.4/extension-dev-guide/build/create_component.md
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
  src/guides/v2.4/security/security-txt.md
  src/release/index.md
  src/release/policy/index.md
Labels: Progress: approved, Site Improvements

#7684 fix(xdebug,docker): accomodate linux differences
  src/cloud/docker/docker-development-debug.md
Labels: Progress: approved

#7595 MCLOUD-1528: Change default value for max execution time of static content deploy
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7686 Magento 2.4.0 Release Note hot fix and known issue update 0806
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7687 Adding new B2B patch note.
  src/guides/v2.4/release-notes/b2b-release-notes.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7640 MS-7739: [DevP][Docs] update of DevDocs for the Marketplace EQP API
  src/_data/toc/marketplace-api.yml
  src/marketplace/eqp/v1/access-keys.md
  src/marketplace/eqp/v1/api.md
  src/marketplace/eqp/v1/auth.md
  src/marketplace/eqp/v1/callbacks.md
  src/marketplace/eqp/v1/files.md
  src/marketplace/eqp/v1/getting-started.md
  src/marketplace/eqp/v1/handling-errors.md
  src/marketplace/eqp/v1/help.md
  src/marketplace/eqp/v1/images/sandbox-access-key-create.png
  src/marketplace/eqp/v1/images/sandbox-access-key-empty.png
  src/marketplace/eqp/v1/images/sandbox-access-key-list.png
  src/marketplace/eqp/v1/images/sandbox-landing-page.png
  src/marketplace/eqp/v1/images/sandbox-not-eligible.png
  src/marketplace/eqp/v1/packages.md
  src/marketplace/eqp/v1/reports.md
  src/marketplace/eqp/v1/rest-api.md
  src/marketplace/eqp/v1/sandbox.md
  src/marketplace/eqp/v1/test-results.md
  src/marketplace/eqp/v1/users.md
Labels: Internal Dev, Progress: approved

#7689 Update .gitignore
  .gitignore
Labels: Internal Dev, Progress: approved, Technical

#7688 updating example versions
  src/recommendations/install-configure.md
Labels: Internal Dev, Progress: approved, Technical

#7642 Added one more required step for JS bundling enablement guide
  src/guides/v2.3/frontend-dev-guide/themes/js-bundling.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Technical

#7694 Update privatelink-service.md
  src/cloud/project/privatelink-service.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7695 GraphQL: Fix typo in Payflow Pro sequence diagram
  src/common/images/graphql/paypal-payflow-pro.svg
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#7680 Fix search results page redirect issue
  Gemfile.lock
  src/_includes/layout/search-form.html
  src/search.md
Labels: Progress: approved

#7690 Adding instructions for editable forks.
  .github/CONTRIBUTING.md
Labels: Editorial, Progress: approved

#7698 Add a contributor to What's New entries
  Gemfile.lock
  src/whats-new.md
Labels: Internal Dev, Progress: approved, Site Improvements

#7697 Typing mistake
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Editorial, Progress: approved, Small Changes

#7693 Added link to public Slack workspace invite
  src/marketplace/eqp/v1/help.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#7691 Use updated way on how echo is done in phtml
  src/guides/v2.3/frontend-dev-guide/translations/translate_theory.md
Labels: 2.3.x, Editorial, Partner: MediaCT, Progress: approved, Small Changes, partners-contribution

#7706 Update composer.json examples
  src/guides/v2.3/extension-dev-guide/build/composer-integration.md
  src/guides/v2.3/extension-dev-guide/build/create_component.md
  src/guides/v2.3/extension-dev-guide/package/package_module.md
  src/guides/v2.3/howdoi/checkout/checkout-add-custom-carrier.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7711 Updates to VERBOSE_COMMANDS deploy and build variable description
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7713 Export option typo
  src/guides/v2.3/ui_comp_guide/components/ui-exportbutton.md
Labels: 2.4.x, Editorial, Progress: approved

#7629 GraphQL: Add section about CORS
  src/guides/v2.4/graphql/send-request.md
Labels: 2.4.1, Community, Internal Dev, Major Update, Progress: approved

#7655 GraphQL: Update customer/cart/store config queries to include reward points
  src/_includes/graphql/cart-object-24.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customer-output-24.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.1, Community, Internal Dev, Progress: approved, Technical

#7715 Remove the 'Contributed by' attribution from What's New template
  src/whats-new.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#7717 Marketplace format fix
  src/marketplace/sellers/profile-company.md
  src/marketplace/sellers/profile-information.md
  src/marketplace/sellers/profile-personal.md
Labels: Editorial, Internal Dev, Progress: approved

#7712 Update Compatibility Table and Prex Installation
  src/_data/mde.yml
  src/recommendations/install-configure.md
Labels: 2.4.x, Internal Dev, Progress: approved

#7719 GraphQL: Move section about custom config attributes
  src/guides/v2.3/graphql/develop/extend-existing-schema.md
  src/guides/v2.3/graphql/queries/store-config.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: approved

#7720 GraphQL: Reorganize storeConfig attributes
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.1, Editorial, Internal Dev, Progress: approved

#7721 GraphQL: Add Commerce icons to left nav
  src/_data/toc/graphql.yml
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#7705 magento/devdocs#7704 PHPStan update
  src/guides/v2.3/test/testing.md
  src/guides/v2.4/test/testing.md
Labels: 2.4.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#7703 Update Module status command for 2.4.1 version
  src/guides/v2.4/install-gde/install/cli/install-cli-subcommands-enable.md
Labels: 2.4.1, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7696 Updated notes and cleanup Cloud services setup topics
  src/_includes/cloud/service-config-integration-starter.md
  src/_includes/cloud/tip-change-installed-service-version.md
  src/cloud/project/project-conf-files_services-elastic.md
  src/cloud/project/project-conf-files_services-mysql.md
  src/cloud/project/project-conf-files_services-rabbit.md
  src/cloud/project/project-conf-files_services-redis.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7727 Magento 2.4.0 Release notes update 0812
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.4.0, Internal Dev, Progress: approved

#7650 GraphQL: Update Customer output object for credit memos
  src/_includes/graphql/customer-orders-output.md
Labels: 2.4.1, Internal Dev, Progress: approved, Technical

#7731 GraphQL: Add statement about cached/uncached queries
  src/guides/v2.3/graphql/caching.md
  src/guides/v2.4/graphql/caching.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Technical

#7733 Use proper menu label
  src/guides/v2.3/config-guide/multi-site/ms_websites.md
Labels: Progress: approved, Small Changes

#7729 Added release notes link to B2B Guide
  src/_data/toc/b2b-developer-guide.yml
Labels: 2.4.x, Progress: approved, Site Improvements

#7741 Magento 2.4.0 Release Notes update 0813
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: Progress: approved

#7714 GraphQL: Add support for Vault on Payflow Pro
  src/_data/toc/graphql.yml
  src/common/images/graphql/paypal-payflow-pro-vault.svg
  src/guides/v2.3/graphql/payment-methods/braintree-vault.md
  src/guides/v2.4/graphql/mutations/set-payment-method.md
  src/guides/v2.4/graphql/payment-methods/payflow-pro-vault.md
  src/guides/v2.4/graphql/payment-methods/payflow-pro.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.1, Community, Internal Dev, New Topic, Progress: approved

#7735 Update the Marketplace EQP API "Help" section
  src/marketplace/eqp/v1/help.md
Labels: 2.4.0, Editorial, Internal Dev, Progress: approved

#7737 Added missing TOC links
  src/_data/toc/ui-components-guide.yml
Labels: Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#7743 Small changes
  src/_data/toc/b2b-developer-guide.yml
  src/guides/v2.3/config-guide/multi-site/ms_websites.md
  src/guides/v2.3/extension-dev-guide/build/composer-integration.md
  src/guides/v2.3/extension-dev-guide/build/create_component.md
  src/guides/v2.3/extension-dev-guide/package/package_module.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/frontend-dev-guide/translations/translate_theory.md
  src/guides/v2.3/howdoi/checkout/checkout-add-custom-carrier.md
  src/guides/v2.3/ui_comp_guide/components/ui-exportbutton.md
  src/marketplace/eqp/v1/help.md
Labels: Progress: approved

#7744 fix typo and link update
  src/guides/v2.4/security/security-txt.md
Labels: 2.4.x, Editorial, Partner: Corra, Progress: approved, Small Changes, partners-contribution

#7746 Fix typo in index.md
  src/extensions/b2b/index.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Interactiv4, Progress: on hold, partners-contribution

#7728 MCLOUD-6708: Add notice that only Production mode is supported on cloud
  src/_includes/cloud/error-codes.md
  src/cloud/requirements/cloud-requirements.md
Labels: Internal Dev, Progress: approved

#7740 Update the Magento Packages topics
  src/_data/codebase/v2_3/cloud/composer_lock.json
  src/_data/codebase/v2_3/commerce/composer_lock.json
  src/_data/codebase/v2_3/open-source/composer_lock.json
  src/_data/codebase/v2_4/cloud/composer_lock.json
  src/_data/codebase/v2_4/commerce/composer_lock.json
  src/_data/codebase/v2_4/open-source/composer_lock.json
  src/_data/toc/release-notes.yml
  src/_includes/install/php-extensions-template.md
  src/_includes/install/php-versions-2.3.md
  src/_includes/install/php-versions-2.4.md
  src/_includes/install/php-versions-template.md
  src/_includes/install/php_2.0.md
  src/_includes/release-notes/packages.md
  src/guides/v2.3/install-gde/prereq/php-settings.md
  src/guides/v2.3/install-gde/prereq/prereq-overview.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.3/performance-best-practices/software.md
  src/guides/v2.3/release-notes/packages-commerce.md
  src/guides/v2.3/release-notes/packages-open-source.md
  src/guides/v2.4/install-gde/prereq/php-settings.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/performance-best-practices/software.md
  src/guides/v2.4/release-notes/packages-cloud.md
  src/guides/v2.4/release-notes/packages-commerce.md
  src/guides/v2.4/release-notes/packages-open-source.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: approved

#7749 Add links to the Magento Marketplace docs on the home page
  src/_data/main-nav.yml
  src/index.html
Labels: Editorial, Internal Dev, Progress: approved

#7662 GraphQL: Add mutations for applying/removing reward points
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/apply-reward-points.md
  src/guides/v2.4/graphql/mutations/remove-reward-points.md
Labels: 2.4.1, Community, Internal Dev, New Topic, Progress: approved

#7716 GraphQL: Add support for downloadable/gift card products in customer …
  src/_includes/graphql/customer-orders-output.md
Labels: 2.4.1, Internal Dev, Progress: approved, Technical

#7750 MCLOUD-6748: Update devdocs regarding Redis L2 cache
  src/cloud/env/variables-deploy.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7725 Update enable-disable-modules.md
  src/_includes/install/enable-disable-modules.md
Labels: Partner: Rave Digital, Progress: approved, Small Changes, partners-contribution

#7724 Update sample-data-other-cmds.md
  src/_includes/install/sampledata/sample-data-other-cmds.md
Labels: Editorial, Partner: Rave Digital, Progress: approved, Small Changes, partners-contribution

#7723 Update pre-release.md
  src/_includes/install/pre-release.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Rave Digital, Progress: approved, partners-contribution

#7722 Update install-quick-ref.md
  src/guides/v2.4/install-gde/install-quick-ref.md
Labels: 2.4.x, Editorial, Partner: Rave Digital, Progress: approved, Small Changes, partners-contribution

#7747 Fixed link definitions on cloud/live/stage-prod-test.html
  src/cloud/live/stage-prod-test.md
Labels: 2.x, Editorial, Progress: approved

#7751 Change Marketplace link text on home page
  src/guides/v2.3/index.html
  src/index.html
Labels: Editorial, Internal Dev, Maintenance, Progress: approved

#7753 Update Cloud CLI reference to latest version
  src/_data/codebase/cloud/magento-cloud.json
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7758 Update negotiable-update.md
  src/guides/v2.3/b2b/negotiable-update.md
Labels: 2.x, Editorial, Partner: Zilker Technology, Progress: approved, Small Changes, partners-contribution

#7754 Update whatsnew for 8-18
  src/_data/whats-new.yml
Labels: 2.4.x, Internal Dev, Progress: approved, Site Improvements

#7738 Update theme-best-practice.md with valid steps
  src/guides/v2.3/frontend-dev-guide/theme-best-practice.md
Labels: 2.3.x, 2.4.x, Major Update, Progress: approved, Technical

#7760 GraphQL: Update same_as_shipping description
  src/guides/v2.3/graphql/mutations/set-billing-address.md
  src/guides/v2.4/graphql/mutations/set-billing-address.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#7762 Db mftf newtopic
  src/_data/toc/mftf.yml
Labels: Progress: approved, Site Improvements

#7761 Clarify Elasticsearch version support for 2.4.0
  src/guides/v2.4/install-gde/system-requirements-tech.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved, Small Changes

#7745 GraphQL: Add coverage for gift wrapping and messages
  src/_data/toc/graphql.yml
  src/_includes/graphql/cart-object-24.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/gift-message.md
  src/_includes/graphql/gift-wrapping.md
  src/guides/v2.4/graphql/mutations/set-gift-options.md
  src/guides/v2.4/graphql/mutations/update-cart-items.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.1, Community, Internal Dev, New Topic, Progress: review

#7673 GraphQL: New mutations for managing customers
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/create-customer-v2.md
  src/guides/v2.4/graphql/mutations/create-customer.md
  src/guides/v2.4/graphql/mutations/update-customer-email.md
  src/guides/v2.4/graphql/mutations/update-customer-v2.md
  src/guides/v2.4/graphql/mutations/update-customer.md
Labels: 2.4.1, Community, Internal Dev, New Topic, Progress: approved

#7757 Reference DB Entrypoint Volume Option
  src/cloud/docker/docker-manage-database.md
Labels: 2.x, Progress: approved, Technical

#7763 Fixed the wrong links in the article "Private content"
  src/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
Labels: 2.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7773 Break symlinks
  src/guides/v2.4/graphql/product/grouped-product.md
  src/guides/v2.4/graphql/product/product-interface.md
Labels: 2.4.1, Maintenance, Progress: approved

#7768 Update fonts import with format specific
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#7639 Add new doc related to topic names generation for Async API
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/message-queues/async-topics.md
  src/guides/v2.4/extension-dev-guide/message-queues/async-topics.md
Labels: 2.3.x, New Topic, Partner: Comwrap, Progress: approved, partners-contribution

#7654 Add information about config files of async api
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/message-queues/async-message-queue-config-files.md
  src/guides/v2.4/extension-dev-guide/message-queues/async-message-queue-config-files.md
Labels: 2.3.x, New Topic, Partner: Comwrap, Progress: approved, partners-contribution

#7776 Fixed a bookmark bug
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: 2.x, Progress: approved, Technical

#7769 Added Azure IP addresses
  src/cloud/cdn/cloud-fastly.md
  src/cloud/env/environments-start.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7770 GraphQL: Add coverage for wishlist items
  src/_data/toc/graphql.yml
  src/_includes/graphql/entered-option-input.md
  src/_includes/graphql/wishlist-user-input-errors.md
  src/_includes/graphql/wishlist.md
  src/guides/v2.4/graphql/mutations/add-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/remove-products-from-wishlist.md
  src/guides/v2.4/graphql/mutations/update-products-in-wishlist.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.1, Community, Internal Dev, New Topic, Progress: approved

#7734 Add Magento Quality Patch package documentation
  src/_data/toc/software-update-guide.yml
  src/cloud/env/variables-build.md
  src/cloud/project/ece-tools-update.md
  src/cloud/project/project-patch.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/guides/v2.3/comp-mgr/patching.md
  src/quality-patches/release-notes.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: review

#7772 Update Inventory REST tutorial to include in-store pickup
  src/_data/toc/rest-api.yml
  src/_includes/webapi/tutorials/configure-shipping-methods-24.md
  src/_includes/webapi/tutorials/set-payment-methods.md
  src/guides/v2.4/rest/tutorials/inventory/configure-environment.md
  src/guides/v2.4/rest/tutorials/inventory/create-customer.md
  src/guides/v2.4/rest/tutorials/inventory/create-invoice.md
  src/guides/v2.4/rest/tutorials/inventory/create-order.md
  src/guides/v2.4/rest/tutorials/inventory/create-shipment.md
  src/guides/v2.4/rest/tutorials/inventory/create-sources.md
  src/guides/v2.4/rest/tutorials/inventory/in-store-pickup.md
  src/guides/v2.4/rest/tutorials/inventory/index.md
Labels: 2.4.0, Community, Internal Dev, New Topic, Progress: approved

#7781 Update custom-validation.md
  src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#7782 Fix list of allowed attributes in escaper
  src/guides/v2.3/extension-dev-guide/xss-protection.md
  src/guides/v2.4/extension-dev-guide/xss-protection.md
Labels: Progress: approved

#7780 Update Marketplace EQP API - files.md
  src/marketplace/eqp/v1/files.md
Labels: Internal Dev, Progress: approved

#7778 Update data_hash information of Bulk requests
  src/guides/v2.3/rest/asynchronous-web-endpoints.md
  src/guides/v2.3/rest/bulk-endpoints.md
  src/guides/v2.3/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.md
  src/guides/v2.3/rest/tutorials/bulk-configurable-product/create-personalization-option.md
  src/guides/v2.3/rest/tutorials/bulk-configurable-product/define-config-product-options.md
Labels: 2.3.x, Partner: Comwrap, Progress: approved, Technical, partners-contribution

#7784 Update message-queue-consumers.md
  src/_includes/config/message-queue-consumers.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7785 Update CLI tools reference
  src/_includes/reference/cli-template.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7775 GraphQL: Add coverage for product reviews
  src/_data/toc/graphql.yml
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/product-review.md
  src/guides/v2.4/graphql/mutations/create-product-review.md
  src/guides/v2.4/graphql/product/product-interface.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/graphql/queries/product-review-ratings-metadata.md
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4.1, Community, Internal Dev, New Topic, Progress: approved

#7788 Updated supported and recommended elasticsearch version
  src/_includes/cloud/cloud-elasticsearch-client-compatibility.md
  src/cloud/project/project-conf-files_services.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7774 magento/devdocs#7367: Added the article "addProductsToCart mutation"
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/add-bundle-products.md
  src/guides/v2.4/graphql/mutations/add-configurable-products.md
  src/guides/v2.4/graphql/mutations/add-downloadable-products.md
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
  src/guides/v2.4/graphql/mutations/add-simple-products.md
  src/guides/v2.4/graphql/mutations/add-virtual-products.md
Labels: 2.4.1, Community, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#7790 GraphQL: Minor fixes
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
  src/guides/v2.4/graphql/mutations/add-products-to-wishlist.md
  src/guides/v2.4/graphql/mutations/create-customer-v2.md
  src/guides/v2.4/graphql/mutations/create-customer.md
  src/guides/v2.4/graphql/mutations/update-customer-v2.md
  src/guides/v2.4/graphql/mutations/update-customer.md
Labels: 2.4.1, Internal Dev, Technical
