Repository magento/devdocs, pull requests merged in 2020-04, with the labels that each got.

#6886 Adding a custom form validation topic
  src/_data/toc/frontend-developer-guide.yml
  src/common/images/form-validation-result.png
  src/guides/v2.3/frontend-dev-guide/validations/custom-form-validation.md
  src/guides/v2.3/frontend-dev-guide/validations/form-validation.md
Labels: 2.3.x, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#6937 Added example on how to adjust the validation message for specific form field
  src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#6949 Making the large code snippets scrollable
  src/common/css/devdocs.css
Labels: Partner: Atwix, Progress: approved, partners-contribution

#6957 2.3.5 Integration branch
  src/_data/toc/configuration-guide.yml
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/config-guide/cache/two-level-cache.md
  src/guides/v2.3/config-guide/redis/redis-pg-cache.md
  src/guides/v2.3/extension-dev-guide/security/content-security-policies.md
Labels: 2.3.5, Internal Dev, Maintenance, Progress: approved

#6965 Moved Docker/DevDocs build steps to the wiki
  README.md
Labels: Internal Dev, Maintenance, Progress: approved

#6946 Enrich the Creating an Access Control List (ACL) rule doc
  src/common/images/ext-best-practices/acl-admin-limited-page-content.jpg
  src/common/images/ext-best-practices/acl-admin-page-content-full-access.jpg
  src/common/images/ext-best-practices/custom_menu.jpg
  src/common/images/ext-best-practices/custom_menu.png
  src/guides/v2.3/ext-best-practices/tutorials/create-access-control-list-rule.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#6898 [GraphQL] Added mutationTypes query in Introspection queries example
  src/guides/v2.3/graphql/queries/index.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6967 Add BIC reference for 2.3.5 (pre-release)
  src/guides/v2.3/release-notes/backward-incompatible-changes/index.md
  src/guides/v2.3/release-notes/backward-incompatible-changes/reference.md
  src/release/policy/index.md
Labels: 2.3.5, Internal Dev, Major Update, Progress: approved

#6709 Use delegated mounts to improve performance
  src/cloud/docker/docker-config.md
Labels: Progress: approved, Small Changes, Technical

#6897 [GraphQL] Add 'customer notes' attribute to shippingCartAddress object
  src/guides/v2.3/graphql/queries/cart.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6961 [GraphQL] Removed deprecated field from graphql query
  src/guides/v2.3/graphql/queries/customer.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, partners-contribution

#6927 Added information about outerClickHandler option
  src/guides/v2.3/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6973 GraphQL: Fix attribute data type
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
Labels: Progress: approved

#6976 jdk 8 install command updated
  src/_includes/config/install-java8.md
Labels: 2.3.x, Community Insider: Cedcommerce, Progress: approved, Technical, community-insider-contribution

#6977 MCLOUD-3063: Provide an Option to Specify Custom URL for Magento
  src/cloud/docker/docker-config.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#6982 Magento 2.3.5 Release Notes -- Pre-release version
  src/_data/toc/release-notes.yml
  src/_includes/release-notes/engcomm-2-3-5-issues.md
  src/_includes/release-notes/engcomm-2-3-5-partner.md
  src/guides/v2.3/release-notes/bk-release-notes.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: Progress: approved

#6984 magento/devdocs#6971: Container section `label` has insufficient description
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.3.x, Editorial, Event: Global-Contribution-Day-2020, Partner: Atwix, Progress: approved, partners-contribution

#6985 Revert inaccurate change
  src/guides/v2.3/extension-dev-guide/build/create_component.md
Labels: 2.3.x, 2.4.x, Editorial, Event: Global-Contribution-Day, Internal Dev, Progress: approved

#6983 magento/devdocs#: Configure Xdebug. Wrong port.
  src/cloud/howtos/debug.md
Labels: Contribution Day, Event: Global-Contribution-Day, Partner: Atwix, Progress: approved, partners-contribution

#6980 Fix the API GET request functionality
  src/guides/v2.3/rest/notes.md
Labels: Progress: approved

#6987 The gallery jQuery widget more view thumbnails in mobile
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md
Labels: Contribution Day, Event: Global-Contribution-Day, Partner: Krish TechnoLabs, Progress: approved, Technical, partners-contribution

#6988 Add missing tags that can be specified in the page <head> section
  src/guides/v2.3/frontend-dev-guide/layouts/layout-types.md
Labels: 2.3.x, Editorial, Event: Global-Contribution-Day, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#6986 Sortby component documentation
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/ui-sortby-result.png
  src/guides/v2.4/ui_comp_guide/components/ui-sortby.md
Labels: 2.4.0, Event: Global-Contribution-Day, New Topic, Progress: approved

#6996 Sync 2.3.5 and master
  README.md
  src/_data/toc/frontend-developer-guide.yml
  src/_data/whats-new.yml
  src/_includes/config/install-java8.md
  src/cloud/docker/docker-config.md
  src/common/css/devdocs.css
  src/common/images/ext-best-practices/acl-admin-limited-page-content.jpg
  src/common/images/ext-best-practices/acl-admin-page-content-full-access.jpg
  src/common/images/ext-best-practices/custom_menu.jpg
  src/common/images/ext-best-practices/custom_menu.png
  src/common/images/form-validation-result.png
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
  src/guides/v2.3/ext-best-practices/tutorials/create-access-control-list-rule.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-types.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/frontend-dev-guide/validations/custom-form-validation.md
  src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
  src/guides/v2.3/frontend-dev-guide/validations/form-validation.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/queries/index.md
  src/guides/v2.3/graphql/send-request.md
  src/guides/v2.3/install-gde/prereq/install-rabbitmq.md
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_modal.md
  src/guides/v2.3/performance-best-practices/advanced-js-bundling.md
  src/guides/v2.3/rest/notes.md
  src/guides/v2.3/rest/tutorials/orders/order-add-items.md
  src/guides/v2.3/rest/tutorials/orders/order-admin-token.md
  src/guides/v2.3/rest/tutorials/orders/order-create-customer.md
  src/guides/v2.3/rest/tutorials/orders/order-create-invoice.md
  src/guides/v2.3/rest/tutorials/orders/order-create-order.md
  src/guides/v2.3/rest/tutorials/orders/order-create-quote.md
  src/guides/v2.3/rest/tutorials/orders/order-create-shipment.md
  src/guides/v2.3/rest/tutorials/orders/order-issue-refund.md
  src/guides/v2.3/rest/tutorials/orders/order-prepare-checkout.md
  src/recommendations/images/arch-diag-sensei.svg
  src/recommendations/product-recs.md
Labels: 2.3.x, Maintenance, Progress: approved

#6989 Add html example for adding a new class to the <body> tag
  src/common/images/body-class-result.png
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: Event: Global-Contribution-Day, Partner: Krish TechnoLabs, Progress: approved, Technical, partners-contribution

#7001 GraphQL: Remove section from resolvers topic
  src/guides/v2.3/graphql/develop/resolvers.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#6998 Fix ELASTICSUITE_CONFIGURATION example for Cloud
  src/cloud/env/variables-deploy.md
Labels: 2.x, Internal Dev, Progress: approved

#6999 Corrections to Upgrade Magento version topic in Cloud Guide
  src/cloud/project/log-locations.md
  src/cloud/project/project-upgrade.md
  src/cloud/requirements/cloud-requirements.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7002 Sync 2.4.0-develop
  README.md
  src/_data/toc/configuration-guide.yml
  src/_data/toc/frontend-developer-guide.yml
  src/_data/toc/php-developer-guide.yml
  src/_data/toc/release-notes.yml
  src/_data/whats-new.yml
  src/_includes/config/install-java8.md
  src/_includes/release-notes/engcomm-2-3-5-issues.md
  src/_includes/release-notes/engcomm-2-3-5-partner.md
  src/cloud/docker/docker-config.md
  src/common/css/devdocs.css
  src/common/images/ext-best-practices/acl-admin-limited-page-content.jpg
  src/common/images/ext-best-practices/acl-admin-page-content-full-access.jpg
  src/common/images/ext-best-practices/custom_menu.jpg
  src/common/images/ext-best-practices/custom_menu.png
  src/common/images/fdg/tooltip-element-result.png
  src/common/images/form-validation-result.png
  src/guides/v2.3/config-guide/cache/two-level-cache.md
  src/guides/v2.3/config-guide/redis/redis-pg-cache.md
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
  src/guides/v2.3/ext-best-practices/tutorials/create-access-control-list-rule.md
  src/guides/v2.3/extension-dev-guide/security/content-security-policies.md
  src/guides/v2.3/frontend-dev-guide/css-topics/theme-ui-lib.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-types.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/frontend-dev-guide/validations/custom-form-validation.md
  src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
  src/guides/v2.3/frontend-dev-guide/validations/form-validation.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/queries/index.md
  src/guides/v2.3/graphql/send-request.md
  src/guides/v2.3/install-gde/prereq/install-rabbitmq.md
  src/guides/v2.3/install-gde/prereq/mysql.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_modal.md
  src/guides/v2.3/performance-best-practices/advanced-js-bundling.md
  src/guides/v2.3/release-notes/backward-incompatible-changes/index.md
  src/guides/v2.3/release-notes/backward-incompatible-changes/reference.md
  src/guides/v2.3/release-notes/bk-release-notes.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
  src/guides/v2.3/rest/notes.md
  src/guides/v2.3/rest/tutorials/orders/order-add-items.md
  src/guides/v2.3/rest/tutorials/orders/order-admin-token.md
  src/guides/v2.3/rest/tutorials/orders/order-create-customer.md
  src/guides/v2.3/rest/tutorials/orders/order-create-invoice.md
  src/guides/v2.3/rest/tutorials/orders/order-create-order.md
  src/guides/v2.3/rest/tutorials/orders/order-create-quote.md
  src/guides/v2.3/rest/tutorials/orders/order-create-shipment.md
  src/guides/v2.3/rest/tutorials/orders/order-issue-refund.md
  src/guides/v2.3/rest/tutorials/orders/order-prepare-checkout.md
  src/guides/v2.4/config-guide/cache/two-level-cache.md
  src/guides/v2.4/extension-dev-guide/security/content-security-policies.md
  src/guides/v2.4/frontend-dev-guide/validations/custom-form-validation.md
  src/recommendations/images/arch-diag-sensei.svg
  src/recommendations/product-recs.md
  src/release/policy/index.md
Labels: 2.4.x, Maintenance, Progress: approved

#6968 "Events and observers" page: Added warning about overriding observer by using existing name.
  src/guides/v2.3/extension-dev-guide/events-and-observers.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, partners-contribution

#6993 magento/devdocs#: Layout instructions. Adding information to the topic
  src/guides/v2.3/extension-dev-guide/message-queues/refresh-config.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#6994 Update custom-import-entity.md
  src/guides/v2.3/ext-best-practices/tutorials/custom-import-entity.md
Labels: 2.3.x, Partner: Smile, Progress: approved, Technical, partners-contribution

#6995 How to place view.xml from parent and Blank theme
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#7003 Add security releases to the patch calendar
  src/release/index.md
Labels: Editorial, Internal Dev, Progress: review

#6934 Extend description of debugging CLI command on Pro Staging and Production
  src/cloud/howtos/debug.md
Labels: 2.x, Internal Dev, Progress: approved, Technical, Waiting for Response

#6978 Create a topic about the Adobe Privacy JavaScript Library
  src/_data/toc/compliance.yml
  src/compliance/industry-compliance.md
  src/compliance/privacy/adobe-privacy-js-library.md
Labels: New Topic, Progress: approved

#6964 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.0, Progress: approved, Technical

#6990 Customize Product view page help of many containers
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
Labels: 2.3.x, Event: Global-Contribution-Day, Major Update, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#7005 Publish changes from the 2020 global contribution day event
  src/cloud/howtos/debug.md
  src/guides/v2.3/extension-dev-guide/build/create_component.md
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md
Labels: Progress: approved

#7004 Update theme.js file name
  src/guides/v2.3/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Progress: approved, Technical, partners-contribution

#7006 magento/devdocs#: How to declare a new CLI command via __construct method
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7009 remove leading backslash when importing namespaces
  src/guides/v2.3/extension-dev-guide/build/component-registration.md
Labels: 2.3.x, Progress: approved, Technical

#7010 #7008 Clarify Configure Consumers page
  src/_data/toc/installation-guide.yml
  src/_includes/config/consumers.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-consumers.md
Labels: 2.3.x, Editorial, Progress: approved

#7016 Update cli-howto.md
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.3.x, Partner: Webjump, Progress: approved, Technical, partners-contribution

#7014 remove spaces for non-alignment example
  src/guides/v2.3/coding-standards/docblock-standard-general.md
Labels: 2.3.x, Editorial, Progress: approved

#7015 Fixes config for register sample files
  src/guides/v2.3/ext-best-practices/tutorials/custom-import-entity.md
Labels: 2.3.x, Partner: Smile, Progress: approved, Technical, partners-contribution

#7012 Bundle update and HTML fixing
  Gemfile.lock
  _config.yml
  src/cloud/architecture/pro-architecture.md
  src/guides/v2.3/coding-standards/docblock-standard-javascript.md
  src/guides/v2.3/contributor-guide/contributing_docs_suggested.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-types.md
  src/guides/v2.3/ui_comp_guide/components/ui-massactions.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_xmlconfig_structure.md
Labels: Maintenance, Progress: approved, Site Improvements

#7013 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: Progress: approved

#7021 PB-313: Using attributes to apply CSS styling
  src/_data/toc/page-builder.yml
Labels: 2.3.x, Progress: approved

#7011 Remove EAP references
  src/_data/toc/product-recommendations.yml
  src/_includes/layout/page-header.html
  src/recommendations/configure.md
  src/recommendations/images/cfg-api-key.png
  src/recommendations/images/get-api-key.png
  src/recommendations/install-configure.md
  src/recommendations/product-recs.md
  src/recommendations/support.md
  src/recommendations/test.md
  src/recommendations/troubleshooting.md
  src/recommendations/verify.md
Labels: 2.3.5, Internal Dev, Progress: approved

#6979 Update setup:install command to include Elasticsearch flags
  src/guides/v2.4/install-gde/install/cli/install-cli-install.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#7025 GraphQL: Update index page
  src/guides/v2.3/graphql/images/graphql-browser.png
  src/guides/v2.3/graphql/index.md
Labels: 2.3.x, Editorial, Internal Dev, Progress: approved

#7030 MCLOUD-5658: Add support of 2.3 release-line for URL-rewrites module
  src/cloud/configure/import-url-rewrites.md
Labels: 2.x, Internal Dev, Progress: approved

#7018 Replace misstaken vendor name in 2.3.5 Vertex release notes
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.5, Editorial, Partner: Mediotype, Progress: approved, Technology Partner: Vertex, partners-contribution, tech-partners-contribution

#7028 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.0, Automation, Progress: approved, Technical

#6823 magento/devdocs#: Layout instructions. Adding more information about cURL [GITBUG]
  src/guides/v2.3/get-started/gs-curl.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#6826 magento/devdocs#: Layout instructions. Adding more examples to Public interfaces & APIs [GITBUG]
  src/guides/v2.3/extension-dev-guide/api-concepts.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#6827 magento/devdocs#: Layout instructions. Adding missing Metadata interfaces info. [GITBUG]
  src/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#7034 Updating Redoc js version
  src/_layouts/redoc.html
Labels: Progress: approved, Site Improvements

#7020 Content security policy intro
  src/_data/main-nav.yml
  src/_data/toc/compliance.yml
  src/security/content-security-policy-overview.md
  src/security/security-and-compliance.md
Labels: 2.3.5, Internal Dev, New Topic, Progress: approved

#7037 Magento privacy library
  src/_data/toc/compliance.yml
  src/compliance/industry-compliance.md
  src/compliance/privacy/__adobe-privacy-js-library.md
  src/compliance/privacy/magento-privacy-js-library.md
Labels: New Topic, Progress: approved

#7041 Adding cookie restriction note
  src/compliance/privacy/magento-privacy-js-library.md
  src/recommendations/events.md
  src/recommendations/verify.md
Labels: 2.3.x, Editorial, Progress: approved

#7019 Functional testing instructions for Magento Cloud code contributions
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-testing-components.md
  src/cloud/docker/docker-development-testing-docker.md
  src/cloud/docker/docker-development-testing-patches.md
  src/cloud/docker/docker-development-testing.md
  src/cloud/docker/docker-test-app-mftf.md
  src/cloud/docker/docker-test-magecloud-pkg-code.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/project-patch.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#7043 Adding ES troubleshooting entry
  src/cloud/docker/docker-containers-service.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7044 PB-480: Update content type styling concepts
  src/_data/toc/page-builder.yml
Labels: 2.3.x, Internal Dev, Major Update, Progress: approved, Technical

#7040 Cloud: remove statement to call support
  src/cloud/project/project-upgrade.md
Labels: Internal Dev, Progress: approved, Small Changes

#7036 Adding redirect to troubleshooting topic in kb
  src/recommendations/troubleshooting.md
Labels: 2.3.x, Editorial, Internal Dev, Progress: approved

#7045 magento/devdocs#7029: for text column in db_schema the attribute 'length' is not allowed.
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7047 Db B2B release notes for 2.3.5
  src/_data/toc/release-notes.yml
  src/guides/v2.3/release-notes/b2b-release-notes.md
Labels: 2.3.5, New Topic, Progress: approved

#7024 Added initial Version of a reference for the system.xml
  src/_data/toc/configuration-guide.yml
  src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
  src/guides/v2.3/config-guide/prod/img/magento2-system-configuration.png
Labels: 2.3.x, New Topic, Progress: approved, Special achievement

#7042 Clarify PHP version support and fix format errors
  src/cloud/configure/import-url-rewrites.md
Labels: 2.x, Internal Dev, Progress: approved, Small Changes

#7054 Add redirect for deprecated Blackfire.io content
  src/cloud/project/project-integrate-blackfire.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7055 Add deprecation notice for Authorize.Net payment method
  src/guides/v2.3/graphql/payment-methods/authorize-net.md
Labels: 2.3.5, Internal Dev, Progress: approved, Technical

#7061 Updating base_amount attribute in cart object graphql
  src/_includes/graphql/cart-object.md
  src/guides/v2.3/graphql/queries/cart.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#7062 Add missing word in command
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: Partner: Ziffity, Progress: approved, Small Changes, partners-contribution

#7050 Update product recommendations module names
  src/recommendations/events.md
  src/recommendations/images/filter-tp2.png
  src/recommendations/install-configure.md
  src/recommendations/product-recs.md
  src/recommendations/test.md
  src/recommendations/verify.md
Labels: Progress: approved

#7064 DEVDOCS-7063: Fixed link for Magento Cloud CLI reference page
  src/cloud/setup/first-time-setup-import-first-steps.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#7057 magento/devdocs#: Add info about column types for which we can set a `length` attribute
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#7035 Added new note about API usage
  src/_data/toc/rest-api.yml
  src/guides/v2.3/rest/notes.md
Labels: 2.3.x, Major Update, Progress: approved

#7022 Fix Indentation
  src/guides/v2.3/migration/migration-tool-configure.md
Labels: 2.3.x, Editorial, Progress: approved

#7053 Clarify "most popular" recommendation name
  src/recommendations/test.md
Labels: 2.3.x, Editorial, Internal Dev, Progress: approved

#7067 Sync 2.3.5-develop
  src/_data/toc/compliance.yml
  src/_data/toc/configuration-guide.yml
  src/_data/toc/page-builder.yml
  src/_data/toc/rest-api.yml
  src/_includes/graphql/cart-object.md
  src/_layouts/redoc.html
  src/cloud/configure/import-url-rewrites.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/project/project-integrate-blackfire.md
  src/cloud/project/project-upgrade.md
  src/cloud/setup/first-time-setup-import-first-steps.md
  src/compliance/industry-compliance.md
  src/compliance/privacy/__adobe-privacy-js-library.md
  src/compliance/privacy/magento-privacy-js-library.md
  src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
  src/guides/v2.3/config-guide/prod/img/magento2-system-configuration.png
  src/guides/v2.3/extension-dev-guide/api-concepts.md
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  src/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/get-started/gs-curl.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/rest/notes.md
  src/recommendations/events.md
  src/recommendations/images/filter-tp2.png
  src/recommendations/install-configure.md
  src/recommendations/product-recs.md
  src/recommendations/test.md
  src/recommendations/troubleshooting.md
  src/recommendations/verify.md
Labels: 2.3.5, Maintenance, Progress: approved

#7066 Typo fix from abandoned PR
  src/guides/v2.3/extension-dev-guide/xss-protection.md
Labels: 2.3.x, Editorial, Progress: approved

#7070 Sync 2.4.0-develop
  rakelib/symlink.rake
  src/_data/main-nav.yml
  src/_data/toc/compliance.yml
  src/_data/toc/configuration-guide.yml
  src/_data/toc/page-builder.yml
  src/_data/toc/release-notes.yml
  src/_data/toc/rest-api.yml
  src/_includes/graphql/cart-object.md
  src/_layouts/redoc.html
  src/cloud/configure/import-url-rewrites.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/project/project-integrate-blackfire.md
  src/cloud/project/project-upgrade.md
  src/cloud/setup/first-time-setup-import-first-steps.md
  src/compliance/industry-compliance.md
  src/compliance/privacy/__adobe-privacy-js-library.md
  src/compliance/privacy/magento-privacy-js-library.md
  src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
  src/guides/v2.3/config-guide/prod/img/magento2-system-configuration.png
  src/guides/v2.3/extension-dev-guide/api-concepts.md
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  src/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/get-started/gs-curl.md
  src/guides/v2.3/graphql/payment-methods/authorize-net.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/migration/migration-tool-configure.md
  src/guides/v2.3/release-notes/b2b-release-notes.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
  src/guides/v2.3/rest/notes.md
  src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
  src/guides/v2.4/config-guide/prod/img/magento2-system-configuration.png
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/recommendations/events.md
  src/recommendations/images/filter-tp2.png
  src/recommendations/install-configure.md
  src/recommendations/product-recs.md
  src/recommendations/test.md
  src/recommendations/troubleshooting.md
  src/recommendations/verify.md
  src/security/content-security-policy-overview.md
  src/security/security-and-compliance.md
Labels: 2.4.0, Maintenance, Progress: approved

#7065 Break symlinks for inventory REST tutorial
  src/guides/v2.4/rest/tutorials/inventory/assign-source-to-stock.md
  src/guides/v2.4/rest/tutorials/inventory/bulk-transfer-products.md
  src/guides/v2.4/rest/tutorials/inventory/configure-environment.md
  src/guides/v2.4/rest/tutorials/inventory/create-cart-add-products.md
  src/guides/v2.4/rest/tutorials/inventory/create-customer.md
  src/guides/v2.4/rest/tutorials/inventory/create-invoice.md
  src/guides/v2.4/rest/tutorials/inventory/create-order.md
  src/guides/v2.4/rest/tutorials/inventory/create-shipment.md
  src/guides/v2.4/rest/tutorials/inventory/create-sources.md
  src/guides/v2.4/rest/tutorials/inventory/create-stock.md
  src/guides/v2.4/rest/tutorials/inventory/index.md
  src/guides/v2.4/rest/tutorials/inventory/prepare-for-checkout.md
  src/guides/v2.4/rest/tutorials/inventory/reassign-products-to-another-source.md
  src/guides/v2.4/rest/tutorials/inventory/run-ssa.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7038 Added information about the missing settings to serve Magento app from `/pub` directory
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
  src/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.md
Labels: Progress: approved

#7056 GraphQL: Remove Authorize.Net payment method for 2.4
  src/_data/toc/graphql.yml
  src/_data/whats-new.yml
  src/guides/v2.4/graphql/mutations/set-payment-method.md
  src/guides/v2.4/graphql/payment-methods/authorize-net.md
  src/guides/v2.4/graphql/release-notes.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7072 Irrelevant site url
  src/guides/v2.3/config-guide/multi-site/ms_websites.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#7031 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.0, Automation, Progress: approved, Technical

#7073 Update Contributor Assistance Documentation on issue self-assign automation
  src/guides/v2.3/contributor-guide/contributing.md
Labels: 2.3.x, Major Update, Progress: approved

#7039 Update installation wizard for Elasticsearch
  src/_data/toc/configuration-guide.yml
  src/_data/toc/installation-guide.yml
  src/_includes/config/es-elasticsearch-magento-24.md
  src/_includes/config/es-verify-proxy-24.md
  src/_includes/install/flow-diagram-24.md
  src/common/images/install-diagram-24.png
  src/common/images/install-qr-admin-24.png
  src/common/images/install-qr-catalog-search-24.png
  src/common/images/install-qr-catalog-search.png
  src/common/images/install-qr-database-24.png
  src/common/images/install-qr-readiness-24.png
  src/common/images/install-qr-store-24.png
  src/common/images/install-qr-web-24.png
  src/guides/v2.4/config-guide/bk-config-guide.md
  src/guides/v2.4/config-guide/elasticsearch/configure-magento.md
  src/guides/v2.4/config-guide/elasticsearch/es-config-apache.md
  src/guides/v2.4/config-guide/elasticsearch/es-config-nginx.md
  src/guides/v2.4/config-guide/elasticsearch/es-downgrade.md
  src/guides/v2.4/config-guide/elasticsearch/es-overview.md
  src/guides/v2.4/install-gde/basics/basics_software.md
  src/guides/v2.4/install-gde/install-flow-diagram.md
  src/guides/v2.4/install-gde/install-quick-ref.md
  src/guides/v2.4/install-gde/install-resource-diagram.md
  src/guides/v2.4/install-gde/install/cli/install-cli-install.md
  src/guides/v2.4/install-gde/install/hosted/hosted_get-ftp.md
  src/guides/v2.4/install-gde/install/hosted/hosted_install.md
  src/guides/v2.4/install-gde/install/hosted/hosted_install_1_readiness.md
  src/guides/v2.4/install-gde/install/hosted/hosted_install_2_db.md
  src/guides/v2.4/install-gde/install/hosted/hosted_install_3_web-conf.md
  src/guides/v2.4/install-gde/install/hosted/hosted_install_4_customize-store.md
  src/guides/v2.4/install-gde/install/hosted/hosted_install_5_create-admin.md
  src/guides/v2.4/install-gde/install/hosted/hosted_install_6_install.md
  src/guides/v2.4/install-gde/install/hosted/hosted_start.md
  src/guides/v2.4/install-gde/install/hosted/hosted_start_db.md
  src/guides/v2.4/install-gde/install/hosted/hosted_start_php.md
  src/guides/v2.4/install-gde/install/post-install-config.md
  src/guides/v2.4/install-gde/install/web/install-web-configure-catalog-search.md
  src/guides/v2.4/install-gde/install/web/install-web_1-readiness.md
  src/guides/v2.4/install-gde/install/web/install-web_2-db.md
  src/guides/v2.4/install-gde/install/web/install-web_3-web-conf.md
  src/guides/v2.4/install-gde/install/web/install-web_4-customize-store.md
  src/guides/v2.4/install-gde/install/web/install-web_5-create-admin.md
  src/guides/v2.4/install-gde/install/web/install-web_6-install.md
  src/guides/v2.4/install-gde/prereq/elasticsearch.md
  src/guides/v2.4/install-gde/prereq/es-config-apache.md
  src/guides/v2.4/install-gde/prereq/es-config-nginx.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/install-gde/system-requirements-tech.md
  src/guides/v2.4/install-gde/system-requirements.md
  src/guides/v2.4/performance-best-practices/software.md
Labels: 2.4.0, Internal Dev, Major Update, Progress: approved

#6852 MAGECLOUD-4894: [MTS] Add support of split DB on docker
  src/cloud/docker/docker-manage-database.md
  src/cloud/docker/docker-split-db.md
Labels: Internal Dev, Progress: approved

#7078 PHP settings - removed asp_tags, fixed typos/markup, links
  src/guides/v2.3/install-gde/prereq/php-settings.md
Labels: 2.3.x, Progress: approved, Technical

#7076 Fix incorrect line numbers
  src/guides/v2.3/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: 2.3.x, Progress: approved

#7080 Removed deprecated attribute from graphql query
  src/guides/v2.3/graphql/queries/customer.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7082 Document Developers Portal requirements for submission
  src/marketplace/sellers/technical-review-guidelines.md
Labels: 2.3.x, Internal Dev, Major Update, Progress: approved

#7083 Update for product recommendations
  src/release/index.md
Labels: 2.3.5, Internal Dev, Progress: approved

#7085 Wrong cli commands
  src/_includes/config/split-db.md
  src/_includes/install/cli_help-commands.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7086 Bulk changes in cli commands
  src/guides/v2.3/config-guide/varnish/use-multiple-varnish-cache.md
  src/guides/v2.3/config-guide/varnish/use-varnish-cache.md
  src/guides/v2.3/install-gde/install/cli/install-cli-adminurl.md
  src/guides/v2.3/install-gde/install/cli/install-cli-install.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-consumers.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-db-status.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-db.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-deployment.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-lock.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-maint.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-store.md
  src/guides/v2.3/install-gde/install/cli/install-cli-theme-uninstall.md
  src/guides/v2.3/install-gde/install/cli/install-cli-uninstall-langpk.md
  src/guides/v2.3/install-gde/install/cli/install-cli-uninstall-mods.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#7088 Textarea ui component example improvements
  src/guides/v2.3/ui_comp_guide/components/ui-textarea.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#7079 Add whats new items
  src/_data/whats-new.yml
Labels: 2.x, Editorial, Progress: approved

#7087 Removed deprecated MTF docs
  src/_data/main-nav.yml
  src/_data/toc/functional-testing-framework-guide.yml
  src/guides/v2.3/architecture/tech-stack.md
  src/guides/v2.3/extension-dev-guide/validate/test-module.md
  src/guides/v2.3/mtf/configuration.md
  src/guides/v2.3/mtf/create_test.md
  src/guides/v2.3/mtf/create_test/create_new_test.md
  src/guides/v2.3/mtf/create_test/new_test.md
  src/guides/v2.3/mtf/create_test/out-of-the-box.md
  src/guides/v2.3/mtf/features.md
  src/guides/v2.3/mtf/features/isolation.md
  src/guides/v2.3/mtf/features/modularity.md
  src/guides/v2.3/mtf/features/parallel_execution.md
  src/guides/v2.3/mtf/features/reporting.md
  src/guides/v2.3/mtf/features/test_suite.md
  src/guides/v2.3/mtf/features/webdriver.md
  src/guides/v2.3/mtf/mtf_entities.md
  src/guides/v2.3/mtf/mtf_entities/mtf_block.md
  src/guides/v2.3/mtf/mtf_entities/mtf_constraint.md
  src/guides/v2.3/mtf/mtf_entities/mtf_dataset.md
  src/guides/v2.3/mtf/mtf_entities/mtf_fixture-repo.md
  src/guides/v2.3/mtf/mtf_entities/mtf_fixture.md
  src/guides/v2.3/mtf/mtf_entities/mtf_handler.md
  src/guides/v2.3/mtf/mtf_entities/mtf_page.md
  src/guides/v2.3/mtf/mtf_entities/mtf_scenariotest.md
  src/guides/v2.3/mtf/mtf_entities/mtf_testcase.md
  src/guides/v2.3/mtf/mtf_entities/mtf_typified-element.md
  src/guides/v2.3/mtf/mtf_installation.md
  src/guides/v2.3/mtf/mtf_introduction.md
  src/guides/v2.3/mtf/mtf_quickstart.md
  src/guides/v2.3/mtf/mtf_quickstart/mtf_quickstart_config.md
  src/guides/v2.3/mtf/mtf_quickstart/mtf_quickstart_environment.md
  src/guides/v2.3/mtf/mtf_quickstart/mtf_quickstart_logs.md
  src/guides/v2.3/mtf/mtf_quickstart/mtf_quickstart_magento.md
  src/guides/v2.3/mtf/mtf_quickstart/mtf_quickstart_runtest.md
  src/guides/v2.3/mtf/mtf_update.md
  src/guides/v2.3/mtf/troubleshooting.md
  src/guides/v2.3/test/testing.md
Labels: Internal Dev, Maintenance, Progress: approved

#7090 Remove Google Shopping ads content
  src/_data/toc/extensions.yml
  src/_data/toc/release-notes.yml
  src/_data/whats-new.yml
  src/extensions/google-shopping-ads/images/apikey.png
  src/extensions/google-shopping-ads/images/config-api-key.png
  src/extensions/google-shopping-ads/images/config-api-portal.png
  src/extensions/google-shopping-ads/images/update.png
  src/extensions/google-shopping-ads/index.md
  src/extensions/google-shopping-ads/release-notes/index.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.5, Channels, Major Update, Progress: approved

#7084 Add response for graphql query
  src/_includes/graphql/grouped-product-sample.md
  src/guides/v2.3/graphql/product/grouped-product.md
  src/guides/v2.3/graphql/product/product-interface-implementations.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6960 Adding example for REST search
  src/guides/v2.3/rest/performing-searches.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7094 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.0, Progress: approved, Technical

#7052 Magento 2.3.5 Release Notes
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.5, Internal Dev, New Topic, Progress: approved

#7089 Update extension compatibility matrix and patch schedule for 2.3.5
  src/_data/mde.yml
  src/_data/vbe.yml
  src/release/index.md
Labels: 2.3.5, Editorial, Internal Dev, Maintenance, Progress: approved

#7105 Break symlinks in topics that mention Elasticsearch
  src/guides/v2.4/architecture/tech-stack.md
  src/guides/v2.4/extension-dev-guide/indexer-batch.md
  src/guides/v2.4/extension-dev-guide/searching-with-repositories.md
  src/guides/v2.4/graphql/queries/products.md
  src/guides/v2.4/performance-best-practices/advanced-setup.md
  src/guides/v2.4/performance-best-practices/reference-architecture.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#7106 Update References to Elasticsearch
  src/guides/v2.4/architecture/tech-stack.md
  src/guides/v2.4/extension-dev-guide/indexer-batch.md
  src/guides/v2.4/extension-dev-guide/searching-with-repositories.md
  src/guides/v2.4/graphql/queries/products.md
  src/guides/v2.4/performance-best-practices/advanced-setup.md
  src/guides/v2.4/performance-best-practices/reference-architecture.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#7113 PB-518: Update page builder TOC entry for 1.3 release
  src/_data/toc/page-builder.yml
Labels: 2.3.5, Internal Dev, Progress: approved

#7112 Update backward incompatible changes docs for 2.3
  src/_includes/backward-incompatible-changes/commerce/2.3.4-2.3.5-develop.html
  src/_includes/backward-incompatible-changes/commerce/2.3.4-2.3.5.md
  src/_includes/backward-incompatible-changes/open-source/2.3.4-2.3.5-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.4-2.3.5.md
  src/guides/v2.3/release-notes/backward-incompatible-changes/reference.md
Labels: 2.3.5, Major Update, Progress: approved

#7091 Updating whatsnew with 2.3.5-develop entries
  src/_data/whats-new.yml
Labels: 2.3.5, Internal Dev, Progress: approved

#7115 Correction for PB link in Magento Commerce 2.3.5 Release Notes
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
Labels: Internal Dev, Progress: approved, Small Changes

#7107 Update REST schemas for 2.3.5
  src/redoc/2.3/admin-schema.json
  src/redoc/2.3/async-admin-schema.json
  src/redoc/2.3/async-customer-schema.json
  src/redoc/2.3/async-guest-schema.json
  src/redoc/2.3/customer-schema.json
  src/redoc/2.3/guest-schema.json
  src/redoc/2.3/index.md
Labels: 2.3.5, Internal Dev, Progress: approved, Technical

#7048 [Merge on April 28th] Add release notes for Magento Cloud Patches 1.0.3
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#7117 Break symlinks in update guide
  src/guides/v2.4/comp-mgr/bk-compman-upgrade-guide.md
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/comp-mgr/cli/upgrade-with-plugin.md
  src/guides/v2.4/comp-mgr/cli/upgrade-with-script.md
  src/guides/v2.4/comp-mgr/prereq/prereq_compman-checklist.md
  src/guides/v2.4/comp-mgr/prereq/prereq_compman.md
  src/guides/v2.4/comp-mgr/trouble/tshoot.md
Labels: 2.4.x, Internal Dev, Maintenance, Progress: approved

#7099 Added params with detail for module:status command
  src/extensions/install/index.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7100 Added static deploy command in install module section
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#7097 magento/devdocs#7092: Correction for Accessing js resources in JavaScript resources in Magento
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#7123 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: Progress: approved

#7118 Updated MFTF reference data after 2.3.5 release
  src/_data/codebase/v2_3/mftf/action-groups.yml
  src/_data/codebase/v2_3/mftf/functional-tests.yml
Labels: 2.3.5, Automation, Major Update, Progress: approved

#7127 Magento 2.3.5 package nomenclature update
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.5, Editorial, Internal Dev, Progress: approved

#7119 Updated composer_lock data after 2.3.5 release
  src/_data/codebase/v2_3/cloud/composer_lock.json
  src/_data/codebase/v2_3/commerce/composer_lock.json
  src/_data/codebase/v2_3/open-source/composer_lock.json
  src/_includes/release-notes/packages.md
  src/packages-open-source.md
Labels: 2.3.5, Automation, Major Update, Progress: approved

#7121 magento/devdocs#7116: Feedback on page: /guides/v2.3/install-gde/system-requirements-tech.html
  src/guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, Small Changes, partners-contribution

#7120 Updated data for bin/magento reference topics
  src/_data/codebase/v2_3/commerce/bin-magento.json
  src/_data/codebase/v2_3/open-source/bin-magento.json
Labels: 2.3.5, Automation, Major Update, Progress: approved

#7130 Magento 2.3.5 Release Note minor update -- new links
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.x, Progress: approved, Small Changes

#7131 Magento 2.3.5 Release Note hotfix update
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.x, Major Update, Progress: approved

#7126 Minor fix for DB variable
  src/cloud/live/stage-prod-migrate.md
Labels: 2.3.x, Partner: Comwrap, Progress: approved, Technical, partners-contribution

#7122 minor typo
  src/guides/v2.3/release-notes/release-notes-2-3-5-open-source.md
Labels: 2.3.5, Editorial, Progress: approved, Small Changes

#7137 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.0, Automation, Progress: approved

#7109 Cron node added in env.php reference
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#7132 Add info about Composer dependency for upgrade plugin
  src/guides/v2.3/comp-mgr/cli/upgrade-with-plugin.md
Labels: 2.3.5, Internal Dev, Progress: approved, Technical

#7129 Custom maintenance page not set in developer mode
  src/guides/v2.3/comp-mgr/trouble/cman/maint-mode.md
Labels: 2.3.x, Editorial, Partner: Krish TechnoLabs, Progress: approved, partners-contribution

#7133 Update Cloud service versions for 2.3.5
  src/_includes/cloud/cloud-elasticsearch-client-compatibility.md
  src/_includes/cloud/note-pro-using-yaml-support.md
  src/cloud/env/environments-start.md
  src/cloud/project/new-relic.md
  src/cloud/project/project-conf-files_services-elastic.md
  src/cloud/project/project-conf-files_services.md
  src/cloud/project/project-upgrade.md
Labels: 2.x, Internal Dev, Progress: approved

#7023 Declaring the logo size
  src/guides/v2.3/frontend-dev-guide/themes/admin_theme_create.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Progress: approved, Technical, partners-contribution
