Repository magento/devdocs, pull requests merged in 2020-02, with the labels that each got.

#6510 MInor edits to Magento 2.3.4 Release Notes
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.4, Progress: approved

#6527 Updates based on review feedback
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-extend.md
  src/cloud/docker/docker-mftf.md
  src/cloud/env/variables-global.md
Labels: 2.x, Editorial, Progress: review, internal-dev

#6533 Extra Colon removed after the text "Extends"
  src/guides/v2.3/ui_comp_guide/components/ui-actiondelete.md
  src/guides/v2.3/ui_comp_guide/components/ui-date.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6526 Removed JS file extension in the require function
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution, small changes

#6477 Updating block's attributes and adjusting the HtmlTag attribute
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6524 Add copyright to the source code
  Rakefile
  _checks/html_check_hook.rb
  _plugins/algolia.rb
  _plugins/generators/mrg_pages.rb
  _plugins/liquid-tags/collapsible.rb
  _plugins/page-params/github-path.rb
  _plugins/page-params/last-modified-at.rb
  _plugins/page-params/page-baseurl-generator.rb
  _plugins/page-params/page-canonical-url.rb
  _plugins/page-params/page-versionless.rb
  _plugins/page-params/page-versions.rb
  lib/converter.rb
  lib/doc_config.rb
  lib/double_slash_check.rb
  lib/link_checker.rb
  rakelib/build.rake
  rakelib/check.rake
  rakelib/multirepo.rake
  rakelib/preview.rake
  rakelib/test.rake
  rakelib/update.rake
  scripts/docs-from-code.sh
Labels: Progress: approved, legal

#6517 magento/devdocs#:6443 Align Magento PHP prerequisites in different topics
  src/guides/v2.3/install-gde/prereq/php-settings.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
  src/guides/v2.3/performance-best-practices/software.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#6538 Updating API keys screenshot
  src/recommendations/images/cfg-api-key.png
Labels: Progress: approved

#6545 Cloud patch update: fix cron deadlocks and improve locking
  src/cloud/release-notes/mcp-release-notes.md
Labels: Progress: review, internal-dev

#6540 closing curly bracket and quote
  src/recommendations/customize.md
Labels: 2.3.x, Editorial, Progress: approved, small changes

#6546 Remove YAML duplicates for the bin-magento data
  src/_data/codebase/v2_3/commerce/bin-magento.yml
  src/_data/codebase/v2_3/open-source/bin-magento.yml
Labels: Progress: approved, internal-dev, maintenance, small changes

#6536 Invalid file reference
  src/guides/v2.2/frontend-dev-guide/css-topics/css_debug.md
Labels: 2.3.x, Partner: Maginus, Progress: approved, partners-contribution, small changes

#6542 Note added for the object property convertors behaviour
  src/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.md
Labels: 2.3.x, Community Insider: Cedcommerce, Progress: approved, Technical, community-insider-contribution

#6547 Removing obsolete Fastly installation and configuration info
  src/cloud/cdn/cloud-fastly.md
Labels: Progress: approved, Technical, internal-dev

#6504 Cloud docker 1.0.0
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_data/whats-new.yml
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/configure/setup-cron-jobs.md
  src/cloud/deploy/reduce-downtime.md
  src/cloud/deploy/static-content-deployment.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-database.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-development-testing.md
  src/cloud/docker/docker-development.md
  src/cloud/docker/docker-extend.md
  src/cloud/docker/docker-manage-cron-jobs.md
  src/cloud/docker/docker-manage-database.md
  src/cloud/docker/docker-mftf.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-syncing-data.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/env/variables-post-deploy.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-conf-files_services.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade-parent.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
  src/cloud/setup/first-time-setup-import-import.md
  src/cloud/setup/first-time-setup.md
  src/common/images/cloud/docker-topology.png
Labels: 2.x, Progress: review, internal-dev

#6552 Cloud docker 1.0.0
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_data/whats-new.yml
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/configure/setup-cron-jobs.md
  src/cloud/deploy/reduce-downtime.md
  src/cloud/deploy/static-content-deployment.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-database.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-development-testing.md
  src/cloud/docker/docker-development.md
  src/cloud/docker/docker-extend.md
  src/cloud/docker/docker-manage-cron-jobs.md
  src/cloud/docker/docker-manage-database.md
  src/cloud/docker/docker-mftf.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-syncing-data.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/env/variables-post-deploy.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-conf-files_services.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade-parent.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
  src/cloud/setup/first-time-setup-import-import.md
  src/cloud/setup/first-time-setup.md
  src/common/images/cloud/docker-topology.png
Labels: 2.x, Major update, internal-dev

#6537 magento/devdocs#6310: Clarify steps in Migration Guide
  src/guides/v2.3/migration/migration-migrate-settings.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6549 Magento 2.3.4 backward incompatible change
  src/guides/v2.3/release-notes/backward-incompatible-changes/index.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.4, Progress: approved

#6548 Updating whatsnew file for week of February 3rd
  src/_data/whats-new.yml
Labels: 2.3.x, Progress: approved, internal-dev

#6521 Add new section section about vendor bundled extensions (VBEs)
  src/_data/mde.yml
  src/_data/toc/extensions.yml
  src/_data/vbe.yml
  src/_includes/compatibility-mde.html
  src/_includes/compatibility-vbe.md
  src/extensions/vendor/vendor.md
  src/release/index.md
Labels: New topic, Progress: approved, internal-dev

#6394 Add documentation for the ColumnsEditor UI component
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/ui-columns-editor-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-columns-editor.md
Labels: 2.3.x, New topic, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6554 Move ece-tools release notes for v2002.0.22 and earlier to the
  src/cloud/composer-packages/patch-notes.md
  src/cloud/deploy/reduce-downtime.md
  src/cloud/env/variables-deploy.md
  src/cloud/project/project-upgrade-parent.md
  src/cloud/reference/discover-deploy.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Editorial, Progress: review, internal-dev

#6464 Include link to Elasticsuite documentation in the Cloud Guide
  src/cloud/env/variables-deploy.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6501 Added new step for custom shipping address renderer page
  src/guides/v2.3/howdoi/checkout/checkout_address.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6562 Magento 2.3.4 broken links fix
  src/_includes/release-notes/engcomm-2-3-4-issues.md
  src/_includes/release-notes/engcomm-2-3-4-partner.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
Labels: 2.3.4, Editorial, Progress: approved

#6563 Updated Cloud Components release notes for 1.0.2 release
  src/cloud/release-notes/mcc-release-notes.md
Labels: 2.x, New topic, Progress: approved, internal-dev

#6568 MAGECLOUD-5181: Disable cron container by default
  src/cloud/docker/docker-manage-cron-jobs.md
  src/cloud/docker/docker-mftf.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6553 Replaced or removed v2.2 link references
  src/cloud/configure/setup-b2b.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-cloud.md
  src/cloud/env/variables-deploy.md
  src/cloud/live/sens-data-over.md
  src/cloud/project/project-upgrade.md
  src/cloud/project/project-webint-basic.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/git-integration.md
  src/cloud/release-notes/CloudReleaseNotes2.2.1.md
  src/cloud/release-notes/CloudReleaseNotes2.2.md
  src/cloud/release-notes/cloud-release-archive.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6440 Update Upgrades and Patches section in Cloud Guide for Cloud v2002.1.0
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/note-ece-tools-package.md
  src/cloud/project/ece-tools-update.md
  src/cloud/project/ece-tools-upgrade-project.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade-parent.md
  src/cloud/project/project-upgrade.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Major update, Progress: changes requested, internal-dev

#6565 Added reference link to overriding a JS component
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#6575 Update widget_modal.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.3.5, Partner: Monsoon, Progress: approved, Technical, partners-contribution

#6572 Adding additional step in custom shipping carrier validations page
  src/guides/v2.3/howdoi/checkout/checkout_carrier.md
Labels: 2.3.2, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6578 Updated note about Page Builder patches improvement
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Editorial, Progress: review, internal-dev

#6555 Fixed incorrect links and added clarity
  src/guides/v2.3/javascript-dev-guide/widgets/widget_navigation.md
Labels: 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#6567 Added missing link, fixed ordering of subheadings
  src/_data/toc/javascript-developer-guide.yml
  src/guides/v2.3/javascript-dev-guide/widgets/jquery-widgets-about.md
Labels: 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#6573 Magento thunder magecloud 4327
  src/cloud/env/variables-build.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Progress: review, Technical, internal-dev

#6570 MAGECLOUD-4106: Magento Cloud scenario-based deploy and default API interfaces
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/note-ece-tools-custom-deployment.md
  src/cloud/deploy/cloud-deployment-process.md
  src/cloud/deploy/scenario-based-deployment.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/release-notes/ece-release-notes.md
Labels: Progress: review

#6582 Cloud 2002.1.0
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/note-ece-tools-custom-deployment.md
  src/_includes/cloud/note-ece-tools-package.md
  src/cloud/composer-packages/patch-notes.md
  src/cloud/deploy/cloud-deployment-process.md
  src/cloud/deploy/reduce-downtime.md
  src/cloud/deploy/scenario-based-deployment.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/project/ece-tools-update.md
  src/cloud/project/ece-tools-upgrade-project.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-upgrade.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Major update, Progress: review, Technical

#6579 Remove unneeded data files
  .ruby-version
  src/_data/codebase/v2_2/cloud/composer_lock.json
  src/_data/codebase/v2_2/commerce/bin-magento.json
  src/_data/codebase/v2_2/commerce/composer_lock.json
  src/_data/codebase/v2_2/open-source/bin-magento.json
  src/_data/codebase/v2_2/open-source/composer_lock.json
Labels: Progress: approved, internal-dev, maintenance

#6583 Fix cloud MySQL topic formatting
  src/cloud/project/project-conf-files_services-mysql.md
Labels: Editorial, Progress: approved, internal-dev

#6569 Update release compatibility table
  src/_data/mde.yml
  src/_includes/compatibility-mde.html
  src/release/index.md
Labels: Editorial, Progress: approved, internal-dev

#6586 Cloud Suite release notes and documentation updates
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_data/var.yml
  src/_data/whats-new.yml
  src/_includes/cloud/note-ece-tools-custom-deployment.md
  src/_includes/cloud/note-ece-tools-package.md
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/composer-packages/patch-notes.md
  src/cloud/configure/setup-cron-jobs.md
  src/cloud/deploy/cloud-deployment-process.md
  src/cloud/deploy/reduce-downtime.md
  src/cloud/deploy/scenario-based-deployment.md
  src/cloud/deploy/static-content-deployment.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-cli.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-database.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-development-testing.md
  src/cloud/docker/docker-development.md
  src/cloud/docker/docker-extend.md
  src/cloud/docker/docker-manage-cron-jobs.md
  src/cloud/docker/docker-manage-database.md
  src/cloud/docker/docker-mftf.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-syncing-data.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/env/variables-post-deploy.md
  src/cloud/live/stage-prod-test.md
  src/cloud/project/ece-tools-update.md
  src/cloud/project/ece-tools-upgrade-project.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/project/project-conf-files_magento-app.md
  src/cloud/project/project-conf-files_services.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade-parent.md
  src/cloud/project/project-upgrade.md
  src/cloud/reference/discover-deploy.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/cloud-tools.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcc-release-notes.md
  src/cloud/release-notes/mcd-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
  src/cloud/setup/first-time-setup-import-import.md
  src/cloud/setup/first-time-setup.md
  src/common/images/cloud/docker-topology.png
Labels: 2.x, Major update, Progress: approved

#6580 Changed minimun Magento version to 2.2 since 2.1 is not suported anym…
  src/cloud/basic-information/starter-architecture.md
Labels: Editorial, Partner: Mediotype, Progress: approved, partners-contribution, small changes

#6566 Fixed incorrect default value
  src/guides/v2.3/javascript-dev-guide/widgets/widget_accordion.md
Labels: 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#6590 Small changes
  src/_data/codebase/v2_3/commerce/bin-magento.yml
  src/_data/codebase/v2_3/open-source/bin-magento.yml
  src/cloud/basic-information/starter-architecture.md
  src/cloud/cdn/cloud-fastly.md
  src/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.md
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_accordion.md
  src/guides/v2.3/ui_comp_guide/components/ui-actiondelete.md
  src/guides/v2.3/ui_comp_guide/components/ui-date.md
  src/recommendations/customize.md
  src/recommendations/images/cfg-api-key.png
Labels: Progress: approved

#6587 Updates and link fixes based on review feedback
  src/cloud/project/project-patch.md
  src/cloud/project/project-upgrade-parent.md
  src/cloud/release-notes/backward-incompatible-changes.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6592 Update Cloud Suite package release table
  src/cloud/release-notes/cloud-tools.md
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6593 MAGECLOUD-5139: Add possibility to edit index.php in production mode
  src/cloud/docker/docker-containers-service.md
Labels: Progress: approved, Technical, internal-dev

#6594 Fix the JSON parsing issue in bin-magento.json
  src/_data/codebase/v2_3/commerce/bin-magento.json
  src/_data/codebase/v2_3/open-source/bin-magento.json
Labels: Progress: approved, maintenance

#6599 DEVDOCS-FORMATTING-FIXES: Fixed the page "Create custom cache engines"
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/database-caching.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6597 🐛Fix typo NGINX
  src/cloud/docker/docker-containers.md
Labels: 2.3.x, Editorial, Progress: approved, small changes

#6595 Upgrade to latest version of Magento
  src/cloud/project/ece-tools-upgrade-project.md
Labels: 2.3.x, Partner: Maginus, Progress: approved, Technical, partners-contribution, small changes

#6589 DEVDOCS-SMALL-FIXES: Fixed versions in "Example - Security patch"
  src/guides/v2.3/comp-mgr/cli/cli-upgrade.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6601 Note added for foreign keys in declarative schema
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: Community Insider: Cedcommerce, Progress: approved, Technical, community-insider-contribution

#6591 Added missing "Full Page Cache" reference to config
  src/cloud/cdn/fastly-vcl-blocking.md
Labels: 2.3.x, Editorial, Progress: approved

#6584 Updating event descriptions
  src/recommendations/events.md
Labels: 2.3.x, Progress: approved, internal-dev

#6602 Added example response for sample query for grouped product data types
  src/guides/v2.3/graphql/product/grouped-product.md
Labels: Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6585 Update GraphQL tutorial to use customerCart query
  src/guides/v2.3/graphql/tutorials/checkout/checkout-customer.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shopping-cart.md
Labels: Progress: approved

#6604 Fixed incorrect syntax to use jQuery in mageInit options
  src/guides/v2.3/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.3.x, Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#6600 Added missing sub fields for region when setting shipping address by …
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6603 Added response for sample query for bundle product data types
  src/guides/v2.3/graphql/product/bundle-product.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6596 Fix a typo in the Add CLI Commands page ("You module" => "Your module")
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-add.md
Labels: 2.3.x, Editorial, Partner: Aligent Consulting, Progress: approved, partners-contribution

#6498 Added additional step in custom validation before order placement page
  src/guides/v2.3/howdoi/checkout/checkout_order.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6605 Added `downloadable domain` node description
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6606 What's New updates from Cloud release integration branch
  src/_data/whats-new.yml
Labels: 2.x, Editorial, Progress: approved, internal-dev

#6609 MAGECLOUD-4925: Ability to support custom database parameters in docker image
  src/cloud/docker/docker-containers-service.md
Labels: Progress: approved

#6608 Adding syntax about how to update your install
  src/recommendations/install.md
Labels: 2.3.x, Progress: approved, internal-dev

#6614 magento/devdocs#: Better usability. Add a link to “https://account.magento.com”
  src/recommendations/configure.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6613 Fixed the broken link in env docs
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#6612 Updated composer.md file
  src/guides/v2.3/install-gde/composer.md
Labels: 2.3.x, Progress: approved, Technical

#6607 Fixing MD046 errors part 1
  src/guides/v2.3/install-gde/basics/basics_docroot.md
  src/guides/v2.3/install-gde/install/cli/dev_add-update.md
  src/guides/v2.3/install-gde/install/cli/install-cli-uninstall-mods.md
  src/guides/v2.3/install-gde/prereq/security.md
  src/guides/v2.3/install-gde/trouble/php/tshoot_session.md
  src/guides/v2.3/install-gde/trouble/tshoot_composer-fail.md
  src/guides/v2.3/install-gde/trouble/tshoot_install-issues.md
  src/guides/v2.3/install-gde/trouble/tshoot_wrong-mysql.md
  src/guides/v2.3/rest/list.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_linking_concept.md
  src/recommendations/install.md
  src/recommendations/troubleshooting.md
Labels: Editorial, Progress: approved

#6577 Adding cli commands in custom payment method page
  src/guides/v2.3/howdoi/checkout/checkout_payment.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6598 DEVDOCS-FIXES: Actualization the document "Running Unit Tests in PhpStorm"
  src/common/images/phpstorm_add_php_interpreter_dialogue.png
  src/common/images/phpstorm_php_language_preferences.png
  src/common/images/phpstorm_phpunit_preferences_dialogue.png
  src/common/images/phpstorm_run_config_all_unit_tests.png
  src/common/images/phpstorm_run_config_class_unit_tests.png
  src/common/images/phpstorm_run_config_module_unit_tests.png
  src/guides/v2.3/test/unit/unit_test_execution_phpstorm.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6619 Fixed Magento min version and Composer command
  src/cloud/architecture/pro-architecture.md
Labels: Editorial, Partner: Mediotype, Progress: review, partners-contribution, small changes

#6618 Doc updates for Cloud Docker default Varnish configuration
  src/cloud/docker/docker-containers-service.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Progress: approved, Technical, internal-dev

#6558 Update on Applying mobile specifc styles
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_mobile.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6624 Enable markdown linting in Actions
  .github/workflows/main.yml
Labels: Site improvements

#6621 Fixing MD046 errors part 2
  src/guides/v2.3/frontend-dev-guide/css-guide/css_quick_guide_approach.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-overview.md
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-practice.md
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
  src/guides/v2.3/frontend-dev-guide/themes/js-bundling.md
  src/guides/v2.3/frontend-dev-guide/tools/using_grunt.md
  src/guides/v2.3/frontend-dev-guide/translations/translate_practice.md
  src/guides/v2.3/frontend-dev-guide/translations/translate_theory.md
  src/guides/v2.3/get-started/create-integration.md
  src/guides/v2.3/graphql/functional-testing.md
  src/guides/v2.3/howdoi/checkout/checkout_new_step.md
  src/guides/v2.3/javascript-dev-guide/javascript/custom_js.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_collapsible.md
  src/guides/v2.3/migration/migration-migrate-settings.md
  src/guides/v2.3/migration/migration-overview-practices.md
  src/guides/v2.3/migration/migration-tool-configure.md
  src/guides/v2.3/mtf/create_test/create_new_test.md
  src/guides/v2.3/mtf/mtf_entities/mtf_block.md
  src/guides/v2.3/mtf/troubleshooting.md
Labels: Editorial

#6543 magento/devdocs#:5916 Adding more information to searching with repositories topic
  src/guides/v2.3/extension-dev-guide/searching-with-repositories.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6634 Fixing MD046 errors part 3
  src/guides/v2.3/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.3/comp-mgr/trouble/cman/maint-mode.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-compiler.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-import.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-test.md
  src/guides/v2.3/config-guide/config/config-create.md
  src/guides/v2.3/config-guide/deployment/pipeline/build-system.md
  src/guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
  src/guides/v2.3/config-guide/elasticsearch/es-overview.md
  src/guides/v2.3/config-guide/memcache/memcache_centos.md
  src/guides/v2.3/contributor-guide/templates/basic_template.md
Labels: Editorial

#6629 magento/devdocs#: Extend setShippingAddressesOnCart example
  src/guides/v2.3/graphql/mutations/set-shipping-address.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#6627 Added correct sort type for products query in graphql
  src/guides/v2.3/graphql/queries/products.md
Labels: 2.3.x, Partner: Ziffity, Technical, partners-contribution

#6623 Add Cron container config change to Cloud Docker BIC
  src/cloud/release-notes/backward-incompatible-changes.md
Labels: 2.x, Technical, internal-dev

#6475 Update pro-develop-deploy-workflow.md
  src/cloud/architecture/pro-develop-deploy-workflow.md
Labels: Editorial, Partner: Wagento, Progress: changes requested, partners-contribution, small changes

#6631 Admin page module sequence node
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: 2.3.x, Partner: Ziffity, Technical, partners-contribution

#6633 Fix scenario-based deployment examples
  src/cloud/deploy/scenario-based-deployment.md
Labels: Technical, internal-dev

#6636 Fixing MD046 errors part 4
  _checks/styles/style-rules-prod
  src/_includes/cloud/cli-get-started.md
  src/_includes/cloud/composer-name.md
  src/_includes/cloud/enable-ssh.md
  src/_includes/install/file-system-perms-before_22.md
  src/_includes/install/file-system-perms-oneuser.md
  src/_includes/install/file-system-perms-twouser.md
  src/_includes/install/file-system-perms-twouser_22.md
  src/_includes/webapi/services21.md
  src/_includes/webapi/services22.md
  src/_includes/webapi/services23.md
Labels: Editorial

#6639 Magento 2.3.4 release note update for PayPal Express checkout hot fix
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.4, Major update

#6617 Cloud Docker release: Fix for fpm container errors
  src/cloud/release-notes/mcd-release-notes.md
Labels: 2.x, Technical, internal-dev

#6642 Fixing MD046 errors part 5
  src/cloud/cdn/fastly-vcl-badreferer.md
  src/cloud/docker/docker-mftf.md
  src/cloud/env/environments-start.md
  src/cloud/env/setup-notifications.md
  src/cloud/howtos/install-components.md
  src/cloud/integrations/github-integration.md
  src/cloud/project/ece-tools-update.md
  src/cloud/project/ece-tools-upgrade-project.md
  src/cloud/project/profile-database-queries.md
  src/cloud/project/project-patch.md
  src/cloud/project/project-webint-snap.md
  src/cloud/project/set-cache.md
  src/cloud/setup/first-time-setup-import-prepare.md
  src/cloud/trouble/reset-cron-jobs.md
  src/cloud/trouble/site-availability.md
  src/cloud/trouble/theme-troubleshooting.md
Labels: Editorial

#6641 Update project-conf-files_services-redis.md
  src/cloud/project/project-conf-files_services-redis.md
Labels: 2.x, Editorial, small changes

#6255 Update Code - DocBlock Standard
  src/guides/v2.3/coding-standards/docblock-standard-general.md
Labels: 2.2.x, 2.3.x, Progress: review, Technical, Technology Partner: Magestore, tech-partners-contribution

#6648 Fixed spacing in code sample
  src/cloud/project/project-multi-sites.md
Labels: 2.x, Technical, internal-dev

#6640 Remove v2.2 release notes and link refs
  src/cloud/project/project-upgrade.md
  src/cloud/release-notes/CloudReleaseNotes2.2.1.md
  src/cloud/release-notes/CloudReleaseNotes2.2.md
Labels: 2.2.x, Editorial, internal-dev

#6632 example snippet added for composer.json
  src/guides/v2.3/extension-dev-guide/build/composer-integration.md
Labels: Partner: Ziffity, partners-contribution

#6626 Add documentation for the ColumnsEditorRecord UI component
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/ui-columns-editor-record-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-columns-editor-record.md
Labels: 2.3.x, New topic, Partner: Atwix, partners-contribution

#6645 php versions are too old in composer.json example
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: 2.3.x, Partner: Ziffity, Technical, partners-contribution

#6638 GraphQL: Add SwatchDataInterface attributes/example to configurable products
  src/guides/v2.3/graphql/product/configurable-product.md
Labels: 2.3.5, Community, Major update, internal-dev

#6655 PB-73: Create Appearances example and documentation
  src/_data/toc/page-builder.yml
Labels: 2.3.x, internal-dev

#6647 Inventory 1.1.4 release notes.
  src/guides/v2.3/inventory/release-notes.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.x, Major update, internal-dev

#6628 magento/devdocs#: Add mergeCarts query API errors
  src/guides/v2.3/graphql/mutations/merge-carts.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#6650 Adding missing information in setBillingAddressOnCart Mutation
  src/guides/v2.3/graphql/mutations/set-billing-address.md
Labels: Editorial, Partner: Ziffity, partners-contribution, small changes

#6635 #6530 Formatting and grammar fixes
  src/guides/v2.3/coding-standards/docblock-standard-general.md
Labels: 2.3.x, Editorial

#6656 Update README
  README.md
Labels: internal-dev, maintenance

#6620 Updated Cloud Guide navigation for accessible Docker launch instructions
  src/_data/main-nav.yml
  src/_data/toc/cloud-guide.yml
  src/_includes/cloud/note-docker-config-reference-link.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-development.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/reference/ece-tools-reference.md
  src/cloud/release-notes/cloud-release-archive.md
Labels: 2.x, Editorial, internal-dev

#6539 #3361 New Configuration Type Topic
  src/guides/v2.3/config-guide/config/config-create.md
  src/guides/v2.3/config-guide/config/config-files.md
Labels: 2.3.3, Major update, Partner: Maginus, Progress: review, Special achievement, partners-contribution

#6661 Magento 2.3.4 broken link fix
  src/_includes/release-notes/engcomm-2-3-4-partner.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: Editorial

#6662 [Components] Fix typo at insert listing component guide
  src/guides/v2.3/ui_comp_guide/components/ui-insertlisting.md
Labels: 2.3.x, Editorial, small changes

#6670 Extending setBillingAddressOnCart mutation example in gr…
  src/guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
Labels: 2.3.x, Editorial, Partner: Ziffity, partners-contribution, small changes

#6665 magento/devdocs#: Install “magento/product-recommendations” clarifications
  src/recommendations/install.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution, small changes

#6532 Added instruction to add new page layout
  src/_data/toc/frontend-developer-guide.yml
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
Labels: 2.3.x, Event: mm20in, New topic, Partner: Ziffity, Progress: approved, partners-contribution

#6557 Restructured themes overview page
  src/_data/toc/frontend-developer-guide.yml
  src/guides/v2.3/ext-best-practices/storefront/storefront-best-practices.md
  src/guides/v2.3/extension-dev-guide/bk-extension-dev-guide.md
  src/guides/v2.3/frontend-dev-guide/bk-frontend-dev-guide.md
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_overview.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-general.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-structure.md
  src/guides/v2.3/migration/bk-migration-guide.md
Labels: 2.3.x, Partner: Zilker Technology, Site improvements, partners-contribution

#6669 layout extend url updated in release notes
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.x, Community Insider: Cedcommerce, Editorial, community-insider-contribution

#6668 Typo corrected in code example
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
Labels: 2.3.x, Community Insider: Cedcommerce, Editorial, community-insider-contribution

#6630 magento/devdocs#: Add setPaymentMethodOnCart query API errors
  src/guides/v2.3/graphql/mutations/set-payment-method.md
Labels: 2.3.x, Partner: Atwix, Technical, partners-contribution

#6664 magento/devdocs#: GraphQL Editorial. Replace “attribute” with “argument”
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/mutations/add-downloadable-products.md
  src/guides/v2.3/graphql/mutations/add-simple-products.md
  src/guides/v2.3/graphql/mutations/add-virtual-products.md
  src/guides/v2.3/graphql/mutations/apply-coupon.md
  src/guides/v2.3/graphql/mutations/change-customer-password.md
  src/guides/v2.3/graphql/mutations/create-customer-address.md
  src/guides/v2.3/graphql/mutations/create-customer.md
  src/guides/v2.3/graphql/mutations/delete-customer-address.md
  src/guides/v2.3/graphql/mutations/delete-payment-token.md
  src/guides/v2.3/graphql/mutations/generate-customer-token.md
  src/guides/v2.3/graphql/mutations/remove-coupon.md
  src/guides/v2.3/graphql/mutations/remove-item.md
  src/guides/v2.3/graphql/mutations/set-guest-email.md
  src/guides/v2.3/graphql/mutations/update-customer-address.md
Labels: 2.3.x, Editorial, Partner: Atwix, partners-contribution, small changes

#6673 Add link to Docker prerequisites info
  src/cloud/docker/docker-mode-developer.md
Labels: 2.x, Editorial, internal-dev

#6453 New topic for creating ACL rule.
  src/_data/toc/extension-best-practices.yml
  src/common/images/ext-best-practices/custom_menu.png
  src/common/images/ext-best-practices/resource-access-custom-create-acl-rule.png
  src/common/images/ext-best-practices/role-resources-create-acl-rule.png
  src/guides/v2.3/ext-best-practices/tutorials/create-access-control-list-rule.md
Labels: 2.3.x, New topic, Partner: Ziffity, Progress: changes requested, partners-contribution

#6556 Added new page for custom validation rules
  src/_data/toc/frontend-developer-guide.yml
  src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
Labels: 2.3.x, New topic, Partner: Zilker Technology, Progress: approved, partners-contribution

#6652 variable declaration and doc blocks added in example code snippet
  src/guides/v2.3/extension-dev-guide/depend-inj.md
  src/guides/v2.3/extension-dev-guide/events-and-observers.md
Labels: Partner: Ziffity, Technical, partners-contribution

#6531 Added example for preference
  src/guides/v2.3/extension-dev-guide/build/di-xml-file.md
Labels: 2.3.x, Event: mm20in, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6677 Remove obsolete files and update rake test:md
  _checks/styles/style-rules-prod
  rakelib/check.rake
  rakelib/test.rake
  src/404.md
  src/guides/v2.3/comp-mgr/upgrader/upgrade-rc1.md
  src/guides/v2.3/extension-dev-guide/build_a_simple_module.md
  src/guides/v2.3/install-gde/back-intro.md
  src/guides/v2.3/search.md
  src/search.md
Labels: Editorial, maintenance

#6676 Remove obsolete content from Cloud Guide
  src/cloud/before/before-workspace-cloud-account.md
  src/cloud/env/environments-start.md
  src/cloud/howtos/environment-tutorial-env-merge.md
  src/cloud/howtos/how-to.md
Labels: 2.x, internal-dev

#6682 Add redirect based on HotJar broken link report
  src/cloud/project/user-admin.md
Labels: 2.x, Editorial, internal-dev

#6685 Added link to ElasticSuite documentation
  src/cloud/project/project-conf-files_services-elastic.md
Labels: 2.x, Editorial, Technical, internal-dev

#6688 Fix link to Installing Apache on CentOS
  src/guides/v2.3/install-gde/prereq/apache.md
Labels: 2.3.x, Editorial, small changes

#6667 magento/devdocs#: Install Product Recommendations. Update information about required dependencies.
  src/recommendations/install.md
Labels: 2.x, Editorial, Partner: Atwix, partners-contribution

#6672 Fixes a 404 link in Docblock standards
  src/guides/v2.3/coding-standards/docblock-standard-general.md
Labels: 2.3.x, Editorial

#6663 Removing Deprecated customer id from createCustomer Mutation
  src/_includes/graphql/customer-output.md
  src/guides/v2.3/graphql/mutations/create-customer.md
Labels: 2.3.x, Partner: Ziffity, Technical, partners-contribution, small changes

#6698 Fix instructions for deploying Magento in Docker
  src/cloud/docker/docker-mode-developer.md
Labels: 2.x, Technical, internal-dev

#6694 GraphQL: Update layered nav info
  src/guides/v2.3/graphql/custom-filters.md
  src/guides/v2.3/graphql/queries/products.md
  src/guides/v2.3/graphql/release-notes.md
Labels: 2.3.5, Technical, internal-dev

#6695 updating example response for category query in graphql
  src/guides/v2.3/graphql/queries/category.md
Labels: 2.3.x, Partner: Ziffity, Technical, partners-contribution, small changes

#6691 Updating Recommendations docs based on feedback
  src/_data/main-nav.yml
  src/_data/toc/product-recommendations.yml
  src/recommendations/configure.md
  src/recommendations/customize.md
  src/recommendations/events.md
  src/recommendations/images/event-metric.png
  src/recommendations/images/snowplow-filter.png
  src/recommendations/install.md
  src/recommendations/product-recs.md
  src/recommendations/support.md
  src/recommendations/test.md
  src/recommendations/testing.md
  src/recommendations/troubleshooting.md
  src/recommendations/verify.md
Labels: 2.3.x, internal-dev

#6675 Updated release notes for Patches v1.0.2
  src/cloud/project/project-patch.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.x, Technical, internal-dev

#6699 Removing install topic
  src/recommendations/install.md
Labels: 2.3.x, Progress: approved, internal-dev

#6678 Added new page for extending an existing GraphQL schema
  src/_data/toc/graphql.yml
  src/guides/v2.3/graphql/develop/extend-existing-schema.md
Labels: 2.3.x, New topic, Partner: Zilker Technology, Progress: approved, partners-contribution

#6701 Update xml-manage.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Editorial, Progress: approved

#6696 Update highlight reference to createAsset function
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-static-deploy-strategies.md
Labels: 2.3.x, Editorial, Progress: approved

#6703 Adding redirect
  src/recommendations/product-recs.md
Labels: 2.3.x, Progress: approved, internal-dev

#6702 Small changes
  src/_includes/graphql/customer-output.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/project/project-conf-files_services-elastic.md
  src/cloud/project/user-admin.md
  src/guides/v2.3/coding-standards/docblock-standard-general.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-static-deploy-strategies.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/graphql/mutations/add-configurable-products.md
  src/guides/v2.3/graphql/mutations/add-downloadable-products.md
  src/guides/v2.3/graphql/mutations/add-simple-products.md
  src/guides/v2.3/graphql/mutations/add-virtual-products.md
  src/guides/v2.3/graphql/mutations/apply-coupon.md
  src/guides/v2.3/graphql/mutations/change-customer-password.md
  src/guides/v2.3/graphql/mutations/create-customer-address.md
  src/guides/v2.3/graphql/mutations/create-customer.md
  src/guides/v2.3/graphql/mutations/delete-customer-address.md
  src/guides/v2.3/graphql/mutations/delete-payment-token.md
  src/guides/v2.3/graphql/mutations/generate-customer-token.md
  src/guides/v2.3/graphql/mutations/remove-coupon.md
  src/guides/v2.3/graphql/mutations/remove-item.md
  src/guides/v2.3/graphql/mutations/set-guest-email.md
  src/guides/v2.3/graphql/mutations/update-customer-address.md
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-billing-address.md
  src/guides/v2.3/install-gde/prereq/apache.md
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
  src/guides/v2.3/ui_comp_guide/components/ui-insertlisting.md
Labels: Progress: approved

#6705 Updated maintainer guidelines
  .github/MAINTAINER_GUIDELINES.md
Labels: Progress: approved, internal-dev, maintenance

#6706 Restored release item for cron lock fix
  src/cloud/release-notes/mcp-release-notes.md
Labels: Progress: approved, Technical, internal-dev

#6671 Remove extra bracket
  src/cloud/release-notes/cloud-tools.md
Labels: Editorial, Partner: Mediotype, Progress: approved, Technology Partner: Vertex, partners-contribution, small changes, tech-partners-contribution

#6714 Updates method name to the common method used for database lookup by ID
  src/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.md
Labels: 2.3.5, Editorial, Partner: Mediotype, Progress: approved, partners-contribution

#6717 Whatsnew for feb 24
  src/_data/whats-new.yml
Labels: 2.3.x, Progress: approved, internal-dev

#6718 Front page edits
  src/recommendations/product-recs.md
Labels: 2.3.x, Progress: approved, internal-dev

#6716 Added the documentation for ColumnsEditorView UI component
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/ui-columns-editor-view-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-columns-editor-view.md
Labels: New topic, Partner: Atwix, Progress: approved, partners-contribution

#6653 doc block added for example php file
  src/guides/v2.3/extension-dev-guide/events-and-observers.md
Labels: 2.3.x, Partner: Ziffity, Technical, partners-contribution

#6715 magento/devdocs#: Adding additional information to Non-secure functio…
  src/guides/v2.3/extension-dev-guide/security/non-secure-functions.md
Labels: Partner: Atwix, Progress: approved, Technical, partners-contribution

#6719 Testing topic edits
  src/recommendations/test.md
Labels: 2.3.x, Progress: approved, internal-dev
