Repository magento/devdocs, pull requests merged in 2020-03, with the labels that each got.

#6755 magento/devdocs#: Add information about required Apache modules
  src/guides/v2.3/install-gde/prereq/apache.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6754 Removing deprecated region_id from createCustomerAddress Mutation
  src/guides/v2.3/graphql/mutations/create-customer-address.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution, small changes

#6753 Updating output attribute in place order mutation output object
  src/guides/v2.3/graphql/mutations/place-order.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution, small changes

#6762 Gathered fixes from abandoned PRs.
  src/guides/v2.3/frontend-dev-guide/css-topics/using-fonts.md
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-enable.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
Labels: 2.3.x, Editorial, Progress: approved

#6760 magento/devdocs#: Layout instructions. Small layout fixes
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_template_literals.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution, small changes

#6748 Result section added for adding new layout document
  src/common/images/fdg/custom_layout_admin_backend.png
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6778 Small grammar updates
  src/guides/v2.3/howdoi/checkout/checkout_payment.md
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: 2.3.x, Community Insider: SwiftOtter, Editorial, Progress: approved, community-insider-contribution

#6772 Added grunt exec and watch commands once grunt is setup
  src/guides/v2.3/frontend-dev-guide/tools/using_grunt.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#6780 Correct deprecated environment variable list
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#6768 Marketplace sellers - redirect FAQ
  src/marketplace/sellers/getting-started.md
Labels: Internal Dev, Progress: approved

#6775 Data migration tool doc update, map files override step, fixed typo
  src/guides/v2.3/migration/extend-the-tool.md
  src/guides/v2.3/migration/migration-tool-configure.md
Labels: Partner: Atwix, Progress: approved, Technical, partners-contribution

#6782 Remove Marketplace User Guide from federated search
  src/_includes/layout/header-scripts.html
Labels: Progress: approved, Site improvements

#6769 MAGECLOUD-4890 Implement support for backup databases from split connections for `ece-tools`
  src/cloud/project/project-webint-snap.md
Labels: Internal Dev, Progress: approved, Technical

#6781 GraphQL: Update 2.3.5 release notes
  src/guides/v2.3/graphql/product/product-interface.md
  src/guides/v2.3/graphql/release-notes.md
Labels: 2.3.5, Internal Dev, Progress: approved

#6764 MQE-1057: Update metadata filenames convention
  src/guides/v2.3/coding-standards/technical-guidelines.md
Labels: 2.3.x, Progress: approved, Technical

#6785 magento/devdocs#6773: Text UI Component Example incorrect
  src/common/images/ui_comps/ui-text-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-text.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6757 magento/devdocs#6689: Add information about required Apache configuration adjustment
  src/guides/v2.3/install-gde/prereq/apache.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6792 Updating whatsnew for the week
  src/_data/whats-new.yml
Labels: Internal Dev, Progress: approved

#6794 Apply the devdocs theme update #55
  Gemfile.lock
Labels: Progress: approved, Site improvements

#6795 Replace link tags with site variables
  src/compliance/industry-compliance.md
  src/compliance/privacy/ccpa.md
  src/compliance/privacy/gdpr.md
  src/compliance/privacy/pi-data-reference-m1.md
  src/compliance/privacy/pi-data-reference-m2.md
  src/guides/v2.3/extension-dev-guide/validate/test-module.md
  src/marketplace/eqp/v1/packages.md
  src/marketplace/sellers/account-setup-process.md
  src/marketplace/sellers/account-setup.md
  src/marketplace/sellers/analytics.md
  src/marketplace/sellers/before-you-begin.md
  src/marketplace/sellers/content.md
  src/marketplace/sellers/developer-portal.md
  src/marketplace/sellers/developer-register.md
  src/marketplace/sellers/extension-create.md
  src/marketplace/sellers/extension-information.md
  src/marketplace/sellers/extension-quality-program.md
  src/marketplace/sellers/extension-resubmit.md
  src/marketplace/sellers/extension-update-information.md
  src/marketplace/sellers/extension-version.md
  src/marketplace/sellers/extensions.md
  src/marketplace/sellers/getting-started.md
  src/marketplace/sellers/marketing-review-guidelines.md
  src/marketplace/sellers/marketing-submission-preview.md
  src/marketplace/sellers/packaging-v1x-extensions.md
  src/marketplace/sellers/profile-company.md
  src/marketplace/sellers/profile-information.md
  src/marketplace/sellers/profile-personal.md
  src/marketplace/sellers/review-report.md
  src/marketplace/sellers/sales.md
  src/marketplace/sellers/seller-overview.md
  src/marketplace/sellers/shared-packages.md
  src/marketplace/sellers/submit-for-marketing-review.md
  src/marketplace/sellers/submit-for-review.md
  src/marketplace/sellers/submit-for-technical-review.md
  src/marketplace/sellers/technical-reference.md
  src/marketplace/sellers/technical-review-guidelines.md
  src/marketplace/sellers/themes.md
Labels: Internal Dev, Maintenance, Progress: approved

#6793 Add a link to the troubleshooting KB in the Migration Guide
  src/_data/toc/migration-guide.yml
Labels: Editorial, Internal Dev, Progress: approved

#6784 magento/devdocs#6774: Input UI Component Example incorrect
  src/guides/v2.3/ui_comp_guide/components/ui-input.md
Labels: Partner: Atwix, Progress: approved, Technical, partners-contribution

#6797 Updating customer output object in resolvers example
  src/guides/v2.3/graphql/develop/resolvers.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Small Changes, Technical, partners-contribution

#6800 Cloud: quick fix for broken link
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-mode-production.md
Labels: Internal Dev, Progress: approved, Small Changes

#6770 Add missing configuration
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6789 Adding customize block placement
  src/_data/toc/product-recommendations.yml
  src/recommendations/customize.md
Labels: 2.3.x, Internal Dev, Progress: approved

#6804 applied_coupon field is deprecated
  src/guides/v2.3/graphql/mutations/apply-coupon.md
  src/guides/v2.3/graphql/mutations/remove-coupon.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Small Changes, Technical, partners-contribution

#6805 Adding Commerce Tag to Header
  src/recommendations/configure.md
  src/recommendations/events.md
  src/recommendations/product-recs.md
  src/recommendations/recs-api.md
  src/recommendations/support.md
  src/recommendations/test.md
  src/recommendations/troubleshooting.md
  src/recommendations/verify.md
Labels: 2.3.x, Internal Dev, Progress: approved

#6803 Removed deprecated field in graphql query
  src/guides/v2.3/graphql/queries/customer.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6766 Add warnings for Cloud tasks requiring redeploy and misc edits
  src/_includes/cloud/backup-db.md
  src/_includes/cloud/note-db-import-export-warning.md
  src/_includes/cloud/note-prevent-site-availability-issues.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/live/stage-prod-migrate.md
  src/cloud/project/project-integrate-blackfire.md
  src/cloud/project/project-webint-snap.md
  src/cloud/project/projects.md
  src/cloud/project/user-admin.md
  src/cloud/requirements/cloud-requirements.md
  src/cloud/setup/first-time-setup-import-import.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#6808 Small changes
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/release-notes/ece-release-notes.md
  src/common/images/ui_comps/ui-text-result.png
  src/guides/v2.3/frontend-dev-guide/tools/using_grunt.md
  src/guides/v2.3/graphql/develop/resolvers.md
  src/guides/v2.3/graphql/mutations/apply-coupon.md
  src/guides/v2.3/graphql/mutations/create-customer-address.md
  src/guides/v2.3/graphql/mutations/place-order.md
  src/guides/v2.3/graphql/mutations/remove-coupon.md
  src/guides/v2.3/graphql/queries/customer.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-coupon.md
  src/guides/v2.3/howdoi/checkout/checkout_payment.md
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_modifier_concept.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_template_literals.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_xmldeclaration_concept.md
Labels: Progress: approved

#6761 magento/devdocs#: Improvement - adding links
  src/guides/v2.3/architecture/archi_perspectives/ABasics_intro.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6813 Deprecated fields removed from graphql query
  src/guides/v2.3/graphql/product/downloadable-product.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6815 Changing the request attribute corresponding to response attribute in using queries example
  src/guides/v2.3/graphql/queries/index.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, Small Changes, partners-contribution

#6814 Products graphql - deprecated fields removed
  src/guides/v2.3/graphql/product/bundle-product.md
  src/guides/v2.3/graphql/product/configurable-product.md
  src/guides/v2.3/graphql/product/gift-card-product.md
  src/guides/v2.3/graphql/product/grouped-product.md
  src/guides/v2.3/graphql/product/product-interface-implementations.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, partners-contribution

#6681 magento/devdocs#:5185 Adding more information about configuring TinyMCE
  src/guides/v2.3/ui_comp_guide/components/wysiwyg/configure-tinymce-editor.md
Labels: 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#6817 Deprecated type_id field in graphql
  src/guides/v2.3/graphql/product/customizable-option-interface.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6806 Added the short description about GraphQL to Magento areas
  src/guides/v2.3/architecture/archi_perspectives/components/modules/mod_and_areas.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, Small Changes, partners-contribution

#6802 Removing deprecated customer id from create customer tutorial
  src/guides/v2.3/graphql/tutorials/checkout/checkout-customer.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#6759 Add SelectionProvider
  src/guides/v2.3/ui_comp_guide/components/ui-insertlisting.md
Labels: 2.3.x, Progress: approved, Technical

#6816 Fixes 404s
  src/cloud/project/project-webint-basic.md
  src/guides/v2.3/extension-dev-guide/build/composer-integration.md
  src/guides/v2.3/extension-dev-guide/prepare/lifecycle.md
  src/guides/v2.3/extension-dev-guide/security/non-secure-functions.md
  src/guides/v2.3/security/two-factor-authentication.md
Labels: 2.3.x, Editorial, Progress: approved

#6810 Added default value for block cacheable attribute
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: Partner: Zilker Technology, Progress: approved, Small Changes, partners-contribution

#6649 Updated attribute type for customAttributMetadata query
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
Labels: Editorial, Partner: Ziffity, Progress: approved, Small Changes, partners-contribution

#6820 Magecloud 5091: Update devdocs documentation with changes in MAGECLOUD-2880
  src/cloud/project/project-webint-snap.md
Labels: 2.3.x, 2.x, Internal Dev, Progress: approved, Technical

#6812 Updating EntityUrl output object in urlResolvers query
  src/guides/v2.3/graphql/queries/url-resolver.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6822 Added input attribute for delete payment token mutation
  src/_includes/graphql/customer-payment-tokens.md
  src/guides/v2.3/graphql/mutations/delete-payment-token.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6829 Updating deprecated category query in Intropection query example
  src/guides/v2.3/graphql/queries/index.md
Labels: 2.3.x, Editorial, Partner: Ziffity, Progress: approved, Small Changes, partners-contribution

#6821 Link Architecture Guide to Security best practices pdf
  src/_data/toc/architecture-guide.yml
  src/guides/v2.3/architecture/security_intro.md
Labels: Progress: approved

#6835 Added input attributes for cartItemUpdateInput object in graphql
  src/_includes/graphql/cart-object.md
  src/guides/v2.3/graphql/mutations/update-cart-items.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6834 GraphQL: Update index page
  src/guides/v2.3/graphql/index.md
Labels: Progress: approved

#6837 Adds varnish 6.x to the list of supported varnish major versions
  src/guides/v2.3/config-guide/varnish/config-varnish.md
Labels: 2.3.x, Editorial, Progress: approved

#6832 Asynchronous image resizing
  src/guides/v2.4/frontend-dev-guide/themes/theme-images.md
Labels: 2.4, Internal Dev, Progress: approved, Tracking

#6844 GraphQL: Add send_friend object to the storeConfig query
  src/guides/v2.4/graphql/queries/store-config.md
Labels: 2.4, Internal Dev, Progress: approved, Technical

#6809 Improve Cloud Starter - New Relic config instructions
  src/cloud/project/new-relic.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#6845 Change references to TAM title to Customer Technical Advisor (CTA)
  src/cloud/architecture/cloud-architecture.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/configure/setup-cron-jobs.md
Labels: 2.3.x, Internal Dev, Progress: review

#6838 Add the documentation for the ColumnsResize UI component
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/ui-columns-resize-result.gif
  src/guides/v2.3/ui_comp_guide/components/ui-columns-resize.md
Labels: 2.3.x, New topic, Partner: Atwix, Progress: approved, partners-contribution

#6847 Updated example for cacheable query in graphql
  src/guides/v2.3/graphql/develop/identity-class.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Small Changes, Technical, partners-contribution

#6811 magento/devdocs#6535: Clarify behavior of plugins in Plugins (Interceptors) topic
  src/guides/v2.3/extension-dev-guide/plugins.md
Labels: 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#6842 Update error in gs-web-api-request.md
  src/guides/v2.3/get-started/gs-web-api-request.md
Labels: 2.3.x, Progress: approved, Technical

#6854 Small editorial fix
  src/cloud/deploy/scenario-based-deployment.md
Labels: 2.x, Internal Dev, Progress: review, Small Changes

#6836 Add the "XSS prevention strategies" page for 2.4.0 with the new approach to sanitize strings in the .phtml templates
  src/guides/v2.4/extension-dev-guide/xss-protection.md
Labels: 2.4, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6850 Changes 'Prompt' widget 'Keyboard navigation' section
  src/guides/v2.3/javascript-dev-guide/widgets/widget_prompt.md
Labels: 2.4, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6851 GraphQL: Update VCL file for 2.3.5
  src/guides/v2.3/graphql/caching.md
Labels: 2.3.5, Internal Dev, Progress: approved, Technical

#6857 Fastly screen cap updates:
  src/cloud/cdn/configure-fastly.md
  src/cloud/cdn/fastly-image-optimization.md
  src/cloud/cdn/trouble-fastly.md
  src/common/images/cloud/cloud-fastly_enable-admin.png
  src/common/images/cloud/cloud_fastly-503-example.png
  src/common/images/cloud/cloud_fastly-backend.png
  src/common/images/cloud/cloud_fastly-geo-code.png
  src/common/images/cloud/cloud_fastly-io-config-adaptive-pixel.png
  src/common/images/cloud/cloud_fastly-io-config-options.png
  src/common/images/cloud/cloud_fastly-io-deep-image-config.png
  src/common/images/cloud/cloud_fastly-io-default-config.png
  src/common/images/cloud/cloud_fastly-purgeoptions.png
  src/common/images/cloud/cloud_fastly-upload-vcl-admin-ui.png
  src/common/images/cloud/cloud_fastly_menu.png
  src/common/images/cloud_fastly-geo-code.png
Labels: 2.x, Editorial, Internal Dev, Progress: review

#6843 Fixed small typo and contractions
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_data_source.md
Labels: 2.3.x, Editorial, Progress: approved

#6858 Small changes
  src/_includes/graphql/cart-object.md
  src/cloud/architecture/cloud-architecture.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/cdn/fastly-image-optimization.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/configure/setup-cron-jobs.md
  src/cloud/deploy/scenario-based-deployment.md
  src/common/images/cloud/cloud-fastly_enable-admin.png
  src/common/images/cloud/cloud_fastly-503-example.png
  src/common/images/cloud/cloud_fastly-backend.png
  src/common/images/cloud/cloud_fastly-geo-code.png
  src/common/images/cloud/cloud_fastly-io-config-adaptive-pixel.png
  src/common/images/cloud/cloud_fastly-io-config-options.png
  src/common/images/cloud/cloud_fastly-io-deep-image-config.png
  src/common/images/cloud/cloud_fastly-io-default-config.png
  src/common/images/cloud/cloud_fastly-purgeoptions.png
  src/common/images/cloud/cloud_fastly-upload-vcl-admin-ui.png
  src/common/images/cloud/cloud_fastly_menu.png
  src/common/images/cloud_fastly-geo-code.png
  src/guides/v2.3/architecture/archi_perspectives/components/modules/mod_and_areas.md
  src/guides/v2.3/get-started/gs-web-api-request.md
  src/guides/v2.3/graphql/develop/identity-class.md
  src/guides/v2.3/graphql/mutations/update-cart-items.md
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
  src/guides/v2.3/graphql/queries/index.md
  src/guides/v2.3/graphql/tutorials/checkout/checkout-customer.md
  src/guides/v2.3/migration/extend-the-tool.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_data_source.md
Labels: Progress: approved

#6824 Add info how to create a custom step in Data migration tool
  src/guides/v2.3/migration/extend-the-tool.md
Labels: 2.3.x, Major update, Partner: Atwix, Progress: approved, Special achievement, partners-contribution

#6862 GraphQL: Update VCL file for 2.4
  src/guides/v2.4/graphql/caching.md
Labels: 2.4, Internal Dev, Progress: approved, Technical

#6831 [MC-32221] Update Elasticsearch/Zend/Apache for 2.3.5
  src/_includes/config/es-elasticsearch-magento.md
  src/_includes/config/es-webserver-overview.md
  src/common/images/elastic_choose-in-admin-es6.png
  src/guides/v2.3/architecture/tech-stack.md
  src/guides/v2.3/config-guide/elasticsearch/es-config-apache.md
  src/guides/v2.3/config-guide/elasticsearch/es-downgrade.md
  src/guides/v2.3/config-guide/elasticsearch/es-overview.md
  src/guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.5, Progress: approved, Technical

#6853 Update hooks example to show correct syntax
  src/cloud/project/ece-tools-upgrade-project.md
  src/cloud/project/project-conf-files_magento-app.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#6874 Fixes small typo in Message Queue topic.
  src/guides/v2.3/extension-dev-guide/message-queues/message-queues.md
Labels: 2.3.x, Editorial, Progress: approved

#6867 Removed duplicate menu item
  src/_data/toc/configuration-guide.yml
Labels: Editorial, Partner: Zilker Technology, Progress: approved, partners-contribution

#6840 MS-6352 Improve Marketplace Public API Documentation
  src/_data/toc/marketplace-api.yml
  src/marketplace/eqp/v1/callbacks.md
  src/marketplace/eqp/v1/files.md
  src/marketplace/eqp/v1/filtering.md
  src/marketplace/eqp/v1/packages.md
  src/marketplace/eqp/v1/test-results.md
  src/marketplace/eqp/v1/users.md
Labels: Internal Dev, Major update, New topic, Progress: approved

#6872 Added the documentation for the FormDataProvider UI component
  src/_data/toc/ui-components-guide.yml
  src/guides/v2.3/ui_comp_guide/components/ui-form-data-provider.md
Labels: New topic, Partner: Atwix, Progress: approved, partners-contribution

#6877 Workaround to commit PR-6840
  src/_data/toc/marketplace-api.yml
  src/marketplace/eqp/v1/callbacks.md
  src/marketplace/eqp/v1/files.md
  src/marketplace/eqp/v1/filtering.md
  src/marketplace/eqp/v1/packages.md
  src/marketplace/eqp/v1/test-results.md
  src/marketplace/eqp/v1/users.md
Labels: Progress: approved

#6861 magento/devdocs#: Add missing cron group
  src/guides/v2.3/config-guide/cron/custom-cron.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6866 Remove unnecessary closing tag
  src/marketplace/sellers/before-you-begin.md
Labels: 2.3.x, Editorial, Progress: approved

#6863 magento/devdocs#: Add a trick how a cron job can be disabled
  src/guides/v2.3/config-guide/cron/custom-cron-ref.md
Labels: 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#6819 Added response for graphql query
  src/guides/v2.3/graphql/product/customizable-option-interface.md
Labels: Editorial, Partner: Imagination Media, Partner: Ziffity, Progress: approved, partners-contribution

#6879 Removed redundant spaces
  src/cloud/docker/docker-mftf.md
Labels: 2.3.x, Editorial, Progress: approved, Small Changes

#6875 #6869: Fix typo in code sample
  src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6856 magento/devdocs#: Layout instructions. Adding the example of disabling plugin.
  src/guides/v2.3/extension-dev-guide/plugins.md
Labels: 2.3.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#6882 Clarify authorization key requirement for Commerce and Cloud packages
  src/_includes/install/auth-tokens-get.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved, Small Changes

#6859 Adding a new topic related to GuzzleHttp library
  src/_data/toc/extension-best-practices.yml
  src/guides/v2.3/ext-best-practices/tutorials/create-integration-with-api.md
Labels: 2.3.x, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#6833 Updated custom VCL documentation
  src/_data/toc/cloud-guide.yml
  src/cloud/cdn/cloud-vcl-custom-snippets.md
  src/cloud/cdn/fastly-vcl-badreferer.md
  src/cloud/cdn/fastly-vcl-blocking.md
  src/cloud/cdn/fastly-vcl-whitelist.md
  src/cloud/cdn/fastly-vcl-wordpress.md
  src/cloud/trouble/robots-sitemap.md
Labels: 2.3.x, Internal Dev, Progress: approved

#6887 Clarified formatting of email templates
  src/guides/v2.3/frontend-dev-guide/templates/template-email-migration.md
Labels: 2.3.4, Editorial, Progress: approved

#6871 Form component container
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/container-result.png
  src/common/images/ui_comps/container-with-field-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-container.md
Labels: 2.3.x, New Topic, Progress: approved

#6848 Added input attribute for breadcrumb object in category interface in graphql
  src/guides/v2.3/graphql/product/category-interface.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#6894 GraphQL: Add url_path filter to categoryList query
  src/guides/v2.3/graphql/queries/category-list.md
Labels: 2.4, Internal Dev, Progress: approved, Technical

#6889 magento/devdocs#: Add setShippingMethodsOnCart query API errors
  src/guides/v2.3/graphql/mutations/set-shipping-method.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6893 Added EOL banner for Google Shopping ads Channel
  src/extensions/google-shopping-ads/index.md
  src/extensions/google-shopping-ads/release-notes/index.md
Labels: 2.2.x, 2.3.x, Channels, Major Update, Progress: review

#6885 Issue 6507 Clarify authentication for Elasticsearch
  src/_includes/config/es-webserver-overview.md
Labels: 2.3.x, Editorial, Progress: approved

#6890 Add docker-compose support
  README.md
  docker-compose.yaml
Labels: Partner: Netz98, Progress: approved, Technical, partners-contribution

#6899 Small changes
  src/_includes/config/es-webserver-overview.md
  src/_includes/install/auth-tokens-get.md
  src/cloud/docker/docker-mftf.md
  src/guides/v2.3/config-guide/cron/custom-cron.md
  src/guides/v2.3/extension-dev-guide/message-queues/message-queues.md
  src/guides/v2.3/extension-dev-guide/plugins.md
  src/guides/v2.3/frontend-dev-guide/validations/custom-validation.md
  src/marketplace/sellers/before-you-begin.md
Labels: Progress: approved, Site Improvements

#6883 Update requirements for disk, mount, and route config updates on Pro projects
  src/_includes/cloud/note-pro-mount-disk-config-yaml-support.md
  src/cloud/env/environments.md
  src/cloud/project/project-conf-files_magento-app.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#6900 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/commerce/2.3.0-2.4-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: Progress: approved

#6902 Generated backward incompatible changes for 2.3.5-develop
  src/_includes/backward-incompatible-changes/commerce/2.3.4-2.3.5-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.3.4-2.3.5-develop.html
Labels: 2.3.5, Progress: approved

#6895 Add documentation for SCD_RUN_BALER env variable for Magento Cloud
  src/cloud/env/variables-build.md
  src/cloud/env/variables-global.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.x, Internal Dev, Progress: approved

#6876 Add GitLab integration for Magento Cloud [GITBUG]
  src/_data/toc/cloud-guide.yml
  src/cloud/integrations/cloud-integrations.md
  src/cloud/integrations/gitlab-integration.md
  src/cloud/project/project-webint-branch.md
  src/cloud/reference/git-integration.md
  src/cloud/requirements/cloud-requirements.md
  src/common/images/cloud_gitlab-deploy-key-form.png
  src/common/images/cloud_gitlab-deploy-key.png
  src/common/images/cloud_gitlab-integration-success.png
  src/common/images/cloud_gitlab-pipelines.png
  src/common/images/cloud_gitlab-settings-main.png
  src/common/images/cloud_gitlab-settings.png
Labels: New Topic, Partner:Agence-DnD-SARL, Progress: approved

#6868 magento/devdocs#:Layout instructions. Adding example of declaring the new new custom noRoute processor
  src/guides/v2.3/extension-dev-guide/routing.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#6906 Update custom-import-entity.md
  src/guides/v2.3/ext-best-practices/tutorials/custom-import-entity.md
Labels: 2.3.x, Partner: Krish TechnoLabs, Progress: approved, Technical, partners-contribution

#6911 magento/devdocs#6896: Using the name variable in Symphony commands
  src/guides/v2.3/extension-dev-guide/cli-cmds/cli-howto.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6913 Updates to the Magento 2.3.x release notes for the March 2020 hot fix
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: 2.3.x, Major Update, Progress: approved

#6915 ASC 4.0 Release Notes
  src/_data/mde.yml
  src/extensions/amazon-sales/index.md
  src/extensions/amazon-sales/release-notes/index.md
  src/release/index.md
Labels: 2.3.x, Channels, Major Update, Progress: approved

#6919 Updating whatsnew with latest
  src/_data/whats-new.yml
Labels: 2.3.x, Internal Dev, Progress: approved

#6920 Update ASC Release Notes
  src/_data/mde.yml
  src/extensions/amazon-sales/release-notes/index.md
Labels: 2.3.x, Channels, Progress: approved

#6921 Clean docker section formatting in readme
  README.md
Labels: Editorial, Internal Dev, Progress: approved

#6873 Add information about ignoreTmpls property
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_template_literals.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#6918 Fix customer auth example with cURL
  src/guides/v2.3/get-started/authentication/gs-authentication-token.md
Labels: 2.3.x, Progress: approved, Technical

#6884 Updating troubleshooting and custom recommendations topics
  src/recommendations/customize.md
  src/recommendations/troubleshooting.md
Labels: 2.3.x, Internal Dev, Progress: approved

#6929 Upgrade whatsup_github (whatsnew)
  Gemfile.lock
Labels: Maintenance, Progress: approved

#6930 Add symlinks to new content for 2.4.0 (round 1)
  src/guides/v2.4/ext-best-practices/tutorials/create-integration-with-api.md
  src/guides/v2.4/ui_comp_guide/components/ui-container.md
Labels: 2.4.0, Internal Dev, Maintenance, Progress: approved

#6910 GraphQL: Add categories query
  src/_data/toc/graphql.yml
  src/_includes/graphql/category-filter-input.md
  src/guides/v2.4/graphql/product/category-interface.md
  src/guides/v2.4/graphql/queries/categories.md
  src/guides/v2.4/graphql/queries/category-list.md
  src/guides/v2.4/graphql/queries/category.md
Labels: 2.4.x, Internal Dev, New Topic, Progress: approved

#6901 [2.4] Upgrade `extension-dev-guide/routing.md` with ActionInterface
  src/guides/v2.4/extension-dev-guide/images/magento2-request-processing.png
  src/guides/v2.4/extension-dev-guide/routing.md
Labels: 2.4.0, Major Update, Partner: Mediotype, Progress: approved, partners-contribution

#6925 GraphQL: Update save_in_address_book attribute
  src/_includes/graphql/cart-address-input-24.md
  src/guides/v2.4/graphql/mutations/set-billing-address.md
  src/guides/v2.4/graphql/mutations/set-shipping-address.md
Labels: 2.4.0, Internal Dev, Progress: approved, Technical

#6926 Added 'Strings added in Underscore templates' section to 'Translate theme strings' page
  src/guides/v2.3/frontend-dev-guide/translations/translate_theory.md
Labels: 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6931 Magento 2 3 x release note tiny formatting fixes
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-open-source.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-4-open-source.md
Labels: Editorial, Internal Dev, Progress: approved

#6892 GraphQL: document the reorderItems mutation
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/reorder-items.md
Labels: 2.4.x, Internal Dev, New Topic, Progress: approved

#6924 Fixed 'Use translation dictionary to customize strings' link
  src/guides/v2.3/frontend-dev-guide/translations/translate_practice.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6903 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: 2.4.x, Progress: approved

#6888 MAGECLOUD-5381 Update extensions and B2B module instructions
  src/_includes/cloud/cli-get-started.md
  src/_includes/cloud/composer-name.md
  src/_includes/cloud/tip-creating-branches.md
  src/cloud/cdn/configure-fastly.md
  src/cloud/cdn/trouble-fastly.md
  src/cloud/configure/setup-b2b.md
  src/cloud/howtos/install-components.md
  src/cloud/trouble/trouble_comp-deploy-fail.md
  src/extensions/b2b/index.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#6933 Adding the implementation of HTTP Action interfaces
  src/guides/v2.3/extension-dev-guide/routing.md
  src/guides/v2.3/ui_comp_guide/howto/update-url-type.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6905 magento/devdocs#: Layout instructions. Improvement - adding changes to Configure services as web APIs topic
  src/guides/v2.3/extension-dev-guide/service-contracts/service-to-web-service.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6932 Added documentation for TimelineColumns UI component
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/ui-timeline-columns-result.png
  src/guides/v2.3/ui_comp_guide/components/ui-timeline-columns.md
Labels: 2.3.x, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#6940 Layout: set block visibility using ACL resource example
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6947 Adding additional information related to tooltip element
  src/common/images/fdg/tooltip-element-result.png
  src/guides/v2.3/frontend-dev-guide/css-topics/theme-ui-lib.md
Labels: 2.3.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#6951 Adding a missing symlink to 2.4
  src/guides/v2.4/ui_comp_guide/components/ui-timeline-columns.md
Labels: Progress: approved

#6945 Generated backward incompatible changes docs for 2.4-develop
  src/_includes/backward-incompatible-changes/open-source/2.3.0-2.4-develop.html
Labels: Progress: approved

#6952 whatsnew for 3/30/20
  src/_data/whats-new.yml
Labels: 2.3.4, Dependencies, Progress: approved

#6938 Example on how to use the viewModel provided from layout in the phtml file
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6950 Set the correct argument names to change store logo from layout xml
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6928 Fixed code style for JSON blocks and styles of the collapsible elements
  src/common/css/devdocs.css
  src/guides/v2.3/rest/tutorials/orders/order-add-items.md
  src/guides/v2.3/rest/tutorials/orders/order-admin-token.md
  src/guides/v2.3/rest/tutorials/orders/order-create-customer.md
  src/guides/v2.3/rest/tutorials/orders/order-create-invoice.md
  src/guides/v2.3/rest/tutorials/orders/order-create-order.md
  src/guides/v2.3/rest/tutorials/orders/order-create-quote.md
  src/guides/v2.3/rest/tutorials/orders/order-create-shipment.md
  src/guides/v2.3/rest/tutorials/orders/order-issue-refund.md
  src/guides/v2.3/rest/tutorials/orders/order-prepare-checkout.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#6935 Adding documentation for WARM_UP_CONCURRENCY config variable on cloud
  src/cloud/env/variables-post-deploy.md
Labels: Internal Dev, Progress: approved

#6944 Add Baler module install and config instructions
  src/cloud/deploy/static-content-deployment.md
Labels: 2.x, Internal Dev, Progress: review, Technical

#6916 Added note regarding use of explicit_defaults_for_timestamps=on
  src/guides/v2.3/install-gde/prereq/mysql.md
Labels: 2.3.x, Partner: Mediotype, Progress: approved, Technical, partners-contribution

#6943 Update to remove RabbitMQ EOL version numbers
  src/guides/v2.3/install-gde/prereq/install-rabbitmq.md
Labels: 2.3.x, Progress: approved, Technical

#6922 magento/devdocs#6912: PHP Extension ext-sockets not in requirement list
  src/guides/v2.3/install-gde/system-requirements-tech.md
Labels: 2.3.x, Partner: Atwix, Progress: approved, partners-contribution

#6799 Optimize communication with Redis [GITBUG]
  src/_data/toc/configuration-guide.yml
  src/guides/v2.3/config-guide/cache/two-level-cache.md
  src/guides/v2.3/config-guide/redis/redis-pg-cache.md
Labels: 2.3.5, Internal Dev, New Topic, Progress: approved

#6783 Create docs for Content Security Policy support
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/security/content-security-policies.md
Labels: 2.3.5, Internal Dev, New Topic, Progress: review

#6839 [GraphQL] Added sample reponse for request example query
  src/guides/v2.3/graphql/send-request.md
Labels: 2.3.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#6917 Add DELETE support
  src/redoc/2.3/index.md
Labels: 2.3.x, Editorial, Partner: Comwrap, Progress: approved, partners-contribution

#6954 Code style fixes on "Creating a Magento admin page"
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: 2.3.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#6941 Updating devdocs with Sensei info
  src/recommendations/images/arch-diag-sensei.svg
  src/recommendations/product-recs.md
Labels: 2.3.x, Internal Dev, Progress: approved

#6958 Advanced Javascript optimization not working
  src/guides/v2.3/performance-best-practices/advanced-js-bundling.md
Labels: Internal Dev, Progress: approved

#6962 Fixes broken links in whatsnew
  src/_data/whats-new.yml
Labels: 2.3.x, Dependencies, Progress: approved
