Repository magento/devdocs, pull requests merged in 2021-11, with the labels that each got.

#9204 Update migration follow up steps
  src/guides/v2.3/migration/migration-migrate-follow-up.md
Labels: Technical, partners-contribution, Partner: Krish TechnoLabs, Progress: approved

#9224 Update PHP examples to match coding standards
  src/_videos/fundamentals/add-a-javascript-module.md
  src/_videos/fundamentals/add-new-product-attribute.md
  src/_videos/fundamentals/create-a-new-module.md
  src/_videos/fundamentals/create-a-new-page.md
  src/cloud/env/variables-deploy.md
  src/contributor-guide/backward-compatible-development/index.md
  src/guides/v2.3/coding-standards/docblock-standard-general.md
  src/guides/v2.3/coding-standards/technical-guidelines.md
  src/guides/v2.3/config-guide/bootstrap/mage-dirs.md
  src/guides/v2.3/config-guide/bootstrap/magento-bootstrap.md
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-i18n.md
  src/guides/v2.3/config-guide/config/config-create.md
  src/guides/v2.3/config-guide/db-profiler/db-profiler.md
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
  src/guides/v2.3/ext-best-practices/tutorials/copy-fieldsets.md
  src/guides/v2.3/ext-best-practices/tutorials/serialized-to-json-data-upgrade.md
  src/guides/v2.3/extension-dev-guide/admin-grid.md
  src/guides/v2.3/extension-dev-guide/api-concepts.md
  src/guides/v2.3/extension-dev-guide/attributes.md
  src/guides/v2.3/extension-dev-guide/build/di-xml-file.md
  src/guides/v2.3/extension-dev-guide/cache/page-caching/public-content.md
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
  src/guides/v2.3/extension-dev-guide/declarative-schema/data-patches.md
  src/guides/v2.3/extension-dev-guide/depend-inj.md
  src/guides/v2.3/extension-dev-guide/events-and-observers.md
  src/guides/v2.3/extension-dev-guide/extend-catalog-rule-conditions.md
  src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
  src/guides/v2.3/extension-dev-guide/factories.md
  src/guides/v2.3/extension-dev-guide/framework/serializer.md
  src/guides/v2.3/extension-dev-guide/indexer-optimization.md
  src/guides/v2.3/extension-dev-guide/message-queues/implement-bulk.md
  src/guides/v2.3/extension-dev-guide/plugins.md
  src/guides/v2.3/extension-dev-guide/prepare/lifecycle.md
Labels: 2.3.x, Technical, partners-contribution, Progress: acceptance testing, 2.4.x, Partner: Fisheye

#9227 Correct syntax for bs-callout-info and bs-callout-warning
  src/cloud/release-notes/cloud-release-archive.md
  src/guides/v2.3/howdoi/checkout/checkout_order.md
  src/guides/v2.4/config-guide/mq/aws-mq.md
  src/guides/v2.4/config-guide/redis/redis-pg-cache.md
Labels: Editorial, 2.3.x, partners-contribution, Progress: approved, Progress: acceptance testing, 2.4.x, Partner: Fisheye

#9228 fix small mistake
  src/guides/v2.4/config-guide/cache/two-level-cache.md
Labels: Editorial, Progress: acceptance testing, 2.4.x

#9231 MC-40750: QPT Landing Page - style fixes
  src/common/js/qpt.app.min.js
  src/quality-patches/tool.md
Labels: 2.x, Progress: acceptance testing, Maintenance

#9240 ACP2E-152: Documentation for new includeDirectChildrenOnly graphql field
  src/guides/v2.4/graphql/queries/products.md
Labels: Major Update, Internal Dev, Progress: approved, 2.4.4

#9233 Change `:version` to `:hash` for L2 caching docs
  src/guides/v2.3/config-guide/cache/two-level-cache.md
  src/guides/v2.4/config-guide/cache/two-level-cache.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Vaimo, Progress: acceptance testing, 2.4.x

#9243 Added a namespace to the example code
  src/guides/v2.3/ui_comp_guide/howto/add_category_attribute.md
Labels: Editorial, 2.3.x, 2.3.4, Progress: acceptance testing

#9250 Fixed link to web-api-access link
  src/guides/v2.4/get-started/authentication/gs-authentication.md
Labels: Editorial, Progress: acceptance testing, 2.4.x

#9208 Added description for reindex in parallel mode command
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-index.md
Labels: Major Update, 2.3.x, partners-contribution, Progress: acceptance testing, Partner: Ziffity, 2.4.x

#9230 Add elasticsearch details in setup install command
  src/cloud/before/before-setup-env-install.md
Labels: Technical, partners-contribution, Partner: Krish TechnoLabs, Progress: acceptance testing

#9241 MC-40750: QPT Landing Page
  src/_includes/install/patch/quality-patch-intro.md
  src/cloud/project/project-patch.md
  src/quality-patches/tool.md
Labels: Editorial, 2.x, Internal Dev, Progress: approved

#9254 Adding Custom Domains to Cloud
  src/cloud/project/project-multi-sites.md
Labels: Progress: approved

#9255 Adobe Commerce Cloud REDIS configuration clarification
  src/guides/v2.3/config-guide/cache/two-level-cache.md
  src/guides/v2.4/config-guide/cache/two-level-cache.md
Labels: 2.x, Technical, Progress: approved

#9274 Fixed list on Extension subscriptions page
  src/marketplace/sellers/subscriptions/extension-subscriptions.md
Labels: Editorial, 2.x, Internal Dev, Progress: approved
