Repository magento/devdocs, pull requests merged in 2021-10, with the labels that each got.

#9163 Fix the example command to rabbitmq tunnel
  src/cloud/project/services-rabbit.md
Labels: Technical, Progress: approved

#9164 Fixed variable declaration error in code example
  src/guides/v2.3/howdoi/custom-attributes/text-field.md
Labels: 2.3.x, Technical, partners-contribution, Progress: acceptance testing, Partner: Ziffity, 2.4.x

#9170 Add disable Google reCAPTCHA for Admin panel Reset Password page from command-line
  src/guides/v2.4/security/google-recaptcha.md
Labels: Editorial, partners-contribution, Partner: Krish TechnoLabs, Progress: acceptance testing, 2.4.x

#9173 Add example for reset user 2FA configuration command for 2.3 and 2.4
  src/guides/v2.3/security/two-factor-authentication.md
  src/guides/v2.4/security/two-factor-authentication.md
Labels: 2.3.x, Technical, partners-contribution, Partner: Krish TechnoLabs, Progress: approved, 2.4.x
