Repository magento/devdocs, pull requests merged in 2021-12, with the labels that each got.

#9267 Updated PHPStorm UCT related info after the last release
  src/common/images/phpstorm/built-in-uct/uct-inspections-highlighting-2.png
  src/common/images/phpstorm/built-in-uct/uct-inspections-highlighting-3.png
  src/common/images/phpstorm/built-in-uct/uct-inspections-highlighting-4.png
  src/common/images/phpstorm/built-in-uct/uct-inspections-settings.png
  src/guides/v2.3/ext-best-practices/phpstorm/built-in-upgrade-compatibility-tool.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#9277 Fix spelling error
  src/guides/v2.3/frontend-dev-guide/layouts/layout-override.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9284 Document where the GraphQL schema is cached.
  src/guides/v2.4/graphql/caching.md
Labels: Editorial, Progress: approved, 2.4.x

#9278 Add section about inspecting compressed data
  src/_includes/config/redis-verify.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9285 Added information about snapshots for Pro Plans
  src/cloud/project/project-webint-snap.md
Labels: 2.x, Technical, Progress: acceptance testing

#9289 Update contributing.md
  src/guides/v2.3/config-guide/log/log-magento.md
Labels: Internal Dev, partners-contribution, Progress: acceptance testing, Partner: Test team
