Repository magento/devdocs, pull requests merged in 2021-01, with the labels that each got.

#8443 correct path for di.xml
  src/guides/v2.3/frontend-dev-guide/themes/admin_theme_apply.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8444 Added the error coverage for redeemGiftCardBalanceAsStoreCredit mutation
  src/guides/v2.3/graphql/mutations/redeem-giftcard-balance.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8447 added error coverage for remove-store-credit mutation
  src/guides/v2.4/graphql/mutations/remove-store-credit.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8448 added the error coverage for removeRewardPointsFromCart mutation
  src/guides/v2.4/graphql/mutations/remove-reward-points.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8449 added the errors coverage for apply giftCard mutation
  src/guides/v2.4/graphql/mutations/apply-giftcard.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8450 Added the error coverage for applyStoreCreditToCart mutation
  src/guides/v2.3/graphql/mutations/apply-store-credit.md
  src/guides/v2.4/graphql/mutations/apply-store-credit.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8452 Added the error coverage for pickupLocations query
  src/guides/v2.4/graphql/queries/pickup-locations.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8453 Added the error coverage for urlResolver query
  src/guides/v2.3/graphql/queries/url-resolver.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8454 added error coverage for payflowtoken mutation
  src/guides/v2.3/graphql/mutations/create-payflow-pro-token.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8455 added error coverage for apply-reward-points mutation
  src/guides/v2.4/graphql/mutations/apply-reward-points.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8456 Added the error coverage for giftCardAccount query
  src/guides/v2.3/graphql/queries/giftcard-account.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8457 Added errors documentation for paypal express token mutation
  src/guides/v2.3/graphql/mutations/create-paypal-express-token.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8430 Sample data Update
  src/_includes/install/sampledata/sample-data_list-of-modules.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: EY, Progress: approved, partners-contribution

#8460 Spelling mistake fixed
  src/guides/v2.3/graphql/index.md
  src/guides/v2.4/graphql/index.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#8463 Token expires info added
  src/guides/v2.3/graphql/authorization-tokens.md
  src/guides/v2.4/graphql/authorization-tokens.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: ready for review, partners-contribution

#8462 Merge small-changes branch into master
  src/_includes/install/sampledata/sample-data_list-of-modules.md
  src/guides/v2.3/frontend-dev-guide/themes/admin_theme_apply.md
  src/guides/v2.3/graphql/authorization-tokens.md
  src/guides/v2.3/graphql/mutations/apply-store-credit.md
  src/guides/v2.3/graphql/mutations/create-payflow-pro-token.md
  src/guides/v2.3/graphql/mutations/create-paypal-express-token.md
  src/guides/v2.3/graphql/mutations/redeem-giftcard-balance.md
  src/guides/v2.3/graphql/queries/giftcard-account.md
  src/guides/v2.3/graphql/queries/url-resolver.md
  src/guides/v2.4/graphql/authorization-tokens.md
  src/guides/v2.4/graphql/mutations/apply-giftcard.md
  src/guides/v2.4/graphql/mutations/apply-reward-points.md
  src/guides/v2.4/graphql/mutations/apply-store-credit.md
  src/guides/v2.4/graphql/mutations/remove-reward-points.md
  src/guides/v2.4/graphql/mutations/remove-store-credit.md
  src/guides/v2.4/graphql/queries/pickup-locations.md
Labels: Maintenance, Progress: approved

#8373 Use a layout processor rather than plugin in the "Customize the view of a checkout step" docs
  src/guides/v2.3/howdoi/checkout/checkout_customize.md
Labels: 2.4.x, Progress: approved, Technical

#8445 Update gdpr.md
  src/compliance/privacy/gdpr.md
Labels: Editorial, Progress: approved

#8469 Mae ssh enablement improvements
  src/_includes/cloud/enable-ssh.md
Labels: Progress: approved

#8470 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#8464 Update project-webint-basic.md
  src/cloud/project/project-webint-basic.md
Labels: 2.x, Progress: approved, Small Changes, Technical

#8371 Fixing jslint errors
  src/common/js/glossary-link-enhancer.js
  src/guides/v2.3/performance-best-practices/samples/build.js
  src/guides/v2.3/performance-best-practices/samples/deps.js
Labels: Maintenance, Progress: approved

#8476 Added the error coverage for cart query
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/cart.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8473 Added the error coverage for isEmailAvailable query
  src/guides/v2.3/graphql/queries/is-email-available.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8468 Added error coverage for createProductReview mutation
  src/guides/v2.4/graphql/mutations/create-product-review.md
Labels: 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8467 Added the error coverage for getHostedProUrl query
  src/guides/v2.3/graphql/queries/get-hosted-pro-url.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: EY, Progress: approved, partners-contribution

#8478 Fixing incorrect table name in SQL
  src/guides/v2.3/config-guide/prod/config-reference-var-name.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8432 JS formatting and grammar fixes
  src/guides/v2.3/howdoi/checkout/checkout_new_step.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8477 Update js-resources.md
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
Labels: 2.4.x, Progress: approved, Technical

#8485 Sync 2.4.2-develop
  src/_data/whats-new.yml
  src/_includes/cloud/enable-ssh.md
  src/_includes/install/sampledata/sample-data_list-of-modules.md
  src/cloud/project/project-webint-basic.md
  src/common/js/glossary-link-enhancer.js
  src/compliance/privacy/gdpr.md
  src/guides/v2.3/config-guide/prod/config-reference-var-name.md
  src/guides/v2.3/frontend-dev-guide/themes/admin_theme_apply.md
  src/guides/v2.3/graphql/authorization-tokens.md
  src/guides/v2.3/graphql/mutations/apply-store-credit.md
  src/guides/v2.3/graphql/mutations/create-payflow-pro-token.md
  src/guides/v2.3/graphql/mutations/create-paypal-express-token.md
  src/guides/v2.3/graphql/mutations/redeem-giftcard-balance.md
  src/guides/v2.3/graphql/queries/cart.md
  src/guides/v2.3/graphql/queries/get-hosted-pro-url.md
  src/guides/v2.3/graphql/queries/giftcard-account.md
  src/guides/v2.3/graphql/queries/is-email-available.md
  src/guides/v2.3/graphql/queries/url-resolver.md
  src/guides/v2.3/howdoi/checkout/checkout_customize.md
  src/guides/v2.3/performance-best-practices/samples/build.js
  src/guides/v2.3/performance-best-practices/samples/deps.js
  src/guides/v2.4/graphql/authorization-tokens.md
  src/guides/v2.4/graphql/mutations/add-requisition-list-items-to-cart.md
  src/guides/v2.4/graphql/mutations/apply-giftcard.md
  src/guides/v2.4/graphql/mutations/apply-reward-points.md
  src/guides/v2.4/graphql/mutations/apply-store-credit.md
  src/guides/v2.4/graphql/mutations/create-product-review.md
  src/guides/v2.4/graphql/mutations/move-items-between-requisition-lists.md
  src/guides/v2.4/graphql/mutations/remove-reward-points.md
  src/guides/v2.4/graphql/mutations/remove-store-credit.md
  src/guides/v2.4/graphql/mutations/update-requisition-list-items.md
  src/guides/v2.4/graphql/queries/cart.md
  src/guides/v2.4/graphql/queries/pickup-locations.md
Labels: 2.4.2, Maintenance, Progress: approved

#8474 Add information about Composer 2 compatibility
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/install-gde/system-requirements.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8482 Added the error coverage for country query
  src/guides/v2.3/graphql/queries/directory-country.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8484 File menu path fix
  src/cloud/howtos/debug.md
Labels: Editorial, Progress: approved

#8488 Added a legal disclaimer about the "date_of_birth" customer attribute
  src/_includes/graphql/create-customer.md
  src/_includes/graphql/customer-input-24.md
  src/_includes/graphql/customer-input.md
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/customer-output.md
  src/compliance/privacy/pi-data-reference-m2.md
  src/guides/v2.3/config-guide/prod/config-reference-most.md
  src/guides/v2.3/extension-dev-guide/configuration/sensitive-and-environment-settings.md
  src/guides/v2.3/graphql/develop/resolvers.md
  src/guides/v2.4/config-guide/prod/config-reference-most.md
  src/guides/v2.4/graphql/mutations/create-customer-v2.md
  src/guides/v2.4/graphql/mutations/update-customer-v2.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: approved

#8486 MCLOUD-7120: Add command which validate .magento.env.yaml locally before push
  src/cloud/project/magento-env-yaml.md
Labels: Internal Dev, Progress: approved

#8489 Added the error coverage for category query
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.4/graphql/queries/category.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8492 Update theme-structure.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8498 Sync 2.4.2-develop
  src/_includes/graphql/create-customer.md
  src/_includes/graphql/customer-input-24.md
  src/_includes/graphql/customer-input.md
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/customer-output.md
  src/cloud/howtos/debug.md
  src/compliance/privacy/pi-data-reference-m2.md
  src/guides/v2.3/config-guide/prod/config-reference-most.md
  src/guides/v2.3/extension-dev-guide/configuration/sensitive-and-environment-settings.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-structure.md
  src/guides/v2.3/graphql/develop/resolvers.md
  src/guides/v2.3/graphql/queries/category.md
  src/guides/v2.3/graphql/queries/directory-country.md
  src/guides/v2.3/howdoi/checkout/checkout_new_step.md
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
  src/guides/v2.4/config-guide/prod/config-reference-most.md
  src/guides/v2.4/graphql/mutations/create-customer-v2.md
  src/guides/v2.4/graphql/mutations/update-customer-v2.md
  src/guides/v2.4/graphql/queries/category.md
Labels: 2.4.2, Maintenance, Progress: approved

#8495 Issue-8491 - Corrected the port numbers under Mailhog topic
  src/cloud/docker/docker-containers-service.md
Labels: Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8499 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#8496 A look of a sub-header
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#8164 Update config-reference-systemxml.md
  src/guides/v2.3/config-guide/prod/config-reference-systemxml.md
  src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8500 Inventory 1.2.2 release notes.
  src/guides/v2.3/inventory/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#8501 Issue-8471-Clarified the information on environments
  src/cloud/reference/cli-ref-topic.md
Labels: Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8497 Update theme-structure.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-structure.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8507 GraphQL: Update schema descriptions for B2B companies
  src/_includes/graphql/company-team.md
  src/_includes/graphql/company.md
  src/guides/v2.4/graphql/mutations/create-company-role.md
  src/guides/v2.4/graphql/mutations/create-company.md
  src/guides/v2.4/graphql/mutations/delete-company-role.md
  src/guides/v2.4/graphql/mutations/delete-company-team.md
  src/guides/v2.4/graphql/mutations/delete-company-user.md
  src/guides/v2.4/graphql/mutations/update-company-team.md
  src/guides/v2.4/graphql/mutations/update-company.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#8509 Whatsnew fix
  src/_data/whats-new.yml
Labels: Progress: approved

#8506 GraphQL: Add bundle product examples to addProductsToCart
  src/guides/v2.4/graphql/mutations/add-products-to-cart.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8502 MCLOUD-7204: Update Redis and ES service versions
  src/cloud/docker/docker-containers.md
  src/cloud/project/services-redis.md
  src/cloud/project/services.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: approved, Tracking

#8503 MCLOUD-7393: Add Redis and MariaDB to Alerts
  src/cloud/project/new-relic.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved, Tracking

#8512 Fix email address
  src/cloud/docker/docker-development.md
Labels: Editorial, Progress: approved

#8511 Updated mcd-release var
  src/_data/var.yml
Labels: 2.4.x, Internal Dev, Progress: approved

#8514 Added new feature to B2B release notes.
  src/guides/v2.4/release-notes/b2b-release-notes.md
Labels: 2.4.2, Editorial, Progress: approved

#8513 GraphQL: Add total_giftcard to schema
  src/_includes/graphql/customer-orders-output.md
Labels: 2.4.3, Internal Dev, Progress: approved, Technical

#8438 Update array-manager.md
  src/guides/v2.3/extension-dev-guide/framework/array-manager.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8440 MCLOUD-7410: DKIM signatures
  src/cloud/project/sendgrid.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved, Waiting for Response

#8508 Updated the response for api endpoints & added additional info
  src/guides/v2.3/rest/tutorials/configurable-product/create-configurable-product.md
  src/guides/v2.3/rest/tutorials/configurable-product/plan-product.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8515 Add info about required API key and SaaS Environment
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-catalog-sync.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8520 MC-40381: [Documentation] Update documentation for DMT not used code migration tool
  src/guides/v2.3/migration/bk-migration-guide.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#8521 Address typos
  src/cloud/project/user-admin.md
  src/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.md
  src/guides/v2.3/extension-dev-guide/message-queues/async-message-queue-config-files.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#8525 Config Guide: Fix link to external file
  src/guides/v2.4/config-guide/prod/config-reference-gitignore.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8534 Update packages.md
  src/marketplace/eqp/v1/packages.md
Labels: Internal Dev, Progress: approved, Technical

#8528 Fix typo and redundant wording
  src/guides/v2.3/extension-dev-guide/view-models.md
Labels: 2.4.x, Editorial, Progress: approved

#8419 Added missing context type in requirejs-config mapping
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8531 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#8529 Update js-resources.md
  src/guides/v2.3/javascript-dev-guide/javascript/js-resources.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8524 Cloud: fix code block in Snapshots topic
  src/cloud/project/project-webint-snap.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#8395 Issue-8347 - added new product attribute documentation
  src/_videos/fundamentals/add-new-product-attribute.md
Labels: Major Update, Partner: EY, Progress: approved, partners-contribution

#8483 Pull requests tests documentation for contributors
  src/_data/toc/contributor-guide.yml
  src/contributor-guide/contributing.md
  src/contributor-guide/pull-request-tests.md
Labels: Internal Dev, New Topic, Progress: review

#8314 MC-35509: Updated the software update guide module with the safe upgrade tool documentation
  src/_data/toc/software-update-guide.yml
  src/_includes/layout/page-header.html
  src/guides/v2.3/comp-mgr/bk-compman-upgrade-guide.md
  src/guides/v2.4/comp-mgr/bk-compman-upgrade-guide.md
  src/safe-upgrade-tool/developer.md
  src/safe-upgrade-tool/img/audience-sut.png
  src/safe-upgrade-tool/img/mvp-diagram-v2.png
  src/safe-upgrade-tool/img/mvp-diagram.png
  src/safe-upgrade-tool/install.md
  src/safe-upgrade-tool/introduction.md
  src/safe-upgrade-tool/prerequisites.md
  src/safe-upgrade-tool/run.md
Labels: Internal Dev, Major Update, New Topic, Progress: approved

#8535 Issue-8490-Sample changed in 2.4 version
  src/guides/v2.4/install-gde/install/post-install-config.md
Labels: Editorial, Partner: EY, Progress: approved, Small Changes, partners-contribution

#8472 Additional nodes added
  src/guides/v2.3/frontend-dev-guide/layouts/layout-types.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#8538 magento/devdocs#: Adding item to the list
  src/_includes/install/sampledata/sample-data-clone-24.md
  src/_includes/install/sampledata/sample-data-clone.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: approved, partners-contribution

#8518 Update indexer-batch.md
  src/guides/v2.4/extension-dev-guide/indexer-batch.md
Labels: 2.4.3, Major Update, Progress: approved

#8548 Delete the 'the' duplicates
  src/_data/whats-new.yml
  src/_includes/cloud/error-codes.md
  src/cloud/env/environment-vars_magento.md
  src/cloud/project/project-webint-snap.md
  src/cloud/project/services-rabbit.md
  src/cloud/project/services.md
  src/contributor-guide/contributing.md
  src/guides/v2.3/graphql/custom-filters.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  src/guides/v2.3/release-notes/release-notes-2-3-3-commerce.md
  src/recommendations/install-configure.md
  src/recommendations/product-recs.md
Labels: 2.x, Editorial, Progress: approved

#8533 magento/devdocs#: Minor grammar fixes
  src/guides/v2.3/frontend-dev-guide/bk-frontend-dev-guide.md
  src/guides/v2.3/frontend-dev-guide/css-guide/css_quick_guide_approach.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-overview.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-types.md
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd-breakpoints.md
  src/guides/v2.3/frontend-dev-guide/theme-best-practice.md
  src/guides/v2.3/frontend-dev-guide/themes/product-video.md
  src/guides/v2.4/frontend-dev-guide/bk-frontend-dev-guide.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#8541 MQP Release 1.0.14
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: approved

#8481 Update content css preprocess
  src/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8459 #8458 getViewModel() results in null
  src/guides/v2.3/extension-dev-guide/view-models.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8542 Clean up Troubleshooting area
  src/_data/toc/installation-guide.yml
  src/_includes/install/file-system-perms-before.md
  src/_includes/install/file-system-perms-before_22.md
  src/_includes/install/file-system-umask-over.md
  src/guides/v2.3/install-gde/continue-to-cm-updater.md
  src/guides/v2.3/install-gde/install-resource-diagram.md
  src/guides/v2.3/install-gde/install-resources-parent.md
  src/guides/v2.3/install-gde/install/legacy-file-system-perms.md
  src/guides/v2.3/install-gde/prereq/apache.md
  src/guides/v2.3/install-gde/prereq/merch_install.md
  src/guides/v2.3/install-gde/trouble/php/tshoot_install-main.md
  src/guides/v2.3/install-gde/trouble/php/tshoot_nginx-port.md
  src/guides/v2.3/install-gde/trouble/php/tshoot_pdo.md
  src/guides/v2.3/install-gde/trouble/php/tshoot_session.md
  src/guides/v2.3/install-gde/trouble/php/tshoot_xdebug.md
  src/guides/v2.3/install-gde/trouble/tshoot_composer-fail.md
  src/guides/v2.3/install-gde/trouble/tshoot_install-log.md
  src/guides/v2.4/install-gde/bk-install-guide.md
  src/guides/v2.4/install-gde/continue-to-cm-updater.md
  src/guides/v2.4/install-gde/install-quick-ref.md
  src/guides/v2.4/install-gde/install-resource-diagram.md
  src/guides/v2.4/install-gde/install-roadmap_cli.md
  src/guides/v2.4/install-gde/install-roadmap_trouble.md
  src/guides/v2.4/install-gde/install/cli/install-cli-install.md
  src/guides/v2.4/install-gde/install/legacy-file-system-perms.md
  src/guides/v2.4/install-gde/prereq/apache.md
  src/guides/v2.4/install-gde/prereq/es-config-nginx.md
  src/guides/v2.4/install-gde/prereq/merch_install.md
  src/guides/v2.4/install-gde/trouble/git/tshoot_clone.md
  src/guides/v2.4/install-gde/trouble/git/tshoot_git-main.md
  src/guides/v2.4/install-gde/trouble/git/tshoot_git-pull-origin.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_70pct.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_access-main.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_install-main.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_nginx-port.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_opcache.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_pdo.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_php-date.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_php-main.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_php-set.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_session.md
  src/guides/v2.4/install-gde/trouble/php/tshoot_xdebug.md
  src/guides/v2.4/install-gde/trouble/readiness/tshoot_rc_cron.md
  src/guides/v2.4/install-gde/trouble/readiness/tshoot_rc_depend.md
  src/guides/v2.4/install-gde/trouble/readiness/tshoot_rc_main.md
  src/guides/v2.4/install-gde/trouble/readiness/tshoot_rc_perms.md
  src/guides/v2.4/install-gde/trouble/readiness/tshoot_rc_php.md
  src/guides/v2.4/install-gde/trouble/tshoot_access-browser.md
  src/guides/v2.4/install-gde/trouble/tshoot_admin.md
  src/guides/v2.4/install-gde/trouble/tshoot_composer-fail.md
  src/guides/v2.4/install-gde/trouble/tshoot_exceptions.md
  src/guides/v2.4/install-gde/trouble/tshoot_install-issues.md
  src/guides/v2.4/install-gde/trouble/tshoot_install-log.md
  src/guides/v2.4/install-gde/trouble/tshoot_no-styles.md
  src/guides/v2.4/install-gde/trouble/tshoot_sample-data.md
  src/guides/v2.4/install-gde/trouble/tshoot_wrong-mysql.md
  src/guides/v2.4/install-gde/tutorials/change-docroot-to-pub.md
  src/marketplace/sellers/installation-and-varnish-tests.md
Labels: Internal Dev, Maintenance, Progress: review

#8550 Update manage-sources.md
  src/guides/v2.4/rest/modules/inventory/manage-sources.md
Labels: Editorial, Progress: approved, Small Changes

#8549 MC-40582: Update the install page with how to download the SUT tool via command line
  src/_includes/layout/page-header.html
  src/quality-patches/release-notes.md
  src/safe-upgrade-tool/install.md
  src/safe-upgrade-tool/introduction.md
  src/safe-upgrade-tool/run.md
Labels: Editorial, Internal Dev, Progress: approved

#8543 Added the error coverage for cmsPage query
  src/guides/v2.3/graphql/queries/cms-page.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8537 Added the error coverage for cmsBlocks query
  src/guides/v2.3/graphql/queries/cms-blocks.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8517 Update indexing.md
  src/guides/v2.4/extension-dev-guide/indexing.md
Labels: 2.4.3, Progress: approved

#8530 Examples and links added
  src/guides/v2.3/graphql/custom-filters.md
Labels: 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8523 Minor edits to addRequisitionListItemsToCart
  src/guides/v2.4/graphql/mutations/add-requisition-list-items-to-cart.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#8547 Adding static analysis topic from wiki
  src/_data/toc/testing.yml
  src/common/images/static-codesniff.png
  src/common/images/static-eslint.png
  src/common/images/static-jscs.png
  src/common/images/static-md.png
  src/guides/v2.3/test/static/static-analysis.md
  src/guides/v2.4/test/static/static-analysis.md
Labels: 2.3.x, 2.4.x, New Topic, Progress: approved

#8439 Add Datetime Library
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/framework/datetime.md
  src/guides/v2.4/extension-dev-guide/framework/datetime.md
Labels: 2.3.x, 2.4.x, New Topic, Partner: EY, Progress: approved, partners-contribution

#8560 MCLOUD-7504: Remove outdated ES images from Cloud Docker
  src/cloud/docker/docker-containers.md
Labels: Progress: approved

#8559 Magento 2 4 2 release notes --update 01/26
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/guides/v2.4/release-notes/commerce-2-4-2.md
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.2, Internal Dev, Progress: review

#8557 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#8562 Call to MySQL cli should not have a space before password value
  src/cloud/project/services-mysql.md
Labels: Internal Dev, Progress: approved

#8553 MC-40585: Removed acronym SUT entries and changed naming convention for the Upgrade Compability Tool
  src/_data/toc/software-update-guide.yml
  src/_data/whats-new.yml
  src/_includes/layout/page-header.html
  src/guides/v2.3/comp-mgr/bk-compman-upgrade-guide.md
  src/guides/v2.3/extension-dev-guide/framework/datetime.md
  src/guides/v2.4/comp-mgr/bk-compman-upgrade-guide.md
  src/safe-upgrade-tool/install.md
  src/safe-upgrade-tool/introduction.md
  src/safe-upgrade-tool/prerequisites.md
  src/upgrade-compatibility-tool/developer.md
  src/upgrade-compatibility-tool/img/audience-uct.png
  src/upgrade-compatibility-tool/img/mvp-diagram-v2.png
  src/upgrade-compatibility-tool/img/mvp-diagram.png
  src/upgrade-compatibility-tool/install.md
  src/upgrade-compatibility-tool/introduction.md
  src/upgrade-compatibility-tool/prerequisites.md
  src/upgrade-compatibility-tool/run.md
Labels: Major Update, Progress: review

#8522 Update Cloud upgrade section based on hotjar feedback
  src/cloud/project/project-upgrade.md
Labels: Progress: approved

#8569 Delete duplicates
  src/_data/whats-new.yml
  src/cloud/project/privatelink-service.md
  src/cloud/release-notes/mcd-release-notes.md
  src/guides/v2.3/b2b/negotiable-checkout.md
  src/guides/v2.3/extension-dev-guide/xss-protection.md
  src/guides/v2.3/install-gde/prereq/nginx.md
  src/guides/v2.3/pattern-library/controls/buttons/buttons.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.1Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.md
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/extension-dev-guide/xss-protection.md
  src/guides/v2.4/install-gde/prereq/nginx.md
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.x, Editorial, Progress: approved

#8536 magento/devdocs#: Added rowbuilder info
  src/guides/v2.3/javascript-dev-guide/widgets/widget-row-builder.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#8573 MC-40649: Included redirects for old Safe Upgrade Tool links
  src/upgrade-compatibility-tool/developer.md
  src/upgrade-compatibility-tool/install.md
  src/upgrade-compatibility-tool/introduction.md
  src/upgrade-compatibility-tool/prerequisites.md
  src/upgrade-compatibility-tool/run.md
Labels: Editorial, Progress: approved

#8567 Add information about GraphQL Fasly cache
  src/guides/v2.3/graphql/caching.md
  src/guides/v2.4/graphql/caching.md
Labels: 2.3.x, 2.4.x, Partner: Comwrap, Progress: approved, Technical, partners-contribution

#8575 Release policy updates
  src/release/policy/index.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8568 MCLOUD-1329 Delete set-variables.md
  src/cloud/env/set-variables.md
Labels: Internal Dev, Progress: approved

#8583 Added info about the optin --custom-registry
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Progress: approved

#8585 Disable the jscpd linter
  .github/workflows/linter.yml
Labels: Maintenance, Progress: approved

#8584 GraphQL: Update schema to include undocumented changes
  src/_includes/graphql/store-config.md
  src/guides/v2.4/graphql/interfaces/category-interface.md
  src/guides/v2.4/graphql/interfaces/product-interface.md
Labels: 2.4.2, Community, Internal Dev, Progress: approved, Technical

#8556 magento/devdocs#: added example of using the gallery widget
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: Atwix, Progress: approved, partners-contribution

#8586 GraphQL: Updates per PR-8526
  src/guides/v2.4/graphql/queries/products.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8588 MCLOUD-7173: Update default Disc and DB value. for Magento cloud
  src/cloud/project/magento-app-properties.md
  src/cloud/project/services-mysql.md
  src/cloud/project/services.md
Labels: Internal Dev, Major Update, Progress: approved, Tracking

#8539 GraphQL: Add configured_variant attribute
  src/guides/v2.4/graphql/interfaces/cart-item-interface.md
Labels: 2.4.3, Community, Internal Dev, Progress: approved, Technical

#8580 Added maintainer handbook
  src/_data/toc/contributor-guide.yml
  src/contributor-guide/img/approve-changes.png
  src/contributor-guide/img/award-labels.png
  src/contributor-guide/img/builds-and-checks.png
  src/contributor-guide/img/deployment-comments.png
  src/contributor-guide/img/pr-code-review.png
  src/contributor-guide/img/pr-dashboard.png
  src/contributor-guide/img/pr-target-branch.png
  src/contributor-guide/img/related-prs.png
  src/contributor-guide/img/repo-and-projects.png
  src/contributor-guide/img/slack-channel.png
  src/contributor-guide/img/test-coverage-labels.png
  src/contributor-guide/maintainer-handbook.md
Labels: 2.x, Internal Dev, New Topic, Progress: approved

#8591 Copy edit release policy
  src/release/policy/index.md
Labels: Editorial, Internal Dev, Progress: approved

#8593 Clarify sentence for clarity
  src/contributor-guide/maintainer-handbook.md
Labels: 2.x, Editorial, Progress: approved

#8590 Cloud: change variable name
  src/cloud/project/manage-disk-space.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved, Small Changes

#8597 update manage-low-quantity.md
  src/guides/v2.3/rest/modules/inventory/manage-low-quantity.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Progress: on hold

#8596 Made changes as per magento standard docs format.
  src/guides/v2.3/frontend-dev-guide/themes/debug-theme.md
  src/guides/v2.3/frontend-dev-guide/themes/favicon.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-apply.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-install.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-uninstall.md
  src/guides/v2.4/frontend-dev-guide/themes/theme-install.md
  src/guides/v2.4/frontend-dev-guide/themes/theme-uninstall.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved
