Repository magento/devdocs, pull requests merged in 2021-05, with the labels that each got.

#8882 Added new page for Magento\Framework\Math\Random
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/framework/math-random.md
  src/guides/v2.4/extension-dev-guide/framework/math-random.md
Labels: 2.3.x, 2.4.x, New Topic, Partner: EY, Progress: acceptance testing, partners-contribution

#8883 Added new page for Magento\Framework\Math\FloatComparator
  src/_data/toc/php-developer-guide.yml
  src/guides/v2.3/extension-dev-guide/framework/float-comparator.md
  src/guides/v2.4/extension-dev-guide/framework/float-comparator.md
Labels: 2.3.x, 2.4.x, New Topic, Partner: EY, Progress: acceptance testing, partners-contribution

#8901 Custom code added to primary button in theme less file
  src/guides/v2.3/frontend-dev-guide/css-topics/css-overview.md
Labels: 2.3.4, 2.4.x, Partner: Ziffity, Progress: acceptance testing, Technical, partners-contribution

#8909 Provide a bit more specificity in favor of #8908
  src/extensions/b2b/index.md
Labels: Editorial, Progress: acceptance testing

#8911 Fix broken list structure of the PoisonPill interfaces
  src/guides/v2.3/extension-dev-guide/message-queues/refresh-config.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#8913 Add email content ss
  src/common/images/custom_variables.png
  src/common/images/store_information.png
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8916 Deployment command added for the frontend and backend separately.
  src/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: acceptance testing, Technical, partners-contribution

#8923 MQP Release 1.0.22
  src/guides/v2.3/extension-dev-guide/prepare/ext-repo-structure.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8915 Example validation argument added to the form fields
  src/guides/v2.3/frontend-dev-guide/validations/custom-form-validation.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: acceptance testing, Technical, partners-contribution

#8918 Magento_ProductRecommendationsStorefront - phtml and Layout file path updated.
  src/recommendations/customize.md
Labels: Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8920 Add the image-clarification for the Magnifier widget
  src/common/images/magnifier-widget.png
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#8921 Area specific di.xml file path updated
  src/guides/v2.3/extension-dev-guide/build/di-xml-file.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8932 Default breakpoint file path added
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8937 Adde link to source Magnifier widget page
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#8938 Update redis-pg-cache.md
  src/guides/v2.3/extension-dev-guide/build/di-xml-file.md
Labels: Editorial, Internal Dev, Progress: acceptance testing

#8944 Correct SFTP configuration instructions
  src/cloud/env/environments-ssh.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8949 Deploy mode information added on the build system topic
  src/guides/v2.3/config-guide/deployment/pipeline/build-system.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8953 DEVDOCS-SMALL-FIXES: Fixed versions in "Example - Manage packages" - Magento 2.4
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
Labels: Editorial, Progress: acceptance testing

#8922 Added notification callouts to relevant pages, explaining that MFTF checks are not required by EQP
  src/marketplace/sellers/mftf-magento.md
  src/marketplace/sellers/mftf-vendor.md
Labels: Internal Dev, Progress: acceptance testing

#8934 FrontName example link added on Routing topic
  src/guides/v2.3/extension-dev-guide/routing.md
  src/guides/v2.4/extension-dev-guide/routing.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8957 MQP Release 1.0.23
  src/quality-patches/release-notes.md
Labels: 2.x, Major Update, Progress: approved

#8958 API > Special price > Fix syntax
  src/guides/v2.3/rest/modules/catalog-pricing.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Le Site, Progress: approved, partners-contribution

#8950 Improvements on event observer topic
  src/guides/v2.3/extension-dev-guide/events-and-observers.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8956 Update ulimit terminology
  src/_data/toc/software-update-guide.yml
  src/_includes/install/ulimit.md
  src/guides/v2.3/comp-mgr/prereq/prereq_compman-ulimit.md
  src/guides/v2.3/install-gde/install/cli/install-cli-backup.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution
