Repository magento/devdocs, pull requests merged in 2021-04, with the labels that each got.

#8849 Update config-remote-storage-aws-s3.md
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.md
Labels: Internal Dev, Progress: acceptance testing

#8850 Add note to clarify when using guest endpoint
  src/_data/whats-new.yml
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8853 Fix typo
  src/guides/v2.3/config-guide/db-profiler/db-profiler.md
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
  src/guides/v2.4/config-guide/db-profiler/db-profiler.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing, Small Changes

#8837 New topic - show or hide password checkbox implementation
  src/_data/toc/ui-components-guide.yml
  src/common/images/ui_comps/show-or-hide-password-checkbox-v2.1.png
  src/guides/v2.4/ui_comp_guide/howto/show_or_hide_password_checkbox.md
Labels: 2.3.x, 2.4.x, New Topic, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8851 Update resource model admin grid tut
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8852 Correct content grunt tasks
  src/guides/v2.3/frontend-dev-guide/tools/using_grunt.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8854 env.php configuration values
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8858 magento/devdocs#: Custom admin URL naming
  src/cloud/env/environment-vars_magento.md
Labels: Progress: acceptance testing

#8859 show-password component info and magento code base link added
  src/guides/v2.4/ui_comp_guide/howto/show_or_hide_password_checkbox.md
Labels: 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8860 Update code sample init date picker calendar widget
  src/guides/v2.3/javascript-dev-guide/widgets/widget_calendar.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Small Changes, Technical

#8866 Fix shell commands
  src/guides/v2.3/ext-best-practices/extension-coding/example-module-adminpage.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing, Small Changes

#8870 Magento_Ui module directory path updated
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uiclass_concept.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uicollection_concept.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uielement_concept.md
Labels: 2.3.4, 2.3.x, Editorial, Partner: Ziffity, Progress: acceptance testing, Progress: approved, partners-contribution

#8878 MQP Release 1.0.20
  src/quality-patches/release-notes.md
Labels: Internal Dev, Major Update, Progress: acceptance testing

#8879 Added js unit tests run examples for frontend area
  src/guides/v2.3/test/js/jasmine.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8874 magento/devdocs#8873: Add clarification about required parameter for date validation
  src/guides/v2.4/javascript-dev-guide/widgets/widget_calendar.md
Labels: Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#8895 MQP Release 1.0.21
  src/quality-patches/release-notes.md
Labels: 2.3.x, 2.4.x, Internal Dev, Major Update, Progress: approved

#8888 File path info added for customization
  src/guides/v2.3/frontend-dev-guide/layouts/layout-types.md
Labels: Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#8892 JS tests debugging instructions
  src/guides/v2.3/test/js/jasmine.md
Labels: 2.3.x, 2.4.x, Internal Dev, Progress: acceptance testing, Technical

#8896 Updated Download Link of Upgrade Tool
  src/upgrade-compatibility-tool/install.md
Labels: Editorial, Progress: acceptance testing

#8898 Add clarification about date component validation
  src/guides/v2.3/ui_comp_guide/components/ui-date.md
Labels: Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#8904 Fix link rendering
  src/cloud/env/variables-deploy.md
Labels: Editorial, Internal Dev, Progress: acceptance testing

#8905 Magento/devdocs. Issue #8897.Set docroot - remove mention of setup wizard in 2.37
  src/cloud/before/before-setup-env-install.md
Labels: Partner: Atwix, Progress: approved, partners-contribution
