Repository magento/devdocs, pull requests merged in 2021-06, with the labels that each got.

#8919 magento/devdocs#8666 Adding instruction - how to stop queue workers.
  src/_includes/config/split-deploy/example_update-prod.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#8943 magento/devdocs #8928 : Add description about data import from configuration files
  src/guides/v2.3/install-gde/install/cli/install-cli-subcommands-deployment.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#8969 Replace a wrong "PHPUnit Manual" source link to correct one
  src/guides/v2.3/test/integration/integration_test_execution.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#8971 Update log-locations.md
  src/cloud/project/log-locations.md
Labels: Editorial, Progress: acceptance testing

#8972 Add select release notes for 2.4.3
  src/extensions/vendor/dotdigital/release-notes.md
Labels: 2.4.3, New Topic, Progress: on hold, Progress: review, Technology Partner: dotdigital, tech-partners-contribution

#8930 New page for extend catalog rule conditions
  src/_data/toc/php-developer-guide.yml
  src/common/images/conditions-section-v2.png
  src/guides/v2.3/extension-dev-guide/extend-catalog-rule-conditions.md
  src/guides/v2.4/extension-dev-guide/extend-catalog-rule-conditions.md
Labels: New Topic, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8980 remove setup_version
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8983 Updated extension packaging guidelines with Marketplace-specific rules
  src/guides/v2.3/extension-dev-guide/package/package_module.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: acceptance testing

#8984 Config guide > Removing unnecessary code expression
  src/guides/v2.3/config-guide/prod/prod_file-sys-perms.md
Labels: Partner: Le Site, Progress: acceptance testing, Technical, partners-contribution

#8987 Removing incorrect line about 2FA admin workflows
  src/guides/v2.4/security/two-factor-authentication.md
Labels: 2.4.x, Internal Dev, Progress: approved, Technical

#8973 Change Advanced to Advanced Configuration
  src/cloud/cdn/configure-fastly-customize-cache.md
Labels: Editorial, Progress: acceptance testing

#8974 Corrected the COnfiguration section tab Name
  src/cloud/cdn/fastly-vcl-wordpress.md
Labels: Editorial, Progress: acceptance testing

#8996 MCLOUD-7934: Hardcoded magento.com in the CN name in the ssl certificate
  src/_includes/cloud/note-docker-ssl-not-private-connection.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
Labels: Editorial, Internal Dev, Progress: acceptance testing

#8997 Update db-schema.md
  src/guides/v2.4/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.4, 2.4.x, Editorial, Partner: Ampersand, Progress: acceptance testing, partners-contribution

#8990 Update best-practices.md
  src/community/best-practices.md
Labels: Editorial, Progress: acceptance testing

#8991 Update resources.md
  src/community/resources.md
Labels: Editorial, Progress: acceptance testing

#8992 Updating Slack Channel links
  .github/CONTRIBUTING.md
  src/contributor-guide/contributing.md
  src/guides/v2.3/frontend-dev-guide/translations/xlate.md
  src/guides/v2.3/graphql/release-notes.md
  src/guides/v2.3/inventory/release-notes.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.4/frontend-dev-guide/translations/xlate.md
  src/guides/v2.4/graphql/release-notes.md
Labels: 2.3.4, 2.4.x, Editorial, Progress: acceptance testing

#8999 Updated spelling in example - proxyDeffered to proxyDeferred
  src/guides/v2.3/extension-dev-guide/async-operations.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing

#9001 Correct inconsistent example of creating a foreign key constraint
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  src/guides/v2.4/extension-dev-guide/declarative-schema/db-schema.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#9004 Update url-library.md
  src/guides/v2.3/extension-dev-guide/framework/url-library.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing

#8994 Update CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: Editorial, Progress: acceptance testing, Progress: approved

#8995 Update README.md
  README.md
Labels: Editorial, Progress: acceptance testing

#9003 magento/devdocs#8989 Add information how to override a mixin
  src/guides/v2.3/javascript-dev-guide/javascript/js_mixins.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#9008 Add the "EXAMPLE NON-MATCHING TOPICS" option to the Configure message queues page
  src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#9012 Fix invalid less break point
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_css.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8940 Steps to add custom field in payment
  src/_data/toc/how-do-i.yml
  src/common/images/custom_field_payment.png
  src/guides/v2.3/howdoi/checkout/checkout_overview.md
  src/guides/v2.3/howdoi/checkout/checkout_payment_new_field.md
  src/guides/v2.4/howdoi/checkout/checkout_payment_new_field.md
Labels: 2.3.x, 2.4.x, New Topic, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#9018 Updated Extension technical information screenshot on the extension CLI Installation page
  src/common/images/marketplace-extension-technical-details.png
Labels: Editorial, Progress: approved

#9019 Incorrect instructions for "reloading ssh config"
  src/cloud/before/before-workspace-ssh.md
Labels: Progress: acceptance testing, Technical
