Repository magento/devdocs, pull requests merged in 2021-02, with the labels that each got.

#8600 GraphQL: Add gift registry search queries and CRUD operations
  src/_data/toc/graphql.yml
  src/_includes/graphql/gift-registry-search-result.md
  src/_includes/graphql/gift-registry.md
  src/guides/v2.4/graphql/mutations/create-gift-registry.md
  src/guides/v2.4/graphql/mutations/remove-gift-registry.md
  src/guides/v2.4/graphql/mutations/share-gift-registry.md
  src/guides/v2.4/graphql/mutations/update-gift-registry.md
  src/guides/v2.4/graphql/queries/gift-registry-email-search.md
  src/guides/v2.4/graphql/queries/gift-registry-id-search.md
  src/guides/v2.4/graphql/queries/gift-registry-type-search.md
  src/guides/v2.4/graphql/queries/gift-registry-types.md
  src/guides/v2.4/graphql/queries/gift-registry.md
Labels: 2.4.3, Internal Dev, New Topic, Progress: ready for review

#8594 Examples and links added
  src/_includes/cache/page-cache-overview.md
  src/guides/v2.3/frontend-dev-guide/cache_for_frontdevs.md
  src/guides/v2.3/frontend-dev-guide/themes/product-video.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8555 Update content less standards
  src/guides/v2.3/coding-standards/code-standard-less.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8605 Updating Product Recommendations Release Notes
  src/_data/mde.yml
  src/recommendations/release-notes.md
Labels: 2.4.x, Internal Dev, Progress: approved

#8606 Fix spelling of MAGENTO_CLOUD_RELATIONSHIPS
  src/cloud/project/services-rabbit.md
Labels: Editorial, Progress: approved

#8577 Cloud Patches 1.0.9 Release
  src/_data/var.yml
  src/cloud/release-notes/mcp-release-notes.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: review

#8607 MQP Release 1.0.15
  src/quality-patches/release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8578 ECE tools 2002.1.5 Release
  src/_data/var.yml
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/release-notes/ece-release-notes.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved

#8612 Correct spelling mistake: availble
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8613 Update note about supported PHP versions
  src/_includes/install/php-versions-2.3.md
Labels: 2.3.x, Internal Dev, Progress: approved, Technical

#8614 Updated docs for change to field for New Relic log files.
  src/cloud/project/new-relic.md
  src/common/images/cloud/cloud_new-relic-log-query-has-ident.png
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved, Tracking

#8621 MC-4064_correction: Fix redirects in Upgrade Compatibility Tool section
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md
  src/upgrade-compatibility-tool/developer.md
  src/upgrade-compatibility-tool/install.md
  src/upgrade-compatibility-tool/introduction.md
  src/upgrade-compatibility-tool/prerequisites.md
  src/upgrade-compatibility-tool/run.md
Labels: Editorial, Maintenance, Progress: approved

#8615 Add Elasticsearch 7.9 as an available version
  src/cloud/docker/docker-containers.md
Labels: Progress: approved

#8622 Fix typo in db-schema.md
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
Labels: Editorial, Progress: approved, Small Changes

#8609 #8106 Clarify JS init component key
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8589 MC-40328: cms_page_view_selectable layout update issue with multistore and multitheme
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, 2.4.x, Editorial, Internal Dev, Progress: approved

#8630 Small typo fix in Install Guide
  src/guides/v2.4/install-gde/prereq/mysql.md
Labels: 2.4.x, Editorial, Progress: approved

#8631 GraphQL: Add missing category attribute
  src/_includes/graphql/category-filter-input.md
Labels: 2.4.2, Internal Dev, Progress: approved, Technical

#8625 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#8633 Add data files to the BIC reference page for beta
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: 2.4.2, Internal Dev, Maintenance, Progress: approved, Technical

#8629 Added the error coverage for customerAttributeMetadata query
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
Labels: Partner: EY, Progress: approved, partners-contribution

#8623 Issue-8581- Changed the Code Snippet as requested
  src/guides/v2.3/howdoi/checkout/checkout_new_field.md
Labels: 2.3.x, 2.4.x, Partner: EY, Progress: approved, Technical, partners-contribution

#8599 Example and links added for override layout section
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8628 #6970 Add more examples for utilizing custom cache type
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#8487 Update GraphQL guidelines
  src/guides/v2.3/coding-standards/technical-vision/webapi.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8643 GraphQL: Add undocumented customizable_options attributes
  src/_includes/graphql/wishlist-item-interface.md
  src/guides/v2.4/graphql/interfaces/cart-item-interface.md
  src/guides/v2.4/graphql/interfaces/requisition-list-item-interface.md
Labels: 2.4.2, Community, Internal Dev, Progress: approved, Technical

#8642 Removing unlinked file from install guide
  src/guides/v2.4/install-gde/install/get-software.md
Labels: 2.4.x, Progress: approved, Site Improvements

#8645 Magneto 2.4.1 release note minor update
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
Labels: 2.4.1, Editorial, Internal Dev, Progress: approved

#8644 ISSUE-7374: The topics for the "Compare List" mutations have been created
  src/_data/toc/graphql.yml
  src/_includes/graphql/compare-list-output.md
  src/_includes/graphql/customer-output-24.md
  src/guides/v2.4/graphql/mutations/add-products-to-compare-list.md
  src/guides/v2.4/graphql/mutations/assign-compare-list-to-customer.md
  src/guides/v2.4/graphql/mutations/create-compare-list.md
  src/guides/v2.4/graphql/mutations/delete-compare-list.md
  src/guides/v2.4/graphql/mutations/remove-products-from-compare-list.md
  src/guides/v2.4/graphql/queries/compare-list.md
  src/guides/v2.4/graphql/queries/customer.md
Labels: 2.4.2, Community, New Topic, Partner: Atwix, Progress: approved, partners-contribution

#8647 Sync 2.4.2-develop
  src/_data/mde.yml
  src/_data/var.yml
  src/_data/whats-new.yml
  src/_includes/cache/page-cache-overview.md
  src/_includes/install/php-versions-2.3.md
  src/cloud/env/variables-build.md
  src/cloud/env/variables-deploy.md
  src/cloud/env/variables-global.md
  src/cloud/project/magento-env-yaml.md
  src/cloud/project/new-relic.md
  src/cloud/project/services-rabbit.md
  src/cloud/release-notes/ece-release-notes.md
  src/cloud/release-notes/mcp-release-notes.md
  src/common/images/cloud/cloud_new-relic-log-query-has-ident.png
  src/guides/v2.3/coding-standards/code-standard-less.md
  src/guides/v2.3/coding-standards/technical-vision/webapi.md
  src/guides/v2.3/config-guide/prod/config-reference-envphp.md
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
  src/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.md
  src/guides/v2.3/frontend-dev-guide/cache_for_frontdevs.md
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/frontend-dev-guide/themes/product-video.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
  src/guides/v2.3/graphql/queries/custom-attribute-metadata.md
  src/guides/v2.3/howdoi/checkout/checkout_new_field.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_init.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery.md
  src/guides/v2.4/install-gde/install/get-software.md
  src/guides/v2.4/install-gde/prereq/mysql.md
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
  src/quality-patches/release-notes.md
  src/recommendations/release-notes.md
  src/upgrade-compatibility-tool/developer.md
  src/upgrade-compatibility-tool/install.md
  src/upgrade-compatibility-tool/introduction.md
  src/upgrade-compatibility-tool/prerequisites.md
  src/upgrade-compatibility-tool/run.md
Labels: 2.4.2, Maintenance, Progress: approved

#8611 2 4 2 release notes 0126
  src/guides/v2.4/release-notes/b2b-release-notes.md
  src/guides/v2.4/release-notes/commerce-2-4-2.md
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.2, Internal Dev, Major Update, Progress: approved

#8646 GraphQL: Comparison list coverage
  src/_data/toc/graphql.yml
  src/_includes/graphql/compare-list-output.md
  src/_includes/graphql/customer-output-24.md
  src/guides/v2.4/graphql/mutations/add-products-to-compare-list.md
  src/guides/v2.4/graphql/mutations/assign-compare-list-to-customer.md
  src/guides/v2.4/graphql/mutations/create-compare-list.md
  src/guides/v2.4/graphql/mutations/delete-compare-list.md
  src/guides/v2.4/graphql/mutations/remove-products-from-compare-list.md
  src/guides/v2.4/graphql/queries/compare-list.md
  src/guides/v2.4/graphql/queries/customer.md
  src/guides/v2.4/release-notes/commerce-2-4-2.md
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.2, Community, New Topic, Progress: approved

#8653 MC-40815: Improve diagrams in the install Upgrade Compatibility Tool page
  src/upgrade-compatibility-tool/img/audience-uct-v2.png
  src/upgrade-compatibility-tool/img/mvp-diagram-v3.png
  src/upgrade-compatibility-tool/img/upgrade-compatibility-tool-development.png
  src/upgrade-compatibility-tool/install.md
Labels: Editorial, Internal Dev, Progress: approved

#8654 Update PWA Studio release note items
  src/guides/v2.4/release-notes/commerce-2-4-2.md
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.x, Internal Dev

#8657 Fix 'rake whatsnew since'
  Rakefile
Labels: Maintenance, Progress: approved

#8655 Update whatsnew for Q1 2021 release
  src/_data/whats-new.yml
Labels: 2.4.2, Maintenance, Progress: approved

#8661 2.4.2 data update: PHP extensions, licenses, magento CLI
  src/_data/codebase/v2_4/cloud/composer_lock.json
  src/_data/codebase/v2_4/open-source/bin-magento.json
  src/_data/codebase/v2_4/open-source/composer_lock.json
Labels: 2.4.2, Major Update, Progress: approved

#8660 Update BIC reference
  src/_includes/backward-incompatible-changes/commerce/2.4.0-2.4.1-develop.html
  src/_includes/backward-incompatible-changes/commerce/2.4.1-2.4.2-develop.html
  src/_includes/backward-incompatible-changes/commerce/2.4.1-2.4.2.md
  src/_includes/backward-incompatible-changes/open-source/2.3.5-2.3.6.html
  src/_includes/backward-incompatible-changes/open-source/2.4.0-2.4.1-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.4.0-2.4.1.html
  src/_includes/backward-incompatible-changes/open-source/2.4.1-2.4.2-develop.html
  src/_includes/backward-incompatible-changes/open-source/2.4.1-2.4.2.md
  src/guides/v2.4/release-notes/backward-incompatible-changes/reference.md
Labels: 2.4.2, Automation, Internal Dev, Major Update, Progress: approved

#8595 Examples added for cache type
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
Labels: 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8662 GraphQL: Update list of cached/non-cached queries
  src/guides/v2.4/graphql/caching.md
Labels: 2.4.x, Community, Internal Dev, Progress: approved, Technical

#8667 Magento 2.4.2 release note minor update 0209
  src/guides/v2.4/release-notes/commerce-2-4-2.md
  src/guides/v2.4/release-notes/open-source-2-4-2.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#8668 2.4.2 update: Packages and bin/magento references for Commerce
  src/_data/codebase/v2_4/commerce/bin-magento.json
  src/_data/codebase/v2_4/commerce/composer_lock.json
Labels: 2.4.2, Major Update, Progress: approved

#8639 Marketing review updates:
  src/marketplace/sellers/marketing-review-guidelines.md
Labels: Internal Dev, Progress: approved

#8648 magento/devdocs#: added example of using the modal widget
  src/guides/v2.3/javascript-dev-guide/widgets/widget_modal.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#8673 Update Page Builder TOC
  src/_data/toc/page-builder.yml
  src/_data/whats-new.yml
  src/guides/v2.3/page-builder/index.md
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved

#8677 Update audience diagram for install page in the upgrade compatibility tool section
  src/upgrade-compatibility-tool/img/audience-uct-v3.png
  src/upgrade-compatibility-tool/install.md
Labels: Editorial, Progress: review

#8601 ui-columncontrols-clarification-7730
  src/guides/v2.3/ui_comp_guide/components/ui-columnscontrols.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: Ziffity, Progress: approved, partners-contribution

#8681 GraphQL: Preview-Version queries
  src/guides/v2.4/graphql/caching.md
Labels: 2.4.3, Community, Internal Dev, Progress: approved, Technical

#8683 GraphQL: Remove reference to backed-out data types
  src/guides/v2.4/release-notes/commerce-2-4-2.md
Labels: 2.4.2, Editorial, Internal Dev, Progress: approved

#8540 [WIP] GraphQL: Add type attribute to CustomizableDateValue
  src/guides/v2.4/graphql/interfaces/customizable-option-interface.md
Labels: 2.4.3, Community, Internal Dev, Progress: approved, Technical

#8691 Update plugins.md
  src/guides/v2.3/extension-dev-guide/plugins.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8689 Add upgrade command for deployment pipeline
  src/_includes/config/split-deploy/example_build-sync.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8684 Enhance readability of CLI references
  src/_includes/reference/cli-template.md
Labels: 2.x, Editorial, Progress: approved

#8692 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#8693 3 ways to set the template for a block
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8680 Examples added and some improvements
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8618 Update indexer-batch.md regarding last code changes
  src/guides/v2.4/extension-dev-guide/indexer-batch.md
Labels: 2.4.3, Internal Dev, Progress: approved, Technical

#8694 change layout file order
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
Labels: Partner: Ziffity, Progress: approved, partners-contribution

#8699 Changed all instances of OrangeCo and OrangeCompany
  src/guides/v2.3/ext-best-practices/tutorials/custom-import-entity.md
  src/guides/v2.3/ext-best-practices/tutorials/custom-widget.md
  src/guides/v2.3/extension-dev-guide/build/di-xml-file.md
  src/guides/v2.3/extension-dev-guide/routing.md
  src/guides/v2.3/extension-dev-guide/view-models.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-overview.md
  src/guides/v2.3/frontend-dev-guide/css-topics/css-practice.md
  src/guides/v2.3/frontend-dev-guide/layouts/layout-practice.md
  src/guides/v2.3/frontend-dev-guide/layouts/xml-manage.md
  src/guides/v2.3/frontend-dev-guide/responsive-web-design/rwd_practice.md
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
  src/guides/v2.3/frontend-dev-guide/templates/template-override.md
  src/guides/v2.3/frontend-dev-guide/templates/template-sample.md
  src/guides/v2.3/frontend-dev-guide/templates/template-walkthrough.md
  src/guides/v2.3/frontend-dev-guide/translations/translate_practice.md
  src/guides/v2.3/graphql/develop/extend-existing-schema.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_mixins.md
  src/guides/v2.3/javascript-dev-guide/javascript/js_practice.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_uilayout_concept.md
  src/guides/v2.4/extension-dev-guide/routing.md
Labels: 2.3.x, 2.4.x, Partner: Vaimo, Progress: approved, Technical, partners-contribution

#8700 GraphQL: Backport statement about the header
  src/guides/v2.4/graphql/caching.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8701 GraphQL: setGiftOptionsOnCart is Commerce only
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/set-gift-options.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved

#8702 PB docs update with better directory naming and organization
  src/_data/toc/page-builder.yml
  src/guides/v2.3/page-builder/index.md
  src/guides/v2.4/page-builder/index.md
Labels: 2.4.2, 2.4.x, Internal Dev, Major Update, Progress: approved

#8685 Additional product layout examples added
  src/guides/v2.3/frontend-dev-guide/layouts/product-layouts.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#8706 MQP Release 1.0.16
  src/quality-patches/release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8686 Examples added on layout extend page
  src/guides/v2.3/frontend-dev-guide/layouts/layout-extend.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8679 magento/devdocs#: added example of using dropdown widget
  src/common/images/widget/dropdown-widget-result.jpg
  src/common/images/widget/dropdown-widget-result.png
  src/guides/v2.3/javascript-dev-guide/widgets/widget_dropdown.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: approved, Technical, partners-contribution

#8710 Change escaping from block to escaper in HtmlContent component page
  src/guides/v2.3/ui_comp_guide/components/ui-htmlcontent.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes, Technical

#8687 Static files fall back docs clarification 2609
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: approved, Small Changes, partners-contribution

#8714 TOC and link changes for updated Page Builder directory and file names
  Docfile.yml
  src/_data/toc/page-builder.yml
  src/_data/whats-new.yml
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
Labels: 2.4.x, Internal Dev, Progress: approved

#8712 Delete empty topic
  src/guides/v2.3/config-guide/prod/config-reference-parent.md
  src/guides/v2.4/config-guide/prod/config-reference-parent.md
Labels: 2.3.x, 2.4.x, Progress: approved, Site Improvements

#8552 Cloud: update migrate files section
  src/cloud/live/stage-prod-migrate.md
Labels: 2.x, Internal Dev, Progress: approved, Technical

#8720 Fix Markdown
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
Labels: Editorial, Progress: approved, Small Changes

#8721 Removed outdated Cloud version notes
  src/cloud/project/magento-app-workers.md
Labels: Editorial, Progress: approved

#8717 Fixed incorrect path.
  src/guides/v2.3/config-guide/deployment/pipeline/technical-details.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8716 Fixed malformed break tags
  src/_includes/config/es-elasticsearch-magento-24.md
Labels: 2.4.x, Editorial, Progress: approved

#8719 Fix an incorrect file reference
  src/guides/v2.3/howdoi/customize-modifier-class.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8708 magento/devdocs#: added magnifier widget file location
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: Editorial, Partner: Atwix, Progress: approved, Small Changes, partners-contribution

#8722 Removed unneeded asterisks
  src/_includes/webapi/services23.md
  src/_includes/webapi/services24.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8723 Small changes
  src/_includes/config/es-elasticsearch-magento-24.md
  src/_includes/webapi/services23.md
  src/_includes/webapi/services24.md
  src/cloud/project/magento-app-workers.md
  src/guides/v2.3/config-guide/deployment/pipeline/technical-details.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
  src/guides/v2.3/howdoi/customize-modifier-class.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery_mg.md
Labels: Progress: approved

#8724 Update Cloud CLI reference
  src/_data/codebase/cloud/magento-cloud.json
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8725 Sync 2.3.7 -develop
  Docfile.yml
  src/_data/codebase/cloud/magento-cloud.json
  src/_data/toc/page-builder.yml
  src/_data/whats-new.yml
  src/_includes/config/es-elasticsearch-magento-24.md
  src/_includes/webapi/services23.md
  src/_includes/webapi/services24.md
  src/cloud/live/stage-prod-migrate.md
  src/cloud/project/magento-app-workers.md
  src/guides/v2.3/config-guide/deployment/pipeline/technical-details.md
  src/guides/v2.3/config-guide/prod/config-reference-parent.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-inherit.md
  src/guides/v2.3/howdoi/customize-modifier-class.md
  src/guides/v2.3/javascript-dev-guide/widgets/widget_gallery_mg.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
  src/guides/v2.4/config-guide/prod/config-reference-parent.md
Labels: 2.3.7, Maintenance, Progress: approved

#8519 GraphQL: Mutation for adding wishlist items to the cart
  src/_data/toc/graphql.yml
  src/_includes/graphql/wishlist-item-interface.md
  src/guides/v2.4/graphql/mutations/add-wishlist-items-to-cart.md
Labels: 2.4.3, Community, Internal Dev, New Topic, Progress: approved

#8727 Updated Page Builder TOC
  src/_data/toc/page-builder.yml
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved

#8730 Update REST links for 2.4.2
  src/_data/toc/rest-api.yml
Labels: 2.4.2, Internal Dev, Maintenance, Progress: approved

#8732 Final Page Builder TOC and removal of
  Docfile.yml
  src/_data/toc/page-builder.yml
  src/_data/toc/rest-api.yml
  src/_data/whats-new.yml
  src/guides/v2.3/release-notes/ReleaseNotes2.3.2Commerce.md
  src/guides/v2.3/release-notes/release-notes-2-3-5-commerce.md
Labels: 2.4.x, Internal Dev, Progress: approved, Site Improvements

#8713 Update tech-vision.md
  src/guides/v2.3/architecture/archi_perspectives/tech-vision.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8598 GraphQL: Dynamic block support
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/queries/dynamic-blocks.md
Labels: 2.4.3, Community, Internal Dev, New Topic, Progress: approved

#8734 Update link for "sign yourself up" into Magento Community Engineering Slack
  .github/CONTRIBUTING.md
  src/cloud/docker/docker-development.md
  src/community/resources/resources.md
  src/contributor-guide/contributing.md
  src/guides/v2.3/frontend-dev-guide/translations/xlate.md
  src/guides/v2.3/graphql/release-notes.md
  src/guides/v2.3/inventory/release-notes.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.4/frontend-dev-guide/translations/xlate.md
  src/guides/v2.4/graphql/release-notes.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#8663 EQPS-908: Devdocs for EQP MFTF Tests
  src/_data/toc/marketplace-sellers.yml
  src/marketplace/sellers/mftf-magento.md
  src/marketplace/sellers/mftf-vendor.md
  src/marketplace/sellers/technical-review-guidelines.md
Labels: Internal Dev, New Topic, Progress: approved, Waiting for Response

#8735 MRG: Updated content for the ConfigurableProduct module
  src/_data/codebase/v2_4/mrg/ce/ConfigurableProduct.yml
Labels: 2.4.x, Internal Dev, Major Update, Progress: approved

#8736 Whats New Update for Feb 24
  src/_data/toc/page-builder.yml
  src/_data/whats-new.yml
Labels: 2.4.x, Internal Dev, Progress: approved

#8737 Remove rake task for page-builder migration repo
  rakelib/update.rake
Labels: Internal Dev, Maintenance, Progress: approved

#8739 Update gs-web-api-request.md
  src/guides/v2.3/get-started/gs-web-api-request.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: DEG, Progress: approved, partners-contribution

#8741 TOC changes to match one more logical update to PB org changes
  src/_data/toc/page-builder.yml
  src/_data/whats-new.yml
Labels: 2.4.x, Internal Dev, Progress: approved

#8743 Sync 2.3.7 -develop
  .github/CONTRIBUTING.md
  rakelib/update.rake
  src/_data/codebase/v2_4/mrg/ce/ConfigurableProduct.yml
  src/_data/toc/page-builder.yml
  src/_data/whats-new.yml
  src/cloud/docker/docker-development.md
  src/community/resources/resources.md
  src/contributor-guide/contributing.md
  src/guides/v2.3/frontend-dev-guide/translations/xlate.md
  src/guides/v2.3/get-started/gs-web-api-request.md
  src/guides/v2.3/graphql/release-notes.md
  src/guides/v2.3/inventory/release-notes.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.md
  src/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.md
  src/guides/v2.4/frontend-dev-guide/translations/xlate.md
  src/guides/v2.4/graphql/release-notes.md
Labels: Internal Dev, Maintenance, Progress: approved

#8738 EQPS-908: Devdocs for EQP MFTF Tests - Editable branch
  src/_data/toc/marketplace-sellers.yml
  src/marketplace/sellers/mftf-magento.md
  src/marketplace/sellers/mftf-vendor.md
  src/marketplace/sellers/technical-review-guidelines.md
Labels: New Topic, Progress: approved

#8746 Break symlink
  src/guides/v2.4/config-guide/prod/config-reference-envphp.md
Labels: 2.4.3, Maintenance, Progress: approved

#8671 Adding link to user guide about cold start
  src/recommendations/implementation.md
Labels: 2.4.x, Internal Dev, Progress: approved

#8748 Edits to EQP MFTF topics
  src/marketplace/sellers/mftf-magento.md
  src/marketplace/sellers/mftf-vendor.md
Labels: Editorial, Internal Dev, Progress: approved
