Repository magento/devdocs, pull requests merged in 2021-08, with the labels that each got.

#9071 Mask cart_id in GraphQL request
  src/guides/v2.3/graphql/tutorials/checkout/checkout-shipping-address.md
Labels: 2.4.x, Editorial, Progress: approved

#9070 Update search-endpoint.md
  src/guides/v2.3/rest/search-endpoint.md
Labels: Editorial, partners-contribution, Progress: acceptance testing, Partner: Netz98

#9077 Fixed typo issue
  src/guides/v2.3/javascript-dev-guide/javascript/requirejs.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9079 Don't recommend overriding _isAllowed
  src/guides/v2.3/ext-best-practices/tutorials/create-access-control-list-rule.md
Labels: 2.3.x, Technical, Progress: acceptance testing, 2.4.x

#9085 Fix link by removing reference to local IP address
  src/guides/v2.4/release-notes/2-4-2-p2.md
Labels: Editorial, Progress: acceptance testing, 2.4.x

#9088 Corrected links containing 127.0.0.1
  src/_data/whats-new.yml
  src/guides/v2.3/release-notes/2-3-7-p1.md
  src/guides/v2.4/release-notes/2-4-2-p2.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Vaimo, Progress: approved, Progress: acceptance testing, 2.4.x

#9075 Updated routes.md
  src/cloud/project/routes.md
Labels: Editorial, Progress: acceptance testing

#9084 Add description for issue 28239 fix
  src/guides/v2.4/release-notes/open-source-2-4-3.md
Labels: Editorial, Progress: approved, 2.4.3

#9100 Fix broken link in the Two-Factor Authentication topic
  src/guides/v2.4/security/two-factor-authentication.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#9105 ngx_http_image_filter_module +webp -svg -ico
  src/guides/v2.4/config-guide/remote-storage/config-remote-storage-image-resize.md
Labels: Editorial, Progress: approved, 2.4.x
