Repository magento/devdocs, pull requests merged in 2021-03, with the labels that each got.

#8676 Magento admin product video option added
  src/guides/v2.3/frontend-dev-guide/images/config-catalog-catalog-product-video.png
  src/guides/v2.3/frontend-dev-guide/themes/product-video.md
  src/guides/v2.4/frontend-dev-guide/images/config-catalog-catalog-product-video.png
Labels: 2.3.x, 2.4.x, Major Update, Partner: Ziffity, Progress: approved, partners-contribution

#8752 Fixed fastly image optimization link
  src/cloud/cdn/cloud-fastly.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: approved, Small Changes

#8753 Magento 2.3.6 and 2.4.0 release note update
  src/guides/v2.3/release-notes/commerce-2-3-6.md
  src/guides/v2.3/release-notes/open-source-2-3-6.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-commerce.md
  src/guides/v2.4/release-notes/release-notes-2-4-0-open-source.md
Labels: 2.3.6, 2.4.0, Editorial, Internal Dev, Progress: approved

#8754 Whatsnew for 03/01/21
  src/_data/whats-new.yml
Labels: Maintenance, Progress: approved

#8610 Issue-8608- Added a disclaimer regarding custom domains of Starter Projects
  src/cloud/cdn/configure-fastly.md
Labels: Community, Editorial, Progress: approved, Small Changes

#8749 GraphQL: Add mutations for managing gift registrants
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/add-gift-registry-registrants.md
  src/guides/v2.4/graphql/mutations/create-gift-registry.md
  src/guides/v2.4/graphql/mutations/remove-gift-registry-registrants.md
  src/guides/v2.4/graphql/mutations/update-gift-registry-registrants.md
Labels: Progress: changes requested

#8757 GraphQL: Add mutations to update/remove gift registry items
  src/_data/toc/graphql.yml
  src/guides/v2.4/graphql/mutations/remove-gift-registry-items.md
  src/guides/v2.4/graphql/mutations/update-gift-registry-items.md
Labels: 2.4.3, Community, Internal Dev, New Topic, Progress: ready for review

#8747 MC-40784 Update sys reqs
  src/_includes/config/es-version-23.md
  src/_includes/install/php-versions-2.3.md
  src/guides/v2.3/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.3/config-guide/elasticsearch/es-downgrade.md
  src/guides/v2.3/config-guide/varnish/config-varnish-install.md
  src/guides/v2.3/install-gde/system-requirements.md
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
Labels: 2.3.7, Editorial, Internal Dev, Progress: approved

#8745 remove database connection line
  src/guides/v2.3/config-guide/deployment/pipeline/build-system.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: approved, partners-contribution

#8709 Explain mixins
  src/guides/v2.3/coding-standards/code-standard-less.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8744 Added an MDB variable for Page Builder
  src/_data/var.yml
Labels: 2.4.x, Internal Dev, Progress: approved

#8728 Improve Docker documentation
  src/_data/toc/cloud-guide.yml
  src/_data/whats-new.yml
  src/_includes/cloud/cloud-docker-config-generator-cmds.md
  src/_includes/cloud/note-docker-config-reference-link.md
  src/cloud/cdn/fastly-vcl-allowlist.md
  src/cloud/docker/docker-config-sources.md
  src/cloud/docker/docker-config.md
  src/cloud/docker/docker-containers-service.md
  src/cloud/docker/docker-containers.md
  src/cloud/docker/docker-development-debug.md
  src/cloud/docker/docker-development.md
  src/cloud/docker/docker-installation.md
  src/cloud/docker/docker-launch.md
  src/cloud/docker/docker-mode-developer.md
  src/cloud/docker/docker-mode-production.md
  src/cloud/docker/docker-quick-reference.md
  src/cloud/docker/docker-split-db.md
  src/cloud/docker/docker-syncing-data.md
  src/cloud/docker/docker-troubleshooting.md
  src/cloud/docker/docker-upgrade.md
  src/cloud/project/ece-tools-update.md
  src/cloud/release-notes/cloud-release-archive.md
  src/cloud/release-notes/mcd-release-notes.md
Labels: Progress: approved

#8755 Removed duplicated section
  src/marketplace/sellers/mftf-vendor.md
Labels: Internal Dev, Progress: approved

#8763 compensations command changes
  src/guides/v2.3/inventory/inventory-cli-reference.md
Labels: 2.3.x, 2.4.x, Progress: approved, Technical

#8778 [Imported] Fix grammar in message-queues.md
  src/guides/v2.3/rest/modules/catalog-pricing.md
Labels: Editorial, Internal Dev, Progress: approved, Small Changes

#8771 privatelink updates needed - Clarifications
  src/_data/features.yml
Labels: Internal Dev, Progress: approved

#8762 Update index.php location
  src/guides/v2.4/config-guide/bootstrap/magento-bootstrap.md
Labels: 2.4.x, Progress: approved, Technical

#8697 [Imported] Add some info make docs related deployment more clarify
  src/_includes/config/split-deploy/example_build-sync.md
  src/guides/v2.3/config-guide/deployment/pipeline/build-system.md
  src/guides/v2.3/config-guide/deployment/pipeline/technical-details.md
  src/guides/v2.3/frontend-dev-guide/cache_for_frontdevs.md
  src/guides/v2.3/frontend-dev-guide/themes/theme-create.md
  src/guides/v2.3/howdoi/php/php_clear-dirs.md
  src/guides/v2.3/install-gde/trouble/tshoot_sample-data.md
  src/guides/v2.3/install-gde/trouble/tshoot_wrong-mysql.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8707 [Imported] magento/devdocs#: added example of using DropdownDialog widget
  src/guides/v2.3/javascript-dev-guide/widgets/widget_dialog.md
Labels: 2.3.x, 2.4.x, Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#8742 [Imported] add component example
  src/guides/v2.3/coding-standards/code-standard-jquery-widgets.md
Labels: 2.3.x, 2.4.x, Major Update, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8776 Wrong config.xml contents
  src/guides/v2.3/ext-best-practices/tutorials/dynamic-row-system-config.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#8781 New topic - email layout handle is added
  src/_data/toc/frontend-developer-guide.yml
  src/guides/v2.3/frontend-dev-guide/images/email-order-items-render.png
  src/guides/v2.3/frontend-dev-guide/templates/template-email-layout-handle.md
  src/guides/v2.4/frontend-dev-guide/images/email-order-items-render.png
  src/guides/v2.4/frontend-dev-guide/templates/template-email-layout-handle.md
Labels: 2.3.x, 2.4.x, New Topic, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8784 Set the store email from Magento Admin
  src/common/images/set_store_email.png
  src/guides/v2.3/frontend-dev-guide/templates/template-email.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8786 Update config-reference-systemxml.md
  src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing

#8798 Update php-settings.md
  src/guides/v2.4/install-gde/prereq/php-settings.md
Labels: 2.4.x, Editorial, Internal Dev, Progress: acceptance testing

#8766 add example of before-and-after-attributes
  src/guides/v2.3/frontend-dev-guide/layouts/xml-instructions.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8774 Add screenshot of clear cache and set logo from admin
  src/common/images/clear_cache.png
  src/common/images/logo.png
  src/guides/v2.3/frontend-dev-guide/themes/theme-apply.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#8811 Add UCT "Troubleshooting" section
  src/upgrade-compatibility-tool/run.md
Labels: Major Update, Progress: ready for review

#8812 Remove "Dedicated IP address"
  src/cloud/project/sendgrid.md
Labels: 2.x, Editorial, Internal Dev, Progress: approved

#8813 MQP Release 1.0.18
  src/cloud/project/sendgrid.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8765 Added new option to static-content:deploy command
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-static-view.md
Labels: 2.4.x, Progress: approved, Technical

#8822 Updated the common log locations
  src/cloud/project/log-locations.md
Labels: Editorial, Partner: Ziffity, Progress: acceptance testing, Small Changes, partners-contribution

#8827 Corrected typos on InsertForm component page
  src/guides/v2.3/ui_comp_guide/components/ui-insertform.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Small Changes

#8830 Fix typo in various page
  src/guides/v2.3/ui_comp_guide/components/ui-colorpicker.md
  src/guides/v2.3/ui_comp_guide/components/ui-massactions.md
  src/guides/v2.3/ui_comp_guide/concepts/ui_comp_template_literals.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing

#8831 Fix/typo services-mysql.html
  src/cloud/project/services-mysql.md
Labels: Editorial, Partner: Vaimo, Progress: acceptance testing, partners-contribution

#8829 EQPS-1001: EQP MFTF Update Devdocs
  src/marketplace/sellers/mftf-magento.md
  src/marketplace/sellers/mftf-vendor.md
Labels: Editorial, Internal Dev, Progress: acceptance testing

#8833 Adding a space to separate words in service contract design patterns …
  src/guides/v2.3/extension-dev-guide/service-contracts/design-patterns.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing, Small Changes

#8834 Update content cli deploy less
  src/guides/v2.3/config-guide/cli/config-cli-subcommands-less-sass.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing

#8846 Update release-notes.md
  src/quality-patches/release-notes.md
Labels: 2.x, Internal Dev, Major Update, Progress: approved

#8828 Add consumers-wait-for-messages warning
  src/_includes/config/consumers.md
  src/guides/v2.4/extension-dev-guide/message-queues/config-mq.md
Labels: Editorial, Partner: Comwrap, Progress: acceptance testing, Small Changes, partners-contribution

#8840 Minor improvements - added examples on topics
  src/guides/v2.3/ui_comp_guide/bk-ui_comps.md
Labels: 2.3.x, 2.4.x, Partner: Ziffity, Progress: approved, Technical, partners-contribution

#8841 Update callout about Pro routing
  src/cloud/project/project-multi-sites.md
Labels: 2.x, Editorial, Partner: Vaimo, Progress: acceptance testing, partners-contribution

#8842 Update link in Cloud Docs
  src/cloud/live/stage-prod-migrate.md
Labels: 2.x, Partner: Vaimo, Progress: acceptance testing, Technical, partners-contribution

#8843 Improve build and deploy env definitions
  src/_includes/cloud/scd-configuration-management.md
  src/cloud/live/sens-data-over.md
  src/cloud/project/magento-env-yaml.md
Labels: 2.x, Partner: Vaimo, Progress: acceptance testing, Technical, partners-contribution
