Repository magento/devdocs, pull requests merged in 2021-09, with the labels that each got.

#9121 Remove the duplicate field from the help page for other configuration paths
  src/guides/v2.3/config-guide/prod/config-reference-most.md
  src/guides/v2.4/config-guide/prod/config-reference-most.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Atwix, Progress: approved, 2.4.x

#9120 Fix outdated CLI command for disabling reCaptcha topic ( M2.4 only)
  src/guides/v2.4/security/google-recaptcha.md
Labels: Technical, partners-contribution, Partner: Atwix, Progress: approved, 2.4.x

#9124 Adjust code formatting for better readability
  src/_videos/fundamentals/create-a-new-module.md
Labels: Editorial, partners-contribution, Progress: acceptance testing, Partner: SNOW.DOG

#9119 Update Plugin Limitations Section
  src/guides/v2.3/extension-dev-guide/plugins.md
Labels: 2.3.x, Technical, partners-contribution, Progress: acceptance testing, 2.4.x, Partner: Fisheye

#9126 Added a warning about custom SQL queries using Magento data adapter n…
  src/guides/v2.4/ext-best-practices/extension-coding/security-performance-data-bp.md
Labels: Editorial, partners-contribution, Progress: acceptance testing, 2.4.x, Partner: MRM Commerce

#9127 Fix code block language identifier
  src/guides/v2.4/security/security-txt.md
Labels: Editorial, partners-contribution, Partner: Vaimo, Progress: acceptance testing, 2.4.x

#9128 Edit styles on the Prerequisites page
  src/guides/v2.3/install-gde/prereq/prereq-overview.md
  src/guides/v2.4/install-gde/prereq/prereq-overview.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#9122 Update migration-overview-how.md
  src/guides/v2.3/migration/migration-overview-how.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9129 Add correct link to the Quality Patches Tool page
  src/guides/v2.3/comp-mgr/patching/mqp.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Atwix, Progress: approved, Progress: acceptance testing, 2.4.x

#9130 Code demarcation standard > Fix syntax
  src/guides/v2.3/coding-standards/code-standard-demarcation.md
Labels: Editorial, 2.3.x, partners-contribution, Progress: acceptance testing, 2.4.x, Partner: Le Site

#9135 Edit broken links for the 2.4 Release Notes block
  src/guides/v2.4/release-notes/commerce-2-4-1.md
  src/guides/v2.4/release-notes/commerce-2-4-3.md
  src/guides/v2.4/release-notes/open-source-2-4-1.md
  src/guides/v2.4/release-notes/open-source-2-4-3.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.1, 2.4.3

#9138 Fixed typo and magento version update
  src/guides/v2.4/security/google-recaptcha.md
Labels: Editorial, 2.3.x, partners-contribution, Progress: approved, Progress: acceptance testing, Partner: Ziffity, 2.4.x

#9137 Updated cli command based on composer2 to check available magento ver…
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
Labels: Technical, partners-contribution, Progress: acceptance testing, Partner: Ziffity, 2.4.x

#9139 Update use-multiple-varnish-cache.md
  src/guides/v2.3/config-guide/varnish/use-multiple-varnish-cache.md
Labels: 2.3.x, Technical, Progress: acceptance testing, 2.4.x

#9145 Update two-level-cache.md
  src/guides/v2.4/config-guide/cache/two-level-cache.md
Labels: Editorial, partners-contribution, Progress: approved, 2.4.x, Partner: Netz98

#9160 Update users.md
  src/live-search/release-notes.md
Labels: Internal Dev, Technical, Progress: approved, 2.4.x

#9142 33160: Remove extra part of information
  src/guides/v2.3/frontend-dev-guide/translations/theme_dictionary.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9147 Fixed page redirect issue
  src/guides/v2.4/install-gde/system-requirements.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Ziffity, 2.4.x

#9150 Suggested update to sentence mistake
  src/guides/v2.3/comp-mgr/upgrade-best-practices.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9151 Updates code snippet for fileuploader component to match the new best practices
  src/guides/v2.3/ui_comp_guide/components/ui-fileuploader.md
Labels: 2.3.x, Technical, Progress: acceptance testing, 2.4.x

#9153 Override all conflicting custom values with the expected Magento default values for command line upgrade
  src/guides/v2.3/comp-mgr/cli/cli-upgrade.md
  src/guides/v2.4/comp-mgr/cli/cli-upgrade.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Krish TechnoLabs, Progress: approved, Progress: acceptance testing, 2.4.x

#9162 updating terminology
  src/recommendations/verify.md
Labels: Editorial, Internal Dev, Progress: acceptance testing

#9148 Fix small typo in example
  src/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.md
Labels: 2.3.x, Technical, Progress: acceptance testing, 2.4.x
