Repository magento/devdocs, pull requests merged in 2021-07, with the labels that each got.

#9031 MQP Release 1.0.26
  src/guides/v2.3/rest/bulk-endpoints.md
Labels: 2.3.x, 2.4.x, Major Update, Progress: approved

#9033 Update store-config.md
  src/_includes/graphql/store-config.md
Labels: 2.4.x, Internal Dev, Progress: approved, Technical

#9038 Update nginx.md
  src/guides/v2.3/install-gde/prereq/nginx.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: acceptance testing

#9045 Update system-requirements-table.md
  src/_includes/install/system-requirements-table.md
Labels: 2.3.4, 2.4.x, Editorial, Progress: acceptance testing, Progress: approved

#9050 magento/devdocs#9049 fixing missing a comma in the example
  src/guides/v2.3/javascript-dev-guide/widgets/widget_alert.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#9051 magento/devdocs#9037 Fixing example with the block inside page layout…
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#9056 Add valid link to the "Asynchronous web endpoints" page
  src/guides/v2.3/config-guide/elasticsearch/es-config-stopwords.md
Labels: 2.3.x, 2.4.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#9040 Added a new page for Custom Attributes tutorials
  src/_data/main-nav.yml
  src/_data/toc/how-do-i.yml
  src/common/images/custom-attributes/customer-text-form.png
  src/common/images/custom-attributes/customer-text-grid.png
  src/guides/v2.3/howdoi/custom-attributes/introduction.md
  src/guides/v2.3/howdoi/custom-attributes/text-field.md
  src/guides/v2.4/howdoi/custom-attributes/introduction.md
  src/guides/v2.4/howdoi/custom-attributes/text-field.md
Labels: New Topic, Progress: acceptance testing

#9043 Fix the instruction for creating the mixins for payment and shipping steps
  src/guides/v2.3/howdoi/checkout/checkout_new_step.md
Labels: 2.3.x, 2.4.x, Progress: acceptance testing, Technical

#9060 magento/devdocs#9059 Fixing path in the new layout example
  src/guides/v2.3/frontend-dev-guide/layouts/layout-create.md
Labels: Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution

#9066 Fixing MD syntax > Composer page
  src/guides/v2.3/comp-mgr/patching/composer.md
Labels: Editorial, Partner: Le Site, Progress: approved, partners-contribution

#9065 Minor fix under [nginx configs] link fixing #9064
  src/cloud/docker/docker-containers-service.md
Labels: 2.x, Editorial, Partner: Onetree, Progress: acceptance testing, partners-contribution

#9068 Fix and improve examples for Fastly API usage
  src/cloud/cdn/trouble-fastly.md
Labels: 2.x, Partner: Atwix, Progress: acceptance testing, Technical, partners-contribution
