Repository magento/devdocs, pull requests merged in 2022-05, with the labels that each got.

#9428 Add message that grid snapshots are not automated.
  src/cloud/project/project-webint-snap.md
Labels: Progress: acceptance testing

#9436 Update project-patch.md
  src/_data/core-releases.json
Labels: Editorial, Internal Dev, Progress: acceptance testing

#9444 Updated XDebug Information for Pro Staging & Production
  src/cloud/howtos/debug.md
Labels: Technical, Progress: approved
