Repository magento/devdocs, pull requests merged in 2022-09, with the labels that each got.

#9512 Update README.md
  README.md
Labels: Editorial, 2.x, Progress: review

#9518 Fix grammar
  src/guides/v2.4/graphql/caching.md
Labels: Editorial, Progress: approved, 2.4.x

#9505 Add examples with OS to cloud documentations
  src/cloud/docker/docker-installation.md
  src/cloud/env/variables-deploy.md
Labels: Technical, partners-contribution, Partner: Atwix, Progress: approved, 2.4.6
