Repository magento/devdocs, pull requests merged in 2022-02, with the labels that each got.

#9341 Update config-reference-config
  src/guides/v2.3/config-guide/prod/config-reference-configphp.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9347 Fix typo
  src/guides/v2.4/security/two-factor-authentication.md
Labels: Editorial, Progress: acceptance testing, 2.4.x

#9344 Change extensions list to a shorter version
  src/_includes/install/php-ext-commerce.md
  src/_includes/install/php-extensions-template.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9342 Fix path for "Send Emails To" config
  src/guides/v2.3/config-guide/prod/config-reference-most.md
  src/guides/v2.4/config-guide/prod/config-reference-most.md
Labels: Editorial, 2.3.x, Progress: approved, 2.4.x

#9366 Update site-wide-analysis.md
  src/_data/whats-new.yml
Labels: 2.x, Internal Dev, Technical, Progress: approved

#9359 Update site-wide-analysis.md
  src/tools/site-wide-analysis.md
Labels: Editorial, partners-contribution, Progress: acceptance testing, Partner: Rave Digital

#9364 Update custom-filters.md
  src/guides/v2.3/graphql/custom-filters.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9370 Add example of setting default values
  src/guides/v2.4/config-guide/prod/config-reference-systemxml.md
Labels: Progress: acceptance testing

#9371 Updated Commerce application version to 2.4.x to keep relevancy with …
  src/guides/v2.4/install-gde/composer.md
Labels: Editorial, Internal Dev, Progress: approved, 2.4.x
