Repository magento/devdocs, pull requests merged in 2022-01, with the labels that each got.

#9294 Removed duplicate datatype in example of date component
  src/guides/v2.3/ui_comp_guide/components/ui-datecolumn.md
Labels: Editorial, 2.3.x, partners-contribution, Progress: acceptance testing, 2.4.x, Partner: ITG Commerce

#9298 define provider for custom checkout form
  src/guides/v2.3/howdoi/checkout/checkout_form.md
Labels: 2.3.x, Technical, Progress: acceptance testing, 2.4.x

#9301 Update v2.4/security/two-factor-authentication.md
  src/guides/v2.4/security/two-factor-authentication.md
Labels: Editorial, Progress: acceptance testing, 2.4.x

#9303 Remove Unused dependency and wrong Constant
  src/guides/v2.3/howdoi/custom-attributes/text-field.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9304 Fix typo, we should use an alias for parent class
  src/guides/v2.3/extension-dev-guide/admin-grid.md
Labels: Editorial, 2.3.4, Progress: acceptance testing, 2.4.x

#9309 Corrected the broken github url for "Data fixture annotation" documentation
  src/guides/v2.4/test/integration/parameterized_data_fixture.md
Labels: Editorial, Internal Dev, Progress: approved, 2.4.x

#9313 Remove incorrect link for 'domain' term in Domain layer page
  src/guides/v2.3/architecture/archi_perspectives/domain_layer.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9311 Add SCD_MATRIX example for build three themes with three locales and update backend theme name to avoid warning: Theme magento/backend does not exist
  src/cloud/env/variables-build.md
Labels: Technical, partners-contribution, Partner: Krish TechnoLabs, Progress: approved

#9315 Updated Cloud user update behaviour
  src/cloud/project/user-admin.md
Labels: 2.x, Technical, Progress: approved

#9312 Add example for deployment command for deploy only js and only css with parallel processing and different deployment strategy.
  src/guides/v2.4/config-guide/cli/config-cli-subcommands-static-view.md
Labels: Technical, partners-contribution, Partner: Krish TechnoLabs, Progress: acceptance testing, 2.4.x

#9316 Github issue 8304: remove obsolete sample payment module from payment pages
  src/guides/v2.3/payments-integrations/base-integration/integration-intro.md
  src/guides/v2.3/payments-integrations/base-integration/module-configuration.md
Labels: Progress: acceptance testing

#9320 Add elasticsearch details in setup install command
  src/guides/v2.3/install-gde/prereq/nginx.md
  src/guides/v2.4/install-gde/composer.md
Labels: 2.3.x, Technical, partners-contribution, Partner: Krish TechnoLabs, Progress: approved, 2.4.x

#9321 magento/devdocs#9299 Adding additional info to REST configurable product tutorial
  src/guides/v2.3/rest/tutorials/bulk-configurable-product/define-config-product-options.md
Labels: Editorial, 2.3.x, partners-contribution, Partner: Atwix, Progress: approved, 2.4.x

#9325 Fix numbered list incorrect on Create a cache type page
  src/guides/v2.3/extension-dev-guide/cache/partial-caching/create-cache-type.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9329 Update lifecycle-policy.md
  src/release/lifecycle-policy.md
Labels: Major Update, 2.3.x, Progress: review

#9328 Update index.md
  src/release/index.md
Labels: Major Update, 2.3.x, Progress: review, 2.4.x

#9331 Update index.md
  src/release/policy/index.md
Labels: Progress: approved

#9332 Update index.md
  src/release/index.md
Labels: Progress: approved

#9333 Update lifecycle-policy.md
  src/release/lifecycle-policy.md
Labels: Progress: approved

#9334 Remove incorrect content for Dependency injection page
  src/guides/v2.3/extension-dev-guide/depend-inj.md
Labels: Editorial, 2.3.x, Progress: approved, Progress: acceptance testing, 2.4.x

#9335 Refactoring sample code due to current code is obsolete
  src/guides/v2.3/extension-dev-guide/build/di-xml-file.md
Labels: 2.3.x, Technical, Progress: acceptance testing, 2.4.x

#9337 Add missing parameter in enable module command
  src/guides/v2.3/extension-dev-guide/build/module-load-order.md
Labels: Editorial, 2.3.x, Progress: approved, 2.4.x

#9338 Update sample code as current code is obsolete on Cloud pages
  src/cloud/project/ece-tools-upgrade-project.md
  src/cloud/project/project-upgrade.md
Labels: 2.x, Technical, Progress: acceptance testing, Progress: done

#9343 Add Link to REST Api Docs for Condition Types
  src/_data/toc/installation-guide.yml
Labels: partners-contribution, Progress: approved, Partner: Fisheye
