Repository magento/devdocs, pull requests merged in 2022-06, with the labels that each got.

#9455 chore: Set permissions for GitHub actions
  .github/workflows/linter.yml
Labels: Progress: approved

#9448 Missing command for applying changes after dev:query-log command
  src/guides/v2.3/config-guide/cli/logging.md
Labels: Progress: approved

#9442 Cleared a wrong comment regarding path repository support
  src/guides/v2.3/extension-dev-guide/build/composer-integration.md
Labels: Progress: acceptance testing

#9453 Fixing Mutagen typo
  src/cloud/docker/docker-development.md
Labels: partners-contribution, Progress: approved, Partner: Le Site

#9454 Fix internal links in elasticsearch.md
  src/guides/v2.4/install-gde/prereq/elasticsearch.md
Labels: Progress: approved
