Repository magento/devdocs, pull requests merged in 2022-04, with the labels that each got.

#9392 Update unit_test_execution_cli.md
  src/guides/v2.4/test/unit/unit_test_execution_cli.md
Labels: Editorial, Progress: acceptance testing, 2.4.x

#9400 Update unit_test_execution_cli.md
  src/guides/v2.4/test/unit/unit_test_execution_cli.md
Labels: Editorial, 2.3.x, Progress: acceptance testing

#9416 adding in EOS date
  src/release/lifecycle-policy.md
Labels: Internal Dev, Technical, Progress: approved, 2.4.x

#9423 Update variables-deploy.md
  src/cloud/env/variables-deploy.md
Labels: Internal Dev, Technical, Progress: approved

#9421 Update ui-container.md
  src/guides/v2.4/ui_comp_guide/components/ui-container.md
Labels: Editorial, Progress: acceptance testing, 2.4.x

#9424 Changes path of where to save file in email migration topic so it dis…
  src/guides/v2.3/frontend-dev-guide/templates/template-email-migration.md
  src/guides/v2.4/frontend-dev-guide/templates/template-email-migration.md
Labels: Editorial, 2.3.x, Progress: acceptance testing, 2.4.x

#9425 Fixed claimed composer version compatibility with Magento 2.3.7-p3
  src/_data/codebase/v2_3/system-requirements.yml
Labels: Progress: approved
